### ISSUE TITLE
Admin area Headline

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1000]
it shows the whole sitename + admin panel
its tooooo longgggg

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18131269/783f424e-6f92-11e6-98ff-5488cf9d81c1.JPG)

**Comment by RobiNN1** [comment]
Short your sitename, delete domain

**Comment by Catzenjaeger** [comment]
yes i know but a trimlink in code was not bad here or?

**Comment by RobiNN1** [comment]
No on my website show normal

**Comment by meangczac** [comment]
your sitename very long. Use Site Description to host your meta.
