### ISSUE TITLE
Admin theme

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1001]
I'm working on the new admin theme and do not know how to change all .fa icons to PNG icons from administration/images/
My code not working 
`$result = dbquery("SELECT \* FROM ".DB_ADMIN." WHERE admin_page='".$_GET['pagenum']."' ORDER BY admin_title");
  $icons = dbarray($result);

  foreach ($icons as $data) {
    PHPFusion\Admin::getInstance()->setAdminPageIcons($data['admin_rights'], '&lt;img src="'.get_image("ac_".$data['admin_rights']).'" alt="'.$data['admin_title'].'"/>');
  }`
![theme](https://cloud.githubusercontent.com/assets/11664877/18142753/44698ca4-6fbf-11e6-8f42-88fd662dcc95.png)

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/c7b82b5d8c0d6899a31a434df874f3b432237f28

See this line here:

https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/admin_themes/Venus/acp_theme.php#L181

Set this to TRUE, 

and in styles.css find:

https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/admin_themes/Venus/acp_styles.css#L49-L52

Adjust accordingly.
