### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1005]
Too big margin-top and margin-bottom

![setup](https://cloud.githubusercontent.com/assets/11664877/18202741/63da7f0e-7112-11e6-8a0e-6518340a4dd5.png)

**Comment by meangczac** [comment]
What is your Screen Resolution? Browser? Please tell me param so I can view it.

**Comment by RobiNN1** [comment]
1366 x 768

**Comment by meangczac** [comment]
Ok. I'll check it now

**Comment by meangczac** [comment]
Please see latest fix, and see if Nebula register is working ok?

**Comment by meangczac** [comment]
it's the center-x and center-y property at default.css i'm trying to develop on.

**Comment by RobiNN1** [comment]
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18203664/a43a8908-7118-11e6-81ef-27c9525dd945.png)

**Comment by meangczac** [comment]
sync please. :dancers:

**Comment by meangczac** [comment]
@https://github.com/php-fusion/PHP-Fusion/commit/284e2381eeb4442435cdd2d2e2747a3cf5794ed2
