### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1006]
Add my new admin theme to RC5 or not?
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18203841/bda40ac6-7119-11e6-91e8-0dd38308817f.png)

**Comment by meangczac** [comment]
Only coloring change?

**Comment by RobiNN1** [comment]
Theme is designed in Material Design by google.
All components redesignes.
Full responsive.
Later add search bar for all admin pages.

**Comment by meangczac** [comment]
Yes if foundation is different. :+1:
