### ISSUE TITLE
Userfields --> Unable to add column user_shouts-stat with attributes 

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1008]
![ashampoo_snap_2016 09 02_21h10m18s_012_](https://cloud.githubusercontent.com/assets/19621858/18215436/81cfd04c-7151-11e6-9630-07ee0da50148.jpg)

all other module the same!

**Comment by Catzenjaeger** [comment]
Driver/PDOMySQL.php
/site/administration/user_fields.php?aid=77fceea53516dc6c
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-stat' at line 1
Line: 72

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/administration/user_fields.php?aid=77fceea53516dc6c
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-stat' at line 1
Line: 72

**Comment by meangczac** [comment]
Ok, please wait while I develop and clean up Quantum class.

**Comment by meangczac** [comment]
Lets keep this issue open, I need to address this after this. Gonna need to clean Quantum as a standalone solution.

**Comment by meangczac** [comment]
Tested and can integrate.
