### ISSUE TITLE
Error Console - Buttons dosent work

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1009]
button have no function - only over the dropdown i can clear my log

![ashampoo_snap_2016 09 02_21h14m52s_013_](https://cloud.githubusercontent.com/assets/19621858/18215573/22ed47fc-7152-11e6-8e6a-c87db6304170.jpg)

**Comment by meangczac** [comment]
Jquery problem. Please fix the upload as addressed in #1013
