### ISSUE TITLE
Email Templates - mail not send

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1010]
![ashampoo_snap_2016 09 02_21h38m57s_014_](https://cloud.githubusercontent.com/assets/19621858/18216186/9bfd79fc-7155-11e6-8d4c-6e2e1561d810.jpg)

**Comment by meangczac** [comment]
If register is mail sent? Want to know if SMTP mail protocol is defined.

**Comment by Catzenjaeger** [comment]
yup register mails will be send and recieve. I have try it with 2 different accounts

**Comment by Catzenjaeger** [comment]
i have reload complete includes today (for 10 minutes) and replace it and all root data ... nothing some problem.

**Comment by meangczac** [comment]
this issue still remain? I can't test because I'm on localhost without smtp.

**Comment by Catzenjaeger** [comment]
i send you a login to my system so you can watch it online himself.

**Comment by Catzenjaeger** [comment]
email send over php fusion website. --- you got it

**Comment by meangczac** [comment]
Will nail when I'm done with the things at hand.

**Comment by meangczac** [comment]
Can someone with a live server check this issue real quick? My localhost dont have sendmail.

**Comment by JoakimFalk** [comment]
Will test in in laps

**Comment by JoakimFalk** [comment]
PM Confirmed Operational.

**Comment by JoakimFalk** [comment]
Can´t test other two places , they are broken.
Edit, Track Thread only semi broken. 
Tested Template and it works for track threads as well
