### ISSUE TITLE
Wrong Background textfields

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1012]

**Comment by Catzenjaeger** [comment]
![ashampoo_snap_2016 09 02_22h18m00s_017_](https://cloud.githubusercontent.com/assets/19621858/18217056/f3fa66e2-715a-11e6-89c7-79e55fc558e3.jpg)

**Comment by Catzenjaeger** [comment]
its a tiny problem ... when i deactivate it the background is shown!

**Comment by meangczac** [comment]
Did you code the css file or something?

Add in your styles last line.

```
div.mce-edit-area {
    background: #FFF !important;
    filter: none !important;
}
```
