### ISSUE TITLE
New install - Date  entry dosent work now

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1013]
on my older test site the date entry works but in actually version not

![ashampoo_snap_2016 09 02_23h18m07s_018_](https://cloud.githubusercontent.com/assets/19621858/18218557/b7709756-7163-11e6-96d5-7304ba60deb3.jpg)
 no functions

i have try to replace the templates with older but it change not

```
                // Formfield "Figure Pubdate"
                echo "<div id='figure_pubdate-field' class='form-group'>\n";
                    echo "<label class='control-label col-xs-12 col-sm-3 col-md-3 col-lg-3 p-l-0' for='figure_pubdate'>". $locale['figurelib/admin/figurelib.php_047']."</label>\n";
                    echo "<div class='col-xs-12 col-sm-9 col-md-9 col-lg-9'>\n";
                        echo "<div class='input-group date'>\n";
                            echo "<input type='text' name='figure_pubdate' id='figure_pubdate' value='".$data['figure_pubdate']."' class='form-control textbox' placeholder='".$locale['figurelib/admin/figurelib.php_048']."' />\n";
                            echo "<span class='input-group-addon'><i class='entypo calendar'></i></span>\n";
                        echo "</div>\n";
                    echo "</div>\n";
                echo "</div>\n";
```

$('#figure_pubdate-field .input-group.date').datetimepicker({
        showTodayButton: true,
        showClear: true,
        showClose: true,
        allowInputToggle: true,
        format: 'YYYY (MMMM)',
});

**Comment by meangczac** [comment]
Reupload the whole Includes/ Folder EXCEPT Atom, PHPMailer, 
Reupload the theme/templates - admin_layout and layout.php

We upgraded jquery to 3.0 minimum latest in layout.php and admin_layout.php and also upgraded the datepicker's js

**Comment by Catzenjaeger** [comment]
i have all releoad all includes and root data in my fresh PHP F installation ...  but it dosnet work!!!! Only the date entry dosent work all other work.

**Comment by Catzenjaeger** [comment]
sory forget ... the whole file (submit) can you find on my github --> https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/submit.php
