### ISSUE TITLE
Multiple Upload Image vs Mimetype Check

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1014]
this error i get also only in the new phpf version .. 

site/maincore.php
/site/infusions/figurelib/admin.php?aid=ee2c847b05a2d8ba&section=figurelib_form&action=edit&figure_id=1
strlen() expects parameter 1 to be string, array given
Line: 236

`Source code (Line: 226 - 246)
226     
227     $lastvisited = Authenticate::setLastVisitCookie();
228     
229     
230     // Check file types of the uploaded file with known mime types list to prevent uploading unwanted files if enabled
231     if ($settings['mime_check'] == "1") {
232         if (isset($_FILES) && count($_FILES)) {
233             require_once INCLUDES."mimetypes_include.php";
234             $mime_types = mimeTypes();
235             foreach ($_FILES as $each) {
236                 if (isset($each['name']) && strlen($each['tmp_name'])) {`

`Line 236 -- 3 minutes ago
strlen() expects parameter 1 to be string, array given
237                     $file_info = pathinfo($each['name']);
238                     $extension = $file_info['extension'];
239                     if (array_key_exists($extension, $mime_types)) {
240                         if (is_array($mime_types[$extension])) {
241                             $valid_mimetype = FALSE;
242                             foreach ($mime_types[$extension] as $each_mimetype) {
243                                 if ($each_mimetype == $each['type']) {
244                                     $valid_mimetype = TRUE;
245                                     break;
246                                 }
247`

**Comment by meangczac** [comment]
Wierd, I don't get this error. This happen in your figurelib/admin.php or just everywhere?

**Comment by Catzenjaeger** [comment]
i get this never before. on my second Testsite the infusion works without errors. (aliencollectors/test)
only on my fresh installed php f on my general site (aliencollectors/site) i get this error

**Comment by meangczac** [comment]
Paste me the errors screenshot.

**Comment by meangczac** [comment]
Duplicated - https://github.com/php-fusion/PHP-Fusion/issues/1043

**Comment by meangczac** [comment]
According to the bug report, 
````
strlen() expects parameter 1 to be string, array given
Line: 236
````
Is referring to this line here equivalent to version 7.03 --- https://github.com/php-fusion/PHP-Fusion/blob/7.02.07/maincore.php#L55

I'm still trying to fix this part:
--------------------------------------
Array Sample for Multiple Upload Image:

````
Array
(
    [files_input] => Array
        (
            [name] => Array
                (
                    [0] => addonverify.jpg // is original .php file
                    [1] => album_default.jpg
                    [2] => trojan_horse.jpg // Is original .exe file
                )

            [type] => Array
                (
                    [0] => image/jpeg
                    [1] => image/jpeg
                    [2] => image/jpeg
                )

            [tmp_name] => Array
                (
                    [0] => C:\Users\meang\AppData\Local\Temp\phpD76C.tmp
                    [1] => C:\Users\meang\AppData\Local\Temp\phpD78C.tmp
                    [2] => C:\Users\meang\AppData\Local\Temp\phpD78D.tmp
                )

            [error] => Array
                (
                    [0] => 0
                    [1] => 0
                    [2] => 0
                )

            [size] => Array
                (
                    [0] => 19859
                    [1] => 149468
                    [2] => 80016
                )

        )

)
````
