### ISSUE TITLE
Tiny/Textfield

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1015]
wrong sign inside

![ashampoo_snap_2016 09 03_12h50m38s_019_](https://cloud.githubusercontent.com/assets/19621858/18224423/defd8c4a-71d4-11e6-854e-910c0e71275d.jpg)

my code from my submit
`// Formfield "Description"
                echo form_textarea("figure_description", $locale['figurelib/admin/figurelib.php_061'], $data['figure_description'], [
                    "type"      => fusion_get_settings("tinymce_enabled") ? "tinymce" : "html",
                    "tinymce"   => fusion_get_settings("tinymce_enabled") && iADMIN ? "advanced" : "simple",
                    #"autosize"  => true,
                    "required"  => false,
                    "form_name" => "inputform"
                ]);`

**Comment by meangczac** [comment]
Wait i check plugin how to disable. Need to see TinyMCE config

**Comment by meangczac** [comment]
http://stackoverflow.com/questions/17376595/how-can-i-remove-p-tags-that-are-auto-added-within-tinymce

**Comment by meangczac** [comment]
This is a tinyMCE issue. Since we integrating, and there are method to disable, i will add the API since requested.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/88f61e74e0eb5c7da3aa63d2736358e2d365ec9b

**Comment by Catzenjaeger** [comment]
i have replace the file with new but the error is still aviable. Wrong background and P sign
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18302087/f29cfab6-74d5-11e6-854a-7705a8721178.JPG)

**Comment by RobiNN1** [comment]
in css add white bg for teaxtarea
P tag is not bug https://www.tinymce.com/docs/demo/basic-example/

**Comment by Catzenjaeger** [comment]
sorry I do not understand you. You can not close everything and  say this is not a fault or this only by me ... These are not solutions! I have no Custom PHPF but a fresh install. You have to find the fault in the system. There is the error. I am Tiny activated, and get this view .. this is not normal!

**Comment by Catzenjaeger** [comment]
ah and i forget i use bootstrap theme ... no custom themes or old themes
p tag is a bug and Frederick have try to solved it but i get it again!

**Comment by meangczac** [comment]
I got the `p`  tag solution done for TinyMCE text area already in Github. Catz, it's on your server as well.

Add this option for textarea  in your code.

https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/dynamics/includes/form_textarea.php#L45

```
$options = array(
'tinymce_forced_root' => TRUE
//'required' => TRUE/FALSE, etc.
);
```

**Comment by Catzenjaeger** [comment]
Catz, it's on your server as well. --> yea but when i activate my tiny i get this wrong background .. guess here is a bug somewhere nor. At the moment i use the tiny not well i gt the P and background problem.

**Comment by meangczac** [comment]
Is the `<p>` doing the problem or its just TinyMCE?

**Comment by Catzenjaeger** [comment]
ok last update: 

i have change in dynamic 
this --> 'tinymce_forced_root' => FALSE
to this -->  'tinymce_forced_root' => TRUE

no its looks good on normal submit site but in my admin area i get this:
![1](https://cloud.githubusercontent.com/assets/19621858/18346882/eb39d7e2-75c2-11e6-8d35-5f7346702777.JPG)
![2](https://cloud.githubusercontent.com/assets/19621858/18346891/f8d7f532-75c2-11e6-99d4-5febfc35bed7.JPG)

i see a sign but have no letters in my entry
and i have a wrong background

**Comment by Catzenjaeger** [comment]
counter dosent work on bootom of this textfield!
![3](https://cloud.githubusercontent.com/assets/19621858/18346971/50afb8da-75c3-11e6-8810-84020f923c68.JPG)
