### ISSUE TITLE
Bootstrap - missing parts on some sites

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1017]
![ashampoo_snap_2016 09 03_15h11m36s_023_](https://cloud.githubusercontent.com/assets/19621858/18224992/b54e9aa6-71e8-11e6-8e32-ca62115b6088.jpg)

![ashampoo_snap_2016 09 03_15h12m25s_026_](https://cloud.githubusercontent.com/assets/19621858/18224993/b7e8559a-71e8-11e6-8b77-cc2d9a1a3338.jpg)

**Comment by Catzenjaeger** [comment]
i have try to upload with newest github files but same error.

**Comment by Catzenjaeger** [comment]
![ashampoo_snap_2016 09 03_15h18m19s_027_](https://cloud.githubusercontent.com/assets/19621858/18225022/7a2b283a-71e9-11e6-940c-e035072e1850.jpg)

i have use the brandnew github files. I have install my system on 14:50 german time and update 2 times with newest files

**Comment by Catzenjaeger** [comment]
when i resize my site with strg + mouse then i see the rest of site.

**Comment by Catzenjaeger** [comment]
bootstrap problem ... Artemis works

**Comment by RobiNN1** [comment]
Fixed 
https://github.com/php-fusion/PHP-Fusion/commit/dbf8bcf37d4e312525b7124baf33bacd6d6a5a2e
