### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1018]
somme errors

1.) no placeholder/default album image
2.) i see php code when i rating as result :)

![ashampoo_snap_2016 09 03_17h56m02s_028_](https://cloud.githubusercontent.com/assets/19621858/18225936/d656156e-71ff-11e6-9a8f-8776596e7eae.jpg)
![ashampoo_snap_2016 09 03_17h57m59s_029_](https://cloud.githubusercontent.com/assets/19621858/18225938/d867744c-71ff-11e6-8ec4-f7f6f7e34d75.jpg)

**Comment by meangczac** [comment]
I'm trying to do jquery.. wait.
