### ISSUE TITLE
Forum - Forum Ranks goes to home site

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1023]
i see the correct link with fr at end but when i click i go to home .. always

**Comment by Catzenjaeger** [comment]
i found some more buttons waht bring me to home site too:

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18240315/2d2cc74c-734b-11e6-9cb8-131480226583.JPG)

**Comment by Catzenjaeger** [comment]
error is still present. 
this sites go to home.php 
-->      Home Admin Dashboard Content Admin Forum Index Forum Management --> Forum Ranks
-->      Home Admin Dashboard User Admin --> User Fields

**Comment by RobiNN1** [comment]
working

**Comment by RobiNN1** [comment]
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18254868/bf6925c2-73a2-11e6-94ea-3bb532bd9a9a.png)

Everything works, clear the cache in web browser
