### ISSUE TITLE
BreadCrumbs bug

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1024]
Breadcrumbs display duplicate links
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18233368/eeaa7128-72e5-11e6-8e6b-eb07bec43971.png)

**Comment by meangczac** [comment]
Breadcrumb has no bugs, somewhere has added double add_breadcrumb()

**Comment by RobiNN1** [comment]
In my theme added only one render_breadcrumbs()

**Comment by meangczac** [comment]
no, it's the add that has problem, not the render. there are somewhere mis-add double breadcrumb?

**Comment by RobiNN1** [comment]
No.
This problem is also in the Artemis

**Comment by meangczac** [comment]
Yes, found the issue. Fixed. Construct run double.
