### ISSUE TITLE
latest comments panel - no content

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1025]
my panel is empty but i have comments

![ashampoo_snap_2016 09 04_21h37m00s_032_](https://cloud.githubusercontent.com/assets/19621858/18233430/7d2be926-72e7-11e6-8912-14f94fe547cc.jpg)
!

![ashampoo_snap_2016 09 04_21h37m19s_033_](https://cloud.githubusercontent.com/assets/19621858/18233431/82a138c0-72e7-11e6-84d3-c3d79f1fe3ad.jpg)

**Comment by meangczac** [comment]
Please wait.... comment overhaulling.
