### ISSUE TITLE
Suggest:  News Source Field in news/articles eg.

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1029]
I would suggest a field insert what show the news source  in URL or text format. 
In today's time due to copyright and warnings of lawyers very important.

**Comment by meangczac** [comment]
If you copy from some website, just add "News Source... from <a href=''>some site</a>" in news extended field...  

We have been through this earlier on with the forum. The answer of the discussion was, I remember as: 

Add fields that has functional values, not text values. lol

**Comment by Catzenjaeger** [comment]
:( so i have to mod it for me private again (some of my other sites i have this feature but for version 7 !). 
I trough this is a good feature.
