### ISSUE TITLE
Forum: Undefined index: thread_tags

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1030]
threads/view.php
/live/infusions/forum/viewthread.php?action=edit&forum_id=19&thread_id=2&post_id=2
Undefined index: thread_tags
Line: 527

**Comment by FrederickChan** [comment]
Reinstall Forum.

**Comment by meangczac** [comment]
I'm running on latest git. New install now checking this. No errors on my side, did you reinstall forum since the major upgrade?

**Comment by Catzenjaeger** [comment]
oh nooo i have create all my forums and now i have to reinstall? ;(
 i have download yesterday the last version around 15:00 german time and install it

**Comment by meangczac** [comment]
You can run SQL...

**Comment by meangczac** [comment]
Can without reinstall. See the tables in the infusion. Add manually the column

**Comment by Catzenjaeger** [comment]
ok .. I have no choice :(

**Comment by meangczac** [comment]
You're not gonna regret anyway..  got Like button. And also Tagging filters. The tables are necessary for future when new codes update.
