### ISSUE TITLE
 Database/Driver/PDOMySQL.php - Syntax error or access violation:

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1031]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
Line: 72 File -- Database/Driver/PDOMySQL.php

i have install cookie control vers 2. infusion. In my older Fusion 9 versions it had works without errors and notices

**Comment by meangczac** [comment]
This error means, there are typo in your query.
