### ISSUE TITLE
Form Errors - field lengh (witdh)

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1033]
i  all my forms have the fields not the same length
i use for all fields width: "width"       => "520px", so that is looks good

look here -- all 520 but it look so:
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18248030/6b3ca1a8-7376-11e6-9595-e17452d7ce8c.JPG)

its new .. was not on older versions!

**Comment by RobiNN1** [comment]
add this style 
`add_to_head('<style type="text/css">.select2-container, .form-control {width: 520px!important;}</style>');`

**Comment by Catzenjaeger** [comment]
have add this on top of my file .. but nothing

**Comment by RobiNN1** [comment]
after maincore.php ?

**Comment by Catzenjaeger** [comment]
yup after language settings

**Comment by Catzenjaeger** [comment]
```
`if (!defined("IN_FUSION")) {
    die("Access Denied");
}

pageAccess("FI");
global $figurelibSettings;
$formEdit = false;

// LANGUAGE
if (file_exists(INFUSIONS."figurelib/locale/".LOCALESET."locale_figurelib.php")) {
    include INFUSIONS."figurelib/locale/".LOCALESET."locale_figurelib.php";
} else {
    include INFUSIONS."figurelib/locale/English/locale_figurelib.php";
}

if (file_exists(LOCALE.LOCALESET."admin/settings.php")) {
    include LOCALE.LOCALESET."admin/settings.php";
} else {
    include LOCALE."English/admin/settings.php";
}

add_to_head('<style type="text/css">.select2-container, .from-control {width: 520px!important;}</style>');`
```

**Comment by Catzenjaeger** [comment]
this is new .. in my older php f 9 installations was all ok and all field inline and had the same lengh
i use bootstrap!!!!!
its a text-field problem ... dropdowns are 520 width thats correct
dont forget fix the datapicker .. he dosent works too!

**Comment by RobiNN1** [comment]
your width not working on input or select?

**Comment by Catzenjaeger** [comment]
i use bootstrap!!!!!
its a text-field problem ... dropdowns are 520 width thats correct but all my textfields are looooonnnnnnnggg
dont forget fix the datapicker .. he dosent works too!

**Comment by Catzenjaeger** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18248533/0e2b7126-7379-11e6-84f9-c11caa48267f.JPG)

this is my code as example:

`// Formfield "Figure Title"
    echo form_text("figure_title", $locale['figurelib/admin/figurelib.php_004'], $data['figure_title'], [
        "placeholder" => $locale['figurelib/admin/figurelib.php_005'],
        "error_text"  => $locale['figurelib/admin/figurelib.php_006'],
        "inline"      => true,
        "width"       => "520px",
        "required"    => true
    ]);
`

**Comment by RobiNN1** [comment]
`add_to_head('<style type="text/css">.form-group .form-control {width: 520px!important;}</style>');`

**Comment by Catzenjaeger** [comment]
but normally i have not add this line. earlier it was never so! 
Have you change something in bootstrap theme?

and this will be forever ignored? --> "width" => "520px",
not the perfect solution guess its bootstrap problem

**Comment by RobiNN1** [comment]
use bootstrap grid system
http://getbootstrap.com/css/#grid

**Comment by Catzenjaeger** [comment]
LOL you have never look inside my files right? its all in bootstrap --> https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/admin/admin_figurelib.php

**Comment by Catzenjaeger** [comment]
here the same -- witdh will be ignored by system

```
    // Formfield "Figure Usedprice"
    echo form_text("figure_usedprice", $locale['figurelib/admin/figurelib.php_052'], $data['figure_usedprice'], [
        "placeholder"   => $locale['figurelib/admin/figurelib.php_053'],
        "inline"        => true,
        "width"       => "500px",
        "min"           => 0,
        "prepend_value" => "&#036;",
        "type"          => "number"
    ]);
```

in old version this wasent

**Comment by RobiNN1** [comment]
OK, download your infusion and test it on my server

**Comment by meangczac** [comment]
Make a quick replace. 

$options = array(
'width' => '520px', 
);

to:

$options = array(
'inner_width' => '520px',
);

This is latest change. Please CTRL+Replace full Infusion.

If no change, $options['stacked'] = form_text(); will not work good..

See Nebula Theme Articles header to know what I mean, I tested hours to get it working. Width is a mistake from the beginning. It's Inner Width, while with is 100% so you can stack things inline.

**Comment by meangczac** [comment]
Please go through the commits before you update your files.. Read this commit. https://github.com/php-fusion/PHP-Fusion/commit/69f5bc3ce65bb94a5a79e4260dd1244550f7063d
