### ISSUE TITLE
Massive errors - fresh install

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1036]
so i have  download the newest version 18:00 german time and installed now (18:30)

this is my main setting:

![ashampoo_snap_2016 09 05_18h28m52s_002_](https://cloud.githubusercontent.com/assets/19621858/18253617/81e485fe-7396-11e6-8214-fcac7c60afd7.jpg)

i guess here is a massive problem.
As try i have installed it 2 times on different folders  (Test and Site) both identical .. same errors

**Comment by RobiNN1** [comment]
Please wait https://github.com/php-fusion/PHP-Fusion/commit/45a6e27b9b2f4a4f1efa5cb0559ed5f794f108a2

**Comment by Catzenjaeger** [comment]
![ashampoo_snap_2016 09 05_18h35m44s_003_](https://cloud.githubusercontent.com/assets/19621858/18253721/53b5971c-7397-11e6-9f2f-c60990150b56.jpg)

**Comment by RobiNN1** [comment]
In  includes/dynamics/includes/form_textarea.php
Find line 381 and replace to `$html .= ($options['type'] == "bbcode" || $options['type'] == "html") && $options['wordcount'] == TRUE ? "</div>\n" : "";`

**Comment by Catzenjaeger** [comment]
the gitfile is 3 hours old? you have not fix it? confused

https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/dynamics/includes/form_textarea.php

my download and install was for some minutes!

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/29018b034da87d32acc22ec0af75754c53f4931b

**Comment by Catzenjaeger** [comment]
ok this fix this problem thanx

**Comment by Catzenjaeger** [comment]
another site wrong (security site in admin area)

![ashampoo_snap_2016 09 05_19h36m34s_006_](https://cloud.githubusercontent.com/assets/19621858/18254623/d0999a00-739f-11e6-832a-023df4cfff6d.jpg)

**Comment by Catzenjaeger** [comment]
here in security settings site i count 25 div .. we must have 26 for correct code :) 
find them :)
