### ISSUE TITLE
user_fields.php 

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1037]
![ashampoo_snap_2016 09 05_18h48m31s_004_](https://cloud.githubusercontent.com/assets/19621858/18253932/165b19f8-7399-11e6-8cd2-2f7ce7a1e1ae.jpg)

**Comment by RobiNN1** [comment]
#1036

**Comment by Catzenjaeger** [comment]
no no error is still present !

**Comment by Catzenjaeger** [comment]
i have replace both dynamics files ... user_fields is solved but not this site

**Comment by RobiNN1** [comment]
Not working for all files, please wait for next updates.

**Comment by meangczac** [comment]
this is working on my new install.
