### ISSUE TITLE
Missing input types in DYNAMICS/includes/form_text.php

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1040]
in moment i found in DYNAMICS/includes/form_text.php

```
  switch ($options['type']) {
        case "number":
            $input_type = "number";
            break;
        case "text":
            $input_type = "text";
            break;
        case "password":
            $input_type = "password";
            break;
        default:
            $input_type = "text";
```

**HTML5 added several new input types:**
-     color
-     date
-     datetime
-     datetime-local
-     email
-     month
-     number
-     range
-     search
-     tel
-     time
-     url
-     week

Source: http://www.w3schools.com/html/html_form_input_types.asp

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/9f13fd41f7d9e528bb5e2b2918340e05052aa48b

**Comment by meangczac** [comment]
Good one there, and let's reopen this issue so we can work on the validation rules over time.

**Comment by meangczac** [comment]
Move to milestone.
