### ISSUE TITLE
Email count 1 = email inbox = 0

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1042]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18339768/b442bb9e-75a1-11e6-8242-332d8741d849.JPG)

was a email send by a indusion. Data was in DB too but i dont see anyone on page

**Comment by meangczac** [comment]
uh. how you send?

send_pm() function.

**Comment by Catzenjaeger** [comment]
it cames from a infusion what i try (video pro) - think well its a old infusion so that makes errors or is not compatible but have a eye on it :)

**Comment by Catzenjaeger** [comment]
i have delete the db entrie via hand

**Comment by meangczac** [comment]
show me the send_pm function of the video infusion pro.

if the author did not use that function to send the pm, implement the send_pm() function. it exists even in version 7.

**Comment by meangczac** [comment]
i got a problem in defender token again, for the how many nth time!  sigh.

**Comment by meangczac** [comment]
Is this still problematic?

**Comment by Catzenjaeger** [comment]
here i have count on send of "1" but when i click on it i have see none

![ashampoo_snap_2016 10 14_20h43m37s_003_](https://cloud.githubusercontent.com/assets/19621858/19398876/ef83aff0-924e-11e6-91a2-f8dbd03f87d9.jpg)

message table in my databse
![ashampoo_snap_2016 10 14_20h49m14s_005_](https://cloud.githubusercontent.com/assets/19621858/19399000/9ae163f6-924f-11e6-852c-f08ce239d25b.jpg)

**Comment by meangczac** [comment]
k

**Comment by karrak1** [comment]
count all the messages, it is not how much you are reading

**Comment by karrak1** [comment]
add a fix
