### ISSUE TITLE
strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1043]
i have patch my maincore with newest but this errors cames again.
Can you take a look plz? 

live/maincore.php
/live/infusions/figurelib/admin.php?aid=e45dcab2f5db75e1&section=figurelib_form&action=edit&figure_id=16
pathinfo() expects parameter 1 to be string, array given
Line: 237

https://github.com/Catzenjaeger/FigureLib_4/issues/103

**Comment by meangczac** [comment]
Man, why so wierd.. oh Multiple upload?

I can't seem to get it yet, wait when i run debug test phase, I'll get it done. Can you do me a favor....

go to your admin > settings tab > miscellaneous settings page. 
Check for "Mimetype" upload - disable it.

**Comment by Catzenjaeger** [comment]
i edit a figure and when i save comes this error. Its never mind what i change the error comes always. also when i change a name or whatever

/infusions/figurelib/admin.php?aid=7fa4a25xxxxxxx&section=figurelib_form&action=edit&figure_id=10

**Comment by meangczac** [comment]
See my edited answer. Wait for me to produce the error my end and I will fix that. We keep this issue open. but you're in a rush, so disable the check.

**Comment by Catzenjaeger** [comment]
ok i have try it and the error came not :)

**Comment by meangczac** [comment]
Ok, so wait for me to fix it so you can get extra value out of v9
