### ISSUE TITLE
textbox problem

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1044]
have this:

```
echo "<div class='col-lg-4 col-md-4 col-sm-12 col-xs-12'>\n";
echo "<div class='navbar-default'><div class='text-smaller text-uppercase'><strong>".$locale['figure_457']."</strong>\n";
echo "</div></div></div>\n";                                    

echo "<div class='col-lg-8 col-md-8 col-sm-12 col-xs-12'>\n";
echo "<span class='small' style='word-break: break-all; word-wrap: break-word;'>".($data['figure_accessories'] ? $data['figure_accessories'] : "-")."&nbsp;</span>\n";      
cho "</div>\n";
```

and get this: 
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18348589/7bc7c28e-75cc-11e6-81b4-4d9cee56c709.JPG)

guess its our text-box problem in dynamics ... or?

i have add the newest file from git here and replace it with mine old.
- [ ] p Problem = yes
- [ ] backgrund problem = yes

actual image with tiny activated:
![1212](https://cloud.githubusercontent.com/assets/19621858/18349816/47259c8e-75d3-11e6-827d-f50219073797.JPG)

**Comment by meangczac** [comment]
see parse_textarea() to format text boxes.

**Comment by Catzenjaeger** [comment]
thanx solved this problem
