### ISSUE TITLE
Server Performance

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1045]
PHP 5.6, Opcache On. Page is viewpage.php?page_id=1 on clean install.

![image](https://cloud.githubusercontent.com/assets/4078041/18348679/5bd9f662-75ff-11e6-8268-edaae7fff1e3.png)

Now that is power. Without OPCache it's 0.23ms, with OPCache it's 0.05ms. 4 times faster.

**Comment by meangczac** [comment]
Please give your online server stats if possible. I want to run benchmark and further optimise codes if possible.

**Comment by RobiNN1** [comment]
Render time: 0.34560 seconds | Average: 0.32390 (-0.0758) seconds | Queries: 51 | Memory used: 4.21MB/4MB

Wtih OPC

Render time: 0.15986 seconds | Average: 0.24006 (-0.06744) seconds | Queries: 51 | Memory used: 951.7kB/2MB

**Comment by meangczac** [comment]
Ok. The slow down mass is in the header includes. We should minify all sources later so it loads faster

**Comment by meangczac** [comment]
JS files are the one flowing slowly. Once we minify them codes, all should be fine. 

Under half a second is still very good even for Development. 

I remember PHP-Fusion 8 with just prototype Theme Engine....  2.86 seconds.  lol

My thoughts are, we're good to go. Should we prove slower than acceptable, I will reopen this ticket.

@RobiNN1 , great job there.

Cheers guys.
