### ISSUE TITLE
templates/news.php --> Undefined index: news_last_updated

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1048]
templates/news.php
/live/infusions/news/news.php
Undefined index: news_last_updated
Line: 116

> Problem comes when i delete all my news

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18386357/dd5b719c-7696-11e6-8830-bdba122de483.JPG)

**Comment by meangczac** [comment]
When you delete ALL your news... then no news, then what's wrong no information?

**Comment by meangczac** [comment]
Oh ok isset errors. Will fix.

**Comment by Catzenjaeger** [comment]
LOL Fredercik .. you should read my post completly :)

--> i get an error then i delete all news --> Undefined index: news_last_updated

**Comment by meangczac** [comment]
Yes. Too much things to do.. very fast skim through, very fast check code, very fast solved. Next.. but what is most important - solve 👍
