### ISSUE TITLE
Unable to create Photo Albums at all - PDO Crash

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#105]
Can not create Photo Albums at all ( PDO Enabled )
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fusion7yG59_photo_albums' at line 1' in includes/temp_dbhandler/pdo_functions_include.php:154 Stack trace: #0 includes/temp_dbhandler/pdo_functions_include.php(154): PDO->prepare('SHOW TABLE STAT...') #1 /home/nextphpf/public_html/RC7/infusions/gallery/classes/Admin.php(479): dbnextid('fusion7yG59_pho...') #2 /home/nextphpf/public_html/RC7/infusions/gallery/classes/Admin.php(190): PHPFusion\Gallery\Admin->set_albumDB() #3 /home/nextphpf/public_html/RC7/infusions/gallery/gallery_admin.php(60): PHPFusion\Gallery\Admin->boot() #4 {main} thrown in /home/nextphpf/public_html/RC7/includes/temp_dbhandler/pdo_functions_include.php on line 154

**Comment by JoakimFalk** [comment]
After the restore of the DatabaseFactory it works again.
