### ISSUE TITLE
Forum - no redirect after delete

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1050]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18386439/6aeabf0e-7697-11e6-974a-9246e433ad19.JPG)

**Comment by Catzenjaeger** [comment]
plus ... the link goes wrong
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18386468/a9fcb09e-7697-11e6-8cf6-2ce50195e5bd.JPG)
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18386481/c6ddcb62-7697-11e6-9f9a-97a0093c0b5f.JPG)

thread is still available!!!!

**Comment by meangczac** [comment]
Please try again, I tested after the past fixes, it's OK.
