### ISSUE TITLE
Forum - last post info wrong

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1051]
when i delete a post and this was the last it will show always on overview

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18386548/0a8e64e8-7698-11e6-883b-dec0de2b6cdf.JPG)

klick on it goes to wrong site or in the forum overview

**Comment by meangczac** [comment]
Yes, i detect some errors in using forum_threadcount = forum_threadcount-1 so, i make sure to refresh to a fresh state using a dbcount.  Screw performance, most important is stability. I'll git in a moment.

**Comment by meangczac** [comment]
If you have any more issues. Please reopen this issue.
