### ISSUE TITLE
Feedback/Comments.php --> Undefined index: comment_type

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1052]
Feedback/Comments.php
/live/infusions/figurelib/figures.php?figure_id=21
Undefined index: comment_type
Line: 226

```
Source code (Line: 216 - 236)
216                             require_once INCLUDES."flood_include.php";
217     
218                             if (!flood_control("comment_datestamp", DB_COMMENTS, "comment_ip='".USER_IP."'")) {
219     
220                                 dbquery_insert(DB_COMMENTS, $comment_data, 'save');
221     
222                                 $id = dblastid();
223     
224                                 if ($this->settings['comments_sorting'] == "ASC") {
225                                     $c_count = dbcount("(comment_id)", DB_COMMENTS,
226                                                        "comment_item_id='".$this->comment_params['comment_item_id']."' AND
                                                       comment_type='".$this->comment_params['comment_type']."'");
Line 226 -- 20 seconds ago
```

**Comment by meangczac** [comment]
What did you do to get this error? Edit a comment and post edit?

**Comment by Catzenjaeger** [comment]
LOOK HERE: http://aliencollectors.com/live/infusions/figurelib/figures.php?figure_id=21
site is destroyed if i have a comment

if not it look so: http://aliencollectors.com/live/infusions/figurelib/figures.php?figure_id=15

**Comment by Catzenjaeger** [comment]
my figurelib panel dosent work anymore . think many is not working after last updates :(
forum dosnet work
admin area dosent work

i test it again ... after i make a comment and push save the site will destroyed

**Comment by Catzenjaeger** [comment]
yup test again ... after i make a comment and push save the site will destroyed

**Comment by meangczac** [comment]
System files were not properly updated. Solved now.
