### ISSUE TITLE
JS - All Pages - Uncaught SyntaxError: Unexpected token if

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1055]
Something went wrong Robin.

Please check your latest git js stuff. It's crashing all my work at the moment. Minify?

**Comment by meangczac** [comment]
I'll stop my js work for now until issue resolved :)

**Comment by RobiNN1** [comment]
The problem is in this code
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18410971/11efdc0e-776e-11e6-900c-9badd1558c58.png)

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/f137f1b3e3f4909f3a8026c15b4277eb48467bac, https://github.com/php-fusion/PHP-Fusion/commit/72480ef1f771c2e0dabae1e64538da068e4da58f

**Comment by meangczac** [comment]
Great work. :+1:
