### ISSUE TITLE
fresh intall - no custom pages possible

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1057]
error message "Unable to retrieve page content."

**Comment by RobiNN1** [comment]
Error is on viewpage.php?page_id=1 or viewpage.php

**Comment by Catzenjaeger** [comment]
overall - i cant show or preview it .. nothing all the some message

**Comment by Catzenjaeger** [comment]
http://aliencollectors.com/site/viewpage.php?page_id=1

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/3fb78390be462b26050a01c61377cb5b37f0d41d

added code

**Comment by Catzenjaeger** [comment]
i install new again (today zum hundersten male man) and try it later but my focus is that i can start with my site in 3 days .. but guess its fantastic :(

**Comment by RobiNN1** [comment]
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18412980/74c1384a-779c-11e6-970d-528dccd1a548.png)
all working

**Comment by FrederickChan** [comment]
The way you do it is wrong. Use another database, install fresh table. After that, re-import back data. You are keeping your data and preventing fresh install. That's why you keep losing track of the core table changes.

Page Composer is RC5. RC5 is no where near half complete. We still got much issues to tackle at this moment.

**Comment by meangczac** [comment]
Fresh install is to kill off the table, start blank. Please do it on a new DB.

**Comment by Catzenjaeger** [comment]
Frederick i have 4 folders with 4 databases. Normaly i change all files what you fix and changee it on my space but often it will more destroy than repair.

i dont know waht i do wrong.

**Comment by meangczac** [comment]
I uploaded a custom maincore.php with show server errors.

First, your admin - Fatal error: Class 'PHPFusion\Locale' not found in /var/www/vhosts/aliencollectors.com/httpdocs/live/includes/translate_include.php on line 23

Are you sure you have uploaded all files when sync. Regardless, I will fix your site. I'll use one hour.

**Comment by meangczac** [comment]
http://aliencollectors.com/live/viewpage.php?page_id=3&c_start=0#c4

Custom page, comments tested. Working.

I'm going to upload latest composer files for your final sync.

Your forum is also not up to date. I'm going to upload the full forum infusion.

**Comment by Catzenjaeger** [comment]
no stop please ... my actuall installing is here unter /side

**Comment by meangczac** [comment]
Hmm. Please take the files from your /live/ server. Replace the files until everything is correctly functioning like /live/
