### ISSUE TITLE
Forum --> templates/forum_input.php -->  Undefined index: tags_field

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1059]
templates/forum_input.php
/site/infusions/forum/viewthread.php?action=reply&forum_id=1&thread_id=1
Undefined index: tags_field

threads/poll.php
/site/infusions/forum/viewthread.php?action=deletepoll&forum_id=1&thread_id=2
Undefined index: post_id
Line: 379

Notice to Frederick: this file are on /live and /site the same - also a older notice! ( i compare always now all files with live and site) /live = your checked version / /site = my new installation from for 10 hours

**Comment by Catzenjaeger** [comment]
threads/view.php
/site/infusions/forum/viewthread.php?action=edit&forum_id=2&thread_id=3&post_id=3
Undefined index: thread_tags

**Comment by meangczac** [comment]
Your forum need latest version with thread_tags

![capture](https://cloud.githubusercontent.com/assets/4078041/18733973/47ab8ad6-80a2-11e6-9d9a-d60b2fa134b1.JPG)

**Comment by UnrealCatze** [comment]
OMG and now? i cant reinstall my forum ... patch? can you give me the right sql code to add this line and settings? 

only the table forums or more?

thats my forum atm
![unbenannt](https://cloud.githubusercontent.com/assets/22166864/18739044/1dcf444c-80a1-11e6-8a94-95b2086242c6.JPG)

**Comment by UnrealCatze** [comment]
omg i have download the last git here and its not include?   i have doenload and infuse forum new but i miss this rows again!!! What happen?

**Comment by RobiNN1** [comment]
Problem is not in database
New install 

F:\xampp\htdocs\PHP-Fusion\infusions\forum\templates\forum_input.php
/infusions/forum/viewthread.php?action=reply&forum_id=1&thread_id=1
Undefined index: tags_field
Line: 37

![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/19013180/b2f3e378-87c9-11e6-828f-e231ec86ce0b.png)

**Comment by meangczac** [comment]
Have an isset check or empty check to get rid of that error.

https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/forum/templates/forum_input.php#L37

tags_field is a form_select, and only happen when you create new thread. when someone reply, they should not be able to change tags as the DB that is referred during reply is DB_FORUM_POST which doesn't have tags related column.

**Comment by FrederickChan** [comment]
Upgrade the site links to have an publish/unpublish. It is very tiring to keep adding and deleting.
