### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#106]
Forum Images are not being uploaded / saved, 0 errors

**Comment by rimelek** [comment]
The image is uploaded but not into the right folder. You can find the uploaded images under "images/". They should be under "images/forum/".

**Comment by rimelek** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/b111b7d65724b368dbf3b3925d2ccfb8015aa11f

the option's value was uplaod_path instead of upload_path
