### ISSUE TITLE
Forum - no/missing warning message

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1060]
when i delete a forum entry no message warning will comes. its dangerous :) 

![ashampoo_snap_2016 09 11_12h14m55s_004_](https://cloud.githubusercontent.com/assets/19621858/18416606/7062b9a4-7819-11e6-9b76-d17c8f8abedc.jpg)

**Comment by meangczac** [comment]
Should have Javascript pop up?

**Comment by meangczac** [comment]
Maybe you checked "[] Do not show these messages again" in the browser. lol
