### ISSUE TITLE
Avatar not shown

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1062]
i have add a avatar and see this in my profile but not in the sidepanel? i fo`rget to action something or error

**Comment by meangczac** [comment]
$userdata = fusion_get_userdata();
echo display_avatar($userdata, '50px');

**Comment by UnrealCatze** [comment]
avators will be not shown .. never mind what size.
i see my uploaded avatar in my profile but not in panels on the startsite (user profil box)

**Comment by RobiNN1** [comment]
Your avatar must be no bigger than 100x100 pixels.
