### ISSUE TITLE
Idea: Admin password

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1063]
when i add a Admin and he goes to admin area a login screen is shown  ... but no message that he have forget to set a password for this area.  When he try now to log in with normal passwort comes only a error password wrong

**Comment by meangczac** [comment]
Drop a note that his password is blank and please tell him to set a password?  Sure. Will do..
But I can't test now because I don't install PHP-Fusion yet.... for 1 week. I'm coding installer / upgrade 2.

**Comment by meangczac** [comment]
Jocke also added to this, have an iADMIN Check in Admin Panel Login page.

**Comment by karrak1** [comment]
corrected

**Comment by meangczac** [comment]
This is a very nice fix. 

Closing.
