### ISSUE TITLE
templates/forum_main.php --> Undefined index: item

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1066]
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=13&parent_id=0
Undefined index: item
Line: 231

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=12&parent_id=0
Undefined index: item
Line: 231

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=11&parent_id=0
Undefined index: item
Line: 231

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=10&parent_id=0
Undefined index: item
Line: 231

**Comment by Catzenjaeger** [comment]
some more now

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&type=attachments&sort=view
Undefined index: forum_name
Line: 236
2 minutes ago  
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&type=attachments&sort=view
Undefined index: forum_description
Line: 237
2 minutes ago  
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&type=attachments&sort=view
Undefined index: forum_rules
Line: 248
2 minutes ago  
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&type=attachments&sort=time
Undefined index: forum_name
Line: 236

**Comment by meangczac** [comment]
Ok.

**Comment by Catzenjaeger** [comment]
i have open my site today morning and get 13 sites!!!! with error notices in my log ... all some like that
i have not changes make -- and i have sleep for 6 horus :) LOL

think here is a massive problem

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&type=unsolved
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&type=solved
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&type=poll
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&type=discussions
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&type=attachments
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&type=all
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&time=today
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&time=6month
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&time=3month
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&time=2week
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&time=2month
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&time=2days
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=0&time=1year
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=6&parent_id=0&sort=view
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=6&parent_id=0&sort=time
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=6&parent_id=0&sort=subject
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=6&parent_id=0&sort=reply
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=6&parent_id=0&sort=author
Undefined index: item
Line: 231
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=unsolved
Undefined index: forum_name
Line: 236
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=unsolved
Undefined index: forum_description
Line: 237
6 hours ago

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=unsolved
Undefined index: forum_rules
Line: 248
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=solved
Undefined index: forum_name
Line: 236
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=solved
Undefined index: forum_description
Line: 237
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=solved
Undefined index: forum_rules
Line: 248
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=poll
Undefined index: forum_name
Line: 236
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=poll
Undefined index: forum_description
Line: 237
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=poll
Undefined index: forum_rules
Line: 248
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=discussions
Undefined index: forum_name
Line: 236
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=discussions
Undefined index: forum_description
Line: 237
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=discussions
Undefined index: forum_rules
Line: 248
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=attachments
Undefined index: forum_name
Line: 236
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=attachments
Undefined index: forum_description
Line: 237
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=attachments
Undefined index: forum_rules
Line: 248
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=all
Undefined index: forum_name
Line: 236
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=all
Undefined index: forum_description
Line: 237
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=view&type=all
Undefined index: forum_rules
Line: 248
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=time&type=unsolved
Undefined index: forum_name
Line: 236
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=time&type=unsolved
Undefined index: forum_description
Line: 237
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=time&type=unsolved
Undefined index: forum_rules
Line: 248
6 hours ago 
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=time&type=solved
Undefined index: forum_name
Line: 236
6 hours ago

and many more -- 13 sites!!!

**Comment by UnrealCatze** [comment]
i get this every time ... i delete all and next day all is inside in my errorlog again

**Comment by meangczac** [comment]
How did you get this messages? You deleted? moved? etc?

I can't get these errors/issue reproduced. 

What is your URL when error happens? or if you could provide me this data feedback.

Line 236 before, add this

```
if (!isset($data['item'][$_GET['forum_id']])) {
            print_p($data);
}
```

Please post back with print output, so I know what to check. By right, if you do not have this, you should be redirected by the core.

**Comment by UnrealCatze** [comment]
every morning i check my site and find some error messages in my log. a day before i clear the log and some hours later is my log full. I guess my guests or members will produce the errors so i cant say what happen.

today i have again this errors

Array
( [forum_new_status] => [last_post] => Array ( ) [forum_icon] => <i class='fa fa-comments-o fa-fw fa-fw m-r-10'></i> [forum_icon_lg] => <i class='fa fa-comments-o fa-fw fa-3x fa-fw m-r-10'></i> [forum_moderators] => [forum_link] => Array ( [link] => ../../infusions/forum/index.php?viewforum&amp;forum_id=9&amp;parent_id=2 [title] => General Discussion (Action Figures) ) [forum_description] => General Discussion (Action Figures) [forum_postcount_word] => 0 posts [forum_threadcount_word] => 0 threads [forum_id] => 9 [forum_cat] => 2 [forum_branch] => 21 [forum_name] => General Discussion (Action Figures) [forum_type] => 2 [forum_answer_threshold] => 15 [forum_lock] => 0 [forum_order] => 1 [forum_rules] => [forum_mods] => [forum_access] => 0 [forum_post] => -101 [forum_reply] => -101 [forum_allow_poll] => 1 [forum_poll] => -101 [forum_vote] => -101 [forum_image] => [forum_post_ratings] => -101 [forum_users] => 1 [forum_allow_attach] => 1 [forum_attach] => -101 [forum_attach_download] => -101 [forum_quick_edit] => 1 [forum_lastpostid] => 0 [forum_lastpost] => 0 [forum_postcount] => 0 [forum_threadcount] => 0 [forum_lastuser] => 0 [forum_merge] => 1 [forum_language] => English [forum_meta] => General Discussion (Action Figures) [forum_alias] => General-Discussion-(Action-Figures) [forum_cat_name] => General Discussion [thread_id] => [thread_lastpost] => [thread_lastpostid] => [thread_subject] => [post_message] => [user_id] => [user_name] => [user_status] => [user_avatar] => [first_post_datestamp] =>
)

**Comment by meangczac** [comment]
what is your url like when it happen? viewthread.php?thread_id=5 ?
See the forum_threads table in MYSQL. See the forum_id . Check if forum_id is the actual parent. 

Remember you had once Forum post thread delete error experience, make sure the data is not bad.

**Comment by Catzenjaeger** [comment]
Frederick ... i have defuse my forum yesterday and get the newest files from git .. uploaded it and infuse new. I have add my 3 forum thread and today morning i get the errors again. I dont know why but every morning when i look on my site my error log is full. Over the day not. 

i add a account for you again when you like watch himself. The logindata are the same . Ftp access you have too

i give up here.

**Comment by meangczac** [comment]
Ok, I will try to see what is the problem this evening after I finish doing upgrades.
