### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1068]
Registration form on small displays is not scrollable
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18439114/4d1d5e4a-7904-11e6-852e-9d5483b38528.png)

**Comment by karrak1** [comment]
ready, + show error messages.

**Comment by meangczac** [comment]
RobiNN keep it up. I leave styling issues to you. 

I'm stopping all work at hand to attend to Install and core files at the moment. I don't want to land myself in a support thread meltdown when we finish RC5.
