### ISSUE TITLE
Forum - text

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1069]
when i post a thread i get a formatted text with spaces, breaks e.g.
so, when i go and edit this thread .... so i get a unformated text now. 

I have to formate all content again and edit it and publish it.
Think here i error on callback data

**Comment by meangczac** [comment]
ok

**Comment by UnrealCatze** [comment]
it is fixed?

**Comment by meangczac** [comment]
See my commits... ive been working on heavy stuff now.

**Comment by meangczac** [comment]
Non issue with current forum build.
