### ISSUE TITLE
cant start a thread in subforums

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1071]
someone is wrong .. i have general forums and subforums. I can start a thread in general forums but not in a subforum. when i go over menu-- > start n new thread and select a subforum from dropdown and write a thread so it will not be stored!

![unbenannt](https://cloud.githubusercontent.com/assets/22166864/18583880/aaffddba-7c0d-11e6-8893-3619e29bdf7e.JPG)
missing button start a thread

**Comment by meangczac** [comment]
Check parent permissions. Anyway I test my side, it's all fine.

**Comment by UnrealCatze** [comment]
no my seetings are ok but i dont see the button for start a new thread

i have all subforums create as category ... is this my error?

![unbenannt](https://cloud.githubusercontent.com/assets/22166864/18738736/bfee0cb6-809e-11e6-9f9b-779cea063dbf.JPG)

**Comment by meangczac** [comment]
Category != Forum. Forum is the one for starting threads. Category is for grouping forums (statistics only).

If you want to have threads, use forum, not category.
