### ISSUE TITLE
includes/core_functions_include.php --> preg_replace_callback(): Requires argument 2, 'render_user_tags', to be a valid callback

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1076]
includes/core_functions_include.php
/site/print.php?type=F&item_id=4&post=4&nr=1
preg_replace_callback(): Requires argument 2, 'render_user_tags', to be a valid callback
Line: 625
9 hours ago 
Non fatal Runtime Errors  
includes/core_functions_include.php
/site/print.php?type=F&item_id=4&rowstart=0
preg_replace_callback(): Requires argument 2, 'render_user_tags', to be a valid callback
Line: 625
9 hours ago 
Non fatal Runtime Errors  
includes/core_functions_include.php
/site/print.php?type=F&item_id=3&post=3&nr=1
preg_replace_callback(): Requires argument 2, 'render_user_tags', to be a valid callback
Line: 625
9 hours ago 
Non fatal Runtime Errors  
includes/core_functions_include.php
/site/print.php?type=F&item_id=3&rowstart=0
preg_replace_callback(): Requires argument 2, 'render_user_tags', to be a valid callback
Line: 625
9 hours ago 
Non fatal Runtime Errors  
includes/core_functions_include.php
/site/print.php?type=N&item_id=1
preg_replace_callback(): Requires argument 2, 'render_user_tags', to be a valid callback
Line: 625
9 hours ago 
Non fatal Runtime Errors  
includes/core_functions_include.php
/site/print.php?type=T
preg_replace_callback(): Requires argument 2, 'render_user_tags', to be a valid callback
Line: 625
9 hours ago

**Comment by RobiNN1** [comment]
#1065
