### ISSUE TITLE
Driver/PDOMySQL.php /site/infusions/forum/tags.php?tag_id=5&sort=author --> General error: 1615 Prepared statement needs to be re-prepared

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1077]
Driver/PDOMySQL.php
/site/infusions/forum/tags.php?tag_id=5&sort=author
Query Error: SELECT t.*, tf.forum_type, tf.forum_name, tf.forum_cat, tu1.user_name ' author_name', tu1.user_status 'author_status', tu1.user_avatar 'author_avatar', tu2.user_name 'last_user_name', tu2.user_status 'last_user_status', tu2.user_avatar 'last_user_avatar', p1.post_datestamp, p1.post_message, IF (n.thread_id > 0, 1 , 0) 'user_tracked', count(v.vote_user) 'thread_rated', count(pv.forum_vote_user_id) 'poll_voted', p.forum_poll_title, count(v.post_id) AS vote_count, a1.attach_name, a1.attach_id, a2.attach_name, a2.attach_id, count(a1.attach_mime) 'attach_image', count(a2.attach_mime) 'attach_files', min(p2.post_datestamp) 'first_post_datestamp' FROM fusionu7I34_forum_threads t LEFT JOIN fusionu7I34_forums tf ON tf.forum_id = t.forum_id INNER JOIN fusionu7I34_users tu1 ON t.thread_author = tu1.user_id LEFT JOIN fusionu7I34_users tu2 ON t.thread_lastuser = tu2.user_id LEFT JOIN fusionu7I34_forum_posts p1 ON p1.thread_id = t.thread_id and p1.post_id = t.thread_lastpostid LEFT JOIN fusionu7I34_forum_posts p2 ON p2.thread_id = t.thread_id LEFT JOIN fusionu7I34_forum_polls p ON p.thread_id = t.thread_id #LEFT JOIN fusionu7I34_forum_votes v ON v.thread_id = t.thread_id AND p1.post_id = v.post_id LEFT JOIN fusionu7I34_forum_votes v on v.thread_id = t.thread_id AND v.vote_user='0' AND v.forum_id = t.forum_id AND tf.forum_type='4' LEFT JOIN fusionu7I34_forum_poll_voters pv on pv.thread_id = t.thread_id AND pv.forum_vote_user_id='0' AND t.thread_poll=1 LEFT JOIN fusionu7I34_forum_attachments a1 on a1.thread_id = t.thread_id AND a1.attach_mime IN ('image/jpg,image/jpeg,image/gif,image/png,image/tiff,image/tif,image/x-ms-bmp,image/x-icon') LEFT JOIN fusionu7I34_forum_attachments a2 on a2.thread_id = t.thread_id AND a2.attach_mime NOT IN ('image/jpg,image/jpeg,image/gif,image/png,image/tiff,image/tif,image/x-ms-bmp,image/x-icon') LEFT JOIN fusionu7I34_forum_thread_notify n on n.thread_id = t.thread_id and n.notify_user = '0' WHERE CONCAT(t.thread_tags, '.') like '%5%' AND t.thread_hidden='0' AND tf.forum_access = 0 AND tf.forum_language='English' GROUP BY t.thread_id ORDER BY t.thread_author DESC LIMIT 0, 20
Stack Trace: #0 /var/www/vhosts/xxxxxxxxxx.com/httpdocs/site/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php(68): PDOStatement->execute() #1 /var/www/vhosts/xxxxxxxx.com/httpdocs/site/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.php(300): PHPFusion\Database\Driver\PDOMySQL->_query('? SE...', Array) #2 /var/www/vhosts/xxxxxxxxx.com/httpdocs/site/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('? SE...', Array) #3 /var/www/vhosts/xxxxxxx.com/httpdocs/site/infusions/forum/classes/forum/tags.php(208): dbquery('? SE...') #4 /var/www/vhosts/xxxxxxx.com/httpdocs/site/infusions/forum/classes/forum/tags.php(91): PHPFusion\Forums\ThreadTags::get_tag_thread('5', Array) #5 /var/www/vhosts/xxxxxxxx.com/httpdocs/site/infusions/forum/classes/server.php(402): PHPFusion\Forums\ThreadTags->set_TagInfo(true) #6 /var/www/vhosts/xxxxxxxx.com/httpdocs/site/infusions/forum/tags.php(31): PHPFusion\Forums\ForumServer::tag(true, true) #7 {main}
Error Nature: SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared
Line: 72

**Comment by meangczac** [comment]
New forum?

**Comment by meangczac** [comment]
I will be making the upgrading for Forum Infusion so you can upgrade easily in Infusion to check on the required update. Will leave this issue open until it's done.

**Comment by UnrealCatze** [comment]
thats fine well my installed PHPF is not older than 2 weeks you know and im going live last week. So its difficult for me .. i cant reinstall and have to update ... the unique way

**Comment by meangczac** [comment]
Download the new Installer library - https://github.com/php-fusion/PHP-Fusion/tree/9.02/includes/classes/PHPFusion/Installer

You need to update 4 include files.
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/autoloader.php
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/core_functions_include.php
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/core_constants_include.php
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/core_resources_include.php

Then test your site see any problem. If no problem, runtime is fine.

Now, download the Forum upgrade. https://github.com/php-fusion/PHP-Fusion/tree/9.02/infusions/forum/upgrade

Then get this file as well: https://github.com/php-fusion/PHP-Fusion/blob/9.02/administration/infusions.php

Make sure $inf_version is set to 1.1

Download this too: https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/forum/infusion.php#L30 

Forum upgrade is now non-descructive. Took me hundred hours to get this done.

But then again, I do not suggest this for your live site, until one fine day, I can do a site wide inspection and make it done. For now, turn off errors reporting if it works, it works.
