### ISSUE TITLE
includes/functions.php --> Undefined index: V

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1079]
includes/functions.php
/site/administration/index.php?aid=204eb2a81d349b9a&pagenum=0
Undefined index: V
Line: 332

New Run-time notices  
includes/functions.php
/site/administration/index.php?aid=204eb2a81d349b9a&pagenum=0
Undefined index: V
Line: 333

**Comment by meangczac** [comment]
Not in Admin Folder - https://github.com/php-fusion/PHP-Fusion/tree/9.02/administration/includes
Not in base includes folder - https://github.com/php-fusion/PHP-Fusion/tree/9.02/includes

Where is this includes/functions.php ?

And there is No "V" in PHP-Fusion.
