### ISSUE TITLE
Forum Polls

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#108]
Forum Polls:

Guests can not see the poll results even tho the forum have guest view access enabled, naturally they should not be able to vote, but viewing polls should be possible with guest access.

**Comment by meangczac** [comment]
OK, spent hours on working this out an initial model to calculate permissions the entire forum.

Please find this .. $thread_data is a result of:

```
$result = dbquery("
                SELECT t.*,
                f.*, #this will fetch all permissions
                f2.forum_name AS forum_cat_name, f2.forum_access as parent_access,
                u.user_id, u.user_name, u.user_status, u.user_avatar, u.user_joined,
                IF (n.thread_id > 0, 1 , 0) as user_tracked,
                count('v.vote_user') 'thread_rated',
                count('p.forum_vote_user_id') 'poll_voted'
                FROM ".DB_FORUM_THREADS." t
                INNER JOIN ".DB_USERS." u on t.thread_author = u.user_id
                INNER JOIN ".DB_FORUMS." f ON t.forum_id=f.forum_id
                LEFT JOIN ".DB_FORUMS." f2 ON f.forum_cat=f2.forum_id
                LEFT JOIN ".DB_FORUM_VOTES." v on v.thread_id = t.thread_id AND v.vote_user='".intval($userid)."' AND v.forum_id=f.forum_id AND f.forum_type='4'
                LEFT JOIN ".DB_FORUM_POLL_VOTERS." p on p.thread_id = t.thread_id AND p.forum_vote_user_id='".intval($userid)."' AND t.thread_poll='1'
                LEFT JOIN ".DB_FORUM_THREAD_NOTIFY." n on n.thread_id = t.thread_id and n.notify_user = '".intval($userid)."'
                ".(multilang_table("FO") ? "WHERE f.forum_language='".LANGUAGE."' AND" : "WHERE")."
                ".groupaccess('f.forum_access')." AND t.thread_id='".intval($thread_id)."' AND t.thread_hidden='0'
                ");
```

I do not want to run permissions in every segment of the files here and there across 4 files. It's a hell to trace one by one. There's too many.

This is the TYPES of permissions on each thread - calculated every single visit to a different thread.

Whether you can access the thread <strong>is depending on your forum access</strong> or if you are a iMOD.

<strong>Who is iMOD?</strong>

<ul>
<li>admin with access FO rights is iMOD,</li>
<li> SUPERADMIN is iMOD.</li>
<li> User Groups that has been entered as moderator in forum admin permission is iMOD</li>
</ul>

<h4>Global changes are depending on this</h4>

<h4>Who can access this thread? </h4>

Moderator can access everything since the site is their property. i.e. global access.

```
$this->thread_info['permissions']['can_access'] = (iMOD || checkgroup($thread_data['forum_access'])) ? TRUE : FALSE;
```

<h4>Create another thread under the same forum</h4>

Here you do not need to check whether thread is locked or not, it's irrelevant. It's merely for users who decide to create a new thread when he's viewing a thread.

```
$this->thread_info['permissions']['can_post'] = (iMOD || (checkgroup($thread_data['forum_post']) && $thread_data['forum_lock'] == FALSE)) ? TRUE : FALSE;
```

<h4>Upload an attachment in this thread</h4>

![screen shot 2015-09-29 at 1 59 00 pm](https://cloud.githubusercontent.com/assets/4078041/10156324/72811d6c-66b2-11e5-9e1e-79e58321a015.png)

You need to check the "forum_allow_attach" checkbox in Forum Admin, otherwise, doesn't matter who you are, you cannot upload.

```
$this->thread_info['permissions']['can_upload_attach'] = $thread_data['forum_allow_attach'] == TRUE &&
                                                                 (iMOD || (checkgroup($thread_data['forum_attach'])
                                                                                     && $thread_data['forum_lock'] == FALSE
                                                                                     && $thread_data['thread_locked'] == FALSE
                                                                 ))  ? TRUE : FALSE;
```

<h4>Download an attachment in this thread</h4>

![screen shot 2015-09-29 at 1 59 00 pm](https://cloud.githubusercontent.com/assets/4078041/10156333/7bfa14f2-66b2-11e5-8866-a1d92330c7a6.png)

<strong>You need to allow attach to be able to download. </strong>
<strong>But since the file is already in, would it be more convenient if Administrator and Moderators can download</strong> since the site is their property. 

This can prove be useful (or not), to control whether public can download when an attachment is uploaded. By doing this, you can lock down the whole forum once forum is locked. However, if forum is not locked, everyone can download an attach still. This is because it is a <strong>more convenient</strong> that Admin and Mods don't need to lock every thread down to do it. They can just uncheck the allow attach checkbox in forum to achieve the same thing.

```
$this->thread_info['permissions']['can_download_attach'] = iMOD || ($thread_data['forum_allow_attach'] == TRUE && checkgroup($thread_data['forum_attach_download'])) ? TRUE : FALSE;
```

<h4>Post a reply in this thread</h4>

![screen shot 2015-09-29 at 2 01 25 pm](https://cloud.githubusercontent.com/assets/4078041/10156350/a5533c16-66b2-11e5-88d4-5819045e9d3a.png)

Pre-requiste check is that the thread must have at least 1 post minimum to be able to reply. If the thread has 0 post, it's bound to be deleted. <strong>That's also the case in v7.</strong>

```
$this->thread_info['permissions']['can_reply'] = $thread_data['thread_postcount'] > 0
                                                         && (iMOD || (checkgroup($thread_data['forum_reply'])
                                                                  && $thread_data['forum_lock'] == FALSE
                                                                  && $thread_data['thread_locked'] == FALSE
                                                        )) ? TRUE : FALSE;
```

<h4>Create a poll in this thread</h4>

![screen shot 2015-09-29 at 1 59 05 pm](https://cloud.githubusercontent.com/assets/4078041/10156361/c7daba66-66b2-11e5-91d0-e29e702247c7.png)

There must be <strong>No existing Poll</strong> and allow POLL must be ON, this rule is applicable to administrator, moderator.

```
$this->thread_info['permissions']['can_create_poll'] = $thread_data['forum_poll'] == FALSE // there are no existing poll.
                                                               && $thread_data['forum_allow_poll'] == TRUE &&
                                                               (iMOD || (checkgroup($thread_data['forum_poll'])
                                                                         && $thread_data['forum_lock'] == FALSE
                                                                         && $thread_data['thread_locked'] == FALSE
                                                                   )) ? TRUE : FALSE;
```

<h4>Edit a Poll (modify or delete the poll)</h4>

Only when you are a iMOD or the thread starter

```
$this->thread_info['permissions']['can_edit_poll'] = $thread_data['thread_poll'] == TRUE &&
                                                             (iMOD || (checkgroup($thread_data['forum_poll'])
                                                                       && $thread_data['forum_lock'] == FALSE
                                                                       && $thread_data['thread_locked'] == FALSE
                                                                       && $thread_data['thread_author'] == $userdata['user_id']
                                                                 )) ? TRUE : FALSE;
```

<h4>Can vote a poll</h4>

Only if you have not voted. AND even you are iMOD, you are not allowed to vote 100 times to manipulate the votes fairness. 

```
$this->thread_info['permissions']['can_vote_poll'] = $thread_data['poll_voted'] == FALSE
                                                        && (iMOD || (checkgroup($thread_data['forum_vote'])
                                                                     && $thread_data['forum_lock'] == FALSE
                                                                     && $thread_data['thread_locked'] == FALSE
            )) ? TRUE : FALSE;
```

<h4>Can Up or Downvote a Post (Forum Type 4 Restricted only) </h4>

Your forum type must be type 4. I.e Questions and Answers. And Everyone can only rate Once to select the best answer. Same as voting fairness, everyone can only vote once.

<strong> I am going to remove the allow_post_ratings in the administration panel</strong> The threshold is there to set, <strong>once it reaches a limit, it's automatically locks down the thread</strong> and preventing further voting. Thereby marking the Question as "Answered". It's very inconvenient to do a checkbox and then start the voting. Just lock the thread manually if you want to intervene. You cannot control this at Forum Level, because each forum has 100s of threads.

```
$this->thread_info['permissions']['can_rate'] = $thread_data['forum_type'] == 4
                                                        && $thread_data['thread_rated'] == FALSE
                                                        && (iMOD || (checkgroup($thread_data['forum_post_ratings'])
                                                                     && $thread_data['forum_lock'] == FALSE
                                                                     && $thread_data['thread_locked'] == FALSE
            )) ? TRUE : FALSE;
```

See if I have made any mistake, and I'll correct it. I pull this into a single function from everywhere in the whole forum. The objective is to do a conditional statement base on this to abort/run scripts.

The Usage is pretty similar to --

```
if (fusion_get_settings("site_seo")) {}
```

and to achieve --

```
if (getThreadPermissions("can_access") {}
```

Please check the logical statements and do try understand it. 

Thanks for reading.

**Comment by JoakimFalk** [comment]
"You need to allow attach to be able to download. 
But since the file is already in, would it be more convenient if Administrator and Moderators can download"

Yes I recon that it would.
I think the logic seem good in general, if mod or admin you should be able to perform actions.
If a superadmin does not want mod to perform action they change the forum access rights after locking a thread for example.

**Comment by meangczac** [comment]
It boils directly down to the function I did for the calculation of iMOD. The referenced git is the calculation of it.

$info['forum_mods'] is from dbquery() of the particular forum which was setup in permission settings.
A typical example of the value is:

```
$info['forum_mods'] = "-102.-103";
```

Function 

```
/**
     * Generate iMOD const
     * @param $info
     */
    public static function define_forum_mods($info) {
        $imod = FALSE;
        if (!defined("iMOD")) {
            if (iMEMBER && $info['forum_mods']) {
                $mod_groups = explode(".", $info['forum_mods']);
                foreach ($mod_groups as $mod_group) {
                    if (checkgroup($mod_group)) {
                        $imod = TRUE;
                    }
                }
            }
            if (iADMIN && checkrights("FO")) $imod = TRUE;
            if (iSUPERADMIN) $imod = TRUE;
        }
        define("iMOD", $imod);
    }
```

The whole of forum will run one time this function on document load after you get  a successful dbrows() of thread, or forum, depending on the page. There are 4 page in forum that is essential to it now. 

<ul>
<li>Index of Forum (Inspected)</li>
<li>Viewforum - when you view a specific forum. In V7, it's viewforum.php (Inspected)</li>
<li>Viewthread - when you view a specific thread. In v7, it's viewthread.php (Inspected)</li>
<li>Misc pages like - newthread form and reply form (Uninspected at this point)</li>
</ul>

It will run once only per document load and the constant will be created.

What I'm doing here is to split up piece-by-piece the v7 forum into components that can be reused again and again - therefore, reducing repeating codes and eliminating inconsistencies like typo errors when repeating the same task.
