### ISSUE TITLE
No confirmations Notice on confirming link for registration - Fix Registration AddNotice()

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1080]
i miss a message for this. Non know is my register ok now or not well it comes no message or popup.
Same when i click on a configurations - link in my email where i confirm my account. I click on it and nothing is to see.

plz add on this places a visualize message ... my new members are really confused

**Comment by JoakimFalk** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/20877040/4ff8d9ba-bac6-11e6-85e6-2aec55fda7c3.jpg)

**Comment by meangczac** [comment]
We can close this if confirm SEO also.

**Comment by JoakimFalk** [comment]
SEO Notifications broken. Test Nebula and Sept.

**Comment by meangczac** [comment]
Ok, the SEO driver _again_.
