### ISSUE TITLE
includes/functions.php --> Undefined index: V/Undefined index: NX

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1081]
includes/functions.php
/site/administration/index.php?aid=96899792bf69a106&pagenum=0
Undefined index: V
Line: 333

includes/functions.php
/site/administration/index.php?aid=96899792bf69a106&pagenum=0
Undefined index: V
Line: 332

includes/functions.php
/site/administration/index.php?aid=96899792bf69a106&pagenum=0
Undefined index: NX
Line: 306

includes/functions.php
/site/administration/index.php?aid=96899792bf69a106&pagenum=0
Undefined index: NX
Line: 305

**Comment by RobiNN1** [comment]
Where is includes/functions.php?

**Comment by meangczac** [comment]
Should be Venus, unable to read his comment rating type. :/ We need to register that V and NX in administration/index.php -- this I will need to make a class example how to register. Will work on that later myself.

Please keep this issue open for a while.

**Comment by UnrealCatze** [comment]
i use only old school .. guess is there

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/blob/9.02/administration/index.php#L106-L133

Add your type V and NX into the relevant array.

**Comment by meangczac** [comment]
I need to make an API for this, $admin->addType() something along this.

**Comment by meangczac** [comment]
Read the fix Git for instruction on your custom module.
