### ISSUE TITLE
templates/forum_main.php -->Undefined index: forum_rules/forum_description/forum_name

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1082]
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=7&time=6month&sort=view&order=ascending&type=discussions
Undefined index: forum_rules
Line: 248

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=7&time=6month&sort=view&order=ascending&type=discussions
Undefined index: forum_description
Line: 237

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=8&parent_id=7&time=6month&sort=view&order=ascending&type=discussions
Undefined index: forum_name
Line: 236

**Comment by RobiNN1** [comment]
It is not a problem on current forum build

**Comment by meangczac** [comment]
We're too active :smiley:
