### ISSUE TITLE
Textfields empty lines

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1086]
when i add text in textfields in a form later will be all empty lines deleted and the text is as 
contiguous text shown. When i open the form and edit this text i will be correct saved. when i reopen and save the empty lines will be delete again. 

that is, I always have to reformat all text on every change in the data.

here a expamle:

```
    // Formfield "Accessories"
    echo form_textarea("accessories", $locale['060'], $data['accessories'], [
        "type"      => fusion_get_settings("tinymce_enabled") ? "tinymce" : "html",
        "tinymce"   => fusion_get_settings("tinymce_enabled") && iADMIN ? "advanced" : "simple",
        "autosize"  => true,
        "required"  => false,
        "form_name" => "inputform"
    ]);
```

shown with this code:

```
echo "<div class='col-lg-8 col-md-8 col-sm-12 col-xs-12'>\n";
                                echo "<span class='small' style='word-break: break-all; word-wrap: break-word;'>".(parse_textarea($data['accessories']) ? parse_textarea($data['accessories']) : "-")."&nbsp;</span>\n";        
                        echo "</div>\n";
```

sometimes i use: `$description = nl2br(parse_textarea($data['description']));`

**Comment by meangczac** [comment]
`$description = nl2br(parse_textarea($data['description']));` Is correct. 

Parse_textarea does not add line breaks. ^^

**Comment by meangczac** [comment]
See the commit, you gotta do as true.. which is harder than typing nl2br(); Param too long will result counting error, it's counter productive. But nevermind, I added.

**Comment by Catzenjaeger** [comment]
what i have to change now?

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/dbba1d3f488613339921d6411c576db330bce64d
