### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1087]
Notice: Undefined index: 0113 in /var/www/vhosts/xxxxxxxxx.com/httpdocs/site2/includes/classes/PHPFusion/Installer/Requirements.core.inc on line 88

Notice: Undefined index: title in /var/www/vhosts/xxxxxxxx.com/httpdocs/site2/includes/classes/PHPFusion/Installer/Install.core.inc on line 357

![ashampoo_snap_2016 10 01_23h04m22s_002_](https://cloud.githubusercontent.com/assets/19621858/19017015/a732d0c8-882b-11e6-86f0-e381c221f5ed.jpg)

**Comment by Catzenjaeger** [comment]
text is not visible but when i mark this are i see this

![ashampoo_snap_2016 10 01_23h28m00s_005_](https://cloud.githubusercontent.com/assets/19621858/19017080/96551b78-882e-11e6-8a87-0b236d26ada6.jpg)

**Comment by meangczac** [comment]
Karrak's https://github.com/php-fusion/PHP-Fusion/commit/a1734db73ea01989f414f2e09c33695d149bdb50
