### ISSUE TITLE
new install - forum - wrong format

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1088]
text:
![ashampoo_snap_2016 10 02_03h10m09s_006_](https://cloud.githubusercontent.com/assets/22166864/19017901/26c83338-884e-11e6-9a60-7b32319ba473.jpg)
result as preview:
![ashampoo_snap_2016 10 02_03h10m37s_008_](https://cloud.githubusercontent.com/assets/22166864/19017902/2abcf730-884e-11e6-9372-d0b49ee0adc0.jpg)

**Comment by UnrealCatze** [comment]
small error is present again ... i have deactivate smilies but in preview i see smilies

**Comment by meangczac** [comment]
All preview is accompanied by smileys, but the Post you see in forum will not have smiley.
