### ISSUE TITLE
new install - forum - Undefined index: thread_tags

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1089]
threads/view.php
/site/infusions/forum/viewthread.php?action=edit&forum_id=14&thread_id=1&post_id=1
Undefined index: thread_tags
Line: 527

Notice: i get the newst PHP F version from today and install it .. have create all forums and this comes when i ediit a threa. Where i create the thread was nothing .. only after a change cames this notice

**Comment by RobiNN1** [comment]
Duplicated #1059
