### ISSUE TITLE
new install - templates/forum_thread.php --> Undefined index

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1091]
there is definitely a error in system .. today i have download and complete new install. 
This errors come when a user (not a admin) open a thread.

templates/forum_thread.php
/site/infusions/forum/viewthread.php?thread_id=1&pid=1
Undefined index: link
Line: 102

Run-time notices  
templates/forum_thread.php
/site/infusions/forum/viewthread.php?thread_id=1&pid=1
Undefined index: title
Line: 102

Run-time notices  
templates/forum_thread.php
/site/infusions/forum/viewthread.php?thread_id=1&pid=1
Undefined index: link
Line: 120

Run-time notices  
templates/forum_thread.php
/site/infusions/forum/viewthread.php?thread_id=1&pid=1
Undefined index: title
Line: 120

**Comment by meangczac** [comment]
fixed.
