### ISSUE TITLE
new install - Forum --> Tags dosent work

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1092]
![ashampoo_snap_2016 10 02_04h02m54s_009_](https://cloud.githubusercontent.com/assets/22166864/19018082/07435d9c-8855-11e6-9ff7-ec34c524c2db.jpg)

tags i have created
![ashampoo_snap_2016 10 02_04h06m08s_010_](https://cloud.githubusercontent.com/assets/22166864/19018103/70153840-8855-11e6-8b60-84fe82830308.jpg)

**Comment by meangczac** [comment]
Problem with Tags cannot be set as active. Fixed
