### ISSUE TITLE
new install - forum notices again and again

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1093]
so today in the morning i have download and install php fusion complete new. But i get again again the same notices like before.

here some of my notices that i get again and again. A error from my site is not possible well all files i have brand new downloaded and i have php fusion complete new install.

i have not imported tables or date from old installing! I have all Forums create new and my 2 posts too. Here is a error from site definitely excluded

Error   Options Severity    Status
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=unsolved
Undefined index: forum_name
Line: 237

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=unsolved
Undefined index: forum_description
Line: 238
38 minutes ago  
Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=unsolved
Undefined index: forum_rules
Line: 249

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=solved
Undefined index: forum_name
Line: 237

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=solved
Undefined index: forum_description
Line: 238

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=solved
Undefined index: forum_rules
Line: 249

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=poll
Undefined index: forum_name
Line: 237

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=poll
Undefined index: forum_description
Line: 238

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=poll
Undefined index: forum_rules
Line: 249

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=discussions
Undefined index: forum_name
Line: 237

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=discussions
Undefined index: forum_description
Line: 238

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=discussions
Undefined index: forum_rules
Line: 249

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=attachments
Undefined index: forum_name
Line: 237

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=attachments
Undefined index: forum_description
Line: 238

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=attachments
Undefined index: forum_rules
Line: 249

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=all
Undefined index: forum_name
Line: 237

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=all
Undefined index: forum_description
Line: 238

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&type=all
Undefined index: forum_rules
Line: 249

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&time=today
Undefined index: forum_name
Line: 237

Run-time notices  
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=19&parent_id=0&time=today
Undefined index: forum_description
Line: 238

**Comment by Catzenjaeger** [comment]
can anyone help? i get this errors again and again. 20 times per day i delete my log.  i get this error never when i log in as admin .. when i use a testaccount or login as normal member .. go to my forum and look around .. log out and log now in as Admin i see the errors again.

**Comment by meangczac** [comment]
reupload forum new files will fix this issue.

**Comment by Catzenjaeger** [comment]
i have do this and ...... today morning i had zero notices!!! hope it solved my problems
