### ISSUE TITLE
Required extended news - dont work

### ISSUE THREAD

**Issue by razin88** [PHPFusion/PHPFusion#1106]
This function Required extended news does not work in spite of the addition of extended news. I dont see readmore.

Required extended news is activated

![schowek](https://cloud.githubusercontent.com/assets/22763471/19342114/b849660c-9130-11e6-9365-04a828f39670.png)
.

**Comment by meangczac** [comment]
I believe it is fixed on 9.02 news infusion with 
News gallery. If its 9.02 news infusion, please tell again.
