### ISSUE TITLE
News date

### ISSUE THREAD

**Issue by razin88** [PHPFusion/PHPFusion#1107]
When I set the date to add news 14/02/2016, this PHP-Fusion adds today's date

**Comment by meangczac** [comment]
news start and news end only controls when it will be published, it doesn't alter the time you post.

**Comment by meangczac** [comment]
i will make an adjustment to alter time of news being posted.

**Comment by razin88** [comment]
I add news np: (set date / begin 26.05.2016), news view, today's date

**Comment by meangczac** [comment]
Will resolve this soonest possible.

**Comment by meangczac** [comment]
Just checked news, this issue is solved.
