### ISSUE TITLE
Installer Too many Redirects when Fail on Password/Dbname

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1108]
New install problem.
If database name or database password not good, then ERR_TOO_MANY_REDIRECTS
only the config_temp.php deleting be repaired.
OR
Admin data (password or admin password) not equal then also let continued to.

**Comment by karrak1** [comment]
The first half corrected, so good, work, unlink(BASEDIR."config_temp.php");

admin data remain to be improved

**Comment by karrak1** [comment]
corrected
