### ISSUE TITLE
Forum Tags dosent work

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1109]
i download the newest forum version and replaced all files. Forum Tags doesent work again. I cant choose a tag . field is blocked

![ashampoo_snap_2016 10 14_20h32m46s_001_](https://cloud.githubusercontent.com/assets/19621858/19398526/5c2cab68-924d-11e6-9433-9d99080c6ada.jpg)

![ashampoo_snap_2016 10 14_20h35m39s_002_](https://cloud.githubusercontent.com/assets/19621858/19398592/ade2df5e-924d-11e6-9060-6410ce32488c.jpg)

**Comment by meangczac** [comment]
set active the tags.

**Comment by Catzenjaeger** [comment]
yes this was my problem ... but suggestion make a little status (active/inactive) on overview .. so i have all to click and look inside and have no overview
