### ISSUE TITLE
Suggestion: add hreflang 

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1112]
i change something for better ranking of my site and found something what i miss in php fusion

i have add in my  templates --> layout.php this line:

`echo "<link rel='alternate' hreflang='x-default' href='".fusion_get_settings("siteurl")."' />\n";`

valdiator and other things can you find her: https://www.sistrix.de/hreflang-guide/

**Comment by Catzenjaeger** [comment]
i get a email from google today:

To: Webmaster of http://www.aliencollectors.com/

Google has detected that the tag "rel-alternate-hreflang" is incorrectly implemented on some pages of your site. The language and region codes do not appear to be correct. It is possible that the bi-directional linking is also faulty. For example, if page A refers to page B by means of "hreflang", a corresponding link from page B to page A must also be present. By using "hreflang" attributes, Google can provide users with the URL for the right language or region in the search results.

Your site will not benefit from the additional targeting to languages or regions unless you fix the errors in the "hreflang" links.

6 Tag tags with errors
1   http://aliencollectors.com/site/
2   /site/infusions/forum/index.php?section=latest
3   /site/infusions/forum/index.php?section=unanswered
4   /site/infusions/forum/index.php?section=unsolved
5   /site/infusions/forum/index.php?viewforum&amp;forum_id=7&amp;parent_id=2
6   /site/profile.php?lookup=1

**Comment by JoakimFalk** [comment]
Let´s roadmap these for any later versions if the issues still exists.
