### ISSUE TITLE
SEO - google say --> Pages with duplicate meta

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1114]
my google webmaster tool says: 

> HTML enhancements Last updated on October 20, 2016
> 
> Resolving the following issues can improve the experience and performance of your site.
> Meta description pages
> Double Metrics 29
> Short Metrics 2
> 
> Title tag pages
> Double "title" tags 6

**Pages with short metric pages**
Your Alien Figures & Merchandising Collector Web Portal /site/infusions/forum/index.php?section=unanswered
Your Alien Figures & Merchandising Collector Web Portal /site/infusions/forum/index.php?section=unsolved

**Pages with duplicate meta pages pages**
Your Alien Figures & Merchandising Collector Web Portal
/
/site/home.php?rowstart=0
/site/home.php?rowstart=5
/site/infusions/figurelib/figures.php?figure_cat_id=10
/site/infusions/figurelib/figures.php?figure_cat_id=13
/site/infusions/figurelib/figures.php?figure_cat_id=17
/site/infusions/figurelib/figures.php?figure_cat_id=1
/site/infusions/figurelib/figures.php?figure_cat_id=20
/site/infusions/figurelib/figures.php?figure_cat_id=22
/site/infusions/figurelib/figures.php?figure_cat_id=23
/site/infusions/figurelib/figures.php?figure_cat_id=4
/site/infusions/figurelib/figures.php?figure_cat_id=6
/site/infusions/figurelib/figures.php?figure_cat_id=9
/site/infusions/figurelib/figures.php?figure_id=250
/site/infusions/figurelib/figures.php?figure_id=25
/site/infusions/figurelib/figures.php?figure_id=263
/site/infusions/figurelib/figures.php?figure_id=362
/site/infusions/figurelib/figures.php?figure_id=393
/site/infusions/forum/index.php?section=unanswered
/site/infusions/forum/index.php?section=unsolved
/site/infusions/forum/index.php?viewforum&forum_id=1&parent_id=0
/site/infusions/forum/index.php?viewforum&forum_id=14&parent_id=0
/site/infusions/forum/index.php?viewforum&forum_id=16&parent_id=14
/site/infusions/forum/viewthread.php?thread_id=1&pid=1
/site/infusions/forum/viewthread.php?thread_id=2&pid=2
/site/infusions/forum/viewthread.php?thread_id=3&pid=3
/site/infusions/video/video.php?id=36
/site/infusions/video/video.php?id=39
/site/login.php

**Pages with duplicate "title" tags pages**
Discussion Forum: Showroom - AlienCollectors
/site/infusions/forum/index.php?viewforum&forum_id=14&parent_id=0
/site/infusions/forum/index.php?viewforum&forum_id=16&parent_id=14
2
AlienCollectors
/
/site/home.php?rowstart=0
/site/home.php?rostart=325
/site/home.php?rowstart=5
4

**Comment by JoakimFalk** [comment]
Let´s roadmap these for any later versions if the issues still exists.
