### ISSUE TITLE
threads/view.php --> Undefined index: thread_tags

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1118]
threads/view.php
/site/infusions/forum/viewthread.php?action=edit&forum_id=3&thread_id=5&post_id=5
Undefined index: thread_tags
Line: 527

**Comment by meangczac** [comment]
Non issue here.. ?

**Comment by meangczac** [comment]
The only thing i can fix is the above. And in this case the template file has an empty check. If you have error, your file is old file I guess.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/forum/templates/forum_input.php#L38

`echo !empty($info['tags_field']) ? $info['tags_field'] : "";`

Is impossible to get undefined index.
