### ISSUE TITLE
Search - PageNav

### ISSUE THREAD

**Issue by DavidGuetl** [PHPFusion/PHPFusion#1120]
It is not possible to change the Page via Pagenav or Rowstart in the Url if there are more than 10 Objects.

Problem is this Line:

```
if (!isset($_GET['rowstart']) || !isnum($_GET['rowstart'])) {
    $_POST['rowstart'] = 0;
}
```

Because Rowstart will be only given with GET-Params.

My Suggestion to fix it quick:

```
$_POST['rowstart'] = 0;
if (isset($_GET['rowstart']) && isnum($_GET['rowstart'])) {
    $_POST['rowstart'] = $_GET['rowstart'];
}
```

**Comment by UnrealCatze** [comment]
Yes I've noticed this in my programming of my SEARCH and also in the forum reports for some days: https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37956&pid=200352#post_200352

**Comment by Catzenjaeger** [comment]
201 additions and 234 deletions for this problem???????????????????

**Comment by RobiNN1** [comment]
No

**Comment by Catzenjaeger** [comment]
what solved my problem? what i have to change/update?

**Comment by RobiNN1** [comment]
In search.php
Line 24
This 

``` php
if (!isset($_POST['rowstart']) || !isnum($_POST['rowstart'])) {
     $_POST['rowstart'] = 0;
}
```

to

``` php
$_POST['rowstart'] = 0;
if (isset($_GET['rowstart']) && isnum($_GET['rowstart'])) {
    $_POST['rowstart'] = $_GET['rowstart'];
}
```

Problem solved?
