### ISSUE TITLE
Site Links Reorder

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1121]
Link position is not saved

**Comment by meangczac** [comment]
Which one, the drag/drop reorder or in the form ? I'll check the form side now.

**Comment by RobiNN1** [comment]
drag & drop

**Comment by meangczac** [comment]
but drag and drop only will sort out the link order only.

**Comment by meangczac** [comment]
ok, i saw that if the link_position filter is used, the jquery drag drop is out of order. I will see what can I do.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/585b8b1596d59eb961d7bf583d8862c540f60987

**Comment by RobiNN1** [comment]
It work and Links per page not working

**Comment by meangczac** [comment]
Links per page as in settings links per page OR the admin result filter selector? Im not with my pc at this moment.

**Comment by RobiNN1** [comment]
![screen](https://cloud.githubusercontent.com/assets/11664877/19845469/87600cc0-9f37-11e6-98ae-fa18d6b70c08.png)

![screen1](https://cloud.githubusercontent.com/assets/11664877/19845470/8a6dfd96-9f37-11e6-9843-681d431374d3.png)
