### ISSUE TITLE
Theme Manager widgets

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1122]
Widgets counter is always 0

**Comment by meangczac** [comment]
Can show screenshot where 0 is?

**Comment by RobiNN1** [comment]
![screen](https://cloud.githubusercontent.com/assets/11664877/19836370/ccaac584-9e9e-11e6-9e80-a808eec811a3.png)

**Comment by meangczac** [comment]
I will fix this. @RobiNN1  please see #1135 and use $admin_sections as Admins::getInstance() instead of inherit parent:: or self:: or $this.
