### ISSUE TITLE
Search blog

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1134]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/search.php?stype=all
Query Error: SELECT COUNT(blog_id) FROM pf9_blog WHERE WHERE blog_language='English' AND 1 = 1 AND (blog_subject LIKE '%test%' || blog_blog LIKE '%test%' || blog_extended LIKE '%test%') AND (blog_start='0'||blog_start<=NOW()) AND (blog_end='0'||blog_end>=NOW()) 
Stack Trace: #0 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(63): PDO->prepare('SELECT COUNT(bl...') #1 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(300): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT COUNT(bl...', Array) #2 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(88): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT COUNT(bl...', Array) #3 F:\xampp\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(125): PHPFusion\Database\Driver\PDOMySQL->count('(blog_id)', 'pf9_blog', 'WHERE blog_lang...', Array) #4 F:\xampp\htdocs\PHP-Fusion\includes\search\search_blog_include.php(54): dbcount('(blog_id)', 'pf9_blog', 'WHERE blog_lang...') #5 F:\xampp\htdocs\PHP-Fusion\search.php(392): include('F:\\xampp\\htdocs...') #6 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE blog_language='English' AND 1 = 1 AND (blog_subject LIKE '%test%' || blog_' at line 1
Line: 71

**Comment by karrak1** [comment]
not work search_querylike_safe("xxx", $swords_keys_for_query, $c_swords, $fields_count, 0);
not calculated properly, one and three adatból good, not good to eject 2.
1 data (article_subject LIKE :sword00)
 search_fieldsvar($ssubject)
2 data (article_article LIKE :sword01 || article_snippet LIKE )
 search_fieldsvar($smessage, $ssnippet)
3 data (article_subject LIKE :sword00 || article_snippet LIKE :sword02 || article_article LIKE :sword01)
 search_fieldsvar($ssubject, $ssnippet, $smessage)

search_querylike("xxx") work..

**Comment by meangczac** [comment]
I don't see errors using 'test' search blog. Is there a fix already in?

**Comment by RobiNN1** [comment]
fixed

**Comment by meangczac** [comment]
Thanks a bunch.
