### ISSUE TITLE
Administration - Left Navigation - New Section

### ISSUE THREAD

**Issue by DavidGuetl** [PHPFusion/PHPFusion#1135]
Hey Guys!

i have a small Problem ..

I will add a new Section in my Adminarea (as example ID 6) but it seems not to work.
Added in infusion_db.php the following Line: 
`\PHPFusion\Admins::getInstance() -> addAdminSection(6, "One more Section", "fa fa-fw fa-list");`

If i use the following Line after the Code (to check the Array) all seems fine:
`print_r(\PHPFusion\Admins::getInstance() -> getAdminSections());`

But the Section will be only added in VENUS, all others not.

As Example Artemis:
![screen](https://cloud.githubusercontent.com/assets/19527428/19999286/a9146180-a271-11e6-8d44-05d6efd81476.png)

**Comment by meangczac** [comment]
Ok, each Theme has its own codes, and I'm fixing Artemis only to set example of the fixes.

The problem is at parent:: and not Admins::getInstance() as oppose to catch the latest state of change.
