### ISSUE TITLE
Warnings on Setup Step 2

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1137]
I got those Warnings on a new Setup:

Warning: Illegal string offset 'severability' in /var/www/web1/htdocs/includes/classes/PHPFusion/Installer/Requirements.core.inc on line 226

Warning: Illegal string offset 'severability' in /var/www/web1/htdocs/includes/classes/PHPFusion/Installer/Requirements.core.inc on line 226

Warning: Illegal string offset 'severability' in /var/www/web1/htdocs/includes/classes/PHPFusion/Installer/Requirements.core.inc on line 226

Warning: Illegal string offset 'severability' in /var/www/web1/htdocs/includes/classes/PHPFusion/Installer/Requirements.core.inc on line 226

Warning: Illegal string offset 'severability' in /var/www/web1/htdocs/includes/classes/PHPFusion/Installer/Requirements.core.inc on line 226

an the second step are nor readable, see screenshot.

![image](https://cloud.githubusercontent.com/assets/164333/20040388/ca684dba-a456-11e6-8555-f0fe81b3b4c0.png)

all marked

![image](https://cloud.githubusercontent.com/assets/164333/20040393/d871fdc0-a456-11e6-9112-21f07b4e659b.png)

Greatz

**Comment by Der-WU** [comment]
A lot more Warnings on Infusion STEP

Notice: Use of undefined constant DB_NEWS - assumed 'DB_NEWS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 34

Notice: Use of undefined constant DB_NEWS_IMAGES - assumed 'DB_NEWS_IMAGES' in /var/www/web1/htdocs/infusions/news/infusion.php on line 61

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 72

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 126

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 127

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 128

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 129

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 130

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 131

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 132

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 133

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 134

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 135

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 136

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 137

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 138

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 139

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 140

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 145

Notice: Use of undefined constant DB_NEWS - assumed 'DB_NEWS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 146

Notice: Use of undefined constant DB_NEWS - assumed 'DB_NEWS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 155

Notice: Use of undefined constant DB_NEWS_CATS - assumed 'DB_NEWS_CATS' in /var/www/web1/htdocs/infusions/news/infusion.php on line 156

Notice: Use of undefined constant DB_NEWS_IMAGES - assumed 'DB_NEWS_IMAGES' in /var/www/web1/htdocs/infusions/news/infusion.php on line 157

**Comment by meangczac** [comment]
Please try again after the fixes. 

For the severability keys, it's an assign. It should be able to assign. See the code yourself. I'm not sure why your system throws a warning, my system is fine..

**Comment by Der-WU** [comment]
Noticed on Infusion Setup fixed.
Don´t know what about the severaribility warning. they still exist.

**Comment by meangczac** [comment]
```
// Check system core files and folders
        $check_arr = array(
            "administration/db_backups" => FALSE,
            "images" => FALSE,
            "images/imagelist.js" => FALSE,
            "images/avatars" => FALSE,
            "robots.txt" => FALSE,
        );

        foreach ($check_arr as $key => $value) {

            $check_arr[$key] = (file_exists(BASEDIR.$key) && is_writable(BASEDIR.$key)) or (file_exists(BASEDIR.$key) && function_exists("chmod") && @chmod(BASEDIR.$key, 0777) && is_writable(BASEDIR.$key));

            if (!$check_arr[$key]) {
                $requirements['files_check']['sub'][$key] = self::$locale['setup_0136'];
                //L226---------> error for you? $requirements['files_check']['sub'][$key]['severability'] = -10;
            } else {
                $requirements['files_check']['sub'][$key] = self::$locale['setup_0137'];
            }

print_r($requirements);

        }

```

Like I said, it is an assign with $key. It's in a loop and I dont know why you get error. See my changes, and it will show you why you get error.
