### ISSUE TITLE
Undefined index: comment_item_type

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1139]
Feedback/Comments.ajax.php
/site/includes/classes/PHPFusion/Feedback/Comments.ajax.php
Undefined index: comment_item_type
Line: 25
Line: 26
Line: 27
Line: 28
Line: 29

**Comment by Catzenjaeger** [comment]
new after i added the fix

templates/render_functions.php
/site/infusions/figurelib/figures.php?figure_id=264
templates/render_functions.php
Line: 215

**Comment by Catzenjaeger** [comment]
Feedback/Comments.inc
/site/infusions/figurelib/figures.php?figure_id=265
Undefined index: comment_subject
Line: 272

**Comment by meangczac** [comment]
templates/render_functions.php
/site/infusions/figurelib/figures.php?figure_id=264

**templates/render_functions.php**
**Update this file**

And for this:
Feedback/Comments.inc
/site/infusions/figurelib/figures.php?figure_id=265
Undefined index: comment_subject
Line: 272

**Rerun the installer.**

**Comment by Catzenjaeger** [comment]
what installer ... for php fusion completly?

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/blob/9.02/install.php

No data will be dropped. Backup your SQL. We're still RC.

**Comment by meangczac** [comment]
PHP-Fusion Installer is also an automatic updater.
