### ISSUE TITLE
Does your Lower Center Panel work?

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1140]
Please answer yes/no. Mine does.

2 more 'yes' to close.

**Comment by JoakimFalk** [comment]
Any theme?

**Comment by RobiNN1** [comment]
yes

**Comment by Kvido** [comment]
Artemis

**Comment by meangczac** [comment]
Just check - Septenary works. 

What I was afraid was the panel class, which I thought had been perfected. Luckily it is still the case.

For Artemis, it's already given it's working. I've triple checked. @Kvido, what exactly was the problem there? Can you describe?

I will be able to help when I get what is the real problem.  

---

This is my test result just using welcome panel. All OK

![capture](https://cloud.githubusercontent.com/assets/4078041/20180764/bf0bc83c-a796-11e6-893a-67f66a1eea8f.JPG)

![capture3](https://cloud.githubusercontent.com/assets/4078041/20180775/c7cc2034-a796-11e6-864f-bab8ebf4d6f8.JPG)

![capture4](https://cloud.githubusercontent.com/assets/4078041/20180779/cb9df304-a796-11e6-892a-d22e533766c9.JPG)

![capture2](https://cloud.githubusercontent.com/assets/4078041/20180767/c1f399da-a796-11e6-8542-e1235788f892.JPG)

**Comment by JoakimFalk** [comment]
I can only get it to work on next with display on all pages and specific page.
When using display opening page only, it does not show.

Edit, 
I had problems displaying side panels on specific page instead. very strange. Will do more careful tests later if needed.

**Comment by Kvido** [comment]
I can only get it to work on next picture display on all pages and specific page.
When using the display opening page only, it does not show.

Edit
I Had problems displaying side panels on specific page instead. Very strange. Will do more careful tests later if needed.

U theme Septenary / Venus works - as Chan
U theme Theme Fusion / Venus or Fusion Themes / Artemis does not work.

The problem is probably in D, table panels, panel_side 3. Here, the value does not appear filname!
When I give panelo_side 4 filname appear in the right column (narrow column).

**Comment by meangczac** [comment]
## Issue 1

> When using the display opening page only, **it does not show.** 

if this is a custom page please check the custom page edit and go settings make sure panels are on/off is done correctly.  For this debugging sake, please set home.php as your new opening page. Because custom page has a settings... don't forget

![capture](https://cloud.githubusercontent.com/assets/4078041/20220333/118ffcdc-a868-11e6-88e3-af0cabd6bb53.JPG)

Also I specifically disable right panels in all custom pages. https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/FusionTheme/ThemePack/Nebula/Templates/Page.php#L32
Delete this line to have the Custom Page Template forced shut down right panel deleted for your case.

In this case, I used Panels's API code to trigger hide_panel() in theme. Yes, a Panel controller via code. V9 have this. (Of course, given chance we'll slowly document it out) 

Because I want the custom page slider a little bit funky, and I do not want the output such as this happening ....

![capture](https://cloud.githubusercontent.com/assets/4078041/20220857/20095aae-a86a-11e6-9ce6-c61fa6a45641.JPG)

With this I manage to place a full control of the PF9 via custom template of the FusionTheme to _have unique styling outlook._ to force panel right side to shut down no matter what user do. Theme has ultimate control. It's best way to give designer what they want and enjoy a risk configuration free accidents.

Please verify your results again after your test with home.php as your opening page.

**Comment by meangczac** [comment]
## Issue 2

on Domi's end: 

> I Had problems displaying side panels on specific page instead. Very strange. Will do more careful tests later if needed. 

Now I will add a test panel into each side of home.php only
![capture](https://cloud.githubusercontent.com/assets/4078041/20221041/ca0adf5a-a86a-11e6-999c-8f8775277e8a.JPG)

![capture1](https://cloud.githubusercontent.com/assets/4078041/20221472/7603b47a-a86c-11e6-8a9c-daa5e6d99b05.JPG)

Lower Center:

![capture2](https://cloud.githubusercontent.com/assets/4078041/20221477/79b6a69a-a86c-11e6-9f5e-3665d6042fa1.JPG)

And OOP! 2 more never do. BL_LOWER and BL_CENTER never designed. haha.. Get the git later. I just added, and this confirms panel class has not a problem in exclusion and inclusion. (The thing that I worried about most)

**Comment by meangczac** [comment]
The fix: https://github.com/php-fusion/PHP-Fusion/commit/69d466f40789ed286be04e8cc67322771c5f03f4

**Comment by meangczac** [comment]
## Issue 3

> The problem is probably in D, table panels, panel_side 3. Here, the value does not appear filname!
> When I give panelo_side 4 filname appear in the right column (narrow column).

Side 3 is...  L_CENTER

```
const PANEL_LEFT = 1;
    const PANEL_U_CENTER = 2;
    const PANEL_L_CENTER = 3;
    const PANEL_RIGHT = 4;
    const PANEL_AU_CENTER = 5;
    const PANEL_BL_CENTER = 6;
```

Ok, test -

![capture](https://cloud.githubusercontent.com/assets/4078041/20221742/7eec1518-a86d-11e6-8122-7e5758def1db.JPG)

![capture2](https://cloud.githubusercontent.com/assets/4078041/20221745/827a7242-a86d-11e6-8ec4-72696f8aee97.JPG)

![capture](https://cloud.githubusercontent.com/assets/4078041/20221771/a5f7ded0-a86d-11e6-9d5c-668d4b308911.JPG)

Test went good without panel class glitch. Just theme were missing codes ^^

**Comment by meangczac** [comment]
@Kvido , the Admin themes just skin and colors only, it has nothing to do with core administration codes. Doesn't matter which Admin theme we use, result still same.

**Comment by meangczac** [comment]
I like the badge, edit and delete of posts in Github. It will very good if it is in our forum software... LOL

**Comment by Kvido** [comment]
Óó, thanks, I'll test.

**Comment by Kvido** [comment]
Hello!
1 / Adjusted page.php to "2"
2/2 page created
3 / you can not insert panel Right

**Comment by Kvido** [comment]
My test: http://frybtest.euweb.cz/viewpage.php?page_id=2

**Comment by meangczac** [comment]
As I've said earlier - see this line --- https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/FusionTheme/ThemePack/Nebula/Templates/Page.php#L39

Please delete this line. I locked it. The carousel will not look good with RIGHT panels.

Theme can control Fusion without going Admin Panel.

**Comment by Kvido** [comment]
http://frybtest.euweb.cz/home.php

With the update files, see .: The fix: 69d466f
Lower Works Center. I'm going to test pc-politika.cz

**Comment by Kvido** [comment]
SUPER!!!
Lower Center now also works on the cutting site, default System Admin / Panels:
https://pc-politika.cz/homepage

1 / Only I have a problem with styles.

**Comment by meangczac** [comment]
So this is fixed yeah.

**Comment by Kvido** [comment]
Yes, this should be a stable, reliable.
1 / It may also be the right column, but the images are small.
2 / I'll try for that reason, without the right column.
3 / I wonder where to insert advertising. Until about HomePahe header ...
