### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1141]
Fresh install 
Notice: date_default_timezone_set(): Timezone ID '' is invalid in F:\xampp\htdocs\PHP-Fusion\maincore.php on line 52

Fatal error: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in F:\xampp\htdocs\PHP-Fusion\includes\core_functions_include.php on line 1384

**Comment by meangczac** [comment]
Yes. I will fix. Already know where.
