### ISSUE TITLE
Feedback/Comments.inc --> Undefined index: comment_subject

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1144]
Feedback/Comments.inc
/site/infusions/figurelib/figures.php?figure_id=265
Undefined index: comment_subject
Line: 272

**Comment by meangczac** [comment]
Non issue your SQL table is not updated only.

**Comment by Catzenjaeger** [comment]
What i have to install new? waht i have to do?

**Comment by meangczac** [comment]
Run the installer. or add comment_subject manually to your sql table.

Comment subject varchar 200 after comment id in comments table

**Comment by Catzenjaeger** [comment]
not the problem well i have this in my table
guess its other problem

![ashampoo_snap_2016 11 16_21h35m01s_001_](https://cloud.githubusercontent.com/assets/19621858/20364584/f72521e4-ac43-11e6-9b58-c72e9a766209.jpg)

**Comment by meangczac** [comment]
Oh. Ok.

**Comment by meangczac** [comment]
Can't find any more reference to comment subject that is unchecked.
