### ISSUE TITLE
Use of undefined constant iAUTH

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1145]
![error](https://cloud.githubusercontent.com/assets/11664877/20236242/1ae12760-a8af-11e6-8c66-d1c584e8371d.png)

**Comment by karrak1** [comment]
not work Admin.inc 
            $acTab = (isset($_GET['pagenum']) && isnum($_GET['pagenum'])) ? $_GET['pagenum'] : self::$instance->_isActive();
            if ($acTab != 0 && $acTab <= 5) {
                BreadCrumbs::getInstance()->addBreadCrumb(['link' => ADMIN.$aidlink."&amp;pagenum=".$acTab, 'title' => $GLOBALS['locale']['ac0'.$acTab]]);
            }
not value $aidlink

**Comment by meangczac** [comment]
check and see now.

**Comment by RobiNN1** [comment]
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/20345485/ad7b1c8e-abf7-11e6-9388-c0782cbb1d74.png)

aid is empty

**Comment by meangczac** [comment]
Is your session timed out? I don't get such.

**Comment by RobiNN1** [comment]
no

**Comment by meangczac** [comment]
try now and see?

**Comment by RobiNN1** [comment]
Nothing

**Comment by meangczac** [comment]
Any error logs?

**Comment by RobiNN1** [comment]
No, problem probably will be in https://github.com/php-fusion/PHP-Fusion/blob/9.02/maincore.php#L215-L228

**Comment by meangczac** [comment]
Help me change your function and tell me whats wrong -

```

/**
 * Get Aidlink
 * @return string
 */
function fusion_get_aidlink() {
    $aidlink = '';

    if(!defined('iADMIN')) {
        print_p("How come you are not admin?");
    }
    if (!defined('iAUTH')) {
        print_p("iAUTH not generated.");
    }

    if (defined('iADMIN') && iADMIN && defined('iAUTH')) {
        $aidlink = '?aid='.iAUTH;
    }

    return (string) $aidlink;
}
```

**Comment by RobiNN1** [comment]
iAUTH not generated.

**Comment by meangczac** [comment]
ok, then here: https://github.com/php-fusion/PHP-Fusion/blob/9.02/maincore.php#L216
add:

print_p("I am admin and i get to execute here");

Tell me if you pass?

Also do a print_p("My iADMIN is ".iADMIN);

**Comment by RobiNN1** [comment]
Yes

**Comment by meangczac** [comment]
Then print_p(iAUTH); see if it prints or not.

**Comment by RobiNN1** [comment]
F:\xampp\htdocs\PHP-Fusion\maincore.php
/administration/index.php?aid=225d2247367dd83f&pagenum=1
Line: 216

Use of undefined constant iAUTH - assumed 'iAUTH'

**Comment by RobiNN1** [comment]
Fixed

**Comment by meangczac** [comment]
ok. wierd.
