### ISSUE TITLE
new install (today 12:00) no link to site back in admin area

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1146]
no link to site back

![ashampoo_snap_2016 11 13_12h32m18s_010_](https://cloud.githubusercontent.com/assets/19621858/20245198/780526e2-a99c-11e6-801f-0b8d579a69d0.jpg)

**Comment by meangczac** [comment]
![working](https://cloud.githubusercontent.com/assets/4078041/20417098/09a1e6dc-ad7e-11e6-9dcf-7a7ec1da861b.png)
