### ISSUE TITLE
site_links.php --> Undefined index: link_position_id

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1147]
site_links.php
/site_neu/administration/site_links.php?aid=84bfa5b67185dc59&ref=link_form
Line: 389

Severity : Run-time notices
Undefined index: link_position_id

**Comment by meangczac** [comment]
This error is triggered by your existing link records. The new ones will not be affected from now on.
Just edit your link position in your own links.
