### ISSUE TITLE
no image last threads panel

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1149]
new install
![ashampoo_snap_2016 11 13_13h13m23s_011_](https://cloud.githubusercontent.com/assets/19621858/20245451/38fa9fda-a9a2-11e6-8d90-6363d5ee770e.jpg)

so it was before in my older install
![ashampoo_snap_2016 11 13_13h14m38s_012_](https://cloud.githubusercontent.com/assets/19621858/20245460/53220006-a9a2-11e6-9d5c-a502792ade65.jpg)

**Comment by RobiNN1** [comment]
Update forum panels

**Comment by Catzenjaeger** [comment]
ok found the mistake/error
we have here some changes
