### ISSUE TITLE
User fields

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1153]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/administration/user_fields.php?aid=71ec05a2cf70d10b
Line: 71

**Comment by meangczac** [comment]
Click the link in the error console , a hidden tab will appear with the stack trace. Paste it here pls

**Comment by RobiNN1** [comment]
Query Error: CREATE TABLE pf9_test ( 1_key MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT , 1 MEDIUMINT(8) NOT NULL DEFAULT '0', PRIMARY KEY (1_key), KEY 1 (1) ) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci
Stack Trace: 
#0 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(63): PDO->prepare('CREATE TABLE pf...') 
#1 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(300): PHPFusion\Database\Driver\PDOMySQL->_query('CREATE TABLE pf...', Array) 
#2 F:\xampp\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('CREATE TABLE pf...', Array) 
#3 F:\xampp\htdocs\PHP-Fusion\includes\sqlhandler.inc.php(59): dbquery('CREATE TABLE pf...') 
#4 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\QuantumFields.inc(1605): SqlHandler::build_table('pf9_test', '1') 
#5 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\QuantumFields.inc(1432): PHPFusion\QuantumFields->quantum_category_form() 
#6 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\QuantumFields.inc(990): PHPFusion\QuantumFields->quantum_admin_buttons() 
#7 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\QuantumFields.inc(264): PHPFusion\QuantumFields->display_all_fields()
#8 F:\xampp\htdocs\PHP-Fusion\administration\user_fields.php(29): PHPFusion\QuantumFields->displayQuantumAdmin() 
#9 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 MEDIUMINT(8) NOT NULL DEFAULT '0', PRIMARY KEY (1_key), KEY ' at line 3

**Comment by meangczac** [comment]
CREATE TABLE pf9_test ( 1_key MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT , 1 MEDIUMINT(8) NOT NULL DEFAULT '0', PRIMARY KEY (1_key), KEY 1 (1) ) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci

what is pf9_test ?

**Comment by RobiNN1** [comment]
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/20344897/e1aa8b14-abf4-11e6-85cc-75649569d050.png)

![2](https://cloud.githubusercontent.com/assets/11664877/20344953/26ef6956-abf5-11e6-8623-ef5a877c1883.png)

**Comment by RobiNN1** [comment]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\QuantumFields.inc
/administration/user_fields.php?aid=85189b84a2e27e8e **
Line: 1517

Undefined index: field_cat_db

**Comment by meangczac** [comment]
ok. its like this now... the installer is missing 1 important thing.
db_users and user_id in page 1 of the menu. add it in manually. 
Installer did not have that, I just added yesterday.

The field is for this during $_GET['lookup'] in profile.php

```
$result = dbquery("SELECT u.*, custom.* FROM ".DB_USERS." u 
INNER JOIN ".$field_cat_db." custom ON u.user_id = custom.$field_key
WHERE u.user_id = '$_GET['lookup']'
");
```

It will omit custom join if your value is "users" for table and "user_id" for key.

**Comment by RobiNN1** [comment]
Not working, still writes "Your table must be a valid table. Your column must be a column of a user id in that table."

**Comment by Rizado** [comment]
MEDIUMINT(11)?
If I remember right, mediumint supports to 8 digits.

**Comment by meangczac** [comment]
@RobiNN1 
Do you have your table in SQL? You need to have it the DB already before pairing can even begin now. 

DB_PREFIX."[your_table_name]

Test with "news", "articles", "photos" - these table have table created, and also user_id column
"news" + "news_user"=u.user_id
"articles" + "article_user"=u.user_id

Then your profile can extend into that table.

If you do not have that table yet, you need to code an infusion and install that table before you can pair in UF admin.

**Comment by RobiNN1** [comment]
F:\xampp\htdocs\PHP-Fusion\includes\defender.inc
/administration/user_fields.php?aid=360132ec94fe72a4
Line: 449
Undefined index: required

**Comment by RobiNN1** [comment]
solved
