### ISSUE TITLE
url_bbcode_include.php - Illegal string offset 'index_url_bbcode'

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1154]
url_bbcode_include.php
/site_neu/home.php
Line: 35
	

Severity : Non fatal Runtime Errors
Illegal string offset 'index_url_bbcode'

**Comment by meangczac** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/20288343/a8ae2f06-ab0d-11e6-8318-31971cb72b03.JPG)

It has been covered in upgrade. Add manually into your settings table 

or do this to check  entire PHP-Fusion 7 SQL tables :

// downgrade your php-fusion version in system record  
- execute this code:

```
dbquery("UPDATE ".DB_SETTINGS." SET settings_value = '7' AND settings_name='version'");
```

Then run the installer.

**Comment by Catzenjaeger** [comment]
it was a fresh install (sunday version) :O

**Comment by Catzenjaeger** [comment]
i have this in my database
![ashampoo_snap_2016 11 15_14h56m53s_007_](https://cloud.githubusercontent.com/assets/19621858/20308155/eced2156-ab42-11e6-9179-4235c9aa24fc.jpg)

and in settings version i have 9.02

what i have to do now exactly?

**Comment by meangczac** [comment]
Installation is fine then. I will check the codes where this is implemented.
