### ISSUE TITLE
Member Poll Panel wrong

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1157]
a member can' t vote
a guest can vote!!!

when i logged in and try to vote comes this: Error sending to Vote.

**Comment by Catzenjaeger** [comment]
sorry solved not my problem

**Comment by RobiNN1** [comment]
This is not a issue, your poll is closed (Status: Close) or in your poll is only one option.

**Comment by Catzenjaeger** [comment]
no look here: 

![ashampoo_snap_2016 11 17_18h16m43s_001_](https://cloud.githubusercontent.com/assets/19621858/20399424/3f9da060-acf1-11e6-8573-2cfbc2cd2a07.jpg)
![ashampoo_snap_2016 11 17_18h17m05s_002_](https://cloud.githubusercontent.com/assets/19621858/20399431/435ebe0a-acf1-11e6-9982-734dcdb6cfe2.jpg)

is not closed ...
i have update all files from here for some hours so i can be save that i have the newest files

**Comment by RobiNN1** [comment]
Any error logs?

**Comment by Catzenjaeger** [comment]
no notice or error in admin errors but i get on top of my page a message window with this message: Error sending to Vote

![ashampoo_snap_2016 11 17_18h39m20s_003_](https://cloud.githubusercontent.com/assets/19621858/20400255/406880d4-acf4-11e6-8752-eccef3268ba0.jpg)

guess the problem is ... i have voted as Member "Admin" but i see not the results ... i can vote again and again

**Comment by RobiNN1** [comment]
update poll_classes.inc

**Comment by Catzenjaeger** [comment]
thanx RobiNN1 👍

**Comment by Catzenjaeger** [comment]
guest see only 
![ashampoo_snap_2016 11 17_18h45m04s_004_](https://cloud.githubusercontent.com/assets/19621858/20400455/0cac67f0-acf5-11e6-98b6-ab2f893bf9ff.jpg)

guess before visitors had see the results but cant vote ... now a visitor see nothing :)

**Comment by RobiNN1** [comment]
Polls is only for members

**Comment by Catzenjaeger** [comment]
yes sure but normaly visitors can see the results .. but not the options for voting

**Comment by UnrealCatze** [comment]
someone is wrong again ... i logged in as admin and can vote again but i have vote 2 or more times! . Every time when i new log in!

**Comment by Catzenjaeger** [comment]
i open my page today and log in and now i can vor again :) 
![ashampoo_snap_2016 11 19_16h02m22s_001_](https://cloud.githubusercontent.com/assets/19621858/20456192/aaf12a00-ae70-11e6-9eb7-4c6eaad014ca.jpg)

**Comment by RobiNN1** [comment]
@Catzenjaeger  fixed?

**Comment by Catzenjaeger** [comment]
no

**Comment by RobiNN1** [comment]
update https://github.com/php-fusion/PHP-Fusion/commit/d8fdbecba1fc5398f855cf71601e6a8a4d065876
