### ISSUE TITLE
All locale files in one folder

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1159]
Move infusions, widgets etc. locale files to one folder - /locale/%language%/...
For example:
/locale/Russian/infusions/news
/locale/Russian/widgets/...
...

This is better when all files are located in one place.

**Comment by meangczac** [comment]
For development purpose yes, is OK.  
It's better for sync as well.

**Comment by meangczac** [comment]
I'll leave it open, please close when done.

**Comment by JoakimFalk** [comment]
Just to be clear, can move them one folder down to examle my_infusion/locale/language.php but not to root or all in a mixed folder, that will become very messy. Some are actually in the locale root today while others ar enot so it can be harmonic to do it all as that.
