### ISSUE TITLE
filter.php - Undefined index: un

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1160]
filter.php
/site/infusions/forum/index.php?viewforum&forum_id=16&parent_id=14&sort=view&order=ascending&type=un
Line: 82

Severity : Run-time notices
Undefined index: un

**Comment by Catzenjaeger** [comment]
filter.php
/site/infusions/forum/index.php?viewforum&forum_id=16&parent_id=14&time=2days&type=unsolved&order=as
Line: 102

Severity : Run-time notices
Undefined index: as

**Comment by meangczac** [comment]
Lol.. ok.
