### ISSUE TITLE
 TinyMCE Editor

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1161]
sorry i know we had this for some month but last weekend i have install php Fusiuon new so that i have the newest files. Today i activat my TinyMCE Editor again and  get this:

i use Bottstrap as thema and Old School as Admin Theme

![ashampoo_snap_2016 11 19_16h23m17s_002_](https://cloud.githubusercontent.com/assets/19621858/20456266/c0c0e0ca-ae73-11e6-9663-e6266fbc2a06.jpg)

**Comment by meangczac** [comment]
This is in Admin panel OR is at Front End?

**Comment by Catzenjaeger** [comment]
its overall

**Comment by RobiNN1** [comment]
Here is a problem https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/admin_themes/Old_School/acp_styles.css#L20-L28 , because TinyMCE textarea is in iframe

**Comment by Catzenjaeger** [comment]
solved not my problem .. .:(

**Comment by RobiNN1** [comment]
Update Old-School theme
