### ISSUE TITLE
News Image Gallery

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1163]
![ashampoo_snap_2016 11 19_16h40m24s_003_](https://cloud.githubusercontent.com/assets/19621858/20456398/317dcfba-ae76-11e6-85ed-5e9e4dfd543f.jpg)

**Comment by meangczac** [comment]
Save your news first. Then edit your news.

**Comment by Catzenjaeger** [comment]
dont work or i make some wrong

![ashampoo_snap_2016 11 20_16h14m04s_001_](https://cloud.githubusercontent.com/assets/19621858/20463880/ee41a646-af3c-11e6-9b80-57016d43617e.jpg)

![ashampoo_snap_2016 11 20_16h17m45s_002_](https://cloud.githubusercontent.com/assets/19621858/20463881/f132e266-af3c-11e6-9b03-481c0ff69fd5.jpg)

![ashampoo_snap_2016 11 20_16h18m47s_003_](https://cloud.githubusercontent.com/assets/19621858/20463885/09256e70-af3d-11e6-8510-32aa2da76ad4.jpg)

**Comment by meangczac** [comment]
I'll update the template then. it's old.
