### ISSUE TITLE
Notices after infuse Gallery

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1164]
English.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 43
	
Severity : Run-time notices
Undefined variable: settings
English.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 34
	
English.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 31
	
English.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 33
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 23
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 79
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 64
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 147
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 22
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 36
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 23
	
infusion.php
/site/administration/infusions.php?aid=xxxxxxxxxxxxxx
Line: 37
14 seconds ago

**Comment by meangczac** [comment]
I don't have this in my localhost. Will try again with live server.
