### ISSUE TITLE
Permalinks error

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1169]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/administration/permalink.php?aid=680ee71aac28a1be&enable=articles
Line: 71

Severity : Notice generated by user using trigger_error() function

Query Error: INSERT INTO pf9_permalinks_method (pattern_type, pattern_source, pattern_target, pattern_cat) VALUES ('1', 'print/%type%/%article_id%/%article_title%', 'print.php?type=%type%&item_id=%article_id%', 'normal')
Stack Trace: 
#0 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(63): PDO->prepare('INSERT INTO pf9...') 
#1 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(300): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO pf9...', Array) 
#2 F:\xampp\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO pf9...', Array) 
#3 F:\xampp\htdocs\PHP-Fusion\administration\permalink.php(186): dbquery('INSERT INTO pf9...') 
#4 {main}
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pattern_cat' in 'field list'

F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\MySQLi.inc
/administration/permalink.php?aid=680ee71aac28a1be&enable=blog
Line: 187

Severity : Error generated by user using trigger_error() function

Unknown column 'pattern_cat' in 'field list' @ INSERT INTO pf9_permalinks_method (pattern_type, pattern_source, pattern_target, pattern_cat) VALUES ('2', 'blogs', 'infusions/blog/blog.php', 'normal')

**Comment by meangczac** [comment]
How is it possible? column `pattern_cat` IS IN the method table..

and I can install fine.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/c5bef93c0b14b26d9861cd35383018b1842cce1e

Ok, Rizado already fix.
