### ISSUE TITLE
Permalinks doesn't works

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1172]
I enabled all of permalinks addons (news, blog, etc).

But on site I have normal links ( ex. infusions/news/news.php?readmore=1) without alias.

Also in "Permailnk settings" I can't set ENABLE to any of settings. When I try change status to enable and press button "Save settings" i see error "There was an error while processing your request".

I dont have any errors in log.

read more: https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38031
Version 9.02

**Comment by meangczac** [comment]
And you can use Permalink in RC4 copy but not for this 9.02 copy?

**Comment by kosiorski-eu** [comment]
exactly. Here i have 9.00.00 PHP Version, and here permalinks works: ex. http://www.tomaszowiak.pl/wiadomosci/23494/Urzad-Miasta-oglasza-nabor-na-stanowisko-urzednicze-ds.-gospodarki-komunalnej

But here I have clean instalation 9.02 and permalinks doesnt works: ex. http://kos.kylos.pl/www/portal/infusions/blog/blog.php?readmore=1

Both sites are on the same server.

**Comment by meangczac** [comment]
Do you have latin characters in your url?

**Comment by meangczac** [comment]
Check again.

**Comment by RobiNN1** [comment]
On my site now works

**Comment by kosiorski-eu** [comment]
I downloaded all files again to make a new installation. But now I can't even start install PHP Fusion. I see only blank page, without anything, any errors, any alerts. 

http://kos.kylos.pl/www/cms

**Comment by meangczac** [comment]
Your URL. It's wierd... why it's like that?

https://www.kylos.pl/install.php
https://www.kylos.pl/cms/install.php

These URL. 

Go to your php.ini - display_errors set it to 'On'

**Comment by kosiorski-eu** [comment]
These urls are temporary, I'm using these only for testing.
I'm just created new domain which  is directed to the folder with PHP Fusion files.

Situation it's the same - visit www.kosiorski.eu


Five minutes age for more tests I installed PHP Fusion on my local server. After finished installation i see error: 

> Fatal error: require_once(): Failed opening required 'themes/FusionTheme/ThemePack/1/Theme.php' (include_path='.;E:\FTP\php\PEAR') in E:\FTP\htdocs\PHP-Fusion\themes\FusionTheme\ThemeFactory\Core.php on line 107

**Comment by meangczac** [comment]
yes already fix as well.

**Comment by kosiorski-eu** [comment]
OK. Now i can finish installation well, but sometimes something still goes wrong:
https://www.youtube.com/watch?v=YklzyuRWHGI&feature=youtu.be
-- edit--
But this happening only when category is empty. When category has some news it works well.

This works for me only in local server, on www.kosiorski.eu. There I updated files today, but still does nothing. Only blank page. 

Errors:

> 
> [28-Nov-2016 10:50:50 Europe/Warsaw] PHP Warning: require(/home/kos/public_html/www/cms/includes/classes/PHPFusion/Installer./Requirements.core.inc): failed to open stream: No such file or directory in /home/kos/public_html/www/cms/includes/classes/PHPFusion/Installer/Install.core.inc on line 321
> 
> [28-Nov-2016 10:50:50 Europe/Warsaw] PHP Warning: require(/home/kos/public_html/www/cms/includes/classes/PHPFusion/Installer./Requirements.core.inc): failed to open stream: No such file or directory in /home/kos/public_html/www/cms/includes/classes/PHPFusion/Installer/Install.core.inc on line 321
> 
> [28-Nov-2016 10:50:50 Europe/Warsaw] PHP Fatal error: require(): Failed opening required '/home/kos/public_html/www/cms/includes/classes/PHPFusion/Installer./Requirements.core.inc' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/kos/public_html/www/cms/includes/classes/PHPFusion/Installer/Install.core.inc on line 321

**Comment by meangczac** [comment]
Please make it public...

![screen shot 2016-11-28 at 7 54 08 pm](https://cloud.githubusercontent.com/assets/4078041/20667493/77b41d74-b5a4-11e6-9fae-09971ff028f7.png)

**Comment by meangczac** [comment]
Oh. got a typo ----> '.' extra. 

https://github.com/php-fusion/PHP-Fusion/commit/86b322a74e5c4464036690d02b53195f890e8f8e

**Comment by kosiorski-eu** [comment]
OK. Now it's good. My installation finished successfully. 

I actually have still wrong redirect in Home and News Categories (on Permalink mode). 
I changed video access to public. https://www.youtube.com/watch?v=YklzyuRWHGI&feature=youtu.be

**Comment by Rizado** [comment]
After update permalinks doesn't work...

**Comment by kosiorski-eu** [comment]
I found another bug. To the blog item i can add only one category. 
https://youtu.be/KCPtGPoqpJI

**Comment by PHPFusion-Ar** [comment]
works now with me :D

**Comment by Rizado** [comment]
I still have the same problem.

Permalinks do not displayed on the pages for which they are disabled even if target is enablen.
See. I have news, articles, blogs and weblinks. For news, articles and blogs permalinks are enabled, for weblinks is disabled. When I open pages /news, /articles or /blog - all right, permalinks works and are displayed as  /news, /articles or /blog. But when I open /infusions/weblinks/weblinks.php - permalinks for news, articles and blogs are now displayed too. I see these links as /infusions/news/news.php, /infusions/articles/articles.php and infusions/blog/blog.php...

**Comment by meangczac** [comment]
Try turning on everything. It works.
