### ISSUE TITLE
select2 blows width way out of proportions in news rating

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1173]
![select_2](https://cloud.githubusercontent.com/assets/4210004/20627830/e6f0c5d6-b322-11e6-8c83-8fff4999995a.png)
See the width, it makes the theme scrollable sideways.

**Comment by meangczac** [comment]
@RobiNN1, can you help me check the inner_width or width. It's just HTML problem.

I work with Installer still.
