### ISSUE TITLE
Format build as text

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1177]
Now build number is formatted as number. Nut in different langauges are different decimal separators. And in English locale build number is displayed as 9.02 (with a dot) but in Russian it's displayed as 9,02 (now with a comma).

**Comment by meangczac** [comment]
as long as they work with this: http://php.net/manual/en/function.version-compare.php

If 9,02 <= 9.01 affected users is all language. So I think best put 9.02
