### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1180]
step 4.
![capture_001_01122016_100903](https://cloud.githubusercontent.com/assets/16163102/20787856/51ea3b26-b7ae-11e6-9992-fd7e375caa5b.jpg)

 not work progress bar, but there is addNotice()..

step 5.
error message only works with password, nothing else.

**Comment by meangczac** [comment]
Fix the real bugs first. I like this layout... waiting someone to contribute HTML.

![bt_1x](https://cloud.githubusercontent.com/assets/4078041/20864210/bd40a750-ba21-11e6-8852-eaaaaa29197c.png)

**Comment by karrak1** [comment]
step 1
token error ..

![capture_001_04122016_062703](https://cloud.githubusercontent.com/assets/16163102/20864291/cf263f52-b9ea-11e6-8338-4c4b136d2fc0.jpg)

**Comment by meangczac** [comment]
updated to today's git?

**Comment by karrak1** [comment]
Now I downloaded, One of the topics starter is faulty.

**Comment by meangczac** [comment]
Yes, there is a problem with the new token method. I've revised.

https://github.com/php-fusion/PHP-Fusion/commit/97514b11d080aaf013439e9a2ab12c632b1a56e2

I have to resort to old method, because of the config dependencies couldn't do better code.

**Comment by karrak1** [comment]
token OK..
 step 4 as before, 
step 5.
error message only works with password, nothing else.

**Comment by meangczac** [comment]
Yes error message I recognize. I haven't check why yet. But I'll see to it.

**Comment by RobiNN1** [comment]
Rebuild .htaccess doesn't work.
HTTP ERROR 500

**Comment by karrak1** [comment]
no change,
step 4, and step 5.
error message only works with password, nothing else.

**Comment by JoakimFalk** [comment]
Solved?

**Comment by karrak1** [comment]
step 4 still bad 
[(https://cloud.githubusercontent.com/assets/16163102/20787856/51ea3b26-b7ae-11e6-9992-fd7e375caa5b.jpg)]

**Comment by meangczac** [comment]
I will start on this next.
