### ISSUE TITLE
Blog categories and end date 

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1181]
Bugs what i find:

- I can't add more than one category to blog item. 
- End Date doesn't works well. Even if I set future date, the blog item always is hidden

https://youtu.be/Wcai3HxcSrM

**Comment by kosiorski-eu** [comment]
OK. Now end date of blogs item works. 
**But I still can't add more than one category to blog item.**

**Comment by meangczac** [comment]
I think it's an SQL column error. Please check blog_cat in your DB_BLOGS. Change it to TEXT

Not sure furbarred when - upgrade? new install?

**Comment by kosiorski-eu** [comment]
**YES! You were right! It's working now. Thank You :)** 

On me site for main news channel I'm using a Blog Infusion (because I can add more than one category). But now in the newest version of PHP Fusion in a News Infusion we have included new system of images gallery. 

Please tell me one thing more, which modification will be easier. Add gallery system to the Blog Infusion or add possibility multiple categories to News Infusion?  I tried few times the second option but without effect.

**Comment by meangczac** [comment]
The news infusion is built to make site news.

The blog infusion is built to make blog. 

It is what we needed. News dont need multiple category because it makes the news confusing!
