### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1183]
![capture_001_04122016_095136](https://cloud.githubusercontent.com/assets/16163102/20865055/4ae8ecc2-ba07-11e6-9273-b65c45768644.jpg)

More drop-down menu, then both down automatically.
photo.. (click Beküldések)

**Comment by meangczac** [comment]
What is the bug again? Explain what is needed?

**Comment by karrak1** [comment]
Navigation panel, site link
create 2 drop down menu (forum and Submissions)
click forum
flips down 2 drop down menu  (forum and Submissions)
click submission 
flips down 2 drop down menu  (forum and Submissions)

**Comment by meangczac** [comment]
How do you get this in the first place? Wait. I'll update the theme so I can scroll down and show you.

**Comment by meangczac** [comment]
![image](https://cloud.githubusercontent.com/assets/4078041/20885745/733b54ea-bb2d-11e6-992b-f1247773c0e7.png)

Is Ok when I'm doing a clean install. Are you meaning those values is present for upgrades?
