### ISSUE TITLE
installer doesent work .. site works not after install

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1186]
i have download the complette paket for some minutes
i have a lot of errors on install and after the install on site ... looks like a mobile style ot wahtever but i use only pc

the installer locks complet wrong
the site after install is not to use nothing works

![ashampoo_snap_2016 12 04_15h35m17s_001_](https://cloud.githubusercontent.com/assets/19621858/20866848/6ce0ae52-ba37-11e6-8019-1ba53c8bacc4.jpg)

![ashampoo_snap_2016 12 04_15h36m03s_002_](https://cloud.githubusercontent.com/assets/19621858/20866850/6fb711ac-ba37-11e6-91f6-c3109f5fd7cc.jpg)

**Comment by UnrealCatze** [comment]
same ... not fixed

**Comment by meangczac** [comment]
There must be an error message. Give me error message. I can't fix what is not broken. I'm not even sure where to check. Give me something.. 😈

**Comment by UnrealCatze** [comment]
works now

**Comment by meangczac** [comment]
😱 😱 😱 ... magic. Thank you. Close
