### ISSUE TITLE
Formatting texts wrong

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1190]
editor:
![ashampoo_snap_2016 12 05_22h24m18s_005_](https://cloud.githubusercontent.com/assets/22166864/20902987/f22b463c-bb39-11e6-80c5-cc7d6545f87a.jpg)

on site: 
![ashampoo_snap_2016 12 05_22h24m01s_004_](https://cloud.githubusercontent.com/assets/22166864/20902991/f81c906e-bb39-11e6-808a-11997ceadb05.jpg)

code:
```
<!-- Description -->
					<div class="row m-0">
					  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
						<div class="navbar-default text-smaller text-uppercase text-bold"><?= $locale['figure_423']; ?></div>
					  </div>
					  <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
						<span class="small" style="word-break: break-all; word-wrap: break-word;"><?= ($info['figure']['general']['description'] ? $info['figure']['general']['description'] : $noInformations); ?></span>
					  </div>
					</div>
```

				// Accessories and Description
				"accessories" => parse_textarea(strip_tags($data['figure_accessories'])),
				"description" => parse_textarea(strip_tags($data['figure_description'])),

**Comment by JoakimFalk** [comment]
Don´t think it is a Fusion error, add nl2br function on your output side.
