### ISSUE TITLE
Redirect after errorlog goes very wrong with SEO on even if not in SEOed Module area

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1198]
/RC7/my_non_seoed_dir/RC7/my_non_seoed_dir/my_non_seoed_filed.php
see screen
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/21037102/4615b5fa-bdcb-11e6-88d2-fe4f33d1ccf8.jpg)

**Comment by meangczac** [comment]
This one should be fixed already.
