### ISSUE TITLE
Multiple categories in News Infusion or gallery system in Blog Infusion

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1200]
On me site for main news channel I'm using a Blog Infusion (not News Infusion, because in Blog I can add more than one category). But now in the newest version of PHP Fusion in a News Infusion we have included new system of images gallery.

Please tell me one thing, which modification will be easier. Add gallery system to the Blog Infusion or add possibility multiple categories to News Infusion? I tried few times the second option but without effect.

**Comment by DavidGuetl** [comment]
I think it will be easier you add multi categories to news.

**Comment by meangczac** [comment]
You can submit to us if you're able and want to. For now, the PF9 doesn't have this requirements. Someday, we will probably just redo the whole thing.
