### ISSUE TITLE
Forum - images

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1201]
plz fix this ot make an option

this destroys the complete forum 

![ashampoo_snap_2016 12 09_20h32m13s_002_](https://cloud.githubusercontent.com/assets/22166864/21061879/9bc8f466-be4e-11e6-82c1-0994b30a436a.jpg)

**Comment by UnrealCatze** [comment]
hmnnn better but not perfect. Image is not clickable so none can see the image complete
We definitely need a better and different solution

**Comment by Catzenjaeger** [comment]
other soultion?
sorry guys but its looks terrible 
better a thumb and with click a bigger version or whatever
atm i have a box from 50 % --- 50 % rest is space 

![grafik](https://cloud.githubusercontent.com/assets/19621858/22936966/5f7a776a-f2d7-11e6-9e07-ee82af8c0c3f.png)

**Comment by Catzenjaeger** [comment]
is it possible to add images responsive in forum? guess this would be the best solution.

**Comment by Catzenjaeger** [comment]
new try:

![grafik](https://cloud.githubusercontent.com/assets/19621858/22944171/2002da5a-f2f0-11e6-8356-d5f6ae8de9e9.png)

result:
![grafik](https://cloud.githubusercontent.com/assets/19621858/22944188/2ec6e1a8-f2f0-11e6-9a0d-e3c603c736ca.png)

loks better but the image is not correct ,,,, when i scoll the image willnot be resized

ok guess i have found the problem!!!!
![grafik](https://cloud.githubusercontent.com/assets/19621858/22944772/133d3fc0-f2f2-11e6-9019-9e0efa0506d7.png)

**Comment by meangczac** [comment]
We're at responsive design. Full scale image without automatic resize is not wise.

All image unless small by default should attach ````<img class='img-responsive'...````

**Comment by Catzenjaeger** [comment]
perfect ... many thanks for this fix ... now all looks fine 💯 

![grafik](https://cloud.githubusercontent.com/assets/19621858/23022272/2fb9fa08-f450-11e6-9bb9-be1afcc1881d.png)
