### ISSUE TITLE
is someone changed on Social Media or Open Graph?

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1202]
since last weekend where i have update all my core files it was possible to share my figures to facebook ... no its not possible anymore. its someone changed in core files?

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commits/9.02/themes/templates/layout.php 

Check and see which one.

**Comment by DavidGuetl** [comment]
Ok .. how we can change Open Graph Metatags?

If i deactivate the complete Modul and add it with add_to_head () all works fine. 

But if i deactivate, the Open Graph Meta doesnt work anywhere :P

But if the Modul acticated, i just have Duplicates.

Add_meta () or add_to_meta () can not be used, because it works only for Metatags with name='' not witn property=''

**Comment by Rizado** [comment]
@DavidGuetl I'll check this today evening (Moscow time). OpenGraph was added by me.

**Comment by DavidGuetl** [comment]
Ok Thanks!

I am hopefull, we will find a realistic solution :-)

**Comment by Rizado** [comment]
@DavidGuetl I saw code, it was changed since first edition - added classes, changed array structure etc.
It's need to rewrite almost completely. I cannot do it in work days and I'll try at Saturday,

@FrederickChan what you mean about new class for OpenGraph tags? I want to create it.

**Comment by Rizado** [comment]
Now OpenGraph class is mostly written, I'll test it tomorrow.
It will be extensible, you can add functions for any content infusion like this:

```
class OpenGraphNews extends OpenGraph {
  public function ogNews($newsid = 0) {
  // place your code here
  }
}
```

P.S. Today my commit with fix is preparing for new implementation.

**Comment by meangczac** [comment]
@rizado , I'll leave it up to you.

**Comment by Rizado** [comment]
OK, now it works for Custom Pages and User Profiles.
It will be added for News, Aricles etc. soon.

**Comment by Rizado** [comment]
Now OpenGraph is ready for: Custom Pages, User Profiles, News, Articles, Blogs and Downloads.
For Gallery and Forum it will be ready in 2-3 days - I don't use this infusions for myself and I have to create site for test purposes. Weblinks and FAQ - I don't know - is this needed?
I close issue.
