### ISSUE TITLE
login.php panel / div error?

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1203]
![ashampoo_snap_2016 12 11_13h07m11s_003_](https://cloud.githubusercontent.com/assets/22166864/21079961/a9b270f2-bfa2-11e6-9a31-82f8556a35f7.jpg)

**Comment by RobiNN1** [comment]
yes

**Comment by UnrealCatze** [comment]
where? Its only on login page .. all other sites are ok :O

**Comment by RobiNN1** [comment]
check forum thread panel  or top stats panel
