### ISSUE TITLE
Undefined index: thread_tags

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1206]
view.php
/site/infusions/forum/viewthread.php?action=edit&forum_id=15&thread_id=31&post_id=32
Line: 534

Severity : Run-time notices
Undefined index: thread_tags

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/9930e9fd26c34faadf6bc9c6ecec77baf78713f5
