### ISSUE TITLE
Database - Everyone can see Database Account Details.

### ISSUE THREAD

**Issue by DavidGuetl** [PHPFusion/PHPFusion#1208]
Hey my Friends!

Currently, i tought, i test the new PHP-Fusion from Github and create the Locale Files for German Peoples.
So, i installed XAMPP on my PC and install PHP-Fusion in it.

All was fine.

But now, my PC restart and cut off the XAMPP Service. So i start XAMPP Controll Panel and start Apache (forget of MySQL Server) and open my Website. Logic, i get a Error. But in this Error i can see all my MySQL Account Details.

I am not Sure, if i can also see it when i test it on a Real Space, but i think it is possible too.

At the End, i post also a Screenshot (and Sorry for my very bad English today).

![database](https://cloud.githubusercontent.com/assets/19527428/21132825/46028ebe-c116-11e6-85fb-18dafde1dbcc.png)

**Comment by meangczac** [comment]
Check and see. Why i use groups crash in the first place. Your at the very fundamental error here.. totally no database. The debug merely shows you what connection parameters you use.
