### ISSUE TITLE
Edit Blog - NON TinyMCE Mode - Removes manually entered <br´s /> and throw a notice

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1210]
There are error in the log, one of them in the \ includes \ classes \ PHPFusion \ Locale.inc

Line 106 ---- $ result = $ words_array [$ form];
(Undefined offset: 2)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38090&pid=200899

**Comment by meangczac** [comment]
First off, the $word_array[$from] should not be present unless locale is outdated. It's explode on | on the locale i.e. "Chair|Chairs". <--- $from. and undefined offset 2 means there is a 3rd one required.
I'm asking @rizado to look at it as I'm not literate on Russian formats.

But manually entered <br's/> is.... totally another thing. I've checked Blog and they all parse line breaks good. So we'll be omitting this fact.

**Comment by Rizado** [comment]
He uses Russian locale or Ukrainian? As I know, Ukrainian is not updated very long ago and I have no time to support both (I understand Russian, Ukrainian and Belarusian languages).
I'll check blog locale again.

**Comment by Rizado** [comment]
Russian, Ukrainian, Belarusian and maybe other Slavic languages have two plural forms of words. And sometimes for plural form may be used the same form of word that for single :-) .

**Comment by Rizado** [comment]
OK, I checked. format_word() function is used 5 times in Blogs, all locale items are defined. 
Please ask user to update locale first - it was updated 9 days ago.
