### ISSUE TITLE
forum_main.php - Invalid argument supplied for foreach() + Undefined index: filter

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1211]
forum_main.php
/site/infusions/forum/tags.php?tag_id=2?tag_id=2
Line: 566

Severity : Non fatal Runtime Errors
Invalid argument supplied for foreach()

forum_main.php
/site/infusions/forum/tags.php?tag_id=2?tag_id=2
Line: 557

Severity : Run-time notices
Undefined index: filter

**Comment by RobiNN1** [comment]
Your url is incorrect use **tags.php?tag_id=2** no **tags.php?tag_id=2?tag_id=2**
