### ISSUE TITLE
Carousel does not auto start - Nebula

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1212]
Example,
http://brzanek.webd.pl/13122016/pages/1/Home , the  carousel does not move 
Thread,
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38089&pid=200910

**Comment by djdandi** [comment]
After the changes still did not work.

**Comment by djdandi** [comment]
Now scroll work but still amend your liquidity

**Comment by meangczac** [comment]
@djdandi, What is Liquidity? Interval?

**Comment by meangczac** [comment]
I assume liquidity is as meant as the transitions speed. You can find them documentation in bootstrap documentation guide.
