### ISSUE TITLE
Missing line in php file NEWS INFUSIONS

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1214]
In file **infusions/news/classes/admin/controllers/news.php**  I found missing line (private function execute_NewsUpdate())
`'news_name' => form_sanitizer($_POST['news_name'], '', 'news_name'),`
Without this line, new items in News infusion are always added by user with ID = 1 (default value in MySQL row), not by actualy logged user.

**Comment by meangczac** [comment]
Can you submit a push patch in the future ? I'm sure there isn't much to review.

**Comment by kosiorski-eu** [comment]
Yes, I would like to help in this way, but for now I don't know how software GITHUB works.. I will learn more about it, and then I could help

**Comment by JoakimFalk** [comment]
I use https://desktop.github.com/

It is awesome and makes it very simple. before I used commandline and it was a tad more tricky.
Anyway for desktop
Just make sure you connect to php-fusion, get that directory to your localhost.
Now any changes or files your replace will be flagged as changed in Github Desktop.
Select a Summare / description on these changes in the changes TAB. ( important ). 
Then push Comment to 9.02 ( in this case ) and your changes are pushed or made as push request.

For commandline, 

Switching between branches:
Git checkout branchname

Adding the change to update list:
Git add *

Commit:
Git Commit -m "my comment"

Sending:
Git push
git push --force (if error occurs)


If you can't see branch names:
git fetch

Downloading files for the branch (switch to the branch before!):
git checkout

Resetting the commit before sending:
git reset


let's say you want to update some files on 7.02.07
*git checkout 7.02.07 (so we switch to the branch)
*git checkout (i double do this to guarantee downloading all files, it should do from the top command though)
*I open my editor, update the files, copy the stuff etc. etc.
*git add * (so it tries to add all files to commit (and understands all of your manual last edits automatically) (you can also use like "git add maincore.php"))
* git commit -m "update" -a eller *git commit -m "update"
*git push (upload to server)
