### ISSUE TITLE
spam attacks and other

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1218]
hello,  is it possible to add a function that use a spamlist with all forum spamers ect. .
my problem since i have phpF9 site i have forum spam and many fake members (6 in last 3 days) with .ru adress

https://stopforumspam.com/ help this? 
all members that was registered in my system i have found in this site and database

**Comment by Rizado** [comment]
This site has API. I'll register and check some later, in 30 minutes I have to go to job.

I see next way - to add a hook to register procedure. Site admin will be able to use own functions for user checking before adding user to DB. This function must return boolean value - is this user allowed to register? How to check - we may leave this to site admins :-) .

**Comment by meangczac** [comment]
Well, we can make a query and insert into the server the IP records into our blacklist.

**Comment by JoakimFalk** [comment]
Let´s roadmap these for any later versions if the issues still exists.
