### ISSUE TITLE
Incorrect select from database

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1219]
When I use Russian (Ukrainian, Belarusian and others where comma is used as decimal separator) locale, dbquery() function is now work properly. When in result exists float value, it's "trimmed" to integer because there are different decimal separators in DB and site.
First part I fixed by myself - https://github.com/php-fusion/PHP-Fusion/commit/c8c76d8d92e806fa99f5624996e9458a538cf07c

**Comment by meangczac** [comment]
Check this: 
1. http://php.net/manual/en/function.money-format.php
2. http://php.net/manual/en/function.localeconv.php
