### ISSUE TITLE
Different status for draft

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1221]
Sometimes for publishing status is used field named "draft" (0 - published), sometimes - field "status" (1 - published).
Is it real to make this field unified for all type of content and categories?
See:
Custom pages: 'page_status';
News: 'news_draft', 'news_cat_draft';
Articles: 'article_draft', 'article_cat_status' (???)...

**Comment by meangczac** [comment]
draft = 1 means draft active
status = 1 means status active

we will use boolean 1/true 0/false so it is easy with php.
````
if ($data['status'])  {
// is ON
}
````
i've told David to change.

**Comment by DavidGuetl** [comment]
Articles changed.

Weblinks Recoding will also work with this schema ;-)

**Comment by Rizado** [comment]
But is possible use field with the same name for different content types?

**Comment by meangczac** [comment]
Support issues could be nightmare. Let's not. It's just an article anyway, let's not risk it. We keep DB_ARTICLE_CATS intact. Less headache. There could be articles ratings and comments, and theme dependencies right now. I want to bet safe especially this is a core system. Dropping category could prove to be a massive headache. But Articles can add a column Article_Content_Type for making more kinds of content type after table, it's a pretty good idea anyway, **except** being a category.
