### ISSUE TITLE
Search Downloads 

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1223]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/search.php **
Line: 71

Severity : Notice generated by user using trigger_error() function

Query Error: SELECT td.*,tdc.* tu.user_id, tu.user_name, tu.user_status, tu.user_avatar, tu.user_joined, tu.user_level FROM pf9_downloads td INNER JOIN pf9_download_cats tdc ON td.download_cat=tdc.download_cat_id LEFT JOIN pf9_users tu ON td.download_user=tu.user_id WHERE tdc.download_cat_language='English' AND 1 = 1 AND (download_title LIKE :sword00 || download_description LIKE :sword01 || download_user LIKE :sword02)ORDER BY download_datestamp DESC
Stack Trace: 
#0 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(63): PDO->prepare('SELECT td.*,tdc...') 
#1 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT td.*,tdc...', Array) 
#2 F:\xampp\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT td.*,tdc...', Array) 
#3 F:\xampp\htdocs\PHP-Fusion\includes\search\search_downloads_include.php(88): dbquery('SELECT td.*,tdc...', Array) 
#4 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Search\Search_Engine.inc(503): include('F:\\xampp\\htdocs...') 
#5 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Search\Search_Engine.inc(425): PHPFusion\Search\Search_Engine::__Load('search_download...') 
#6 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Search.inc(34): PHPFusion\Search\Search_Engine::display_results() 
#7 F:\xampp\htdocs\PHP-Fusion\search.php(20): PHPFusion\Search::display_search() 
#8 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'tu.user_id, tu.user_name, tu.user_status, tu.user_avatar, tu.user_joined, tu.use' at line 2

**Comment by RobiNN1** [comment]
Not solved

**Comment by meangczac** [comment]
What is your input ? How do you search? which button active? all or just downloads? Thanks.

**Comment by RobiNN1** [comment]
Here is my test download file https://rncdn.ml/pf9/infusions/downloads/downloads.php
If I give the search in the top menu of the seach bar "test",  write this error

PDOMySQL.inc
/pf9/search.php?stype=all **
Line: 71

Severity : Notice generated by user using trigger_error() function

Query Error: SELECT td.*,tdc.* tu.user_id, tu.user_name, tu.user_status, tu.user_avatar, tu.user_joined, tu.user_level FROM pf9_downloads td INNER JOIN pf9_download_cats tdc ON td.download_cat=tdc.download_cat_id LEFT JOIN pf9_users tu ON td.download_user=tu.user_id WHERE tdc.download_cat_language='English' AND 1 = 1 AND (download_title LIKE :sword00 || download_description LIKE :sword01 || download_user LIKE :sword02)ORDER BY download_datestamp DESC
Stack Trace: 
#0 /home/u418250512/public_html/pf9/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('SELECT td.*,tdc...') 
#1 /home/u418250512/public_html/pf9/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT td.*,tdc...', Array) 
#2 /home/u418250512/public_html/pf9/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT td.*,tdc...', Array) 
#3 /home/u418250512/public_html/pf9/includes/search/search_downloads_include.php(85): dbquery('SELECT td.*,tdc...', Array) 
#4 /home/u418250512/public_html/pf9/includes/classes/PHPFusion/Search/Search_Engine.inc(503): include('/home/u41825051...') 
#5 /home/u418250512/public_html/pf9/includes/classes/PHPFusion/Search/Search_Engine.inc(425): PHPFusion\Search\Search_Engine::__Load('search_download...') 
#6 /home/u418250512/public_html/pf9/includes/classes/PHPFusion/Search.inc(34): PHPFusion\Search\Search_Engine::display_results() 
#7 /home/u418250512/public_html/pf9/search.php(20): PHPFusion\Search::display_search() 
#8 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'tu.user_id, tu.user_name, tu.user_status, tu.user_avatar, tu.user_joined, tu.use' at line 2

**Comment by karrak1** [comment]
fix

**Comment by meangczac** [comment]
Thanks guys.
