### ISSUE TITLE
Template Function Changes

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1226]
http://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38135&pid=201037
@FrederickChan  render_userform() is for edit profile and for register is display_registerform().
Now is display_register_form() for edit and register.
One template for edit profile and register form?

**Comment by meangczac** [comment]
I think there is one that is deprecated. Need to clean up.

**Comment by RobiNN1** [comment]
Solved, this is not perfect solution but it works.
```php
function display_register_form($info) {
    if (FUSION_SELF == 'edit_profile.php') {
        MaterialTheme\Templates\Profile::EditProfile($info);
    } else if (FUSION_SELF == 'register.php') {
        MaterialTheme\Templates\Profile::Register($info);
    }
}
```

**Comment by meangczac** [comment]
I'll be back on this one.
