### ISSUE TITLE
mod_rewrite

### ISSUE THREAD

**Issue by Shadowsilk** [PHPFusion/PHPFusion#1227]
it looks like `mod_rewrite` is not enabled on your host. Enabling SEF urls might break your website. Please contact your hosting provider about enabling `mod_rewrite` on your host.
tried to force using rewrite with Rewrite Engine On in file .htaccess - but nothing happend

Using Plesk 17 (onyx) on Centos 7. Apache mod_rewrite activated (no nginx in use, no proxy, only Apache mode served with PHP-FPM)

**Comment by meangczac** [comment]
The notice is in permalink admin right?

The conditions are as follows:
````
// Check if mod_rewrite is enabled
$mod_rewrite = FALSE;
if (function_exists('apache_get_modules') && in_array('mod_rewrite', apache_get_modules())) {
    $mod_rewrite = TRUE;
} elseif (getenv('HTTP_MOD_REWRITE') == 'On') {
    $mod_rewrite = TRUE;
} elseif (isset($_SERVER['IIS_UrlRewriteModule'])) {
    $mod_rewrite = TRUE;
} elseif (isset($_SERVER['HTTP_MOD_REWRITE'])) {
    $mod_rewrite = TRUE;
}
````
See if your server can meet this. We have put one of four conditions to pass check. Yours failed all?

For more information, you can see this thread here:
https://talk.plesk.com/threads/htaccess-mod_rewrite-or-change-iis-to-apache.313094/

PF 9 is developed on Linux env + Apache, Linux env on Windows + Apache. On local env, we use tools like Xampp, MAMP, etc.

Let us know what resolved this issue for you.

**Comment by Shadowsilk** [comment]
It's failed, but rewrite engine is on.
following code snippet solved this issue:
(at top of .htaccess file)

<IfModule mod_rewrite.c>
    # Tell PHP that the mod_rewrite module is ENABLED.
    SetEnv HTTP_MOD_REWRITE On

    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # The rest of your rewrite rules here
</IfModule>
[....]

After that, the message on 'Admin Panel -> System Admin -> Permalinks' dissapeared
Maybe Apache 2.4 is not announcing mod_rewrite anymore, settings tells only 'rewrite' is on.

**Comment by Shadowsilk** [comment]
actually failed. Trying some tests. Rewrite engine is on and works fine, not sure, why checks not passed that way.

following entry in .htaccess dissapears the message, but if I change any settings (Permalinks menu at admin dash), file would be modified and this manually entered code will be deleted again.
```
<IfModule mod_rewrite.c>

    # Tell PHP that the mod_rewrite module is ENABLED.
    SetEnv HTTP_MOD_REWRITE On

    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # The rest of your rewrite rules here

</IfModule>
```

 it didn't worked for Apache as the apache_get_modules() was disabled but the mod_rewrite was enable in that server.

**Comment by RobiNN1** [comment]
Enable manually from database. In prefix_settings change site_seo to 1.
I had the same problem on my web host.
