### ISSUE TITLE
Weblinks Search Module

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1228]
Query Error: SELECT tw.*,twc.* FROM phpfusion_weblinks tw INNER JOIN phpfusion_weblink_cats twc ON tw.weblink_cat=twc.weblink_cat_id WHERE twc.weblink_cat_language='English' AND tw.weblink_language='English' AND 1 = 1 AND (weblink_name LIKE :sword00)
Stack Trace: 
#0 C:\MAMP\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(63): PDO->prepare('SELECT tw.*,twc...') 
#1 C:\MAMP\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT tw.*,twc...', Array) 
#2 C:\MAMP\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT tw.*,twc...', Array) 
#3 C:\MAMP\htdocs\PHP-Fusion\includes\search\search_weblinks_include.php(70): dbquery('SELECT tw.*,twc...', Array) 
#4 C:\MAMP\htdocs\PHP-Fusion\includes\classes\PHPFusion\Search\Search_Engine.inc(503): include('C:\\MAMP\\htdocs\\...') 
#5 C:\MAMP\htdocs\PHP-Fusion\includes\classes\PHPFusion\Search\Search_Engine.inc(430): PHPFusion\Search\Search_Engine::__Load('search_weblinks...') 
#6 C:\MAMP\htdocs\PHP-Fusion\includes\classes\PHPFusion\Search.inc(34): PHPFusion\Search\Search_Engine::display_results() 
#7 C:\MAMP\htdocs\PHP-Fusion\search.php(20): PHPFusion\Search::display_search() 
#8 {main}
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tw.weblink_language' in 'where clause'

**Comment by karrak1** [comment]
Missing update weblink_language, improving

**Comment by meangczac** [comment]
Thanks @karrak1
