### ISSUE TITLE
Notices in Photo Admin when creating an album and add a photo to it

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#123]
classes/Admin.php unlink(../../infusions/gallery/albums/thumbs/) [function.unlink]: No such file or directory Line: 703
classes/Admin.php unlink(../../infusions/gallery/albums/) [function.unlink]: Is a directory Line: 704
classes/Admin.php unlink(../../infusions/gallery/albums/thumbs/) [function.unlink]: No such file or directory Line: 702

**Comment by JoakimFalk** [comment]
![photo-image-boxes-can-have--heights](https://cloud.githubusercontent.com/assets/4210004/9353825/c7e0ec9a-466b-11e5-8987-04c39aab5023.png)

**Comment by meangczac** [comment]
Mass uploader simplified. Dropped FTP up add photo.
