### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1230]
When I try to install PHP-Fusion I have this message:

> Fatal error: Can't use function return value in write context in /home/victor09/%my_domain_name%/www/includes/classes/PHPFusion/Installer/Steps/Introduction.inc on line 41

It's regardless of new install or upgrade.

**Comment by Rizado** [comment]
@RobiNN1 , thanks, I'll check right now,

**Comment by Rizado** [comment]
Problem still exists.

**Comment by RobiNN1** [comment]
Any errors?

**Comment by Rizado** [comment]
The same error.
