### ISSUE TITLE
News - Comments on logged in users do not work

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1231]
Hello Developers,

This is only noticeable to me today that I can not comment on the news as a logged in user. I'll show you a screenshot.

![News-Comments not worked](https://you-big-blog.net/blog/wp-content/uploads/2017/01/php-fusion902-comments-not-worked.jpg)

It is so that if I want to comment and send the comment, then I will be displayed, the field is not filled.

Before I see the visual editor in the comment area, but then he disappears and I can not insert links. HTML does not work without the visual editor in the comments.

Can you see this again? Thanks in advance.

**Comment by meangczac** [comment]
Hello Alex, can I ask few things:
1. SEO on or off?
2. Ajax on or off? 

Whats the combo here.

**Comment by ghost** [comment]
Hello Frederick,

Thanks for the fix. Unfortunately, the problem continues with me. As an anonymous guest with ReCaptcha I can not comment.

How do I enable Ajax? SEO is switched on with me.

Is it possible to install or integrate Disqus comments in PF 9.0.2? That would be my favorite.

Thanks in advance.

**Comment by ghost** [comment]
Now I have implemented Disqus comments. I'm going to work now.

**Comment by meangczac** [comment]
Great, make it done on an addon level for the convenience of syncing on your forks later.
Thanks.
