### ISSUE TITLE
Infusing an Infusion gets thru even with errors, could we not halt the install upon tbl error?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1233]
I think it would be good if it can be done simple.

**Comment by meangczac** [comment]
Ok, I will break and add message.

However, there were many commands and during the installation, things run procedurally top down.
On error, we break the loop finding the next command to run.

Hence:
````
foreach (self::$inf as $callback_method => $statement_type) {
                    $method = $callback_method."_infuse";
                    if (method_exists(self::$instance, $method)) {
                        $error = self::getInstance()->$method(self::$inf);
                    }
                    if ($error) { addNotice('danger', 'The infusions has error and cannot be infused properely'); return $error;}
                }
````

We can remove the previous method by finding the opposite by declaring an array..
````
$opposite_array = array(
'insertable' => 'deltable'
);
````
However, this is overkill atm? Let's just test having a loop breaker and try it first.
