### ISSUE TITLE
How can I completely change to noFollow links in PF 9.0.2

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1235]
Hello Developers,

I have a question and I would work in PF 9.0.2 only with noFollow links. In which file do I need to set or paste the NoFollow attribute?

Nofollow is better for me because I link my own projects and Google does not like it. For this reason, I now changed most blogs and forums to NoFollow.

Thanks in advance.

**Comment by meangczac** [comment]
All BBcode autolinks are no follow by default. This includes auto generated News, Articles if you use html editor unless escaped by tinymce paste function. 

For [url] bbcode, Go to Misc > Allow Index URLS in Bbcode  - shut it down with "NO"

Please use the forum for user guides questions next time.  Thanks.
