### ISSUE TITLE
Theme Preset

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1236]
Cannot create custom presets in Theme Manager. Do I have to set special write permissions for any files?

![screenshot at 2017-01-07 20-11-27](https://cloud.githubusercontent.com/assets/24844259/21747002/bf60db9a-d515-11e6-86bd-01a30a6ca39a.png)

**Comment by meangczac** [comment]
I've removed the notify. Will check the relevant issues.
