### ISSUE TITLE
Search user groups does not work

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1237]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38153&pid=201105

![przechwytywanie](https://cloud.githubusercontent.com/assets/4210004/21748514/1416a824-d587-11e6-87c2-12ac923d141f.png)

**Comment by meangczac** [comment]
Kinda messy the UI. I'll redo the UI and make some clean up.
