### ISSUE TITLE
forum_main.php

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1239]
forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 566 	
Severity : Non fatal Runtime Errors
Invalid argument supplied for foreach()

forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 566	
Severity : Run-time notices
Undefined index: filter

forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 537	
Severity : Run-time notices
Undefined index: filter

forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 537

Severity : Non fatal Runtime Errors
Invalid argument supplied for foreach()
forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 547
Severity : Run-time notices
Undefined index: filter

forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 547
2 hours ago 	

Severity : Non fatal Runtime Errors
Invalid argument supplied for foreach()
forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 557
Severity : Run-time notices
Undefined index: filter

forum_main.php
/site/infusions/forum/tags.php?tag_id=1A=0&time=1month&sort=time&order=descending&type=poll
Line: 557
	
Severity : Non fatal Runtime Errors
Invalid argument supplied for foreach()

**Comment by RobiNN1** [comment]
How you got this error? The error is caused by a bad tag id in url.

**Comment by Catzenjaeger** [comment]
i get this from time to time when i or other a thread on my site
i clear every morning my error log
