### ISSUE TITLE
Google Adsense - ads disappeared

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1240]
If it possible that PHP Fusion can block view ads from Google Adsense?

Until I upgrade to actual version of PHP Fusion form GITHUB (5th january 2017) my ads sometimes are disabled. 
Please see my video: https://youtu.be/qeTDigawXDA
where I showed what happend. On front page ads are enabled, but when I go for example to blog item ADS disappeared.

**Comment by kosiorski-eu** [comment]
I found reason why ads are blocked. 

**PERMALINKS**

For example, please visit the same page with permalinks on and without. When seo mode is disabled google ads are visible.

With permalinks:
http://www.tomaszowiak.pl/wiadomosci/23532/Edyta-Geppert-zagra-koncert-dla-tomaszowskiej-publicznosci

Without permalinks:
http://www.tomaszowiak.pl/infusions/blog/blog.php?readmore=23532&google

Some code generated by addon permalinks crashed code google ads.

**Comment by meangczac** [comment]
When SEO is on permalink actually reroutes all traffic from index.php, but for Adsense specific issues... requires me to learn how Adsense actually work. 

New Mainsite has commercial integration to process credit cards. Past month I have been learning and doing things with their sandbox and therefore I'm more familiar with 2CO and Paypal integration and they do work fine with SEO on. 

I will need to look into adsense API later to fix this issue.

**Comment by meangczac** [comment]
Very nice site done there @kosiorski-eu. So far the best mod on PF9. 

And I'm looking at your adsense working on SEO on. Viewing from Malaysia 

![github](https://cloud.githubusercontent.com/assets/4078041/22092854/eee44698-de3b-11e6-8028-6f2ea005f5ba.PNG)

**Comment by kosiorski-eu** [comment]
@FrederickChan on start page adsense working well, but please visit some blog item. There adsense will disappeared.
ex.: http://www.tomaszowiak.pl/wiadomosci/23620/Policjanci-uratowali-19-latka-przed-wyziebieniem


I see some dependence when google ads are blocked. Maybe this help you in localize problem. 

**Google adsense works for:**
www.site.com/news
www.site.com/blogs
www.site.com/articles

**Not works for:**
www.site.com/news/cats/2/cat-name
www.site.com/news/2/news-item
www.site.com/blog/cats/2/cat-name
www.site.com/blog/2/blog-item
etc.

So ads are blocked when url has more than one **/** ?
