### ISSUE TITLE
/site/administration/infusions.php?aid=xxxxxxx--> Array to string conversion / Undefined variable: userdata

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1243]
infusion.php
/site/administration/infusions.php?aid=xxxxxxx
Line: 46

Severity : Run-time notices
Array to string conversion
infusion.php
/site/administration/infusions.php?aid=xxxxxxxx
Line: 90

Severity : Run-time notices
Undefined variable: userdata
infusion.php
/site/administration/infusions.php?aid=xxxxxx
Line: 75

Severity : Run-time notices
Undefined variable: userdata

**Comment by RobiNN1** [comment]
Issues is in your infusion. administration/infusions.php works well.
