### ISSUE TITLE
How do I properly update my Fork Repository? - PHP-Fusion 9.02

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1244]
Hello Developers,

I have problems updating my fork repository. I followed your instructions and hints from the readme.md. Unfortunately, I can still fully understand.

What is a "remote repository"? Is it the Repo or is it my Fork Repo?

I entered these SSH commands in the GitBash.

```
git init
git checkout 9.02
git pull upstream
git push
```

In my Fork Repo under https://github.com/AlexL777/PHP-Fusion the last commits and changes of this repository are not yet available. Something I'm still completely wrong.

I am looking forward to some help.

Thank you!

**Comment by meangczac** [comment]
https://help.github.com/articles/syncing-a-fork/

The documentation is quite complete this one.
