### ISSUE TITLE
Make Tiny / Non Tiny image select box only search in respective directory for images

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1246]
Since we have the Images uploader tool that only places for example News images in the upload directory for news images.  I need the image selector to also look in this directory for any addon specific images when inserting these.

AFAIK this goes for 
News
Blog
Articles

Related, https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38163&pid=201134

**Comment by meangczac** [comment]
News, Blog, Articles - got it.

**Comment by ovasclub** [comment]
The problem remains in the news. The problem with the formats PNG and jpg files. Gif format is displayed normally

**Comment by meangczac** [comment]
Ok good to know. I will check again.

**Comment by ovasclub** [comment]
Insert images in news to the administration panel:
<,img src="/infusions/news/news_cats/bsd.gif" alt="" style="margin:5px"/>  <=shows
<,img src="/images/panel_off.gif" alt="" style="margin:5px"/>  <=does not show
