### ISSUE TITLE
BBCode Mod Required?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1247]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38124&pid=201119

**Comment by meangczac** [comment]
I can't verify since I dont have 7.1 (no LAMP stack on Windows packages - XAMPP, MAMP) available on PHP 7.1 yet.

Someone with PHP7.1 please verify and close.

**Comment by meangczac** [comment]
I think is array variable initialized as string, and my patch could have solved it. I'll close for now.
