### ISSUE TITLE
/site/infusions/forum/postify.php

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1248]
Unknown
/site/infusions/forum/postify.php
Line: 0
Severity : Non fatal Runtime Errors
Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,'

Unknown
/site/infusions/forum/postify.php
Line: 0
Severity : Non fatal Runtime Errors
Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5)

same on 👍 
/site/print.php
/site/infusions/forum/tags.php

**Comment by meangczac** [comment]
Line: 0

**Comment by meangczac** [comment]
#1276
