### ISSUE TITLE
https://pc-politika.cz/index.php?sortby=P

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#1249]
Path to File:
Request URI: index.php?sortby=P
1. index.php?sortby=P : No matching Alias found.
2. index.php?sortby=P : No matching Alias Pattern found.
3. File path is empty.

**Comment by Kvido** [comment]
The Administration Members can not be edited by users.

**Comment by meangczac** [comment]
@Kvido, you have SEO on. 

Since Day 1, the code submitted to us was that each increment in URL must be fitted into driver. 
During the debug process, I rewrote the class 3 times, and I did not touch alias, because that was not seen in Admin Panel coded.

It will take me a lot of time to redesign the whole thing. 

Let's compromise. The driver must be updated to fit your rules to mod.

Look here please:
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/rewrites/homepage_rewrite_include.php

````
"home" => "index.php",
"homepage" => "home.php",
````

Then you need to compare another driver see:

https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/rewrites/articles_rewrite_include.php#L34

````
"submit/%stype%/articles" => "submit.php?stype=%stype%",
````

Ok, now If you add a rule like this:

````
"index/kvido_sort/%p%" => "submit.php?sort=%p%",
````

`````
$regex = array(
 "%p%" => "([0-9a-zA-Z._\W]+)",
`````

I think the Router will be able to read that $_GET. Otherwise, omit. 

The SEF driver is very precise. 

Each URL you add, You need to increment Driver. 
Each $_GET variable you introduce, you need to define in driver. 

----

You need to tell next time that this Issue is SEO issue. 

Administration members, is ?

**Comment by Kvido** [comment]
@Chan
I adjusted about works. Error only in News Comments which are not seen.
The question must be added in the same also for other Admins?

**Comment by Kvido** [comment]
Changes, yes, but has errors while browsing Member List

Path to File:
Request URI: index.php?sortby=P
1. index.php?sortby=P : No matching Alias found.
2. index.php?sortby=P : No matching Alias Pattern found.
3. File path is empty.

Fatal error: Call to undefined function PHPFusion\display_user_field() in /home/www/pc-politika.cz/www/pc-politika.cz/includes/classes/PHPFusion/UserFields.inc on line 689

**Comment by meangczac** [comment]
@Kvido 
https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/templates/global/profile.php#L69-L89

I hope you did not  directly edit out any files. I mentioned that we want to make "sync" and "fork" easy.

Make new files for mods and make include, a lot of functions in this repository is wrapped in !function_exists. 

If you have that function in a seperate file and included in theme.php, the core ones will not run. This is basic development strategy. If you want to replace any function and our core is not wrapped in such !function_exists , tell us. It will be included. BUT, don't replace with your version, it makes all the community modding  development 200% times slower, at least if you need to copy and paste codes fix and dare not directly replace the whole file.. that is the beginning of a bad direction.

I'm basically in for a pro mod.

I also have question why your site is so slow? 5.6seconds is not normal. If you can determine your cause, we can have a fix here as well.

**Comment by Kvido** [comment]
Thanks for the answers given to your important work.
Yes, in the last week to me seems slow web. I had a backup folder incluides and 2x 2x FusionTheme backup folder. After clearing the site opens when turned Administration superadmin:

I had just insert an include file render_function - already deleted:
include INFUSIONS. "deluxe_dropdown_menu / menu.php";

**Comment by Kvido** [comment]
Superadmin Frederic, I have good news.
1 First Queries Which Were Made for Rewriting longer appears. The error was in htacces not been commented out ... # Options + SymLinksIfOwnerMatch
2. After today's update (24 January 2017) works displaying the "Comments" as well as writing and editing.
https://pc-politika.cz/news/8456/Ve-Windows-10-bude-Game-Mode#c214
3. Members third sheet is also OK, admin members and y can be opened and edited.
4. Finally, a unique mistake.
BLOG. Everything OK, opening and editing ... but ... NEWS from the homepage can open the latest articles from below, about 5 articles. Recent articles from above can not be opened and therefore read ????
in news_rewrite_include.php I added:
`$regex = array(
 "%p%" => "([0-9a-zA-Z._\W]+)",`
`$pattern = array(
 "index/sort/%p%" => "submit.php?sort=%p%",`
Same in articles.
https://pc-politika.cz/news/8468/PHPF;-menime-hlavni-menu
Error:
Fatal error: Unsupported operand Types in /home/www/pc-politika.cz/www/pc-politika.cz/includes/classes/PHPFusion/Feedback/Comments.inc on line 984
It is already a known bug in recent days discussed. You can look at it? Thank you.

**Comment by meangczac** [comment]
For point 4, i need to have a look at the problem, because your site has operand problem, i can't view it.

**Comment by Kvido** [comment]
For point 4,I point out, I forgot to add that the newly saved NEWS displays standard means. So comments.
Greetings!

**Comment by Kvido** [comment]
02:23:58
After repairing # 1249 - operand fix function (to me already open) all articles NEWS !!

**Comment by meangczac** [comment]
I'm guessing this case is solved. If it is not, please tell and reopen and tell me what else to fix. Thanks.

**Comment by Kvido** [comment]
Yes, it resolved!

**Comment by meangczac** [comment]
👍
