### ISSUE TITLE
Investigate and implement option to insert and use tokens on standard forms not initiated by Dynamics

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1250]
Naturally there are many purposes by doing this.
One could be for easy integration of older v7 Infusions to 9. 
Another would be if you want variations of your form validation checkers other than the one shipped with Dynamics. 
Third would be if Dynamics somehow would not be compatible with 3d party integrations, this is the solution.

I could go on, point is it will save us some headache's and open possibilities by providing alternatives.

**Comment by meangczac** [comment]
Your form html/php syntax:

````
$options['form_id'] = 'MyUniqueFormID';
$options['max_tokens'] = 5;
$options['remote_url'] = ''; // if have ajax - value is:  fusion_get_settings('site_path').'/absolute-path/to/your/ajax.file.php
$token = \Defender\Token::generate_token($options['form_id'], $options['max_tokens'], $options['remote_url']);

// Begin Form
echo "<form id='".$options['form_id']."'>\n";
echo "<input type='hidden' name='fusion_token' value='".$token."' />\n";
echo "<input type='hidden' name='form_id' value='".$options['form_id']."' />\n";
// Fields..
echo "</form>\n";
````

That is why openform is a whole lot faster. It does the exact same thing.
