### ISSUE TITLE
Ability to move at least 1 individual post and make a new thread of it

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1251]
This is for thread hijackers.
You know people that take one open thread and post something totally new in it when it does not belong.
We need an option to mark that post and make a new thread out of it in a new forum.
1, Poster of the Post will be set as author of the new thread.
2, Moderator selects subject.
3, Moderator selects which new forum it belong in. ( same can be default )

**Comment by meangczac** [comment]
#1276

**Comment by JoakimFalk** [comment]
Adding to 9.1 Dev plan

> [Forum]
> 	Ability to move individual forum posts and make a new thread of it in a new forum of choice.
> 	· Poster of the Post will be set as author of the new thread.
> 	· Moderator selects subject.
> 	· Moderator selects which new forum it belong in. ( Default to current )
