### ISSUE TITLE
Articles 

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1252]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/infusions/articles/articles_admin.php?aid=81bac80ee2ee2af9 **
Line: 71

Severity : Notice generated by user using trigger_error() function

Query Error: SELECT article_cat_id, article_cat_name, article_cat_parent FROM pf9_article_cats WHERE article_cat_language='English' ORDER BY article_cat_id ASC AND article_cat_id IN (1) ORDER BY article_cat_name ASC
Stack Trace: 
#0 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(63): PDO->prepare('SELECT article_...') 
#1 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT article_...', Array) 
#2 F:\xampp\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT article_...', Array) 
#3 F:\xampp\htdocs\PHP-Fusion\includes\dynamics\includes\form_select.php(581): dbquery('SELECT article_...') 
#4 F:\xampp\htdocs\PHP-Fusion\includes\dynamics\includes\form_select.php(516): dropdown_select('pf9_article_cat...', 'article_cat_id', 'article_cat_nam...', 'article_cat_par...', '1', 'WHERE article_c...', '') 
#5 F:\xampp\htdocs\PHP-Fusion\infusions\articles\classes\admin\controllers\articles.php(473): form_select_tree('article_categor...', '', '', Array, 'pf9_article_cat...', 'article_cat_nam...', 'article_cat_id', 'article_cat_par...') 
#6 F:\xampp\htdocs\PHP-Fusion\infusions\articles\classes\admin\controllers\articles.php(47): PHPFusion\Articles\ArticlesAdmin->display_article_listing() 
#7 F:\xampp\htdocs\PHP-Fusion\infusions\articles\classes\admin\articles_admin_view.php(105): PHPFusion\Articles\ArticlesAdmin->displayArticlesAdmin() 
#8 F:\xampp\htdocs\PHP-Fusion\infusions\articles\articles_admin.php(21): PHPFusion\Articles\ArticlesAdminView->display_admin() 
#9 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND article_cat_id IN (1) ORDER BY article_cat_name ASC' at line 1

**Comment by karrak1** [comment]
corrected
