### ISSUE TITLE
Faq System

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1254]
Can't add categories.
Submissions is not needed for faq.

**Comment by JoakimFalk** [comment]
We can keep the submissions, it does give community an option to help with any sites content.

**Comment by FrederickChan** [comment]
The FAQ is missing an entire FAQ Category - Admin Page.

**Comment by meangczac** [comment]
FAQ has category in Version 7. 
https://github.com/php-fusion/PHP-Fusion/blob/7.03/faq.php#L23-L34

Why is the OOP version 9 no FAQs category?

**Comment by FrederickChan** [comment]
@karrak1 can you fix?

**Comment by meangczac** [comment]
Let me fix this. I've got a new idea.
