### ISSUE TITLE
Site links have a very odd issue when using Custom ID

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1256]
Check refresh and adding multiple links after edit, ordering seems off with new links for a better problem description

**Comment by meangczac** [comment]
Can I get a description in steps? 
.. cause... adding multiple links (admin can only add 1 link per time)

Adding 1 link per time is OK. If link order is 0, it is always the last.

**Comment by JoakimFalk** [comment]
I get back to it when running laps, idk how I managed to bug it out my self yet, so it is as topic says. Note to self for now.

**Comment by meangczac** [comment]
Ok sure bro

**Comment by JoakimFalk** [comment]
Screw it, I make a new one. This is messy LOL.
