### ISSUE TITLE
2 notices when using site links

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1257]
adminDashboard.php Line: 241 Undefined index: SF
site_links.php /administration/site_links.php?aid=xxxxxx Line: 892 Undefined offset: 103

**Comment by meangczac** [comment]
Notices for these 2 are kinda legit and if suppressed will make Infusions broken.

1. 9.0 Infusions - SF must be defined in infusion_db.php or in your theme.php
````
\PHPFusion\Admins::getInstance()->setCommentType('SF', 'CUSTOM TYPE');
\PHPFusion\Admins::getInstance()->setLinkType('SF', fusion_get_settings("siteurl")."infusions/custom/custom.php?readmore=%s");
````
2. Site links has used 103 as a standard super admin access. This is v7. In v9, it is **USER_LEVEL_SUPER_ADMIN** or **-103**

**Comment by JoakimFalk** [comment]
Ok had some old values there, but this 
> \PHPFusion\Admins::getInstance()->setCommentType('SF', 'CUSTOM TYPE');
> \PHPFusion\Admins::getInstance()->setLinkType('SF', fusion_get_settings("siteurl")."infusions/custom/custom.php?readmore=%s");

Will it throw notices if not defined? or whats the deal here?
