### ISSUE TITLE
Register submission link

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1259]
Admin class API to use infusion_db.php to register submission link.

**Comment by meangczac** [comment]
Care to describe more of your proposal?

**Comment by RobiNN1** [comment]
I found this in https://github.com/php-fusion/PHP-Fusion/commit/3796f4314accff9b82007d669f8cf2f74026226a#diff-2621f32e659f1da6e609094a99b13a63L311

**Comment by meangczac** [comment]
It's there. If you mean Artermis is missing the submission link.

https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/admin_themes/Artemis/Drivers/Viewer/adminDashboard.php#L313-L315

So close?

**Comment by meangczac** [comment]
Thank you.
