### ISSUE TITLE
trimlink function has html entity problem

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1264]
$comment_data['comment_message'] = strip_tags($comment_data['comment_message']);
echo "<span class='text-smaller text-lighter'>".trimlink(parseubb($comment_data['comment_message']), 70)."</span><br />\n";
Result:
![ashampoo_snap_2017 01 25_19h15m24s_002_](https://cloud.githubusercontent.com/assets/19621858/22303289/eb21700c-e332-11e6-99d9-4a928a836969.png)

$comment_data['comment_message'] = strip_tags($comment_data['comment_message']);
 echo "<span class='text-smaller text-lighter'>".parseubb($comment_data['comment_message'])."</span><br />\n";
Result
![ashampoo_snap_2017 01 25_19h16m49s_003_](https://cloud.githubusercontent.com/assets/19621858/22303299/fa6bcd00-e332-11e6-9728-fe6023d24568.png)

**Comment by meangczac** [comment]
Good suggestion.

**Comment by UnrealCatze** [comment]
Will this be fixed by you developers? So I can no longer shorten texts. So I need a solution here

**Comment by meangczac** [comment]
I was under the impression there is an entity problem only. What about the trim link?

**Comment by UnrealCatze** [comment]
dosent work correct. When i add a trimlink in a code the following text will be including wrong singns like this here: lt&#039

when i delete the trimlink part in my code all is correct.
Its in forum, in my panels and otherwhere too. Think its a global problem

**Comment by meangczac** [comment]
Ok. So trimlink breaks entity. I will double check it.
