### ISSUE TITLE
Impossible to remove unused infusions

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1265]
When I try to phisically remove unused infusions, I have many errors and locale for main admin page is not loaded. As I understood, code requires unused infusions too. But why all content was moved to infusions when I cannot remove them?

**Comment by meangczac** [comment]
Please give all error codes while I fix them

**Comment by Rizado** [comment]
Main error - DB_ARTICLES, DB_NEWS etc. is now defined.

**Comment by meangczac** [comment]
See any more error. You copy all errors, I will fix them.

**Comment by Rizado** [comment]
You can reproduce them by yourself. Make a new installation, but dont install any infusions. After that physically remove these folders:
/infusions/articles/
/infusions/blogs/
/infusions/downloads/
/infusions/forum/
/infusions/news/
/infusions/weblinks/
And see error log.

**Comment by Kvido** [comment]
I have noticed a change in behavior infusions NEWS. It does not open from the last update Git content https://pc-politika.cz/news
Is DB NEWS changing tables? Why is it?

**Comment by Rizado** [comment]
@Kvido , news infusion contains subfolder named "upgrade". See there.

**Comment by Kvido** [comment]
@rizado
I put a new table news_images.
Please table is good?
The news is you do not see the content only to HomePage
`CREATE TABLE IF NOT EXISTS `fusion4KN2L_news_images` (
`news_image_id` MEDIUMINT(8) UNSIGNED NOT NULL,
`news_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
`news_image` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_t1` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_t2` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_user` MEDIUMINT(9) NOT NULL DEFAULT '0',
`news_image_datestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (news_image_id)
    ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `fusion4KN2L_news_images`
 ADD PRIMARY KEY (`news_image_id`), ADD KEY `news_datestamp` (`news_datestamp`);

INSERT INTO `fusion4KN2L_news_images` (`news_image_id`, `news_id`, `news_image`, `news_image_t1`, `news_image_t2`, `news_image_user`, `news_image_datestamp`)  VALUES

ALTER TABLE `fusion4KN2L_news_images`
MODIFY `news_image_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
`

**Comment by Kvido** [comment]
`CREATE TABLE IF NOT EXISTS `fusion4KN2L_news_images` (
`news_image_id` MEDIUMINT(8) UNSIGNED NOT NULL,
`news_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
`news_image` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_t1` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_t2` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_user` MEDIUMINT(9) NOT NULL DEFAULT '0',
`news_image_datestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (news_image_id)
    ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Klíče pro tabulku `fusion4KN2L_news_images`
--
ALTER TABLE `fusion4KN2L_news_images`
  ADD PRIMARY KEY (`news_image_id`), ADD KEY `news_datestamp` (`news_datestamp`);

--

INSERT INTO `fusion4KN2L_news_images` (`news_image_id`, `news_id`, `news_image`, `news_image_t1`, `news_image_t2`, `news_image_user`, `news_image_datestamp`)  VALUES
ALTER TABLE `fusion4KN2L_news_images`
MODIFY `news_image_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
`

**Comment by Rizado** [comment]
@Kvido please create separate issue because this thread is about different question.
