### ISSUE TITLE
Comments.ajax.php

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1267]
Comments.ajax.php
/site/includes/classes/PHPFusion/Feedback/Comments.ajax.php?action=delete
Line: 71
Severity : Run-time notices
Undefined index: comment_options

Comments.ajax.php
/site/includes/classes/PHPFusion/Feedback/Comments.ajax.php?action=delete
Line: 73
Severity : Run-time notices
Undefined index: comment_key

**Comment by meangczac** [comment]
Update PHPFusion/Feedback/ folder and Themes/Templates/ folder in full.
