### ISSUE TITLE
News, no content

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#1268]
From 27 January 2017 to open my elder news content articles. Only in the left column are the categories, but they also can not be opened.
It has a relationship with a new table in the DB news_image? See. news / upgrade / 11.1.inc?

**Comment by Kvido** [comment]
`CREATE TABLE IF NOT EXISTS `fusion4KN2L_news_images` (
`news_image_id` MEDIUMINT(8) UNSIGNED NOT NULL,
`news_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
`news_image` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_t1` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_t2` VARCHAR(100) NOT NULL DEFAULT '',
`news_image_user` MEDIUMINT(9) NOT NULL DEFAULT '0',
`news_image_datestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (news_image_id)
    ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
ALTER TABLE `fusion4KN2L_news_images`
 ADD PRIMARY KEY (`news_image_id`), ADD KEY `news_datestamp` (`news_datestamp`);

INSERT INTO `fusion4KN2L_news_images` (`news_image_id`, `news_id`, `news_image`, `news_image_t1`, `news_image_t2`, `news_image_user`, `news_image_datestamp`)  VALUES
ALTER TABLE `fusion4KN2L_news_images`
MODIFY `news_image_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
`

**Comment by meangczac** [comment]
News Table ```DB_NEWS```

![news](https://cloud.githubusercontent.com/assets/4078041/22452295/8d3a1c50-e7b0-11e6-8f84-ff98d62c0e5d.PNG)

This table is not dependent on anything. It does not have ID of other table.

News Gallery Table. ```DB_NEWS_IMAGES```

![news_gallery](https://cloud.githubusercontent.com/assets/4078041/22452300/959afd38-e7b0-11e6-8b5c-277b3cd55109.PNG)

This table has ID of news.

As long as your table is not faulty, everything should be working OK.

**Comment by meangczac** [comment]
Just tested news, and everything works as intended. If you have SQL error, paste them.

**Comment by Kvido** [comment]
I utf_8_general_ci lines 4,5,6,7 and still about 3 mistakes others
and news_datestamp, news_reads meet the Primary ...
I need to change
If I understand correctly:
prefix_news_gallery remains functional and contains DB_NEWS_IMAGES? Thus, table No. 2.
Yes.
Thanks.

**Comment by meangczac** [comment]
welcome.

**Comment by Kvido** [comment]
Comments work, news function on the homepage. In the NEWS page appears to me for articles from January 2017 across the cell references in the titles:
https://pc-politika.cz/news

**Comment by meangczac** [comment]
Great. now please test Forum with upgrade. Please use a non-production site!

**Comment by Kvido** [comment]
NEWS OK!
Reason:
Subtitles are not running because of DB tables disappeared text news headlines for all the articles since January 2017. How is this possible?
After manually adding captions are now displayed. However, all older articles in news headlines have.
Why is it?
