### ISSUE TITLE
Peoblem with a single language content

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1271]
When content table is not multilingual you have a query like this:
```
SELECT
  a.*,
  ac.*,
  COUNT(c.`comment_id`) 'comments_count',
  COUNT(r.`rating_id`) 'ratings_count',
  u.`user_id`,
  u.`user_name`,
  u.`user_status`,
  u.`user_avatar`
FROM
  `chr_articles` a
    LEFT JOIN `chr_article_cats` ac ON ac.`article_cat_id` = a.`article_cat`
    LEFT JOIN `chr_comments` c ON c.`comment_item_id` = a.`article_id` AND c.`comment_type` = 'A'
    LEFT JOIN `chr_ratings` r ON r.`rating_item_id` = a.`article_id` AND r.`rating_type` = 'A'
    INNER JOIN `chr_users` u ON u.`user_id` = a.`article_name`
WHERE
GROUP BY
  a.`article_id`
ORDER BY
  `article_draft` DESC, `article_datestamp` DESC
LIMIT
  0,16
```
See at "WHERE GROUP".
Users have an error and content is not displayed in admin panel. In front-end content is displayed.
How I understand this problem exists in all type of content which are rewritten with classes, not in Articles only.

**Comment by Rizado** [comment]
I propose change next:
/infusions/articles/classes/admin/controllers/articles.php, from line 370:
```
        $article_query = "
            SELECT
                a.*, ac.*,
                count(c.comment_id) 'comments_count',
                count(r.rating_id) 'ratings_count',
                u.user_id, u.user_name, u.user_status, u.user_avatar
            FROM ".DB_ARTICLES." a
            LEFT JOIN ".DB_ARTICLE_CATS." ac ON ac.article_cat_id=a.article_cat
            LEFT JOIN ".DB_COMMENTS." c ON c.comment_item_id=a.article_id AND c.comment_type='A'
            LEFT JOIN ".DB_RATINGS." r ON r.rating_item_id=a.article_id AND r.rating_type='A'
            INNER JOIN ".DB_USERS." u on u.user_id=a.article_name
            WHERE 1 ".(multilang_table("AR") ? "article_language='".LANGUAGE."'" : "")."
            $sql_condition
            GROUP BY a.article_id
            ORDER BY article_draft DESC, article_datestamp DESC
            LIMIT $rowstart, $limit
        ";
```
And similar change is required for categories. And for other content types.

**Comment by meangczac** [comment]
Actually there is a multilang column implementation error.  Everyone should follow this:

````
".(multilang_table("XYZ") ? "WHERE a.xyz_language='".LANGUAGE."' AND ac.xyz_language='".LANGUAGE."' AND " : "WHERE ")."
````

immediately after select statement.

Do not use it in the middle of the condition.

**Comment by meangczac** [comment]
Please help with the debug if you find anything. Many thanks!

@rizado , unless Article is able to be created without Category then I find it could mean something to add an extra column for lang data, because by then Category is NULL and we need language in Article table itself. I can see the need for one in Blog for example. 

In the Article system, no article can be added without category setup first right? Then there is no need for one.

**Comment by Kvido** [comment]
Articles with me, "Column" category tdisplays, articles appears.
Categories can not be saved.

**Comment by Rizado** [comment]
I mean admin panel, not front-end. How to reproduce problem:
1. Sdd some articles to database.
2. Switch off multilingual content for articles.
3. Go to articles list in admin panel.
![without_ml](https://cloud.githubusercontent.com/assets/3373906/22582386/b821a0c0-e9f7-11e6-9755-8389f7357053.png)

**Comment by Kvido** [comment]
@rizado, I changed according to the proposal.
Shows !!! Categories and articles !!!
https://pc-politika.cz/articles

**Comment by Rizado** [comment]
@Kvido , in Admin panel? I'll see it some later, at 16-17 UTC.

**Comment by Rizado** [comment]
Now it works but other types of content are needed to check too.

**Comment by meangczac** [comment]
When have issues, please check if got encountered just report it.

**Comment by Kvido** [comment]
@rizado, @chan
30 minutes of OK !!! on HomePage Article I show that with me will be a "pillar"
Help:
In DB - AR Articles 0
https://pc-politika.cz/articles/1/Snezi,-a-co?
***
The same problem was with NEWS. Now displays categories of articles + OK
https://pc-politika.cz/news
