### ISSUE TITLE
Thumb view/list view in news

### ISSUE THREAD

**Issue by bronxi** [PHPFusion/PHPFusion#1274]
When I switch between thumb view and list view in news, I get this error?

Invalid UserID within token.
There was an error while processing your request

**Comment by meangczac** [comment]
There is something illegally posting back end. It should not happen. I will check.

**Comment by bronxi** [comment]
It is only when I am logged in as super admin. When im logged out, there is nothing.

**Comment by meangczac** [comment]
Can you show me your error logs? Please remember to paste the stack trace as well. Which theme btw?

**Comment by bronxi** [comment]
Sorry for me bad english. Stack trace? There are no errors in "error log". I use bootstrap theme. I only got this error.
![news](https://cloud.githubusercontent.com/assets/25545883/22692897/4e2e6520-ed41-11e6-8566-a2ed9de1e2f1.png)

**Comment by meangczac** [comment]
<img src='https://s-media-cache-ak0.pinimg.com/originals/99/f6/31/99f631504ce61c165468a0a5bf8e63e5.png'>

See the error log, has lots of logs
Query Error.......................................... at line 1 is a stack strace.

**Comment by meangczac** [comment]
1 file to update. Please close issue if solved for you.
