### ISSUE TITLE
blog.php

### ISSUE THREAD

**Issue by bronxi** [PHPFusion/PHPFusion#1275]
Something is wrong in infusions/blog/blog.php, the text is out whit the panels.
![unavngivet](https://cloud.githubusercontent.com/assets/25545883/22620440/7563664a-eb0c-11e6-97e1-2c5d7ba935b5.png)

**Comment by meangczac** [comment]
what panels?

**Comment by meangczac** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/22702277/22dd0570-ed9b-11e6-9e9f-4ca19a997d78.PNG)

**Comment by bronxi** [comment]
![unavngivet](https://cloud.githubusercontent.com/assets/25545883/22707353/d444dd5c-ed72-11e6-9bfa-159699b6f9a3.png)
![1](https://cloud.githubusercontent.com/assets/25545883/22707354/d68d572e-ed72-11e6-9e0c-f9f8a4afcc52.png)


Thought it was a mistake, the other just seems more normal. This look wrong

**Comment by RobiNN1** [comment]
Delete this https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/blog/templates/blog.php#L25-L46
and paste this code 
```php
        echo render_breadcrumbs();
        echo "<div class='row'>\n";
        echo "<div class='col-xs-12 col-sm-9 overflow-hide'>\n";
        if (isset($_GET['readmore']) && !empty($info['blog_item'])) {
            echo "<!--blog_pre_readmore-->";
            echo display_blog_item($info); // change this integration
            echo "<!--blog_sub_readmore-->";
        } else {
            echo display_blog_index($info);
        }
        echo "</div><div class='col-xs-12 col-sm-3'>\n";
        echo "<!--pre_blog_cat_idx-->";
        echo display_blog_menu($info);
        echo "<!--sub_blog_cat_idx-->";
        echo "</div>\n";
        echo "</div>\n";
```

**Comment by bronxi** [comment]
Thanks for help
