### ISSUE TITLE
Forum Upgrade 1.0.6

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1276]
While coding for the new PHP-Fusion site, I had lacked several features and is not satisfied with the benchmark of the code execution of the forum still. Some optimization is required, and I'm currently working on rewriting again portions of the Forum. 

Our support forum type is not strong enough for  a new platform. That is when I've decided to talk to Jock about new feature making our support forum on main site with new additional features delivery.

I'm currently progressing fast on making the upgrade. So please refrain from debugging forum at this moment, and create them issues if you find any. 

These are on going progress work that I will do / have done.

- Postify.php recoded as Forum_Postify class and will turn to drivers for each supported actions. This eliminates common sanitization, render_postify parameters in drivers and make extensions easier.

- User Reputation and Score Board for Posting in Forum. 

- User Bounty system which allows Thread Author to use their Reputation to get answer from other users that wishes to earn that bounty. There will be a seperate database to store this.

- Deleting Moods does not delete reactions in the forum post. This will be fixed.

- Adding Comments as a form of reply on each post. Some people like to post just a smiley or respond in gratitude. Comment API can be helpful in this case.

- Found that when viewing a thread, it checks access from its forum container and the forum container parent only. If the forum is nested more than 2 levels down, access check is broken. This is a security flaw and will be fixed.

- Mood Buttons are now appending +2 queries in every post increment. This is very slow. It needs to be rewritten on top most layer before entering while post found loop.

- Populate all attachment and make them into a nice slideshow (in concept).

- Remove the $_GET filters in the forum due to bad SEO effect. Implement in Ajax instead.

**Comment by meangczac** [comment]
![capture15](https://cloud.githubusercontent.com/assets/4078041/22635534/1b2d68d8-ec6f-11e6-86e5-5873b79026b3.PNG)

Screenshots on development of bounty in progress.

**Comment by meangczac** [comment]
Remake of the voting system.
(Based on what is generally needed in php-fusion.co.uk)

1. Forum Settings have settings. They are self explanatory
![forum_settings](https://cloud.githubusercontent.com/assets/4078041/22635595/8e57b0ca-ec6f-11e6-9a35-b655168806f4.PNG)

2. Your user earn bounty based on the earn marks allocated in the Settings above.  By system default, ONLY thread author or moderator can accept an answer because he's the owner of the thread, as thread author. 

3. Forum Bounty extensions.
In addition to that, every user, can post a bounty for a specific scope of the same thread.
I'm adding a few columns into the threads table.

````

if (!column_exists('forum_threads', 'thread_bounty')) {
    $inf_altertable[] = $db_prefix."forum_threads ADD thread_bounty SMALLINT(8) NOT NULL AFTER thread_answered";
}

if (!column_exists('forum_posts', 'bounty_description')) {
    $inf_altertable[] = $db_prefix."forum_posts ADD bounty_description TINYINT(4) NOT NULL AFTER thread_bounty_reason";
}

if (!column_exists('forum_posts', 'thread_bounty_start')) {
    $inf_altertable[] = $db_prefix."forum_posts ADD thread_bounty_start INT(10) UNSIGNED NOT NULL AFTER thread_bounty_reason";
}

if (!column_exists('forum_posts', 'thread_bounty_user')) {
    $inf_altertable[] = $db_prefix."forum_posts ADD thread_bounty_user MEDIUMINT(11) UNSIGNED NOT NULL AFTER thread_bounty_start";
}


if (!column_exists('forum_posts', 'post_answerid')) {
    $inf_altertable[] = $db_prefix."forum_posts ADD post_answerid TINYINT(1) NOT NULL AFTER post_locked";
}

if (!column_exists('users', 'user_reputation')) {
    $inf_altertable[] = $db_prefix."users ADD user_reputation INT(10) UNSIGNED NOT NULL AFTER user_status";
}
````
- These will be set into thread to avoid any additional SQL. Since thread selects data as SELECT t.* 

- Secondly, by having only column into the threads table and not alienated table, i allow que-ing of the bounty. So people using the "thread" will be to giving their best answer always. 

![add_bounty](https://cloud.githubusercontent.com/assets/4078041/22635780/1bac2112-ec71-11e6-8ca7-006014daf87c.PNG)

![capture17](https://cloud.githubusercontent.com/assets/4078041/22635784/2d9e09a8-ec71-11e6-9271-5fc5db19e57d.PNG)

![bounty_desc](https://cloud.githubusercontent.com/assets/4078041/22635792/3d9925ae-ec71-11e6-8acd-ff7a755feffd.PNG)


- Each bounty added is from the user's own reputation fund. They are non-refundable. So once you add, you cannot adjust at all the bounty award and will be straight away deducted.
*@todo: (user info panel increment)*
*@todo:(user fields module for php-fusion.co.uk)*

- Only the bounty maker will be able to accept the answer.

- 1 topic can only have 1 bounty at a time. However, when bounty lapses by default 7 days. Half of the bounty will be given to the top votes. It doesn't matter if the vote is 100 days old and has already existing vote (the top vote will be given half of the bounty award if nothing happens in 7 days).

**Comment by meangczac** [comment]
Postify will be made into a class, and each action will seperated into one file each, and will be loaded into a string object that postify will execute. 

FORUM."postify.php?post=DRIVERNAME&amp;;thread_id=%thread_id%

DRIVERNAME.php is a file in the postify folder.

I made a sample of post=ON and post=OFF - (for user track threads) mapped to Tracking.php. The sample codes will be available. I'm still pending testing on Linux server environment. Case sensitive test.

**Comment by meangczac** [comment]
Sorting in thread  - oldest and latest from key **section** to **sort_post**. SEO driver need update
@todo: SEO driver update.

**Comment by meangczac** [comment]
Locale updated:

````

$locale['forum_4001'] = 'Post Answer';
$locale['forum_4002'] = 'Post Answer Accepted';
$locale['forum_4003'] = 'You have marked the post as the answered to your question';
$locale['forum_4003'] = 'Post Answer Removed';
$locale['forum_4004'] = 'You have marked the post as unanswered to your question';
$locale['forum_4003'] = 'Post Answer Changed';
$locale['forum_4004'] = 'You have changed the answer to your question';

// Bounty
$locale['forum_4100'] = 'Edit Bounty Description';
$locale['forum_4101'] = 'This question has an open bounty worth {%points%} from {%profile_link%} ending in {%countdown%}';
$locale['forum_4102'] = 'This question is widely addressed to the entire community. The author has requested an answer to this thread.';
$locale['forum_4103'] = 'Bounty Points awarded to {%user_name%}';
$locale['forum_4104'] = 'We wish to inform you that since there are no selected answer within bounty time limit, the highest voted answer has been awarded with half of the bounty points. You can view the best answer to your bounty {%link_start%}here.{%link_end%}';
$locale['forum_4105'] = 'You have earn a Bounty Award!';
$locale['forum_4106'] = 'Congratulations for earning half of the total bounty points made on the question in {%thread_link%}. Your answer was selected by default because it has received the highest vote by the community before bounty time ended.';
````

I'm using strtr function.

![locale](https://cloud.githubusercontent.com/assets/4078041/22636186/6a6ae4fc-ec74-11e6-9a40-e09b0fa28390.PNG)

**Comment by meangczac** [comment]
You do not gain anything from accepting your own post as the answer. Sometimes, voting your own answer is made by moderator who wishes to put their knowledge out as example FAQ purposes, Documentation, Knowledge sharing or Community Wiki.. (for those who doesn't have wiki and need something to doc fast).

**Comment by meangczac** [comment]
Logic flow for Author of thread to pick an answer.

                // 1 - thread has been answered -- if current post id is not an answer, means moved answer.
                // 2 - thread has not been answered -- selecting is acccepting answer
                // 3. thread has been answered -- if current post is an answer, means remove answer.

**Comment by meangczac** [comment]
Bounty must be unaffected by thread_locked status. Possible sabotage by admin. funny.

Explanation - 
User A post a bounty, 400 points. Valid for 7 days. People post diligently for 3 days, hoping to earn that 400. Then suddenly, Admin locked the thread.  User A unable to select an answer. Only waiting for system to award half of the points to the highest voted. 

````
// Can award bounty
        $this->thread_info['permissions']['can_award_bounty'] = $this->thread_data['forum_type'] == 4 && $this->thread_data['thread_bounty'] && ($this->thread_data['thread_bounty_user'] == fusion_get_userdata('user_id')) ? TRUE : FALSE;
````

iMOD cannot pay on behalf. It's unfair.

**Comment by meangczac** [comment]
Bounty restricted to Support Type Forum only? hmm.

Actually it doesn't matter, but anyway, lets try just type 4 only.

**Comment by meangczac** [comment]
Vote up and Vote down change of Concept.

If you voted up on that post, click again and it removes that up vote. Same rule applies to vote down.

So i'm wondering what to do with this logic:
````
if ($thread_info['thread']['forum_answer_threshold'] > 0) { // if is 0, is unlimited and do nothing.
                                $vote_points_sql = "SELECT SUM('vote_points'), thread_id FROM ".DB_FORUM_VOTES." WHERE post_id = '".intval($data['post_id'])."'";
                                $vote_result = dbquery($vote_points_sql);
                                $v_data = dbarray($vote_result);
                                if ($v_data['vote_points'] >= $thread_info['thread']['forum_answer_threshold']) {
                                    $update_sql = "UPDATE ".DB_FORUM_THREADS." SET 'thread_locked'='1', thread_answered='1' WHERE thread_id='".intval($v_data['thread_id'])."'";
                                    $result = dbquery($update_sql);
                                }
                            }
                            
````

Locking a thread, is an administrator moderation. I think deprecate the automatic locking.

**Comment by meangczac** [comment]
Git updated.

**Comment by RobiNN1** [comment]
This item cannot be infused

F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/administration/infusions.php?aid=6f06691c503945bf **
Line: 71

Query Error: ALTER TABLE pf9_forum_posts ADD bounty_description TINYINT(4) NOT NULL AFTER thread_bounty_reason
Stack Trace: 
#0 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(67): PDOStatement->execute() 
#1 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('ALTER TABLE pf9...', Array) 
#2 F:\xampp\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('ALTER TABLE pf9...', Array) 
#3 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Installer\Infusion.core.inc(554): dbquery('ALTER TABLE pf9...') 
#4 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Installer\Infusion.core.inc(128): PHPFusion\Installer\Infusion_Core->altertable_infuse(Array) 
#5 F:\xampp\htdocs\PHP-Fusion\administration\infusions.php(28): PHPFusion\Installer\Infusion_Core->infuse('forum') 
#6 {main}
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'thread_bounty_reason' in 'pf9_forum_posts'


![hnhu](https://cloud.githubusercontent.com/assets/11664877/22657002/44b84260-ec95-11e6-9123-cdeda4311dcb.png)

**Comment by meangczac** [comment]
Ok thanks. Ill fix in a few hour.

**Comment by meangczac** [comment]
Errors on Linux server fixed. Please report any issues if found. Thank you all.

**Comment by RobiNN1** [comment]
F:\xampp\htdocs\PHP-Fusion\infusions\forum\classes\threads\threads.php
/infusions/forum/viewthread.php?thread_id=1 **
Line: 507
Line: 511
Array to string conversion

F:\xampp\htdocs\PHP-Fusion\infusions\forum\templates\forum_thread.php
/infusions/forum/viewthread.php?thread_id=1 **
Line: 36
Invalid argument supplied for foreach()

**Comment by bronxi** [comment]
![image](https://cloud.githubusercontent.com/assets/25545883/22708666/72829be0-ed77-11e6-9986-9e06c82e2b00.png)

Am iDoing something wrong after new forum files?

**Comment by meangczac** [comment]
@RobiNN1 your issues resolved?

**Comment by RobiNN1** [comment]
yes

**Comment by meangczac** [comment]
Good to hear.

**Comment by RobiNN1** [comment]
How to enable Bounty, in settings is not this option.

**Comment by meangczac** [comment]
To enable Bounty, you need to change Forum Type to Questions and Answers when you add the forum in Admin. 

I needed that for the new UK Support Forum.

**Comment by RobiNN1** [comment]
I don't have forum type Questions and Answers

**Comment by meangczac** [comment]
![forum](https://cloud.githubusercontent.com/assets/4078041/23003907/9484f73e-f42e-11e6-9577-22f3c0caa420.PNG)

This one.

**Comment by RobiNN1** [comment]
Ok thanks :)

**Comment by meangczac** [comment]
Any problem your side with the upgrade? Any notices?

**Comment by RobiNN1** [comment]
In forum/index.php?viewforum&forum_id=4 all threads redirects to Forum Index

**Comment by RobiNN1** [comment]
F:\xampp\htdocs\PHP-Fusion\infusions\forum\classes\threads\bounty.php
/infusions/forum/viewthread.php?action=editbounty&thread_id=1
Line: 49
Undefined index: bounty_points

F:\xampp\htdocs\PHP-Fusion\includes\sqlhandler.inc.php
/infusions/forum/viewthread.php?action=editbounty&thread_id=1
Line: 650
Undefined index: pf9_users

F:\xampp\htdocs\PHP-Fusion\infusions\forum\templates\forum_input.php
/infusions/forum/viewthread.php?action=editbounty&thread_id=1
Line: 113
Undefined index: bounty_select

**Comment by meangczac** [comment]
there is a code mistake in field_generator(). I'm very sorry there. Sync your git again now, and Line 650 error will be gone.

Downgrade your forum manually like this.
DB_INFUSIONS.' find, forum version and demote the version number by 0.1
Then go back to Infusions Admin and upgrade again.

DB_USERS will add a new 'user_reputation' column INT(10) default '0' - no unsigned

I will check the rest immediately.

**Comment by RobiNN1** [comment]
After reinstalling 0 notices

**Comment by meangczac** [comment]
Ok, all should be fixed. Just small isset errors.
