### ISSUE TITLE
Forum errors (core dl from 08FEB/1800 GMT)

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1277]
settings.php
/site/infusions/forum/admin/forums.php?aid=xxxxxx&section=fs
Line: 127

Severity : Run-time notices
Undefined index: points_to_downvote
settings.php
/site/infusions/forum/admin/forums.php?aid=xxxx&section=fs
Line: 126

Severity : Run-time notices
Undefined index: points_to_upvote
settings.php
/site/infusions/forum/admin/forums.php?aid=xxxxxb&section=fs
Line: 125

Severity : Run-time notices
Undefined index: answering_points
settings.php
/site/infusions/forum/admin/forums.php?aid=xxxxb&section=fs
Line: 124

Severity : Run-time notices
Undefined index: downvote_points
settings.php
/site/infusions/forum/admin/forums.php?aid=xxxxxxb&section=fs
Line: 123

Severity : Run-time notices
Undefined index: upvote_points

**Comment by meangczac** [comment]
Go Infusions > Run Upgrade

**backup please**
