### ISSUE TITLE
Requests: User Fields

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1278]
IM - , ~~WhatsApp~~,  ~~Line~~, Wire, Google Hangouts, Signal, 
Social - ~~Steam-id~~, ~~PSN-id~~

**Comment by ewl1** [comment]
Requests: ~~Discord~~ and Plug.dj

**Comment by meangczac** [comment]
I will omit the rest. Community can add them in themselves with the samples given.
