### ISSUE TITLE
no grid when i use a other domainname

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1282]
i have www.aliencollectors.com .... when i use this i have a responsive layout with grid -- on smartphone all is ok so now ....  when i use my other domainname www.predatorcollectors.com  i get a NON respnsive website without a gird

this is a Domain forwarding

whats wrong?
i use bootstrap

**Comment by meangczac** [comment]
No, your forwarders work for me, after I click on your predator link, it redirects to alien and it is still responsive. Maybe clear your browser cache or something.
