### ISSUE TITLE
Token error on commenting

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1286]
"Does not work commenting system news, article itp.
The error
Cannot find any token for this form.
There was an error while processing your request"
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38219&pid=201304#post_201304

**Comment by FrederickChan** [comment]
No errors on my system. So I don't have logs. When you're doing inspections, have a look at it and see if such error do exist.

**Comment by meangczac** [comment]
Ok, I tested again on news. Twice. There was no problems on the commenting token issues, but issues were more towards jquery execute/ non jquery execute update/save/delete. 

Will close issue. Please open new issue if problem exist with comments.
