### ISSUE TITLE
The latest version I have a problem with the display of several pages

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1287]
The latest version I have a problem with the display of several pages
members.php
profile.php
edit_profile.php
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38218&pid=201300#post_201300

**Comment by meangczac** [comment]
Should and would be a custom template problem. I already wrote a detailed explanation in forum very early prior to changing method. My post title next time must all put uppercase... lol
