### ISSUE TITLE
Request: Forum to have a HTML / BBcode Toggler.

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1289]
The forum to have a HTML or BBcode switch in the forum settings. 

When we do this, HTML must test to sanitize against hidden forum post <script> tags that can send user cookie data to 3rd party site or js console / alert.  a simple str_replace('<script>', '') can sanitise it.

**Comment by JoakimFalk** [comment]
Added to 9.1 Dev plan

> [Forum]
> 	Provide with a choice to have HTML or BBcode switch in forum settings.
> 	· HTML must test to sanitize against hidden forum post <script> tags that can send user cookie data to 3rd party site or js console / alert. 
> 	·  a simple str_replace('<script>', '') can sanitize it.
>
