### ISSUE TITLE
Url Rewriter is broken

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#1290]
Url Rewriting is brocken

From my site code from Browser
`<a href="../../viewpage.php?page_id=5">AGB</a> | <a href="../../pages/2/Impressum">Impressum</a></p>`
both are in my code as
`<a href="<?php echo BASEDIR ?>viewpage.php?page_id=5">AGB</a> | <a href="<?php echo BASEDIR ?>viewpage.php?page_id=2">Impressum</a>`

In the navigation bars sometimes the same issue.

with link to startpage the same, sometimes it's home and sometimes it's correct.

**Comment by meangczac** [comment]
Please try with a single quote. Pls tell results. 

```` echo "<a href=' ````

**Comment by meangczac** [comment]
If its not working still pls uninstall driver and tell us which driver is broken for you. I will fix it if know where to look.. appreciate it.

**Comment by Webmeteor** [comment]
above it's the driver for the custompages. In the Navigation Panel I've got sometimes the same issue.

And it's the home, I don't know which driver that is.

Ok with single quote it seems to be work.

**Comment by meangczac** [comment]
It must work with just single quote. It's designed this way so we can escape anything that is double quoted. Or else we would be having a hard time doubling back and forth everytime a SEO issue is up. PHP HTML JS combination is just too big to cover it all single and double quote.

Maybe later, but please use single quote right now. Thanks.
