### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1291]
bring PHP Fusion to TAPATALK

https://www.tapatalk.com/getting_started

**Comment by Webmeteor** [comment]
You can develop a responsive Theme. And then you create a Icon with your link in it. So you have your own webapp

http://sherin-z.com this is a responsive Theme from me. Site is based on Fusion 9

**Comment by meangczac** [comment]
@Webmeteor , very nice site going there. Love the design.

**Comment by meangczac** [comment]
@Catzenjaeger , you realise having 3rd party integration must be done at addon level right? 
Even user fields in this repository will be wiped and moved to addon downloads later. 

Only reason I git User Fields (FB, Skype etc) here is because we could use the translations.
