### ISSUE TITLE
user_timezone field problem

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1292]
Any site admin can remove user_timezone field from user profiles, But this field is necessary for user list display in Admin panel. Now when this field is disabled, user list is not displayed.
I see two ways for solution:
To check for existance of this field.
To make this field "hardcoded" without capability to disable it.

**Comment by meangczac** [comment]
I agree. must hardcode it.

I find user web, user timezone and user sig must all hardcode. They cause too much nuisance doing extra checks...

**Comment by Rizado** [comment]
Where user sig is used excluding forum? Is really need to hardcode this field?

**Comment by meangczac** [comment]
Well yes, just solve the timezone then. 

For user_sig, i'll think of other method for optimizing. Those checks are nuisance. Each field have to issets and determine on key at this moment, to me is redundant.

**Comment by meangczac** [comment]
![sigh](https://cloud.githubusercontent.com/assets/4078041/22975836/0e375bec-f3c3-11e6-9978-68e0864441ea.PNG)

user web, user sig, user this, user that.
It's frustrating keep checking and spending tons of resources.
need to find a solution.

**Comment by Rizado** [comment]
OK, I'll see but later, not now. About reasons I'll send you PM.

**Comment by JoakimFalk** [comment]
I don´t see the problem, just use ternary operator on em all and return default value for use with inserts in MVC.
something like , 
$user_sig = isset($data['user_sig']) ? true : false; 
With isset it does not notice on non existing field. 
Does not feel redundant to me.

**Comment by meangczac** [comment]
Getting lazy lately. >.<"
