### ISSUE TITLE
DB issues with new upgrade

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1294]
Today I try this method to upgrade my php fusion 7 website. But when I try go from step 3 to step 4 (Step 3: Database Settings
Step 4: Config / Database Setup) in installer I get this error 
Code Gist: Download source  

Fatal error: Access to undeclared static property: PHPFusion\Steps\InstallerDbSetup::$allow_delete in /users/0008/gczechowski/www/test.astro-zone.net/includes/classes/PHPFusion/Installer/Steps/DatabaseSetup.inc on line 264

My php version is set to 5.6 when I change it to version 5.5 I get this same. But when I change it for version 7.0 I get much more errors

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38210

**Comment by meangczac** [comment]
This one I wait. I can't possibly reinstall my system at this moment. Too much at stake... maybe later.
