### ISSUE TITLE
Request: default news category image.

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1295]
These are icons from PHP-Fusion Version 7, I'm thinking of changing it many times, but could not find a good replacements for them. 

If anyone willing, please have a go at it.

**Comment by RobiNN1** [comment]
Icons size?

**Comment by meangczac** [comment]
256 i think ok. but if svg files, doesnt matter size.

**Comment by meangczac** [comment]
Beautiful ! Good work @RobiNN1
