### ISSUE TITLE
Custom search form

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1298]
[custom search form.zip](https://github.com/php-fusion/PHP-Fusion/files/783332/custom.search.form.zip)

**Comment by JoakimFalk** [comment]
Please use the Modifications and Requests forms for such requests.
https://www.php-fusion.co.uk/forum/viewforum.php?forum_id=167

**Comment by Catzenjaeger** [comment]
Frederick told me i should upload it here on github :) but its ok

**Comment by meangczac** [comment]
I need to know standard protocol for writing search modules and make notes for documentation.

**Comment by meangczac** [comment]
I already responded in PM your issues. Should fix if nothing out of my expectations.
