### ISSUE TITLE
admin area member ban missing

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1301]
i was attacked this night from a spammer and would ban him ... but i cant find a option to do this
it is missing !

**Comment by Catzenjaeger** [comment]
i cant delete a user or ban him

![grafik](https://cloud.githubusercontent.com/assets/19621858/23093132/b124e2de-f5da-11e6-83a5-e4cefc0d2974.png)

**Comment by Catzenjaeger** [comment]
another 

![grafik](https://cloud.githubusercontent.com/assets/19621858/23093140/e3d378a8-f5da-11e6-96fc-3e80fd01f795.png)

**Comment by meangczac** [comment]
Go to your member administration page.

![banning](https://cloud.githubusercontent.com/assets/4078041/23103260/7bebf4e4-f6f3-11e6-8b9b-a7db1ab720a2.png)

Tick the guy you want to delete or ban. And Execute.

![banned](https://cloud.githubusercontent.com/assets/4078041/23103267/b1b29aba-f6f3-11e6-9b61-7f27591415ba.png)

You then update your list via Filters. You can configure your table to check what kind of fields you want to see.

![filters](https://cloud.githubusercontent.com/assets/4078041/23103280/dc49d450-f6f3-11e6-89aa-b4a6372c9ebd.png)

Once you update, a cookie will be stored in your browser. It remembers your preference as your admins preference might be different than yours.

**Comment by meangczac** [comment]
The delete user button on Profile page is user fields that allows Your user to delete himself and destroying all his personal information from your server I think. It's a self destruct button.
