### ISSUE TITLE
new user info panel destroy the site

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1302]
i have download for some minutes the new core files and update my infusions folder too
when i replace the newest  "user info panel" infusion with my old my site ist destroyed

**Comment by RobiNN1** [comment]
On my page displays all well
![jhbniomkm](https://cloud.githubusercontent.com/assets/11664877/23093193/b9ca8c7a-f5dc-11e6-9786-d086dc415611.png)

**Comment by Catzenjaeger** [comment]
and this is my with the new files

![grafik](https://cloud.githubusercontent.com/assets/19621858/23093412/b2cf2092-f5e2-11e6-8f04-f6beac108beb.png)

**Comment by Catzenjaeger** [comment]
and here with old

![grafik](https://cloud.githubusercontent.com/assets/19621858/23093417/d5675ea8-f5e2-11e6-9e9c-47c8d78dde36.png)

**Comment by meangczac** [comment]
![bootstrap_default](https://cloud.githubusercontent.com/assets/4078041/23103239/eb63c384-f6f2-11e6-941e-f18d03ae6ec8.png)

Just used my other machine and git sync latest. The user info panel don't have problem..  

please view source why your theme will have extra </div>, is it on openside, closeside?

**Comment by meangczac** [comment]
Please show on your news page. 

Not figurelibs page. Nobody has that screen.
