### ISSUE TITLE
quote_bbcode_include.php - Undefined index: bb_quote_expand

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1303]
![grafik](https://cloud.githubusercontent.com/assets/19621858/23093091/d8b8406c-f5d9-11e6-840d-dfea6b8b213a.png)

**Comment by Catzenjaeger** [comment]
sorry not solved

![grafik](https://cloud.githubusercontent.com/assets/19621858/23093960/7a1142f4-f5f0-11e6-84f7-016e41562121.png)

**Comment by meangczac** [comment]
I fixed this one.
