### ISSUE TITLE
profile - impages to big

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1304]
![grafik](https://cloud.githubusercontent.com/assets/19621858/23093119/85dc93ba-f5da-11e6-92d5-34fe685a6b89.png)

**Comment by RobiNN1** [comment]
reupload 
https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/templates/default.css
and 
https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/templates/default.min.css

**Comment by Catzenjaeger** [comment]
thanx solved
