### ISSUE TITLE
Nebula theme error

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1308]
so the images appear. Only the theme Nebula
![vagolap01](https://cloud.githubusercontent.com/assets/16163102/23113648/d1b28262-f739-11e6-97e3-5519aa20d7a2.jpg)

**Comment by karrak1** [comment]
not good

**Comment by RobiNN1** [comment]
Reupload https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/FusionTheme/ThemePack/Nebula/css/panel.css and press CTRL + F5

**Comment by karrak1** [comment]
Sorry.. Ok..
But
Not good smilley Shoutbox, and contact image.

![vagolap01](https://cloud.githubusercontent.com/assets/16163102/23152015/4b72f170-f7ff-11e6-82b2-bbbd8a241ca1.jpg)
![vagolap02](https://cloud.githubusercontent.com/assets/16163102/23152016/4b75d96c-f7ff-11e6-900f-99b8a0371ba0.jpg)

**Comment by Kvido** [comment]
@ RobiNN1
Pictures show (according to recent changes) ONLY cutouts photos. This is bad, the ugly!
To be images on HomePage reduced / transformed into small mine adjustments:
```
figure {img
     width: 100%;
     height: auto;
}
```
Look at my Homepage
https://pc-politika.cz/homepage
