### ISSUE TITLE
user fields

### ISSUE THREAD

**Issue by bronxi** [PHPFusion/PHPFusion#1309]
QuantumFields.inc
/administration/user_fields.php?aid=349363d15c2c9fb5
Line: 1940
1 minute ago		New Solved Ignored Delete
Severity : Run-time notices

Undefined index: field_config

**Comment by ovasclub** [comment]
![-2](https://cloud.githubusercontent.com/assets/16386011/23122801/f276fe1e-f78f-11e6-935b-6cdbe031dc3e.jpg)
add
Do not show the correct icons
[http://ovas.club/profile.php?lookup=1](url)

**Comment by meangczac** [comment]
which theme?

**Comment by bronxi** [comment]
Bootstrap theme

**Comment by meangczac** [comment]
@bronxi , the field config error should not happen. How do you get that? I need to know what to click to get that error.

**Comment by meangczac** [comment]
Caught the bug..
