### ISSUE TITLE
1 extra step?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1312]
After init and successful creation I get this, 2 notice windows with info ( should be debug and not public I guess?.) 
and then I get to click next again, just skip that part. auto next on success.

![untitled-4](https://cloud.githubusercontent.com/assets/4210004/23146924/6b6628ea-f7db-11e6-9429-68592239c39f.jpg)

**Comment by meangczac** [comment]
This is in #1180
