### ISSUE TITLE
Custom Pages first page info Category is static Page ID

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1319]
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/23147477/787ae26a-f7df-11e6-8713-4e0d5a7a297b.jpg)

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/5fb8a3b0257869fc57279f5a8a08c0c07f8733ae


![screen](https://cloud.githubusercontent.com/assets/11664877/24367598/7f4da4f2-131d-11e7-83c6-362c831dc454.png)
