### ISSUE TITLE
Required extended articles toggler

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#132]
There are a \* showing red as in required ( the colour on it ) even when this setting is turned off in the article settings.

**Comment by meangczac** [comment]
hmm.. should not be. i have tried it. can you make a print_p($article_settings);  and see why?

**Comment by meangczac** [comment]
Ah. I know you're referring to Article admin, but the checkbox on was for forcing guest to submit a full article in article_submit.

I will turn it off in article admin as per default.

**Comment by JoakimFalk** [comment]
yeah no red *, so it works as is now
