### ISSUE TITLE
Edited Album image get randomly removed

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#133]
Here I edit the middle album, giving it a new image.
![edit-1](https://cloud.githubusercontent.com/assets/4210004/9354638/6c1df1da-4672-11e5-92ac-6b7de2380d3f.png)

Right after I move the album, push back or up and the image is gone. It is not a cache issue. verified.
![restored](https://cloud.githubusercontent.com/assets/4210004/9354639/6fd184ae-4672-11e5-87ae-88e164c8a185.png)

You can see it was possible on the parent image up top, the image was saved and remains so.

**Comment by meangczac** [comment]
Recoded
