### ISSUE TITLE
Member Profile View are missing all Admin action options

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1333]
A basic set of admin options, as seen in 7 are a minimum requirement.

**Comment by RobiNN1** [comment]
Super admin can't edit, therefore does not show admin actions in profile.

**Comment by JoakimFalk** [comment]
Admins need to be able to edit. Just as in 7. I port it in eventually if we don´t have a better solution.

**Comment by JoakimFalk** [comment]
No options on single member seen.
![untitled-3](https://cloud.githubusercontent.com/assets/4210004/23235363/84efe5aa-f955-11e6-897e-209d933d9041.jpg)
