### ISSUE TITLE
search

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1335]
1.) 
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/23174731/98e8b486-f85d-11e6-8f78-0d2e8297efae.JPG)

2.) only 10 results shown and no page nav when i have more as 10

**Comment by meangczac** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/23409421/868182ba-fe06-11e6-9d15-65d2e11b1636.PNG)
