### ISSUE TITLE
Time Zones time-date display are off

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1339]
When I select differant time zones the listed times are not correct, Idk why but thats the case.
Maybe summer time / winter time  are not accounted for?

![untitled-6](https://cloud.githubusercontent.com/assets/4210004/23188924/dc495f5e-f890-11e6-9ca7-d4e60d8a023f.jpg)

**Comment by Rizado** [comment]
DST (daylight saving time - winter as you wrote) is adjusted automatically. You use linux server? I know about problem with Windows.

**Comment by meangczac** [comment]
Jock's test environment is at php-fusion.co.uk subdomains. We are on linux yes.

**Comment by Rizado** [comment]
OK, I see problem and I'll fix it today.

**Comment by Rizado** [comment]
Now it works good. Commented lines will be removed after testing.

**Comment by Rizado** [comment]
But it will be rewritten in some days. I see more simple way for works with timezone. I want to discuss this with @FrederickChan and @Domi-php . 
See. Timestamps in DB are in Unixtime. It means anyway UTC.
I propose in /maincore.php line:
`date_default_timezone_set('UTC');`
move after
```
if (isset($_POST['login']) && isset($_POST['user_name']) && isset($_POST['user_pass'])) {
    $auth = new Authenticate($_POST['user_name'], $_POST['user_pass'], (isset($_POST['remember_me']) ? TRUE : FALSE));
    $userdata = $auth->getUserData();
    unset($auth, $_POST['user_name'], $_POST['user_pass']);
    redirect(FUSION_REQUEST);
} elseif (isset($_GET['logout']) && $_GET['logout'] == "yes") {
    $userdata = Authenticate::logOut();
    redirect(BASEDIR.$settings['opening_page']);
} else {
    $userdata = Authenticate::validateAuthUser();
}
```
and change it to:
```
if (isset($userdata['user_timezone']) && !empty($userdata['user_timezone'])) {
  $site_tz = $userdata['user_timezone'];
} else {
  $site_tz = fusion_get_settings("timeoffset");
}
date_default_timezone_set($site_tz);
```
And serveroffset option will not be needed :-) .

**Comment by meangczac** [comment]
My opinion of server time offset settings.

Server time offset is to used to manual override. How abt like this.

All automatic unless override is on. Form select +24hr to -24hr as option and an extra 0 for off.
Have servertimeoffset 0 by default.

**Comment by Rizado** [comment]
OK, let it be. I leave this version as is, it works.
