### ISSUE TITLE
Editors review on the DLs looks a tad off ( Nebula )

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1341]
See it way below the box, maybe should have it inside at least?

![untitled-8](https://cloud.githubusercontent.com/assets/4210004/23190753/21e46f96-f89a-11e6-9dac-b87326558189.jpg)

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/decec6e7492a66dba6cb3fa31e279f557354af81
