### ISSUE TITLE
Why language selector on shoutbox?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1344]
Idk, if there are any particular reason as to why we have a lang selector for shouts.?
If no obvious good reason, lets keep it hidden to current language, this type of less is more.
![untitled-13](https://cloud.githubusercontent.com/assets/4210004/23191135/48f705ce-f89c-11e6-9416-6ba1b77f29b8.jpg)

**Comment by karrak1** [comment]
Only admins.
