### ISSUE TITLE
1 icon to many in weblink footer?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1347]
See the hdd upload icon
![untitled-19](https://cloud.githubusercontent.com/assets/4210004/23191607/e7cb8948-f89e-11e6-990a-67554e7c9507.jpg)

**Comment by RobiNN1** [comment]
Time Zone issue on your server 

![hgbjko](https://cloud.githubusercontent.com/assets/11664877/23230713/5109c324-f945-11e6-93ef-35051c9c6663.png)

**Comment by RobiNN1** [comment]
#1340

**Comment by JoakimFalk** [comment]
No, not connected.

**Comment by JoakimFalk** [comment]
nm, it is.
