### ISSUE TITLE
Polls Start and End Dates is missing in the panel and archive and admin

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1348]
Panel 
![untitled-21](https://cloud.githubusercontent.com/assets/4210004/23191717/8512dada-f89f-11e6-8953-801b2403499c.jpg)

Archive
![untitled-23](https://cloud.githubusercontent.com/assets/4210004/23191744/ab316786-f89f-11e6-978c-fe41c125d860.jpg)

Admin
![untitled-25](https://cloud.githubusercontent.com/assets/4210004/23191800/f466bec4-f89f-11e6-91fa-a1d01348b1bd.jpg)

**Comment by RobiNN1** [comment]
Same porblem than #1347

**Comment by RobiNN1** [comment]
#1340

**Comment by JoakimFalk** [comment]
No, not connected.

**Comment by JoakimFalk** [comment]
Ok it maybe connected. Will try a fresh set of settings. Yes Confirmed was the fubared Time/Date that made it 0, even tho settings was hardcoded. We need to fix the glitch in https://github.com/php-fusion/PHP-Fusion/issues/1340
