### ISSUE TITLE
Gallery directories, The Return

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1350]
I would really like to see the return of album_x directories in this Gallery. Perhaps after launch. 

Suggested change ( think it is how it was? ) but nevertheless, we need it. It becomes to messy to fast with out it.
 
photos/ > albums/
then in albums > 
Thumbs in a thumbs dir
album_{ID}>thumbs/
and photo files in root
album_{ID}>ROOT

**Comment by meangczac** [comment]
Can, wait for 3 weeks on this. I'll deliver it last.

**Comment by meangczac** [comment]
The Version 7 method of 'guessing' what is the next ID could be used. 
But it is best to write such major change after stable. 

I will keep this issue open.

**Comment by JoakimFalk** [comment]
yeah , well I would not call it guess. By checking auto increment you know next id, it will be a fact. The function should be builtin to the databaseFactory if I remember right.

**Comment by JoakimFalk** [comment]
```
    public function getLastId() {
        return (int)$this->connection->lastInsertId();
    }
```
$id = getLastId()+1; or something :)

**Comment by JoakimFalk** [comment]
Placed on next ver
