### ISSUE TITLE
What is featured?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1353]
And where is the link suposed to go?

![untitled-9](https://cloud.githubusercontent.com/assets/4210004/23192634/d27faece-f8a4-11e6-8334-0edaa86db9d7.jpg)

**Comment by meangczac** [comment]
When u sticky something.

**Comment by meangczac** [comment]
Them links are not yet made. It was something I made for Main at first, then I got disarrayed by other issues. There are more pages yet to be coded if "See All" since the list is just fetching a few. I'll code them when other issues is lesser.
