### ISSUE TITLE
Forum attachment zip file DL does not initiate

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1354]
Click goes thru, no DL starts.

![untitled-11](https://cloud.githubusercontent.com/assets/4210004/23193198/f8c35358-f8a7-11e6-8899-5e063ea23f77.jpg)

**Comment by JoakimFalk** [comment]
The images display nice tho, even pretty grouping !

**Comment by meangczac** [comment]
Can download also... all working fine. Is SEO on?
![can_download](https://cloud.githubusercontent.com/assets/4078041/23328603/4e75d1a8-fb60-11e6-8c87-5f4c425e419a.PNG)

**Comment by meangczac** [comment]
Can but no driver on them link. I dont think I want to add another SEF url on the attachs.
Forum SEF is too heavy.

**Comment by JoakimFalk** [comment]
Still does not work for me in Chrome on test, the download does not fire.
http://next.php-fusion.co.uk/final9/infusions/forum/viewthread.php?thread_id=2
