### ISSUE TITLE
Forum polls wierd glitch

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1355]
When you create a poll in a thread it is all working nice.
Delete this poll and add a new one from the button will make the answers not match the text.

The order is clearly 1) Yes 2) No
![untitled-13](https://cloud.githubusercontent.com/assets/4210004/23193432/48f7d8b6-f8a9-11e6-8a76-d9c2f1f6178e.jpg)

But in reality it becomes no / yes
![untitled-15](https://cloud.githubusercontent.com/assets/4210004/23193463/71e08a16-f8a9-11e6-8631-40f14a2082d3.jpg)

So I remove poll and make a new one, OK it reversed order of answers, but maybe works anyway
![untitled-17](https://cloud.githubusercontent.com/assets/4210004/23193514/a5612a4e-f8a9-11e6-9609-a872c2796aff.jpg)

However, the output is no, but I voted yes.
![untitled-19](https://cloud.githubusercontent.com/assets/4210004/23193546/d1159652-f8a9-11e6-9fb8-2737296b99f2.jpg)

To be clear,  this issue only occurs if you once remove the first poll created and make a new one again.

**Comment by meangczac** [comment]
But I can't replicate this issue. Is SEO on?
