### ISSUE TITLE
Change versioning to 9.0 from 9.2 for final

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1358]
Can wait but needs to be done before release.

**Comment by meangczac** [comment]
I thought it was 9.02. Because we haven't release 9 yet, officially speaking..? 
So all I just did was minor version. 

We're currently on fusion_get_settings('version') == 9.02

**Comment by JoakimFalk** [comment]
Thats why it is 9.0, all else  are revisions of alpha, beta, rc´s.  but sure anything goes it is a small thing.
For future, it is better to stick to naming the Revisions as you want so final release number never is affected by internal dev numbers.
