### ISSUE TITLE
Upgrade halts installer no chance to go thru

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1360]
Fatal error: Access to undeclared static property: PHPFusion\Steps\InstallerDbSetup::$allow_delete in /home/pfdemos/public_html/v7_Default/includes/classes/PHPFusion/Installer/Steps/DatabaseSetup.inc on line 264

There is also a tad unclear that you are doing an upgrade. Flag it clearly.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/d69c9ebdc759b2a63d601303b02a916c3133aaa5
