### ISSUE TITLE
General Images relative pathing issue in SEO Mode 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1377]
So we have this, 

path : final9/weblinks
![untitled-12](https://cloud.githubusercontent.com/assets/4210004/23241486/910dba2e-f973-11e6-88d5-1ecee6e362ec.jpg)

No problem, it is 1 level.

Here for the link, we add logo type, /final9/images/php-fusion-logo.png ( default droplist )
it translates to `<img src="../..//final9/images/php-fusion-logo.png" alt="" style="margin:5px">`

now 2 slashes and to few dots is not gonna cut it, the SEO path is 
/final9/weblinks/1/test-weblink-cat so it need to do something else.

**Comment by meangczac** [comment]
Multiple Git. All infusions should be fixed by now.
