### ISSUE TITLE
Comments redirect (jquery comments off) fails on post ( SEO )

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1384]
Cross the board except in News ! it actually works there !

Could be driver in all permalink modules or a comment function issue. but well the famous , 
![untitled-4](https://cloud.githubusercontent.com/assets/4210004/23242433/08bddfb8-f979-11e6-9101-e64b2285adae.jpg)
When commenting.

**Comment by meangczac** [comment]
Test Phase: 

**News Infusion** 
Comments Jquery On / SEO Off -- pass
Comments Jquery Off / SEO Off -- pass
Comments Jquery On / SEO On -- pass
Comments Jquery Off / SEO Off -- pass

**Comment by meangczac** [comment]
Blog Comment - Cleared 4 test phase
Article Comment - Cleared 4 test phase

**Comment by meangczac** [comment]
Downloads - cleared
Gallery - cleared -- closed an issue.

**Comment by meangczac** [comment]
Close case.
