### ISSUE TITLE
Why theres no difficult errors in errorlog?

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#1388]
In the new error log, I cant see what error it is.

Errors.php says not enough, it can be in very folders
And only a Line number with out a difficult error description is bad.

in RC4 i can see all errors with difficult description, and i can see what error is it.

**Comment by meangczac** [comment]
In fact, the one in RC5 has more functionality.

Please read this post I made regarding the stack tracing.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38204&highlight=stack+trace&pid=201250#post_201250

I have covered everything. The one in RC4 is lenghty and far too simple to cover SQL query. RC5 gives you a complete head to toe stack trace on how the error occured so you can open up all the files from 0 to final and run a system debug using xdebug or similar.

**Comment by JoakimFalk** [comment]
Click on the reports, it is collapsed.
