### ISSUE TITLE
No Upgrade vom RC4 to RC5

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#1389]
I've got this.
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'link_status' in 'where clause'
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cp.page_cat' in 'where clause'
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cp.page_user' in 'on clause'

But there's no Upgrade.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/d69c9ebdc759b2a63d601303b02a916c3133aaa5

Please try again.
