### ISSUE TITLE
Time Date Settings not taking translations

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1395]
Allthough I have the correct Danish monthnames in the relevant locale files, settings for dat format still show English month names.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38267&pid=201456#post_201456

**Comment by karrak1** [comment]
modify 
locale/language/admin/settings.php

$locale['dateformats'][] = "%m/%d/%Y";
$locale['dateformats'][] = "%d/%m/%Y";
.........

According to the desired time display
