### ISSUE TITLE
allowed_file_type in blog, news, and gallery

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1396]
In Content Admin > Images > Upload 
Jan, had an error of image type, but where do we define these general settings?
Seems as if they poofed out from misc.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38266&pid=201472#post_201472

**Comment by meangczac** [comment]
they are handled each on their own infusion.

**Comment by JoakimFalk** [comment]
Read the whole thing. This is not an Infusion. What settings do we need for these images?
Maybe even a whole new section , general image settings?
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/23332893/ca7951be-fb81-11e6-8631-19d91d687f1a.jpg)

**Comment by JoakimFalk** [comment]
Gallery, News, Blog and This image upload function are missing specific file type options while downloads and forum have specific file type options. 
This means that we either need a general file types tab that is global when not given or make a new setting tab for each section that is missing these options. Right now as you can see on the above error report you get issues from both this given example and gallery on not allowed types but there is no way to change it.

**Comment by meangczac** [comment]
For global ones, allow all size, allow all types. We won't be making $settings already and cause dependencies. I'll amend the title for this one.

Add Allowed File Type
- Gallery
- News
- Blog

**Comment by JoakimFalk** [comment]
Karrak´s Git´s today covers most, Closing this. We need to test Gits.
