### ISSUE TITLE
Articles does not open correctly selected language file

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1400]
It seems that the article submission function use English even if site language is Danish.
See attached image.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38275&pid=201492#post_201492

**Comment by meangczac** [comment]
The language file name... 

https://github.com/php-fusion/PHP-Fusion-9-Locale/commit/e7713fb0e105c139d74fe15de07c2d0a922679da

https://github.com/php-fusion/PHP-Fusion-9-Locale/commit/8994bf10cdd4e848d86c984560720a40f137df06

https://github.com/php-fusion/PHP-Fusion-9-Locale/commit/e7b4d06bb646223ed164b0bd086a2f1833e4dd16

https://github.com/php-fusion/PHP-Fusion-9-Locale/commit/22573b7aeeea17681f60b78b0b84f12c726482ae

https://github.com/php-fusion/PHP-Fusion-9-Locale/commit/08843d96bf9b69123fc5b55efc79da399dc2b986

https://github.com/php-fusion/PHP-Fusion-9-Locale/commit/f6826f8756842a3aefc251fecfa8473ce8088825
