### ISSUE TITLE
hardcoded locale , installer

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1401]
In includes/classes/PHPfusion/Installer/Steps/Introduction.inc
this text is hardcoded:

> Note:</strong> Like Version 7 requirements - Your Database Must Exist and Empty</li>                                    
>             <li>Don't report any issues in Github with the v7 installer. If it doesn't work for you, try other method.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38279&pid=201491#post_201491

**Comment by meangczac** [comment]
I already said Don't report any issues...
