### ISSUE TITLE
Upgrade error from RC4 to RC 5

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#1402]
In step Database settings

outputs: 
running once 
Notice: Query Error: SELECT * FROM ihg_photo_albums

Stack Trace:
upgrade/9.02.upgrade.inc(692): dbquery('SELECT * FROM i...')

I dont have installed gallery in this case. Theres no infusion installed. 

The complete installation is dropped.

For upgrading from RC4 to RC5 theres no option. We do a complete new installation.

**Comment by Webmeteor** [comment]
After uprgrading i cant open login.php redirects to "login-to-website" but there comes an 404 error

login.php is on server.

All settings are on default without panels. There is no way to login

**Comment by Webmeteor** [comment]
And old passworts dont work!!!!!!!!!!! GRRRRRRRRRRRRRRRRRRR
Now I must setup new

**Comment by Webmeteor** [comment]
Infusions Update dont work. (Articles etc.
Renames the config.php to config_temp.php and stops with error no conig.php oder install.php found

**Comment by meangczac** [comment]
I have tried huge number of times v7 to v9, I haven't try RC4 to RC5.

**Comment by meangczac** [comment]
Backup your DB. Then selectively execute them over Phpmyadmin once the new RC5 installs. 
I'm terribly sorry, but I can't help this case... just too many variables and I need all them error logs to know what happens in the system.
