### ISSUE TITLE
Reworking Locale

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1403]
Hello.

I´m on the reworking of german locale.
I got those Errors in the errorlog i attached on the screenshot.
Are they related to the  locale or not?
Can´t find the Problem.

Greatz WuChEn
![unknow](https://cloud.githubusercontent.com/assets/164333/23339272/f834ba56-fc1e-11e6-8a90-25d9dcb1241e.png)

**Comment by Webmeteor** [comment]
by clicking on the file name, you can expand and see detailed error.
if undefined index it's a language error.

Some files i've added yesterday in the German git files.

**Comment by meangczac** [comment]
Thanks for clarification.

form_checkbox.php <-------- click here.
