### ISSUE TITLE
Cant add new administrators

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#1409]
cant find Username and cant find UserID.

No errors in Log

**Comment by JoakimFalk** [comment]
These are my results in the test environment, perhaps you have some versioning glitch.
As you can see I pull both from name and id, two differant users.

![user_name_admin](https://cloud.githubusercontent.com/assets/4210004/23344246/47f06860-fc79-11e6-95d1-44f5cde42662.jpg)

![user_id_admin](https://cloud.githubusercontent.com/assets/4210004/23344244/335a433a-fc79-11e6-8eb2-ff099388b881.jpg)

**Comment by Webmeteor** [comment]
it's from the current gitrepo from yesterday afternoon.

**Comment by karrak1** [comment]
search user id or user name ->
select user ->
select Admin or superadmin

me good

**Comment by Webmeteor** [comment]
I know how to set admin btc superadmin. Is like 7.02. But iz doesn't.

After Upgrade from 9 RC4 to RC5 the second user was resetet from 
user_level 103 to 0. That was the problem. The rights were correctly settet.


---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by meangczac** [comment]
V9 uses negative numbers on all user level.

0 public
-101 member
-102 admin
-103 super admin.

But can you manually adjust his administrator access ok?

- 9 RC4 to RC5 the second user was reset from user_level 103 to 0 
I'm not sure where to fix this issue without knowing what caused it.
