### ISSUE TITLE
Custom pages are missing it´s preview function

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#141]
Custom pages are missing it´s preview function

**Comment by meangczac** [comment]
The preview function was taken off deliberately when CP was redesigned. I renabled it, but no execution of codes.

http://stackoverflow.com/questions/14653201/storing-code-in-an-sql-database-and-executing-it
Been there myself. It's very, very, very bad ending. Not all hosting companies run 10 firewalls, and it's the software company that takes the fall. It's a very serious accusation and why a software developer need to feature it then? So few reward for such a big problem.

Panels. They must not as well. Upload them files. That's the standard.

**Comment by JoakimFalk** [comment]
We have Admin password, Admin checked rights
I see no dif in preview and save / execute the content, still have the data in the DB,
We still have preview in panels. Can´t have it hanging to only do a little bit, it is on or 100% off. Hence remove the function as a whole in both panels & custom pages as well as dropping custom pages. I don´t think it sounds reasonable.
