### ISSUE TITLE
MySQL supports only explainable select before MySQL 5.6

### ISSUE THREAD

**Issue by rimelek** [PHPFusion/PHPFusion#142]
includes/db_handlers/all_functions_include.php contains an EXPLAIN statement, which tries to explain each query, but before MySQL 5.6 only the select was explainable. 

It is hard to determine if the query is a valid select or an invalid select or not a select at all even if we check the version of the MySQL. And think about MySQL compatible database servers like MariaDB. We can get features in different versions.

Currently this debug funtionality does not work using PDOMySQL driver and generates many SQL errors into the error log. And any time we try to delete an entry in error log, we get a new (before MySQL 5.6), because DELETE and UPDATE is not explainable.

I don't see what the real advantage of EXPLAIN why we should solve this issue. I recommend to remove it **if we want to support MySQL 5.5.**

**Comment by meangczac** [comment]
Yes, deprecate it please. I doubt many servers run beyond 5.5

**Comment by rimelek** [comment]
It's already done. I forgot to close: https://github.com/php-fusion/PHP-Fusion/commit/0b6c5d4771f2a38b18f1d4390a89f64a6093779e
