### ISSUE TITLE
Default captcha set on an upgraded system will crash it

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1430]
![untitled-6](https://cloud.githubusercontent.com/assets/4210004/23388323/b93d919e-fd61-11e6-95fa-15fa7a44e223.jpg)

Fatal error: Call to undefined method ThemeFactory\Lib\Modules\Footer\Contact::setRequiredJavaScript() in /home/pfdemos/public_html/v7_Default/includes/captchas/securimage2/captcha_display.php on line 36

**Comment by meangczac** [comment]
Change to no captcha on upgrade

**Comment by JoakimFalk** [comment]
Confirmed Fix.
