### ISSUE TITLE
What on earth is this?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1449]
I added Russian, went to home and I see this only and error log have 60 issue entries. 
Issue is only on frontpage. Was fine yesterday. for reference.

![untitled-5](https://cloud.githubusercontent.com/assets/4210004/23437832/e32fde36-fe0f-11e6-8c37-bff108f22754.jpg)

**Comment by FrederickChan** [comment]
The locale was incorrect or not obtainable. I need error log.

$locale = fusion_get_locale('mickey_mouse', LOCALE.LOCALESET.'setup.php');

will return full setup.php $locale array.

**Comment by JoakimFalk** [comment]
Just because you don´t get it does not mean it is fixed. Keep it open. Issue is still there afik !

**Comment by JoakimFalk** [comment]
Works on latest git with Eng, so closing it at that.
