### ISSUE TITLE
Langhub still not 100% restored

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1450]
It works 50% on gallery ( only tested Gallery now )
This is a Russian Photo. It do display the photo now,  BUT the site has not changed it´s locale on the fly for the user, we can assume anyone clicking Russian links also expect the site to be read in Russian and that was the orginal functionallity of the hub. 

![untitled-7](https://cloud.githubusercontent.com/assets/4210004/23438001/6cf18372-fe10-11e6-9d67-24e7821a0031.jpg)

**Comment by meangczac** [comment]
Will look into each individual issues. I'll close this general statement.

**Comment by JoakimFalk** [comment]
It is not a general statement it as an issue of a 50% working fix. Close it when 100% solved.

**Comment by JoakimFalk** [comment]
The solution is flawed somewhere, I have tested back and forth quite a bit.

Guests never gets the language of the linked content on page, this is a Russian Image and a Gust viewing it, clearly the site locale stays in Eng.
![untitled-6](https://cloud.githubusercontent.com/assets/4210004/23575244/67123cf4-008a-11e7-8cdb-f4d6d866f040.jpg)

Members do get correct translation sometimes but it seems to only be when you have not selected a default languge, if you have then the site won´t change even on content request from other languages.

**Comment by meangczac** [comment]
Hmm. Wait for it then. I need 2 perfect translations to dig deeper. Give me a couple of days
