### ISSUE TITLE
redirects to index.php when there is an issue in own infusions

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#1451]
and no logs in error_log

I get this link from error.php
/infusions/kalender_panel/infusions/kalender_panel/viewpage.php?page_id=1

and this is the form action url
KALENDER.'admin.php'.fusion_get_aidlink().'&action=insert
KALENDER = INFUSIONS.'kalender_panel/'

without error it goes to.
This link working
KALENDER.'admin.php'.fusion_get_aidlink()."&action=bearbeiten&id=".$data['kalender_id']
KALENDER.'admin.php'.fusion_get_aidlink()."&action=delete&id=".$data['kalender_id']

but without error reporting i can't find the error

**Comment by Webmeteor** [comment]
My full code you can see here [https://github.com/Webmeteor/kalender_panel/blob/master/admin.php](https://github.com/Webmeteor/kalender_panel/blob/master/admin.php)

**Comment by Webmeteor** [comment]
function openform() causes the error.
With FUSION_REQUEST as action url and the GET Paraemeters as hidden fields it's working

**Comment by Rizado** [comment]
In my humble opinion :-) , redirect from main page is bad idea. In first for SEO - search systems don't like redirects. Include is better.

**Comment by meangczac** [comment]
form_action , try clean_request() as a wildcard fix. It's best in many situation where $_GET is messy.

````
clean_request('', ['section', 'aid'], TRUE);
````
This will keep just $_GET['section'] and $aid and wipe the rest.

If you know your $_GET parameters, 
````
$all_my_gets_in_this_program = ['ref', 'readmore', 'action', 'id', 'cid'];
$action_url = clean_request('', $all_my_gets_in_this_program, FALSE);
````
This will remove all the above $_GET in your $action_url.
