### ISSUE TITLE
fusion_first_words() problem

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1452]
This function doesn't trim text which contains "<br><br>" (line break tag without slash repeatred twice). There is nothing in error log.

**Comment by FrederickChan** [comment]
trim(preg_replace('/\s+/', ' ', $string));

**Comment by meangczac** [comment]
$string = preg_replace('~[\r\n]+~', '', $string);

**Comment by meangczac** [comment]
So how many word should we count per \n ? 1 word?
