### ISSUE TITLE
Sensitive data are visible -- fast fix necessary

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1453]
today my host have problems (sql dosent work) but now anyone can see all my data 

plz fix this .. This is absolutely fatal if everyone can see these sensitive data

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/23484164/2dd29a16-fed6-11e6-9697-3e1a84f0a473.JPG)

**Comment by meangczac** [comment]
It happens.

**Comment by FrederickChan** [comment]
I'll make the fix this afternoon.

**Comment by Catzenjaeger** [comment]
thank you so much

**Comment by meangczac** [comment]
I'm advising you to change the whole password and update your config.php after such exposure.

**Comment by Catzenjaeger** [comment]
thanx for your tip -- i have do that :) better is better

**Comment by Catzenjaeger** [comment]
whats wrong ???
i have change my user and password and change this too in my confic

now my site says: Website configurations do not exist, please check your config.php file or run install.php again.

i have only change this where i have marked .. all other (XXXXX) i have not change
but i get no connection

Website configurations do not exist, please check your config.php file or run install.php again.

or in phpmyadmin i get htis:  mysqli_real_connect(): (08004/1040): Too many connections

// database settings
$db_host = 'localhost';
$db_user = 'i have change this';
$db_pass = 'i have change this';
$db_name = 'xxxxxxx';
$db_prefix = 'xxxxxxx';
$pdo_enabled = x;
define("DB_PREFIX", "xxxxx");
define("COOKIE_PREFIX", "fxxxxxxx_");
define("SECRET_KEY", "xxxxxx");
define("SECRET_KEY_SALT", "xxxxxx");

in my adminarea from my hosting company i see this:
ERROR: Zend_Db_Adapter_Exception: SQLSTATE[08004] [1040] Too many connections (Abstract.php:144)
Search for related Knowledge Base articles

**Comment by Catzenjaeger** [comment]
is a problem with one of scripts that shut down sql for my account
omg
this tell me my hoster for some minutes
