### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1455]
token.php
/site/includes/classes/PHPFusion/Feedback/Comments.ajax.php?action=edit
Line: 75
Severity : Run-time notices
Undefined index: form_id

token.php
/site/includes/classes/PHPFusion/Feedback/Comments.ajax.php?action=edit
Line: 75
Severity : Run-time notices
Undefined index: 

**other error:** when i edit a comment and i will add a smilie or change one ... no popup for this are shown.

**Comment by FrederickChan** [comment]
Ajax on or off?

**Comment by meangczac** [comment]
textarea 'form_input' binding is off. Which script is this?
