### ISSUE TITLE
Merging article snippet and full text

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1460]
render_article_item($info) function displays article text as merged snippet and full text? Why?
Sometimes snippet isn't repeat first paragraph(-s) of text. When user want, he/she can merge these items in own function, but for output full text without snippet there is need to make additional query to DB :-( .

Is it possible to use "clean" text without snippet?

**Comment by JoakimFalk** [comment]
I think it was cloned from News, 
article_snippet,  is the db table for snippet
article_articlem is the db table for full 
It can differ from theme template I guess, or maybe we only have 1 default template for this one now? idk.

**Comment by Rizado** [comment]
@Domi-php the key difference with v7 is that now CMS call render function with news information and there is no sense to make additional query (for better perfomance and by other reasons).
I used print_r() for test - into render function CMS passes merged texts and snippet separately.
I propose to pass into function snippet and full text separately.

**Comment by JoakimFalk** [comment]
oh, I thought they did. I totally agree they should be separated. Please do what you need before my testing rounds finnish.

**Comment by Rizado** [comment]
Done. @Domi-php, please see comments.
