### ISSUE TITLE
Important - register dosent work

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1461]
i have update my system with all new core files for a hour. 
now i and a ohter guy have try to register .. but we get no mails and in my system i cant see "unactivated" members. 

**Databse is also empty with new entries.**

is this problem known?

i get no mails . the other guy too
spam we have checked

UPDATE: the mail coming in now but 1 or more hours later

**Comment by JoakimFalk** [comment]
Ah this is most likley due to routing of the email server / isp you have. Fusion does not down prio messages they are sent instantly, rest is up to host / isp / location.
