### ISSUE TITLE
Internal Error can not send message - contact.php

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1463]
contact.php Line: 54 Undefined offset: 424

![untitled-2](https://cloud.githubusercontent.com/assets/4210004/24638278/75d681ee-18e7-11e7-91ff-362614f525ab.jpg)

**Comment by karrak1** [comment]
corrected

**Comment by JoakimFalk** [comment]
Not fixed

**Comment by meangczac** [comment]
Please test again. 

contact.php Line: 54 Undefined offset: 424

only happens when this line fails:
$locale = fusion_get_locale('', LOCALE.LOCALESET."contact.php");

I'm double guessing here - git sync not complete.

**Comment by JoakimFalk** [comment]
still broken

**Comment by meangczac** [comment]
The contact.php form has locale error and I've fixed SEO path.

**Comment by JoakimFalk** [comment]
Works !
