### ISSUE TITLE
Some glitch in the mlang hotlink switch

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1465]
As you can see the language is now changed on site but only array it. ( Translation do exist, see pic 2 )

![image](https://cloud.githubusercontent.com/assets/4210004/23583930/66365eb4-0152-11e7-9624-6ae26600cf1b.png)

Nothing wrong with the locale after I hard switch manually to the language.

![image](https://cloud.githubusercontent.com/assets/4210004/23583940/a242f4b2-0152-11e7-8515-c052af319f64.png)

**Comment by meangczac** [comment]
Finishing on last infusion forum now. 

Will start core locale files inspection.

After that i resume with php fixes.

**Comment by FrederickChan** [comment]
I don't see a glitch now.
