### ISSUE TITLE
Translators have confusion with faq locales Normalize this section

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1468]
It is mixing faq_xxx and faqs_xxx

**Comment by meangczac** [comment]
Fixed the locale reindex and multiple cleanups. 

https://github.com/php-fusion/PHP-Fusion/commit/e8e06bbdea3315297df4c75196da0067ce3b5cf7

Just info:

FAQ is an acronym, referring to the Frequent Asked Question system. 
A system, is singular.  
It's like NATO (North Atlantic Treaty Organization), you cannot use NATOs. Hence, FAQs are wrong. We don't have many FAQ system. We only have 1 FAQ system. Referring to sets of questions and answers, we can use alternative as "Answers", or "Questions", but never "Q&As", which is again wrong.
