### ISSUE TITLE
Time Date Settings

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1470]
F:\xampp\htdocs\PHP-Fusion\administration\settings_time.php
/administration/settings_time.php?aid=e3e76a16700cf8fa **
Line: 72
Severity : Non fatal Runtime Errors
A non-numeric value encountered

**Comment by meangczac** [comment]
@rizado pls help. i'm still checking locale.

**Comment by Rizado** [comment]
OK

**Comment by meangczac** [comment]
Thanks.

**Comment by Rizado** [comment]
It's ready.
