### ISSUE TITLE
Shoutbox broken non SEO Edit / Posting

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1473]
See title

**

Update: Edit Shout link to current Page like

submit.php?stype=l&s_action=edit&shout_id=1#edit_shout

infusions/downloads/downloads.php?s_action=edit&shout_id=1#edit_shout

**Comment by JoakimFalk** [comment]
It is not an issue unless it actually does not work?
The shout use issets since it is a panel and need to work globally.

**Comment by Der-WU** [comment]
But it  doesn't Work. If i try to Edit an entry in Frontpage. Nothing happens.  Only the URL Change.

**Comment by JoakimFalk** [comment]
You are correct, shoutbox broken AGAIN, LOL.

**Comment by meangczac** [comment]
I just tested 1 sec ago with latest pull, it's not broken.

Please retest after Logout > Clear Cache > Login. Install new Shoutbox.
------------------------------------------------------------------------------------

Delete shout can work or not?

If Delete shout can work, Edit should work. 

I just tried, all working fine. If you click edit, the shoutbox should call value back.

Editing..
![capture](https://cloud.githubusercontent.com/assets/4078041/23818030/bbc7f092-0632-11e7-8d07-803a972719da.PNG)

**Comment by Der-WU** [comment]
Tryed a clean install.
Created a post.
Edit Post nothing happens, only URL changes.
Deleting working fine with popup and question to delete.

**Comment by meangczac** [comment]
Where is your site? I take a look. Give me user: guest_admin, pass: 12345678, email:any@email.com

**Comment by Der-WU** [comment]
take a look @ www.der-wu.de account is created like you say.

Greatz

**Comment by meangczac** [comment]
Wu, 

Please install and delete the install.php from yoir server first.. its dangerous to open like that.

**Comment by Der-WU** [comment]
Done. In the road with my Mobile Phone i can Edit the entrys. I  Check it again with Edge and Chrome in the evening with my laptop.

**Comment by meangczac** [comment]
I have to admit the editing is not very visual. However, it works. I tested multiple times.

**Comment by Der-WU** [comment]
Ok work fine.
You are right, it was my misstake.
After pres edit, i have never look into the shoutbox.
thX
