### ISSUE TITLE
Admin Menu are changed after save on iPAD

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1475]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38335&pid=201663#post_201663

**Comment by JoakimFalk** [comment]
Let´s roadmap these for any later versions if the issues still exists.

**Comment by helmuthm** [comment]
Still exists 😁

![image](https://cloud.githubusercontent.com/assets/9512774/24320772/3adca3aa-113c-11e7-910e-615ae70e84b9.jpg)

**Comment by FrederickChan** [comment]
There you go..

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/c2c8a65a36beffe24a7f4be08e80b0c31526b790

There, hopefully fixed.
