### ISSUE TITLE
Fileinput Language Translations

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1480]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38342&pid=201694#post_201694

**Comment by Rizado** [comment]
It's not in Downloads Administration. form_fileinput function doesn't use locale.
I propose to add value "short_lang_name" to global.php locale file: "en" for English, "ru" for Russian, "es" for Spanish etc. and use this value for such functions.

**Comment by JoakimFalk** [comment]
Ah yes I see, I am for any solution that will localize it. :)

**Comment by meangczac** [comment]
@rizado 

Please proceed.

**Comment by Rizado** [comment]
OK, today some later. At evening in my time.
