### ISSUE TITLE
Update from RC1

### ISSUE THREAD

**Issue by ALTUN69** [PHPFusion/PHPFusion#1481]
How can I update from 9.00 to 9.02?
A clean install version will be released.
Thank you

**Comment by meangczac** [comment]
Well, run the install.php, without deleting config.php.

For infusion, please upgrade each individually.

**Comment by ALTUN69** [comment]
I did what you said. This error has occurred. The update screen did not appear.

Fatal error: Can't use function return value in write context in /home/alapelit/public_html/fusionturkey/includes/classes/PHPFusion/Installer/Steps/Introduction.inc on line 36

**Comment by meangczac** [comment]
this line crash:
if (!empty(fusion_get_settings('version'))) {

I think it's your PHP version, can I say which version?

I'll accompany you till your case work.

**Comment by meangczac** [comment]
no response. closing. I'll still get notification if anyone post here.
