### ISSUE TITLE
comments mobil/smartphone

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1482]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/23827717/02c6b2bc-06ba-11e7-9634-1db603c707ec.JPG)

**Comment by meangczac** [comment]
Which one is this?

![capture](https://cloud.githubusercontent.com/assets/4078041/23828039/0b3223f6-06ff-11e7-98ba-aac007732fb5.PNG)

**Comment by RobiNN1** [comment]
ReCaptcha v2 is not responsive.
https://github.com/google/recaptcha/issues/61

**Comment by FrederickChan** [comment]
kill it

**Comment by meangczac** [comment]
thats the case then i'm closing. good find @RobiNN1 . Thank you!
