### ISSUE TITLE
Change font in the news

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1484]
[Size =] [/ size] does not change the font in the news. The pages and the forum are correct.

**Comment by meangczac** [comment]
News are using HTML. It's 
````
<h1>BIG</h1> 
````
for
<h1>BIG</h1>

**Comment by ovasclub** [comment]
It turns out like this
![-9](https://cloud.githubusercontent.com/assets/16386011/23838694/8d5e1cae-07c2-11e7-8147-8168dc659b39.jpg)

**Comment by meangczac** [comment]
Shouldn't be. Which theme?

**Comment by ovasclub** [comment]
Septenary
![-2](https://cloud.githubusercontent.com/assets/16386011/23864962/51a1c072-083e-11e7-9cf2-6a8729cad374.jpg)

**Comment by meangczac** [comment]
Remove bbcode.
