### ISSUE TITLE
Watermark text always red

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#149]
I dont know how to fix this..

**Comment by rimelek** [comment]
It was easy to fix https://github.com/php-fusion/PHP-Fusion/commit/d680ca1c32b3c66a269cea254ea0a998d943c106
but after that I improved the function: https://github.com/php-fusion/PHP-Fusion/commit/9ba7f5ccbdbd8ee238fda9bcecf0c1c298df8207
