### ISSUE TITLE
Other people cannot track threads not created by themselves.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1491]
"I know for a fact that I follow at least two threads, but it is not shown using Tracked threads in drop down menu Discussion Forum"
"Using Followed threads in Private menu shows correctly"

![2017-03-17_00-08-16](https://cloud.githubusercontent.com/assets/4210004/24055344/e99277d8-0b3f-11e7-980b-39f06151b9e0.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38382&pid=201804#post_201804

**Comment by helmuthm** [comment]
problem is still there ... just tested on janmol's testsite


![2017-03-23_07-34-56](https://cloud.githubusercontent.com/assets/9512774/24235040/a23304d8-0f9b-11e7-9ad2-b1c5f177a09e.png)
![2017-03-23_07-36-06](https://cloud.githubusercontent.com/assets/9512774/24235041/a238f0dc-0f9b-11e7-9799-6d1080e88111.png)

**Comment by JoakimFalk** [comment]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38423&pid=201966#post_201966

**Comment by meangczac** [comment]
Please be precise about your bug reports. I have literally wasted hours trying to dig this issue.
