### ISSUE TITLE
Navigation menu: Members Online

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1492]
> Number and names of Members Online does not show up correctly
> at this moment it should show that admin, helmuth & Astrid are online ...
> 
![2017-03-17_09-12-09](https://cloud.githubusercontent.com/assets/4210004/24055419/3604a9c4-0b40-11e7-9325-bd30b93142a6.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38381&pid=201803#post_201803

**Comment by karrak1** [comment]
I think this is good, well count

**Comment by JoakimFalk** [comment]
He claims to only have counted and displayed one user, while in fact 3 were online. 
Let me also test it before we close.

**Comment by helmuthm** [comment]
just tested on my localhost logged in with 3 different browsers and 3 different users ... still only shows as if 1 is online :(

![chrome_2017-03-23_07-20-48](https://cloud.githubusercontent.com/assets/9512774/24234721/1cbfdc8c-0f9a-11e7-9ddd-ecc6fd16af32.png)
CHROME
![firefox_2017-03-23_07-23-14](https://cloud.githubusercontent.com/assets/9512774/24234723/1cc4a5c8-0f9a-11e7-9794-7dcefc480652.png)
FIREFOX
![opera_2017-03-23_07-24-24](https://cloud.githubusercontent.com/assets/9512774/24234725/1cca1634-0f9a-11e7-959c-4ece3f83321d.png)
OPERA
