### ISSUE TITLE
adding web links requires http://

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1494]
Ok, remove requirement / add a droplist selector of type since it can be https as well, 
> it seems that the http:// is nessescary when adding any link
> 
> wouldn't it be nice if it was there as a default value ?
> why does members have to type it when it's demanded ...

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38379&pid=201801#post_201801

**Comment by RobiNN1** [comment]
Works well.
![screen1](https://cloud.githubusercontent.com/assets/11664877/24070399/fc1c158a-0bbc-11e7-88cc-044fb902554d.png)
![screen2](https://cloud.githubusercontent.com/assets/11664877/24070401/fe63b01e-0bbc-11e7-8930-eb0da96459c1.png)
