### ISSUE TITLE
Intro image and Full news image not deleted

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1498]
> When you add a "Intro image" and a "Full news image" to a news item ... and then try to delete them > both ... images are kept - not removed

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38363&pid=201782#post_201782

**Comment by karrak1** [comment]
News Admin: it works for me, (delete image, and delete thumb)
Admin->Images
Not delete database and thumb.

repair images.php

**Comment by meangczac** [comment]
Yes affirmed.

Manage Gallery in News - Deletion will delete the image & thumbs from the file system.
Deleting news also will delete the image & thumbs from the file system.

However, deleting a news will only delete just 1 file i think.. not all the images.

Need someone verify this for me. Thanks guys.
