### ISSUE TITLE
Problems with latest git

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1504]
Fatal error: Uncaught Error: Class 'ThemePack\Nebula\Components' not found in /var/www/web1/htdocs/themes/FusionTheme/themepack/nebula/theme.php:63 Stack trace: #0 /var/www/web1/htdocs/themes/templates/global/home.php(26): opentable('Neueste News') #1 /var/www/web1/htdocs/home.php(205): display_home(Array) #2 {main} thrown in /var/www/web1/htdocs/themes/FusionTheme/themepack/nebula/theme.php on line 63

**Comment by meangczac** [comment]
rename all files and folders in FusionTheme into low case.

**Comment by meangczac** [comment]
This change is for better file management.
