### ISSUE TITLE
Email change notification.

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1510]
You can not change your email address in your profile

**Comment by meangczac** [comment]
It will send email to your account.

Localhost XAMPP without email server cannot test this. However, you can check your DB_EMAIL_VERIFY

Turn off $settings['email_verification'] in Settings > Registration Administration.

After turning off, it works.

**Comment by meangczac** [comment]
There must some form of notification.

**Comment by meangczac** [comment]
Now, for Site Owner, I'll bypass.
