### ISSUE TITLE
article counter call all page breaks

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1512]
in have a article with 7 sites - click on next site set the counter +17
thats wrong

**Comment by meangczac** [comment]
Sorry, don't understand. 
Image please.

**Comment by Catzenjaeger** [comment]
I have an article In the text of the article I have several <-pagebreak->. If I now read the article, after every click on the pagenav the counter plus one is set. So per page in the article and not per call of the whole article.

**Comment by meangczac** [comment]
Only tracker we have on user right now is 'user_lastvisit' column of users table.
We use 'user_lastvisit' to compare against any datestamp records to see if items are new or not.

Now, the refreshes of articles, downloads, etc (we have to use cookie). 

I had it there but there was a bug report stating that refreshes causing reads not incrementing. Bug reports arguably said that "reads" no matter how many time one person read it, is called reading, and therefore must +1 to read count. 

But, I can do a 'no increment if rowstart exist'
