### ISSUE TITLE
Article Adminarea

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1513]
here i miss the space to edit .. stupit .. well a admin can not have enough space/overview
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/24309430/0738e2f4-10cc-11e7-8426-e3660811c7be.JPG)

**Comment by RobiNN1** [comment]
It's okay, they're 2 columns.

**Comment by Catzenjaeger** [comment]
But squandered space. In the admin area you can not have enough space to edit.

**Comment by meangczac** [comment]
use Atermis or Material. 🙉
