### ISSUE TITLE
Missing menu band in header on bootstrap on smartphone

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1514]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/24309720/3aa12af6-10cd-11e7-9c0b-b40fd5a4b411.JPG)

this menu i miss in smartphone view

**Comment by helmuthm** [comment]
me too...

**Comment by meangczac** [comment]
What kind of phone?
Native Chrome Resize browser is Ok.

![capture](https://cloud.githubusercontent.com/assets/4078041/24320322/0928a0de-116e-11e7-8ca2-87cc1c19fa4d.PNG)

**Comment by meangczac** [comment]
````
<div class='clearfix'></div>
<div class='floatfix'></div>
````
All can clear floats so they don't intersect. you can try it out.
