### ISSUE TITLE
Gallery design issue

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1520]
![album_error_4](https://cloud.githubusercontent.com/assets/4210004/24334568/8690712e-126c-11e7-8886-205ffd39ab64.gif)
![album_error_1_1](https://cloud.githubusercontent.com/assets/4210004/24334567/868ffae6-126c-11e7-9089-5c5476afb6d2.gif)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38414&pid=201942#post_201925

**Comment by meangczac** [comment]
What theme is this? Nebula?

This is Nebula. The tpl were updated. 

![capture](https://cloud.githubusercontent.com/assets/4078041/24337455/e2f5325c-12cf-11e7-958c-d27cd7f83167.PNG)
