### ISSUE TITLE
error log loops

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1521]
> Upgrading from github, today March 25. The site is empty, but when I delete locale errors from the log, I get a message:
> There are too many queries this page. Please reduce it to below 30
> 

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38417&pid=201931#post_201931

**Comment by meangczac** [comment]
The loop is there. It's a design note for developers to know how much load your server is putting up with. It is not an error or an issue. There is no bug to catch here, it is simply a counting of executed dbquery.
