### ISSUE TITLE
Error in connection with mysqli_fetch_assoc()

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1523]
I have reconstructed my testsite and reinstalled Fusion here - now with MySQLi ... not PDO. And now I get an error in MySQLi.inc.
Errorlog says: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given
Error occur on line 103 in connection with:
 infusions/forum/index.php?section=tracked
LATER: Tried to add a photoalbum just now. Wasn't possible ... got a new error this time in infusions/gallery/gallery_admin.php - and album wasn't created:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''24'' at line 9 @ SELECT album.album_id, album.album_title, album.album_image, album.album_thumb2, album.album_thumb1, album.album_order, album.album_user as user_id, u.user_name, u.user_status, u.user_avatar, count(photo.photo_id) as photo_count FROM fusion7678Z_photo_albums album LEFT JOIN fusion7678Z_photos photo on photo.album_id=album.album_id INNER JOIN fusion7678Z_users u on u.user_id=album.album_user WHERE album_language='Danish' AND 1 = 1 GROUP BY album.album_id ORDER BY album.album_order ASC, album.album_datestamp DESC LIMIT 0, '24'
LATEST: I went in into the config.php and changed $pdo_enabled from 0 to 1 ... and strange, strange ... the album was there!!

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38412&pid=201923#post_201923

**Comment by meangczac** [comment]
No answer on this.
