### ISSUE TITLE
Theme error for rating box?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1524]
> Rating news ... rating function is moved to the right of the screen under news.
![rating_error](https://cloud.githubusercontent.com/assets/4210004/24334608/74b2e350-126d-11e7-994d-456547b0b644.gif)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38415&pid=201926#post_201926

**Comment by meangczac** [comment]
Answered, no bug.
