### ISSUE TITLE
Forum Vote

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1525]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/infusions/forum/postify.php?post=votedown&forum_id=2&thread_id=1&post_id=3
Line: 71

Query Error: DELETE FROM pf9_forum_votes WHERE rep_id=:vote_id
Stack Trace: 
#0 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(63): PDO->prepare('DELETE FROM pf9...') 
#1 F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('DELETE FROM pf9...', Array) 
#2 F:\xampp\htdocs\PHP-Fusion\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('DELETE FROM pf9...', Array) 
#3 F:\xampp\htdocs\PHP-Fusion\infusions\forum\classes\postify\vote.php(110): dbquery('DELETE FROM pf9...', Array) 
#4 F:\xampp\htdocs\PHP-Fusion\infusions\forum\classes\postify.php(139): PHPFusion\Forums\Postify\Postify_Vote->execute() 
#5 F:\xampp\htdocs\PHP-Fusion\infusions\forum\postify.php(25): PHPFusion\Forums\Postify\Forum_Postify->do_postify() 
#6 {main}
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rep_id' in 'where clause'

**Comment by meangczac** [comment]
Ok, I have the same uncommitted change. Dropped mine.
