### ISSUE TITLE
Missing index in Comments.ajax.php

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1526]
> Line 71 $ajax_respond = \defender::unserialize($_POST['comment_options']);
> Undefined index: comment_options
> ... and in the same context, line 73:
> Undefined index: comment_key
> 

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38420&pid=201952#post_201952

**Comment by meangczac** [comment]
No more implementation of comments.ajax.php
