### ISSUE TITLE
Image upload - very strange behavior

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1528]
>  have had some problems uploading images ... album thumb and in images in general.
> I have just made a fresh install on my localhost, and this is what I experience:
> 
> 1. Modifying an image - changing size: Upload is rejected with an error message, that image type is not correct
> 2. Trying to upload exactly the same image - but without any modifications - worked OK.
> 
> I'm using Corel PaintShop Pro version X9 to modify the images. 
> 
> I tried to attach the images here ... but without any luck. Images were rejected. So here is links to the images:
> 

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38425&pid=201979#post_201973

**Comment by meangczac** [comment]
I'm using Corel PaintShop Pro version X9 to modify the images.

Try use photoshop or resave the image in Windows Paint.

Anyway, I need to have a valid image to test.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/issues/1518 closed. Use this one.

**Comment by JoakimFalk** [comment]
I link to them images, 
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38425&pid=202006#post_202006

**Comment by meangczac** [comment]
![image1](https://cloud.githubusercontent.com/assets/4078041/24531615/cfc13184-15ec-11e7-990b-da2af5c1c9b4.gif)

**Comment by meangczac** [comment]
Can upload.

**Comment by meangczac** [comment]
![jan_m](https://cloud.githubusercontent.com/assets/4078041/24531885/d8f9daf6-15ee-11e7-92ec-661d26a04fe1.jpg)
