### ISSUE TITLE
Messages - Undefined index: items

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1530]
> Line 753 Undefined index: items

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38426&pid=201978#post_201978

**Comment by meangczac** [comment]
Closing this. I can't get any error fiddling on /final9

**Comment by RobiNN1** [comment]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\PrivateMessages.inc
/messages.php?folder=inbox&msg_read=2 **
Line: 748
Undefined index: items

F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\PrivateMessages.inc
/messages.php?folder=inbox&msg_read=2 **
Line: 749
Undefined index: items

**Comment by RobiNN1** [comment]
solved
