### ISSUE TITLE
form_fileinput.php - Undefined index: df_304

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1531]
form_fileinput.php
/site/administration/theme.php?aid=486ee1c8d01b7276
Line: 253

Severity : Run-time notices
Undefined index: df_304

**Comment by meangczac** [comment]
No this should not be valid issue. Your locale is either an old locale file or old plugin file. Regardless, I will change some codes and it will be solved.

````fusion_get_locale```` is **global** based, and by default loads both global.php and df_ defender's file, and will only load all other subsequent files **if specified** under the 2nd parameter.
