### ISSUE TITLE
form_datepicker.php - Undefined index: datepicker_js

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1532]
form_datepicker.php
/site/infusions/articles/articles_admin.php?aid=486ee1c8d01b7276&section=article&ref=article_form&action=edit&article_id=3
Line: 101

Severity : Run-time notices
Undefined index: datepicker_js

**Comment by karrak1** [comment]
add locale/global.php
$locale['datepicker_js'] = "YYYY-M-DD, H:mm:ss";
