### ISSUE TITLE
Database Backup dosent work

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1534]
when i klick the button i would redirect to a new white site

**Comment by meangczac** [comment]
Too many tables in one backup.

**Comment by meangczac** [comment]
Try 1 table. It will backup properly. Server max limit time to execute compile is too short and table is too big. Try back up in PhpMyAdmin.... for now.

**Comment by UnrealCatze** [comment]
Lol sorry then that is totally pointless. Who already secures 1 table individually. Here should be revised

**Comment by meangczac** [comment]
Revise your server configuration. Max Limit is too low then redirect to white page.

**Comment by UnrealCatze** [comment]
I can not .. is a hoster. I can not change these settings. I secure my DB via phpmyadmin .. this is wonderful without problems. Until recently, but also went in PHPF. Did you change something? My DB is not very large

2200 kb compressed

**Comment by meangczac** [comment]
Ok, i'll try to see what I can do, but no guarantee

**Comment by meangczac** [comment]
The main a2 server could serve the backup nicely on full scale table. As I've said, it depends on hosting server. The codes are standard v7

**Comment by meangczac** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/24505587/f74acf22-158c-11e7-8af1-35fc25d8782e.PNG)
