### ISSUE TITLE
login.php - Undefined index: UM067/Undefined index: global_109

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1535]
login.php
/site/login.php?error=1&redirect=%2Fsite%2Fhome.php
Line: 93
Severity : Run-time notices
Undefined index: UM067

login.php
/site/login.php?error=1&redirect=%2Fsite%2Fhome.php
Line: 95
Severity : Run-time notices
Undefined index: global_109

**Comment by meangczac** [comment]
Update your English Locale file. Change to English language only.
