### ISSUE TITLE
 includes/defender/token.php - Undefined index:......

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1538]
Undefined index: comments_reply_frm-10
File -- includes/defender/token.php

Undefined index: comments_reply_frm-5
File -- includes/defender/token.php

**Comment by RobiNN1** [comment]
F:\xampp\htdocs\PHP-Fusion\includes\defender\token.php
/includes/classes/PHPFusion/Feedback/Comments.ajax.php?action=edit
Line: 75
Undefined index: form_id

 Ajax Off, only members
After editing comments will create a new
![screen](https://cloud.githubusercontent.com/assets/11664877/24563565/16b40582-164f-11e7-94d0-87af952bee3a.png)

**Comment by meangczac** [comment]
Ok, this issue can close.

**Comment by RobiNN1** [comment]
Not solved
![screen](https://cloud.githubusercontent.com/assets/11664877/24714214/280ce43e-1a28-11e7-8030-810570c0c11f.png)

**Comment by meangczac** [comment]
What remains in error? Can I get the error log? (Full stack copy and paste please)
Jquery mode should be off. It will not be on until later release.

**Comment by RobiNN1** [comment]
errol log is empty

**Comment by meangczac** [comment]
haha. Can you describe ?

**Comment by meangczac** [comment]
When you click edit... 
Form pops up..
Edit message..
Post ... 
And what happens?

**Comment by RobiNN1** [comment]
I wrote a comment after I posted. I later edited it when I clicked on send, created new comment

**Comment by meangczac** [comment]
ok

**Comment by meangczac** [comment]
Should be ok. I tested without error now. The only error I had was Jock's issue. (Update Comment Text Field Name error) and has been fixed.
