### ISSUE TITLE
Get bug when try to edit member (user)

### ISSUE THREAD

**Issue by omikron20** [PHPFusion/PHPFusion#1540]
Array to string conversion 
in file -- dynamics/includes/form_datepicker.php
on page -- /administration/members.php?aid=8b1154c8eb9f281c&ref=edit&lookup=1171

184	            }
185	            addNotice("danger", "<strong>$title</strong> - ".$options['error_text']);
186	        }
187	    }
188	
189	    $input_id = $options['input_id'] ?: $default_options['input_id'];
190	    $html = "<div id='$input_id-field' class='form-group ".$error_class.$options['class']."'>\n";
191	    $html .= ($label) ? "<label class='control-label".($options['inline'] ? " col-xs-12 col-sm-3 col-md-3 col-lg-3 p-l-0" : '')."'
        for='$input_id'>".$label.($options['required'] ? "<span class='required'>&nbsp;*</span> " : '').($options['tip'] ? "<i class='pointer fa
        fa-question-circle' title='".$options['tip']."'></i>" : '')."</label>\n" : '';
192	    $html .= $options['inline'] ? "<div class='col-xs-12 col-sm-9 col-md-9 col-lg-9'>\n" : "";
193	    $html .= "<div class='input-group date' ".($options['width'] && !$label ? "style='width: ".$options['width']."'" : '').">\n";
194	    $html .= "<input type='text' name='".$input_name."' id='".$input_id."' value='".$input_value."' class='form-control textbox'
        style='width:".($options['inner_width'] ? $options['inner_width'] : $default_options['inner_width']).";'".($options['placeholder'] ? "
        placeholder='".$options['placeholder']."'" : '')."/>\n";

**Comment by meangczac** [comment]
Can I get the full stack error report. No need to reference code. I can't see where Array to string conversion is used in members.php file.

**Comment by karrak1** [comment]
the error did not occur to me

**Comment by omikron20** [comment]
Hi, How can I give You full stack this bug ? Maby it;s problem with my database, because is upgraded from php 7.02.07. 

This bug shows me when I click on members - (next klick on) some user- (end next) edit. Them I get this bug.

**Comment by omikron20** [comment]
P.S. I install PF9 2 weeks ago and I don't upgrade files to latest files from github.

**Comment by meangczac** [comment]
The fix for this thread: 

It is related to a couple of files - 1 error chaining another error. Reverse tracked each and debugged.

https://github.com/php-fusion/PHP-Fusion/commit/2c04f2d2104371e73678be4cbd1332f325782555

In order to fix this for your server @omikron20 , you need to "recreate - i.e. delete & add back" this field if it is made from UF Quantum Fields Engine. or check the column manually in your phpmyadmin - change the TINYINT(10) to INT(10) for that datepicker column, and select unsigned from dropdown list on attributes.

**Comment by omikron20** [comment]
Thanks for this. I don't know how to do it.  But I try make new user, and when I try edit this new user from my admin acount, this bug dont shows me. It shows only when I try Edit upgraded users from PHP-F 7. 
Maby can you explain me step by step how to fix this problem ?
