### ISSUE TITLE
RSS Don't Support HTML

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1544]
RSS is with the new core files wrong. Now i see only code

![unbenannt](https://cloud.githubusercontent.com/assets/22166864/24540757/e70d8e7a-15f4-11e7-97ca-44116581ad05.jpg)

**Comment by meangczac** [comment]
Show us any infusion RSS that is within scope. 

http://simplepie.org/demo/?feed=http%3A%2F%2Fnext.php-fusion.co.uk%2Ffinal9%2Finfusions%2Frss_feeds_panel%2Ffeeds%2Frss_articles.php

http://simplepie.org/demo/?feed=http%3A%2F%2Fnext.php-fusion.co.uk%2Ffinal9%2Finfusions%2Frss_feeds_panel%2Ffeeds%2Frss_forums.php

http://simplepie.org/demo/?feed=http%3A%2F%2Fnext.php-fusion.co.uk%2Ffinal9%2Finfusions%2Frss_feeds_panel%2Ffeeds%2Frss_news.php

Where got text. It parses nicely.

**Comment by UnrealCatze** [comment]
lol i have no modification ... all included in php fusion and look ... my rss is wrong .. why?
http://aliencollectors.com/site/infusions/rss_feeds_panel/feeds/rss_articles.php

**Comment by meangczac** [comment]
Paste me your Article here. Check your html again.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/84959bd3cf4bd5791a46eda2fc99fbd8b350023c

**Comment by UnrealCatze** [comment]
no ... now i see none rss ... all empty 
http://aliencollectors.com/site/infusions/rss_feeds_panel/feeds/rss_articles.php

but i have articles!!! 
i have restore the old rss file again .. so i have articles anymore but with this specialcharacter problem again :(

and this problem is on all feeds not only in articles!!!

**Comment by helmuthm** [comment]
on janmols test production site the problem still exists:

![2017-04-03_09-53-02](https://cloud.githubusercontent.com/assets/9512774/24600202/c94a77a2-1853-11e7-9401-91ec11611136.png)

**Comment by RobiNN1** [comment]
Reupload RSS Feeds Panel

**Comment by JoakimFalk** [comment]
Confirmed fixed, 
![image](https://cloud.githubusercontent.com/assets/4210004/24638436/b5ac24f8-18e8-11e7-8b6a-d1c913a40021.png)

![image](https://cloud.githubusercontent.com/assets/4210004/24638472/f9b3b080-18e8-11e7-8baf-7c5e6d92289b.png)
