### ISSUE TITLE
News readmore (extended) broken since some recent patch

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1545]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38434&pid=202030#post_202030

**Comment by RobiNN1** [comment]
#1542

**Comment by ovasclub** [comment]
Have you checked?!! All the same!!! The problem is not solved!!!

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/f242d51da8becae904fcfd87ad897c62b5be2533

**Comment by meangczac** [comment]
If fix , close issue. Thanks.
