### ISSUE TITLE
Gray line in the boxes

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#155]
There is a gray line to the right of all photos including albums in the thumb boxes.
![grayline](https://cloud.githubusercontent.com/assets/4210004/9491673/1d918322-4bf1-11e5-970d-43883067dba4.png)

**Comment by meangczac** [comment]
Bigger thumbnail should fix that. But I'm going to try something now injecting a default no crop on width.

**Comment by JoakimFalk** [comment]
ah, we need it larger by default if that does not do the trick then.
I just tested and report what I find without giving it any thought or depth why it happens

**Comment by meangczac** [comment]
Np. It gonna be like this now. 

Previously:
echo <div class='col-xs-12 col-sm-2'>  meaning, 100% width on mobile, 2/12 width (i.e. 6 container of 2/12 width will make a row) on all desktop screens. So, the container width will grow accordingly when you stretch your browser. 

Now, I adjusted to like this.
echo "<div class='float:left; width: ".$gallery_settings['thumb_w']."'> and wrap the contents of the container. But how many per row will depend on the user's screen. Wider it is, more container it can be, but there will be no centerings of the containers positioning. 

Hence, there will be no gray borders.
