### ISSUE TITLE
Who's online - counter confusion

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1552]
> on my test site there are 2 users logged in: admin and helmuth (laptop and iPad)
> only one is shown at Users Online in the navigation panel
![2017-04-01_19-55-16](https://cloud.githubusercontent.com/assets/4210004/24583185/315f6612-1742-11e7-8374-26e27bf8b2aa.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38442&pid=202060#post_202060

**Comment by JoakimFalk** [comment]
Please note this is for names, we went thru the counter carefully but this is Users online name list.

**Comment by helmuthm** [comment]
on janmols test production site you can notice that when you login the login is not shown correctly at the left - after refreshing the page it shows OK


![2017-04-03_09-58-59](https://cloud.githubusercontent.com/assets/9512774/24600473/236f6d54-1855-11e7-8d3a-404d1dd2ee88.png)
![2017-04-03_10-04-18](https://cloud.githubusercontent.com/assets/9512774/24600474/2374aaf8-1855-11e7-84b3-7f149aad95d2.png)

**Comment by meangczac** [comment]
So is this issue still need fixing?

**Comment by helmuthm** [comment]
if it doesn't work correctly I think it should be fixed ;)

**Comment by JoakimFalk** [comment]
> after refreshing the page it shows OK

Is it not so even on 7?, The site renders panels before the online updates which happens in the footer.
Perhaps we could try to have in the header tho.

**Comment by meangczac** [comment]
I will handle this. Let me revise panel class a bit for this

**Comment by meangczac** [comment]
No need to handle panel class increment. The layout.php is down in the footer area. You need a refresh to kick mysql change.

Today's first and last git. I'm very tired from moving heavy stuff whole day.
