### ISSUE TITLE
Fatal error when viewing albums

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#156]
![albumviewcrash](https://cloud.githubusercontent.com/assets/4210004/9491723/7101ec54-4bf1-11e5-8ec9-61de48c20f3f.png)
includes/theme_functions_include.php getimagesize() [function.getimagesize]: Filename cannot be empty Line: 584

**Comment by meangczac** [comment]
Yep. happen when your image src is ... IMAGES."photos.php?photo_id=4" that's a php generated image file, and parsed a lot of gibberish nonsense. I removed it.
