### ISSUE TITLE
A few default panels refuses to get listed when enabled on all themes

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1564]
These are enabled, they have content they are on the right side, 
Forum Threads 
Latest Articles 
Blog Archive Panel 
Latest Downloads 

![image](https://cloud.githubusercontent.com/assets/4210004/24639007/20e188d6-18ed-11e7-9800-390ddd80f6ca.png)

This is what I see, 

![image](https://cloud.githubusercontent.com/assets/4210004/24639041/4f1b7afe-18ed-11e7-9193-4f318e3156f8.png)

**Comment by karrak1** [comment]
Fixed
