### ISSUE TITLE
New custom page missing all options

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1566]
No tab with options exists on this new page creation click
![image](https://cloud.githubusercontent.com/assets/4210004/24641771/b0e802ce-1902-11e7-96ee-71a3de50c862.png)

As can be seen in Edit Page
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/24641776/b6eac5ee-1902-11e7-9044-e64a52e920ef.jpg)

**Comment by meangczac** [comment]
For copyright purposes, I decided to clear out edit functions. I don't want people put up negative content. 
If they dont want the page, delete it.. or click No to install default page.

I hope we can leave this as is.

**Comment by JoakimFalk** [comment]
I am confused. 
Should not these options be available when creating a new page at all?
They are visual when you edit it.

We are talking about , Page Content + Visual Page Composer + Page Settings
It is simple missing when you click Add page and you must edit it after save to see these.

**Comment by meangczac** [comment]
I'll try a clean install later. My system somehow has the edit and composer settings available.

![got_settings](https://cloud.githubusercontent.com/assets/4078041/25085862/efbc70b8-2396-11e7-9ec0-7d24e573a448.PNG)

**Comment by JoakimFalk** [comment]
Again you talk about edit, I am asking about when you create a new page, should these options not be there?

See image 0 options on new page, 

![image](https://cloud.githubusercontent.com/assets/4210004/25090321/c93e9916-2382-11e7-98dd-15ebab4155ee.png)

**Comment by meangczac** [comment]
No you cannot, without ID, there is nothing to tie to.

You need to at least have a page Id created, and you can then edit and add widgets from there.

ASynchonous only possible if we immediately save and generate ID and refresh the form once you push the Create New Page with Jquery. I'm not going there. The debug will be hell.

Note: The only that creates sub tier based on an sync model is the news image upload on new news page form. You already have a few issues of missing options and this and that. With Page Widgets, and Grids, and Rows.. we're looking at a very bad shape if "Options" are in during new Page.
