### ISSUE TITLE
No overlay nor entering photo when clicking on front

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#157]
Click on any of these albums and you get an image in a new broswer window. 
It used to be so you enter the photo for either overlay , commenting, rating etc.
![albumviewcrash](https://cloud.githubusercontent.com/assets/4210004/9491766/d7136cc0-4bf1-11e5-8117-c55453ffe430.png)

**Comment by meangczac** [comment]
I took off the overlay, the overlay mask couldn't position well under responsive circumstances. I will add back edit and delete link.

**Comment by meangczac** [comment]
Done.
