### ISSUE TITLE
It looks like `mod_rewrite` is not enabled on your host. 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1570]
I must have reported on this 3+ times, if this "detector" does not work as it should in most standard environments we don´t need it. Let´s just place a general headsup notice if it is hard to get it solid?. 
Idk why we keep patching and it still report badly on mod_rewrite support in our own environments.
The early versions of it did work in our environment, the later versions never have.

![image](https://cloud.githubusercontent.com/assets/4210004/24685544/8aa7fd38-19ae-11e7-951d-d545df426bfd.png)

**Comment by RobiNN1** [comment]
On your server is disabled the function apache_get_module, therefore the detector is not working

**Comment by JoakimFalk** [comment]
Ok, fair enough.  But what is the point with it if we can´t get it to detect that and it still falls short in many environments? From my perspective, we might as well remove the whole thing if it breaks on such things.
So last chance before I drop it as a whole.  Any ideas to make it work better?

**The early versions of it did work in our environment, the later versions never have.**

**Comment by meangczac** [comment]
We need to know when to exit support when such error exist.  Some people might want that warning. Same as low PHP version. One of the things that I never had changed from Ankur's contributed base code because I think it is good to keep. This feature helped dev to filter out possibilities.

**The early versions of it did work in our environment, the later versions never have.**
This one, maybe because we had switched server recently?

**Comment by FrederickChan** [comment]
But for this: The early versions of it did work in our environment, the later versions never have.

I'll check if apache_get_module() works on the server.

**Comment by JoakimFalk** [comment]
What I mean here is that I think a simple static notification that tells people that mod_rewrite or it´s equivalent it is required for it to work now when it fails portions of the time anyway.

My guess is that we would have far more questions on why it reports badly than why it does not work since that part would be clear.

Could be due to server change, not sure.
