### ISSUE TITLE
Forum Driver is not translating main threads from Forum Index SEO

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1574]
It seems to be both  /index.php?viewforum&forum_id=3 and  /index.php?viewforum&forum_id=3&thread_id=4
not translated.

![image](https://cloud.githubusercontent.com/assets/4210004/24686521/d40d40d6-19b4-11e7-8614-f974facbac43.png)

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/94937b5078c18650a3581c7deef578e0c1ba7b24
https://github.com/php-fusion/PHP-Fusion/commit/0875680a76d2dcb879d046dba1d6bcdd95698d4d
