### ISSUE TITLE
Starting a new thread from within forum will crash forum, SEO

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1575]
Click in on forum and use buttons in Forum to test it, the Start a New Thread link from Menu works.

![image](https://cloud.githubusercontent.com/assets/4210004/24686621/55a94842-19b5-11e7-9511-48a3d13496e1.png)

**Comment by meangczac** [comment]
http://next.php-fusion.co.uk/final9/forum/1/Test-forum-1-Eng/create-new-thread

Works. But postify not work.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/94937b5078c18650a3581c7deef578e0c1ba7b24
https://github.com/php-fusion/PHP-Fusion/commit/0875680a76d2dcb879d046dba1d6bcdd95698d4d
