### ISSUE TITLE
Registration - always annoying

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1580]
some people tell me that shw have massive problems on register. Always write me people who have the same problem. Of many, I do not know ... so I do not have to wonder if I get no new user

newest response i got from a user:  "It didn't work on Chrome, it didn't work on Firefox... it finally worked on my smarthphone (with chrome)... I have no idea why."

It is constantly reported that despite the correct filling out of the form the button does not become active.

Whats the problem?
![unbenannt](https://cloud.githubusercontent.com/assets/22166864/24702177/effceb72-19fd-11e7-9f51-48f263f93ac7.JPG)

**Comment by RobiNN1** [comment]
Problem is caused by AdBlock Plus. After disable AdBlock works well.

**Comment by UnrealCatze** [comment]
User says he have no adblock and other tools
Can it be that the new Firefox blocks?

**Comment by RobiNN1** [comment]
Can you send me link to your site?

**Comment by UnrealCatze** [comment]
have send you a e-mal

**Comment by UnrealCatze** [comment]
here on my Computer it works ... but some Report me it dosent work ... this is very embarrassing for an admin

**Comment by RobiNN1** [comment]
Reupload https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/classes/PHPFusion/UserFields.inc
