### ISSUE TITLE
Error in articles - too many queries

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1582]
> Made a new article on testsite. Commented this article. Deleted 3 older comments. Added a rating ... and then I got this message:

There are too many queries this page. Please reduce it to below 30

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38458&pid=202140#post_202140

**Comment by meangczac** [comment]
Yes cron at footer kicked in.
