### ISSUE TITLE
Firefox cuts input text field content very short

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1586]
If you have a input box of 350 chars long, FF will limit to like 20 rest goes invisible. ( Generalized explanation )

**Comment by meangczac** [comment]
It's definitely more than 20.. fresh download firefox.

![morethan20](https://cloud.githubusercontent.com/assets/4078041/24845168/67d204d8-1de2-11e7-8c53-e0bc47dfccd8.PNG)

I tested on firefox on articles admin. If you have a specific page, let me try it.

**Comment by JoakimFalk** [comment]
https://github.com/php-fusion/PHP-Fusion/issues/1596
