### ISSUE TITLE
When trying to attach more files than allowed in forum I get an error-message saying "Service unavailable" 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1587]
> ... and by the way: Allowed number of attached files was 6, error when I tried to attach file number 6 - also in UK / localhost but without the system message: There was an error while processing your request Current upload files is more than the maximum limit. Please try again and attach less files. Both in DK and UK both on localhost and prodserver

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38459&pid=202141#post_202141

**Comment by meangczac** [comment]
Attach more files than allowed in forum. Testing now.
