### ISSUE TITLE
Multisite: navigation menu has no content + missing user info

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1589]
when you've installed using, let's say, Danish as language and then switch to English, then there is no content in the English left menu

furthermore the private menu (e.g.: Welcome: username) is not present in the English version

I have not tried to install using English as basic language and Danish as the second - maby I will later

![install-uk-after-login-menu-userinfo](https://cloud.githubusercontent.com/assets/9512774/24827937/84c3461e-1c53-11e7-83dd-01b84c2dc383.png)
![install-dk-after-login-menu-userinfo](https://cloud.githubusercontent.com/assets/9512774/24827938/84c96a8a-1c53-11e7-9275-b56046fb960b.png)

**Comment by karrak1** [comment]
corrected

**Comment by helmuthm** [comment]
works like a charm :)
