### ISSUE TITLE
Remove autosize: Edit Blog, Articles, News, Faqs

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1591]
if you have a blog with a normal amount of text, you have to scroll up and down while editing the block if you want to set text attributes etc.

the same goes for adding a new blog

**must be the same as under custom pages**

problem is the same with Articles, News, Faqs,

**Remove autosize**

**Comment by meangczac** [comment]
A simple css trick will solve your problem.
See my git. Test your platform and cache is off. 

Read this for how: https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38469
