### ISSUE TITLE
I have multiple MySQLi errors in the forums

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1592]
> SQLi.inc
> /infusions/forum/viewthread.php?thread_id=520
> Line: 187
> 27 minutes ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=29
> Line: 187
> 4 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=35
> Line: 187
> 4 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=216
> Line: 187
> 5 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=269
> Line: 187
> 5 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=285
> Line: 187
> 6 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=32
> Line: 187
> 7 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=30
> Line: 187
> 11 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=34
> Line: 187
> 11 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=31
> Line: 187
> 15 hours ago	New Solved Ignored Delete
> MySQLi.inc
> /infusions/forum/viewthread.php?thread_id=205
> Line: 187
> 19 hours ago

https://www.php-fusion.co.uk/forum/viewthread.php?forum_id=160&thread_id=38466#post_202173

**Comment by meangczac** [comment]
Incomplete stack trace.

I am guessing the forum check access. If that is the case, then it's solved earlier.
