### ISSUE TITLE
language mix - edit_profile.php

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1595]
installed using English as base language, Danish as second option

this gives both Danish and Engllish when you edit your profile and if you choose Danish language 

![2017-04-09_13-17-55](https://cloud.githubusercontent.com/assets/9512774/24836871/b5ca1722-1d27-11e7-9e1b-7c5aed156417.png)

**Comment by helmuthm** [comment]
same problem on Admin / user_fields.php

**Comment by helmuthm** [comment]
same on Admin / panels.php

**Comment by helmuthm** [comment]
same on Admin / Infusions

**Comment by helmuthm** [comment]
the problem is also present here: https://github.com/php-fusion/PHP-Fusion/issues/1597

**Comment by JoakimFalk** [comment]
I think it is connected to installer,

> installed using English as base language, Danish as second option

Both ( All Selected ) languages are not inserted to user fields, panels correctly.

The Infusions mentioned above should not be related to user_fields and panels so it is 2 differant issues.

**Comment by helmuthm** [comment]
you're ptobably right ... what I meant with 'same' was that English is inserted on a Danish site ...

**Comment by meangczac** [comment]
I will only increment User Field Category because these English values are found, and I can translate reversing on a identified lookup. Further update on this can be streamlined at a much later date.

**Comment by dtechniker** [comment]
oh no. Is there a solution for the problem by now? And can i chance the Datepicker in German format? d-m-J

**Comment by meangczac** [comment]
ok, i'll address this.

**Comment by dtechniker** [comment]
thanks.

**Comment by RobiNN1** [comment]
You must add manually
![screen](https://user-images.githubusercontent.com/11664877/49338941-db693f80-f629-11e8-9be1-166afc694cb3.png)
