### ISSUE TITLE
language mix - Admin Forums

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1597]
installed with English as base and Danish as second language

![2017-04-09_13-50-43](https://cloud.githubusercontent.com/assets/9512774/24837060/c15d17b6-1d2b-11e7-9592-92f7b745f8ec.png)

**Comment by karrak1** [comment]
infusions/forum/locale/language/forum_tags.php
translate
$locale['forum_tag_0110']

**Comment by helmuthm** [comment]
the problem is not a missing translation, the problem is that English is loaded instead of Danish
