### ISSUE TITLE
class.smtp.php and contact.php What could be the reason for this error?

### ISSUE THREAD

**Issue by ALTUN69** [PHPFusion/PHPFusion#1598]
![2017-04-09](https://cloud.githubusercontent.com/assets/8268248/24837083/75ea1396-1d2c-11e7-9b2e-6aec05a7c5eb.png)

**Comment by meangczac** [comment]
Get a proper hosting ssl certificate. Not some hosting-provided-fast-register-cheap-name solution.

This one: https://www.websecurity.symantec.com/

**Comment by JoakimFalk** [comment]
Maybe can be related to https://github.com/php-fusion/PHP-Fusion/issues/1463 ?

**Comment by meangczac** [comment]
This is when your SMTP class uses HTTPS protocol without a properly configured server configuration.

**Comment by ALTUN69** [comment]
I solved the problem. I've reconfigured SSL settings from CPanel.
