### ISSUE TITLE
Forum - Line: 71 File -- Database/Driver/PDOMySQL.inc

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1602]
i get this again and again

Line: 71 File -- Database/Driver/PDOMySQL.inc
On Page -- infusions/forum/viewthread.php?thread_id=6&section=oldest 

Query Error: SELECT forum_access FROM fusion12345_forums WHERE forum_id IN () ORDER BY forum_cat ASC
Stack Trace: #0 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('SELECT forum_ac...') #1 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT forum_ac...', Array) #2 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT forum_ac...', Array) #3 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/classes/server.php(174): dbquery('SELECT forum_ac...') #4 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/classes/threads/threads.php(297): PHPFusion\Forums\ForumServer->check_forum_access(Array, 0, '6') #5 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/classes/server.php(482): PHPFusion\Forums\Threads\ForumThreads->set_threadInfo() #6 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/classes/threads/view.php(30): PHPFusion\Forums\ForumServer::thread() #7 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/viewthread.php(29): PHPFusion\Forums\Threads\ViewThread->display_thread() #8 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY forum_cat ASC' at line 1

**Comment by meangczac** [comment]
do you have seo turned on or not

**Comment by UnrealCatze** [comment]
you meaning this? --> Create OpenGraph meta tags for Social networks
it stand by me as yes

**Comment by JoakimFalk** [comment]
It is non SEO, visit Admin > Infusions and see if any updates are available on the Infusion.

**Comment by UnrealCatze** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/22166864/24856280/6d305982-1de4-11e7-8e7c-67a815768953.JPG)

**Comment by meangczac** [comment]
Before I fix this time. Please give me a SQL backup of your DB_FORUMS "i.e. __prefix__forums" table. I want to replicate your situation in my system. See if you can attach .zip file here.

**Comment by UnrealCatze** [comment]
i have send it over php fusion uk site message system

**Comment by meangczac** [comment]
OK thank you.

**Comment by meangczac** [comment]
I cannot edit PM mode, View Source mode has  br tags and plain view has Image.
![zip_needed](https://cloud.githubusercontent.com/assets/4078041/24898932/1669b088-1ed1-11e7-871c-95ec0264f8f1.PNG)

Can you **zip** it up here.... like this.
[Zip_needed.zip](https://github.com/php-fusion/PHP-Fusion/files/912515/Zip_needed.zip)

**Comment by UnrealCatze** [comment]
i will send you a link to the zipped file over PM system from UK site

**Comment by meangczac** [comment]
ok...

**Comment by meangczac** [comment]
Latest forum update I'm not getting anymore. If persist just tell. Closing for now.

**Comment by UnrealCatze** [comment]
same again today
![unbenannt](https://cloud.githubusercontent.com/assets/22166864/25042859/b55a81a8-211b-11e7-8309-15c75c860314.JPG)

**Comment by UnrealCatze** [comment]
again and again every day
![grafik](https://cloud.githubusercontent.com/assets/22166864/25312753/3c58e990-2821-11e7-833b-ecba9b15988a.png)
