### ISSUE TITLE
Install step 1: weird text addition (Danish)

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1603]
when switching to Danish during install some weird text additions are added: Trin 1 - 7 (number 4 is missing, why?) and the version number is changed: 9.09,02

this has actually been so in all installations I've done with v.9 ...

Some Trin 1 - 7 was earlier found in the locale files and deleted...

from where do they come and why is the version number altered ?

![install-step1-dk](https://cloud.githubusercontent.com/assets/9512774/24877981/83c5769e-1e31-11e7-9304-09b18eec700e.png)

**Comment by meangczac** [comment]
Danish setup locale file need to be re translated

**Comment by JoakimFalk** [comment]
9.09.02 should just not be possible, are you running somewhat own pack somewhere?
Even our 9.02 is kinda off, if we are to be correct it would be 9.04 as a minimum and 9.05 as dev in progress.

**Comment by helmuthm** [comment]
I looked through and compared both Danish and English setup.php ... there was some differences ... hope this solves the problem ;)

**Comment by helmuthm** [comment]
changes didn't cure the 9.09,02 problem ...

@Domi-php : I sync both https://github.com/php-fusion/PHP-Fusion-9-Locale and https://github.com/php-fusion/PHP-Fusion from github through GitHub Desktop, then copy all files&folders from my locale github version into my localhost htdocs/(subfolder) - here I run the setup ...

**Comment by helmuthm** [comment]
found it:
from
$locale['setup_0010'] = "9.0 ";
to
$locale['setup_0010'] = "Nuværende Build Version - ";
