### ISSUE TITLE
Infinite redirect loop forum on removed / non existing forum ID - SEO

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1604]
Try enter an SEO url that does not exist, for example : http://next.php-fusion.co.uk/final9/forum/browse/278/Test-Forum-for-test-forum-attach
And you get, and a site crash naturally.
> /forum/browse/278/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/index.php

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/94937b5078c18650a3581c7deef578e0c1ba7b24
https://github.com/php-fusion/PHP-Fusion/commit/0875680a76d2dcb879d046dba1d6bcdd95698d4d
