### ISSUE TITLE
undefined index twice in widgets\ratings\ratings_widget.php

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1606]
it's a fresh/new install with no added content - looked in the error log first time after login to admin page

occurs on this page: viewpage.php?page_id=1

![2017-04-12_17-00-25](https://cloud.githubusercontent.com/assets/9512774/24964657/28f61b2a-1fa2-11e7-97e3-6603f5538d69.png)
![2017-04-12_17-02-08](https://cloud.githubusercontent.com/assets/9512774/24964658/28fac774-1fa2-11e7-85dd-0079cf4b9978.png)

**Comment by helmuthm** [comment]
site has two languages: Danish + English

**Comment by Der-WU** [comment]
There are more Language Files to be translated.  Take a look into /Widget/ Directory and every sub Directory. 

Gratz

**Comment by helmuthm** [comment]
it was a mispelling in the danish folder structure: rarings :(
