### ISSUE TITLE
Setup Locale doubled

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1607]
I Check the locale Setup file for not needed etrys.
By the way i found entrys doubled

	Line 170: $locale['setup_1600'] = "Installing ";
	Line 171: $locale['setup_1601'] = "Updating table structure on ";
	Line 172: $locale['setup_1602'] = "Adding new column on ";
	Line 173: $locale['setup_1603'] = "Populating data ";

	Line 362: $locale['setup_1600'] = "Setup is Complete";
	Line 363: $locale['setup_1601'] = "PHP-Fusion 9.0 is now ready for use. Click Finish to rewrite your config_temp.php file to config.php<br/>";
	Line 364: $locale['setup_1602'] = "<strong>Note: After you enter your site you should delete the entire /install folder and chmod your config.php back to 0644 for security reasons.</strong>";
	Line 365: $locale['setup_1603'] = "Thank you for choosing PHP-Fusion.";

Witch are the right? :D

**Comment by meangczac** [comment]
The later one.
