### ISSUE TITLE
long lines in forum ...

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1608]
Some writers don't know KISS (Keep It Short Stupid) and they produce very long lines of unbroken letters

to prevent that the theme is screwed up there should be an automatic soft wrap function

below you can see:

1. this is where you type the text
2. here is the preview ... needs soft wrap
3. how it looks in forum ... here the 'editor function' has deleted the text that goes beyond the field borders - not a good solution

**1**
![2017-04-12_19-20-14](https://cloud.githubusercontent.com/assets/9512774/24970826/0e3f7376-1fb6-11e7-99d8-8ef398ef9db1.png)

**2**
![2017-04-12_19-20-59](https://cloud.githubusercontent.com/assets/9512774/24970827/0e41e5f2-1fb6-11e7-86f7-f70a5a73e08e.png)

**3**
![2017-04-12_19-22-37](https://cloud.githubusercontent.com/assets/9512774/24970828/0e49fb84-1fb6-11e7-849a-39d56f02b57f.png)

**Comment by helmuthm** [comment]
**4**
![2017-04-12_19-47-23](https://cloud.githubusercontent.com/assets/9512774/24971654/ffcc64b8-1fb8-11e7-92d3-6d26c2a43939.png)

**Comment by meangczac** [comment]
No biggie, just css needs tweak.

**Comment by helmuthm** [comment]
This is after I downloaded a new package this morning to my localhost ... sorry ...

![2017-04-14_08-14-00](https://cloud.githubusercontent.com/assets/9512774/25035465/2874b2ae-20ee-11e7-8aff-058a43c5c480.png)
![2017-04-14_08-23-55](https://cloud.githubusercontent.com/assets/9512774/25035466/287c96ea-20ee-11e7-80b3-53c2f96fb00a.png)
![2017-04-14_08-26-07](https://cloud.githubusercontent.com/assets/9512774/25035467/28809894-20ee-11e7-907e-cec74a11c707.png)
![2017-04-14_08-37-43](https://cloud.githubusercontent.com/assets/9512774/25035468/2882b156-20ee-11e7-8604-dadcf8f8ed21.png)

**Comment by meangczac** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/25038926/b9f4ee70-2133-11e7-9e2a-d32e0dc53514.PNG)

**Comment by meangczac** [comment]
**Please read : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38469&highlight=cache&pid=202194#post_202194**

**Comment by helmuthm** [comment]
I read it when you posted it originally - but it had no effect in my end - but I'll try again

**Comment by JoakimFalk** [comment]
The category view  is still very long with connected words, maybe have a lenght parser instead there.
![image](https://cloud.githubusercontent.com/assets/4210004/25044691/5235710c-2128-11e7-8d6d-e0691061dcc1.png)

**Comment by helmuthm** [comment]
after syncing from github and copying the files to the local web folder I can't see any changes to the problem
I think I'm going to make a totally new and fresh install in the weekend ...

**Comment by JoakimFalk** [comment]
You can try a CSS reloader to Chrome
