### ISSUE TITLE
Warning x 2 when adding to many files in forum

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1609]
double warning when number of attached files are to high in forum

![2017-04-12_19-54-21](https://cloud.githubusercontent.com/assets/9512774/24971971/10f49c14-1fba-11e7-8812-41320ac757ef.png)

**Comment by meangczac** [comment]
The first warning is by your server configuration. It has nothing to do with Fusion.

Check this tip to resolve your issue: http://stackoverflow.com/questions/4438551/maximum-number-of-allowable-file-uploads-has-been-exceeded
