### ISSUE TITLE
Attachments max count - not right

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1610]
number set to 10 but only allowed 9

![2017-04-12_20-06-07](https://cloud.githubusercontent.com/assets/9512774/24972453/be4bb7d4-1fbb-11e7-96b7-eadc54f05970.png)

![2017-04-12_20-04-16](https://cloud.githubusercontent.com/assets/9512774/24972452/be3c9592-1fbb-11e7-8dc4-4d16a6896d05.png)

**Comment by meangczac** [comment]
This one is updated/fixed earlier. Please resync to the repository copy.
