### ISSUE TITLE
stripping line breaks

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1612]
1. viewing an article looks okay
2. viewing articles overview line breaks are stripped in content
3. viewing Latest Articles line breaks are stripped in content

**1**
![2017-04-13_12-57-40](https://cloud.githubusercontent.com/assets/9512774/25002186/6a55550c-2049-11e7-9593-8643123be577.png)

**2**
![2017-04-13_12-59-04](https://cloud.githubusercontent.com/assets/9512774/25002187/6a587f70-2049-11e7-8de3-9bea24ba694a.png)

**3**
![2017-04-13_12-59-40](https://cloud.githubusercontent.com/assets/9512774/25002188/6a613336-2049-11e7-9334-041577710822.png)

**Comment by meangczac** [comment]
The container is designed to be as such so that the panel all looks identical height.
I've adjusted the home latest article.

**Comment by meangczac** [comment]
Nothing wrong with fusion_first_words() because those do not include whitespace or breaks in calculation..
