### ISSUE TITLE
mass upload photo not working

### ISSUE THREAD

**Issue by omikron20** [PHPFusion/PHPFusion#1613]
Can't upload mass photo. I get message "Number of files selected for upload (16) exceeds maximum allowed limit of 1."

But I don't see setting where I can change it.

![massupload](https://cloud.githubusercontent.com/assets/26767781/25010085/41162d2c-2069-11e7-8b88-58b22202c844.jpg)

**Comment by meangczac** [comment]
Don't need to change. It depends on  your php.ini ultimately, i'll just put 20 and I doubt most hosting environment allows you as much.
