### ISSUE TITLE
contact.php is not rendering any spam protection options in any theme

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1617]
![image](https://cloud.githubusercontent.com/assets/4210004/25035305/0ee94134-20ed-11e7-9713-e221718ae673.png)

and it seems to be broken in general, see the other issues on denied. Perhaps connected with missing captchas.

**Comment by meangczac** [comment]
No. The message was Sent. It was a locale error from what I know.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/4077944f15de9deb72e3c05f86e0802bf44bd73c

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/1f833e714b36d120c98bbefd9027dc77793e4b78
