### ISSUE TITLE
submit news still not working

### ISSUE THREAD

**Issue by omikron20** [PHPFusion/PHPFusion#1620]
After fix this issue #1619 I get next 3. And in news shows only short news introduction. Full text of news is always disappears. 

1.Undefined index: news_image_full_default
Line: 224 File -- admin/controllers/news_submissions.php

2.Undefined index: news_image_front_default
Line: 225 File -- admin/controllers/news_submissions.php

3.Undefined index: news_image_align
Line: 226 File -- admin/controllers/news_submissions.php

**Comment by meangczac** [comment]
Please close issue if fixed. Thanks.

**Comment by omikron20** [comment]
Is fixed. Thanks
