### ISSUE TITLE
What could be the cause of this error? "slider_admin.php and slider.php

### ISSUE THREAD

**Issue by ALTUN69** [PHPFusion/PHPFusion#1623]
![2017-04-15](https://cloud.githubusercontent.com/assets/8268248/25065678/d834f94e-2213-11e7-99ea-737368df676e.png)
![2017-04-15 1](https://cloud.githubusercontent.com/assets/8268248/25065675/d82c9cea-2213-11e7-8607-9555e21844dd.png)
![2017-04-15 2](https://cloud.githubusercontent.com/assets/8268248/25065676/d82ec0d8-2213-11e7-9edc-ca4a42a37ca9.png)
![2017-04-15 3](https://cloud.githubusercontent.com/assets/8268248/25065677/d831d61a-2213-11e7-998b-51028e00b56a.png)

**Comment by meangczac** [comment]
Thanks for posting issues like this, it is almost immediately fix and solve all language barriers 👍 
It is really a huge deal for us core devs to do our work. 

Find problem = 1 hour. Fix = 10 second.

**Comment by ALTUN69** [comment]
You are great at solving the problems.

**Comment by meangczac** [comment]
This fix is was provided by @RobiNN1  👍 He's also doing it like a champ.

**Comment by ALTUN69** [comment]
Thank you RobiNN1
