### ISSUE TITLE
How do I gain my initial points?, I have 0 even as Superadmin

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1646]
![image](https://cloud.githubusercontent.com/assets/4210004/25069404/f39314a2-227f-11e7-9a12-a9d45471f373.png)

**Comment by meangczac** [comment]
You need to answer question and get voted up.

**Comment by JoakimFalk** [comment]
But I can´t vote up with 0 points?

**Comment by helmuthm** [comment]
I ended up 'cheating' adding points via phpadmin ... but I think it's not a good solution that super admin does not have any means to initiate some points to users :(

**Comment by meangczac** [comment]
Yes, 'cheating' was the way to jump start yourself.

What is the options gonna be... discuss before I increment on the codes. How you want it to go down.. Please name all the options out. 👍 

I'm taking **feature request** as this could be the very last issue before we close the branch.

**Comment by JoakimFalk** [comment]
Ok , the Accept answer works, We just need a simple way for admin to give points I guess :)

**Comment by helmuthm** [comment]
some ideas:

1. populate Super with enough ordinary points from the start (during installation)
2. from edit profile give Super and maby Admins  the option to add extraordinary points - we could call them 'Super Points' - of course they are ordinary/normal points 
3. make it possible to 'take away' points already given to users as well

**Comment by helmuthm** [comment]
any solution here? ... I suppose a lot of users will flood the forum's with request regarding this problem ...
