### ISSUE TITLE
When you edit a news item you are missing the feature to add a intro image to it

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1647]
I can only manage the gallery but to attach and align a non existing intro news image option is just not there.

**Comment by meangczac** [comment]
First Upload, then on 2nd tab in gallery - If you can see this
![step_1_news](https://cloud.githubusercontent.com/assets/4078041/25110056/de90972e-2413-11e7-9041-c8dc2b265237.PNG)

Then this is available guaranteed.
![step_2_news](https://cloud.githubusercontent.com/assets/4078041/25110060/e2a7a406-2413-11e7-8167-5c21f5077faf.PNG)
