### ISSUE TITLE
A whole bunch of panels are not rendering, cross themes

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1648]
Enabled panels
![image](https://cloud.githubusercontent.com/assets/4210004/25069488/84576540-2282-11e7-843a-21ebffc9fe0a.png)

It stops at latest articles
![image](https://cloud.githubusercontent.com/assets/4210004/25069492/ab42796a-2282-11e7-8eff-b15836af6487.png)

**Comment by meangczac** [comment]
![is_got](https://cloud.githubusercontent.com/assets/4078041/25086149/884a2c0c-2398-11e7-9024-e047bc6e6b42.PNG)

All got, but members poll panel i think will only show if got content.

**Comment by JoakimFalk** [comment]
Check final9, something prevents em from displaying there, could be member poll panel

I move the polls to right and it all pops in, please see if you can notice a glitch there

![image](https://cloud.githubusercontent.com/assets/4210004/25135359/72d9b602-2452-11e7-8d5a-b0e60cedb45a.png)

**Comment by meangczac** [comment]
I could pop member poll panel in. However only when there is a poll started.

**Comment by JoakimFalk** [comment]
quite odd, I have same poll on in the first pic as in the last pic, it only showed when I moved the panel from left to right. But when I moved it back to left, it all worked. Makes me think some number is off.
It seems to be related with this one, his poll panel are not working on left side at all, https://github.com/php-fusion/PHP-Fusion/issues/1669

**Comment by JoakimFalk** [comment]
Making a new issue here, think I found the error..
