### ISSUE TITLE
Preview does not work on unpublished pages, lets just call it view, it is not a preview per say?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1649]
![image](https://cloud.githubusercontent.com/assets/4210004/25069525/d4ee5dd2-2283-11e7-8e48-abadc7a565ce.png)

**Comment by JoakimFalk** [comment]
Logic is preview should always work, view requires enabled page.

**Comment by meangczac** [comment]
Preview is a form of peeking. Well, anyhow change locale will fix this.
