### ISSUE TITLE
News intro image are displayed twice

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1653]
![image](https://cloud.githubusercontent.com/assets/4210004/25069664/21288a20-2288-11e7-9dda-dbd972c71660.png)

**Comment by meangczac** [comment]
Can't find problem. Can you reproduce steps?

**Comment by JoakimFalk** [comment]
The image(s) you see there on the picture are added twice via submit news. But it is an intro image. 

Now I see this is an ordinary problem with all news items, I change title.

Blog for example lists the intro image once and after selected align, as expected.
![image](https://cloud.githubusercontent.com/assets/4210004/25094527/d0d10302-2397-11e7-92a1-3576a5e501dc.png)

**Comment by meangczac** [comment]
Oh That One. It's image galleries collections. Ok. I'll add seperator.

Blog only have one image, but News have many images.. It can be a slideshow at the bottom or something like that. I just roughly put up as attachments.

**Comment by meangczac** [comment]
Like this, you need to upload a lot more photos to see it.

![news_gallery](https://cloud.githubusercontent.com/assets/4078041/25112129/d1b490e2-2421-11e7-94f8-7fa7469d062b.PNG)

**Comment by meangczac** [comment]
![grid](https://cloud.githubusercontent.com/assets/4078041/25112381/5c6eaf1e-2423-11e7-8587-350fd58b89c0.PNG)

Updated: https://github.com/php-fusion/PHP-Fusion/issues/1653
