### ISSUE TITLE
Find to day 3 bugs

### ISSUE THREAD

**Issue by omikron20** [PHPFusion/PHPFusion#1654]
It's generated probably from some user who must change your password from klicking forget password. And them he make update your profile.

1. Undefined index: /includes/dynamics/assets/preview/preview.ajax.php
Line: 75 File -- includes/defender/token.php
On Page -- assets/preview/preview.ajax.php

2. Undefined index: error
Line: 748 File -- classes/PHPFusion/UserFieldsInput.inc
On Page -- /edit_profile.php

3. Undefined index: image_name
Line: 749 File -- classes/PHPFusion/UserFieldsInput.inc
On Page -- /edit_profile.php

**Comment by FrederickChan** [comment]
Thank you. If fixed, please close.

**Comment by meangczac** [comment]
Should be fixed, but if still persist, feel free to reopen issue. Thanks.
