### ISSUE TITLE
[FORUM] There was an error while processing your request when cancel reply to theard

### ISSUE THREAD

**Issue by omikron20** [PHPFusion/PHPFusion#1655]
Don't get any bug. But when I click to cancel, in reply post window .Website was refreshed only, without cancel, and them shows this text "There was an error while processing your request"
![error_forum](https://cloud.githubusercontent.com/assets/26767781/25070425/1f81231a-229e-11e7-9f68-cb9c0123c432.jpg)

**Comment by JoakimFalk** [comment]
Confirmed in my test as well.
