### ISSUE TITLE
Can't quote on forum

### ISSUE THREAD

**Issue by omikron20** [PHPFusion/PHPFusion#1656]
When I click quote button my website give me this

`
Fatal error: Uncaught Error: Call to undefined function PHPFusion\Forums\Threads\strip_bbcodes() in /users/0008/gczechowski/www/astro-zone/infusions/forum/classes/threads/view.php:353 Stack trace: #0 /users/0008/gczechowski/www/astro-zone/infusions/forum/classes/threads/view.php(56): PHPFusion\Forums\Threads\ViewThread->render_reply_form() #1 /users/0008/gczechowski/www/astro-zone/infusions/forum/viewthread.php(29): PHPFusion\Forums\Threads\ViewThread->display_thread() #2 {main} thrown in /users/0008/gczechowski/www/astro-zone/infusions/forum/classes/threads/view.php on line 353
`

**Comment by JoakimFalk** [comment]
I just quoted posts in all 4 forum types with no issue, do you have the latest git?

**Comment by omikron20** [comment]
Yes. I have it from yesterday.

**Comment by JoakimFalk** [comment]
Please try a new sync, clear cache.  I just added bbcodes as well.

![image](https://cloud.githubusercontent.com/assets/4210004/25071299/d358f60a-22b3-11e7-836f-80a4bbf9fe73.png)

**Comment by omikron20** [comment]
Sorry not work. This same error

**Comment by omikron20** [comment]
When I change permission in forum seetings (this from attached sreen shot) quote its possible, without errors. So I don't know, close this issue or wait.
![forumperm](https://cloud.githubusercontent.com/assets/26767781/25092174/cad146f2-238c-11e7-99f2-71731df94d98.jpg)

**Comment by JoakimFalk** [comment]
Let´s see if we can replicate the issue first, What setting did you have before?
Also, can you replicate the issue if you switch back to previous setting?

**Comment by omikron20** [comment]
Ale settings was disable

**Comment by JoakimFalk** [comment]
I got the error now when removing Enable Quick Post. 
But when updating to latest Git from today the error poofed, please update your system with all the latest Git now and test.

**Comment by omikron20** [comment]
It's fixed. close issue
