### ISSUE TITLE
latest addition to English/global.php is not correct

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1658]
[](https://github.com/php-fusion/PHP-Fusion/commit/7deab106cceedbe4d34e9b638c735b17afef64e7)

2 lines are identical

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/fbe5d550a63702a1680d965f699693366ab0cc05

**Comment by helmuthm** [comment]
hadn't seen the correction ...
