### ISSUE TITLE
Missing Linebreak @ lost password

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1660]
![image](https://cloud.githubusercontent.com/assets/164333/25096740/d945b37a-23a1-11e7-9046-0f555512b9ae.png)

**Comment by meangczac** [comment]
Can assist in redesign this part @RobiNN1  ?

I'll look into some other stuff.

**Comment by Der-WU** [comment]
![image](https://cloud.githubusercontent.com/assets/164333/25139985/233e1f4a-245f-11e7-9250-f855ca088348.png)

not a nice solution.
i think the text should come first then the enterline over the button and use more widht.

Greatz

**Comment by Der-WU** [comment]
Sorry, my mistake.
It was cause missing locale.
Now all good. :)
