### ISSUE TITLE
Security settings: activation of php code missing

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1662]
it seems that the area where ytou activate / deactive execution of php code has disappeared ...

**Comment by meangczac** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/25109814/104838f0-2412-11e7-985b-369341c1b45b.PNG)

The code is in Github... https://github.com/php-fusion/PHP-Fusion/blob/9.02/administration/settings_security.php#L199-L201

**Comment by helmuthm** [comment]
code was present and correct - corrected by editing Danish/admin/settings.php
