### ISSUE TITLE
Fast edit, Ban, Moderation options in Forum

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1665]
This is what we have, 
![image](https://cloud.githubusercontent.com/assets/4210004/25114233/7270df06-23fd-11e7-94f8-38324c57464a.png)

A minimum set of options I think we need in that droplist for Admins with user rights is , 
Edit User, Ban User, Delete User. For must be easy to moderate and keep clean.

Today I use as you know mostly delete user upon spammer and place an IP ban, most efficent way to get rid of all crap they might have spread thru comments here and there as well. It looks like this for us atm.
![image](https://cloud.githubusercontent.com/assets/4210004/25114260/b2adcbce-23fd-11e7-8f12-5df2541d00fa.png)

**Comment by meangczac** [comment]
Can we leave this for later? first php is ok can do.. errors and Seo url and driver errors is pain and will set much delay. 

For main ok. Not in Github

**Comment by JoakimFalk** [comment]
yeah sure, I can mod for main too
