### ISSUE TITLE
multi language: switching languages 

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1667]
you are viewing  a category of links in Engllish

if you switch to Danish nothing happens

category is only in English not in Danish ... users might get confused and wonder why nothing happens

if you click on another link you will see that the language change has happened

**Comment by meangczac** [comment]
Is it Weblinks?

**Comment by helmuthm** [comment]
yes

**Comment by helmuthm** [comment]
problem is also the same in forum: if you are watching/reading a forum category/thread only existing in English and you (for whatever reason) wants to switch to Danish the page stays the same after a short screen update (you see the flickering). If you then click on, let's say, the Home link you'll discover that the language switch has been done already

![2017-04-20_07-01-13](https://cloud.githubusercontent.com/assets/9512774/25214404/4b26947c-2597-11e7-82d5-7a9d5dc726c5.png)

**Comment by JoakimFalk** [comment]
Confirmed,  it still does not behave as intended. Any switch on lang switcher should redirect site back to closest directory. Like forum index if you are in a thread. 
Any hotlink to content that exists should change lang on the fly temporarly for any given clicker.
