### ISSUE TITLE
Member Polls: can't vote

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1669]
member polls aren't working - no way to enter your vote

**Comment by JoakimFalk** [comment]
The panel need to be enabled, 
![image](https://cloud.githubusercontent.com/assets/4210004/25135298/410c062a-2452-11e7-90f4-60e3bee49e8a.png)

**Comment by helmuthm** [comment]
where do you enable the panel?

if it's under Panels it's already enabled

![2017-04-18_17-10-21](https://cloud.githubusercontent.com/assets/9512774/25138249/50e70236-245a-11e7-8d1d-f0bc7129dfb1.png)

**Comment by JoakimFalk** [comment]
yeah it is there, Members Poll, 
Try change side of it, from left to right. I think there is some glitch somewhere... once moved it can be moved back and all works. very odd.

![image](https://cloud.githubusercontent.com/assets/4210004/25140340/3b0d44c4-2460-11e7-83f9-f43f589b9e07.png)

**Comment by helmuthm** [comment]
tried to move to right side and was allowed to vote

moved it back to the left and logged in as a different (normal) user, but no possibility to vote

moved it back to the right and then I could vote

on you screen dump I can see a pencil (I suppose it's Edit), but I don't have the pencil ... and again, I have all the newest files from github ...

**Comment by JoakimFalk** [comment]
I can´t explain the pencil, but we sure have some trolls in that panel.

**Comment by JoakimFalk** [comment]
Oh, if you disable Fontawesome the pencil will poof ( along with other icons naturally ), but I figured you know... but it is the only explanation to it.

![image](https://cloud.githubusercontent.com/assets/4210004/25280234/83090a2e-26a9-11e7-83d3-ee7c0adc1b38.png)

**Comment by helmuthm** [comment]
none of my browsers do show the pencil - latest files from github and font-awesome disabled ...
