### ISSUE TITLE
submission button : no text

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1671]
weird behaviour in Submit Faq and Submit Web Link in Danish 

all other submissions show up correct

![2017-04-18_17-16-26](https://cloud.githubusercontent.com/assets/9512774/25138552/187ae510-245b-11e7-9800-962dfdf2efb3.png)
![2017-04-18_17-17-15](https://cloud.githubusercontent.com/assets/9512774/25138553/187fa5f0-245b-11e7-9318-79f01e9177bb.png)

**Comment by RobiNN1** [comment]
Missing locale https://github.com/php-fusion/PHP-Fusion/blob/9.02/locale/English/global.php#L461
