### ISSUE TITLE
Create poll brings errors and bugs on add option

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1674]
Okay, create poll now works on german locale.
It was an , in the datapicker Options that causes the big error.

Now Only 2 Things open.

1. Create a poll 
- Push on "Add Option" 
- New Option Field Comes but get Errors in log:
![image](https://cloud.githubusercontent.com/assets/164333/25240396/f45646fe-25f2-11e7-85d3-a49dc0746280.png)

2. Create a poll
- Fill Out all Fields
- Now Push "Add Option"
- The Fields lost the entrys and left only one Character and generates one more error on log
![image](https://cloud.githubusercontent.com/assets/164333/25240471/333261be-25f3-11e7-99c7-6b387cad709d.png)

**Comment by Domi-php** [comment]
Do you have the absolute latest Git ? , I can not replicate this issue with it.

**Comment by WuChEn** [comment]
I have upgrade to latest git and still same Problems and Errors.

**Comment by WuChEn** [comment]
Clean install only english works.
Aktivate German Locale as second locale works too.
Set German Locale as Default, add poll is broken.
So it is an locale Problem, but can´t find the Problem. 
All Locale from poll complete. -.-

**Comment by WuChEn** [comment]
![image](https://cloud.githubusercontent.com/assets/164333/25190725/6f386a26-252d-11e7-93b8-f47a23be32af.png)

**Comment by JoakimFalk** [comment]
Please try a new Git, just tested and got 0 errors.

**Comment by Der-WU** [comment]
It is the latest git

**Comment by Der-WU** [comment]
Okay, the Problem is  related to PHP7.

With PHP 5.6.30-0+deb8u1 no Errors.
With PHP 7.1.3 the Errors come.

So PHP-Fusion is not PHP7 ready. ;)

Greatz

**Comment by RobiNN1** [comment]
I have PHP 7.1.1 and I don't have any errors. All works perfectly.

**Comment by Der-WU** [comment]
PHP 7.1.1 no Errors
PHP 7.1.3 get Errors

**Comment by meangczac** [comment]
Give me your error log please.

**Comment by meangczac** [comment]
````
So PHP-Fusion is not PHP7 ready. ;)
````
![capture](https://cloud.githubusercontent.com/assets/4078041/25311192/ef7085e6-282c-11e7-9fe5-6bd38cbe3a7f.PNG)

So is Xampp 💃 , and PF's main server all running PHP 5.6.8

There is no environment to test now. If you have error log, please copy paste the errors, and we'll try to accomodate it.

**Comment by Der-WU** [comment]
See at the first Post screenshot, Thats are the Errors i get with 7.1.3

Greatz

**Comment by meangczac** [comment]
I helped increment the Interface. It is now more beautiful.

I've read through the lines of the codes, and it's OK.

So, for your problem at PHP 7.1.3 , I'm curious as to what is generating those errors, and your $_POST structure like. See this line here ----

https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/member_poll_panel/poll_classes.inc#L543

Uncomment That //

Upload to your server, and the form that you have problem with, click the "add Option". 

You will see a debug print. Paste them  here for me to see.

**Comment by meangczac** [comment]
This is my output, which is running perfectly.

````
Array
(
    [fusion_token] => 1.1492927900.4e3eb940aef5d99b1b12ad2263cbfdcd25318aa0455704089d14124bff8ab221
    [form_id] => addcat
    [poll_id] => 0
    [opt_count] => 2
    [poll_title] => Array
        (
            [English] => 
            [Malay] => 
            [Russian] => 
        )

    [poll_opt_0] => Array
        (
            [English] => 
            [Malay] => 
            [Russian] => 
        )

    [poll_opt_1] => Array
        (
            [English] => 
            [Malay] => 
            [Russian] => 
        )

    [poll_visibility] => 0
    [poll_started] => 4-23-2017 6:52:22
    [poll_ended] => 
    [addoption] => Add Option
)
````

Your problem is not having this -- or somewhat is defective.

````
    [poll_opt_XXXXXXXX] => Array
        (
            [English] => 
            [Malay] => 
            [Russian] => 
        )
````

Where "English" is not Present or is undefined offset created. 

Summary Instruction:
-----
1. Uncomment line 543 of poll_classes.inc, upload to server
2. Go to Add new Poll
3. Click Add Option
4. See Print On Top
5. Copy and Paste full printout here.

**Comment by Der-WU** [comment]
on edit i have seen that my poll_classes.inc is other then the Version on github.
so i first delete all and make 1 new checkout and try again.

**Comment by Der-WU** [comment]
Okay clean Installation:

Output is:
````
Array
(
    [fusion_token] => 1.1492934896.d9d04d3c054268a477f72fa3c6c2038b050e402a54556e340d2385af40e43599
    [form_id] => addcat
    [poll_id] => 0
    [opt_count] => 2
    [poll_title] => Array
        (
            [English] => 
        )

    [poll_opt_0] => Array
        (
            [English] => 
        )

    [poll_opt_1] => Array
        (
            [English] => 
        )

    [poll_visibility] => 0
    [poll_started] => 4-23-2017 8:09:58
    [poll_ended] => 
    [addoption] => Add Option
)
````
New entrys on error log after pushing on add Option are:

![image](https://cloud.githubusercontent.com/assets/164333/25311954/50b2f228-280d-11e7-8468-3a73915dd08e.png)

**Comment by meangczac** [comment]
It's a wild guess here. We may take a few times to figure things out because I have no PHP 7.1.3. Please be patient and try this fix. If still not fix, error log again please. If fix, please close issue.

**Comment by Der-WU** [comment]
Still the same Errors in the error log.
I don´t know it is an kompile error in php!?
So we wait if had anyone this Problem too.

**Comment by meangczac** [comment]
There must be something wrong on your end.

How card can be:

````
 $i = 0;
            while ($i < $_POST['opt_count']) {
                foreach ($_POST['poll_opt_'.$i] as $key => $value) {
                    $this->data['poll_opt'][$i][$key] = stripinput($value); // and you have error here
// $i have value
// $key have value
// but your $key is undefined offset???? Impossible.

                }
                $i++;
            }
````
