### ISSUE TITLE
Member Poll: start date wrong

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1682]
![2017-04-19_14-40-46](https://cloud.githubusercontent.com/assets/9512774/25180462/5db049be-250e-11e7-8afb-d46578529d77.png)

**Comment by bronxi** [comment]
Ended date shows also when poll not is ended. that must also be wrong

**Comment by helmuthm** [comment]
Started must say Votes

or

file must use $locale['POLL_060'] = "Votes:";
instead of $locale['POLL_048'] = "Started:";
