### ISSUE TITLE
User Geo Location: Danish values

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1685]
in Denmark you can do either **regions** or **kommuner** - I prefer _kommuner_ - btw. in Denmark we call Denmark for Danmark, which I have entered ;)

so if you choose regions

`$state['Danmark'] = construct_array("Hovedstaden,Nordjylland,Midtjylland,Sjælland,Syddanmark");`

if you choose kommuner

`$state['Danmark'] = construct_array("Albertslund,Allerød,Assens,Ballerup,Billund,Bornholms,Brøndby,Brønderslev,Dragør,Egedal,Esbjerg,Fanø,Favrskov,Faxe,Fredensborg,Fredericia,Frederiksberg,Frederikshavn,Frederikssund,Furesø,Faaborg-Midtfyn,Gentofte,Gladsaxe,Glostrup,Greve,Gribskov,Guldborgsund,Haderslev,Halsnæs,Hedensted,Helsingør,Herlev,Herning,Hillerød,Hjørring,Holbæk,Holstebro,Horsens,Hvidovre,Høje-Taastrup,Hørsholm,Ikast-Brande,Ishøj,Jammerbugt,Kalundborg,Kerteminde,Kolding,København,Køge,Langeland,Lejre,Lemvig,Lolland,Lyngby-Taarbæk,Læsø,Mariagerfjord,Middelfart,Morsø,Norddjurs,Nordfyn,Nyborg,Næstved,Odder,Odense,Odsherred,Randers,Rebild,Ringkøbing-Skjern,Ringsted,Roskilde,Rudersdal,Rødovre,Samsø,Silkeborg,Skanderborg,Skive,Slagelse,Solrød,Sorø,Stevns,Struer,Svendborg,Syddjurs,Sønderborg,Thisted,Tønder,Tårnby,Vallensbæk,Varde,Vejen,Vejle,Vesthimmerland,Viborg,Vordingborg,Ærø,Aabenraa,Aalborg,Aarhus");`

and I know I can't add/edit any files in the User Geo userfield DB ... that's why I post it here :)

**Comment by RobiNN1** [comment]
Please update https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/geomap/geomap.inc.php#L112

**Comment by helmuthm** [comment]
found it :-)
