### ISSUE TITLE
not localize bootstrap-datetimepicker.min.js

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1687]
tooltips not localized.

**Comment by RobiNN1** [comment]
Locales for datepicker are here https://github.com/php-fusion/PHP-Fusion/tree/9.02/includes/dynamics/assets/datepicker/locale

**Comment by karrak1** [comment]
bootstrap-datetimepicker.min.js
859 line
        tooltips: {
            today: "Go to today",
            clear: "Clear selection",
            close: "Close the picker",
            selectMonth: "Select Month",
            prevMonth: "Previous Month",
            nextMonth: "Next Month",
            selectYear: "Select Year",
            prevYear: "Previous Year",
            nextYear: "Next Year",
            selectDecade: "Select Decade",
            prevDecade: "Previous Decade",
            nextDecade: "Next Decade",
            prevCentury: "Previous Century",
            nextCentury: "Next Century",
            pickHour: "Pick Hour",
            incrementHour: "Increment Hour",
            decrementHour: "Decrement Hour",
            pickMinute: "Pick Minute",
            incrementMinute: "Increment Minute",
            decrementMinute: "Decrement Minute",
            pickSecond: "Pick Second",
            incrementSecond: "Increment Second",
            decrementSecond: "Decrement Second",
            togglePeriod: "Toggle Period",
            selectTime: "Select Time"
        },
datepicker title..
Such is not included in the file
