### ISSUE TITLE
Site introduction: Multi language error???

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1689]
You run a multi lingual site - in this example Danish and English. The initial setup language was Danish.

The content of **Site introduction:** is Danish ... looks a bit odd when you switch to English.

Do we need _Language Site introduction_ fields?

![2017-04-20_05-52-57](https://cloud.githubusercontent.com/assets/9512774/25212998/23a02d68-258e-11e7-8f2d-bd1415bbfc7b.png)

**Comment by JoakimFalk** [comment]
No but we sure need a Language BBCode [DANISH] Content [/DANISH] etc..

**Comment by helmuthm** [comment]
Could be a nice 'work araound'.

For this version or later?

**Comment by JoakimFalk** [comment]
I am not sure yet. Will see if we / I can solve it this version, I do think we need it for many scenarios.

**Comment by JoakimFalk** [comment]
Here is a start anyway, code need to be refined for sure. But it works.
Usage ,

[English]Welcome to your site[/English]
[Danish]Hej sidan[/Danish]

https://github.com/php-fusion/PHP-Fusion/commit/b0b71aa1ea599cefd8f786faa26fbb2f61abebb8
