### ISSUE TITLE
Menu link: Contact Me

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1690]
What if it's a company or an organisation or group, band, team ... ?

![2017-04-20_06-11-21](https://cloud.githubusercontent.com/assets/9512774/25213349/677d5978-2590-11e7-88dc-6c6b59821abe.png)

**Comment by JoakimFalk** [comment]
This have been fixed, should have been fixed anyway. I personally did such adjustment just a couple of days ago.

**Comment by helmuthm** [comment]
weird ...  I have used the latest updated files from github ...

**Comment by JoakimFalk** [comment]
should be $locale['setup_3305'] = "Contact"; in setup.php , if it is not that one... we have issues there too.

Is the other parts synced for you?

![image](https://cloud.githubusercontent.com/assets/4210004/25215465/02c5c99e-259e-11e7-916b-7649f0d93f23.png)

**Comment by helmuthm** [comment]
locale is OK ... I must have forgotten to edit the site link

I must remember: overwriting files doesn't alter content in the database ;-)
