### ISSUE TITLE
Forum: [hide] .... [/hide] doesn't work and signature missing during preview

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1692]
1. Starting a new thread or answer to a thread. Here signature is not visible during preview - is that intended?

2. using [hide] ... [/hide] is fun ... everyone can read ;) ... should only be visible for admins. Here user helmuthm is a plain user with no admin rights

1.
![2017-04-20_06-40-48](https://cloud.githubusercontent.com/assets/9512774/25214106/b88f885e-2595-11e7-811d-06e6c714d5e4.png)

2.
![2017-04-20_06-47-32](https://cloud.githubusercontent.com/assets/9512774/25214105/b887e1da-2595-11e7-9dc1-de341d5ebe13.png)

**Comment by JoakimFalk** [comment]
It is a BBCode, is it enabled? or maybe we have not ported it yet?

**Comment by RobiNN1** [comment]
In the textarea preview is not necessary to see the signature.
