### ISSUE TITLE
BB code Language not active in Signature

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1694]
https://github.com/php-fusion/PHP-Fusion/commit/b0b71aa1ea599cefd8f786faa26fbb2f61abebb8

**Comment by JoakimFalk** [comment]
Seems to work, GJ.

**Comment by helmuthm** [comment]
Yes, works now ... but I wonder why the content of the signature text is all in italics ... ?

And there's a little dash in front of the signature text too - why?

**Comment by JoakimFalk** [comment]
Dev´s preference, please make a new issue asking for "normalize" if you want. At least it can be discussed there.
