### ISSUE TITLE
Language Settings: remove linebreaks 

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1696]
![2017-04-21_09-54-05](https://cloud.githubusercontent.com/assets/9512774/25268380/d3831c00-2678-11e7-9725-71e0a4e0ca79.png)

**Comment by JoakimFalk** [comment]
Sync from 1h ago, I don´t  have em, FF, Chrome,  IE?

![image](https://cloud.githubusercontent.com/assets/4210004/25268556/76da99fa-2679-11e7-8a5f-e9aac1a83900.png)

**Comment by helmuthm** [comment]
Safari

**Comment by meangczac** [comment]
Ok.

**Comment by helmuthm** [comment]
same thing for Miscellaneous Settings in Safari

Chrome looks fine

**Comment by helmuthm** [comment]
Safari still wrong ... all other browsers are okay

**Comment by helmuthm** [comment]
Now I've checked all admin themes - only with the problem in Safari is Artemis

**Comment by meangczac** [comment]
This need "SAFARI" and Mac OSX. Last to do. I need to find missing power cable to my iMac.

**Comment by meangczac** [comment]
First, I install the best version safari available in PC. I can't find the power cord for my mac now.

![install_safari](https://cloud.githubusercontent.com/assets/4078041/25320213/b2346b4c-28d7-11e7-84c5-2fde427fe207.PNG)

Then, to my surprise the Safari does not render a lot of things correct EXCEPT the inline checkbox which is the subject matter in this issue.

![capture](https://cloud.githubusercontent.com/assets/4078041/25320238/da38af5e-28d7-11e7-9b2a-838f9664c445.PNG)

That's Safari for Windows.

I'll run Safari for OSX after I go buy a cable later today and debug the whole of Artemis on my Mac.

**Comment by JoakimFalk** [comment]
lol , look at the top and bread crumbs too :)
very odd behaviour, these things works in FF, Chrome and IE 11+

**Comment by RobiNN1** [comment]
In Safari v7.1 looks good
![screen](https://cloud.githubusercontent.com/assets/11664877/25349424/13a3b05a-2922-11e7-881d-5602ed495ebd.png)

**Comment by meangczac** [comment]
@RobiNN1 , thank you so much.

**Comment by helmuthm** [comment]
This is how it looks in Safari 10.1 with the newest updated files from github :(

![2017-04-26_11-59-00](https://cloud.githubusercontent.com/assets/9512774/25429027/e399db76-2a77-11e7-98a0-df69ce86158c.png)
