### ISSUE TITLE
Can't login after last github update

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1697]
10 minutes or so ago i synched and copied all the files to my localhost - now I can't login 

how can I reset the password for super administrator without being logged in?

**Comment by JoakimFalk** [comment]
lost password mail should work OR, start installer again and reset it ,

![image](https://cloud.githubusercontent.com/assets/4210004/25289292/436ef926-26c9-11e7-8b09-29168c80596a.png)

**Comment by helmuthm** [comment]
thx - I knew it was easy ;-)
