### ISSUE TITLE
Infused Panels get the same ordering number and it sometimes seem to cause glitches 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1702]
In that panel list attached, I have 4 panels with same order number.
this prevented for example the member poll panel to display, but when you re-arrange the order some it will display but another panel can poof instead. So regardless of the odd behaviour we get here. 
The ordering need to work better than it does now. Numbering is totally off.

![image](https://cloud.githubusercontent.com/assets/4210004/25301695/14959c80-272e-11e7-9dd7-01bbadb90d3f.png)

**Comment by Der-WU** [comment]
Simple way ist to cahnge the order number on installer. But the better way where, "use next value" instead of 1 2 3 or more.

**Comment by meangczac** [comment]
Drag and dropping it will rearrange all panels and normalize the order.
