### ISSUE TITLE
Move location down to misc - Profile

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1704]
![image](https://cloud.githubusercontent.com/assets/4210004/25301776/dbdb870e-272f-11e7-8159-af8dea1c1844.png)

**Comment by helmuthm** [comment]
why have so many enabled in the first place - it's a pain in the **** to disable all those fields ... let users decide what they want to have on their profile page ...

**Comment by Der-WU** [comment]
Or enable all on default als in Profil Show only Fields str filled out by the User. Not the Empty.  I Think aim ICQ and Yahoo very outdated.  :D
