### ISSUE TITLE
Move User Management Page from Settings to User Admin

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#171]
Good idea or not?

**Comment by JoakimFalk** [comment]
You lost me, there are no User Management Page under System Admin on my installation.
![system-admin-menu](https://cloud.githubusercontent.com/assets/4210004/9523270/7492b19e-4cd9-11e5-9fdd-43a74a7cc9ad.png)

**Comment by meangczac** [comment]
Sorry another tab.. my bad. :dancer: 
![screen shot 2015-08-28 at 5 18 29 pm](https://cloud.githubusercontent.com/assets/4078041/9543138/eea3651c-4da8-11e5-8f1b-68ba16c28d1c.png)

**Comment by JoakimFalk** [comment]
Well it is a setting, might as well keep it in that section

**Comment by meangczac** [comment]
ok.
