### ISSUE TITLE
Auto redirect from tracking threads / stop tracking thread crash - SEO

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1719]
final9/forum/thread/on/http://next.php-fusion.co.uk/final9/infusions/forum/viewthread.php?forum_id=1&thread_id=3&pid=4#post_4

**Comment by meangczac** [comment]
I think I find all common issues. Meta redirect of postify server is all BAD.

**Comment by FrederickChan** [comment]
Permalink Driver, is **again** not catching any non-seo link redirect and execute L=301 and redirect to SEO path. I'll debug it in a while after breakfast.
