### ISSUE TITLE
User Submit photo generate a bunch of notices and totally fail - SEO 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1721]
/final9/submit/p/photos
Line: 61
Illegal string offset 'thumb1_name'

photo_submit.php 
/final9/submit/p/photos
Line: 61
Uninitialized string offset: 0

photo_submit.php
/final9/submit/p/photos
Line: 62
Illegal string offset 'thumb2_name'

photo_submit.php
/final9/submit/p/photos
Line: 62
Uninitialized string offset: 0

**Comment by meangczac** [comment]
See if this is better. I have not uploaded file to server.
