### ISSUE TITLE
Viewing post in forum: can't vote in poll

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1727]
When you are viewing a tread/post in forum and you realize there's a poll you can vote in, then you of course try to.

clicking vote redirects to the forum 'front page' and your vote isn't recorded.

clicking vote now gives the result you wanted ...

**Comment by meangczac** [comment]
Test with SEO OFF - No Glitch. It is **perfect**.

**Comment by meangczac** [comment]
Testing with SEO On - In Progress with the rest of the driver malfunction.
