### ISSUE TITLE
Issues Closed Momentarily

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1728]
Please be notified that Issues are momentarily frozen. We will proceed further issues at 9.1

**Comment by ghost** [comment]
No Problem, Frederick. 

I follow it here every day and am already looking forward to the RC5 version out there :smile:

**Comment by meangczac** [comment]
Issues are clean now. We're pending for Falk to check on last upgrade bit now before shutting 9.02 down permanently and start 9.1
