### ISSUE TITLE
Install error - unable to connect to DB

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1733]
I tried to make clean install for testing but I have error: cannot to connect to DB.
PHP, MySQL and Apache have properly versions.
I checked connection on other method (MySQL Front, Free software) - it works with the same DB andf the same password.

**Comment by meangczac** [comment]
ok i will check again

**Comment by Der-WU** [comment]
No Problems on 

Web Server: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 OpenSSL/1.0.1t
PHP Version: 5.6.30-0+deb8u1

Tested with PDO and MySQLi!

**Comment by Rizado** [comment]
Apache 2.2.31/PHP 7.0.7 (on 5.6 tested too)/MySQL 5.5.54

**Comment by meangczac** [comment]
Rizado install XAMPP and try with that.

https://www.apachefriends.org/download.html

**Comment by Rizado** [comment]
At files permissions check I had this message repeated 5 times:

>  Warning: Illegal string offset 'severability' in /var/www/html/includes/classes/PHPFusion/Installer/Requirements.core.inc on line 234

Аnd I remember that when I try 10 hours ago, files permission checking was skipped.

OK, now I installed.

**Comment by meangczac** [comment]
I think your end have some machine problem. The array output looks ok. Illegal offset in 234 is as such:

```` 
$check_arr = array(
            "administration/db_backups" => FALSE,
            "images"                    => FALSE,
            "images/imagelist.js"       => FALSE,
            "images/avatars"            => FALSE,
            "robots.txt"                => FALSE,
        );
        // $key is filename
        // $value - boolean false
        foreach ($check_arr as $key => $value) {
            // Override key values
            $check_arr[$key] = (file_exists(BASEDIR.$key) && is_writable(BASEDIR.$key)) or (file_exists(BASEDIR.$key) && function_exists("chmod") && @chmod(BASEDIR.$key, 0777) && is_writable(BASEDIR.$key)) ? TRUE : FALSE;
            if (!$check_arr[$key]) {
                $requirements['files_check']['sub'][$key] = self::$locale['setup_0136'];
                $requirements['files_check']['sub'][$key]['severability'] = -10;

// Here is your problem :
// $requirements['files_check']['sub'][                  ]['severability'] = -10; // i.e. Is not possible.


            } else {
                $requirements['files_check']['sub'][$key] = self::$locale['setup_0137'];
            }
        }
````

I'm second guessing it's incomplete or bad file upload. We have that issue on PHPStorm CRLF upload. 
File before upload to Linux Server must be LF only or else it is 50/50 chance file corruption.

If using other FTP programs, you need to make sure it never upload as "AUTO". It must always be "BINARY" never "Ascii"

**Comment by Rizado** [comment]
It works...
I found a problem. Previous DB password was generated automatically and there were special characters like `% etc. It works because I changed password manually to "12345678".
It's seems that PF doesn't like such characters.
