### ISSUE TITLE
is the difference between ' ' and " important in locale files?

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1735]
Danish
$locale['forum_root'] = **'Debatoversigt';**
English
$locale['forum_root'] = **"Forum Index";**

is the above shown example important in connection with the locale files?

**Comment by RobiNN1** [comment]
On this page it's well described 
https://www.quora.com/What-is-the-difference-between-single-quoted-and-double-quoted-strings-in-PHP

**Comment by helmuthm** [comment]
thanx ... I might clean this up later ;-)

**Comment by RobiNN1** [comment]
For locales is better to use quotes "", because you do not have to use a backslash 
```php
$locale['locale'] = "I don't like pizza.";
```
If you use apostrophe you must use backslash
```php
$locale['locale'] = 'I don\'t like pizza.';
```

**Comment by helmuthm** [comment]
that makes it a little more easy - most of the files contain " 

👍

**Comment by RobiNN1** [comment]
You do not have to change everything

**Comment by helmuthm** [comment]
No, you're right - I don't have to, but I like the idea that things that are going to do the same thing (render English or Danish language) should be build the same way ...

the reason I asked in the first place is when I compared the different files (e.g. English setup.php versus Danish setup.php) i discovered this difference
