### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1736]
Clean install, admin password didn't work. I cleared password and salt in DB directly. When I try to set new password, I don't see first field - confirm field is displayed only.

![2017-04-23 23-00-10](https://cloud.githubusercontent.com/assets/3373906/25316958/9fa357e0-2878-11e7-8764-df91370d8fd1.png)

**Comment by meangczac** [comment]
Go to installer again.

![here](https://cloud.githubusercontent.com/assets/4078041/25319394/1ca4a3f0-28d0-11e7-8d88-9375b18c4944.PNG)

**Comment by meangczac** [comment]
I don't have error to work with here. This might be purely installation fails due to either PDO or MYSQLi driver on your end. I did code the recovery console for troubleshooting 'unknown'. Test them out.

**Comment by Rizado** [comment]
OK, now field is visible. Thanks.
