### ISSUE TITLE
The opportunity to insert an image in the admin panel in the news, in the pages

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1737]
The opportunity to insert an image in the admin panel in the news, in the pages
![-2](https://cloud.githubusercontent.com/assets/16386011/25323707/1a52f7f6-28e3-11e7-98f8-6706beb81c71.jpg)

**Comment by JoakimFalk** [comment]
It works on my tests with latest Git, please update all files.

I tried on both boxes, 
![image](https://cloud.githubusercontent.com/assets/4210004/25331312/d58c00b8-28e2-11e7-9ffe-a0febe38f9ab.png)

result

![image](https://cloud.githubusercontent.com/assets/4210004/25331239/8bf993fc-28e2-11e7-91c3-092d57cb023c.png)
