### ISSUE TITLE
Content is pushable out from screen as News , Blog was before

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#174]
![pushable-edges](https://cloud.githubusercontent.com/assets/4210004/9523191/129a7bfc-4cd9-11e5-8a64-dc6041e1ec76.png)

**Comment by meangczac** [comment]
Can't fix what I can't replicate..

**Comment by JoakimFalk** [comment]
well, it is a small thing. Closing it for now.
