### ISSUE TITLE
Navigation with the language switch button in the admin panel stopped working

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1740]
Navigation with the language switch button in the admin panel stopped working
![-2](https://cloud.githubusercontent.com/assets/16386011/25326437/017d6874-28f2-11e7-802f-fb68d221f797.jpg)

**Comment by helmuthm** [comment]
this is also the case in Artemis

![2017-04-24_09-33-49](https://cloud.githubusercontent.com/assets/9512774/25326663/73a5d524-28d1-11e7-83d6-449b5f2da7f2.png)

**Comment by helmuthm** [comment]
none of the admin themes works in the pop out menu ... only button that works is Admin Home

**Comment by helmuthm** [comment]
None of these work in admin top menu

![2017-04-24_10-00-57](https://cloud.githubusercontent.com/assets/9512774/25327646/33dc4a0a-28d5-11e7-80a2-eb0ccecbd9b5.png)

**Comment by helmuthm** [comment]
👍 

https://github.com/php-fusion/PHP-Fusion/commit/0bcbe331a447bdd96617c559411bb0d4e9b320a5
