### ISSUE TITLE
where can you alter settings for image uploads in Admin ?

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1743]
I try to upload a very tiny little image as a new category image but 4K seems to be too much :-(

and the ability to change sizes in admin area seems to have vanished up in the blue sky (even it rains in Denmark) ...

![2017-04-24_11-05-37](https://cloud.githubusercontent.com/assets/9512774/25329969/3b0136e8-28de-11e7-9c86-b843517e01ad.png)
![2017-04-24_11-06-18](https://cloud.githubusercontent.com/assets/9512774/25329970/3b06d3aa-28de-11e7-88b1-3d49738f5afc.png)

**Comment by helmuthm** [comment]
all other places than this place I can upload much bigger files ... that's crazy :(
please guide me where to find this limit so I can alter it ...


![2017-04-24_18-12-00](https://cloud.githubusercontent.com/assets/9512774/25347080/fa871876-2919-11e7-97fd-cff4098100d0.png)

**Comment by JoakimFalk** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/9e2e446a12a2dd17bd769dc662bedb0df19f7977

**Comment by JoakimFalk** [comment]
We will make it´s own interface for 9.1 or so,
