### ISSUE TITLE
News settings tab redirects to front page

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1744]
after synching (github desktop) it is no more possible to access the settings tab in News

redirects to front page of site

**Comment by JoakimFalk** [comment]
Please grabb a fresh set of files and try again, I just synced and it did work.

![image](https://cloud.githubusercontent.com/assets/4210004/25335919/674c5a22-28f5-11e7-9de2-afd27542b789.png)

**Comment by helmuthm** [comment]
yes - works now after syncing

**Comment by helmuthm** [comment]
works in Chrome, NOT in Firefox nor Safari

**Comment by JoakimFalk** [comment]
I just tested FF and IE , no problem there. very odd indeed.  Can you see where it goes wrong?, like redirect paths or aything?

**Comment by helmuthm** [comment]
tehre are several undefined index's in the error log like this one 

what I did was delete all files on the localhost - sync with github - copy files to localhost - adding danish language files to localhost


![2017-04-24_16-34-15](https://cloud.githubusercontent.com/assets/9512774/25342358/21cb868c-290c-11e7-8c35-ae02a4dabde8.png)

**Comment by JoakimFalk** [comment]
those should be locale notices, missing/ can´t read the global_200

**Comment by helmuthm** [comment]
I have also checked in Opera works OK as Chrome

Firefox and Safari don't work
I also cleared the error log - no new errors occure (at the moment)

I'm going to take a break - have to attend my choir for the evening :-)

**Comment by JoakimFalk** [comment]
We had a long day here too :) Try a hard refresh, CTRL+F5 in FF and Safari.

**Comment by helmuthm** [comment]
hard refresh in Safari helped and solved

did not work for FF ...

thx for the tip ...

**Comment by JoakimFalk** [comment]
I will have to guess that it is a local / browser issue with 3 out of 4 working and I can not reproduce the issue on my FF. Closing, if more reports come we need to figure something but closing for now.
