### ISSUE TITLE
The panels stopped moving.

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1749]
The panels stopped moving. In the admin panel they move, but they have their own site in contrast to the admin panel.
![-9](https://cloud.githubusercontent.com/assets/16386011/25339016/0e78caba-2923-11e7-9e90-651c9e11338e.jpg)

**Comment by JoakimFalk** [comment]
Confirmed, it re-order as intended it even switched sides but ordering are not followed.
