### ISSUE TITLE
installation halts after finishing db settings

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1751]
![2017-04-25_07-12-49](https://cloud.githubusercontent.com/assets/9512774/25369855/194f8712-2987-11e7-84ee-5892b4d33657.png)

**Comment by helmuthm** [comment]
going backwards with browser / refresh page

![2017-04-25_07-18-08](https://cloud.githubusercontent.com/assets/9512774/25369906/811adbb2-2987-11e7-87fd-29e908ad39d6.png)

**Comment by JoakimFalk** [comment]
I did like 4 installs lastnight, 2 upgrades never saw that one. But I will do a few more later today and we see.

**Comment by helmuthm** [comment]
I started all over again and made a fresh install:

dropped the DB
deleted all files
synced github
copied files to localhost folder
added Danish language files to localhost folder
now I get this:


Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 19

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 20

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 21

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 22

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 23

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 24

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 25

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 26

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 27

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 28

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 29

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 30

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 31

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 32

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 33

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 34

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 35

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 36

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 37

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 38

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 39

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 40

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 41

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 42

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 43

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 44

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 45

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 46

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 47

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 48

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 49

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 50

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 51

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 52

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 53

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 54

Notice: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' in /Applications/MAMP/htdocs/v9final/includes/multisite_include.php on line 55

Fatal error: Uncaught Error: Call to undefined function dbconnection() in /Applications/MAMP/htdocs/v9final/includes/core_functions_include.php:1573 Stack trace: #0 /Applications/MAMP/htdocs/v9final/includes/core_functions_include.php(1630): fusion_get_settings('theme') #1 /Applications/MAMP/htdocs/v9final/includes/defender/token.php(179): fusion_get_userdata() #2 /Applications/MAMP/htdocs/v9final/includes/dynamics/includes/form_main.php(54): Defender\Token::generate_token('setupform', 5, '') #3 /Applications/MAMP/htdocs/v9final/includes/classes/PHPFusion/Installer/Console.core.inc(44): openform('setupform', 'post', 'install.php?loc...') #4 /Applications/MAMP/htdocs/v9final/includes/classes/PHPFusion/Installer/Install.core.inc(318): PHPFusion\Installer\Console_Core::getView(NULL) #5 /Applications/MAMP/htdocs/v9final/install.php(22): PHPFusion\Installer\Install_Core->install_phpfusion() #6 {main} thrown in /Applications/MAMP/htdocs/v9final/includes/core_functions_include.php on line 1573

**Comment by helmuthm** [comment]
seems to work now
