### ISSUE TITLE
Polls seems to have not been updated

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1759]
![image](https://cloud.githubusercontent.com/assets/4210004/25396449/df495b98-29e4-11e7-9b7b-cd15ba03a6fe.png)

poll_classes.inc
/v7_Default/infusions/member_poll_panel/poll_admin.php?aid=cb5ab6b22aa52f89 **
Line: 369 unserialize(): Error at offset 0 of 20 bytes

poll_classes.inc
/v7_Default/infusions/member_poll_panel/poll_admin.php?aid=cb5ab6b22aa52f89 **
Line: 375 Invalid argument supplied for foreach()

poll_classes.inc
/v7_Default/infusions/member_poll_panel/poll_admin.php?aid=cb5ab6b22aa52f89 **
Line: 382 Invalid argument supplied for foreach()

**Comment by meangczac** [comment]
For this i need to install a v7, and download MAMP for windows. I can't run v7 on Xampp. Installing now.

**Comment by JoakimFalk** [comment]
poll_classes.inc
/v7_Default/infusions/forum/index.php?viewforum&forum_id=2
Line: 224
6 minutes ago		New Solved Ignored Delete
Severity : Run-time notices
unserialize(): Error at offset 0 of 20 bytes

**Comment by JoakimFalk** [comment]
![image](https://cloud.githubusercontent.com/assets/4210004/25442929/a6a64194-2aa6-11e7-8b0d-dced66f7056a.png)

**Comment by meangczac** [comment]
If fixed, close ok.
