### ISSUE TITLE
downloads, items per page, photo gallery should not be there

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1763]
![image](https://cloud.githubusercontent.com/assets/4210004/25396864/7de8c7ba-29e6-11e7-80af-c469a91ca132.png)

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/3e65d5e57b87ffbb5b9e97c314e6a6052c56ad0e

Not sure why $inf_deldbrow[] is not working. I've converted to dbquery for quick fix.
