### ISSUE TITLE
admin not work form_user_select()

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1767]
Admin Nowhere does not work form_user_select()

**Comment by RobiNN1** [comment]
It works
![screen](https://cloud.githubusercontent.com/assets/11664877/25402461/0e9f3458-29f9-11e7-8c1e-4905f4ecaa0c.png)

**Comment by JoakimFalk** [comment]
Works for me too

**Comment by karrak1** [comment]
download github.
not work me form_user_select() (localhost, chrome, php 5.6.30)

**Comment by RobiNN1** [comment]
Delete cache ( CTRL + F5 ) and try again.

**Comment by karrak1** [comment]
happened

**Comment by RobiNN1** [comment]
No errors in the console?

**Comment by karrak1** [comment]
solved
