### ISSUE TITLE
Forum print 

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1771]
Can't print post in SEO

**Comment by meangczac** [comment]
@RobiNN1 , i can print with my copy. 
![can_print](https://cloud.githubusercontent.com/assets/4078041/25445863/292b97be-2ae2-11e7-8f19-4091accd56ef.PNG)

**Comment by meangczac** [comment]
I will close this as non issue, maybe u can try alter the print driver rules in permalink admin or the SEF driver itself.

**Comment by meangczac** [comment]
Nvm, I reopen for Falk to confirm.

**Comment by JoakimFalk** [comment]
Yes, works for me to. 
![image](https://cloud.githubusercontent.com/assets/4210004/25445978/393e8008-2ab0-11e7-8768-975837ffdc70.png)

**Comment by RobiNN1** [comment]
![screen](https://cloud.githubusercontent.com/assets/11664877/25445982/41456924-2ab0-11e7-97a8-94d9fbd43b03.png)
after click on this redirects to home

**Comment by JoakimFalk** [comment]
![image](https://cloud.githubusercontent.com/assets/4210004/25446057/8e2024c8-2ab0-11e7-9a0c-df00c8ace692.png)

**Comment by RobiNN1** [comment]
I try reinstall forum and forum permalinks

**Comment by JoakimFalk** [comment]
Do you have any special chars in the subject?, topics?
Enable Normalize function

**Comment by JoakimFalk** [comment]
Try it on, 
![image](https://cloud.githubusercontent.com/assets/4210004/25446139/de0ec9da-2ab0-11e7-9644-d47e9cbc0ba3.png)

**Comment by RobiNN1** [comment]
enabled

**Comment by meangczac** [comment]
We will set up a test server environment later. 

Falk and I online rushing for release. So I won't wait for this issue. Been upgrading over thousand of times since 6am this morning and it's now 12:53am.
