### ISSUE TITLE
Split words in forum

### ISSUE THREAD

**Issue by bronxi** [PHPFusion/PHPFusion#1772]
After a refresh from git 20mins ago, it now split the whole words from each other.
![unavngivet](https://cloud.githubusercontent.com/assets/25545883/25439720/812441a4-2a9d-11e7-9c3d-4ab7377f6a10.png)

**Comment by bronxi** [comment]
It is the same, no changes happen
![unavngivet](https://cloud.githubusercontent.com/assets/25545883/25441461/923a1b62-2aa2-11e7-8c9b-e65bb824d095.png)

**Comment by RobiNN1** [comment]
Delete cache
