### ISSUE TITLE
repository for translations for 9.03?

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1777]
will there be a new repository for translated locales or should we continue using https://github.com/php-fusion/PHP-Fusion-9-Locale ???

**Comment by Rizado** [comment]
I use old. And who wrote about 9.03?

**Comment by helmuthm** [comment]
Chan did: https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38506

**Comment by kot2007** [comment]
Oh wow, such a great news and I've almost missed it! Congrats for all!
BTW, there is no new download on the official site, still v.7.
About the question: why do we need a new repo? Maybe we should create a new branch?
Frankly speaking, as for me I don't whant to change anything :)
For now I'm using the old one too.

**Comment by RobiNN1** [comment]
For locales use old repo, is not needed create a new branch.

**Comment by meangczac** [comment]
Im sorry for not being clear. I mean 9.03 is the active branch now for fixes. Locale repo still old.

**Comment by meangczac** [comment]
@kot2007 the download for version 9 is in the news itself. Since the new site is going to be relaunched, I am lazy to update. Hehehe..

The master branch here or the release version tab here is also v9 stable. Git users dont use the dl link anyway.
