### ISSUE TITLE
database update 9.0->

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1778]
The database will be upgraded by upgrade.php to the next version?

**Comment by meangczac** [comment]
upgrade/9.0.2 upgrade ? Yes on v7 to v9. It also inject an initial version to infusions table for the infusions to be able to be upgraded individually since v7 does not have these core infusions.

**Comment by meangczac** [comment]
Just run the install.php

**Comment by karrak1** [comment]
9.0 to 9.1 install.php upgrade, or admin->upgrade.php 
If you use install.php, delete the upgrade.php from the admin directory

**Comment by JoakimFalk** [comment]
install.php for the initial upgrade. The administrration/upgrade.php is good to keep for minor code changes  on revisions when it comes to patches and database update of current version for example.
