### ISSUE TITLE
Comments on Galerieview not counted

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1780]
![image](https://cloud.githubusercontent.com/assets/164333/25557869/20ca340a-2d1b-11e7-8b2f-600a594255bf.png)
![image](https://cloud.githubusercontent.com/assets/164333/25557871/2b50e770-2d1b-11e7-8da8-4d09a4278b45.png)

**Comment by karrak1** [comment]
fix

**Comment by Der-WU** [comment]
thX
