### ISSUE TITLE
Foto Count on Admin Galery overview in text is wrong

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1784]
There are 2 Kategories with 2 Fotos inside not 4.

![image](https://cloud.githubusercontent.com/assets/164333/25563590/4370998e-2d9f-11e7-8a69-2d76f582a9f2.png)

**Comment by karrak1** [comment]
![okgalery](https://cloud.githubusercontent.com/assets/16163102/25564798/0f62cbbe-2dbb-11e7-9e22-a5c9eabb3597.jpg)

aright count, comment count not work. fix

**Comment by Der-WU** [comment]
Count still wrong  see Picture
( After deleting an old Album with Pictures. i think it is related to #1792, Fotos after deleting not moved to new Album and get lost, but Counter still use the lost Fotos )
![count](https://cloud.githubusercontent.com/assets/164333/25912086/67485fd0-35b6-11e7-91d3-35aef52ac8e0.png)

**Comment by karrak1** [comment]
Did not delete the images
corrected
https://github.com/php-fusion/PHP-Fusion/commit/04c156329ef5e18ebfb62df2bd8566fd222c67e1
