### ISSUE TITLE
PHP-Fusion 9.03 version in Turkish has this error in the new installation

### ISSUE THREAD

**Issue by ALTUN69** [PHPFusion/PHPFusion#1785]
Notice: Query Error: INSERT INTO fusionpnh6m_settings (`settings_name`, `settings_value`) VALUES ('sitename', 'PHP-Fusion Powered Website'), ('siteurl', 'http://fusion.alapelit.com/'), ('site_protocol', 'http'), ('site_host', 'fusion.alapelit.com'), ('site_port', ''), ('site_path', '/'), ('site_seo', '0'), ('sitebanner', 'images/php-fusion-logo.png'), ('logoposition_xs', 'logo-xs-left'), ('logoposition_sm', 'logo-sm-left'), ('logoposition_md', 'logo-md-left'), ('logoposition_lg', 'logo-lg-left'), ('sitebanner1', ''), ('sitebanner2', ''), ('siteemail', ''), ('siteusername', ''), ('siteintro', '
Sitenize Hoşgeldiniz
'), ('description', 'PHP-Fusion, PHP ile yazılmış hafif açık kaynak kodlu bir içerik yönetim sistemi (CMS) 'dir.'), ('keywords', 'PHP-Fusion, CMS, Portal, Open Source, AGPL, PHP, MySQL, HTML, CSS, JS'), ('footer', '
Copyright © 2017
'), ('opening_page', 'home.php'), ('locale', 'Turkish'), ('bootstrap', '1'), ('entypo', '0 in /home/alapelit/public_html/fusion/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc on line 71

Notice: Undefined index: siteusername in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 339

Notice: Undefined index: siteemail in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 339

Notice: Undefined index: locale in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 339

Notice: Undefined index: siteusername in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 340

Notice: Undefined index: siteemail in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 340

Notice: Undefined index: locale in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 340

Notice: Undefined index: siteusername in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 341

Notice: Undefined index: siteemail in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 341

Notice: Undefined index: locale in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 341

Notice: Undefined index: locale in /home/alapelit/public_html/fusion/upgrade/9.0.upgrade.inc on line 609

Fatal error: Cannot redeclare rrmdir() (previously declared in /home/alapelit/public_html/fusion/upgrade/upgrade_functions_include.php:22) in /home/alapelit/public_html/fusion/upgrade/upgrade_functions_include.php on line 22
![2017-04-30](https://cloud.githubusercontent.com/assets/8268248/25567933/73282f8a-2df8-11e7-999b-552c11f5747e.png)

**Comment by JoakimFalk** [comment]
Does it work in English?

**Comment by ALTUN69** [comment]
Does not work in English

**Comment by JoakimFalk** [comment]
none of these issues are present in Stable 9, check the requirements please.

**Comment by ALTUN69** [comment]
I solved the problem. There is no error in translating.
The source of the error is the encoding of the setup.php file in windows format.
I converted the language file of setup.php to Unix format and the problem is solved.
