### ISSUE TITLE
Articles

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1786]
someone is wrong - all content is bold - i have update with the newest core files for some minutes. with old it was ok

![grafik](https://cloud.githubusercontent.com/assets/22166864/25580274/d9f2aee8-2e7f-11e7-9848-ff438461ee48.png)
 
![grafik](https://cloud.githubusercontent.com/assets/22166864/25580286/04602b06-2e80-11e7-8461-e7fd3b21ba6f.png)

**Comment by RobiNN1** [comment]
Unclosed or extra ```<strong>```  in you code

**Comment by UnrealCatze** [comment]
sure it comes from my code? I had thois after i change the core files. with my old core files i had this not.
