### ISSUE TITLE
Invalid display of poll start date

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1787]
![-2](https://cloud.githubusercontent.com/assets/16386011/25600809/b47a2432-2f08-11e7-8645-8bb2b7ee4b14.jpg)
Invalid display of poll start date

**Comment by RobiNN1** [comment]
It works. Maybe try change date to actual.
![screen](https://cloud.githubusercontent.com/assets/11664877/25674471/328dc026-303b-11e7-92d8-40288168f5fb.png)

**Comment by ovasclub** [comment]
Yes. The problem of Russian localization
