### ISSUE TITLE
Forum - PDOMySQL.inc

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1788]
i have update all core files last weekend ... but i have an error in forum

PDOMySQL.inc
/site/infusions/forum/index.php?viewforum&forum_id=6&type=unsolved&sort=time&time=6month
Line: 71
10 hours ago 	

Severity : Notice generated by user using trigger_error() function
Query Error: SELECT t.*, tf.forum_type, tf.forum_name, tf.forum_cat, tu1.user_name ' author_name', tu1.user_status 'author_status', tu1.user_avatar 'author_avatar', tu2.user_name 'last_user_name', tu2.user_status 'last_user_status', tu2.user_avatar 'last_user_avatar', p1.post_datestamp, p1.post_message, IF (n.thread_id > 0, 1 , 0) 'user_tracked', count(v.vote_user) 'thread_rated', count(pv.forum_vote_user_id) 'poll_voted', p.forum_poll_title, count(v.post_id) AS vote_count, a1.attach_name, a1.attach_id, a2.attach_name, a2.attach_id, count(a1.attach_mime) 'attach_image', count(a2.attach_mime) 'attach_files', min(p2.post_datestamp) 'first_post_datestamp' FROM fusion62855_forum_threads t LEFT JOIN fusion62855_forums tf ON tf.forum_id = t.forum_id INNER JOIN fusion62855_users tu1 ON t.thread_author = tu1.user_id LEFT JOIN fusion62855_users tu2 ON t.thread_lastuser = tu2.user_id LEFT JOIN fusion62855_forum_posts p1 ON p1.thread_id = t.thread_id and p1.post_id = t.thread_lastpostid LEFT JOIN fusion62855_forum_posts p2 ON p2.thread_id = t.thread_id LEFT JOIN fusion62855_forum_polls p ON p.thread_id = t.thread_id
#LEFT JOIN fusion62855_forum_votes v ON v.thread_id = t.thread_id AND p1.post_id = v.post_id LEFT JOIN fusion62855_forum_votes v on v.thread_id = t.thread_id AND v.vote_user='0' AND v.forum_id = t.forum_id AND tf.forum_type='4' LEFT JOIN fusion62855_forum_poll_voters pv on pv.thread_id = t.thread_id AND pv.forum_vote_user_id='0' AND t.thread_poll=1 LEFT JOIN fusion62855_forum_attachments a1 on a1.thread_id = t.thread_id AND a1.attach_mime IN ('image/jpg,image/jpeg,image/gif,image/png,image/tiff,image/tif,image/x-ms-bmp,image/x-icon') LEFT JOIN fusion62855_forum_attachments a2 on a2.thread_id = t.thread_id AND a2.attach_mime NOT IN ('image/jpg,image/jpeg,image/gif,image/png,image/tiff,image/tif,image/x-ms-bmp,image/x-icon') LEFT JOIN fusion62855_forum_thread_notify n on n.thread_id = t.thread_id and n.notify_user = '0' WHERE t.forum_id='6' AND t.thread_hidden='0' AND tf.forum_access = 0 AND ((p1.post_datestamp BETWEEN '1478124949' AND '1493763349') OR (t.thread_lastpost BETWEEN '1478124949' AND '1493763349'))AND t.thread_answered = '0' AND tf.forum_language='English' GROUP BY t.thread_id ORDER BY t.thread_lastpost DESC LIMIT 0, 20
Stack Trace:
#0 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(67): PDOStatement->execute()
#1 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('? SE...', Array)
#2 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('? SE...', Array)
#3 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/classes/threads/threads.php(146): dbquery('? SE...')
#4 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/classes/forum/forum.php(331): PHPFusion\Forums\Threads\ForumThreads::get_forum_thread(6, Array)
#5 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/classes/server.php(447): PHPFusion\Forums\Forum->set_ForumInfo()
#6 /var/www/vhosts/xxxxxxxxxxxx.com/httpdocs/site/infusions/forum/index.php(27): PHPFusion\Forums\ForumServer::forum()
#7 {main}
Error Nature: SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared

**Comment by karrak1** [comment]
I have not experienced yet, when he came?

**Comment by meangczac** [comment]
IDK how he get this. But anyway, I'm working on a new version for the forum now. The queries in the current one is very bad on large datasets. Project has been set up.
