### ISSUE TITLE
user_rights are glicthing in more than 1 place during upgrade

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1789]
It seems to be more than user tables that are affected, Jan reports forum as well.
Check ALL Infusions that have rights so these do not glitch.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38515
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38534&pid=202487#post_202487

**Comment by JoakimFalk** [comment]
Update,RobiNN patched user from Netrix. 
forum posts are still having issues, rest of forum areas seem to be ok according to Netrix.
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38535

**Comment by RobiNN1** [comment]
Just forum_mods can't upgrade to -103, -102, -101
