### ISSUE TITLE
GIT Commandos not worked for local clone

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1791]
Hello Developers,

Unfortunately updating my local clone repos in the command line does not work.

What am I doing wrong?

     git fetch https://www.github.com/PHP-Fusion/php-fusion.git 9.00
    warning: redirecting to https://github.com/PHP-Fusion/php-fusion.git/
    From https://www.github.com/PHP-Fusion/php-fusion
    * branch                9.00       -> FETCH_HEAD
    [xxxxx@liebrecht-projekte PHP-Fusion]# git merge
    Already up-to-date.
    [xxxxxx@liebrecht-projekte PHP-Fusion]# git push
    Username for 'https://github.com': AlexL777
    Password for 'https://AlexL777@github.com':
    remote: Permission to php-fusion/PHP-Fusion.git denied to AlexL777.
    fatal: unable to access 'https://github.com/php-fusion/PHP-Fusion.git/': The requested URL returned error: 403
    [xxxxx@liebrecht-projekte PHP-Fusion]#`

Thanks in advance.

**Comment by ghost** [comment]
I deleted my Clone-Repo in bitbucket server and imported your PHP-Fusion-Repo from Github.

Let's see if it will work now.

Which branch is now up-to-date and is being developed?

Thank you

**Comment by JoakimFalk** [comment]
We are working on 9.03
