### ISSUE TITLE
Exclude Left Panels: /infusions/news/news.php Not working

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1793]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38543&pid=202518

**Comment by RobiNN1** [comment]
It works and with parameters

**Comment by afaaro** [comment]
well mine not working

**Comment by JoakimFalk** [comment]
Any one have ideas here  ( see thread ) ?

**Comment by JoakimFalk** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/3d6e10990f8271b603e06775d7343de023a28905
