### ISSUE TITLE
Two bugs in theme

### ISSUE THREAD

**Issue by omikron20** [PHPFusion/PHPFusion#1795]
Hi I have problem with look of my website.  
one is strange margin You can find on attached picture. And wrong display colapse menu in system admin.
![crazycolapse](https://cloud.githubusercontent.com/assets/26767781/25779845/f7958aac-331f-11e7-813d-58eeb6de581d.jpg)
!
![crazymarg](https://cloud.githubusercontent.com/assets/26767781/25779852/27b26cdc-3320-11e7-9b0c-34bfbd1ffb9e.jpg)

**Comment by RobiNN1** [comment]
For second issue pleas read https://github.com/php-fusion/PHP-Fusion/issues/1796

![jhbnio](https://cloud.githubusercontent.com/assets/11664877/25780672/4f71d8c8-332c-11e7-9bb3-2c9e6a2d212e.png)

**Comment by omikron20** [comment]
Is fixed
