### ISSUE TITLE
For translators - please read

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1796]
Please change in all locale files encoding from UTF-8 with BOM to UTF-8.
I found this bug in Danish/admin/settings.php
Before: 
![screen](https://cloud.githubusercontent.com/assets/11664877/25780615/76b0f272-332a-11e7-8347-4bfd202a538d.png)

and after changing to UTF-8
![screen](https://cloud.githubusercontent.com/assets/11664877/25780626/cda687e0-332a-11e7-91f5-3cb73fbe556b.png)

**Comment by omikron20** [comment]
I don't know how to do it. Can you explain me ?

**Comment by RobiNN1** [comment]
What code editor do you use?

**Comment by omikron20** [comment]
notepad ++

**Comment by RobiNN1** [comment]
You must check all files in your locale.
In menu find encoding end set to UTF-8 if is checked UTF-8-BOM
![jhbin](https://cloud.githubusercontent.com/assets/11664877/25783002/cbcf2e98-3354-11e7-8bcf-90ce4f51554c.png)

**Comment by omikron20** [comment]
Thanks so much

**Comment by JoakimFalk** [comment]
Let´s keep it to the official forums.
Both of these threads cover it.

> Make sure that you save the files in UTF-8 Without BOM.

here: https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37102
and RobiNNs thread with screens here: https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38546
