### ISSUE TITLE
datapicker dosent work anymore

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1797]
anyone chnged the last time? 
my datapicker dosent work after core update

**Comment by UnrealCatze** [comment]
add_to_head("<link href='".DYNAMICS."assets/datepicker/css/bootstrap-datetimepicker.min.css' rel='stylesheet' />");
    add_to_footer("<script src='".DYNAMICS."assets/datepicker/js/moment.min.js'></script>");
    add_to_footer("<script src='".DYNAMICS."assets/datepicker/js/bootstrap-datetimepicker.min.js'></script>");
    add_to_head("<script src='".DYNAMICS."assets/datepicker/locale/".$locale['datepicker'].".js'></script>");
}

hmn in css folder im missing files
chnage?

**Comment by RobiNN1** [comment]
Check this commit https://github.com/php-fusion/PHP-Fusion/commit/30feb97b810a77c172d17f3e5f96ef7253e65a42

**Comment by JoakimFalk** [comment]
I just did a sync and test it in profile, works well for me on the test site.
