### ISSUE TITLE
Please help to code

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1799]
I everybody. I hope someone can help me. :D 

 On File -> inlcudes/theme_functions_include.php

In Line 820 -> return "<abbr class='atooltip' data-toggle='tooltip' data-placement='top' title='".showdate('longdate', $updated)."'>".$answer." ".$string." ".$locale['ago']."</abbr>";

HOW TO make a if else of it?
I Need it for transaltion.

if -> Locale German
return "<abbr class='atooltip' data-toggle='tooltip' data-placement='top' title='".showdate('longdate', $updated)."'>"".$locale['befor']." ".$answer." ".$string."</abbr>";
else ->
return "<abbr class='atooltip' data-toggle='tooltip' data-placement='top' title='".showdate('longdate', $updated)."'>".$answer." ".$string." ".$locale['ago']."</abbr>";

Any ideas?

Greatz WuChEn

**Comment by RobiNN1** [comment]
Please create the thread at official Forum, because this is not a issue.
