### ISSUE TITLE
Latest Comments Panel

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1800]
F:\xampp\htdocs\PHP-Fusion\infusions\latest_comments_panel\latest_comments_panel.php
/home.php **
Line: 167
Severity : Run-time notices
Undefined variable: infos

F:\xampp\htdocs\PHP-Fusion\infusions\latest_comments_panel\latest_comments_panel.php
/home.php **
Line: 167
Severity : Non fatal Runtime Errors
Invalid argument supplied for foreach()

![screen](https://cloud.githubusercontent.com/assets/11664877/25865565/94e4b628-34f3-11e7-9807-843e94f8c097.png)
![sceen2](https://cloud.githubusercontent.com/assets/11664877/25865608/bd0fb77e-34f3-11e7-80d9-74893a849d3f.png)

**Comment by RobiNN1** [comment]
Does not show News comments.

**Comment by karrak1** [comment]
works for me
![capture](https://cloud.githubusercontent.com/assets/16163102/25907462/ce007758-35a7-11e7-8f4a-5228bc27cffa.jpg)

**Comment by RobiNN1** [comment]
In Comments panel, all show but not comments from news
