### ISSUE TITLE
Submit News reloads and removes all data

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1803]
> When I write some news and click on preview news button, everything what i write was deleted, and preview don't shows. I have instaled official release of php-fusion 9. I don't install latest files from github.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38555&pid=202582#post_202582

**Comment by karrak1** [comment]
git
[](https://github.com/php-fusion/PHP-Fusion/commit/22a9bd2f80d0840109ccc15c10cca57b2f70ab54)
