### ISSUE TITLE
Last Update on News Overview use 1970 !!??!!??

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1805]
![news1](https://cloud.githubusercontent.com/assets/164333/25913610/a92aecf6-35bb-11e7-9e79-9efd89c5f439.png)

**Comment by JoakimFalk** [comment]
It comes when you edit news?

**Comment by Der-WU** [comment]
It is a fresh created news without editing.

**Comment by JoakimFalk** [comment]
https://github.com/php-fusion/PHP-Fusion/issues/1827
