### ISSUE TITLE
Button on Articel overview

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1806]
I think Button on articel Overview should have "Categories" on it like on News overview.
![articel](https://cloud.githubusercontent.com/assets/164333/25913921/c17bd8aa-35bc-11e7-8498-949573c8c116.png)
![articel2](https://cloud.githubusercontent.com/assets/164333/25913924/c3a2952e-35bc-11e7-891f-1bfa85758e13.png)

**Comment by Der-WU** [comment]
2 more titels missing see Pictures
![articel](https://cloud.githubusercontent.com/assets/164333/25918911/543237d8-35cd-11e7-9501-3aa38af69fe2.png)
![articel2](https://cloud.githubusercontent.com/assets/164333/25918916/5878cbea-35cd-11e7-9ea1-08d475a91457.png)

**Comment by RobiNN1** [comment]
That's is ok. You can edit the template, replace this https://github.com/php-fusion/PHP-Fusion/blob/9.03/infusions/articles/templates/articles.php#L98-L99  by 

```php 
                        <?php echo form_button("switchview", "<i class='fa fa-fw fa-th-large'></i> ".$locale['article_0040'], "1", array("class" => "btn-sm btn-default nsv".($active == "1" ? " active" : ""), "alt" => $locale['article_0040'])); ?>
                        <?php echo form_button("switchview", "<i class='fa fa-fw fa-bars'></i> ".$locale['article_0041'], "2", array("class" => "btn-sm btn-default nsv".($active == "2" ? " active" : ""), "alt" => $locale['article_0041'])); ?>
```
