### ISSUE TITLE
infusions/gallery/submissions/images/ missing

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1808]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38561&pid=202619

**Comment by RobiNN1** [comment]
Photos are saved to submissions folder, submissions/images/ folder is unnecessary.
https://github.com/php-fusion/PHP-Fusion/blob/9.03/infusions/gallery/photo_submit.php#L104
