### ISSUE TITLE
Add htaccess rule

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#181]
<code>
< Files ~ "(^#.*#|~|.sw[op])$" >
Order allow,deny
Deny from all
< /Files >
</code>

http://feross.org/cmsploit/

**Comment by JoakimFalk** [comment]
We use this on config ,

# Protect config.php

<Files config.php>
order allow,deny
deny from all
</Files>

**Comment by meangczac** [comment]
<b>I misread the first time too.</b> And I emailed the author about solution, and he asked me he did not undestood the question. I was so embarrassed about it.

The article is about this.. when someone edit config.php directly thru Filezilla, Emacs, Vim, etc it creates a tmp file of that config.php - 

You did not protect these files:

wp-config.php~        # Vim, Gedit
#wp-config.php#       # Emacs
wp-config.php.save    # Nano
wp-config.php.swp     # Vim (swap file)
wp-config.php.swo     # Vim (swap file)

 The author builds a script to sniff these files and found that close to 1% of top sites exposed the config file. In 2014, millions of sites were vulnerable caused by this. This rule is to prevent $_GET request to sniff these files. Also need to add a public warning not to edit files directly on server in h1 font. 

---

There is another one recently hit hijacking CMS sites - CryptoPHP - http://blog.fox-it.com/2014/11/18/cryptophp-analysis-of-a-hidden-threat-inside-popular-content-management-systems/ - A user downloads a free theme in the Website, inside there is a .png file that is embedded with a very sophisticated script that allows itself to auto-patch itself against removal once uploaded to server, and links with a command and control center. It can access your DB, steal all your customer's credit card number, password, etc and inject your site with hidden files that launches DDos attack against servers. 

The author is very smart. He knows, all CMS -> uploading themes won't go thru image vulnerability scans. Just FTP. So, only thing that comes to my mind is that approving themes submissions need to be scanned using anti-virus first. Making available themes on site with malicious script is a crime.

---

**Comment by JoakimFalk** [comment]
I see, that seems reasonable to avoid, I guess we could include a Tools section at some point with things like malicious code scanner, image scanner. ( better to separate them for execution times) even tho it does the same. But one check images and the other php files, js scripts etc. 
Naturally a database optimiser on top of it. 
Basically , I think we should have something like Netrix started here : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=36404.

**Comment by meangczac** [comment]
Ok, keep this issue open then. I'm not going to add the .htaccess rule because my knowledge to verify it is limited.
