### ISSUE TITLE
Custom DB Prefix during install did not take effect

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1812]
I entered custom DB and it still took random one.

I did have a major crash by some reason before, perhaps it glitched it...

**Comment by RobiNN1** [comment]
Weird, on my server works. 

Apache 2.4.25
PHP 7.1.8

**Comment by JoakimFalk** [comment]
I guess it was due to the crash, did not test again after it. We can close it, ty.
