### ISSUE TITLE
Adminsitration is not counting all member correctly / pagination issue

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1817]
![image](https://cloud.githubusercontent.com/assets/4210004/26150035/0165abc2-3afd-11e7-862e-f44deb8d3593.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38579&pid=202690#post_202690

**Comment by helmuthm** [comment]
to clarify: you are only allowed to see the first page (containing 16 members) and it is not possible to see the rest (page 2 etc.) 

only way too see members on those pages are by searching for them
