### ISSUE TITLE
Change Admin Passwort on Edit Profil did not work.

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1819]
See Titel

**Comment by meangczac** [comment]
Steps to recover admin password when you're locked out. Read the codes carefully.

Reset Password Walkthrough
-----
Step 1:
$user_id = ''; // insert your user id here
$result = dbquery("UPDATE ".DB_USERS." SET user_admin_password=:blank1 and user_admin_salt=:blank2 WHERE user_id=:user_id", [':blank1' => '', ':blank2' => '', ':user_id'=>$user_id]);
if (dbrows($result)) {
addNotice('success', 'You have updated and reset the users admin password');
}

Similarly, go to PHPMyadmin, blank out "user_admin_password" and "user_admin_salt" column for that particular user. Yes, wipe clean - blank.

Step 2:
Login - and then a warning notice will appear. Go to edit profile and enter new admin password and repeat new admin password.  **Login password is not required.**

Now go to admin, use that new password. 


Changing Admin Password in _user_profile.php_
-------
Type in OLD admin password.
Type in New Admin Password
Type in Repeat New Admin Password.
Click Update.
New admin password will be in effect. 

If you get error saying that the password cannot be changed using this way, give me the errors displayed in the field itself. Most probably is your current admin password is wrong or forgotten. In such case, use Step 1 if you're Site Owner. 

If you're not site owner, ask the site owner do it for you - let him read step 1 or go to the admin panel and do the admin password reset process. The long way of sending mail bla bla bla.. which is the way of the v7
