### ISSUE TITLE
Longtext fields come out empty in PHP7, everything works fine in PHP5

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#1822]
To set the stage here, I'm using the official PHP docker containers.

If I use PHP7 and enable PDO, all the comment bodies, article bodies and forum bodies are empty on output. Usernames and dates etc come out, and I can see there should be comments there, however they are all blank. This happens with all plugins.

Roll the container back to PHP5 and all is well. PHP7 is supposed to be supported so I'm a bit confused.

Debugging has not produced any errors I can find. 

Seems like it could be related to this question: http://stackoverflow.com/questions/6972319/why-does-mysqli-fetch-return-empty-results-from-longtext-column 

However I'm at a loss as to why I would experience this and not others.

I've tested this and MySQL version does not seem to affect the issue, the problem is the same with either MySQL 5.5 or 5.7

**Comment by meangczac** [comment]
Ok I haven't try this yet. I will find out.

**Comment by meangczac** [comment]
I would like to see a sample page. I'm using XAMPP on PHP 7.1 on Dev server.
I'm also building and tested my work constantly on a live server provided by PHP-Fusion Inc.

I do not encounter any issue so far.

I'm thinking it's a server configuration at Apache level? Not sure until I can produce the error.
