### ISSUE TITLE
token.php

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1823]
token.php
/site/home.php
Line: 73

Severity : Run-time notices
Undefined index: form_id

get this sometimes

**Comment by meangczac** [comment]
Your site is full of bot or is running a ````<form>```` tag without using openform() 
That will cause you alert someone is trying to inject something bad and or is failing to do so causing the whole site to go into 'defensive' mode and prevent any SQL insert/update/delete
