### ISSUE TITLE
 links don´t parse in e-mail messages with SEO Enabled

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1824]
![image](https://cloud.githubusercontent.com/assets/4210004/26279621/f359e16a-3db8-11e7-85f5-c9bf82036631.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38598&pid=202754#post_202754

**Comment by RobiNN1** [comment]
In English works?
