### ISSUE TITLE
Remove PHP Trims on Texts and replace with CSS3 solutions

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1825]
The trim is a bad way to go. 

The problem with trimlink, trim_text and all the fusion_first_words are literally a bad solution with formatted texts output. Because simply it produces HTML as such:

````
[b]Something....
````

or 

```` 
<strong>Something that got tri...... 
````

So, the solution is  to wrap it inside a non float container and use this CSS styling. It will automatically add "..." for the overflow text if you have a defined width or height. 

This is a browser base solution instead of wasting resources on PHP processor for such trivial matter and get people asking why it happens all over the support forum.

The CSS replacement for the PHP trims:

**add to Default.min.css and default.css**
````
.text-overflow-hide {
    overflow: hidden;
    text-overflow: ellipsis;
}
````

I believe this issue will be more user centric than developer centric since we do not know what kind of content people will do and this probably is the one-for-all solution.

**Comment by RobiNN1** [comment]
I created jQuery function for this.

Function:
```javascript
$.fn.trim_text = function() {
    var length = this.data("trim-text"), newtext;
        
    newtext = this.text().substr(0, length) + "...";
    
    return this.text(newtext);
} 
```

Usage:
Add the attribute data-trim-text="30" to the div, 30 is length of output text.
```html
<div id="text_id" data-trim-text="30">';
    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Fugit quod id aliquid corrupti molestias aperiam modi corporis earum quam, tempore perferendis ipsum illum porro,
    recusandae nihil veniam alias quibusdam atque omnis cumque tenetur iure adipisci velit!
    Quo odio obcaecati aperiam aut? Assumenda sit magnam voluptate delectus reprehenderit modi dolorem officiis rerum quae cumque ipsum,
    illum vitae, debitis perspiciatis laudantium excepturi mollitia numquam et voluptates molestiae recusandae similique.
</div>
```
```php
add_to_jquery("$('#text_id').trim_text();");
```

Output:
Lorem ipsum dolor sit ame...

**Comment by meangczac** [comment]
Champ! Ill try this later.
