### ISSUE TITLE
members.php pagination broken in SEO

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1828]
> I have activated SEO (= /website-members)
> but it's not possible to go to page 2, 3, 4 etc. - gives an 404 (/index.php?sortby=all&rowstart=24)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38599&pid=202774#post_202774

**Comment by karrak1** [comment]
sortby SEO OK,
 search and select menu SEO not good.

**Comment by helmuthm** [comment]
any solution here?
