### ISSUE TITLE
How to add new Languages

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#183]
Hello there.
I want to translate PHPFusion to german.
How can i do it?
Only Create folder german, copy files from english and edit them?
Or there more to do?
Sorry for my bad english. :)

Greatz WuChEn

**Comment by Rizado** [comment]
Yes, you are right. Just copy English locale and translate all files to German.
Notice: see /infusions/articles/locale, /infusions/news/locale etc. too.

**Comment by Der-WU** [comment]
No more needed in config or database? 
If i done, should i take a pull request or create a zip with all files?

Greatz WuChEn

**Comment by Rizado** [comment]
Don't touch the config :-) .
The better is pull request. It may appove Hien, Domi or me.

**Comment by meangczac** [comment]
Please make a pull request. :+1:
