### ISSUE TITLE
RSS does not parse HTML - SEO On.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1830]
I know it should, we had this topic up like 10 times, Maybe it is SEO mode that fubars it.

![image](https://cloud.githubusercontent.com/assets/4210004/26352027/3f0a3dd2-3fba-11e7-970d-8bc66d205df4.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38601&pid=202779#post_202779

**Comment by Rizado** [comment]
Please give me link to this feed.
Thanks!
