### ISSUE TITLE
[LOCALE] PM inbox shows months name in English

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1835]
![image](https://cloud.githubusercontent.com/assets/4210004/26453275/793c8bae-4163-11e7-8bf4-f3ab00d87b5b.png)

**Comment by helmuthm** [comment]
now it doesn't read May any longer, but it's still kind of English: you wouldn't write 05.20 in Danish but 20.05

in this example it isn't confusing but consider the confusion when it's 01 Feb ...

![pm-date2](https://cloud.githubusercontent.com/assets/9512774/26495071/3b85063c-4222-11e7-932e-d086e6840efe.png)

**Comment by helmuthm** [comment]
the latest update has removed date totally ...

![pb-missing-date](https://cloud.githubusercontent.com/assets/9512774/26514142/3d829c76-4270-11e7-8e3c-10c141ba795c.png)

**Comment by JoakimFalk** [comment]
You need to update your Danish global, https://github.com/php-fusion/PHP-Fusion/commit/eb1a28540a6d347a24afcc638a1b7f4469be9bff
`$locale['date_day'] = "%d %b";`

**Comment by helmuthm** [comment]
I had missed that one - works now!
