### ISSUE TITLE
Optimization of Core Process

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1838]
The bootstrap theme is used as a benchmark for the purpose of this issue. 

Environment is tested on this season's performance PC:
- 16 gb DDR4 performance 3000Mhz ram
- Samsung Evo SSD
- Netstat less than 15 processes
- Intel Hexacore 3.2ghz processor
- Graphic card may not be relevant, running GTX 1080 Ti FE.
- Localhost - Xampp latest PHP 7.1.1

I produced this on a blank file just to see the performance:

![base_time](https://cloud.githubusercontent.com/assets/4078041/26617843/013013fa-460a-11e7-8966-5b0340661e96.PNG)

I've created a new file with header, footer, and body, and bootstrap on. As we can see the render time is very high for a blank file. It's about 0.24-0.30 -ish zone. 

We need to dig up every single file, and reduce the query or whatever is stalling the render speed to about 10 times faster. **It should be 0.02s**

**Comment by meangczac** [comment]
Latest finding after digging for few hours:

![time_loaded](https://cloud.githubusercontent.com/assets/4078041/26619761/71528cdc-4612-11e7-8184-c18be660d9d8.PNG)

I'm puzzled. Going to check back at core codes.

**Comment by meangczac** [comment]
After fixing the locale engine

It is slightly improvised a little.

![performance_shot](https://cloud.githubusercontent.com/assets/4078041/26624471/8c7dea68-4623-11e7-901a-852d2332ffd2.PNG)

As you can see the core codes that runs from header to middle body - Is quite OK.

After in footer we have about a slight drop from the original. 

The hunt continues.

**Comment by meangczac** [comment]
A am creating a new theme for the community pending all my work with main site development now. A clean and lightweight theme.

Without sitelinks, the render speed is optimum. That probably is the culprit behind the 0.2s from the original 0.1s

![without_sitelinks](https://cloud.githubusercontent.com/assets/4078041/26625389/851aea20-4626-11e7-9473-2bdc99961bc1.PNG)

**Comment by meangczac** [comment]
I'll close this issue now.

**Comment by meangczac** [comment]
I did a render time at file to test this. All core confirms runs at 0.10s.

![capture](https://cloud.githubusercontent.com/assets/4078041/26629995/60b43450-4637-11e7-849a-be1b3dcc77c2.PNG)

If you want to get same breaking results at footer.php, turn off:

1. Remove Font Awesome + Entypo
2. Bootstrap disabled or Remove it
3. Turn off Jquery or Remove it
4. Remove OG tags implementation
5. Remove Holder.js
6. Remove SEO.

Make a new custom layout.php with non of the above implemented. It will be very fast.

**Comment by RobiNN1** [comment]
For 3rd Party scripts use external CDNs, it's better and faster.
