### ISSUE TITLE
after adding  the latest changes (More optimized files)

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1839]
https://www.joyfulsingers.dk/pages/1/Hvem-er-Joyful-Singers?

Fatal error: Cannot redeclare infusion_exists() (previously declared in /home/helmuth/public_html/includes/infusions_include.php:123) in /home/helmuth/public_html/includes/infusions_include.php on line 123

**Comment by helmuthm** [comment]
reuploaded stable version

**Comment by JoakimFalk** [comment]
Lets keep it open, still a new issue on current Git :)
