### ISSUE TITLE
User's IP is publicly shown

### ISSUE THREAD

**Issue by rimelek** [PHPFusion/PHPFusion#184]
Everyone can see everyone's IP in the forum. Does not matter if they are logged in or not.

Only administrators should see IP addresses.

**Comment by JoakimFalk** [comment]
Actually there is a setting for this in the forum settings, 
Show IP Publicly: Yes / No , if it is Yes, then it should show. But naturally default should be No.

**Comment by rimelek** [comment]
I did not search for this setting because I could not imagine why anyone would want to enable it. It does not work anyway. I turned it off but the IP is still shown.

**Comment by JoakimFalk** [comment]
Nor do I, but I knew it have been around for a while :)

**Comment by meangczac** [comment]
Everything is controlled in the template. I probably missed out reading the settings and show it regardless.
