### ISSUE TITLE
in maintenance mode not possible to login as admin 

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1840]
login for admin has vanished:

![maintenance](https://cloud.githubusercontent.com/assets/9512774/26619170/8e8d1982-45dd-11e7-9204-f2164c05a8fc.png)

**Comment by helmuthm** [comment]
I'm not sure, but it might be connected with this: https://github.com/php-fusion/PHP-Fusion/issues/1839

**Comment by karrak1** [comment]
Is this wrong yet?
It works for me..

**Comment by helmuthm** [comment]
I reuploaded the stable version - now it works

**Comment by JoakimFalk** [comment]
Lets keep it open, still a new issue on current Git :)
