### ISSUE TITLE
panels.inc

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1842]
![panels-inc](https://cloud.githubusercontent.com/assets/9512774/26620274/6c4d9ae0-45e2-11e7-8d60-6d0fb77ff12a.png)

**Comment by karrak1** [comment]
if seo enabled but not turned on panels then error
panels.inc
411 row
wrong line
$script_url = explode("/", $file_path);

it works like this

$script_url = !empty($params) ? explode("/", $file_path) : explode("/", $_SERVER['PHP_SELF']);

**Comment by JoakimFalk** [comment]
@RobiNN1 Is this the fix, https://github.com/php-fusion/PHP-Fusion/commit/2d52ade6fd7e5463afcc8ee9c10169dc37c8c267 ?

**Comment by RobiNN1** [comment]
I not test this. I fixed issue what I found on Atom9 Star City.
