### ISSUE TITLE
Error after adding #1838

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1843]
after adding https://github.com/php-fusion/PHP-Fusion/issues/1838

site is down

Fatal error: Call to undefined method PHPFusion\Locale::__getInstance() in /home/helmuth/public_html/includes/core_functions_include.php on line 1589

**Comment by JoakimFalk** [comment]
Restore same files from 9.0 pack to open the site., at least until the latest Git´s been completed, it is a optimization work in progress.

**Comment by helmuthm** [comment]
I reuploaded the stable version and did overwrite thw files - now site is working again ;)

**Comment by JoakimFalk** [comment]
Lets keep it open, still a new issue on current Git :)

**Comment by meangczac** [comment]
Fatal error: Call to undefined method PHPFusion\Locale::__getInstance() in /home/helmuth/public_html/includes/core_functions_include.php on line 1589

Reupload the whole /includes/

**Comment by meangczac** [comment]
1838 is still in progress. dont merge anything now.
