### ISSUE TITLE
default locale

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1844]
If not English locale file
C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Locale.inc
/fusion/administration/infusions.php?aid=58e6495bb9129f7c **
Sor: 58

include_once(../infusions/joke_panel/locale/English/joke.php): failed to open stream: No such file or directory

AND
include_once(): Failed opening '../infusions/joke_panel/locale/English/joke.php' for inclusion (include_path='C:\xampp\php\PEAR')

**Comment by meangczac** [comment]
In your joke.php
$locale = fusion_get_locale('', JOKE_LOCALE));
