### ISSUE TITLE
fórum undefined iMOD

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1846]
C:\xampp\htdocs\fusion\infusions\forum\classes\forum\forum.php
/fusion/infusions/forum/index.php?viewforum&forum_id=1
Sor: 344
3 mp	

Use of undefined constant iMOD - assumed 'iMOD'

line 340, 342, 344,345,346

AND 

C:\xampp\htdocs\fusion\infusions\forum\templates\forum_main.php
/fusion/infusions/forum/index.php?viewforum&forum_id=2
Sor: 336
3 mp

Undefined index: thread_starter_text

**Comment by meangczac** [comment]
Yes, I am aware of this. Please give me some time before testing the forum again. All codes aims to be faster than the current one. 

There will be a new template as a good reward for ugprading later.
