### ISSUE TITLE
Updating and installing give an error

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1847]
<img width="986" alt="-2" src="https://cloud.githubusercontent.com/assets/16386011/26755240/3c40b082-48ab-11e7-8d75-744c7271abe1.png">

**Comment by ovasclub** [comment]
The problem in the update sits in  maincore.php
231// Set admin login procedures
Authenticate::setAdminLogin();

234 $fusion_dynamics = Dynamics::getInstance();
       $fusion_page_head_tags = &\PHPFusion\OutputHandler::$pageHeadTags;
       $fusion_page_footer_tags = &\PHPFusion\OutputHandler::$pageFooterTags;
       $fusion_jquery_tags = &\PHPFusion\OutputHandler::$jqueryTags;

232// Set admin login procedures
Authenticate::setAdminLogin();

new Dynamics();

$fusion_page_head_tags = &\PHPFusion\OutputHandler::$pageHeadTags;
$fusion_page_footer_tags = &\PHPFusion\OutputHandler::$pageFooterTags;
$fusion_jquery_tags = &\PHPFusion\OutputHandler::$jqueryTags;

And in administration/index.php
103 $submit_data = array();
104$submit_data += \PHPFusion\Admins::getInstance()->getSubmitData();

And the installation still produces an error

**Comment by meangczac** [comment]
Hi I am aware of this, but 9.03 is not for public because I am doing loads of tuning up/down. 
This, is the next upcoming release. Please dont use it yet.

**Comment by karrak1** [comment]
corrected
 undefined function .....form_select(), and infusion_exist()

**Comment by Der-WU** [comment]
Fatal error: Uncaught Error: Class 'PHPFusion\Installer\Dynamics' not found in /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Installer/Install.core.inc:160 Stack trace: #0 /var/www/web1/htdocs/ver9/install.php(22): PHPFusion\Installer\Install_Core::getInstance() #1 {main} thrown in /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Installer/Install.core.inc on line 160

**Comment by karrak1** [comment]
install or update??
Im install work.

**Comment by Der-WU** [comment]
Clean clone and run install. 
I switch php and Check if it 7.1.5 Related.

PHP 5.6.30
Fatal error: Class 'Dynamics' not found in /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Installer/Install.core.inc on line 160

PHP 7.1.5
Fatal error: Uncaught Error: Class 'PHPFusion\Installer\Dynamics' not found in /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Installer/Install.core.inc:160 Stack trace: #0 /var/www/web1/htdocs/ver9/install.php(22): PHPFusion\Installer\Install_Core::getInstance() #1 {main} thrown in /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Installer/Install.core.inc on line 160

**Comment by karrak1** [comment]
I corrected
so I installed.
