### ISSUE TITLE
Unique setting name for infusion

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1848]
Field "settings_name" in %DB_PREFIX%_settings_inf table is unique. Why? There is possible situation when two settings in **different** infusions will have the same name. And user will have problem "duplicate key entry".
I propose two ways:
1. Add autoincrement field which will be primary unique key.
2. Change primary key to unique **pair** settings_name + settings_inf (I think that this is better).

**Comment by meangczac** [comment]
Can I get an example on how do you propose to autoincrement field and pairing is like? Looks like an interesting idea, but I lack example change input.

**Comment by meangczac** [comment]
When error happens like this, error happens. In that case, a wiki guide can be made to resolve such issues. Any seasoned php fusion users can resolve it
