### ISSUE TITLE
Guest commenting without Avatar get error

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1849]
Fatal error: Uncaught TypeError: Argument 1 passed to display_avatar() must be of the type array, null given, called in /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Feedback/Comments.inc on line 1124 and defined in /var/www/web1/htdocs/ver9/includes/theme_functions_include.php:683 Stack trace: #0 /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Feedback/Comments.inc(1124): display_avatar(NULL, '50px', '', false, '') #1 /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Feedback/Comments.inc(1004): PHPFusion\Feedback\Comments->parse_comments_data(NULL, 1) #2 /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Feedback/Comments.inc(148): PHPFusion\Feedback\Comments->get_Comments() #3 /var/www/web1/htdocs/ver9/includes/classes/PHPFusion/Feedback/Comments.inc(137): PHPFusion\Feedback\Comments::setInstance('_A2') #4 /var/www/web1/htdocs/ver9/includes/comments_include.php(40): PHPFusion\Feedback\Comments::getInstance(Array, '_A2') #5 /var/www/web1/htdocs/ver9/infusions/articles/classes/articles/articles.php(560): in /var/www/web1/htdocs/ver9/includes/theme_functions_include.php on line 683

Set a Default Avatar for guests postings!?

**Comment by meangczac** [comment]
The array must return a non blank.
````
display_avatar(NULL, '50px', '', false, '');
````
This one is not ok. If NULL is array, then should be no error.
