### ISSUE TITLE
RSS Errors

### ISSUE THREAD

**Issue by ALTUN69** [PHPFusion/PHPFusion#1851]
These errors appear in the error log.

![2017-06-09](https://user-images.githubusercontent.com/8268248/26983994-dc0de0b2-4d3d-11e7-981f-ed8c75d63c4c.png)

![2017-06-09 1](https://user-images.githubusercontent.com/8268248/26984053-1ae02bba-4d3e-11e7-9603-569056461bef.png)

![2017-06-09 2](https://user-images.githubusercontent.com/8268248/26984091-437b9cf8-4d3e-11e7-9557-3f59a9e7fb46.png)

**Comment by Der-WU** [comment]
It is Related to a Missing locale in the global.php 
Please Check and Add zur Missing like in your locale. 

Greatz

**Comment by karrak1** [comment]
corrected.
