### ISSUE TITLE
Do not turn off the panels on the pages

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1853]
Do not turn off the panels on the pages
<img width="255" alt="-2" src="https://user-images.githubusercontent.com/16386011/27011017-d5f51744-4ed3-11e7-8f7a-5da26f1d59b2.png">

**Comment by JoakimFalk** [comment]
Try the new panels \includes\classes\PHPFusion\Panels.inc

**Comment by ovasclub** [comment]
All files from v9.03

**Comment by JoakimFalk** [comment]
Did this work with 9.0 Stable release for you?
One small change was done that worked in 9.03 for others.
