### ISSUE TITLE
Error report in /infusions/forum/index.php and templates.php

### ISSUE THREAD

**Issue by ALTUN69** [PHPFusion/PHPFusion#1854]
![2017-06-12 1](https://user-images.githubusercontent.com/8268248/27015562-ba122570-4f10-11e7-8d3a-8265dd9a1cec.png)
![2017-06-12](https://user-images.githubusercontent.com/8268248/27015561-ba0f8126-4f10-11e7-883f-c98630114a19.png)

**Comment by meangczac** [comment]
Wait up bro, I'm still fixing the template. The while and for loop requires sub items at the moment is making me a headache with nested html file requirement. I want it flat.

**Comment by meangczac** [comment]
I'll check on isset errors after I do everything. I programmed a lightweight template class to handle what I need to reduce a lot of template files and functions for the forum.

**Comment by ALTUN69** [comment]
I just wanted to report the errors.
Thanks ok.

**Comment by meangczac** [comment]
Hi @ALTUN69 , please check if there are still any errors as of last git https://github.com/php-fusion/PHP-Fusion/commit/decf6793701235a2b446fefd50016685dade4d94
