### ISSUE TITLE
Forum Threads panel

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1857]
Array
(
    [0] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\infusions\forum_threads_panel\forum_threads_panel.php
            [line] => 22
            [function] => include
        )

    [1] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Panels.inc
            [line] => 295
            [args] => Array
                (
                    [0] => F:\xampp\htdocs\PHP-Fusion\infusions\forum_threads_panel\forum_threads_panel.php
                )

            [function] => include
        )

    [2] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\themes\templates\footer.php
            [line] => 23
            [function] => getSitePanel
            [class] => PHPFusion\Panels
            [object] => PHPFusion\Panels Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\infusions\forum\index.php
            [line] => 33
            [args] => Array
                (
                    [0] => F:\xampp\htdocs\PHP-Fusion\themes\templates\footer.php
                )

            [function] => require_once
        )

)

RSS Fedds panel 

Array
(
    [0] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\infusions\rss_feeds_panel\rss_feeds_panel.php
            [line] => 24
            [function] => include
        )

    [1] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Panels.inc
            [line] => 295
            [args] => Array
                (
                    [0] => F:\xampp\htdocs\PHP-Fusion\infusions\rss_feeds_panel\rss_feeds_panel.php
                )

            [function] => include
        )

    [2] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\themes\templates\footer.php
            [line] => 23
            [function] => getSitePanel
            [class] => PHPFusion\Panels
            [object] => PHPFusion\Panels Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => F:\xampp\htdocs\PHP-Fusion\home.php
            [line] => 26
            [args] => Array
                (
                    [0] => F:\xampp\htdocs\PHP-Fusion\themes\templates\footer.php
                )

            [function] => require_once
        )

)

**Comment by karrak1** [comment]
corrected
