### ISSUE TITLE
PHP-Fusion 9 available to install

### ISSUE THREAD

**Issue by t0msk** [PHPFusion/PHPFusion#1861]
Hello, I was using PHP-Fusion for long time (I started with PHP-Fusion 6), but now I would like to create a website that will runs on PHP-Fusion, I see that official release is PHP-Fusion 7 on the main website, but I would like to skip version 7 and install PHP-Fusion 9, when will be PHP-Fusion 9 released?

Because on the main page (github) is "NOTICE: 9.03 IS NON INSTALLABLE AND IS CURRENTLY UNDER DEVELOPMENT. DO NOT INSTALL."

Does it mean that there are security holes? Or something doesn't work? If there is only trivially issues, it is ok, I can fix it.

**Comment by RobiNN1** [comment]
PHP Fusion 9 is released https://www.php-fusion.co.uk/news.php?readmore=614
Here is next version 9.03 (9.1) -  under development

**Comment by t0msk** [comment]
Oh great :) thanks for reply, but it is a 9.0 and in development is 9.3, so is 9.2 ready?

And is there any benchmark, I mean like render time vs PHP-Fusion 7 :)
