### ISSUE TITLE
Tutorial for PHP-Fusion 9?

### ISSUE THREAD

**Issue by t0msk** [PHPFusion/PHPFusion#1862]
Hello,
I was using PHP-Fusion long time ago (PHP-Fusion 6) and code was very clear.

But I downloaded PHP-Fusion 9 and I am extremely confused. Hah? Everything changed. Is there any tutorial or documentation to understand code of PHP-Fusion 9? Like what are widgets? Why there is so many files in infusion folders etc.. I am really confused :/

**Comment by t0msk** [comment]
Halo?

**Comment by RobiNN1** [comment]
Visit Official Documentation https://www.php-fusion.co.uk/infusions/wiki/documentation.php?page=212
