### ISSUE TITLE
PDOMySQL.inc - Column not found: 1054 Unknown column 'a.attach_id' in 'where clause'

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1865]
PDOMySQL.inc
/site/infusions/forum/tags.php?tag_id=6&time=today&type=poll&sort=reply
Line: 71
2 minutes ago 	

Severity : Notice generated by user using trigger_error() function
Query Error: SELECT count(t.thread_id) 'thread_max_rows', count(a1.attach_id) 'attach_image', count(a2.attach_id) 'attach_files' FROM fusion62825_forum_threads t LEFT JOIN fusion62825_forums tf ON tf.forum_id = t.forum_id INNER JOIN fusion62825_users tu1 ON t.thread_author = tu1.user_id
#LEFT JOIN fusion62825_users tu2 ON t.thread_lastuser = tu2.user_id LEFT JOIN fusion62825_forum_posts p1 ON p1.thread_id = t.thread_id and p1.post_id = t.thread_lastpostid LEFT JOIN fusion62825_forum_polls p ON p.thread_id = t.thread_id
#LEFT JOIN fusion62825_forum_votes v ON v.thread_id = t.thread_id AND p1.post_id = v.post_id LEFT JOIN fusion62825_forum_attachments a1 on a1.thread_id = t.thread_id AND a1.attach_mime IN ('image/jpg,image/jpeg,image/gif,image/png,image/tiff,image/tif,image/x-ms-bmp,image/x-icon') LEFT JOIN fusion62825_forum_attachments a2 on a2.thread_id = t.thread_id AND a2.attach_mime NOT IN ('image/jpg,image/jpeg,image/gif,image/png,image/tiff,image/tif,image/x-ms-bmp,image/x-icon') WHERE CONCAT(t.thread_tags, '.') like '%6%' AND t.thread_hidden='0' AND tf.forum_access = 0 AND (t.thread_lastpost >= 1498348800)AND (a.attach_id IS NULL or attach_count ='0') AND thread_poll ='1' GROUP BY tf.forum_id
Stack Trace:
#0 /var/www/vhosts/aliencollectors.com/httpdocs/site/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('? SELECT...')
#1 /var/www/vhosts/aliencollectors.com/httpdocs/site/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('? SELECT...', Array)
#2 /var/www/vhosts/aliencollectors.com/httpdocs/site/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('? SELECT...', Array)
#3 /var/www/vhosts/aliencollectors.com/httpdocs/site/infusions/forum/classes/forum/tags.php(144): dbquery('? SELECT...')
#4 /var/www/vhosts/aliencollectors.com/httpdocs/site/infusions/forum/classes/forum/tags.php(91): PHPFusion\Forums\ThreadTags::get_tag_thread('6', Array)
#5 /var/www/vhosts/aliencollectors.com/httpdocs/site/infusions/forum/classes/server.php(464): PHPFusion\Forums\ThreadTags->set_TagInfo(true)
#6 /var/www/vhosts/aliencollectors.com/httpdocs/site/infusions/forum/tags.php(30): PHPFusion\Forums\ForumServer::tag(true, true)
#7 {main}
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'a.attach_id' in 'where clause'

**Comment by JoakimFalk** [comment]
Is this current revison or does it come from 9.0?

**Comment by karrak1** [comment]
Is this current.
