### ISSUE TITLE
I can't start install

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1866]
Why I can't start install new PHP FUSION 9.02?

HTTP ERROR 500

Please visit: http://www.tdk.tomaszow-lubelski.com.pl/php/install.php

**Comment by ovasclub** [comment]
Possible reason: PHP settings on hosting.
Requirements for this version
- PHP 5.5.08 or higher

**Comment by kosiorski-eu** [comment]
Thanks!
