### ISSUE TITLE
Rewrite Driver Errors

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1871]
htdocs/PHP-Fusion/includes/classes/PHPFusion/Rewrite/RewriteDriver.inc
htdocs/PHP-Fusion/news/86/test
Line: 523
Undefined offset: 401

**Comment by RobiNN1** [comment]
Another problem, url that contains characters: '; ,[] {}  and other special chars need replace with -  because it redirects to a broken address and shows the error above.

RewriteDriver.inc
/infusions/forum/index.php?viewforum=&forum_id=13&thread_rowstart=15
Line: 523
Undefined offset: 401

**Comment by JoakimFalk** [comment]
@RobiNN1 https://github.com/php-fusion/PHP-Fusion/commit/0cdd1bbdd0bf889073bf2d8e70fd86f83e7d97ba

**Comment by JoakimFalk** [comment]
idk if this fixes the notices you had, but your redirect problems should be gone.
Tested on Gallery, 
![image](https://user-images.githubusercontent.com/4210004/39590255-ab82bc4a-4f00-11e8-9216-8a8733896085.png)

Result, 

![image](https://user-images.githubusercontent.com/4210004/39590238-9ba638b0-4f00-11e8-87b5-5f1fcf5e1c0b.png)

**Comment by RobiNN1** [comment]
Tested on CzechNSS, still same issues
RewriteDriver.inc
/infusions/forum/index.php?viewforum=&forum_id=13&thread_rowstart=15
Line: 510
Undefined offset: 401

Maybe Forum rewrites issue

![ddefrgftvyh](https://user-images.githubusercontent.com/11664877/39591716-d72b23ce-4f04-11e8-9fb9-6f70b2a4d7c9.png)

**Comment by JoakimFalk** [comment]
But it fixed the redirect issue?

**Comment by RobiNN1** [comment]
yes

**Comment by RobiNN1** [comment]
Issue with redirecting the forum if you try to delete post is still here. 
ERR_TOO_MANY_REDIRECTS

Something is wrong with this redirect  https://github.com/php-fusion/ci-Forum/blob/c87814a2c937e650d61b6ea1722220ffbf7dd962/classes/mods.php#L723
