### ISSUE TITLE
Locales index missing

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1872]
```
  echo "<th class='col-xs-2'>".$locale['language']."</th>\n";
  echo "<th class='col-xs-1'>".$locale['status']."</th>\n";
```
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38725&pid=203118#post_203118

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/blob/9.03/locale/English/global.php#L412
https://github.com/php-fusion/PHP-Fusion/blob/9.03/locale/English/global.php#L438
