### ISSUE TITLE
Blog dosent work on new installation

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1873]
i have download the newest version from here and create a new database and complete new installation (complete clean)

but the blog dosent work. I see the categories and also the blog in admin area but i cant write anything or set in the seetings. 

when i click in settings on ADD a BLOG i jump to the viewpage.php?page_id=1
when i click an CREATE A CATEGORY its the same

Site Host: *
Site Path: * 
 are correct

**Comment by UnrealCatze** [comment]
i have change the startsite in main settings to HOME (home.php) but the same ... when i try to make a catogory in forum, blog or articles i would redirect to home site ... i can do nothing

**Comment by karrak1** [comment]
Try it now
