### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1876]
i use this:

```
				echo form_datepicker('figure_pubdate', $locale['figurelib/admin/figurelib.php_047'], $data['figure_pubdate'],
				array(
					"placeholder" => $locale['figurelib/admin/figurelib.php_048'],
					"inline" 		=> true,
					"width"       => "250px"
				)
				);	
```

but is see only always 2001 (january)
When i use this: echo $data['figure_pubdate']; i see the correct date

someone is wrong

**Comment by RobiNN1** [comment]
echo $data['figure_pubdate']; you see as 1502139728 or 14.9.2017?  Date must be saved as datestamp not as a formatted date.
