### ISSUE TITLE
Administration > Album Action > Delete album is non working.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#188]
Administration > Album Action > Delete album is non working.

**Comment by meangczac** [comment]
![album_delete](https://cloud.githubusercontent.com/assets/4078041/9650018/abbe140a-522f-11e5-93b2-2fb9d359df19.gif)

I looked thru codes, find nothing irregular... need instructions to replicate.

**Comment by meangczac** [comment]
OK found it. It will not delete when there are photos inside the album.
