### ISSUE TITLE
Article Date not correct

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1883]
Hello Developers,

I wrote in the own PF 9.0.0 portal the first article and see that unfortunately the date is not displayed correctly. It shows me the year 1970, although I set the current date in the backend.

Can you please check this or resolved.

Thanks in advance.

![php-fusion-9-articles-date-error](https://user-images.githubusercontent.com/7885632/30234261-c47f33a0-94fb-11e7-9dcb-d1ae21c18d61.jpg)

**Comment by RobiNN1** [comment]
1.1. 1970 shows only if date is empty
