### ISSUE TITLE
PF 9.0.3 Forum Categories in the Frontend not correct - look this Screenshot

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1889]
Hello Developers,

I use the PF 9.0.3 version at https://bloggertips.guru and in the forum it does not show me the forum categories that I created.

Please look at this screenshot or directly in the portal with me in the forum there.

It is always shown PHP Fusion 9 categories, but not the appropriate forum category.

Is it a bug or how can I fix it?

Thanks in advance.

P.S. I have added two German translations to forum.php because it was still in English.

![phpfusion903-error-forum-categories](https://user-images.githubusercontent.com/7885632/30539327-31d05510-9c72-11e7-9b9d-dfe8affef761.jpg)

**Comment by meangczac** [comment]
Add me on Skype - hien.phpfusion, and I need an export of your DB_FORUMS sql data to help me identify what went wrong.

I'm betting on template, but is just my rough guess. I need to see the data to be sure. Thanks.

**Comment by ghost** [comment]
Hi Frederick,

I just added you to the contacts in Skype and now wait for your approval. Then I send you the SQL file via Skype.

Thank you for watching this.
