### ISSUE TITLE
locale.inc gives error

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1903]
How to solve this one?

![locale-inc-1](https://user-images.githubusercontent.com/9512774/32455343-4a6fa70c-c322-11e7-8e5e-a691492a0b58.png)
![locale-inc-2](https://user-images.githubusercontent.com/9512774/32455345-4ad1e368-c322-11e7-8ddb-38e94f27c239.png)
![locale-inc-3](https://user-images.githubusercontent.com/9512774/32455350-4c084704-c322-11e7-8655-6bbaf30188df.png)

**Comment by meangczac** [comment]
Danish/search/\1.php?

**Comment by helmuthm** [comment]
error is still there and a lot of them - would you like to have access to see for yourself?

**Comment by karrak1** [comment]
Denish forum locale incomplete

**Comment by helmuthm** [comment]
thx karrak1 - after updating forum.php the error has gone :-)
