### ISSUE TITLE
not work multilang installer

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1909]
![capture_001_15112017_095727](https://user-images.githubusercontent.com/16163102/32827162-782b6918-c9eb-11e7-889f-076cc8ca14e5.jpg)

locale file good..

**Comment by JoakimFalk** [comment]
In the screen I see 2 languages on the site links, where does it fail?

**Comment by karrak1** [comment]
Yes. But one language link_name (all multilang table similar)

**Comment by JoakimFalk** [comment]
Ok, so it does not read in the new Locale for all new languages selected.

**Comment by karrak1** [comment]
yes only reads the default language
