### ISSUE TITLE
Error Infusing Infusions During New Install

### ISSUE THREAD

**Issue by kreativmind** [PHPFusion/PHPFusion#1910]
I have tried v9.0 and now v9.03 and both give me error only the two version reference different lines of code but for the same reason. Therefore I can start the install but not complete it. If I choose to click on Finish Configuration without infusing, it will finish the install, but the user created doesn't exists or anything because it didn't write anything to the database due to the error. I am thinking it's possibly something to do with STRICT_TRANS_TABLES. If it is, it's unfortunate as my hosting provider doesn't allow me to turn off on Shared Hosting Plan.

v9.0 errors:
Notice: Field 'link_icon' doesn't have a default value @ INSERT INTO tmag_site_links (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('News', 'infusions/news/news.php', '0', '2', '0', '2', '1', 'English') in /includes/classes/PHPFusion/Database/Driver/MySQLi.inc on line 187

Notice: Field 'link_icon' doesn't have a default value @ INSERT INTO tmag_site_links (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('Submit News', 'submit.php?stype=n', -101, '1', '0', '13', '1', 'English') in /includes/classes/PHPFusion/Database/Driver/MySQLi.inc on line 187

v9.03 errors:
Notice: Field 'link_icon' doesn't have a default value @ INSERT INTO tmag_site_links (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('News', 'infusions/news/news.php', '0', '2', '0', '2', '1', 'English'Wink in /includes/classes/PHPFusion/Database/Driver/MySQLi.inc on line 201

Notice: Field 'link_icon' doesn't have a default value @ INSERT INTO tmag_site_links (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('Submit News', 'submit.php?stype=n', -101, '1', '0', '13', '1', 'English'Wink in /includes/classes/PHPFusion/Database/Driver/MySQLi.inc on line 201

**Comment by ovasclub** [comment]
On openserver it is established, the truth with an error that that the user's password coincides with the administrative one. Check the PHP version on the hosting.

**Comment by kreativmind** [comment]
There is no user created and written into the database as it didn't write to the users table. The php is 5.6.31. Any other ideas?

**Comment by RobiNN1** [comment]
If is possible, try PDO driver instead MySQLi.

**Comment by kreativmind** [comment]
Not sure why I didn't do that the first time. It infuses now using PDO during the install process. Thanks for the insight @RobiNN1

**Comment by RobiNN1** [comment]
@FrederickChan also does not work the DB backup in administration with MySQLi driver, but with PDO works well.

**Comment by RobiNN1** [comment]
#1949
