### ISSUE TITLE
HUGE BUG in Blog infusion

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1912]
I just found GIGANTIC bug in blog infusions..

When I add some blog item in admin panel and select more than one categories. Sometimes blogs items will not display in list. IT DEPENDS of order categories what I choose. 

**For example:**
Im on home page, I go to blog category with ID 26. 
I dont see blog item with blog_cat="2,26", but if I change order categories to blog_cat="26,2" it will show normally in category ID 26. 

Simillary situation is when I go to second category (ID 2) the same blog item.
I dont see the blog item when order categories look like this "26,2", but if I reverse categories to "2,26" it will display normal.

**Comment by meangczac** [comment]
Thank you for the find. Will fix as soon as possible. 

Regards, Frederick

**Comment by kosiorski-eu** [comment]
Ok, I think it works better, but not perfectly yet. 
**Please look at this example.**

I have blog item with cats  ID "5.38"

Yeah, when I go to cat with ID "5" or ID "38" I see this blog item, so it works well. 
BUT when I choose cat ID "3" or cat ID "8" it will display this blog item me too.

Your solutions will works well only for cats with one character. The numbers must be separated with another way, beacause when some category of blog will have ID = "234567". Then the blog item which include to this category will display too respectively on categories with IDs "2", "3", "4", "5", "6" and "7" for sure. 

Better results give me sql query 
`blog_cat LIKE '%".$_GET['cat_id']."' OR blog_cat LIKE '".$_GET['cat_id']."%'`
But still not perfectly.

**Comment by meangczac** [comment]
I’m using the in_group concat with delimiter of “,” ? See in_group() function. Perhaps delimiter is set wrongly, but I’ve tried it and it works. I’ll go at it another round. 

Regards, Frederick
