### ISSUE TITLE
Content on Custom Pages not visible

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1917]
Hi Developers,

please check the Custom Pages again, because the content on Pages will not be displayed. I installed the last branch of Github and created two pages. In the Navagion these pages are already with me, but the content is not displayed.

That would be my issue for this moment.

Thanks in advance.

**Comment by meangczac** [comment]
Test context:

> Test page 1Page 2

URL: your-server.com/viewpage.php?page_id={page_id}

Navigation works.

**Comment by ghost** [comment]
Hi @FrederickChan ,

I can confirm well that the navigation links are displayed. Unfortunately, the content of the static pages is not displayed, for whatever reason.

I uploaded the last branch of Github again.

As an example, you can see this under https://phpfusion.hro-mv.de/pages/1/Impressum .

Maybe you have an idea what I can do or debug or something else.

Thank you!
