### ISSUE TITLE
V.9.0 , downloads

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#1918]
V.9.0 - https://www.phpfusion.cz
Problems with downloads.
1 / The HomePage downloads are displayed and downloaded correctly.
2 / But on the "Downloads" section of https://www.phpfusion.cz/downloads you can not see the link:
https://www.phpfusion.cz/infusions/downloads/downloads.php?cat_id=36&download_id=19
https://www.phpfusion.cz/infusions/downloads/downloads.php?cat_id=31&download_id=77

**Comment by RobiNN1** [comment]
All works.


@Kvido funguje to, čo presne nejde? Myslíš to, že neprekladá adresy na pekne url? Z /infusions/downloads/ na /downloads/ ?

**Comment by Kvido** [comment]
After repairs, RobiNN downloads are perfect in versions 9.0 and 9.03!
