### ISSUE TITLE
Need to rework repos

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1919]
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

We will impose this on:
/locale/
/infusions/

User fields and its locale will be restructured 

SEO drivers must go to each infusion and declared at infusion_db file

**Comment by RobiNN1** [comment]
Such as this?
Permalinks:
Articles SEO rewrite move to /infusions/articles/rewrites
and in Premalinks admin load rewrites from default /includes/rewrites and from infusions/INFUSION_NAME/rewrites

New folder structure:
/includes/rewrites/REWRITE_NAME
 - /locale/LANGUAGE.php
 - rewrite_include.php
 - rewrite_info.php

 /infusions/INFUSION_NAME/rewrites
 - /locale/LANGUAGE.php
 - rewrite_include.php
 - rewrite_info.php

User Fields:
In /includes/user_fields/ create folder user_facebook and user_facebook_include.php, user_facebook_include_var.php, icon and locale  move to them to a folder

New folder structure:
/includes/user_fields/USER_FIELD_NAME
 - /locale/LANGUAGE.php
 - include.php
 - include_var.php
 - icon.png

And also search includes move to each infusion.

My idea is move related components to infusion folder, it's better for developers.

Maybe to reduce files:
/images/flags
/images/small_flag

/includes/classes/PHPMailer/language
/includes/dynamics/assets/datepicker/locale
/includes/dynamics/assets/fileinput/js/locales
/includes/dynamics/assets/select2

move to new repo and keep only english locale.

**Comment by meangczac** [comment]
Yes, but we do a step a time. That you have suggested is related to folder structure of the release package. 

What I also suggested is :

Infusions/news ——> stand-alone repository on GitHub. (I.e news.git) But is available when you download the main project (I.e PHP-fusion.git) 

The roadmap service I am coding now shall support by “per project basis” and therefore supports its own issues, milestones, branch. 
Therefore allowing people to work or fork  on infusions itself.I hope to work this out soon. But let me experiment it first before I execute this part. See the link I provided in the first post. 

Regards, Frederick

**Comment by RobiNN1** [comment]
Do you mean this or something similar?
![qasxdfcgt](https://user-images.githubusercontent.com/11664877/39826533-511acf7c-53b5-11e8-943c-773bcdb049e3.png)

https://github.com/RobiNN1/PHP-Fusion-Themes

After click to php-fusion-Themes@b2275e8 will be shown content from php-fusion/Themes

`git submodule add git@github.com:php-fusion/Themes.git php-fusion-Themes`

**Comment by meangczac** [comment]
Yes, how do you achieve that? We need the whole of 
/themes/ into another repo, and the 
/locale/ folder too.
/infusions/folder too

This way this repo only core only.

**Comment by RobiNN1** [comment]
Themes - Maybe keep one or two and other themes move to https://github.com/php-fusion/Themes repo
Locales - I think it's okay
Infusions - keep only necessarily

**Comment by meangczac** [comment]
Ok, lets' start moving Themes. Can you set it up?

Move all Themes to Theme Repo and Link the repo to /themes/

I'm not sure how to do it on Storm

**Comment by RobiNN1** [comment]
I try to do it on another GitHub account, but I still have some problems with updating repos.

**Comment by meangczac** [comment]
@php-fusion/core-developers , I need everyone please join into Discord chat for updates and team discussions. We have 40% on board only. Please, join in, you're automated as "Core Developer" promotion immediately.

Click this link now: https://discord.gg/PhF4XTz

@karrak1

**Comment by meangczac** [comment]
As of today, @RobiNN1 and me have started to rework the repos into submodules. 

https://blog.github.com/2016-02-01-working-with-submodules/

The term **ci** Stands for Core Infusion
----

The forum is now on <a href='https://github.com/php-fusion/ci-Forum/tree/2.0'>ci-Forum</a> repository. 

Working on the folder itself will bind a new VCS root, and you will need to push to the correct VCS. 

As a thumb rule, I've set the latest stable is "Master" as the Submodule alias of the main repository, but @php-fusion/core-developers  will work on latest version numbers.  i.e. For Forum, it's Branch 2.0.  

As a result of the change, there was 2 VCS root in the editor.

![capture](https://user-images.githubusercontent.com/4078041/42125978-e76568ae-7cb2-11e8-9d8b-67d85c529c0a.JPG)

When pushing, just submit to Forum if you are working with forum. You're not needed to push to main repository anymore.

Example of VCS root to choose from when pushing:
![capture2](https://user-images.githubusercontent.com/4078041/42125979-f401869c-7cb2-11e8-8331-37d4b8d77adf.JPG)

We will be versioning the CIs, along with advantage of not stabilizing the core software i.e. PHP-Fusion while developing on new stuffs.

**Comment by meangczac** [comment]
I will close this issue when everything is done.

**Comment by meangczac** [comment]
Let's change Permalink structure next. I will point to each infusions/xxxx/rewrite folder and set an example. Please help me out after that.

**Comment by RobiNN1** [comment]
@karrak1  please join https://discord.gg/PhF4XTz

**Comment by Ardakilic** [comment]
Guys, while on the subject, have you considered making such submodules as composer dependencies ? This way, it'd be easier to update for everyone and people don't need to hunt differences or re-upload everything upon update. Also, 3rd party assets (such as bootstrap, TinyMCE etc. etc.) will be easier to update.

E.g: Popular PHP Frameworks such as Symfony and Laravel use this approach, and call the files from namespaces.

Composer downloads all files into `vendor` folder, but if you want to have custom paths such as `./forum`, `./gallery` etc. it's possible with `composer/installers` package, [see this link](https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md).

Sorry, I can't be of much help because of my life tempo as an active developer, but in the long run, I'm sure this'll benefit for everyone both on time and flexibility. Not to mention, you can have different tests for individual repositories, and individual repositories may have their own dependencies.

**Comment by meangczac** [comment]
@Ardakilic , composer comes last because we still have new files to introduce next patch.
