### ISSUE TITLE
A new empty album is not linked to be entered

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#192]
Once content is in the album the direct link works.

![right-album-not-clickable](https://cloud.githubusercontent.com/assets/4210004/9600217/0fdb735c-509a-11e5-94f3-04942698b545.png)

**Comment by meangczac** [comment]
This is intentional. There is no purpose to enter a blank album in admin. Adding photo is done right on top already

**Comment by JoakimFalk** [comment]
Ah, I figured it was a glitch since that is how old albums worked. But it is fine. I leave it closed.
