### ISSUE TITLE
#3 /home/buhlmode/public_html/v9/infusions/downloads/downloads.php(283):

### ISSUE THREAD

**Issue by jonathanwichter** [PHPFusion/PHPFusion#1927]
Query Error: SELECT d., dc., tu.user_id, tu.user_name, tu.user_status, tu.user_avatar , tu.user_level, tu.user_joined, IF(SUM(tr.rating_vote)>0, SUM(tr.rating_vote), 0) AS sum_rating, COUNT(tr.rating_item_id) AS count_votes, MAX(d.download_datestamp) as last_updated FROM fusionc7E6d_downloads d INNER JOIN fusionc7E6d_download_cats dc ON d.download_cat=dc.download_cat_id LEFT JOIN fusionc7E6d_users tu ON d.download_user=tu.user_id LEFT JOIN fusionc7E6d_ratings tr ON tr.rating_item_id = d.download_id AND tr.rating_type='D' WHERE download_cat_language='English' AND download_visibility = 0 AND download_cat = '5' GROUP BY d.download_id ORDER BY count_comment DESC LIMIT 0,15

**Comment by jonathanwichter** [comment]
Why did you close it with out helping me?

Thanks,
John

**Comment by RobiNN1** [comment]
Github have auto-closing function. Click to https://github.com/php-fusion/PHP-Fusion/commit/13e72f8f0064b109de14a2333dfa00b2c2fd32f3 to see what is fixed or see latest commit.

And please second time copy entire text from blue box from Error log. Or create screenshot like this https://github.com/php-fusion/PHP-Fusion/issues/1842

**Comment by jonathanwichter** [comment]
PDOMySQL.inc /v9/infusions/downloads/downloads.php?cat_id=5&type=comments Line: 71 3 hours ago	New Solved Ignored Delete Severity : Notice generated by user using trigger_error() function Query Error: SELECT d., dc., tu.user_id, tu.user_name, tu.user_status, tu.user_avatar , tu.user_level, tu.user_joined, IF(SUM(tr.rating_vote)>0, SUM(tr.rating_vote), 0) AS sum_rating, COUNT(tr.rating_item_id) AS count_votes, MAX(d.download_datestamp) as last_updated FROM fusionc7E6d_downloads d INNER JOIN fusionc7E6d_download_cats dc ON d.download_cat=dc.download_cat_id LEFT JOIN fusionc7E6d_users tu ON d.download_user=tu.user_id LEFT JOIN fusionc7E6d_ratings tr ON tr.rating_item_id = d.download_id AND tr.rating_type='D' WHERE download_cat_language='English' AND download_visibility = 0 AND download_cat = '5' GROUP BY d.download_id ORDER BY count_comment DESC LIMIT 0,15 Stack Trace: #0 /home/buhlmode/public_html/v9/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('SELECT d.*, dc....') #1 /home/buhlmode/public_html/v9/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT d.*, dc....', Array) #2 /home/buhlmode/public_html/v9/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT d.*, dc....', Array) #3 /home/buhlmode/public_html/v9/infusions/downloads/downloads.php(249): dbquery('SELECT d.*, dc....') #4 {main} Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count_comment' in 'order clause'

**Comment by jonathanwichter** [comment]
PDOMySQL.inc /v9/infusions/downloads/downloads.php?type=comments Line: 71 5 hours ago	New Solved Ignored Delete Severity : Notice generated by user using trigger_error() function Query Error: SELECT d., dc., tu.user_id, tu.user_name, tu.user_status, tu.user_avatar , tu.user_level, tu.user_joined, IF(SUM(tr.rating_vote)>0, SUM(tr.rating_vote), 0) AS sum_rating, COUNT(tr.rating_item_id) AS count_votes, max(d.download_datestamp) as last_updated FROM fusionc7E6d_downloads d INNER JOIN fusionc7E6d_download_cats dc ON d.download_cat=dc.download_cat_id LEFT JOIN fusionc7E6d_users tu ON d.download_user=tu.user_id LEFT JOIN fusionc7E6d_ratings tr ON tr.rating_item_id = d.download_id AND tr.rating_type='D' WHERE dc.download_cat_language = 'English' AND download_visibility = 0 GROUP BY d.download_id ORDER BY count_comment DESC LIMIT 0,15 Stack Trace: #0 /home/buhlmode/public_html/v9/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('SELECT d.*, dc....') #1 /home/buhlmode/public_html/v9/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT d.*, dc....', Array) #2 /home/buhlmode/public_html/v9/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT d.*, dc....', Array) #3 /home/buhlmode/public_html/v9/infusions/downloads/downloads.php(283): dbquery('SELECT d.*, dc....') #4 {main} Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count_comment' in 'order clause'

**Comment by RobiNN1** [comment]
*duplicate comment deleted
This issue has been fixed https://github.com/php-fusion/PHP-Fusion/commit/233132b0f68d2d552ec9a52737f72ad29cfff2b9#diff-b962fb8e32a7b99f2e285c6765e1fa2c

**Comment by jonathanwichter** [comment]
So do I replace the downloads.php file with the one one here?

**Comment by RobiNN1** [comment]
No, if you use 9.0 stable (probably you use it)

**Comment by jonathanwichter** [comment]
I am using 9.0 but then how do it fix it.

**Comment by RobiNN1** [comment]
Reupload https://raw.githubusercontent.com/php-fusion/PHP-Fusion/233132b0f68d2d552ec9a52737f72ad29cfff2b9/infusions/downloads/downloads.php

**Comment by jonathanwichter** [comment]
so i am rewriting over the old downloads.php file on my server then.

**Comment by jonathanwichter** [comment]
Sorry this is my first time learning all this new code with 9

**Comment by jonathanwichter** [comment]
On the Septenary theme on the main page there is white space between the content and the footer. All the other pages are fine only showing up on home.php 

<img width="1537" alt="screen shot 2018-01-04 at 11 18 09 am" src="https://user-images.githubusercontent.com/35083828/34573003-f800f190-f140-11e7-9849-ddb736942b1d.png">

**Comment by RobiNN1** [comment]
Delete this line https://github.com/php-fusion/PHP-Fusion/blob/9.02/themes/Septenary/styles.css#L642

**Comment by jonathanwichter** [comment]
That shows the same as mine on that line. That as the first place I went too.

**Comment by jonathanwichter** [comment]
<img width="1321" alt="screen shot 2018-01-04 at 11 34 26 am" src="https://user-images.githubusercontent.com/35083828/34573761-3e408916-f143-11e7-8c58-fe2854069918.png">

**Comment by jonathanwichter** [comment]
the gap is only on the main page all the other pages shows normal.
