### ISSUE TITLE
Debonair theme widget enable generate error

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#193]
Fatal error: Cannot redeclare opentable() (previously declared in /themes/admin_templates/Venus/includes/functions.php:30) in /themes/debonair/functions.php on line 84

**Comment by meangczac** [comment]
This should not be debonair. Maybe related to presets. Try scan and see if you have presets on Debonair. Delete the presets if any and see if the error occur or not. 

Lets not debug the wrong file. lol
