### ISSUE TITLE
Theme Septenary: does not work Sub-header

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1930]
Theme Septenary: does not work Sub-header.
Sub-header works when you exit the admin panel. When you enter, it turns off. You can go to the admin panel via the navigation panel.
  In FusionTheme and Bootstrap  everything is fine.
Tested on Open Server

![-2](https://user-images.githubusercontent.com/16386011/34649734-f2e2b1d0-f3de-11e7-911d-34e8e0e7cdb0.jpg)

**Comment by ovasclub** [comment]
I found the problem in a file **themes/Septenary/includes/components.php**
`440  $footer_errors = showFooterErrors();`
switched off
`440  //$footer_errors = showFooterErrors();`

**Comment by RobiNN1** [comment]
It's okey https://github.com/php-fusion/PHP-Fusion/blob/9.03/themes/Septenary/includes/components.php#L440

**Comment by ovasclub** [comment]
The problem is not solved. It appears if creating a new panel
