### ISSUE TITLE
Footer on main page

### ISSUE THREAD

**Issue by jonathanwichter** [PHPFusion/PHPFusion#1931]
Their is a space between the content box and the footer box. Only showing home.php the other pages are fine. Already checked the css file and the footer space is set 50x. already confirmed that is correct. Here is a photo to show what I am talking about.
<img width="2073" alt="screen shot 2018-01-07 at 10 59 11 am" src="https://user-images.githubusercontent.com/35083828/34651133-04685f4e-f39a-11e7-866c-671704b00ba7.png">

**Comment by RobiNN1** [comment]
Change margin-top: 50px to margin-top: 0;
https://github.com/php-fusion/PHP-Fusion/blob/9.03/themes/Septenary/styles.css#L656

On other pages is margin-top reseted by this line
https://github.com/php-fusion/PHP-Fusion/blob/9.03/themes/Septenary/includes/components.php#L377

**Comment by jonathanwichter** [comment]
thanks, that worked... How do I add the submit video link with other submit links?
<img width="510" alt="screen shot 2018-01-08 at 3 49 54 pm" src="https://user-images.githubusercontent.com/35083828/34691731-8e286732-f48b-11e7-8ea6-fa048257a384.png">

**Comment by RobiNN1** [comment]
Replace this https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/user_info_panel/user_info_panel.php#L23-L31

```php
$modules = array(
    'n' => array($locale['UM090'], DB_PREFIX.'news'),
    'b' => array($locale['UM095'], DB_PREFIX.'blog'),
    'l' => array($locale['UM091'], DB_PREFIX.'weblinks'),
    'a' => array($locale['UM092'], DB_PREFIX.'articles'),
    'p' => array($locale['UM093'], DB_PREFIX.'photos'),
    'd' => array($locale['UM094'], DB_PREFIX.'downloads'),
    'q' => array($locale['UM102'], DB_PREFIX.'faqs'),
    'v' => array(fusion_get_locale('VID_076', VID_LOCALE), DB_PREFIX.'videos')
);
```

**Comment by jonathanwichter** [comment]
<img width="1281" alt="screen shot 2018-01-08 at 7 10 47 pm" src="https://user-images.githubusercontent.com/35083828/34698731-ac869962-f4a7-11e7-8a4e-5157db7f842f.png">
Added it had it screwed up the layout of the site. Had to replace the file to make it normal again.
