### ISSUE TITLE
User createded sites not visible - Custom Pages is missing the pagination 

### ISSUE THREAD

**Issue by warberg** [PHPFusion/PHPFusion#1932]
In admin panel, only 8 user created site are visible, there are no opportunities to change to new site and edit other pages

**Comment by meangczac** [comment]
What do you mean? There are no user sites in admin panel. Which system are you referring to?

**Comment by warberg** [comment]
In custom site section where user created site are shown, its only possible to see 8 user sites there need to be some buttons like "Next" and "previous" that can go to next site to see the rest of the site? see my picture.

![image](https://user-images.githubusercontent.com/33963105/35006014-b5661266-faf5-11e7-92b4-4d5006849668.png)

**Comment by meangczac** [comment]
Got it. Thanks for the helpful screenshot

**Comment by warberg** [comment]
Is it possible for me to do anything in stable 9 som that i can finde all user created sites, before release of 9.03 ?

**Comment by meangczac** [comment]
I’ll fix it in a jiffy. 

Regards, Frederick

**Comment by meangczac** [comment]
This is a duplicated issue - https://github.com/php-fusion/PHP-Fusion/issues/1807

Fixed : https://github.com/php-fusion/PHP-Fusion/commit/71d28514d0c961ff86a69094a4d159792725f210
