### ISSUE TITLE
google recaptcha

### ISSUE THREAD

**Issue by jonathanwichter** [PHPFusion/PHPFusion#1934]
This is what happens when I am testing out google recaptcha. I talked to the hosting company and they are seeing if it on their end or not, but just seeing if it is a coding problem.

<img width="2529" alt="screen shot 2018-01-14 at 8 11 59 pm" src="https://user-images.githubusercontent.com/35083828/34923164-57b977b4-f967-11e7-86af-1affbff313fc.png">
<img width="1734" alt="screen shot 2018-01-14 at 8 12 42 pm" src="https://user-images.githubusercontent.com/35083828/34923166-599620fa-f967-11e7-9737-24b5ef0afdd9.png">

**Comment by jonathanwichter** [comment]
It gives me the check mark but it says it wrong, so I do not know what making this happen.
<img width="865" alt="screen shot 2018-01-15 at 7 01 52 am" src="https://user-images.githubusercontent.com/35083828/34941582-59cb9496-f9c2-11e7-9183-5c6e66da8dcb.png">
<img width="878" alt="screen shot 2018-01-15 at 7 02 25 am" src="https://user-images.githubusercontent.com/35083828/34941583-5c1b14f6-f9c2-11e7-8e6d-6fb2e43a00a2.png">

**Comment by JoakimFalk** [comment]
file_get_contents function is disabled on host with allow_url_fopen = 0

**Comment by jonathanwichter** [comment]
I told them and thanks for the reply.

**Comment by jonathanwichter** [comment]
It is not the host, but here is a link to the info.php

http://buhlmodeltrainsociety.a2hosted.com/v9/info.php

<img width="826" alt="screen shot 2018-01-15 at 9 39 53 am" src="https://user-images.githubusercontent.com/35083828/34947422-0df0c512-f9d8-11e7-8b73-4c97a066d060.png">

**Comment by JoakimFalk** [comment]
For now I can´t answer that, on our tests it works and the first report we get back in the error list says that it is disabled by url_fopen, are you sure they did not enabled it after your report? and it is all working just fine now?

**Comment by jonathanwichter** [comment]
They told me when they create the servers they always have that set to enable.  I installed version 9.0 and it never worked. It was enabled and I still got the same error.

**Comment by meangczac** [comment]
Give me a day or two to check before I know what’s going on.

**Comment by jonathanwichter** [comment]
Thanks Chan

**Comment by jonathanwichter** [comment]
Did you find the problem that caused the error?

**Comment by meangczac** [comment]
No there is no problem on my end. What infusion are you using, see contact.php on v9 integration. 

Regards, Frederick

**Comment by jonathanwichter** [comment]
I’m just trying to use the integrated google  Security when people are trying to register

**Comment by meangczac** [comment]
I've doubled check, and your issue is similar to this:
https://groups.google.com/forum/#!topic/recaptcha/IiWoGPEv38U

I would have got the error replicated on my system if it's code issue. But it is very likely a hosting server issue. Reopen the ticket, show them url i've given above, and tell them the code is by Google, not by PHP Fusion. 

Tell them that in localhost, there is no problem. So the issue must be in their server php.ini configuration settings. If you have access to it then follow the instruction as @Domi-php said.

**Comment by jonathanwichter** [comment]
It’s not the PHP.ini is f open is enabled.

Thank you,
Jonathan Wichter
1401 Kimberly Road
Sharon, PA 16146
(724) 714-1947 Cell
(724) 213-9118 Fax
