### ISSUE TITLE
news and downloads fusion not shown on admin menu

### ISSUE THREAD

**Issue by lagkdok** [PHPFusion/PHPFusion#1935]
![admin12](https://user-images.githubusercontent.com/5101035/34947516-9c8cbfba-fa0a-11e7-9374-890f2723a5b4.png)
first, the Arabic locale for PHP-Fusion 9 is 95% ready 
aftern installing fusions i found no news admin and downloads admin too.
The fusion menu in admin panel is empty or it redirect into homepage admin when using Material or AdminLTE theme
![admin11](https://user-images.githubusercontent.com/5101035/34947501-8ffe8940-fa0a-11e7-855b-52fb8beecf3a.png)

**Comment by RobiNN1** [comment]
In English language works?

Same issue https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38979&pid=204153#post_204153

**Comment by ghost** [comment]
For me in this branch the same problem, News and TinyMCE are not displayed.

Can anyone confirm?

`My solution was today!!`

You have to defuse and infuse the news infusion. Then it goes again, but a news was lost to me then.

**Comment by ovasclub** [comment]
There were many changes in (locale \ English) includes, infusions, locale, themes, widgets. Change your locale in accordance with English.
Everything works, everything is displayed.

**Comment by ghost** [comment]
My Problems on new Shared Hosting with PHP Fusion 9.0.3 and this branch is solved. This was MariaDB/Plesk-Issue!!

**Comment by meangczac** [comment]
If can’t found on admin, there is several thing to check. Does it work in English? If yes, language problem. If no, read on..

Check your sql records. In DB_INFUSIONS is it infused? If yes, check user_rights column in DB_USERS under your own user_id - see if you can see the respective user rights for news infusion and download infusion (I.e “.N” for news)
If it’s there, then check DB_ADMIN see if you have a news admin record.
