### ISSUE TITLE
Cannot infuse Articles Infusion - Errors in the Installer

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1936]
Hi Developers,

I've disabled the Articles infusion today and can no longer activate it.

The installer displays these errors.

`Notice: Query Error: INSERT INTO fusionnN328_settings_inf (settings_name, settings_value, settings_inf) VALUES ('article_pagination', '15', 'articles')
Stack Trace: #0 /xxxxxxxxxxxx/phpfusion.hro-mv.de/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(67): PDOStatement->execute() #1 xxxxxxxxxxxxxxxxxxx/phpfusion.hro-mv.de/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array) #2 /xxxxxxxxxxxxxxxxxxxxxxx/phpfusion.hro-mv.de/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array) #3 /xxxxxxxxxxxxxxxxxxxxxxxxx/phpfusion.hro-mv.de/includes/classes/PHPFusion/Installer/Infusion.core.inc(708): dbquery('INSERT INTO fus...') #4 /xxxxxxxxxxxxxxxxxxxxxxxxxxx/phpfusion.hro-mv.de/includes/classes/PHPFusion/Installer/Infusion.core.inc(158): PHPFusion\Installer\Infusion_Core->insertdbrow_infuse(Array) #5 /xxxxxxxxxxxxxxxxxxxxxxxxxxx/phpfusion.hro-mv.de in /xxxxxxxxxxxxxxxxxxxxxxxxx/phpfusion.hro-mv.de/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc on line 71`

Maybe you can check it out.

Thanks in advance.

**Comment by ovasclub** [comment]
Checked on Open Server, disconnected, connected. Everything is working

**Comment by ghost** [comment]
My Problems on new Shared Hosting with PHP Fusion 9.0.3 and this branch is solved. This was MariaDB/Plesk-Issue!!
