### ISSUE TITLE
On Custom Pages in The Frontend >> Unable to retrieve page content.

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#1937]
Hi Developers,

what does that mean in the frontend. The content of a custom page is not displayed.

Thanks in Advance.

**Comment by lagkdok** [comment]
turn the page status from unpublished to published

**Comment by ghost** [comment]
With my 30-hour time online, such mistakes happen. But thanks for the tip. In the old blog, it was probably or something else. Problem is now solved 👍
