### ISSUE TITLE
Septenary - header is not clickable, if is error in log

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1938]
The problem [#1930](https://github.com/php-fusion/PHP-Fusion/issues/1930) is not solved. Errors block the Sub-header. When you clean Error Log, the problem goes away.

**Comment by RobiNN1** [comment]
Sorry, I don't know what you want, can you more describe problem? Everything on my server works.

**Comment by ovasclub** [comment]
Install it on a clean on the Open Server.
All is well, until the first mistake. For example: I add an empty panel. An error occurred, Sub-header was disabled. I am clearing the Error Log, the problem has disappeared. **Only in Theme Septenary**.
If there is an error entry in Error Log, Sub-header does not work in Theme Septenary !!!
Checked it and on my site and hosting

**Comment by RobiNN1** [comment]
Bug is caused by right panel inserted in left panel, but I can't seem to fix it.
