### ISSUE TITLE
Administration > System Admin > Theme

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#194]
When you try to save a theme with no title you get : 
There was an error while processing your request
Theme cannot rebuild due to the following reason(s): - Variables were not set or form is has error

You also get a complete dump of the settings you try to save with the following notices. 

Atom/Atom.php Undefined index: Line: 1802
Atom/Atom.php Undefined index: Line: 1797
Atom/Atom.php Undefined index: Line: 1807
Atom/Atom.php Undefined index: navbar_link_decoration Line: 511
Atom/Atom.php Undefined index: navbar_link_decoration_hover Line: 511
Atom/Atom.php Undefined index: navbar_link_decoration_active Line: 511
Atom/Atom.php Undefined index: navbar_font_decoration Line: 511
Atom/Atom.php Undefined index: navbar_brand_decoration Line: 511

**Comment by meangczac** [comment]
Hohoho.... Looks like i'm going to open <a href="https://en.wikipedia.org/wiki/Pandora%27s_box">Pandora's box</a> again.

**Comment by meangczac** [comment]
I'm going to use a cheap hack. See if it fixes.
