### ISSUE TITLE
Styles are missing / not loaded

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1943]
**PHP Fusion Version**: 9.03
![image](https://user-images.githubusercontent.com/4210004/35704720-b19d872e-07a0-11e8-9a78-22db7dd5db8d.png)

**Comment by RobiNN1** [comment]
Enable Bootstrap in theme settings

https://github.com/php-fusion/PHP-Fusion/commit/12de5f4bcf6b3810e88430f3b96705200c0bfd96

**Comment by JoakimFalk** [comment]
All Themes need to be controlled by the Admin settings, 

![image](https://user-images.githubusercontent.com/4210004/35706708-123952f6-07a7-11e8-9041-33bd15f48fea.png)

**Comment by RobiNN1** [comment]
I added `define('BOOTSTRAP', TRUE);` because if you need turn off Bootstrap for admin theme, but must also be turned on the front page or without Bootstrap, theme will not work properly

**Comment by JoakimFalk** [comment]
Even if it "breaks" the Themes, in stock Infusions, Themes , etc.  
We should always reflect the system options and never hard code anything.  
I would for one never had or experienced this issue if the setting toggler was not removed in the first place, 
It is also because the stock themes need to work as examples to new people, so all system connections need to be there. Good or Bad ;)

**Comment by JoakimFalk** [comment]
I see the setting in layout.php , so I guess it is ok. It is global and allow for 2 options. We keep it as is then !
