### ISSUE TITLE
Undefined indexes, 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1944]
**PHP Fusion Version**: 9.03

If SQL amends. changes have been done, they must always be included in both in the standard upgrade from script 7.02.07 > 9 and in the administration/upgrade.php from 9.0 > 9.03

![image](https://user-images.githubusercontent.com/4210004/35704762-cd8dbed6-07a0-11e8-88e2-5cb6ca331c9d.png)

**Comment by RobiNN1** [comment]
Update includes/classes/PHPFusion/PrivateMessages.inc
On line 751 is `placeholder' => $this->locale['422'],`
https://github.com/php-fusion/PHP-Fusion/blob/9.03/includes/classes/PHPFusion/PrivateMessages.inc#L751

**Comment by JoakimFalk** [comment]
This is from a complete sync of current Git

**Comment by JoakimFalk** [comment]
Removed all system files and updated from current git again, prolly some autoloader getting old stuff that fubared it. Case closed.
