### ISSUE TITLE
themes/templates/layout.php

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#1945]
**PHP Fusion Version 9.03**: 
```
<!-- for PHP5 do not use this code is not good-->
<link type="text/css" rel="stylesheet"href="css/styles.css" />
<script type="text/javascript" src="js/scripts.js"></script>

<!-- Use this -->
<link rel="stylesheet" href="css/styles.css" />
<script src="js/scripts.js"></script>
```
I think it should apply to other files too.
In HTML5, you do not need to specify a type attribute for script and the style element.

**Comment by RobiNN1** [comment]
It's okay, it has no effect on the site's performance.
Not all modern browsers are supporting the HTML5. And your sites should work not only in last versions of Chrome, Opera and Firefox - you should support IE too, even if you don't use it.
