### ISSUE TITLE
This members online does not seem right 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1952]
**PHP Fusion Version**: 9,03
![image](https://user-images.githubusercontent.com/4210004/35773405-6e311b4c-0951-11e8-804e-6a4af92c717f.png)

**Comment by ovasclub** [comment]
What is not right here?

![-4](https://user-images.githubusercontent.com/16386011/35831457-f773a016-0af3-11e8-8fc0-5e24e2a2f3b3.jpg)

**Comment by JoakimFalk** [comment]
Yours is OK, mine not ok . Are you running the latest git?

**Comment by ovasclub** [comment]
Yes, PHP-Fusion 9.03

**Comment by RobiNN1** [comment]
I don't know how, but i have same issue 
![dvrgb](https://user-images.githubusercontent.com/11664877/36395987-32f14c88-15bc-11e8-8925-60cb0c453a52.png)

**Comment by karrak1** [comment]
This error exists in the case of a browser now?
