### ISSUE TITLE
PDOMySQL.inc

### ISSUE THREAD

**Issue by balin50** [PHPFusion/PHPFusion#1953]
**PHP Fusion Version**: 9.03 from 2.2.2018
PDOMySQL.inc
/articles/filter/comment/category/5
Severity : Notice generated by user using trigger_error() function

Query Error: SELECT a.*, ac.*, au.user_id, au.user_name, au.user_status, au.user_avatar, au.user_level, au.user_joined, SUM(ar.rating_vote) AS sum_rating, COUNT(ar.rating_item_id) AS count_votes, COUNT(ad.comment_item_id) AS count_comment FROM fusion44293_articles AS a LEFT JOIN fusion44293_users AS au ON a.article_name=au.user_id LEFT JOIN fusion44293_article_cats AS ac ON a.article_cat=ac.article_cat_id LEFT JOIN fusion44293_ratings AS ar ON ar.rating_item_id=a.article_id AND ar.rating_type='A' LEFT JOIN fusion44293_comments AS ad ON ad.comment_item_id=a.article_id AND ad.comment_type='A' AND ad.comment_hidden='0' WHERE a.article_language='Slovak' AND ac.article_cat_language='Slovak' AND a.article_draft='0' AND a.article_visibility = 0 AND ac.article_cat_status='1' AND ac.article_cat_visibility = 0 AND a.article_cat='5' GROUP BY a.article_id ORDER BY count_comment DESC LIMIT 0, 
Stack Trace: 
#0 /home/dj023500/www_root/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('\n SE...') 
#1 /home/dj023500/www_root/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('\n SE...', Array) 
#2 /home/dj023500/www_root/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('\n SE...', Array) 
#3 /home/dj023500/www_root/infusions/articles/classes/articles/articles.php(368): dbquery('\n SE...') 
#4 /home/dj023500/www_root/infusions/articles/classes/articles/articles_view.php(37): PHPFusion\Articles\Articles->set_ArticlesCatInfo('5')
#5 /home/dj023500/www_root/infusions/articles/articles.php(29): PHPFusion\Articles\ArticlesView->display_articles() 
#6 /home/dj023500/www_root/index.php(43): require_once('/home/dj023500/...') 
#7 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 17

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/a561a9c6f5258c1e7e114b9991d087c04a545d35
