### ISSUE TITLE
Blog - does not show items

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1955]
Does not show items after  https://github.com/php-fusion/PHP-Fusion/commit/634fbdc90836f83eb5e69552f00872003186183 , but on home is all OK.

Error log is empty. I use PDO driver.

**Comment by meangczac** [comment]
Sorry I will check again. Coz my side works fine. Is the SEO driver on your end?

**Comment by RobiNN1** [comment]
Same issue on Ubuntu WSL (Windows 10 subsystem for linux)

I try run PHP Fusion on different systems with same PHP configuration (XAMPP, NGINX Server, Windows IIS, WSL Ubuntu and CentOS) and all works good.

Just blog have issue.

**Comment by RobiNN1** [comment]
SEO is disabled

**Comment by meangczac** [comment]
Can you send me a SQL entry

Like a $_GET[‘readmore’] = xx and 

Do a print_p of the data output. I test using your blog entry. It’s weird. 

Regards, Frederick

**Comment by meangczac** [comment]
Which part exactly did not work? Filters or readmore?

**Comment by RobiNN1** [comment]
Main page /blog/blog.php

**Comment by JoakimFalk** [comment]
You have the issue to test on next production blog as well, no posts listed while 1 exist in reality.

**Comment by meangczac** [comment]
Ok I will patch 

Regards, Frederick

**Comment by RobiNN1** [comment]
Now works good with PDO, but

MySQLi.inc
/infusions/blog/blog.php **
Line: 201
Expression 
#1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pf9.pf9_blog.blog_datestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by @ SELECT YEAR(from_unixtime(blog_datestamp)) as blog_year, MONTH(from_unixtime(blog_datestamp)) AS blog_month, count(blog_id) AS blog_count FROM pf9_blog WHERE blog_language='English' AND 1 = 1 AND (blog_start=0 || blog_start<=1518180188) AND (blog_end=0 || blog_end>=1518180188) AND blog_draft=0 GROUP BY blog_year, blog_month ORDER BY blog_datestamp DESC

**Comment by meangczac** [comment]
Is this Fixed @RobiNN1  ?

**Comment by RobiNN1** [comment]
With MySQLi no
