### ISSUE TITLE
It's not possible to write a message in Shoutbox as a guest.

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1957]
It's not possible to write a message in  Shoutbox as a guest.
Сhanged Google Recaptcha and Secure Image v.3, but the result is one:
> There was an error while processing your request
> Enter Validation Code:

PHP-Fusion 9.03

**Comment by meangczac** [comment]
What is mini chat?

**Comment by ovasclub** [comment]
Shoutbox. I can not write a message as a guest, as a member of this problem there is no.


![-2](https://user-images.githubusercontent.com/16386011/36034341-01b8fee4-0dde-11e8-90c1-b663b78dcafe.jpg)

**Comment by karrak1** [comment]
Admin -> Settings -> Miscellaneous -> 
Allow Guests to post? == Yes ??
(It works for me)

**Comment by ovasclub** [comment]
Secure Image v.3 works
Google Recatcha does not work

**Comment by meangczac** [comment]
Why is the Recaptcha suddenly doesn't work? We had it working...

**Comment by ovasclub** [comment]
Everything is working. This is an old entry
