### ISSUE TITLE
Let's simplify the world

### ISSUE THREAD

**Issue by kkMatt** [PHPFusion/PHPFusion#1959]
**PHP Fusion Version**: V9

I don't get the point - why make Fusion world so complicated when there is standards in the worlds for naming already. These a well known words. So let's rename:
Infusion => Plugin
Panel => Widget (and 'register_widget')

WordPress is now running 24% of the web online, so everybody is used to that standard, and it should be allowed to convert those customers much easier, with less hassle.

**Comment by JoakimFalk** [comment]
It´s been called that for 13+ years for us, we won´t change it. ;)
