### ISSUE TITLE
HomePage error

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#1961]
**PHP Fusion Version 9.03**: 
Yesterday's update / update v.9.03 of GitHub on localhost:
Reports error on line 201 v
/includes/classes/PHPFusion/Database/Driver/MySQLi.inc

**Comment by RobiNN1** [comment]
The stack trace is needed. Please read https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38204

**Comment by Kvido** [comment]
securimage.php /contact.php Řádek: 1385 před 2 dny |  
-- | --
file_exists(): open_basedir restriction in effect. File(/usr/bin/lame) is not within the allowed path(s): (/var/www/vhosts/phpfusion.cz/:/tmp/)

/includes/captchas/securimage3/securimage.php
link 1385:
if (file_exists(Securimage::$lame_binary_path) && is_executable(Securimage::$lame_binary_path)) {
                $html .= sprintf('<source id="%s_source_mp3" src="%sid=%s&amp;format=mp3" type="audio/mpeg">', $image_id, $play_path, uniqid())."\n";
            }

**Comment by Kvido** [comment]
Na http://localhost/homepage není již žádná chyba.
Na test.phpfusion.cz je chyba:
securimage.php
/contact.php
Řádek: 1385
před 3 dny
`file_exists(): open_basedir restriction in effect. File(/usr/bin/lame) is not within the allowed path(s): (/var/www/vhosts/phpfusion.cz/:/tmp/)`

**Comment by RobiNN1** [comment]
Webhost issue

**Comment by Kvido** [comment]
Probably the problem is on the path to / tmp. Maybe use the absolute file path. So on hosting give a request, right?

Make a change to /etc/php/php.ini and add a path to the file in the open_basedir property.
Somehow as follows:

open_basedir = / srv / http: / home /: / tmp /: / usr / share / pear /: / usr / share / webbrowser /: /

**Comment by Kvido** [comment]
Zdrojový kód                                 (Řádek: 1375 - 1395)
--
1375              $html .= sprintf('<img %s/>', $image_attr);                      1376          }                      1377                        1378          if (($parts & Securimage::HTML_AUDIO) > 0 && $show_audio_btn) {                      1379              // html5 audio                      1380              $html .= sprintf('<div id="%s_audio_div">', $image_id)."\n".                      1381                  sprintf('<audio id="%s_audio" preload="none" style="display: none">', $image_id)."\n";                      1382                        1383              // check for existence and executability of LAME binary                      1384              // prefer mp3 over wav by sourcing it first, if available                      1385              if (file_exists(Securimage::$lame_binary_path) && is_executable(Securimage::$lame_binary_path)) {                       Line 1385 -- před 3 dnyfile_exists():  open_basedir restriction in effect. File(/usr/bin/lame) is not within  the allowed path(s): (/var/www/vhosts/phpfusion.cz/:/tmp/)   1386                  $html .= sprintf('<source id="%s_source_mp3" src="%sid=%s&amp;format=mp3" type="audio/mpeg">', $image_id, $play_path,                    uniqid())."\n";                      1387              }                      1388                        1389              // output wav source                      1390              $html .= sprintf('<source id="%s_source_wav" src="%sid=%s" type="audio/wav">', $image_id, $play_path, uniqid())."\n";                      1391                        1392              // flash audio button                      1393              if (!$disable_flash_fbk) {                      1394                  $html .= sprintf('<object type="application/x-shockwave-flash" data="%s?bgcol=%s&amp;icon_file=%s&amp;audio_file=%s" height="%d"                    width="%d">',                      1395                      htmlspecialchars($swf_path),                      1396 | 1375 | $html .= sprintf('<img %s/>', $image_attr); | 1376 | } | 1377 |   | 1378 | if (($parts & Securimage::HTML_AUDIO) > 0 && $show_audio_btn) { | 1379 | // html5 audio | 1380 | $html .= sprintf('<div id="%s_audio_div">', $image_id)."\n". | 1381 | sprintf('<audio id="%s_audio" preload="none" style="display: none">', $image_id)."\n"; | 1382 |   | 1383 | // check for existence and executability of LAME binary | 1384 | // prefer mp3 over wav by sourcing it first, if available | 1385 | if (file_exists(Securimage::$lame_binary_path) && is_executable(Securimage::$lame_binary_path)) { | Line 1385 -- před 3 dnyfile_exists():  open_basedir restriction in effect. File(/usr/bin/lame) is not within  the allowed path(s): (/var/www/vhosts/phpfusion.cz/:/tmp/) | 1386 | $html .= sprintf('<source id="%s_source_mp3" src="%sid=%s&amp;format=mp3" type="audio/mpeg">', $image_id, $play_path,                    uniqid())."\n"; | 1387 | } | 1388 |   | 1389 | // output wav source | 1390 | $html .= sprintf('<source id="%s_source_wav" src="%sid=%s" type="audio/wav">', $image_id, $play_path, uniqid())."\n"; | 1391 |   | 1392 | // flash audio button | 1393 | if (!$disable_flash_fbk) { | 1394 | $html .= sprintf('<object type="application/x-shockwave-flash" data="%s?bgcol=%s&amp;icon_file=%s&amp;audio_file=%s" height="%d"                    width="%d">', | 1395 | htmlspecialchars($swf_path), | 1396
1375 | $html .= sprintf('<img %s/>', $image_attr);
1376 | }
1377 |  
1378 | if (($parts & Securimage::HTML_AUDIO) > 0 && $show_audio_btn) {
1379 | // html5 audio
1380 | $html .= sprintf('<div id="%s_audio_div">', $image_id)."\n".
1381 | sprintf('<audio id="%s_audio" preload="none" style="display: none">', $image_id)."\n";
1382 |  
1383 | // check for existence and executability of LAME binary
1384 | // prefer mp3 over wav by sourcing it first, if available
1385 | if (file_exists(Securimage::$lame_binary_path) && is_executable(Securimage::$lame_binary_path)) {
Line 1385 -- před 3 dnyfile_exists():  open_basedir restriction in effect. File(/usr/bin/lame) is not within  the allowed path(s): (/var/www/vhosts/phpfusion.cz/:/tmp/)
1386 | $html .= sprintf('<source id="%s_source_mp3" src="%sid=%s&amp;format=mp3" type="audio/mpeg">', $image_id, $play_path,                    uniqid())."\n";
1387 | }
1388 |  
1389 | // output wav source
1390 | $html .= sprintf('<source id="%s_source_wav" src="%sid=%s" type="audio/wav">', $image_id, $play_path, uniqid())."\n";
1391 |  
1392 | // flash audio button
1393 | if (!$disable_flash_fbk) {
1394 | $html .= sprintf('<object type="application/x-shockwave-flash" data="%s?bgcol=%s&amp;icon_file=%s&amp;audio_file=%s" height="%d"                    width="%d">',
1395 | htmlspecialchars($swf_path),
1396
