### ISSUE TITLE
Articles is not displayed through the navigation

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1962]
The problem in server.php, or rather in article <=> articles
With article, I'm fine, but with articles the problem.

43.self::$article_settings = get_settings("article");
      self::$article_settings = get_settings("articles");

Got it. You need to change the database in the  table **fusion12345_settings_inf**
('article_pagination', '15', 'articles'),
('article_allow_submission', '1', 'articles'),
('article_extended_required', '0', 'articles'),

PHP-Fusion 9.03

**Comment by RobiNN1** [comment]
This has been fixed https://github.com/php-fusion/PHP-Fusion/commit/a561a9c6f5258c1e7e114b9991d087c04a545d35#diff-c02fcfe1a8f8ab092da6060328bc3e28

**Comment by ovasclub** [comment]
This file is installed.
