### ISSUE TITLE
Youtube, Excel disappeared in the news and articles.

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1963]
Youtube, Excel disappeared in the news and articles.
PHP-Fusion 9.03
Youtube,
<iframe width="560" height="315" src="https://www.youtube.com/embed/********" frameborder="0" allowfullscreen></iframe>

Excel

<iframe width="658" height="900" frameborder="0" scrolling="no" src="https://onedrive.live.com/embed?resid=7B2C418EDABDC1FE%21303&authkey=%21ACTu3xjpGY-6Wzc&em=2&wdAllowInteractivity=False&ActiveCell='%D0%9B%D0%B8%D1%81%D1%821'!B1&Item=%D0%9B%D0%B8%D1%81%D1%821!Print_Area&wdInConfigurator=True"></iframe>

**Comment by RobiNN1** [comment]
Use 
```html
<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="https://www.youtube.com/embed/*********" allowfullscreen></iframe></div>
```

**Comment by ovasclub** [comment]
Not showing, although the place under the video has increased.

Problem in core_functions_include.php.
replaced it with a file from 01/22/17. And the problem is gone.
