### ISSUE TITLE
Youtube, Excel disappeared in the news and articles.

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1964]
Problem in core_functions_include.php.
583.    $text = descript($text);  kills the show
583.    //$text = descript($text);  the problem is gone.

https://github.com/php-fusion/PHP-Fusion/issues/1963

**Comment by RobiNN1** [comment]
These tags are not allowed: applet, meta, xml, blink, link, style, script, embed, object, iframe, frame, frameset, ilayer, layer, bgsound, title, base
