### ISSUE TITLE
Undefined index: news_last_updated

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1965]
**PHP Fusion Version**: 

fresh install (Danish and English) v9.03
all infusions installed
![undefined-index-news_last_updated](https://user-images.githubusercontent.com/9512774/36274307-932a451a-1287-11e8-8f6a-5cb3c9b5980d.png)

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/9752836068d86a75c0b404ba62ae00eff390213f
