### ISSUE TITLE
New Tags system

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1966]
creating a tag system for news, articles, images, as a forum tag system

**Comment by JoakimFalk** [comment]
We actually have it a upcoming Dev plan, but I am not sure we should do it on this revision.  
But if you use Toxi Method and make it global we might as well :)

	Develop and incorporate a Core based Tag system
	· Suggesting Toxi Method with a 3 table solution, it is suposed to be the fastest in most scenarios
	· This need to be a global API similar to Comment´s , display_tags(tag_id,item_id,type, etc, etc), save_tags(), edit_tags() , update_tags() functions.

**Comment by meangczac** [comment]
Add to implementation wise. 

Clicking a Tag shows results in the search engine by default unless we have a custom page for such results. This way we can Tag about almost anything. 

Regards, Frederick

**Comment by JoakimFalk** [comment]
Is in roadmap
