### ISSUE TITLE
Not correctly displayed E-mail on the page

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1968]
Example: primer@gmail.com => primergmailcom

PF 9.03

**Comment by meangczac** [comment]
What function and what page? Where is it does it display wrongly?

**Comment by ovasclub** [comment]
Now is E-mail: ML="il1=rhet>:;04axxxx5f 6/m8#'7&o9";MI=">=A5463GD=017J9IF222:IF22E:IFKH:IF22?:IFxxxxB:IFKK:IF2;E:IF22H:IFKE:IFBxxxx:IF2;K:IFKH:IF2;?:IF2;E:IFxxxxB:IF22xxxx:IF22H:G8IF222:IF22E:IFKH:IF22?:IFxxxxB:IFKK:IF2;E:IF22H:IFKE:IFBxxxx:IF2;K:IFKH:IF2;?:IF2;E:IFxxxxB:IF22xxxx:IF22H:>C=8";ML=ML.replace(/xxxx/g, '<');MI=MI.replace(/xxxx/g, '<');OT="";for(j=0;j < MI.length;j++){OT+=ML.charAt(MI.charCodeAt(j)-48);}document.write(OT);

Problem in core_functions_include.php.
587.  $text = descript($text); kills the show
587. //$text = descript($text); the problem is gone.
[](https://ovas.club/viewpage.php?page_id=1)
