### ISSUE TITLE
not work form_fileinput translate

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1973]
version 9.03

![capture3](https://user-images.githubusercontent.com/16163102/37723713-5100b792-2d2f-11e8-90c1-d3b7ae1e8cc8.jpg)

admin-> images.php good,
infusions/downloads/admin/downloads not good

echo form_fileinput('download_image', $locale['download_0220'], '', $image_options);
and 
echo form_fileinput('download_file', $locale['download_0214'], "", $file_options);
conflict

**Comment by RobiNN1** [comment]
Hungarian translate issue. Compare locales with English.

I checked it in Czech and Slovak translation and it's ok.

Czech locale:
![ertyjhu](https://user-images.githubusercontent.com/11664877/38175842-8799c926-35e3-11e8-8c9a-660861234265.png)

**Comment by karrak1** [comment]
for me Czech is not good either,
 the problem is the same.
![capture_001_01042018_213130](https://user-images.githubusercontent.com/16163102/38176710-1ae2ac24-35f4-11e8-9410-131f1b2f3c45.jpg)
