### ISSUE TITLE
The division of the text into pages disappeared

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1978]
The division of the text into pages disappeared
Problem in includes/classes/PHPFusion/Page/PageController.inc

![37886671-9936c8dc-30de-11e8-8ad7-bb84d9fa0731](https://user-images.githubusercontent.com/16386011/37919719-8d38beec-3146-11e8-9e06-e4bbcf8b9156.jpg)

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/674845be02eb6fad2e70e80b1e1f9472ec587c9f
