### ISSUE TITLE
Automatic updates over github?

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1981]
sorry if I ask here but how do I set up an automatic github update on my FTP. 
Is there a guide to it somewhere?

every core file includes a github folder. I'm not a github profi so my question what do I do with it?

![grafik](https://user-images.githubusercontent.com/22166864/38139226-c8b75a24-342e-11e8-9398-84affca7ea19.png)

**Comment by RobiNN1** [comment]
GitHub natively does not support FTP synchronization, but you can use https://desktop.github.com/ and sync on your computer.

You can delete:
- .github
- test
- .gitattributes
- .gitignore
- every *.md file
- LICENSE
- _config.yml
- readme-en.html
It is not necessary for the functionality of the system.
