### ISSUE TITLE
On contact.php no panels are displayed

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1982]
On contact.php no panels are displayed

![-2](https://user-images.githubusercontent.com/16386011/38174339-9ecd0680-35ed-11e8-9e9c-34f382d5d915.jpg)

**Comment by karrak1** [comment]
the septenary interface is not compatible with the opentable function

**Comment by karrak1** [comment]
if septenary theme error then
[look](https://github.com/php-fusion/PHP-Fusion/commit/f10d4aac5543b658c012da9fee82a2ff7bf54cd2)
