### ISSUE TITLE
news Array to string conversion error

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#1992]
if bootstrap theme activ, then
C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Template.inc
/fusion/infusions/news/news.php **
Sor: 189
there is no error on another theme

**Comment by meangczac** [comment]
I'm not getting any errors. Did you fix it ? I have the latest state git.

**Comment by karrak1** [comment]
yes, but I do not know if it is ok. no error message
[https://github.com/php-fusion/PHP-Fusion/commit/f2a35fa351f8768a5f6d19ee123c29191409395e](url)

**Comment by meangczac** [comment]
Ok we can close
