### ISSUE TITLE
plz encode email adress in contact form

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1994]
please encode email for spam. My email is in clear text on the contactpage. I get hundreds of mails from Russia!

in my old system i have this: 
E-Mail: <a href="email_handler.php">Info [at] AlienCollectors [dot] com</a><br>

**Comment by ovasclub** [comment]
Google Recaptcha - You will be helped

**Comment by UnrealCatze** [comment]
There are many possibilities I have just made a handler. Anyway, like now in the core, I would not let that happen. I get shit .ru mails every day. I will not let go of the crap

**Comment by meangczac** [comment]
I thought I hide it already. 

Use hideemail function it will become gibberish to bits, which has been implemented. 

Turn on hide email settings in admin panel.

**Comment by UnrealCatze** [comment]
no not hide email ... in contact i have to show my mail but it must be encrypted .. so its perfect for all russian spamer and hacker .. i get hunderts fuc,,,, .ru mails ervery week about this. here is a massive security leak .. well this place is the only one where i have puplish this mail online an a website

this im meaning
![grafik](https://user-images.githubusercontent.com/22166864/38675201-3613d462-3e57-11e8-8f47-e5f4f8488c9d.png)

**Comment by meangczac** [comment]
I think you misunderstood me. 

In contact page, your email is encased by hide_email() function. That function encrypts your email. 

Turn in hide email settings in admin and that will prevent Russian bot catching your email.

**Comment by JoakimFalk** [comment]
That toggler is for profiles, we do not have a global one. Site email should use hide_email() function at all times. Perhaps the locale macro glitches it now.

**Comment by UnrealCatze** [comment]
guess here are missunderstandings. I meaning the site email .. this site email comes from the locale and its not encrypted. i see on mousover mailto: ....... perfect for bots

![grafik](https://user-images.githubusercontent.com/22166864/38725321-497a6b96-3f07-11e8-8c86-4904c598df6a.png)
![grafik](https://user-images.githubusercontent.com/22166864/38725255-0782fad2-3f07-11e8-82ab-22f749c917c9.png)

in admin settings i have no possibility to hide my site email. or i m blind ;)

**Comment by meangczac** [comment]
Sorry you’re not mistaken. Just had a talk with @Falk earlier regarding
this. The email encryption might be wrongly implemented.
I will check on the implementation tonight.

> --

Regards,
Frederick MC Chan
Intl' Business
Catessens Holdings Sdn Bhd

**Comment by JoakimFalk** [comment]
Bot see, 
![image](https://user-images.githubusercontent.com/4210004/38741922-6cbf4ffc-3f3b-11e8-8493-1af6c0dbb576.png)
Browser see,
![image](https://user-images.githubusercontent.com/4210004/38741939-77fc8326-3f3b-11e8-8c19-aad3d8e296e1.png)

**Comment by UnrealCatze** [comment]
ok @falk thx .. i have check my browser and source code and it looks same as yours ... but where is my massive .ru bot spam problem?

**Comment by meangczac** [comment]
Once you confirm your contact page print out, I'll close this issue.

**Comment by meangczac** [comment]
That mailto has just been recently patched as it was not encrypted earlier on.

The commit is:
https://github.com/php-fusion/PHP-Fusion/commit/e69a79bf270f955222b0f79b9917667f8c362915#diff-4980c4158e3058d8fde8002280cbe6c5
