### ISSUE TITLE
Login - banner 

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1995]
![grafik](https://user-images.githubusercontent.com/22166864/38659976-f8c6a92a-3e2b-11e8-94ef-848b7f679ae6.png)

on the login page the banner is shown twice. Unfortunately, this can not be changed in the code of the login scripts

**Comment by RobiNN1** [comment]
Comment out https://github.com/php-fusion/PHP-Fusion/blob/9.03/themes/templates/global/login.php#L50
