### ISSUE TITLE
Bootstrap Forum ... nicer?

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1996]
sorry if i say that but today i have set my forum and it looks really worst. none will stay on it. I know i can mod then but other have for sure the same problem or feelings

![grafik](https://user-images.githubusercontent.com/22166864/38698601-e7a56702-3e95-11e8-9f47-bca4c8261285.png)

can we get here a "nicer" forum???

**Comment by RobiNN1** [comment]
Maybe in future will be redesigned.
You can customize it. You just need to edit html templates https://github.com/php-fusion/PHP-Fusion/tree/9.03/infusions/forum/templates

For example as it can look:

![screen](https://user-images.githubusercontent.com/11664877/38699124-77d750dc-3e97-11e8-8a8f-b2cd899de679.png)

**Comment by JoakimFalk** [comment]
Not an issue, Theme makers, new versions ( soon to come ) all have or may have improvements.
