### ISSUE TITLE
Problem with saving the session (token)

### ISSUE THREAD

**Issue by djdandi** [PHPFusion/PHPFusion#1998]
My site is served by 3 servers that use the load balancing mechanism. Is it possible to indicate another directory in which the sessions are stored.
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=39142

**Comment by meangczac** [comment]
Yes read about that and responded.

**Comment by djdandi** [comment]
What I read the forum does not work for me.

**Comment by djdandi** [comment]
Is it about saving the session in the database? If it helps, you may have to do it.

**Comment by meangczac** [comment]
No, If I can read your problem correctly "Where Sessions are Stored" 
You need to do a manual session storage and callback in the same server.  Force it to read and save into the same server location where you can have access. You need to test.

In here as you can see this is where the PF session_start is located at:
https://github.com/php-fusion/PHP-Fusion/blob/9.03/maincore.php#L57-L67

According to http://php.net/manual/en/function.session-save-path.php
````
ini_set('session.save_path',realpath(dirname($_SERVER['DOCUMENT_ROOT']) . '/../session'));
session_start();
````
You need to read and adjust accordingly. We are way behind session and balancer yet. It will be developed, but not now. We remain lightweight so there is no need to recode it to go for database oriented session storage like a few CMS I have been developing on before.

Our main distro market right now is single small-medium scale websites, we are not yet aiming for government sector which runs on multiple load balanced server. 

But one thing I find odd, you specified only forum. 

No way the forum doesn't work for you and the rest does. Every input has a session and has to be automatic validated against malicious payload. If the rest work, why does the forum does not load.

**Comment by djdandi** [comment]
I have mistakes when saving a new news, article and photos in the gallery. I get an error related to the token in the session.
Maybe you gave me a solution to this problem but I have no idea how to go about it. I am asking you for help because I can not drive my website well.
Probably the point is that my site gets data from three servers and there is always access to the given session. Maybe the solution is to give a session to a rigid session?
I do not know about php so well to solve it myself. That's why I'm asking you PHP FUSION creators for help.

**Comment by meangczac** [comment]
Worry not. I am always ready to help all Fusioneers.

Please add me on Skype: hien.phpfusion

We need to discuss this in detail to solve your problem.

In fact I have started to develop a session engine using database storage
and will be useful for everyone.

When you’ve added me on skype, we can elaborate on detail. I have your
server details and I will need your presence as well.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/350b56e09d92c5770a5fe99b7ae56650206e7801

Implementation is in maincore.php. I will prepare an interim upgrade file before i push the last part out.

**Comment by djdandi** [comment]
OK thanks When it's finished, I'll test it.

**Comment by karrak1** [comment]
#2028 
I found these errors.
I did not fix it

**Comment by djdandi** [comment]
I installed the latest version of FUSION but now I can not get to PA. In the database, I added a table session but it is empty.

Cannot find any token for this form.
There was an error while processing your request

**Comment by meangczac** [comment]
I will inspect your server very soon in this week.

**Comment by djdandi** [comment]
The latest PHP-FUSION Andromeda 9.03 has already fixed this problem. It looks like everything is working well. The session is saved in the mysql database. Good job.
