### ISSUE TITLE
No access to news settings

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#1999]
V-9.03
No access to news settings.
There is no access to the news settings, except for the main superadmin.
If you go to the settings under other logins, you throw it on the main page.

![-3](https://user-images.githubusercontent.com/16386011/38780716-d233670c-40fc-11e8-869f-09ce82aa33f5.jpg)

**Comment by meangczac** [comment]
It's S8. I'll be fixing it.
