### ISSUE TITLE
errors.php?aid=f3beda311xxxxxxxx dosent work

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2001]
since last core updates the link dosent work .. any changes in code?

link adress: https://aliencollectors.com/test/administration/errors.php?aid=f3beda311xxxxxxxx

![grafik](https://user-images.githubusercontent.com/22166864/38794350-1ce30156-4155-11e8-804b-f3c526cce4d2.png)

**Comment by meangczac** [comment]
Any Inline JavaScript error will prevent the modal pop up.

**Comment by UnrealCatze** [comment]
on my side or from core?

**Comment by UnrealCatze** [comment]
when i open i an new window the link works .. only on same site doing nothing

**Comment by meangczac** [comment]
Open Developer Tools from Chrome, Refresh the page. If you see the console log has red errors, that is inline javascript error that the browser loads, and hence, the whole JS is broken and pop up is also broken and will not occur.

Recently we had a shift of files in admin_scripts.js , see if you missed that one.

**Comment by meangczac** [comment]
Will close this, it's very subjective issue to site to site.

**Comment by UnrealCatze** [comment]
for 5 minutes i made a complete core update with the newest fles ... the error link dosent work .. no modifications!!!

**Comment by meangczac** [comment]
Open your Developer Console. 

Chrome - Right Click, Inspect -- see Console. 
Firefox - Right Click, Inspect Element (Q) -- second tab Console.

Refresh page

Any Error Text?

**Comment by UnrealCatze** [comment]
no
![grafik](https://user-images.githubusercontent.com/22166864/38919201-39a49998-42f0-11e8-82e9-a0c0b178e277.png)

this other errors comes from my affilate links that i run as a panel. This are codes directly from abay and amazon where i am affiliate partner

after i refresh and look came a new error
![grafik](https://user-images.githubusercontent.com/22166864/38919294-7e1b8ee2-42f0-11e8-9c6e-35c5e4e433c8.png)

**Comment by UnrealCatze** [comment]
this is my panel what i run
`<?php
/***************************************************************************
 *   AFFILIATE PANEL                                                       *
 *                                                                         *
 *   Copyright (C) 2018 Catzenjaeger                                       *
 *   www.AlienCollectors.com                                               *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 ***************************************************************************/
if (!defined("IN_FUSION")) { die("Access Denied"); }

add_to_head("
<script>window._epn = {campaign:5338079397};</script>
<script src='https://epnt.ebay.com/static/epn-smart-tools.js'></script>
");

add_to_footer("<div id='amzn-assoc-ad-3c24a6ff-76c5-4305-a6cb-beeb5a9f1635'></div><script async src='//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=3c24a6ff-76c5-4305-a6cb-beeb5a9f1635'>");
`

**Comment by meangczac** [comment]
try disable that first and see if it work or not, because i just tried.. the link do work.

**Comment by UnrealCatze** [comment]
ok thats my problem. But my problem is the codes from ebay and amazon are fixed. I have this from thiers partner networks

here from ebay
![grafik](https://user-images.githubusercontent.com/22166864/38921342-d1401db8-42f5-11e8-9027-4aa34506506c.png)

so have you a idea how can solve my problem? The affilate links i need.

**Comment by meangczac** [comment]
Yes but you must let me know first if you turn off that -- will the link work or not. We dont have a scope now to understand the cause of the error in the first place.

**Comment by UnrealCatze** [comment]
ups sorry ... yes link work now when i deactivate my panel

here the code from amazon
![grafik](https://user-images.githubusercontent.com/22166864/38921693-a3251874-42f6-11e8-8e6b-c7faa82301c7.png)
Copy the JavaScript code below and integrate into the footer/before the end tag of the body of your website.

**Comment by meangczac** [comment]
> Copy the JavaScript code below and integrate into the footer/before the end tag of the body of your website.

Yep. That is the way. We have a function just for that.

````
add_to_footer("<div id='amazaon-......................</script>");
````

**Comment by UnrealCatze** [comment]
ok and where i have to put in this? one must in header one in footer
maincore? themes/templates? includes? 
thank you for help @FrederickChan :)

**Comment by meangczac** [comment]
what is it for?

**Comment by UnrealCatze** [comment]
i need this for affiliate links to ebay and amazon. This codes comes from amazon and ebay and must be add to my footer/header .. but where? witch folder/file? ... maincore maybe? otr what function you meaning?
