### ISSUE TITLE
Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in xxxxxxxxxxxx/includes/dynamics/includes/form_checkbox.php on line 156

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2002]
newest core from today .
Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in xxxxxxxxxxxx/includes/dynamics/includes/form_checkbox.php on line 156

**Comment by meangczac** [comment]
I have the fix please give me 30min

Regards, Frederick

**Comment by UnrealCatze** [comment]
found it  -->"::" = delete  and replace with  "->"

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/b107fc494ae5378755fd233c2237b022856066d7
