### ISSUE TITLE
Text boxes

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2003]
**PHP Fusion Version**: 
![grafik](https://user-images.githubusercontent.com/22166864/38802328-71776538-416c-11e8-8ad8-520915689dd7.png)
![grafik](https://user-images.githubusercontent.com/22166864/38802352-825150bc-416c-11e8-9239-ab4368a1e488.png)
![grafik](https://user-images.githubusercontent.com/22166864/38802473-d1bf44ba-416c-11e8-8d9a-41c543237bfb.png)

**Comment by meangczac** [comment]
When you edit and resave it appends another blank row? or it just do double BR from initial save?

**Comment by UnrealCatze** [comment]
**old core files and old site**
**code:**
`
                    <div class="row m-0">
                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <div class="navbar-default text-smaller text-uppercase text-bold"><?= $locale['figure_423']; ?></div>
                        </div>
                        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                            <span class="small" style="word-break: break-all; word-wrap: break-word;"><?= ($info['figure']['general']['description'] ? parse_textarea($info['figure']['general']['description']) : $noInformations); ?></span>
                        </div>
                    </div>`
![grafik](https://user-images.githubusercontent.com/22166864/38915173-0d7dc3ba-42e3-11e8-99ae-250029617a82.png)
Database old system:
![grafik](https://user-images.githubusercontent.com/22166864/38915192-224a01be-42e3-11e8-97ef-dba4bdfb4a60.png)
**New site with newest core**
**code**
`// Display Description
if (!@function_exists("FLIB_Frontend_ItemDetails_Tab4")) {
	function FLIB_Frontend_ItemDetails_Tab4($informations) {
		?>
		
		<?= opentabbody("", "item_details_view_4", $informations['active-tab']); ?>
		
		
		<div class="row">
		  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 figure-details-description">
		  
		    
			<div class="content-label"><i class="fa fa-fw fa-file-text"></i> <?= $informations['locale']['viewheader-1401']; ?></div>
			
			
			<div class="content-description">
			  <?= $informations['data']['figure_description']; ?>
			</div>
			
		
		  </div>
		</div>

		
		<?= closetabbody(); ?>
		<?php
	}
}`
![grafik](https://user-images.githubusercontent.com/22166864/38915216-36fbdb64-42e3-11e8-9bba-e970d2641ad0.png)
Database new site newest core
![grafik](https://user-images.githubusercontent.com/22166864/38915531-5c13ec74-42e4-11e8-80a8-acf90c19a91c.png)

**Comment by meangczac** [comment]
That is an easy fix, just remove your nl2br
