### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2004]
I have dropdowns where I write or change a date in the database . If I do that or something more annoying, the date 16 JAN 2018 - so today is also 16e ... the month is always set to JAN and the year to 2018. Core error?

today i have update the core files with the newest

**Comment by meangczac** [comment]
Show me your codes  **_SPECIFIC_** to the dropdown and _**its array values**._

Try not to paste the whole file.

**Comment by UnrealCatze** [comment]
OK HERE WE GO.

`
			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
				
				
				<?= form_datepicker("figure_pubdate", $informations['locale']['fields-1302'], $informations['data']['figure_pubdate'], [
					"inline" => true, "placeholder" => $informations['locale']['fieldplaceholder-1302'], "type" => "date",
					"type" => "date", "showTime" => false, "date_format_js" => "YYYY MMMM", "date_format_php" => "Y F"
				]); ?>
				
			`


[figurelibBackendItems.class.php.zip](https://github.com/php-fusion/PHP-Fusion/files/1919633/figurelibBackendItems.class.php.zip)

**Comment by UnrealCatze** [comment]
can any of you professionals look here? my whole database does not work anymore ...

**Comment by meangczac** [comment]
See user_birthdate_include.php and apply the same option configuration and modify as soon as it work.

See your Database Column Type for the `figure_pubdate` if it is DATE, then use 'type'=>'date', and if it is INT(10) then no need to set type.
