### ISSUE TITLE
Unknown incoming query from somewhere in my site

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2005]
this comes on every site  - btw .. i dont have news  (not infused!)

`PDOMySQL.inc
/test/infusions/figurelib/item_details.php?item_id=893
Line: 72
6 minutes ago 	

Severity : Notice generated by user using trigger_error() function
Query Error: SELECT COUNT(news_id) FROM fusion9952D_news
Stack Trace:
#0 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(64): PDO->prepare('SELECT COUNT(ne...')
#1 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT COUNT(ne...', Array)
#2 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(90): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT COUNT(ne...', Array)
#3 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/includes/db_handlers/all_functions_include.php(127): PHPFusion\Database\Driver\PDOMySQL->count('(news_id)', 'fusion9952D_new...', '', Array)
#4 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/themes/Bootstrap/theme.php(232): dbcount('(news_id)', 'fusion9952D_new...', '')
#5 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/themes/templates/layout.php(107): render_page()
#6 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/themes/templates/footer.php(37): require_once('/var/www/vhosts...')
#7 /var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/infusions/figurelib/item_details.php(19): require_once('/var/www/vhosts...')
#8 {main}
Error Nature: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aliencollectors_com_test_.fusion9952D_news' doesn't exist`

![grafik](https://user-images.githubusercontent.com/22166864/38806883-08951664-417b-11e8-8e51-e7b45fb7413e.png)

**Comment by FrederickChan** [comment]
/var/www/vhosts/xxxxxxxxxxxxxxx.com/httpdocs/test/themes/Bootstrap/theme.php(232): dbcount('(news_id)', 'fusion9952D_new...', '')

**Comment by meangczac** [comment]
You have any panels on news activated?

**Comment by UnrealCatze** [comment]
no see here plz: 
![grafik](https://user-images.githubusercontent.com/22166864/38869093-ce614d26-4249-11e8-9388-ffcec9338e44.png)

**Comment by meangczac** [comment]
I've searched the system and only found that the only global placement for something that run universally is the search engine. See if the fix is OK, and if it is, we'll change the approach for all the files.

**Comment by UnrealCatze** [comment]
found my problem .. was on my site .. big big sorry ..
