### ISSUE TITLE
Bootstrap Theme need a Custom News Template

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2008]
faulty display at the bootstrap interface
![capture_001_17042018_105813](https://user-images.githubusercontent.com/16163102/38859549-8fe343d0-422e-11e8-81cb-26d871e1ce18.jpg)

**Comment by meangczac** [comment]
I'll make a new one for Portal type design

**Comment by karrak1** [comment]
news/templates/news.php
line 108

`$x_logic = (empty($x % 3) or empty($x % 4) ? TRUE : FALSE);`
it counts badly

**Comment by meangczac** [comment]
It means the 3rd or the 4th, 
If you print the condition 

print_p(($x % 3) or ($x % 4));

We will get the result : 0 0 1 1.

0 0 1 1 0 0 1 1 0 0 1 1

**Comment by karrak1** [comment]
yes. 
but
if news = 1
1
if news = 2
11
if news =3 
000
if news =4
0000
if news = 5
00001
if news = 6
000011
if news = 7
0000000

it should be,
look image = 3 news.

**Comment by meangczac** [comment]
Ok let’s go with loop. I will fix a template.
