### ISSUE TITLE
Problem with cyryllic letters

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#201]
Now PHP-Fusion has a problem with display of cyryllic letter И (for example, Russian "Изображения" means "Images").
In Russian sites is written that is needed to add this query directly after connect to DB:

SET CHARACTER SET ‘utf8′
or
SET NAMES ‘utf8′
Problem exists with two Russian letters: ш and И. And these letters are used in Ukrainian, Bulgarian, Kazakh and Belarusian (ш only) languages too.

**Comment by rimelek** [comment]
The default character set is utf8. I will look into that why DatabaseFactory does not set it.

send "SET CHARACTER SET 'utf8'" or "SET NAMES 'utf8'" is not recommended since "PHP 5.3.6" using PDO and the old mysql_\* library also supports "mysql_set_charset" since PHP 5.0.7.

**Comment by Rizado** [comment]
OK, but what we can do with this problem? These letters are used not in Russian only.

**Comment by rimelek** [comment]
PDO can set it in constructor and as I wrote, there is a mysql_set_charset() function for the old library. Probably I forgot to pass the charset. Please, wait some hours. I will check it at home after my work time :) ( 8-9 hours maybe )

**Comment by Rizado** [comment]
OK, I checked last version of Wordpress, this CMS uses 'set names'.

P.S. Contact with me directly, I'll show this problem for you.

**Comment by meangczac** [comment]
Rizado told me "This problem exists when I use PDO only."

**Comment by rimelek** [comment]
I tried it using PDO and without PDO, with MySQL 5.1 and 5.6. I changed the both mysql server's default character set and re-installed PHP-Fusion many times when I selected Russian language for the system. I could not reproduce this bug and I have no idea why it does not work for @rizado 

I don't want to insert a new query (set names utf8) until I don't know what happens. I need to test it more different way.

**Comment by meangczac** [comment]
Maybe relevant here, this morning when i am reshuffling the upgrade codes, i happen to come across this.. @rimelek  - https://github.com/php-fusion/PHP-Fusion/blob/9.00/administration/upgrade/upgrade-7.02-9.00.php#L340-L347. Not sure if it's any help

**Comment by rimelek** [comment]
@hien I saw your comment too late, but that would not have helped me. Thanks anyway.
