### ISSUE TITLE
Not correctly displayed E-mail on the page

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2012]
Not correctly displayed E-mail on the page
[](https://github.com/php-fusion/PHP-Fusion/issues/1968)
Now is E-mail: ML="il1=rhet>:;04axxxx5f 6/m8#'7&o9";MI=">=A5463GD=017J9IF222:IF22E:IFKH:IF22?:IFxxxxB:IFKK:IF2;E:IF22H:IFKE:IFBxxxx:IF2;K:IFKH:IF2;?:IF2;E:IFxxxxB:IF22xxxx:IF22H:G8IF222:IF22E:IFKH:IF22?:IFxxxxB:IFKK:IF2;E:IF22H:IFKE:IFBxxxx:IF2;K:IFKH:IF2;?:IF2;E:IFxxxxB:IF22xxxx:IF22H:>C=8";ML=ML.replace(/xxxx/g, '<');MI=MI.replace(/xxxx/g, '<');OT="";for(j=0;j < MI.length;j++){OT+=ML.charAt(MI.charCodeAt(j)-48);}document.write(OT);

Problem in core_functions_include.php.
587. $text = descript($text); kills the show
587. //$text = descript($text); the problem is gone.

<img width="400" alt="-2" src="https://user-images.githubusercontent.com/16386011/38939616-272069e6-434a-11e8-9059-5ad6cc1ed98b.png">

[](https://github.com/php-fusion/PHP-Fusion/issues/1968)

**Comment by meangczac** [comment]
Show me your code

**Comment by meangczac** [comment]
Let’s use me@email.com as email in your code

**Comment by RobiNN1** [comment]
In custom pages same problem, 
![sawxedfcg](https://user-images.githubusercontent.com/11664877/38940081-aa61a2e6-4329-11e8-96ae-33d6f02bb2a2.png)

![swdecfg](https://user-images.githubusercontent.com/11664877/38940130-bde9b6c8-4329-11e8-8789-e182c29060a6.png)

**Comment by FrederickChan** [comment]
Ok, now i know ... stripinput in form_sanitizer.

**Comment by FrederickChan** [comment]
we need to allow email address there.

**Comment by meangczac** [comment]
I tested news. and it runs form_sanitizer() as well, and it display well. Get back later to my findings.

**Comment by meangczac** [comment]
Found it, it was done by the fusion_parse_user(). Need to fix the regex.

**Comment by ovasclub** [comment]
On the page in admin panel:
E-mail: test@mail.ru
E-mail: test@gmail.com
The output on the site is:

> E-mail: ML="fmih14l:'70a6ro8t5=;& 9exxxx>#/";MI="H;E3=G0B81;26@>7DJ44xxxxCDJ4:4CDJ44ACDJ44xxxxCDJxxxx5CDJ4:FCDJF9CDJ4:ACDJ4:?CDJ5xxxxCDJ445CDJ449C8IDJ44xxxxCDJ4:4CDJ44ACDJ44xxxxCDJxxxx5CDJ4:FCDJF9CDJ4:ACDJ4:?CDJ5xxxxCDJ445CDJ449CHK;I";ML=ML.replace(/xxxx/g, '<');MI=MI.replace(/xxxx/g, '<');OT="";for(j=0;j < MI.length;j++){OT+=ML.charAt(MI.charCodeAt(j)-48);}document.write(OT);
> E-mail: ML="75e34hr'/;6m =&o0it:#1laf9xxxx>8";MI="JGxxxx562H=7;GAFB?C>DEE:9>DE@E9>DEE19>DEE:9>D:49>DE@39>DE@I9>DI09>DE@19>DE@L9>D4:9>DII9>DEEE9>DE@I97K>DEE:9>DE@E9>DEE19>DEE:9>D:49>DE@39>DE@I9>DI09>DE@19>DE@L9>D4:9>DII9>DEEE9>DE@I9J8GK";ML=ML.replace(/xxxx/g, '<');MI=MI.replace(/xxxx/g, '<');OT="";for(j=0;j < MI.length;j++){OT+=ML.charAt(MI.charCodeAt(j)-48);}document.write(OT);

If you disable in core_functions_include
585. //$text = descript($text);
Everything is fine
Septenary, PHP-Fusion 9.03

**Comment by meangczac** [comment]
Where at the site is the output?

**Comment by ovasclub** [comment]
I found the problem, it was included BB Code:

> !autolink | - | Turns links or email addresses into clickable hyperlinks.
If you turn it on, then the e-mail is not shown correctly

**Comment by ovasclub** [comment]
All right, if you disable
 in core_functions_include
585. //$text = descript($text)
