### ISSUE TITLE
Forum attachment does not follow settings

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2016]
**PHP Fusion Version**: 9.03
file is like 3m, system set to like 8.5mb denied at 1.43 mb.

![image](https://user-images.githubusercontent.com/4210004/39021690-29b938ca-4432-11e8-900f-fbedb52ea758.png)

**Comment by JoakimFalk** [comment]
That only fix new thread, Edit thread must also follow attach rules for forum, still locked at 1.44 mb.

**Comment by meangczac** [comment]
ok
