### ISSUE TITLE
Default search setting is not in effect

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2021]
**PHP Fusion Version**: 9.03
![image](https://user-images.githubusercontent.com/4210004/39072238-3793e086-44ea-11e8-9de8-b63d5b15e779.png)

**Comment by RobiNN1** [comment]
It works. If you are using search in the menu, it search everything because there is a default form action search.php?stype=all

**Comment by JoakimFalk** [comment]
ah yes you are right, closing ;)
