### ISSUE TITLE
submit.php?type=n

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2022]
**PHP Fusion Version**: 9.03
![image](https://user-images.githubusercontent.com/4210004/39074658-923da5aa-44f2-11e8-811b-a2b27a1daf3d.png)
Notice the bracket.

**Comment by RobiNN1** [comment]
I checked core themes, all is OK.

**Comment by meangczac** [comment]
It’s our theme pack maybe. Tomorrow I check.

**Comment by meangczac** [comment]
moved
