### ISSUE TITLE
PM - Mark as unread does not work

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2023]
**PHP Fusion Version**: 9.03
![image](https://user-images.githubusercontent.com/4210004/39076096-a6eb5f5e-44f9-11e8-9bec-f24beed6ec6d.png)

**Comment by RobiNN1** [comment]
It works (Inbox/Outbox/Archive). Tested on XAMPP - MariaDB and  Windows 10 WSL Ubuntu - MySQL.

**Comment by JoakimFalk** [comment]
I guess it is only an issue on new main then, justed tested again and no work

**Comment by RobiNN1** [comment]
Try reupload https://github.com/php-fusion/PHP-Fusion/blob/Andromeda-9.0.3/includes/classes/PHPFusion/PrivateMessages.inc

**Comment by JoakimFalk** [comment]
Tried to replace, no diff. i´ll digg in to it later. 0 errors as well.

**Comment by meangczac** [comment]
Let me handle this one. The pm on main site is running its own theme template. A simple diff check will fix this problem

**Comment by JoakimFalk** [comment]
Ok moved it
