### ISSUE TITLE
session error

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2028]
a try
`\PHPFusion\Sessions::getInstance("fusion_weblinks_view")->_write("fusion_weblinks_view", 1);`

error code:

Fatal error: Uncaught exception 'PHPFusion\Database\Exception\UndefinedConfigurationException' with message 'Unknown configuration id: sessions' in C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\DatabaseFactory.inc:171 Stack trace: #0 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Sessions.inc(187): PHPFusion\Database\DatabaseFactory::getConnection('sessions') #1 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks.php(385): PHPFusion\Sessions->_write('fusion_weblinks...', 1) #2 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks.php(150): PHPFusion\Weblinks\Weblinks->weblink_cat_navbar() #3 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks_view.php(31): PHPFusion\Weblinks\Weblinks->set_WeblinkCatInfo('1') #4 C:\xampp\htdocs\fusion\infusions\weblinks\weblinks.php(25): PHPFusion\Weblinks\WeblinksView->display_weblink() #5 {main} thrown in C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\DatabaseFactory.inc on line 171

if Sessions.inc 
line 38
    private static $_sess_key = 'session';
change
    private static $_sess_key = 'default';

C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Sessions.inc
/fusion/infusions/weblinks/weblinks.php?cat_id=1
Sor: 54
Argument 1 passed to PHPFusion\Sessions::getInstance() must be an instance of PHPFusion\string, string given, called in C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks.php on line 385 and defined

if Sessions.inc 
line 54

    public static function getInstance(string $handler) {
change
    public static function getInstance($handler) {
and 
line 154
    public function _read(string $name) {
change
    public function _read($name) {

then

C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/fusion/infusions/weblinks/weblinks.php?cat_id=1
Sor: 72

Query Error: REPLACE INTO fusiontmC3N_sessions VALUES (:name, :access, :data)
Stack Trace: 
#0 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(64): PDO->prepare('REPLACE INTO fu...') 
#1 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('REPLACE INTO fu...', Array) 
#2 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Sessions.inc(187): PHPFusion\Database\AbstractDatabaseDriver->query('REPLACE INTO fu...', Array) 
#3 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks.php(385): PHPFusion\Sessions->_write('fusion_weblinks...', 1) 
#4 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks.php(150): PHPFusion\Weblinks\Weblinks->weblink_cat_navbar() 
#5 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks_view.php(31): PHPFusion\Weblinks\Weblinks->set_WeblinkCatInfo('1') 
#6 C:\xampp\htdocs\fusion\infusions\weblinks\weblinks.php(25): PHPFusion\Weblinks\WeblinksView->display_weblink()
#7 {main}
Error Nature: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1

if Sessions.inc 
line 185
        $query = "REPLACE INTO ".DB_SESSIONS." VALUES (:name, :access, :data)";
change
        $query = "REPLACE INTO ".DB_SESSIONS." (session_id, session_start, session_data) VALUES (:name, :access, :data)";

it is work.., but I do not know whether it is good

**Comment by karrak1** [comment]
if 
`$cookie_expiry = time() + 7 * 24 * 3600;
 \PHPFusion\Sessions::getInstance("fusion_weblinks_view")->_clean($cookie_expiry);`
then

C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc
/fusion/infusions/weblinks/weblinks.php?cat_id=1
Sor: 72

Query Error: DELETE FROM fusiontmC3N_sessions WHERE access < :old
Stack Trace: 
#0 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(64): PDO->prepare('DELETE FROM fus...') 
#1 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('DELETE FROM fus...', Array) 
#2 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Sessions.inc(235): PHPFusion\Database\AbstractDatabaseDriver->query('DELETE FROM fus...', Array) 
#3 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks.php(385): PHPFusion\Sessions->_clean(1525077937) 
#4 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks.php(150): PHPFusion\Weblinks\Weblinks->weblink_cat_navbar() 
#5 C:\xampp\htdocs\fusion\infusions\weblinks\classes\weblinks\weblinks_view.php(31): PHPFusion\Weblinks\Weblinks->set_WeblinkCatInfo('1') 
#6 C:\xampp\htdocs\fusion\infusions\weblinks\weblinks.php(25): PHPFusion\Weblinks\WeblinksView->display_weblink()
#7 {main}
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'access' in 'where clause'

line 233
        $query = "DELETE FROM ".DB_SESSIONS." WHERE access < :old";
change
        $query = "DELETE FROM ".DB_SESSIONS." WHERE session_start < :old";

**Comment by karrak1** [comment]
new bug
new install, after the installation is completed.
Catchable fatal error: Argument 1 passed to PHPFusion\Sessions::getInstance() must be an instance of PHPFusion\string, string given, called in C:\xampp\htdocs\fusion\maincore.php on line 58 and defined in C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Sessions.inc on line 54

**Comment by meangczac** [comment]
ok, i'll make a fresh install tomorrow.

@karrak1 , the sessions is suppose to be set as:

$_SESSION['faq'] = 'something you want to store'
unset($_SESSION['faq']);

The $_SESSION will go to DB instead of file.

Each user 1 row.

No class calls should be done. At least my intent is that.

**Comment by karrak1** [comment]
the error php version 5.6.30 is affected.
php 7.0.29 good. (delete core_tables.inc -> session_key
 or session.inc add :key data the _write function
)

**Comment by meangczac** [comment]
Please make the change for us.

**Comment by RobiNN1** [comment]
Done. Chcek last commit

**Comment by karrak1** [comment]
New install
php 5.6.30

Catchable fatal error: Argument 1 passed to PHPFusion\Sessions::getInstance() must be an instance of PHPFusion\string, string given, called in C:\xampp\htdocs\fusion\maincore.php on line 58 and defined in C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Sessions.inc on line 54

php 7.0.18 good.

**Comment by meangczac** [comment]
Ok I will recheck why is it not an instance
