### ISSUE TITLE
PM seems to not respect settings in limits

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2029]
**PHP Fusion Version**: 9.03

We had 20 as limit for users on main, I still got PM from non admins. Admins need overrides from the standard values but members inbox, outbox, archive all have each setting that need to be followed by the system.

I am not convinced that there is a clever thing to bounce messages on full inboxes. Perhaps a auto sanitation system. oldest message gets deleted from the inbox when a new one arrives if the limits are breeched. Adding it to roadmap for thought anyway.

**Comment by meangczac** [comment]
moved
