### ISSUE TITLE
Upgrade 9.0 to latest

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#2036]
Table Prefix and Cookie Prefix are not filled automatically from config.php

![sxedcrfgvf](https://user-images.githubusercontent.com/11664877/39128151-5692814e-4707-11e8-97bd-7fa976be09eb.png)

And lot of errors 

Notice: Query Error: CREATE TABLE fusionjp53m_admin (admin_id MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT, admin_rights CHAR(4) NOT NULL, admin_image VARCHAR(50) NOT NULL, admin_title VARCHAR(50) NOT NULL, admin_link VARCHAR(100) NOT NULL DEFAULT 'reserved', admin_page TINYINT(1) UNSIGNED NOT NULL DEFAULT '1', PRIMARY KEY (admin_id)) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci<br/>Stack Trace: #0 C:\xampp\htdocs\test\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(68): PDOStatement->execute() #1 C:\xampp\htdocs\test\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('CREATE TABLE fu...', Array) #2 C:\xampp\htdocs\test\includes\db_handlers\all_functions_include.php(113): PHPFusion\Database\AbstractDatabaseDriver->query('CREATE TABLE fu...', Array) #3 C:\xampp\htdocs\test\includes\classes\PHPFusion\Installer\Steps\DatabaseSetup.inc(196): dbquery('CREATE TABLE fu...') #4 C:\xampp\htdocs\test\includes\classes\PHPFusion\Installer\ in C:\xampp\htdocs\test\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc on line 72

Notice: Query Error: CREATE TABLE fusionjp53m_admin (admin_id MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT, admin_rights CHAR(4) NOT NULL, admin_image VARCHAR(50) NOT NULL, admin_title VARCHAR(50) NOT NULL, admin_link VARCHAR(100) NOT NULL DEFAULT 'reserved', admin_page TINYINT(1) UNSIGNED NOT NULL DEFAULT '1', PRIMARY KEY (admin_id)) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci<br/>Stack Trace: #0 C:\xampp\htdocs\test\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(68): PDOStatement->execute() #1 C:\xampp\htdocs\test\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('CREATE TABLE fu...', Array) #2 C:\xampp\htdocs\test\includes\db_handlers\all_functions_include.php(113): PHPFusion\Database\AbstractDatabaseDriver->query('CREATE TABLE fu...', Array) #3 C:\xampp\htdocs\test\includes\classes\PHPFusion\Installer\Steps\DatabaseSetup.inc(196): dbquery('CREATE TABLE fu...') #4 C:\xampp\htdocs\test\includes\classes\PHPFusion\Installer\ in C:\xampp\htdocs\test\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc on line 72
--

1 | 0.0008 | 397520 | {main}( ) | ...\install.php:0
2 | 0.0323 | 526608 | PHPFusion\Installer\Install_Core->install_phpfusion( ) | ...\install.php:22
3 | 0.0323 | 526608 | PHPFusion\Installer\Install_Core->get_InstallerContent( ) | ...\Install.core.inc:327
4 | 0.0323 | 526856 | PHPFusion\Steps\InstallerDbSetup->__view( ) | ...\Install.core.inc:357
5 | 0.0323 | 526856 | PHPFusion\Steps\InstallerDbSetup->dispatch_tables( ) | ...\DatabaseSetup.inc:34
6 | 0.3310 | 958016 | dbquery( ) | ...\DatabaseSetup.inc:196
7 | 0.3310 | 958016 | PHPFusion\Database\Driver\PDOMySQL->query( ) | ...\all_functions_include.php:113
8 | 0.3311 | 960928 | PHPFusion\Database\Driver\PDOMySQL->_query( ) | ...\AbstractDatabaseDriver.inc:312
9 | 0.3315 | 982136 | trigger_error ( ) | ...\PDOMySQL.inc:72

After upgrade

![werthgy](https://user-images.githubusercontent.com/11664877/39128853-30a9dcc8-4709-11e8-8f1f-84349144aad4.png)

Server: latest XAMPP (Apache 2.4.33, MariaDB 10.1.31, PHP 7.2.4)

**Comment by meangczac** [comment]
Yes only happens on MariaDB.  I need to check the output again. Something is off already since last I check in beta.

**Comment by RobiNN1** [comment]
0 errors
WSL Ubuntu
Apache/2.4.33
PHP 7.2.4
MySQL 5.7.22

**Comment by RobiNN1** [comment]
MariaDB OK - XAMPP

Just this need fix

> Table Prefix and Cookie Prefix are not filled automatically from config.php
