### ISSUE TITLE
Header column 3 preset (display article ) crashes

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#204]
Fatal error: Call to a member function rowCount() on a non-object in includes/classes/PHPFusion/Database/Driver/PDOMySQL.php on line 143

![debwidget](https://cloud.githubusercontent.com/assets/4210004/9654632/56b75e74-522c-11e5-8e6b-c197466ae49a.png)

**Comment by meangczac** [comment]
> .> dbrows() unknown???

**Comment by JoakimFalk** [comment]
No, issue is still on for dbrows, making a new issue
