### ISSUE TITLE
Token does not allow multiple instances

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2040]
**PHP Fusion Version**: 9.03
As an Administrator you often open new tab instances. 
I just poped like 5 since I need to update forum permissions in all but you get token error.
I also blew a news item like this earlier because of multiple instances. 

We really need a solution to allow more than 1 instance for Admins at the very least anyway.

**Comment by meangczac** [comment]
todo: Add a number of valid tokens in system security settings.
