### ISSUE TITLE
Function "Hide Email"-does not work

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2043]
Function "Hide Email"-does not work

![-2](https://user-images.githubusercontent.com/16386011/39182036-4a6e16ae-47dd-11e8-93ce-65190ada8888.jpg)

**Comment by karrak1** [comment]
only admin can see it.

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/issues/1994
