### ISSUE TITLE
Administration Control Panel (New set)

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2044]
Warning: include(../locale/English/admin/errors.php): failed to open stream: No such file or directory in C:\OSPanel\domains\ovas0424\includes\classes\PHPFusion\Locale.inc on line 58

Warning: include(): Failed opening '../locale/English/admin/errors.php' for inclusion (include_path='.;c:/ospanel/modules/php/PHP-7.2-x64;c:/ospanel/modules/php/PHP-7.2-x64/PEAR/pear') in C:\OSPanel\domains\ovas0424\includes\classes\PHPFusion\Locale.inc on line 58

![-2](https://user-images.githubusercontent.com/16386011/39249800-45079d18-48c1-11e8-8b36-247d0a1582c8.jpg)

**Comment by meangczac** [comment]
you dont have the files uploaded to your server?

**Comment by ovasclub** [comment]
Files by PHP-Fusion 9.03
Server: Open Server
PHP-7.2-x64
New installation

**Comment by RobiNN1** [comment]
Try reupload files

**Comment by ovasclub** [comment]
Updated the files. The problem has disappeared.

**Comment by ovasclub** [comment]
The problem returned on Andromeda-9.0.3
