### ISSUE TITLE
Error upgrading PHP-Fusion to 9.0

### ISSUE THREAD

**Issue by jameswill** [PHPFusion/PHPFusion#2045]
I am getting issue while upgrading my existing installation of 7.02.07 to 9.0.

I have followed all the upgrade steps from https://www.php-fusion.co.uk/infusions/wiki/documentation.php?page=220 however on visiting {URL to Fusion}/install.php in "Database settings and Server paths" step, when I select database driver as "MySQLi" it gives error stating " There was an error while processing your request " and the driver automatically sets to PDO by default. Also the all the other values are prefilled except Cookie prefix. I am using PHP 5.5 and 5.6 and MySQL > 5.6 and linux OS.

Can anyone please let me know what is causing this issue ?
![fusion1](https://user-images.githubusercontent.com/6368036/39395670-c8117956-4afe-11e8-8f49-50856ee30735.png)

**Comment by JoakimFalk** [comment]
There are known issues with mysqli atm, you need to use PDO, min requirement is - PHP 5.5.08.

**Comment by jameswill** [comment]
Is there any ETA for solving this issue ? or can you remove that option till it resolves ? As many users will try to upgrade through MySQLi driver and will get that error.

Also why cookie prefix is not pre-filled from config_temp.php during upgrade ?

**Comment by meangczac** [comment]
@jameswill , the cookie prefix is autofill following your old config file.
MYSQLI driver is inconsistent with the abstract rules of our database Factory and require further inspection and testing. The driver has problem with MariaDB, which most hosting server use as a standard now.

**Comment by meangczac** [comment]
There is a duplicate issue on this one. I will close this issue and move the issue to https://github.com/php-fusion/PHP-Fusion/issues/2036
