### ISSUE TITLE
Comments on news are not displayed

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2046]
Comments on news are not displayed

![-2](https://user-images.githubusercontent.com/16386011/39438759-05584dc0-4cc7-11e8-83fa-4b9f9fce9aa1.jpg)

**Comment by karrak1** [comment]
the failure occurs on the surface bootstrap and septenary.
and
does not display bbcodes as well
Nebula theme == good.

**Comment by karrak1** [comment]
There is no change.
the fault existed

**Comment by karrak1** [comment]
sorry .. cache :(
