### ISSUE TITLE
Translations Server can not be installed

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2051]
Translations Server can not be installed.
This item cannot be infused

Notice: Query Error: CREATE TABLE fusion52Z5e_translation_package ( package_id	MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,	package_name	TEXT	NOT NULL,	package_meta	TEXT	NOT NULL, package_description	TEXT	NOT NULL,	package_datestamp INT(10) UNSIGNED NOT NULL DEFAULT '0', package_status TINYINT(1) NOT NULL DEFAULT '0', PRIMARY KEY(package_id), KEY package_name (package_name, package_meta, package_description) ) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci
Stack Trace: #0 C:\OSPanel\domains\ovas0501\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(68): PDOStatement->execute() #1 C:\OSPanel\domains\ovas0501\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('CREATE TABLE fu...', Array) #2 C:\OSPanel\domains\ovas0501\includes\db_handlers\all_functions_include.php(113): PHPFusion\Database\AbstractDatabaseDriver->query('CREATE TABLE fu...', Array) #3 C:\OSPanel\domains\ovas0501\includes\clas in C:\OSPanel\domains\ovas0501\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc on line 72

**Comment by RobiNN1** [comment]
Work is in progress. Do not sync repo

**Comment by meangczac** [comment]
This Infusion is not part of the package.
It’s an experimental application I built. Please remove.

Thanks.

> --

Regards,
Frederick MC Chan
Intl' Business
Catessens Holdings Sdn Bhd

**Comment by RobiNN1** [comment]
@FrederickChan remove about.php and frontpage.php files in root or is just not complete?

**Comment by meangczac** [comment]
Remove please. Some files got mixed up
-- 

Regards,
Frederick MC Chan
Intl' Business
Catessens Holdings Sdn Bhd
