### ISSUE TITLE
We need standards in the locales

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2052]
https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=39198

![image](https://user-images.githubusercontent.com/4210004/39472900-63f56bc6-4d4c-11e8-8645-18acfe611162.png)

**Comment by RobiNN1** [comment]
Perhaps just add for all locale files some prefix

**Comment by meangczac** [comment]
The standards I wish to add to localization file is:

1. 3 letter prefix using the USER_RIGHTS will be best. For example, FAQ has rights of FAQ so, the locale goes like $locale['FAQ_0000']

2. 4 digit for keys. This gives us a max of 9999 in indexing.

3. 2 digits for each set, followed by a comment for next set.
````
// Listing
$locale['FAQ_0000'] = 'Frequent Asked Question';
$locale['FAQ_0100'] = '';
// Categories
$locale['FAQ_0101'] = '';
````
This leaves some room for reserved numbering in case we want to add something to it in the future.

**Comment by JoakimFalk** [comment]
Yes that is the one standard we shall use.
