### ISSUE TITLE
Fatal error: Call to undefined function fusion_get_function() in k:\files\administration\settings_main.php on line 173

### ISSUE THREAD

**Issue by Synthese** [PHPFusion/PHPFusion#2054]
https://github.com/php-fusion/PHP-Fusion/blob/b4eba2a3f276b720e1b2c6f0f4adec88e2d02d14/administration/settings_main.php#L173

**Comment by karrak1** [comment]
I have no such mistake

**Comment by RobiNN1** [comment]
Reupload themes/templates/render_functions.php
