### ISSUE TITLE
Token Error Reports.

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2055]
I have renabled some parts and modified the token implementation. There are robots still sinking into main site. I suspect the Token is not working in a certain manner.

Please check if the latest change do work, and if have issue please report here.

**Comment by ovasclub** [comment]
Problem with registration

**Comment by RobiNN1** [comment]
It works. Are you added  form_tokens and value 1 into settings DB ?

**Comment by ovasclub** [comment]
I have on the site
![-2](https://user-images.githubusercontent.com/16386011/39675713-0645c776-5181-11e8-90f3-6e0c11be3fd9.jpg)
No registration
On Open Server
Need activacition
![-4](https://user-images.githubusercontent.com/16386011/39675789-0dfe9c62-5182-11e8-8c6f-aa940d0e8ff1.jpg)

![-6](https://user-images.githubusercontent.com/16386011/39675910-438874ce-5183-11e8-84d3-da4fe1df5568.jpg)

**Comment by RobiNN1** [comment]
Admin Dashboard > Settings > Registration Settings
Turn off these settings:
Use email verification for registration?  No
New members activated by admin? No

**Comment by meangczac** [comment]
I suspect that no page redirect was done. 

How did that screen occur? What steps was taken?

**Comment by balin50** [comment]
registration problem
token.php
/registration
Line: 184
Severity : Run-time notices
Undefined index: csrf_tokens

token.php
/registration
Line: 185
Severity : Non fatal Runtime Errors
array_rand() expects parameter 1 to be array, null given

this is bad idea
Use email verification for registration? No
New members activated by admin? No

**Comment by meangczac** [comment]
**It is impossible to have undefined index for csrf tokens.**

Undefined index: csrf_tokens

This error only happens when you update to Andromeda files, without changing the Database. I will make a patch here later. Give me some time to crunch it out.

https://github.com/php-fusion/PHP-Fusion/commit/10af5304cd401d0d546a08aba65340bd8c312133
