### ISSUE TITLE
PM issued

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2057]
It has been reported that PM does not work on clean install.

**Comment by RobiNN1** [comment]
That's weird. I have clean install on both test servers and it works. Yesterday, I updated CzechNSS test server and all works.

**Comment by djdandi** [comment]
PM works but I have a problem sending messages from contact.php
I get this error and the message is not sent.
There was an error while processing your request
Internal error: cannot send your message.

**Comment by dtechniker** [comment]
look under: 
Undefined index: siteusername / siteemail #2076
that could solve the problem.
With this error, the mail templates do not get senders, because they can not be pushed into the database.

**Comment by RobiNN1** [comment]
This issue refer to https://github.com/php-fusion/PHP-Fusion/issues/2023

**Comment by RobiNN1** [comment]
Only on Main not work.
