### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2061]
this error will be displayed for each submission
php 5.6.30

Token 1.1525839274.3d0107b589307d8688f1d908738716075c4497d5d57d06183decff0787a4c45a has been consumed

**Comment by ovasclub** [comment]
You need to make changes in the database **_settings** correctly:

> ('user_name_ban', ''),
> ('database_sessions', '1'),
> ('form_tokens', '1');

Not correctly:
> ('user_name_ban', '');
> ('database_sessions', '1'),
> ('form_tokens', '1');

The problem I had was >> ; <<

**Comment by karrak1** [comment]
where you see this bug, I can not find it

**Comment by ovasclub** [comment]
Make a new installation of the site on Open Server.
Copy the _sessions table and the token to the database of your site.
Add _settings to the table:
('domain_server', ''),
('database_sessions', '1'),
('form_tokens', '1');

**Comment by RobiNN1** [comment]
It's not error, It's just alert. Maybe for debug
