### ISSUE TITLE
Applying Filters in Member Admin does nothing

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2062]
The selected filter is not saved after push either.
![image](https://user-images.githubusercontent.com/4210004/39871112-1f2bd4fc-5464-11e8-9c29-9f152d7873f7.png)

**Comment by RobiNN1** [comment]
It works

![eddrfghj](https://user-images.githubusercontent.com/11664877/40391610-3188049a-5e19-11e8-97a9-eb405109bb5a.png)

**Comment by ovasclub** [comment]
Do not show banned

![-2](https://user-images.githubusercontent.com/16386011/40397677-a215d61a-5e55-11e8-8c62-0e0bc30df8b8.jpg)

**Comment by meangczac** [comment]
Just confirmed it works. 

See this patch: https://github.com/php-fusion/PHP-Fusion/commit/10af5304cd401d0d546a08aba65340bd8c312133

Distribute to anyone running Andromeda and having this problem.
