### ISSUE TITLE
Localhost after installing PHP 7

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#2064]
On a local PC in a localhost, they report this problem:

Fatal error: Uncaught Error: Call to undefined function PHPFusion\Database\Driver\mysqli_connect() in /var/www/html/includes/classes/PHPFusion/Database/Driver/MySQLi.inc:176 Stack trace: #0 /var/www/html/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(71): PHPFusion\Database\Driver\MySQLi->connect('localhost', 'root', 'xxxx', 'phplocal', Array) #1 /var/www/html/includes/classes/PHPFusion/Database/DatabaseFactory.inc(222): PHPFusion\Database\AbstractDatabaseDriver->__construct('localhost', 'root', 'Didina4046', 'phplocal', Array) #2 /var/www/html/includes/db_handlers/all_functions_include.php(191): PHPFusion\Database\DatabaseFactory::connect('localhost', 'root', 'xxxx', 'phplocal', Array) #3 /var/www/html/maincore.php(40): dbconnect('localhost', 'root', 'xxxx', 'phplocal') #4 /var/www/html/index.php(18): require_once('/var/www/html/m...') #5 {main} thrown in /var/www/html/includes/classes/PHPFusion/Database/Driver/MySQLi.inc on line 176

Written: The mbstring extension is missing. Please check your PHP configuration.

**Comment by RobiNN1** [comment]
Change driver to PDO and install mbstring (apt get install php7.0-mbstring)

**Comment by meangczac** [comment]
See also there is an existing task to redo the MYSQLI driver under PHP7.0
#1991

**Comment by Kvido** [comment]
Yes, OK.
