### ISSUE TITLE
Theme Footers do not parse editor options

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2065]
A minimum would be nl2b(parseubb($string));
https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=39216&pid=204894#post_204894

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/1cee9ae93b0b0ae5bb5e8aa761874e463d466039
