### ISSUE TITLE
Admin area Editing news is not working

### ISSUE THREAD

**Issue by Synthese** [PHPFusion/PHPFusion#2066]
In the admin area I can not enter the news, news_admin.php is not loaded. The link under content is not there.
After submitting news, the submission is displayed, but can not be edited.
Do not know where to look for the error.
Sorry for my bad english I am a bit older, but good German.

**Comment by Synthese** [comment]
Display of News submissions is back, here was an Error in the Database. The rights under link visibility had to be set to -101. Why, I did not know why it was changed.
However, the link to edit still does not work.
So with submitted news can not be published

**Comment by RobiNN1** [comment]
PF9 version? In DEV it's OK.

**Comment by Synthese** [comment]
ok I had the version 9.0.3 from 13.5, reload it again and make it new on it. Thx

**Comment by Synthese** [comment]
After playing the new files and changing the theme to default, everything was back, could then switch back to Atomx where the colors changed. Will have to investigate this yet. Thank you for your help.
