### ISSUE TITLE
Issue: Upgrading - Error fusionscan/infusion.php

### ISSUE THREAD

**Issue by LaocheXe** [PHPFusion/PHPFusion#2067]
Line 32, Missing file "infusion_db.php"; - include INFUSIONS."fusionscan/infusion_db.php";

Checked in FTP - fusionscan folder has locale folder, index, and infusion.php - no infusion_db.php

**Comment by RobiNN1** [comment]
Just create infusion_db.php
Example:  https://github.com/php-fusion/PHP-Fusion/blob/Andromeda-9.0.3/infusions/articles/infusion_db.php

This is not Andromeda 9.0.3 issue. Next time use Forum.
