### ISSUE TITLE
Add Administrator is not work

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2068]
Add Administrator is not work

![-3](https://user-images.githubusercontent.com/16386011/40556667-4fbd043a-606f-11e8-8fca-fdfb111f06eb.jpg)

Andromeda-9.0.3

**Comment by karrak1** [comment]
it works for me.
![capture](https://user-images.githubusercontent.com/16163102/40562471-63473d58-6061-11e8-98dc-e73f2406bedf.jpg)

**Comment by Synthese** [comment]
In current Dev it goes without problems

**Comment by ovasclub** [comment]
Error	
PDOMySQL.inc
/includes/dynamics/assets/users/users.json.php?allow_self=true&q=t&_=1527299034693
Line: 72

Stack Trace: #0 /home/ovasclub/public_html/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(68): PDOStatement->execute() #1 /home/ovasclub/public_html/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT user_id,...', Array) #2 /home/ovasclub/public_html/includes/db_handlers/all_functions_include.php(113): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT user_id,...', Array) #3 /home/ovasclub/public_html/includes/dynamics/assets/users/users.json.php(35): dbquery('SELECT user_id,...', Array) #4 {main}
Error Nature: SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list

**Comment by meangczac** [comment]
Please do not miss the git commit message. See the file in concern, click
history and you will see the latest patch git will contain the instruction
for the patch.

Go to PhpMyAdmin, in your DB_USERS table, user_name click "Full Text" to
add a full text indexing to that particular column.

**Comment by ovasclub** [comment]
Thank you so much. Your instruction helped.
Add Administrator is working
