### ISSUE TITLE
Error registrace

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#2069]
TEST, Andromeda 9.0.3 - GitHub 25.05.2018, localhost domácí PC:
Nefunguje registrace uživatele
Hláška při vypnutém (NO) "Nové uživatelé aktivuje administrator!:
byla
There was an error while processing your request
Incorrect validation code.

Dalčí varianta:
Povolit registraci systému - ANO
Povolit ověřování e-mailem - AQNO
Nové uživatele aktivuje admin - ANO
Hláška:
Activation email could not be sent.
Please contact the Site Administrator.

**Comment by Kvido** [comment]
Now signing up for the user already at Andromeda 9.0.3 (test.phpfusion.cz) works.
The login email came.
The user has successfully activated his / her account.
ALE ERROR - Admin can not activate from a separate side column on HomePage:
https://test.phpfusion.cz/administration/members.php.?aid=2408708744e31f9e&status=2

The second activation option through the Administration was successful:
https://test.phpfusion.cz/administration/members.php?aid=2408708744e31f9e&status=2
This activation was successful. User has emailed:

Your PHP-Fusion 9 account has been activated.
You can now sign in with your username and password.
Regards,
PHP-Fusion CZ support

**Comment by RobiNN1** [comment]
duplicate
