### ISSUE TITLE
New Error found: Cannot find any token for storage: 1.1527821537.1c459c9e6c7f8d4a656543ab9bc69479e1307913f31e816183a31667887cb9fc

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#2070]
Hi Developers,

I found a bug and this is the last github branch, if I want to create a new topic in the forum. This error is shown to me in the header.

    Cannot find any token for storage: 1.1527821537.1c459c9e6c7f8d4a656543ab9bc69479e1307913f31e816183a31667887cb9fc
There was an error while processing your request

Can you take a closer look and fix it if necessary.

Thanks in advance.

**Comment by meangczac** [comment]
Thanks, will let you know.

**Comment by ghost** [comment]
Thanks @FrederickChan !

**Comment by meangczac** [comment]
Token storage issue on Andromeda need few database alterations. To determine whether you need this is when you go to security settings page whether you have error or not. There are 1 new DB, and 3 new $settings entries which probably best to run upgrade.

**Comment by ghost** [comment]
I only get a blank page under `/upgrade/index.php`. Can you please check that with the current Github Branch? Thank you. Then I'll do an upgrade and we'll see what happens.

P.S. and in the Backend under System Settings i have `No upgrades available` .

**Comment by ghost** [comment]
I want to update the settings and see this:

```
Can not find any token for storage: 1.1528597408.36bcee65079b070d83bf8e7f60fb2af6f39578e532977cc8e19ce8bf0f73938a
There was an error while processing your request
Database update error occurs: Settings were not Updated!
Please enter your public and private reCAPTCHA key!
Settings successfully updated
```

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/10af5304cd401d0d546a08aba65340bd8c312133
