### ISSUE TITLE
Database Backup-It is not possible to create in adminpanel (very large table)

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2072]
On OSPanel is OK
On my site is not possible
There are clones of my site, there is the same picture

![-2](https://user-images.githubusercontent.com/16386011/41100603-a4db918e-6a83-11e8-859f-f5196cf280fb.jpg)

**Comment by meangczac** [comment]
Try backup 1 table. See if it works. If it do, backup 5 table, 10 table until you fail. Tell us the results

**Comment by Synthese** [comment]
I have the same problem with one table goes, with 2tables goes, with 3 tables goes too. With 4 tables error when I want to save table praefix_admin alone error. This Massage is output.
#---------------------------------------------------------- # PHP-Fusion SQL Data Dump # Database Name: `d02a5641` # Table Prefix: `fu_` # Date: `09/06/2018 12:26` #---------------------------------------------------------- # # Structure for Table `fu_admin` # DROP TABLE IF EXISTS `fu_admin`; CREATE TABLE `fu_admin` ( `admin_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT, `admin_rights` char(4) COLLATE utf8_unicode_ci NOT NULL, `admin_image` varchar(50) COLLATE utf8_unicode_ci NOT NULL, `admin_title` varchar(50) COLLATE utf8_unicode_ci NOT NULL, `admin_link` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'reserved', `admin_page` tinyint(1) unsigned NOT NULL DEFAULT '1', PRIMARY KEY (`admin_id`) ) ENGINE=MyISAM AUTO_INCREMENT=80 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; # # Table Data for `fu_admin` #
Fatal error: Call to undefined method mysqli_result::columnCount() in /www/htdocs/v158214/gsrc/administration/db_backup.php on line 61

**Comment by ovasclub** [comment]
Does not work only with the fusion*****_user table, with others everything is fine

**Comment by meangczac** [comment]
@Synthese 

in /your-php-fusion/config.php file, see that $pdo_enabled is set to true.

**Comment by meangczac** [comment]
@ovasclub 
Does not work only with the fusion*****_user table, with others everything is fine

Problem with that administration now is that it refuses to connect to a large table. I had problem when migrating old v7 to v9 too. 

Can you tell how big is the table?

![capture](https://user-images.githubusercontent.com/4078041/41192353-e63060d6-6c2e-11e8-8c9c-8938991a1f0a.JPG)

Maybe we can put a check and see how to get over that problem.

**Comment by ovasclub** [comment]
The problem is probably that the table is large

![-2](https://user-images.githubusercontent.com/16386011/41192603-1e710692-6c22-11e8-86b4-b84cdc87f923.jpg)

**Comment by meangczac** [comment]
Yes we have that issue. It's SQL execution timeout preventing full download of all tables. I will look into this matter. Keep this issue open.

For now, you can manually export it that table alone. I'm sure it's not a pressing concern. 

I will address this issue before we release Andromeda.

**Comment by Synthese** [comment]
Thx @FrederickChan everything works without errors
