### ISSUE TITLE
Nomination for Name of Repository for Next Branch

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2073]
The name must be associated with "Astro, Space, Science, Technology, High-Tech Terminology".

The next name will start with "**B**"

Let's come up with 10-15 names before we decide together via poll. 

We will keep this between Developers only. Thats why I post here, not on main site. This is dev branch 👍

**Comment by meangczac** [comment]
I named Andromeda, so I will naturally forfeit my turn this round. So please have your share.

**Comment by Ardakilic** [comment]
First things come to my mind:

* Borealis
* Bionic
* Battlestar

**Comment by kot2007** [comment]
Betelgeuse
Blueshift
Binary
Beyond
Big Bang :)

**Comment by ovasclub** [comment]
Bastion
Bestrow
Bolt
Banzai
Belomor
Bezdna
Babayaga
Baskarma

**Comment by meangczac** [comment]
@RobiNN1, @Dahlgren, @Talocha , @rizado

**Comment by helmuthm** [comment]
Baham
Baten Kaitos
Becrux
Beid
BELLATRIX
BETELGEUSE
Botein
Brachium
.................
Star names above - I like Bellatrix and Brachium ;-)

**Comment by meangczac** [comment]
Ok I will set up the name up in the forum.

https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=39278

**Comment by RobiNN1** [comment]
I can't access to thread

**Comment by dtechniker** [comment]
Burning ....
             sun
             star
             asteriod

**Comment by meangczac** [comment]
Discord Server is open for PHP-Fusion. Please join Discord by clicking this link - https://discord.gg/WNvqrxJ 
We have a developer core team channel.
