### ISSUE TITLE
New User Does not receive a registration E-mail.

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2074]
New User Does not receive a registration E-mail.
User can not be activated by E-mail.

**Comment by meangczac** [comment]
Sendmail fail?

**Comment by ovasclub** [comment]
Now:
Letter came
Through the link in the email, the account is not activated.

![-2](https://user-images.githubusercontent.com/16386011/41669699-2fef6a8e-74d4-11e8-8546-bb5d481a868f.jpg)

**Comment by ovasclub** [comment]
Updated
Everything is working
