### ISSUE TITLE
Web Link URL - Please enter a valid URL

### ISSUE THREAD

**Issue by dtechniker** [PHPFusion/PHPFusion#2075]
Each URL is reported as invalid. No link can be entered. Browser (Opera 53, Win10 Edge)

**Comment by karrak1** [comment]
you have an internet connection? (online)
it works for me.

**Comment by JoakimFalk** [comment]
We used to have http(s) required, but I did request a removal of that,  did you try with or without http,

**Comment by ovasclub** [comment]
At me such problem:
I create two links, but I can edit only the first one.
Click on the "Сhange" button of the second link, toggles on the first link change
Error Log:
echo form_checkbox('check_all', $this->locale['WLS_0206'], '', ['class' => 'm-b-0', 'reverse_label' => TRUE]);
Line 519 -- 8 секунд назад
Undefined index: WLS_0206

**Comment by dtechniker** [comment]
So, i'm creating a new web link. Enter link name, link URL and write test in the description.
Then there is always the error message: -> There was an error while processing your request
Web Link URL - Please enter a valid URL <-

What I used as a URL does not matter.

http://google.com
https://google.com
https://www.google.com
http://www.google.com

Everything the same mistake. ( weblinks_admin.php or submit.php?stype=l )

(Sorry I used partial Google translator ...)

**Comment by meangczac** [comment]
It will check url using cURL, maybe server is configured not to allow?

**Comment by dtechniker** [comment]
hm, i use bplaced.net, i dont now.

*
On the server PHP-Fusion-7.02.07 runs without this kind of problem.

I checked, the server does not support this. What can you do there?

**Comment by dtechniker** [comment]
@ovasclub your prob is easy to fix.  Your translation pack miss this entry = WLS_0206. 
on English -> $locale['WLS_0206'] = "Select All";
=> infusions\weblinks\locale\English\weblinks_admin.php

your path infusions\weblinks\locale\  ???Russian???  \weblinks_admin.php

**Comment by dtechniker** [comment]
ok i have a quick solution for all with the problem that a URL can not be checked with cURL.dll because the web hoster does not support this: 
=> includes\defender\validation\uri..php

ORIGINAL alt line 83 -85
        } else if (filter_var($url, FILTER_VALIDATE_URL, FILTER_FLAG_HOST_REQUIRED) === FALSE) {
            return FALSE;
        }
Qick fix at line 83 - 85
        } else if (filter_var($url, FILTER_VALIDATE_URL) {
            return $url;
        }

Im open for better ideas...

**Comment by ovasclub** [comment]
dtechniker
Thank you. There was no line in infusions\weblinks\locale\Russian
$ locale ['WLS_0206'] = "Select All";
But it did not solve my problem.
On your problem:
Had the same thing. Hosting blocked certain links. It was solved through phpMyAdmin on a hosting

**Comment by dtechniker** [comment]
Are the links stored in the same language?


Once the page language in English and try again to create 2 new links (in Eng) and then access it.

**Comment by RobiNN1** [comment]
Everything works, but if you are offline (without internet on localhost), it does not work.

**Comment by meangczac** [comment]
@dtechniker 
https://github.com/php-fusion/PHP-Fusion/blob/Andromeda-9.0.3/includes/defender/validation/uri.php#L67
add new line before Line 67;
````return TRUE;````

This will skip the true URI check we've done. I don't know what happens with your server issue. On PHP-Fusion servers, the checks do run fine.

We should  have just leave it at regex check or make a bias rule. Say if iSUPERADMIN type it, the value must be true. Any ideas?

**Comment by RobiNN1** [comment]
@FrederickChan 
Alternative to filter_var
```php
function validateURL($url) {
    if (preg_match("/\b(?:(?:https?|ftp):\/\/|www\.)[-a-z0-9+&@#\/%?=~_|!:,.;]*[-a-z0-9+&@#\/%=~_|]/i", $url)) {
        return $url;
    } else {
        return FALSE;
    }

    return FALSE;
}

$urls = [
    'google.com',
    'google.com/',
    'www.google.com',
    'www.google.com/',
    'http://google.com',
    'http://google.com/',
    'http://www.google.com',
    'http://www.google.com/',
    'https://google.com',
    'https://google.com/',
    'https://www.google.com',
    'https://www.google.com/'
];

$i = 1;
foreach ($urls as $url) {
    print_p($i.'. '.validateURL($url));
    $i++;
}
```

**Comment by dtechniker** [comment]
@FrederickChan haha
I've read a little more in my hoster purely. I have a free provider without advertising. But for certain things you have to pay and php (curl, get_headers (), fopen () and fsockopen ()) cost in the month.

I do not want to bypass the function, if the hoster (or the next one) supports cURL, it should work again. , -)

@RobiNN1 
I try the approach in the function line 83 - 85 to set. Let's see if it works.

***************************************************************
ABER erstmal danke für die hilfe und dieses super Projekt. (german)
But first thanks for the help and this great project. 
***************************************************************

**Comment by ovasclub** [comment]
On my paid hosting links are blocked
I walk through the database.

Web Link URL - Please enter a valid URL

![-2](https://user-images.githubusercontent.com/16386011/41670802-08f05896-74d7-11e8-9470-e0dbb68bab23.jpg)

**Comment by dtechniker** [comment]
I have a question: I have completed a complete German translation for this version of PHP-Fusion-Andromeda-9.0.3. Do you want to have these? If so, where to go? (zip)?

**Comment by RobiNN1** [comment]
@dtechniker here https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=38624&pid=202814#post_202814

**Comment by dtechniker** [comment]
in the normal 9.00 -9.03 the string declaration is different. I have completed the translation into German (inclusive, infusion and themes) for the current Andromeda-9.0.3.

Ps: even for the cookiebar ;-)

**Comment by meangczac** [comment]
I'll add you into core dev team so you can look into things here :)

**Comment by dtechniker** [comment]
oh, thanks, I'll behave myself too. ;)
Where should I now save the translation for the 9.03 Andromeda?

**Comment by RobiNN1** [comment]
All locales is here https://github.com/php-fusion/PHP-Fusion-9-Locale
