### ISSUE TITLE
Web links subcategories are not displayed as such

### ISSUE THREAD

**Issue by dtechniker** [PHPFusion/PHPFusion#2078]
Web links subcategories are not displayed as such, but as main categories.

![sublinkerror](https://user-images.githubusercontent.com/40355496/41769794-c2c8252a-7610-11e8-90a0-4500f51e6dd6.jpg)

**Comment by dtechniker** [comment]
Ok, I saw that this is not implemented yet. If there is interest, I have made this possible and is already running. Should I insert this into the project?

**Comment by RobiNN1** [comment]
If you fix a bug/error, you can insert it into the project immediately. But first double check if it really fixed. If is fixed, close issue.
BTW. try use GitHub Desktop https://desktop.github.com/

**Comment by dtechniker** [comment]
ok, is in. Close

**Comment by RobiNN1** [comment]
Subcategories is hidden and I cannot access to it

**Comment by dtechniker** [comment]
Hm, I create a main category in the admin panel, then I create 2 more categories and let them descend from the main category as a parent. And everything works.
![sublinkscats](https://user-images.githubusercontent.com/40355496/41808683-8ce60004-76e1-11e8-8890-d3cbe22a6ae1.jpg)
