### ISSUE TITLE
Install - .... Steps/DatabaseSetup.inc on line 23

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2079]
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /var/www/vhosts/aliencollectors.com/httpdocs/beta/includes/classes/PHPFusion/Installer/Steps/DatabaseSetup.inc on line 23

fresh download and install ... this comes when i open my page to install (fresh download from 1 hour ago)

**Comment by RobiNN1** [comment]
This is PHP 5.5 error. If is possible upgrade to newest. I recommend PHP 7
