### ISSUE TITLE
Forum for Andromeda

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2081]
I’m currently revisiting forum UI/UX on Andromeda for further improvements;

Here is what will be added:

Deleting Forum Thread First Post
—-
If we are deleting the first post, the thread will lose its meaning. Question itself will be gone with just answers remaining. 

On such event, the deletion must not wipe a sql record, but to reset all fields. Post message will be blank, and author id will be -1. (0 maybe guest for future proofing). And we will view the post by (moderator) and post message as “This message has been removed”

Checkboxes in the Reply Field will be replaced with new button checkbox. 
——-
And form_checkbox $options[‘type’] will extended by “button” on top of radio, checkbox, and toggle. (4th possible form)

Reassigning forum moderator key parts
——
The forum moderator bar has been always a bar. If we split the parts, we can mod the moderation menu, for example a panel by the right side. 

Post Replies
———
Now we have a message “xxx has replied to this message”. This will be revised to add threaded views of the post reply in smaller texts via a jquery Ajax toggle.

Post Bombing
——
On all single thread container views such as displayed on latest threads, unanswered posts, etc, moderator will have a new Bomb button to insta-nuke and wipe the entire thread. 

Report/flag thread
——
Users must be able to flag a thread for moderators notice. 

For this, we will add a column in DB_FORUM_THREADS ‘flagged’.

We will add a notice pop up for the moderators when viewing a forum with a moderation page listing all the threads that has been flag and that can be nuked with the new bomb button. 

90% if the base core codes have been done. I will add more if there are requests on UX improvement requirements. 

Please add ideas if any. Thanks.

**Comment by ovasclub** [comment]
ovas.club:
Andromeda-9.0.3
Septenary Theme
PHP:  7.2
Like the theme Arise
