### ISSUE TITLE
XSS vulnerability in search_downloads script

### ISSUE THREAD

**Issue by TimFoerster** [PHPFusion/PHPFusion#2084]
Hello,

i found a script that has xss vulnerability:
https://github.com/php-fusion/PHP-Fusion/blob/b78ac78736219b402d8be9d2187f569e79400c6b/includes/search/search_downloads_include.php#L77

Parameter `$_POST['stext']` will be not escaped nor checked.
`stext='></a><script>alert('xss')</script><a href='
will give you an infection.

Fix:
Escape `$_POST['stext']`

**Comment by meangczac** [comment]
Thank you for the important find. We will review all search modules and patch it by today.

**Comment by karrak1** [comment]
add line PHP-Fusion/includes/search/search_xxx_include.php

`$stext = stripget($_POST['stext']) ? redirect(FUSION_REQUEST) : "&amp;stext=".$_POST['stext'];`

`$item_count = "<a href='".BASEDIR."search.php?stype=downloads".$stext."&amp;".Search_Engine::get_param('composevars')."'>".$rows." ".($rows == 1 ? $locale['d401'] : $locale['d402'])." ".$locale['522']."</a><br />\n";`

if xss vulnerability then redirect
