### ISSUE TITLE
Create Forum Posts not possible - PHP-Fusion v9.0.3

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#2086]
**Describe the bug**
Hi Developers,

I have just uploaded the last Github Branch and unfortunately had to find in the forum that creating the forum topics does not work. There is no rewrite or something like that. So I press the button Send or "Create", but nothing happens and no error is displayed internally.

Can you please check this in the test environment.

Thanks in advance.

This is in the Chrome browser under Shared Hosting with PHP 7.1 and MariaDB 10.2.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by meangczac** [comment]
From what i get:
1. Your SEO is turned on.
2. You cannot post a message.

What is your forum title, thread name? (Any special characters, etc.)?

**Comment by ghost** [comment]
I tried to investigate the problem more closely and in the PHP fusion error log is the problem token.php. I can not create forums and do not use the shoutbox.

Also already several times deleted with Ccleaner Browser Cache and Cookies, unfortunately without success. Again and again token.php appears in the error logs.

Can you possibly do something with it? I downloaded the last Github Branch today and uploaded it to the server.

**Comment by RobiNN1** [comment]
In Settings>Security Settings
Change form tokens to 5
