### ISSUE TITLE
aministration from smartfon

### ISSUE THREAD

**Issue by balin50** [PHPFusion/PHPFusion#2087]
hi
can not log in to  administration from  smartphone
click on dministration and return to the homepage

version from 16.7.2018

Users can log in on different devices simultaneously
[http://www.imagehosting.cz/?v=povolenie.png]

Android 7 , Android 4

access to other menu is OK

**Comment by RobiNN1** [comment]
all is ok

**Comment by balin50** [comment]
I've updated chrome and all is OK
