### ISSUE TITLE
Smileys Shoutbox Archive is not displayed

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2088]
Andromeda-9.0.3 (ci)
Site theme: Septenary
Site Admin Theme: Venus
PHP 7.2.7
BB Codes Shoutbox Archive is not displayed

![1](https://user-images.githubusercontent.com/16386011/43012371-ec5be724-8c67-11e8-91ea-283c774ad7f1.jpg)

**Comment by RobiNN1** [comment]
it works
![screen](https://user-images.githubusercontent.com/11664877/43013339-e7c5e076-8c48-11e8-8e77-c40198e08448.png)

**Comment by ovasclub** [comment]
A new installation on Open Server

![-5](https://user-images.githubusercontent.com/16386011/43028352-4cea6fa0-8ca1-11e8-9b96-606862f8542f.jpg)
