### ISSUE TITLE
News, bbcode

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#2089]
The embedded source appears in News only if we place blank characters in brackets in the "pre" box.
Sample on the server: https://test.phpfusion.cz/news/8740/Test-psani-Novinky-a-zdrojak
![test_news_code1](https://user-images.githubusercontent.com/617755/43034073-69c3a9c8-8cd5-11e8-9ecb-11edc04aaf58.png)
![test_news_code2](https://user-images.githubusercontent.com/617755/43034077-70d064c2-8cd5-11e8-9490-25c17801ac43.png)

form_textarea.php
change to:
link 61
link68
`'bbcode'              => TRUE,
        'html'                => FALSE,
        'preview'             => FALSE,
        'path'                => IMAGES,
        'maxlength'           => '',
        'tip'                 => '',
        'ext_tip'             => '',
        'input_bbcode'        => FALSE,`

![test_news_code3](https://user-images.githubusercontent.com/617755/43034623-0a742c6c-8ce0-11e8-8649-ee795981e17f.png)

**Comment by RobiNN1** [comment]
News has only  HTML.
