### ISSUE TITLE
Doubled colours entrance in colors.php

### ISSUE THREAD

**Issue by jantom** [PHPFusion/PHPFusion#2090]
In file /locale/English/color.php there are vars with the same value - colour names. In my opinion, it's a bug - I haven't any idea, why this entrances are doubled - only one var from pairs is in use.
**Sea Green**
$locale['color_115'] = "Sea Green";  -> never used
$locale['color_146'] = "Sea Green";
**Plum**
$locale['color_107'] = "Plum"; -> never used
$locale['color_159'] = "Plum";
**Pink**
$locale['color_106'] = "Pink"; -> never used
$locale['color_153'] = "Pink";
**Pale Green**
$locale['color_100'] = "Pale Green"; -> never used
$locale['color_156'] = "Pale Green";
**Light Yellow**
$locale['color_74'] = "Light Yellow"; -> never used
$locale['color_155'] = "Light Yellow";
**Light Green**
$locale['color_67'] = "Light Green"; -> never used
$locale['color_145'] = "Light Green";
**Gold**
$locale['color_48'] = "Gold"; -> never used
$locale['color_150'] = "Gold";
**Orange**
$locale['color_96'] = "Orange"; -> never used
$locale['color_142'] = "Orange";
**Indigo**
$locale['color_56'] = "Indigo"; -> never used
$locale['color_140'] = "Indigo";
**Turquoise**
$locale['color_129'] = "Turquoise"; -> never used
$locale['color_147'] = "Turquoise";
**Sky Blue**
$locale['color_119'] = "Sky Blue"; -> never used
$locale['color_151'] = "Sky Blue";

**Comment by RobiNN1** [comment]
That's OK.
