### ISSUE TITLE
Site Sharing .. wrong image

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2092]
when i share my site over facebook i see only php fusion favicon 150x150

![grafik](https://user-images.githubusercontent.com/22166864/43978859-023d7008-9ce9-11e8-946f-4012d8505064.png)

**Comment by RobiNN1** [comment]
Generate own favicons https://realfavicongenerator.net/ and replace this icons https://github.com/php-fusion/PHP-Fusion/tree/Andromeda-9.0.3/images/favicons
