### ISSUE TITLE
contact.php - Undefined index: captcha_code

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#2093]
contact.php
/site/contact.php
Line: 35

Undefined index: captcha_code
![grafik](https://user-images.githubusercontent.com/22166864/44085499-0f76bd14-9fba-11e8-8ff9-feea08131c97.png)

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/4c898d0aa7be99d5a792be76876f92de4035ce27
