### ISSUE TITLE
incorrect display

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2094]
![capture_001](https://user-images.githubusercontent.com/16163102/44615817-8d32ec00-a843-11e8-8d0e-726d9efc98d9.jpg)

**Comment by RobiNN1** [comment]
It's OK. Check your changes.

![screen](https://user-images.githubusercontent.com/11664877/44615907-29a9be00-a845-11e8-80de-b12fce455503.png)
