### ISSUE TITLE
/themes/templates/global/profile.php::line 117 - There is an out of place bootstrap page 'container' class here.

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#2096]
**Describe the bug**
The described file has the following css classes on the user-profile containing div:

```
116            {%tab_header%}
117            <div class='container spacer-sm'>
118                <div class='clearfix p-15 p-t-0'>
```
The `container` class in bootstrap is a fixed width class that is intended for the container of the main content only. This placement in the global profile breaks Bootstrap 4 rendering when a page has a left or right sidebar present, and when there is no sidebar it breaks the flow of the profile itself.

![screenshot from 2018-09-09 15-03-34](https://user-images.githubusercontent.com/727535/45269368-d5582e00-b441-11e8-8cde-45014547db82.png)

The container class is intended for the outermost element of the main content pane only and should not be used on interior elements.

Removing the container class from this element fixes the page flow.

**To Reproduce**
1. Install PHP 9 latest release (9.02)

**Comment by RobiNN1** [comment]
It's already fixed in latest **9.0.3 - Andromeda**
