### ISSUE TITLE
Add a honeypot dynamics

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2098]
**Increment openform.**

Put up a honey pot into openform with dynamic inputname generated, and let \defender run it automatically and if bot fills it, have it halt the system.

**Comment by RobiNN1** [comment]
This empty file? https://github.com/php-fusion/PHP-Fusion/blob/9.01/includes/dynamics/includes/form_honeypot.php

**Comment by meangczac** [comment]
Yeah I think that file can be deleted. The better implementation is through openform because this way all form will by default have a honeypot. Just like token. 

But however, we can use the function $options to turn it off if needed.

**Comment by RobiNN1** [comment]
Something like this ? https://gist.github.com/andrewlimaza/958826feac907114a57462bfc8d535ff

```php
form_honeypot('user_full_name');
```
```html
<input name="user_full_name" type="text" class="hidden"/>
```
or in openform()
```php
$option = [
   'honeypot' =>  FALSE,
   'honeypot_value' => 'user_full_name'
];

if ($options['honeypot']) {
   echo '<input name="'.$options['honeypot_value'].'" type="text" class="hidden"/>';
}
```

**Comment by meangczac** [comment]
Yes, the second method.

````
$options['honeypot'] = 'user_full_name'; // hidden field name
if ($options['honeypot']) {
// now we also need to mark it as a honeypot as $_Session so defender can read it.
  \defender::add_field_session([
        'input_name' => $ioptions['honeypot'],
        'type'       => 'honeypot',
    ]);
}
````

Token was implemented in maincore.php but it bypasses when FUSION_ALLOW_REMOTE is declared.

For Honeypot, we need a new class that extends to the Defender class, so the defender Session is accessible. From there, we add a line into maincore.php to run this honeypot class to declare defender stop() . (See how Token was constructed).

**Comment by meangczac** [comment]
Please commit this to Babylon branch. We do not want to stall the release of Andromeda pending end of this year.

**Comment by JoakimFalk** [comment]
Make a randomized output , maybe even a algo..
No, make it an algo..
For example 9 inputs options, randomize them and output 3 possible ones everytime with a twist. Some are pre-checked others are not. Just store correct array and compare for post to success.
That way the bots need to guess 3 randomized check or no check every single post.. I see it virtually impossible before spam filter kick in.

**Comment by meangczac** [comment]
Yep delete it
