### ISSUE TITLE
Permalinks auto changing URL's

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#2099]
I added Facebook like button on my website. On some pages its doesn work, beacause infusion permalinks auto changing url of FB plugin. 

1. Go to https://www.tomaszowiak.net/powiat-tomaszowski
On the top-right side page you will find like button
2. Now go to eq. https://www.tomaszowiak.net/wiadomosci/24772/Debata-kandydatow-na-urzad-Burmistrza-Miasta-Tomaszow-Lubelski 
And there like button will be disabled. 

Please look on the source code. Like button in blog readmore page has modyfied some atributes 
`data-action="../../like"
`
Should be:
`data-action="like"
`

**Comment by RobiNN1** [comment]
Fast fix https://github.com/php-fusion/PHP-Fusion/commit/5be677edd9681a3be4cb906128404de9df7af9db  , Need better solution

**Comment by kosiorski-eu** [comment]
THANKS A LOT :+1:  :)
