### ISSUE TITLE
Add a On / Off toggler button for Fusion GateWay under Admin Security

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2100]
It are read in register.

https://github.com/php-fusion/PHP-Fusion/commit/e8b67caf72ab863353b33cec8479293c49fbd519

**Comment by RobiNN1** [comment]
Good work, everything in English is fine, but it does not work in another language

**Comment by JoakimFalk** [comment]
Awesome fixing, locale/english/gateway.php need to be copied to any /locale/language and translated.

**Comment by ovasclub** [comment]
Does not turn off. Only **Yes** And disappeared Fusion Gateway at registration

**Comment by RobiNN1** [comment]
@JoakimFalk  I translated it into Slovak but it does not work right. Numbers in Slovak does not work but in English yes

@ovasclub  you have not updated database   add to db setting row settings_name gateway  and value 1 or 0

**Comment by JoakimFalk** [comment]
convert to UTF-8, locale and control files, that should do the trick... might be a js output issue to tho. But double check utf 8 first

**Comment by RobiNN1** [comment]
I use only UTF-8

@ovasclub   run site.com/csrf_andromeda_patch.php

**Comment by JoakimFalk** [comment]
Try original output, 

```
	echo '<script type="text/javascript">
		document.write("<h3>'.$locale['gateway_060'].' " + decode("'.$a.'") + " '.$multiplier.' " + decode("'.$b.'") + " '.$locale['gateway_061'].' '.$reply_method.'</h3>");
	</script>';

```

**Comment by RobiNN1** [comment]
It did not work even before my changes

**Comment by ovasclub** [comment]
Does not work

**Comment by RobiNN1** [comment]
@ovasclub  reupload https://github.com/php-fusion/PHP-Fusion/blob/Andromeda-9.0.3/csrf_andromeda_patch.php and run

Or in phpMyAdmin run 
```sql
INSERT INTO `PREFIX_settings` (`settings_name`, `settings_value`) VALUES ('gateway', '1');
```

`PREFIX` replace with your db prefix

**Comment by RobiNN1** [comment]
It works, it must be grammatically correct and with diacritics.

**Comment by karrak1** [comment]
not work word.
![capture_001](https://user-images.githubusercontent.com/16163102/48618189-e620a500-e998-11e8-875b-88403daab34a.jpg)

print_p($_SESSION["antibot"]) ==  twenty  four //space twenty before and duble space twenty and four between and space four after. 
print_p($antibot) == twenty four

And It will not work in Hungarian (locale good)

**Comment by ovasclub** [comment]
It works for me if I write together **twentyfour**
