### ISSUE TITLE
The correct answers are not correct in Words (Fusion GateWay)

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2102]
Two words like **twenty one** are not correct. The correct answers are **twentyone**.
That is how it should be?

**Comment by JoakimFalk** [comment]
ohh wait
it removes all spaces, correct answer should not be posted and saved as 1 word..

small or large numbers, none should matter. It separates on my tests.
![image](https://user-images.githubusercontent.com/4210004/47256500-ce313080-d481-11e8-88c5-4e384dd54553.png)

**Comment by ovasclub** [comment]
Is the correct answer just the answer in numbers?

**Comment by karrak1** [comment]
gateway.php line 49., 50

if $a = 10 and $b = 10 
then $a - $b (10-10=0)

no such text
or
$a = rand(11, 20);

**Comment by JoakimFalk** [comment]
The correct answer are random, etiher in words or numbers. People need to think before answering. The output is random where it asks for either eight (8) or 8 (eight) etc.

This,       
`$antibot = preg_replace('/\s+/', '', $antibot); `
Strips all spaces..  please try again.
If it does not work for you, under it, echo $antibot; and show your output.

Yes good catch, Karrak, it must be odd number there as in b..Fixed
