### ISSUE TITLE
missing infusions on installation on localhost

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#2104]
I've installed the latest 9.0.3 on my localhost with 2 llanguages (English & Danish)

there are only 3 infusions available after installation: Login, Polls and Shoutbox

I wonder what happened to News, Articles etc...

I've defused and infused, I deleted the installation, ran it again - same result ...

btw. link to downloads ends in 404 !

![v9-infusions](https://user-images.githubusercontent.com/9512774/47712595-6e344a00-dc38-11e8-82f0-b5a1eedce74e.png)

**Comment by RobiNN1** [comment]
You must install Git https://git-scm.com/downloads
after installation open cmd/terminal  and run this command

`git clone --recursive https://github.com/php-fusion/PHP-Fusion.git php-fusion`

Please read README https://github.com/php-fusion/PHP-Fusion#new-changes-about-submodules-and-git-management-of-core-infusions-ci

**Comment by meangczac** [comment]
For manual downloads in GitHub, The infusions need to be downloaded separately from its own repository.

If you have access to SSH, With git command line, you can use the guide given by Robin. That command will compile all repositories into a single package.
