### ISSUE TITLE
Extra field in registration errors

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2109]
Extra field in registration errors

<img width="353" alt="-2" src="https://user-images.githubusercontent.com/16386011/47806865-e435cf80-dd64-11e8-9245-9ca3165ba55a.png">

**Comment by RobiNN1** [comment]
I do not have it. Any error in Error log?

**Comment by ovasclub** [comment]
In themes Bootstrap, Septenary, Magazine

**Comment by RobiNN1** [comment]
I ask for an error log, not what theme you use. On my side all is OK.

**Comment by ovasclub** [comment]
Understood, just this entry comes from the panel User Info
