### ISSUE TITLE
Problem with News / Settings

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2116]
New installation. Themes Magazine

<img width="400" alt="-3" src="https://user-images.githubusercontent.com/16386011/48015843-41aa9180-e154-11e8-91f9-de5ad0542306.png">

Themes admin Venus

<img width="400" alt="-5" src="https://user-images.githubusercontent.com/16386011/48016069-d2816d00-e154-11e8-8874-8fafe4eeb3f2.png">

Themes  Septenary

<img width="400" alt="-8" src="https://user-images.githubusercontent.com/16386011/48016442-cd70ed80-e155-11e8-83e8-989458ecaa94.png">

**Comment by RobiNN1** [comment]
Oh again? Only news?
BTW. you don't need to reinstall system after every update, just replace files.
OK I add subimt locales to submissions.php as beore, due to these issues.
