### ISSUE TITLE
It is not possible to register

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2121]
It is not possible to register
After filling in the registration field there is a return to it.
Andromeda 9.0.3

**Comment by karrak1** [comment]
the bug is a defender/token.php line 143.
the flood_interval blocks
} elseif ((TIME - $token_time) < fusion_get_settings('flood_interval') && !iADMIN) {

the register fix.......

} elseif ((TIME - $token_time) < fusion_get_settings('flood_interval') && !iADMIN && isset($_POST['register'])) {

**Comment by RobiNN1** [comment]
It works well, i have no errors

**Comment by meangczac** [comment]
I don’t think that is the best solution.

The token should have been used to check that too. 

Where is the url for the originating form?
