### ISSUE TITLE
Long loading

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2122]
Please optimize questions to database.
One database, one server, two sites: left - v7; right - v9
![ashampoo_snap_2018 11 12_22h21m55s_005_](https://user-images.githubusercontent.com/12687843/48382594-0115bf80-e6e2-11e8-8519-0ebd30fd50df.png)

**Comment by meangczac** [comment]
If you disable all panels, how fast you get?

**Comment by meangczac** [comment]
There are some fix that I've made on Babylon for the forum, it will speeds up the forum because of hierarchy queries run by the forum are very intensive on large forums.

**Comment by RobiNN1** [comment]
Maybe add option to allow loading external resources from CDN

**Comment by Inventer89** [comment]
Ok, results of tests:
- all tables: 18-19 sek.
- without news table: 3.5 sek.
- without news and photos tables: 2.9 sek.
- without news, photos and articles tables: 2.6 sek.
- without news, photos, articles and posts tables: 0.9 sek.
- without photos, articles and posts tables (but with news table): 18.5 sek.

**Comment by meangczac** [comment]
Alright, there is a few tweaks you can try.

See comments table.

![capture](https://user-images.githubusercontent.com/4078041/48527449-2d8a3100-e8c6-11e8-9032-ae1d822d1b8d.JPG)

Add Index for "EACH" of these, click add Index 4 Times.

You'll get this.

![capture2](https://user-images.githubusercontent.com/4078041/48527545-88238d00-e8c6-11e8-8b30-1c301c3ec27c.JPG)

Do the same for all possible ID columns that slows you down.
By ID Columns I mean those with ID identifiers, usually the column structure type is MEDIUMINT(11)
It will increase your database size x2, but it will speed up site x10. 
When I add these for the forum on main website, a 48.0 second site query becomes 0.1s

The SQL for doing this is:
````
ALTER TABLE ".DB_COMMENTS." ADD INDEX( `comment_item_id`);
ALTER TABLE ".DB_COMMENTS." ADD INDEX( `comment_type`);
ALTER TABLE ".DB_COMMENTS." ADD INDEX( `comment_cat`);
````

**Comment by Inventer89** [comment]
It works! Thank you!
