### ISSUE TITLE
Double menu in the admin panel

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2123]
When installing a second language, a double menu appears.
There is no forum.
Two Blogs
User fields do not switch
<img width="400" alt="-2" src="https://user-images.githubusercontent.com/16386011/48463081-f869da00-e804-11e8-9134-6b3b06feef6b.png">
<img width="400" alt="-4" src="https://user-images.githubusercontent.com/16386011/48463087-04559c00-e805-11e8-88b9-b58f3d6cfa40.png">
<img width="400" alt="-7" src="https://user-images.githubusercontent.com/16386011/48463096-0c154080-e805-11e8-893d-d3988d89e678.png">

**Comment by meangczac** [comment]
Please patch the files as per this commit?

https://github.com/php-fusion/PHP-Fusion/commit/dc7dc3894b752b425cd2b6d4e841eff40e7367b0

**Comment by ovasclub** [comment]
This is already a patch.
