### ISSUE TITLE
Names of images

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2125]
All upload images are in infusions/gallery/photos/ with original name. This isn't good idea, but I had a problem with rewiting in past. I suggeste md5 and time date in name of file and 1 category = 1 folder. Look my example https://nfszone.pl/prace-11-need-for-speed-payback.html

**Comment by meangczac** [comment]
About the names of the upload of the photos with extra file name extensions. That's fine by me.
New Image Name: **xxx_md5+timestamp.jpg** 

But 1 category 1 folder not so good. 
1. Duplicate of same image with not the same name. When you have thousands of that, it will bloat your system heavily.
2. On coding side, once you change category or move photos across, we have to move the files too, and if those files are 10mb in size, copy delete will slow down core performance, and possibly introduce bug when server is slow.

**Comment by Inventer89** [comment]
@RobiNN1 Why do you close this issue? I think xxx_md5+timestamp.jpg is a good idea.

**Comment by RobiNN1** [comment]
See Frederick's answer. But maybe make like this original_name+md5(timestamp+original_name).jpg

**Comment by Inventer89** [comment]
@RobiNN1  I'm not programmer :( I can only give you any ideas to make better CMS. My site is 10 years old and I have a few observations.
