### ISSUE TITLE
Second and third photo in one photo_id

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2128]
What do you think about add second and third place in one photo_id in photogallery? Like this: [https://nfszone.pl/photogallery.php?photo_id=2935](url)

**Comment by RobiNN1** [comment]
Image grouping? That's not bad idea.

btw. nice theme.

**Comment by Inventer89** [comment]
Thanks :) But we must change Fusion v7 to Fusion v9 in next months. Test platform: http://iworld.com.pl
