### ISSUE TITLE
New userfields API not work

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2134]
Fatal error: Class 'PHPFusion\UserFieldsQuantum' not found in C:\xampp\htdocs\fusion94\includes\classes\PHPFusion\UserFields.inc on line 32

if it is set to the above place nothing works

**Comment by meangczac** [comment]
Sorry maybe auto loader. Will check on it hold on this issue

**Comment by meangczac** [comment]
Ok should be resolved by now.
