### ISSUE TITLE
Single preview in the gallery generates errors

### ISSUE THREAD

**Issue by dtechniker** [PHPFusion/PHPFusion#2139]
If I click on a frame in an album then the error message comes. 
Testlink: [http://mefhamburg.bplaced.net/willkommen/infusions/gallery/gallery.php?album_id=1](url)

***************************** Error*********************
{%stars%} {%reviews%}
{%ratings%}
{%ratings_remove_button%}

Fatal error: Uncaught TypeError: Argument 3 passed to progress_bar() must be of the type array, boolean given, called in /users/mefhamburg/www/willkommen/includes/classes/PHPFusion/Feedback/Comments.inc on line 332 and defined in /users/mefhamburg/www/willkommen/includes/theme_functions_include.php:492 Stack trace: #0 /users/mefhamburg/www/willkommen/includes/classes/PHPFusion/Feedback/Comments.inc(332): progress_bar(0, '', false, '10px', false, true, false, true, 'm-0') #1 /users/mefhamburg/www/willkommen/includes/comments_include.php(40): PHPFusion\Feedback\Comments->showComments() #2 /users/mefhamburg/www/willkommen/infusions/gallery/gallery.php(469): showcomments('P', 'fusion93AND_pho...', 'photo_id', '1', '../../infusions...', '1') #3 /users/mefhamburg/www/willkommen/infusions/gallery/gallery.php(171): get_photo_comments(Array) #4 {main} thrown in /users/mefhamburg/www/willkommen/includes/theme_functions_include.php on line 492

**Comment by RobiNN1** [comment]
Don't download Babylon branch. It's incomplete.
