### ISSUE TITLE
 localization error

### ISSUE THREAD

**Issue by dtechniker** [PHPFusion/PHPFusion#2140]
When I install Fusion9.03 in English and then switch to another language, some entries in profile.php are not translated into the new language:

Profile
Contact Information
Miscellaneous Information
Options
Statistics
Privacy

The reason: These are not queried through the locasition, but these are fixed database entries.
user_field_cats -> field_cat_name

Localization place:
Proper PHP-Fusion-Andromeda-9.0.3\locale\English\user_fields.php
$locale['u044'] = "Contact Information";
$locale['u045'] = "Miscellaneous Information";
$locale['u046'] = "Options";
$locale['u047'] = "Statistics";
.....
Example function that does not use this:
PHP-Fusion-Andromeda-9.0.3\includes\classes\PHPFusion\UserFields.inc
on line 564 ....
if ($data['field_cat_id']) {
    $category[$data['field_parent']][$data['field_cat_id']] = self::parse_label($data['field_cat_name']);
}

ps: sorry for google translate eng.

**Comment by karrak1** [comment]
new userfields API is made, not yet localized

**Comment by meangczac** [comment]
no @karrak1 , he's referring to Andromeda still.

Yes, it's main problem is that the Category of the User Fields, not on file but on Database. That is given. When you create a Category, you don't increment on files.  So the values are not in files but on Category DB.

As such, we had another way of localizing the values of the category with a multi lang column method.
It's as such:

![capture](https://user-images.githubusercontent.com/4078041/49325527-def3bc80-f57e-11e8-9fcb-ac360ad0eca9.JPG)

That if you have 2-3 language installed, you will have to manually edit those extra fields and add it in manually to update the databse. It will spare the automatic sequence. There is nothing for coder to do, the fields are dynamic and will be of all kinds of values.

**Like news title, you cannot localize it. It's _dynamic_.**

We however, covered the values in default language. If you installed in German copy, you will have that value as German by default.
