### ISSUE TITLE
do not see any subforums

### ISSUE THREAD

**Issue by Synthese** [PHPFusion/PHPFusion#2141]
**Describe the bug**
Forum / Subforum is displayed nothing
**To Reproduce**
1. Go to 'Forum '
2. Click on 'Subforums in Head '
3. Scroll down to 'I see no Subforums'
No Errors
**Expected behavior**
Expect to see my subforums under subforums
**Screenshots**
https://drive.google.com/file/d/1F_01jLKO0usoaguYOnMLja57Fp0z0V-X/view?usp=sharing
https://drive.google.com/file/d/19wz-U-bfibn2RTSRn3cbBTw9dtvRKPs5/view?usp=sharing
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by meangczac** [comment]
Sorry for the earlier mistakes, I'm patching this as well on the new forum version.

**Comment by Synthese** [comment]
Hallo 
@Mr.Chan ich habe von @RobiNN1 die Änderungen bei mir eingebaut, danach werden die Unterforen angezeigt. Allerdings hatte ich einige andere Fehler mit der Übersetzung auf Deutsch, habe diese nun auch behoben. Die Faq und die Artikel sowie die Shoutbox machen in der Version, die unter infusions/ Ci..... sind  machen leider in der Version noch Probleme, die ich noch nicht beheben konnte. Da reichen meine PHP Kenntnisse wohl nicht aus.
Vielen Dank Das Team leistet hier tolle Arbeit.
Gruss

**Comment by Synthese** [comment]
Hello
@FrederickChan I have the changes built by @RobiNN1 with me, then the sub-forums are displayed. However, I had some other mistakes with the translation in German, have now also fixed. The Faq and the articles as well as the Shoutbox make in the version, which under infusions / Ci ..... are unfortunately in the version still problems, which I could not fix yet. Since my PHP knowledge probably not enough.
Thank you The team does a great job here.
Greeting
