### ISSUE TITLE
New Bootstrap

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2143]
Will you upgrade Bootstrap and jQuery to the newest versions?

**Comment by meangczac** [comment]
I am currently developing a framework for Boilerplates, and potential replacement for all frameworks, not just Bootstrap. https://github.com/php-fusion/PHP-Fusion/tree/Babylon-9.0.4/themes/templates/boilers

Latest relevant gits:
https://github.com/php-fusion/PHP-Fusion/commit/14244f1574e9c3f5ba2c2e093c0578cdd3256485
https://github.com/php-fusion/PHP-Fusion/commit/20422a7441526caa0a714a8287b638e8a604067a

We'll be updating our core with a lot of frameworks.

In future, please use the main official forum for development questions. It is much easier for many of us to respond there.
