### ISSUE TITLE
Wrong read and comments icons

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2147]
infusions/news/news.php has wrong read and comments icons

![clipboarder 2018 12 10-003](https://user-images.githubusercontent.com/12687843/49763782-eaa55880-fccd-11e8-8f54-7b0b274e8cfc.png)

**Comment by RobiNN1** [comment]
Where? Please, send me link.

And please next time if is issue not solved click to "Reopen issue". Thanks.

Reference: #2145

**Comment by RobiNN1** [comment]
Fixed
