### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2149]
New size of favicon for Apple devices is 180 x 180. In PHP-Fusion is 144 x 144.

**Comment by RobiNN1** [comment]
That's OK. later I update it.
If you need own favicon use this generator: https://realfavicongenerator.net/

**Comment by Inventer89** [comment]
I use it :) But I don't know where is code for favicon and I haven't bigger PHP-Fusion logo for generate new size.

**Comment by RobiNN1** [comment]
I'll update it. Later. It's not important.
