### ISSUE TITLE
User Award System / Achievements

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2150]
What do you think about User Award System / Achievements? E.g for
10/20/50/100 comments
1st/10th/20th photo uploaded
1 year/2 years/3 years on page
login per 7 days
login between 23:55 31.12.2018 and 00:05 1.01.2019
catch 10 awards

like here: https://www.dobreprogramy.pl/142197,Inventer89,Odznaki.html (sorry for non-english page) and https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=30760&rowstart=0

**Comment by RobiNN1** [comment]
If you have any request for infusions, themes.. please use Forum or our Discord. 
https://discord.gg/CGSYU8r  #infusion-requests or #themes

**Comment by Inventer89** [comment]
@RobiNN1 I haven't access to write in #infusion-requests on Discord.

**Comment by RobiNN1** [comment]
Oh sorry,  #infusions channel
