### ISSUE TITLE
Replace all db_exist() instances to poll DB_INFUSIONS and set definitions.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2158]
Lets do a simple core function that read in to INFUSIONS_DB and then sets a definition for each Core Infuison.

Example 
define('BLOG', FALSE);
if ($enabled_infusions['inf_title'] == "Blog") {
define('BLOG', TRUE);
}
Then simply replace all db_exist areas with the if defined('VALUE').
This should  lower calls to database considerably.

**Comment by meangczac** [comment]
I did.

```
    function infusion_exists($infusion_folder) {
        // get the whole thing is faster maybe
        static $infusions_installed = array();
        if (empty($infusions_installed)) {
            $result = dbquery("SELECT inf_folder FROM ".DB_INFUSIONS);
            if (dbrows($result)) {
                while ($data = dbarray($result)) {
                    $infusions_installed[$data['inf_folder']] = TRUE;
                }
            }
        }

        return (boolean)(isset($infusions_installed[$infusion_folder])) ? TRUE : FALSE;

    }
```

It's 1 query for all infusions. 

https://github.com/php-fusion/PHP-Fusion/blob/Andromeda-9.0.3/includes/infusions_include.php#L134-L158

**Comment by JoakimFalk** [comment]
The db_check infusion exist will basically get same result as db_exist if not used to set definitions that is on maincore level. 1 call per Infusion to check and return. up to 7+ queries in one area and another 7+ in next etc.. with static definitions on a small db, 1 query and all checks are done site wide.

**Comment by RobiNN1** [comment]
Put this to maincore

```php
$result = dbquery("SELECT inf_folder FROM ".DB_INFUSIONS);
if (dbrows($result)) {
    while ($data = dbarray($result)) {
        define(strtoupper($data['inf_folder']).'_EXIST', TRUE);
    }
}
```

Usage:
```php
if (defined('BLOG_EXIST')) {
// code
}
```

**Comment by JoakimFalk** [comment]
That is great to cover all indeed.

**Comment by RobiNN1** [comment]
Add it to Andromeda?

**Comment by JoakimFalk** [comment]
Yeah, I think it will reduce load some.
