### ISSUE TITLE
News / Comments

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2159]
News / Comments
If I want to change the comment as a user, then it creates a duplicate of it, that is, a new comment.

![-2](https://user-images.githubusercontent.com/16386011/50477429-889b6180-09f6-11e9-9361-aad14369c043.jpg)

**Comment by RobiNN1** [comment]
For me it's ok. Try reupload all those files https://github.com/php-fusion/PHP-Fusion/tree/Andromeda-9.0.3/includes/classes/PHPFusion/Feedback

**Comment by ovasclub** [comment]
Superadmin- OK
User- not OK

![-2](https://user-images.githubusercontent.com/16386011/50532858-f1dfb980-0b49-11e9-8a41-4a5a1bfb8e1e.jpg)
