### ISSUE TITLE
The size of avatars in profile

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2162]
The avatar in profile is code as size in px, not %.

Effect:
![clipboarder 2019 01 06-002](https://user-images.githubusercontent.com/12687843/50730864-ad5eaa00-1157-11e9-9a07-bf594394aa93.png)

**Comment by RobiNN1** [comment]
It's fully responsive, check if your image has img-responsive class

https://github.com/php-fusion/PHP-Fusion/blob/Andromeda-9.0.3/includes/theme_functions_include.php#L782
