### ISSUE TITLE
warnings & fatal error installing on localhost

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#2178]
fresh github version install on localhost:

`
Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 19

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 20

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 21

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 22

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 23

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 24

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 25

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 26

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 27

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 28

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 29

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 30

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 31

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 32

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 33

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 34

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 35

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 36

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 37

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 38

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 39

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 40

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 41

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 42

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 43

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 44

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 45

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 46

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 47

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 48

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 49

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 50

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 51

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 52

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 53

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 54

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 55

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in /Applications/MAMP/htdocs/mobilbrygv9/includes/multisite_include.php on line 56

Fatal error: Uncaught Error: Call to undefined function dbconnection() in /Applications/MAMP/htdocs/mobilbrygv9/includes/core_functions_include.php:1594 Stack trace: #0 /Applications/MAMP/htdocs/mobilbrygv9/includes/dynamics/includes/form_main.php(37): fusion_get_settings('form_tokens') #1 /Applications/MAMP/htdocs/mobilbrygv9/includes/classes/PHPFusion/Installer/Console.core.inc(48): openform('setupform', 'post', 'install.php?loc...') #2 /Applications/MAMP/htdocs/mobilbrygv9/includes/classes/PHPFusion/Installer/Install.core.inc(326): PHPFusion\Installer\Console_Core->getView('') #3 /Applications/MAMP/htdocs/mobilbrygv9/install.php(22): PHPFusion\Installer\Install_Core->install_phpfusion() #4 {main} thrown in /Applications/MAMP/htdocs/mobilbrygv9/includes/core_functions_include.php on line 1594`

**Comment by RobiNN1** [comment]
Delete config.php, clean DB and install again.

**Comment by helmuthm** [comment]
situation is this: files copied to folder; pointing web browser to folder; result: all of the above warnings and the fatal error are shown on screen

in other words: the installation does not start

**Comment by RobiNN1** [comment]
php?
apache?
mysql?

**Comment by helmuthm** [comment]
php: 7.2.10
apache: 2.2.34
mysql: 5.7.23

**Comment by RobiNN1** [comment]
<strong>Requirements for v9</strong>
<table>
            <thead><tr>
                <th>Software</th>
                <th>Version</th>
            </tr></thead>
            <tbody>
                <tr><td>PHP</td><td>5.6.39 or higher</td></tr>
                <tr><td>MySQL</td><td>5.5.3 or higher</td></tr>
                <tr><td>Apache</td><td>2.4+ or higher</td></tr>
                <tr><td>Nginx</td><td>1.8+ or higher</td></tr>
                <tr><td colspan="2">mod_rewrite or equivalent for SEO</td></tr>
            </tbody>
        </table>

https://httpd.apache.org/#apache-httpd-22-end-of-life-2018-01-01

 - Update Apache.
 - Check chmod, must be 775 or 777

**Comment by helmuthm** [comment]
I checked the Apache version from command line with this command:

httpd -v

result:
Server version: Apache/2.4.34 (Unix)
Server built:   Aug 17 2018 18:35:43

the version I mentioned (2.2.34) was located in some log file ...

So if I'm running 2.4.34 what can then be the problem?

**Comment by RobiNN1** [comment]
Check chmod, must be 775 or 777. If you will install again see if config.php is created. Problem is on your side with chmod.

**Comment by RobiNN1** [comment]
I close it, it's not a system problem.
