### ISSUE TITLE
The : is removed from https:// when trying to download from an URL

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#218]
I added https://www.php-fusion.co.uk/downloads.php?cat_id=23&file_id=264 as Download URI
When I try to download from the link added it becomes https//www.php-fusion.co.uk/downloads.php?cat_id=23&file_id=264

**Comment by JoakimFalk** [comment]
Issue remains, : is striped from the url.

**Comment by meangczac** [comment]
In the admin, my side: 

![weblink](https://cloud.githubusercontent.com/assets/4078041/9782885/2dad76ce-57d3-11e5-949b-65a3f08106df.gif)

In the front end, you actually see weblink.php?weblink_id=[weblink-id] and when click it, it redirected.

**Comment by JoakimFalk** [comment]
hehe, you are on weblinks the issue is Downloads , 
https://www.php-fusion.co.uk/downloads.php?cat_id=23&file_id=264
becomes 
http://https//www.php-fusion.co.uk/downloads.php?cat_id=23&file_id=264
Live demo :
http://next.php-fusion.co.uk/RC7/infusions/downloads/downloads.php?download_id=1

**Comment by meangczac** [comment]
hahah.. doh (palm faced)

**Comment by meangczac** [comment]
Man, many silly mistakes lately. Sorry about that.

**Comment by JoakimFalk** [comment]
No worries, it says that it needs be completed so you can take some time off :)

**Comment by JoakimFalk** [comment]
Works, Ty !
