### ISSUE TITLE
Double menu in Admin Panel

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2184]
Double menu in Admin Panel
Problem in file themes\admin_themes\Artemis\Drivers\Viewer\adminPanel.php

![-2](https://user-images.githubusercontent.com/16386011/51875100-cdb40a00-238d-11e9-8d70-96b9d75ec4f6.jpg)

**Comment by RobiNN1** [comment]
Open Developer Tools (Press F12 or Ctrl + Shift + I)  and see Console. It's javascript issue
