### ISSUE TITLE
Single preview in the gallery generates error

### ISSUE THREAD

**Issue by dtechniker** [PHPFusion/PHPFusion#2187]
When I click on an album in Gallery, a popup of the album's content opens instead of refreshing the page. Thus ends a depth play. Page in page in page ....

I use Opera, Edge and Firefox on the PC.

bsp.LINK 
http://dtech.bplaced.net/dtech/infusions/gallery/gallery.php?album_id=2#

![pic1](https://user-images.githubusercontent.com/40355496/52395351-15354700-2aae-11e9-8050-4456419f9bbb.jpg)

-> No problems on PHP-Fusion-Andromeda-9.0.3

**Comment by RobiNN1** [comment]
Here is development for Andromeda and not for older releases.
And also `No problems on PHP-Fusion-Andromeda-9.0.3`

**Comment by dtechniker** [comment]
I use the current version, because there is no more number now. The 3 months old 9.0.3 with which it runs. I have found the bad one. (jQuery v2.2.4) [Deprecation] Synchronous.... and than ..... Uncaught TypeError: $(...).select2 is not a function
    at HTMLDocument.eval (eval at globalEval (jquery.min.js:2), <anonymous>:2:219)
    at i (eval at globalEval (jquery.min.js:2), <anonymous>:2:27151)
    at Object.fireWith [as resolveWith] (eval at globalEval (jquery.min.js:2), <anonymous>:2:27914)
    at ready (eval at globalEval (jquery.min.js:2), <anonymous>:2:29707)   

PHP-Fusion-Andromeda-9.0.3 have the same probs.
