### ISSUE TITLE
Fatal Redirection

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2190]
**Describe the bug**
A fatal redirection will occur if an infusion has been deleted from the /infusions/ folder after being installed.

**To Reproduce**
1. Install an Infusion.
2. Go to it's admin page.
3. Delete the infusion.
4. Reload browser.
5. See the error.

**Expected behavior**
Gracefully fallback to the administration dashboard.

**Comment by meangczac** [comment]
I did not git because I want to double confirm behavior and fix for all scenarios, but the possible fix is:

at Line 66 of file BASEDIR.'index.php';
-------------------------------
Change :
redirect(BASEDIR.$settings['opening_page']); 
to:
redirect(FUSION_ROOT.$settings['opening_page']);

works for me.

If so, we can detect whether it is ../../ or ../ based. or if $aidlink is present and is valid, and if so, redirect to admin dashboard instead.

**Comment by meangczac** [comment]
Guys please confirm.

**Comment by JoakimFalk** [comment]
Issue will not reproduce in my laragoon, I have a graceful fallback to home. But as mentioned, more logical would be back to admin area.
Tested: Shoutbox, FaQ.

**UPDATE**
I had SEO on, so with SEO it did indeed work as intended.. With SEO Disabled I do get a 404.

**Comment by RobiNN1** [comment]
error 404
