### ISSUE TITLE
FaQ Categories really need an ordering option

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2205]
FaQ Categories really need an ordering option

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/ci-Faq/commit/a3039567e9578e74df6894247fbb762b7e31fa28

**Comment by JoakimFalk** [comment]
Ah that Git was for : https://github.com/php-fusion/PHP-Fusion/issues/2208
But did you also fix the ordering? already? O.O
