### ISSUE TITLE
Search system has issues 9.xx

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2206]
Often results expected, that I know exist are not displayed. If I do same search on 8 or 7 with same DB the results will be clear. It is esp hard to find forum posts that should exist. Also with many hits a lot disappear when you try to browse them.

**Comment by MPolleke** [comment]
On 9.03.00 this issue exists for me as well. I use this patch. Does this help you?
I don't see the problem on current git.

[038-infusion-forum-search-fix-form-value.txt](https://github.com/php-fusion/PHP-Fusion/files/3694834/038-infusion-forum-search-fix-form-value.txt)
