### ISSUE TITLE
Remove all $_POST , $_GET , $_SERVER, $_REQUEST

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2210]
https://stackoverflow.com/questions/19767894/warning-do-not-access-superglobal-post-array-directly-on-netbeans-7-4-for-ph

I think we can have filter_input to replace them all to decrease codacy issues. 

Just to make sure to avoid PHP deprecation issues in the future (who knows what happens when PHP10 is released) we should wrap this into defender class to declare a filter_input() and a non Oop function referencing to it. This way when things deprecates we can just modify the function itself without affecting all the files implementing this. 

I will prepare the master function later today. This will probably cut down hundreds of issues in the PHP Mess Detection (Codacy)

**Comment by meangczac** [comment]
Okay, the methods are in.
See https://github.com/php-fusion/PHP-Fusion/issues/2210 the methods available now.

From now on, please change statements such as these:

```if (isset($_GET['example'])) ...```
to 
```if (get('example')) ...```

```if (isset($_GET['int']) && isnum($_GET['int'])) ```
to
```if (get('int', FILTER_VALIDATE_INT))```

For more info on filter types , refer to : https://www.php.net/manual/en/filter.filters.validate.php

This will drastically increase code quality inspection.

The advantage of this is:
- Reduce typing fatigue, (at least a very needy pro for me)
- Reduce logical conditions by 2x
- The new methods returns NULL so compare the below codes. Most likely can replace empty checks when dealing with superglobals.

```
$_GET['section'] = isset($_GET['section']) ? $_GET['section'] : 'default';
switch($_GET['section') {
...
}
```
with:
```
switch( get('section')?: 'default' ) {
...
}
```
- All superglobals are effectively sanitized by PHP by default.
- Available since PHP 5.2.0, so no problem at all for everyone.

**Comment by JoakimFalk** [comment]
It may crash the whole SEO Engine, Rob mentioned something about it so look at that before doing massive changes.

**Comment by meangczac** [comment]
Yes. I agree. It's just a method to set up a standard among devs here not using having such superglobals in our code anymore. 

The $_GET, $_POST, etc is "untouched". 

Mutation is even more discouraged, but yet our SEO engine do assign. We'll leave it at that first. Not going to change SEO engine anytime yet.

Less better code:
````if (isset($_POST['post_button']) {````

Better code:
```if (post('post_button')) {```

This will increase our codacy ratings.

**Comment by meangczac** [comment]
Test Codacy Response with this change:

https://github.com/php-fusion/PHP-Fusion/commit/1b6a4a0ddbe8c0f99a283bb8ee36227466034f94

**Comment by meangczac** [comment]
![Capture](https://user-images.githubusercontent.com/4078041/56883950-c985ae80-6a9a-11e9-88ce-7a04aee3f085.JPG)

Currently as it stands, Security issues is **> 58%** of total issues found in code inspection. I hope while I'm preparing for the development of main, this issue fix can provide developers with a solution to reduce and improvise codes on the project.

The defender, test files and live example of integration (test file) has been shared through this commit, 
https://github.com/php-fusion/PHP-Fusion/commit/fc52bcc84b9b9a3edb5250321c40fcec3c4e6f38

**Comment by meangczac** [comment]
See the code change, no more isset, no more empty checks. No $_POST even.

https://github.com/php-fusion/PHP-Fusion/blob/Babylon/test/defender/sanitizer.php
````
if (post('save')) {
    $data = [
        'input_string' => sanitizer('input_string', 'No input string', 'input_string'),
        'input_name_arr' => sanitizer(['input_name_arr'], 'No input array', 'input_name_arr'),
    ];
    print_p($data);
}
echo "<div class='container'>\n";
echo "<div class='spacer-md'>\n<h3>\nTest Sanitizer\n</h3>\n";
echo openform('inputform', 'post').
    form_text('input_string', 'Enter anything', '').
    form_select('input_name_arr[]', 'Select Groups', '', [
        'options'=>fusion_get_groups(),
        'multiple' => TRUE,
        'width' => '100%',
        'inner_width' => '100%',
        ]).
    form_button('save', 'Test sanitization', 'save', ['class'=>'btn-primary']).
    closeform();
echo "</div>\n";
echo "</div>\n";
````

**Comment by RobiNN1** [comment]
After https://github.com/php-fusion/PHP-Fusion/commit/1b6a4a0ddbe8c0f99a283bb8ee36227466034f94 SEO works good in PM

**Comment by meangczac** [comment]
This issue is now closed as I've finished drafting the functions. Some of the implementations changed in defender now allows non superglobals checks
```
Before :  $_POST['key'] , After:  post('key');
Before : $_GET['key'] , After get('key');
Before: isnum($_GET['key']) , After: get('key', FILTER_VALIDATE_INT);
Before:  $_COOKIE['key'] , After cookie('key');
Before: isset($_GET['key']) , After check_get('key');
Before: $_SESSION['key'] = 'key', After session_add('key', 'key');
Before:  $_SESSION['key'], After session_get('key');
Before : unset($_SESSION['key']), After session_remove('key');
```
