### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by Inventer89** [PHPFusion/PHPFusion#2212]
**Describe the bug**
install.php (Babylon) doesn't work. It shows

`Fatal error: Uncaught Error: Class 'Defender' not found in /public_html/includes/dynamics/includes/form_select.php:341 Stack trace: #0 /public_html/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(84): form_select('localeset', '', 'English', Array) #1 /public_html/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(29): PHPFusion\Steps\InstallerIntroduction->__Index() #2 /public_html/includes/classes/PHPFusion/Installer/Install.core.inc(351): PHPFusion\Steps\InstallerIntroduction->__view() #3 /public_html/includes/classes/PHPFusion/Installer/Install.core.inc(330): PHPFusion\Installer\Install_Core->get_InstallerContent() #4 /public_html/install.php(22): PHPFusion\Installer\Install_Core->install_phpfusion() #5 {main} thrown in /public_html/includes/dynamics/includes/form_select.php on line 341`

**Comment by JoakimFalk** [comment]
Babylon is Development in Progress, it may or may not work from times to times since any given Git may be partial.
