### ISSUE TITLE
Sign in with a Temporary Code option

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2213]
iherb.com have this feature and I personally think it is great and my #1 option to login.

![image](https://user-images.githubusercontent.com/4210004/56876013-b7792100-6a44-11e9-9e15-38bd36f218cf.png)

**Comment by meangczac** [comment]
Completed. https://github.com/PHPFusion/PHPFusion/commit/168690727c0d97003f10c398a612b198aadb8839
