### ISSUE TITLE
All ID links brings you back to cat selection

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#222]
Such as TOP ( #TOP) get´s you right back to cat selection
and the hotlinks from the questions in top (faq.php#faq_2) instead if going to the FaQ it brings you back to cat select.

**Comment by meangczac** [comment]
O.M.G .. The issue isn't that only. The issue is that this doesn't makes sense.. what the heck is this ?
![screen shot 2015-09-06 at 8 49 23 am](https://cloud.githubusercontent.com/assets/4078041/9701868/5994dfaa-5474-11e5-9fbc-988a51bac33e.png)

**Comment by meangczac** [comment]
Done.

**Comment by JoakimFalk** [comment]
Makes more sense with content, Look here : https://www.php-fusion.co.uk/faq.php?cat_id=10

**Comment by JoakimFalk** [comment]
However the issue remains

**Comment by JoakimFalk** [comment]
Works, Ty !
