### ISSUE TITLE
Atom9 theme breaks sidepanels

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2221]
> Panels such as home_panel will break pages and or override the location it is placed in.
> Placing them above content will prevent side panels from displaying.
> Placing them in a side panel will cause them not to display.
> Placing them in lower panels will cause them not to display.
> Placing them in a custom page will over-ride and spawn above the page content and prevent the side panels from displaying.

https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=39662

**Comment by JoakimFalk** [comment]
Ok pls, leave feedback to user.

**Comment by RobiNN1** [comment]
Atom9 has disabled some panels and home_panel is only for home.php.
