### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by djdandi** [PHPFusion/PHPFusion#2223]
I downloaded the last version with github but I have a problem with the installation.
`Fatal error: Uncaught Error: Class 'Defender' not found in /home/brzanek/public_html/08062019/includes/dynamics/includes/form_select.php:378 Stack trace: #0 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(84): form_select('localeset', '', 'English', Array) #1 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(29): PHPFusion\Steps\InstallerIntroduction->__Index() #2 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Install.core.inc(351): PHPFusion\Steps\InstallerIntroduction->__view() #3 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Install.core.inc(330): PHPFusion\Installer\Install_Core->get_InstallerContent() #4 /home/brzanek/public_html/08062019/install.php(22): PHPFusion\Installer\Install_Core->install_phpfusion() #5 {main} thrown in /home/brzanek/public_html/08062019/includes/dynamics/includes/form_select.php on line 378 `

**Comment by djdandi** [comment]
The amendment that was introduced still did not help. Can not be installed. The message pops up immediately
`Fatal error: Uncaught Error: Class 'Defender' not found in /home/brzanek/public_html/08062019/includes/dynamics/includes/form_select.php:378 Stack trace: #0 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(84): form_select('localeset', '', 'English', Array) #1 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(29): PHPFusion\Steps\InstallerIntroduction->__Index() #2 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Install.core.inc(351): PHPFusion\Steps\InstallerIntroduction->__view() #3 /home/brzanek/public_html/08062019/includes/classes/PHPFusion/Installer/Install.core.inc(330): PHPFusion\Installer\Install_Core->get_InstallerContent() #4 /home/brzanek/public_html/08062019/install.php(22): PHPFusion\Installer\Install_Core->install_phpfusion() #5 {main} thrown in /home/brzanek/public_html/08062019/includes/dynamics/includes/form_select.php on line 378 `

**Comment by RobiNN1** [comment]
It's dev version....

Download again whole pack, it works for me.

**Comment by djdandi** [comment]
I downloaded this package https://github.com/php-fusion/PHP-Fusion Babylon

**Comment by RobiNN1** [comment]
9.10 = Babylon. Everything works.

![screen](https://user-images.githubusercontent.com/11664877/59161953-694a4980-8ae9-11e9-8af2-f975c6baee1a.png)


Use stable version....

**Comment by djdandi** [comment]
I do not understand why is there a problem with me?

**Comment by RobiNN1** [comment]
Did you download it again?

**Comment by RobiNN1** [comment]
You have not properly updated files.

**Comment by djdandi** [comment]
https://i.postimg.cc/qv2hD2Z0/tyttyty.png
I downloaded 20 minutes ago

**Comment by RobiNN1** [comment]
Try now.  https://github.com/php-fusion/PHP-Fusion/commit/0e8c8cd78c31656bfc8efddf2be766870ee15dff

**Comment by djdandi** [comment]
I downloaded and continue about the same

**Comment by meangczac** [comment]
There are lot of things that breaks in Babylon. User Admin interface crashes now since it's WIP. Template class not fully implemented, and a lot of other problems. Please don't use it yet unless you know what you're doing bro.
On Jun 10 2019, at 1:55 am, djdandi <notifications@github.com> wrote:
> I downloaded and continue about the same
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub (https://link.getmailspring.com/link/A439F276-3EBD-40FF-9D45-36EB0CF25455@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fphp-fusion%2FPHP-Fusion%2Fissues%2F2223%3Femail_source%3Dnotifications%26email_token%3DAA7DTWMI6TOPWCGURVP7MJLPZU7YPA5CNFSM4HWJFYCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXIPAWI%23issuecomment-500232281&recipient=cmVwbHkrQUE3RFRXTkZCUUhIMktNM0U2UUEyWE4zQko1SVBFVkJOSEhCV0RPQlFRQHJlcGx5LmdpdGh1Yi5jb20%3D), or mute the thread (https://link.getmailspring.com/link/A439F276-3EBD-40FF-9D45-36EB0CF25455@getmailspring.com/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA7DTWPT7V4DCXHYYZEMI23PZU7YPANCNFSM4HWJFYCA&recipient=cmVwbHkrQUE3RFRXTkZCUUhIMktNM0U2UUEyWE4zQko1SVBFVkJOSEhCV0RPQlFRQHJlcGx5LmdpdGh1Yi5jb20%3D).
>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by djdandi** [comment]
I just wanted to test it

**Comment by meangczac** [comment]
We've received 2nd report now. I'll check the underlying problem right away.

On Jun 10 2019, at 3:06 pm, djdandi <notifications@github.com> wrote:
> I just wanted to test it
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub (https://link.getmailspring.com/link/A27D08E0-B412-4EAB-B3B5-30A625F71128@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fphp-fusion%2FPHP-Fusion%2Fissues%2F2223%3Femail_source%3Dnotifications%26email_token%3DAA7DTWOE2SYPLPO5KERZFU3PZX4QBA5CNFSM4HWJFYCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXJDGGI%23issuecomment-500314905&recipient=cmVwbHkrQUE3RFRXSVZWR0VJV1VONFQ3QkdOWE4zQk0yQUJFVkJOSEhCV0RPQlFRQHJlcGx5LmdpdGh1Yi5jb20%3D), or mute the thread (https://link.getmailspring.com/link/A27D08E0-B412-4EAB-B3B5-30A625F71128@getmailspring.com/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA7DTWNP454HI46Q2LD56IDPZX4QBANCNFSM4HWJFYCA&recipient=cmVwbHkrQUE3RFRXSVZWR0VJV1VONFQ3QkdOWE4zQk0yQUJFVkJOSEhCV0RPQlFRQHJlcGx5LmdpdGh1Yi5jb20%3D).
>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by meangczac** [comment]
The issue is fixed. I couldn't replicate the problem on localhost because it's a windows machine. I saw the problem after creating a new workspace on our development server and had it fixed.

On Jun 10 2019, at 3:20 pm, Frederick Chan <meangczac.chan@gmail.com> wrote:
> We've received 2nd report now. I'll check the underlying problem right away.
>
> On Jun 10 2019, at 3:06 pm, djdandi <notifications@github.com> wrote:
> > I just wanted to test it
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub (https://link.getmailspring.com/link/44EE649A-57FE-4B32-87AF-DACBEBC236C3@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fphp-fusion%2FPHP-Fusion%2Fissues%2F2223%3Femail_source%3Dnotifications%26email_token%3DAA7DTWOE2SYPLPO5KERZFU3PZX4QBA5CNFSM4HWJFYCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXJDGGI%23issuecomment-500314905&recipient=cmVwbHkrQUE3RFRXSVZWR0VJV1VONFQ3QkdOWE4zQk0yQUJFVkJOSEhCV0RPQlFRQHJlcGx5LmdpdGh1Yi5jb20%3D), or mute the thread (https://link.getmailspring.com/link/44EE649A-57FE-4B32-87AF-DACBEBC236C3@getmailspring.com/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA7DTWNP454HI46Q2LD56IDPZX4QBANCNFSM4HWJFYCA&recipient=cmVwbHkrQUE3RFRXSVZWR0VJV1VONFQ3QkdOWE4zQk0yQUJFVkJOSEhCV0RPQlFRQHJlcGx5LmdpdGh1Yi5jb20%3D).
> >
> >
>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by JoakimFalk** [comment]
Thats a really bad fix , have all files and functions etc to correlate to real file name case sensitive. Anything else is just very bad.
