### ISSUE TITLE
Unable to make a new installation

### ISSUE THREAD

**Issue by ALTUN69** [PHPFusion/PHPFusion#2224]
Unable to make a new installation

Fatal error: Uncaught Error: Class 'Defender' not found in /home/alapelit/public_html/includes/dynamics/includes/form_select.php:378 Stack trace: #0 /home/alapelit/public_html/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(84): form_select('localeset', '', 'English', Array) #1 /home/alapelit/public_html/includes/classes/PHPFusion/Installer/Steps/Introduction.inc(29): PHPFusion\Steps\InstallerIntroduction->__Index() #2 /home/alapelit/public_html/includes/classes/PHPFusion/Installer/Install.core.inc(351): PHPFusion\Steps\InstallerIntroduction->__view() #3 /home/alapelit/public_html/includes/classes/PHPFusion/Installer/Install.core.inc(330): PHPFusion\Installer\Install_Core->get_InstallerContent() #4 /home/alapelit/public_html/install.php(22): PHPFusion\Installer\Install_Core->install_phpfusion() #5 {main} thrown in /home/alapelit/public_html/includes/dynamics/includes/form_select.php on line 378

**Comment by meangczac** [comment]
#2223

**Comment by ALTUN69** [comment]
After a long break, I have to do a new installation to translate language files. Please note that this important error must be corrected immediately.
Thanks

**Comment by meangczac** [comment]
Just a pathing issues on the spl_autoload_register function at core. It's now fixed. 

@ALTUN69 , the Babylon is very very new and is in developing mode. Please use the Andromeda version to translate. We have a translate helper here at https://translate.php-fusion.co.uk

Please use this link to be invited to the translation team: 
https://translate.php-fusion.co.uk/project/php-fusion-locales/invite
