### ISSUE TITLE
email templates are not working

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2225]
Mails are sent in plain text even when HTML is enabled and the definitions are not translated ( SENDER, RECIVER , ETC ETC..)

https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=39668

**Comment by RobiNN1** [comment]
[SENDER], [RECIVER] ... 
[SENDER] => username,  in template testing this not working

**Mails are sent in plain text even when HTML**
I know about this. It works in some e-mail clients.

**Comment by RobiNN1** [comment]
![screen](https://user-images.githubusercontent.com/11664877/59347580-54ea9480-8d15-11e9-8579-b46b81cfa0ef.jpg)
