### ISSUE TITLE
Facebook to the shared addresses adds something like fbclid

### ISSUE THREAD

**Issue by djdandi** [PHPFusion/PHPFusion#2231]
Facebook to the shared addresses adds something like fbclid + some special no. After entering this link, there is no page in php-fusion 404.
As the site excludes friendly links, everything is ok. The problem only occurs on the forum.
For example, I paste the link on facebook http://pogoda-zachodniopomorskie.pl/website-members
Now, if someone wants to enter this link from facebook, then something like this is added to the link & fbclid = nr.id and the problem arises.

**Comment by meangczac** [comment]
The original link you posted on FB is

https://www.site.com/infusions/forum/viewthread.php?thread_id=123 

OR

https://www.site.com/infusions/forum/thread-name

?
