### ISSUE TITLE
Permalink issue with forum pagination

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2240]
> I have received several reports from my users that the page navigation is not working anymore after enabling permalinks/seo engine. I confirm this bug.
> Examples:
> 
> https://xs4all.gebruikers.eu/forum/thread/view/787/FRITZ!Box-7581-problemen-row-3460 <-- goes to page 1
> Hell, every thing is going to page 1.
> 

https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=39702

**Comment by RobiNN1** [comment]
Enable 
Normalize - Toggle to strip URLs from all special characters
