### ISSUE TITLE
Error displaying the Email on the page

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2241]
Andromeda.
Error displaying the Email on the page after the update file **core_functions_include.php**

![Безымянный-3](https://user-images.githubusercontent.com/16386011/62817875-d026c600-bb5f-11e9-8533-7b43485af55e.jpg)

**Comment by RobiNN1** [comment]
which page?

BTW.  You are violating the license

1, Must be: `Powered by PHP-Fusion Copyright © 2019 PHP-Fusion Inc Released as free software without warranties under GNU Affero GPL v3.`

2, https://github.com/RobiNN1/PHP-Fusion-Themes#dont-edit-copyright  `© 2019 Created by RobiNN`

Not just    `Design by RobiNN . Copyright © 2019.  PHP-Fusion Inc`

Please keep this part and dont edit it  https://github.com/RobiNN1/PHP-Fusion-Themes/blob/master/themes/Czechia/classes/Main.inc#L306-L311

**Comment by RobiNN1** [comment]
![screen](https://user-images.githubusercontent.com/11664877/63024342-4cdeda80-bea7-11e9-8f54-4e0a43b28c53.png)

**Comment by ovasclub** [comment]
When turned on BB Codes **!autolink**

![Безымянный-2](https://user-images.githubusercontent.com/16386011/63058697-31a7b580-bf0f-11e9-859f-b0c67a5f2747.jpg)

**Comment by ovasclub** [comment]
**The error is not fixed!!!** It appears when turned on **BB Codes !autolink**

**Comment by RobiNN1** [comment]
![screen](https://user-images.githubusercontent.com/11664877/63095974-dc01f600-bf6c-11e9-9b20-d4da3f9bced5.png)

!autolink - enabled

**Comment by ovasclub** [comment]
Sorry. My error (did not see PageController.inc). Email is displayed correctly.
