### ISSUE TITLE
Social Media sharing should be local code

### ISSUE THREAD

**Issue by MPolleke** [PHPFusion/PHPFusion#2245]
The Social Media sharing in the News infusion loads JavaScript from Twitter and an iframe from Facebook. These Social Media companies do a lot of user tracking, and in my opinion are not userfriendly. We should not expose users to this tracking.
I am the tech for a privacy focused forum, and these code inclusions came somewhat as a shock to me :)

It should use local html, JavaScript and images. Using sharing urls, which are available, and local code would not lead to tracking of users in this way.
I would be happy to provide a patch for the Magazine, Atom-X and Atom-X2 themes.

I can also imagine that the admin section for News has a checkbox to enable/disable the social media sharing feature. It could have a setting_inf called 'news_social_media_share = 0/1'. I would be willing to provide a patch for that.

Also, I can imagine the social media sharing can be added to all themes that are included. I don't know if they are developed here, or pulled from someplace else. If they are developed here, I would be willing to provide a patch for that as well.

It is my first time here on this issue tracker, so if I am doing something wrong, let me know :)
Regards,
Marcel Pol

**Comment by meangczac** [comment]
Hey there, thanks for the write-in.  The social sharing links were implemented from examples we've gotten from the web, as we were just doing snippets searching on how to share content with these platforms. It would be great to have your contribution so we can learn from example. That being said, I'm glad a pro like you can guide the community.

Please clone the repository and submit a push to the repository when ready.

**Comment by MPolleke** [comment]
Hi Chan, thank you for your response. I will make a patch and submit a pull request.

By the way, I am not a pro :) Just more of a hobbyist. I would enjoy contributing. For now I am just tipping my toes, we will see where it goes from here.
