### ISSUE TITLE
Mail address field in Members do not accept some characters

### ISSUE THREAD

**Issue by Ainz** [PHPFusion/PHPFusion#2249]
When using an e-mail adress with a plus sign it is not interpreted as a valid e-mail adress.

**Comment by meangczac** [comment]
![D84F0648-B388-49EF-8D29-344B2CA28E89](https://user-images.githubusercontent.com/4078041/66408667-f06ce700-ea21-11e9-9a42-ced0efce924e.png)

Tried creating gmail account using a + sign. I don’t think it’s a valid email.  Most services don’t allow them.

**Comment by Ainz** [comment]
Actually it IS a gmail account. I realise it is not standard but there is nothing I can but report this, I even think I did the same several years ago when the same person tried to register on the same site. I have no arguments if Gmail allows for it, despite being against standards.

I found a reference: https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html

Maybe it is how he uses it that is wrong, trying to get a verification.

**Comment by Ainz** [comment]
Actually: https://en.wikipedia.org/wiki/Email_address

The local-part of the email address may use any of these ASCII characters:

- uppercase and lowercase Latin letters A to Z and a to z;
- digits 0 to 9;
- printable characters !#$%&'*+-/=?^_`{|}~;
- dot ., provided that it is not the first or last character unless quoted, and provided also that it does not appear consecutively unless quoted (e.g. John..Doe@example.com is not allowed but "John..Doe "@example.com is allowed);[8]

**Comment by meangczac** [comment]
Ok I will allow a +sign. Fix will be in later today if not tomorrow on 9.03 and 9.10

**Comment by Ainz** [comment]
That's fine I guess, but should it not be according to standards listed in Wikipedia above? (If that is correct). I am fine telling people off and have them use proper syntax, but if we sanitise away what is proper syntax...?

**Comment by meangczac** [comment]
We don’t check much on the string in the email. Just a regex to include a + that we can allow, will fix this issue.
