### ISSUE TITLE
Preview Tabs function always does not include attached images and clear the selected one

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#226]
In Blog, News the preview fucntion clears the selected image for upload.

**Comment by meangczac** [comment]
Can't preview un-uploaded photos. Can't help it, defender doesn't support auto-truncate yet. One might preview the photo as it uploaded the photo into the server, and then abandon submission, which leave the photos in the server. We need a cronjob here in 9.1 so i can upload the photo into the server whether submitted or not (if needed - depend on roadmap 9.1)
