### ISSUE TITLE
Possible issue with Downloads upgrade from 7.x / 8.x

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2274]
> The upgrade deleted most of the files I had there and downloads worked in 7.02 I am restoring from backup, but when testing all I get is 404, despite the files being on the server. I checked the directory and its 777 (had to create a new one called /downloads/ since the old was either /fusion_download/ (very old) or /infusions/download/ ...

> I upped step by step via 8 and no obvious errors.  The file move/deletion thing was also an issue on another site so this is second time around. I posted about it on the forums at the time.  Many files, above GB so maybe memory ran out in the process, i don't know did not get any message about that.

**Comment by RobiNN1** [comment]
Upgrade from v7 to v8 will not affect any downloads files or images
