### ISSUE TITLE
install. Andromeda

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2286]
When installing or changing the file /includes/defender.inc

Warning: require_once(C:\OSPanel\domains\ovas0401a\includes/defender/csrftoken.php): failed to open stream: No such file or directory in C:\OSPanel\domains\ovas0401a\includes\defender.inc on line 1018

Fatal error: require_once(): Failed opening required 'C:\OSPanel\domains\ovas0401a\includes/defender/csrftoken.php' (include_path='.') in C:\OSPanel\domains\ovas0401a\includes\defender.inc on line 1018

**Comment by RobiNN1** [comment]
don't use version from Github
