### ISSUE TITLE
Lowering lines in Settings Main /Site description

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2287]
When do I put <.br./>, the site displays "**<.br./>**"and in phpMyAdmin  "**&lt;.br./&g.t;**" 
you need to correct phpMyAdmin so that the lowering of lines is displayed correctly
![1](https://user-images.githubusercontent.com/16386011/73471259-44298480-43b3-11ea-9e94-a70b51b90469.jpg)
![Безымянный-2](https://user-images.githubusercontent.com/16386011/73470942-dbdaa300-43b2-11ea-8665-3158d33e6c51.jpg)
![Безымянный-4](https://user-images.githubusercontent.com/16386011/73471551-be5a0900-43b3-11ea-80e8-4f80f2d69d6e.jpg)
![2](https://user-images.githubusercontent.com/16386011/73472312-0a597d80-43b5-11ea-89b0-66f28281f772.jpg)

**Comment by RobiNN1** [comment]
Page description cannot contain HTML. It's for SEO.
