### ISSUE TITLE
File system error

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2291]
Fatal error: Uncaught Error: Class 'Twig\Cache\FilesystemCache' not found in C:\xampp\htdocs\babilon\vendor\twig\twig\src\Environment.php:267 Stack trace: #0 C:\xampp\htdocs\babilon\vendor\twig\twig\src\Environment.php(125): Twig\Environment->setCache('cache/twig') #1 C:\xampp\htdocs\babilon\themes\templates\render_functions.php(155): Twig\Environment->__construct(Object(Twig\Loader\FilesystemLoader), Array) #2 C:\xampp\htdocs\babilon\themes\Magazine\classes\Templates\Home.inc(24): twig_init('themes/Magazine...') #3 C:\xampp\htdocs\babilon\themes\Magazine\theme.php(64): Magazine\Templates\Home::display_home(Array) #4 C:\xampp\htdocs\babilon\home.php(250): display_home(Array) #5 {main} thrown in C:\xampp\htdocs\babilon\vendor\twig\twig\src\Environment.php on line 267

**Comment by RobiNN1** [comment]
fixed
