### ISSUE TITLE
I want us to bring back old and perhaps some new CSS definitions to all sections of PHPFusion theming.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2292]
.forum-caption 
.forum-index-table 
etc anywhere it applies, we name em and apply default / optional styles.

Also bring back the tablebreak(); function.

It is very helpful to have definitions to all sections and it makes both smaller and larger modifications of existing themes a lot easier for the community.

**Comment by JoakimFalk** [comment]
Awesome speed on that one Rob :) 
But closed a tad early, we should have it everywhere. DLs, Links, FaQs etc etc :)

**Comment by RobiNN1** [comment]
Ah OK :D
