### ISSUE TITLE
No search text box shows up

### ISSUE THREAD

**Issue by jonathanwichter** [PHPFusion/PHPFusion#2302]
When trying to make a member an administrator there is no search text box to type the user name. Give me a heads up when this has been fixed. Buhl Model Train Society on Discord.
Thanks again,
Jonathan
 
<img width="2559" alt="Screen Shot 2020-03-30 at 7 19 32 AM" src="https://user-images.githubusercontent.com/35083828/77906979-de446680-7256-11ea-9dd1-18e91af92bc1.png">

**Comment by RobiNN1** [comment]
Reupload all files and use latest stable 9.03.50.

![screen](https://user-images.githubusercontent.com/11664877/77907681-4f514180-728a-11ea-8c02-c583ddb70dde.png)
