### ISSUE TITLE
iframe not showing in news

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2311]
Version: 9.03.60, PHP version: 7.3.6

iframe not showing in news.
Everything is displayed fine on the pages, but not on the news
Example
<iframe width="560" height="315" src="https://www.youtube.com/embed/********"></iframe>
<iframe width="630" height="900" frameborder="0" scrolling="no" src="https://onedrive.live.com/embed?*******"></iframe>

**Comment by RobiNN1** [comment]
Add `define('ENABLE_IFRAME', 1);` into your theme.php
Make sure you have latest 9.03.60 version from Github.
