### ISSUE TITLE
Cross Site Scripting Vulnerability on "Web links" feature in PHP-Fusion 9.03.50

### ISSUE THREAD

**Issue by thiennv-2147** [PHPFusion/PHPFusion#2313]
**Describe the bug**
An authenticated malicious user can take advantage of a stored XSS vulnerability in the "banner" feature

**To Reproduce**
To Reproduce

1. Login as member
2. Go to 'Web Links'
3. Submit malicious content
4. Login as admin and view Weblink
5. XSS trigger

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page.

**Screenshots**
![xss_weblinks](https://user-images.githubusercontent.com/60764841/80944341-87145180-8e13-11ea-8ef4-1e60ef8887c9.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser: Firefox or Chrome
Version:

**Comment by thiennv-2147** [comment]
@FrederickChan another XSS endpoint, please review to fix it! Thanks

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/c09939d5d15692ca84a68ce8fcf077418ea9bec6
