### ISSUE TITLE
Cross Site Script Vulnerability on "Blog" in PHP-Fusion feature 9.03.60

### ISSUE THREAD

**Issue by r0ck3t1973** [PHPFusion/PHPFusion#2317]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Blog" feature.

**To Reproduce**
1. Login into the panel
2. Go to 'infusions/blog/blog_admin.php'
3. Click Add Blog
4. Insert Payload:
    <svg<script> onmou<script>seover</script>="alert(document.domain)">hii</svg</script>>
5. Save Blog
6. Login as member
7. Go to 'Blog'
8. XSS Alert Message

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page

**Screenshots**
1. Info PHP Fusion:
![Info_PHP_Fusion](https://user-images.githubusercontent.com/62001260/81847841-6029ee00-957e-11ea-9e3a-1d42be5ca1a9.PNG)
2. Add Blog and bypass insert Payload XSS:
![bypass_payload](https://user-images.githubusercontent.com/62001260/81847886-746deb00-957e-11ea-8996-951e462b2acd.PNG)

![Add_Blog](https://user-images.githubusercontent.com/62001260/81847898-79cb3580-957e-11ea-941c-397938d096a0.PNG)
3. Login as member -> Go to 'Blog' -> xss alert message:
![Alert_xss_message](https://user-images.githubusercontent.com/62001260/81847950-8ea7c900-957e-11ea-8d71-2e58370efa20.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: All
 - Version

I Hope you fix it ASAP

**Comment by RobiNN1** [comment]
This is already fixed in 9.03.60...  Use DEV version from Github `git clone --recursive --branch Andromeda https://github.com/php-fusion/PHP-Fusion.git php-fusion`

**Comment by r0ck3t1973** [comment]
Hi @RobiNN1 

I have updated your latest version according to the updated pull files github. Your fillter is currently not enough, so I have been bypassed

**Comment by RobiNN1** [comment]
You may not have an updated infusions. I tried the same code and nothing happened.


But OK, I will add another check to the output

**Comment by th3lawbreaker** [comment]
Hi @RobiNN1,
I clone repo Andromeda and diff source code in blog folder. Source code in the Andromeda repo and on my current server is the same.

**Comment by RobiNN1** [comment]
It's the same as  https://github.com/php-fusion/PHP-Fusion/issues/2318
