### ISSUE TITLE
Bypass Cross Site Scripting Vulnerability on "banner" feature in PHP-Fusion 9.03.60

### ISSUE THREAD

**Issue by r0ck3t1973** [PHPFusion/PHPFusion#2318]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Banner" feature.

**To Reproduce**
1. Login into the Panel
1. Go to '/administration/banners.php'
2. Click edit on banner one, or add a new banner.
3. Insert payload: bypass fun filter:
   <svg<script> onmou<script>seover</script>="alert(1337)">hii</svg</script>>
4. xss alert message.

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page.

**Screenshots**
1. Test payload update fix:
![test](https://user-images.githubusercontent.com/62001260/81853375-88b5e600-9586-11ea-9307-575c1a0927a5.PNG)

![result](https://user-images.githubusercontent.com/62001260/81853395-8ce20380-9586-11ea-817c-c2ffe9402e48.PNG)

2. Insert payload xss:
![check](https://user-images.githubusercontent.com/62001260/81853629-dfbbbb00-9586-11ea-89f7-d642dacdaf40.PNG)

![result1](https://user-images.githubusercontent.com/62001260/81853642-e34f4200-9586-11ea-8d9f-1d7d30bd3ac3.PNG)

Bypass xss: 
![result2](https://user-images.githubusercontent.com/62001260/81853650-e64a3280-9586-11ea-80b2-7920e90516a1.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: All
 - Version 

I Hope you fix it ASAP

**Comment by r0ck3t1973** [comment]
I have check update fix banner:
function parse_textarea($text, $smileys = TRUE, $bbcode = TRUE, $decode = TRUE, $default_image_folder = IMAGES, $add_line_breaks = FALSE, $descript = TRUE) {
    return (string)parse_text($text, $smileys, $bbcode, $decode, $default_image_folder, $add_line_breaks, $descript);
}

->>> 
I have successfully bypassed

**Comment by RobiNN1** [comment]
OK this will probably in all parts. No need to create issue for every part. 

Thank you for report.

**Comment by r0ck3t1973** [comment]
Tks @RobiNN1

**Comment by r0ck3t1973** [comment]
Hi @RobiNN1 , file fix? ex: abde2342

**Comment by r0ck3t1973** [comment]
Hi @RobiNN1

Please note that all requests within a single browser session will share a single reference number and will only receive a confirmation email for the first request. If you refresh your browser or close and reopen your browser between each request, you will receive a new confirmation email and reservation number for each request.
