### ISSUE TITLE
PHPFusion 2FA.

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2319]
Monitor browsers for login and ask for verification code if it is different.

**Column to enter:**
$settings["2fa_enabled"] = 1/0

**Description**
When user login, we will store the last browser information used. 
If the browser is different than the previous one: 
We will send email to the user with a 6 digit verification code. 

The email default templates could be simple as such:

``Hi USER_NAME,
We have noticed an unusual login attempt with your account. If the login is done by you, we will need to ask you to enter the following verification code at the login screen.
VERIFICATION_CODE
For your account security, please do not share this information with anyone else. Thank you.
SITE_NAME
``

**Comment by nullatonce** [comment]
I can see the value in having this feature as a global thing, tho maybe letting site's user to decide if he needs to enable 2FA on his account would be better UX?

**Comment by MathiasHun** [comment]
> I can see the value in having this feature as a global thing, tho maybe letting site's user to decide if he needs to enable 2FA on his account would be better UX?

Did you think of this?

https://i.postimg.cc/5ywXmjmj/2fa-sample.png

There will be a test version soon.

**Comment by MathiasHun** [comment]
> I can see the value in having this feature as a global thing, tho maybe letting site's user to decide if he needs to enable 2FA on his account would be better UX?

Did you think of this?

https://i.postimg.cc/c4nmVcF8/2fa-sample.png

There will be a test version soon.

**Comment by meangczac** [comment]
I'm coming up with a new one embedded with UF and Auth class on the next major version upgrade. 
https://github.com/PHPFusion/PHPFusion/issues/2397

**Comment by MathiasHun** [comment]
This is good news. 

This won't be necessary then, I don't have much time

[https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=40883&pid=211383#post_211399](url)

**Comment by meangczac** [comment]
The one I make is 6 digit code, which system generate randomly and send it
to the user email everytime you try to login.

Albeit it's a One Time Password system which doesn't require user to have
any mobile phone or hard token devices.

So there would be no need to keep updating it when we roll it out. It's
MVCT and thus theme can customize the outlook of the OTP page as well. I
also made email templates to work with it. In fact I added 6 to 8 new email
templates which the system was sending through locale files. Lots of
adjustments actually. So I dare not commit until I'm done with all my work.

I'll need more time than I initially thought.
