### ISSUE TITLE
Cross Site Script Vulnerability on "Gallery"

### ISSUE THREAD

**Issue by Songohan22** [PHPFusion/PHPFusion#2321]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Gallery" feature

**To Reproduce**
1. Log into the panel. 
2. Go to "/infusions/gallery/gallery_admin.php"
3. Click on "Add Photo"
4. Insert payload:
! [ ] (https://github.com/Songohan22/PHP_Furion/blob/master/4.PNG)
<img src=xx onmouseover=alert('xss')>
5. Click: "Save Photo"
6. Login as member
7. Go to "Gallery "
8. Click picture upload.
9. XSS Alert Message

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page.

**Screenshots**
1. Insert payload: <img src=xx onmouseover=alert('xss')> on "Gallery"
! [ ] (https://github.com/Songohan22/PHP_Furion/blob/master/5.PNG)
2. XSS Alert Message
! [ ] (https://github.com/Songohan22/PHP_Furion/blob/master/8.PNG)
! [ ] (https://github.com/Songohan22/PHP_Furion/blob/master/7.PNG)

**Desktop (please complete the following information):**
- OS: Kali
- Browser: Firefox
- Version of Browser: 68.6

**Comment by RobiNN1** [comment]
I checked all infusions and this is already fixed in 9.03.60

Use this command to download all `git clone --recursive --branch Andromeda https://github.com/php-fusion/PHP-Fusion.git php-fusion`

**Comment by Songohan22** [comment]
@RobiNN1 
Yep...Thank you
