### ISSUE TITLE
Bug with e-mail on the page

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2322]
Version: 9.03.60
If you change the color of the e-mail 

 `<span style='color:#339966'>test@mail.com</span> `

, it is displayed on the page

ML="ma 7fh=&0/;59#'i8>1e6o:txxxxrl4";MI="H125IC46>01?JGEF7=BBD:7=B8B:7=BB;:7=BBD:7=DK:7=B8xxxx:7=xxxx3:7=B8;:7=B8@:7=KD:7=xxxxxxxx:7=BBB:7=B8xxxx:>A7=BBD:7=B8B:7=BB;:7=BBD:7=DK:7=B8xxxx:7=xxxx3:7=B8;:7=B8@:7=KD:7=xxxxxxxx:7=BBB:7=B8xxxx:H91A";ML=ML.replace(/xxxx/g, '<');MI=MI.replace(/xxxx/g, '<');OT="";for(j=0;j < MI.length;j++){OT+=ML.charAt(MI.charCodeAt(j)-48);}var e=document.getElementById('e53607368');e.innerHTML += OT;

**Comment by RobiNN1** [comment]
which page?

**Comment by ovasclub** [comment]
[https://ovas.club/pages/17/Test](url)

![Безымянный-3](https://user-images.githubusercontent.com/16386011/82007714-b9804300-968c-11ea-9abb-a07c185e89cd.jpg)
