### ISSUE TITLE
Cross Site Script Vulnerability on "Registration Settings"

### ISSUE THREAD

**Issue by Songohan22** [PHPFusion/PHPFusion#2323]
**Describe the bug**
An authent.icated malicious user can take advantage of a Stored XSS vulnerability in the "Registration Settings"  feature.

**To Reproduce**
1. Log into the panel.
2. Go to "/administration/settings_registration.php"
3. Click on Registration.
4. Insert payload:
![4](https://user-images.githubusercontent.com/29293812/82032590-a63d9980-96c5-11ea-95c9-9d84e25ace21.PNG)
5. Click "Save Setting"
6. Go to "/home.php", click Register
![9](https://user-images.githubusercontent.com/29293812/82032902-22d07800-96c6-11ea-902d-7b5ba11b0c52.PNG)
7. Click " Terms of Agreement"
![10](https://user-images.githubusercontent.com/29293812/82033357-d0438b80-96c6-11ea-944f-9dd24d5c7dc9.PNG)
8. XSS Alert Message

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page.

**Screenshots**
XSS Alert Message:
![11](https://user-images.githubusercontent.com/29293812/82033528-0bde5580-96c7-11ea-9aba-80d76c69c940.PNG)

**Desktop (please complete the following information):**
- OS: Kali
- Browser: Firefox
- Version of Browser: 68.6

**Comment by RobiNN1** [comment]
did you really download the latest version?
