### ISSUE TITLE
Bypass Cross Site Scripting Vulnerability on "Banner" feature in PHP-Fusion 9.03.60 (New Version))

### ISSUE THREAD

**Issue by Songohan22** [PHPFusion/PHPFusion#2324]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Banner" feature.

**To Reproduce**
1. Login into the Panel
2. Go to '/administration/banners.php'
3. Click edit on banner one, or add a new banner.
4. Insert payload: bypass fun filter:
![ba5](https://user-images.githubusercontent.com/29293812/82078453-541f6700-970b-11ea-966f-a05e661be577.PNG)
![ba6](https://user-images.githubusercontent.com/29293812/82078879-1838d180-970c-11ea-9000-c67cd3d035e8.PNG)

5. XSS alert message

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page.

**Screenshots**If applicable, add screenshots to help explain your problem.
1. Test payload update fix:
![ba1](https://user-images.githubusercontent.com/29293812/82077967-85e3fe00-970a-11ea-93e8-6cc9b1b177f1.PNG)
![ba2](https://user-images.githubusercontent.com/29293812/82077983-8b414880-970a-11ea-96dc-134680c176fe.PNG)
2. Insert payload bypass XSS Banner:
![ba3](https://user-images.githubusercontent.com/29293812/82078155-e115f080-970a-11ea-8ee5-43419ffca510.PNG)
![ba4](https://user-images.githubusercontent.com/29293812/82078168-e5daa480-970a-11ea-832a-c777c186b1e5.PNG)
![ba7](https://user-images.githubusercontent.com/29293812/82078899-1ff87600-970c-11ea-9acc-a7c387a6d98f.PNG)

**Desktop (please complete the following information):**
 - OS: Kali
 - Browser: Firefox
 - Version of Browser: 68.6

**Comment by r0ck3t1973** [comment]
Happy 👯‍♂️

**Comment by Songohan22** [comment]
@RobiNN1  Did you get the information?

**Comment by RobiNN1** [comment]
yes
