### ISSUE TITLE
XSS Bypass Cross Site Scripting Vulnerability in PHP-Fusion 9.03.60

### ISSUE THREAD

**Issue by r0ck3t1973** [PHPFusion/PHPFusion#2325]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability:
1. In Content Admin: Poll, Blog,
2. In System Admin: Banner
3. In Setting: Main

**To Reproduce**
1. Login into the Panel
2. Insert Payload Example 1: 
a. Go to ''infusions/member_poll_panel/poll_admin.php''
b. Click add Poll
c. Insert Payload:
![payload](https://user-images.githubusercontent.com/62001260/82082902-060e6180-9713-11ea-801c-6fa0cc5846aa.PNG)
d. Save Poll: XSS alert Message!

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**Screenshots**
Info PHP Fusion in Update:
![info_php_fusion_update](https://user-images.githubusercontent.com/62001260/82081466-913a2800-9710-11ea-98fc-e69d55b22f6d.PNG)

Ex1: Pools
![insert_payload](https://user-images.githubusercontent.com/62001260/82081652-e4ac7600-9710-11ea-9f1f-23eefee035dc.PNG)

![pools_alert_message](https://user-images.githubusercontent.com/62001260/82081656-e8d89380-9710-11ea-897a-a42607abaed9.PNG)

Ex2: Blogs
![insert_payload_blogs](https://user-images.githubusercontent.com/62001260/82081865-3bb24b00-9711-11ea-8699-ece262f186ff.PNG)

![blogs_alert_mess](https://user-images.githubusercontent.com/62001260/82081878-3fde6880-9711-11ea-8ce4-f7f2502d6ebc.PNG)

Ex3: Banner
![insert_payload_banner](https://user-images.githubusercontent.com/62001260/82082023-7c11c900-9711-11ea-9bbc-fd98c1745322.PNG)

![banner_alert_mess](https://user-images.githubusercontent.com/62001260/82082036-82a04080-9711-11ea-9c2b-ec75b867c230.PNG)

Ex4: Main Settings
![insert_payload_main_setting](https://user-images.githubusercontent.com/62001260/82082688-a617bb00-9712-11ea-880e-2686723beaa6.png)

![main_alert_mess](https://user-images.githubusercontent.com/62001260/82082707-b2037d00-9712-11ea-85bd-8a39467ba7b8.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser All
 - Version

**Comment by RobiNN1** [comment]
Man...  Paste it as text
https://user-images.githubusercontent.com/62001260/82082902-060e6180-9713-11ea-801c-6fa0cc5846aa.PNG

**Comment by r0ck3t1973** [comment]
Hi, @RobiNN1 
Payload insert: 
<a href="j&Tab;a&Tab;v&Tab;asc&NewLine;ri&Tab;pt&colon;&lpar;a&Tab;l&Tab;e&Tab;r&Tab;t&Tab;(1337)&rpar;">X</a>
I took a payload for you to see clearly

**Comment by RobiNN1** [comment]
This text 
![82082902-060e6180-9713-11ea-801c-6fa0cc5846aa](https://user-images.githubusercontent.com/11664877/82083416-fd556580-96e9-11ea-8ebb-d8a40cd9c0f6.png)

paste as text

**Comment by r0ck3t1973** [comment]
`<a href="j&Tab;a&Tab;v&Tab;asc&NewLine;ri&Tab;pt&colon;&lpar;a&Tab;l&Tab;e&Tab;r&Tab;t&Tab;(1337)&rpar;">X</a>`

**Comment by RobiNN1** [comment]
thanks, btw you can paste it directly here

**Comment by r0ck3t1973** [comment]
Hi @RobiNN1,
I Hope you fix it ASAP!
tks

**Comment by r0ck3t1973** [comment]
Hi @RobiNN1

Please note that all requests within a single browser session will share a single reference number and will only receive a confirmation email for the first request. If you refresh your browser or close and reopen your browser between each request, you will receive a new confirmation email and reservation number for each request.
