### ISSUE TITLE
After shoutbox Infuse a few error come in the Administration and it is not infusable again

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#233]
administration/infusions.php Undefined index: page Line: 144
administration/infusions.php Undefined index: page Line: 146
administration/navigation.php Undefined index: 0 Line: 30

The strange part here is, I defused to verify errors after infsue. Now when I tried to infuse it, the box refuse.

**Comment by JoakimFalk** [comment]
I can still not infuse the shoutbox ( could be remains in db that bug I guess, someone try a infuse and come back )

**Comment by meangczac** [comment]
bro, run this. Something is stuck inside the Admin table, thats why infusion detected and wont let install.

dbquery("Delete from ".DB_ADMIN." where admin_rights='S'");

Then try.
