### ISSUE TITLE
The month is not correctly displayed in the date in the localization

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2332]
Andromeda  9.03.70
The month is not correctly displayed in the date in the localization
![Безымянный-3](https://user-images.githubusercontent.com/16386011/84332118-e2252b00-abad-11ea-99c0-c4096a17953a.jpg)

**Comment by RobiNN1** [comment]
Windows....   https://github.com/php-fusion/PHP-Fusion/commit/ba7a3cceb21b34a1506e9bfb32550846bf585d2d
