### ISSUE TITLE
404 for submission.php

### ISSUE THREAD

**Issue by shefben** [PHPFusion/PHPFusion#2344]
when trying to approve submisions for news or anything, a link usually takes me to administration/submissions.php
which works in both 7 and 8 versions.

in this new version it is missing.

Did it get moved to a different spot or is it integrated into something else entirely

**Comment by shefben** [comment]
I apologize,  I see it was moved into an infusion with each module seperatly.

**Comment by JoakimFalk** [comment]
It seems that you do not have a CRL, Please restore Copyrights or purchase a CRL here, https://www.php-fusion.co.uk/licensing/
