### ISSUE TITLE
Business Logic Bypass to Add Users with no email, username and password.

### ISSUE THREAD

**Issue by oosman-rak** [PHPFusion/PHPFusion#2345]
**Describe the bug**
The general requirement of the admin portal to add user with username, email and password can be bypassed. New users with blank entry can be created.

**Version**
PHP-Fusion latest version 9.03.90.

**To Reproduce**
1. Go to 'https://v9.demos.php-fusion.co.uk/home.php'
2. Login using Demo creds provided.
3. Click on 'admin panel'
4. Login using demo creds provided. 
5. Go to user admin tab and click on members tab.
6. Click on 'Add a new user tab'
7. Fill required details.
8. Turn on any interception tool like Burp.
9. Submit the new add user form and intercept the request.
10.  Send the request to repeater.
11.  Press the send button multiple times and follow the re-direction.
12. It is observed that new members with blank entries get successfully added as members in the admin panel. 

**Expected behavior**
A new user added must be validated and blank/duplicate entries should be checked and proper error should be thrown.

**Screenshots**
![php-fusion-2](https://user-images.githubusercontent.com/74533050/102780312-b2a47600-43bb-11eb-9217-67c932847cee.png)

https://user-images.githubusercontent.com/74533050/102781990-948c4500-43be-11eb-9b74-67238de13d15.mp4

**Comment by oosman-rak** [comment]
@FrederickChan @RobiNN1 any updates on this?

**Comment by meangczac** [comment]
Hi, sorry our team is fully occupied this week to coding. We will propose a fix soon and you can test again when its there. Thanks for the issue contribution.

**Comment by oosman-rak** [comment]
Hi @FrederickChan,

Thank you for the response. I understand, sure, i'll re-test the issue once the fix is implemented by your team to check if the issue is fixed.

I have also reported 2 other vulnerabilities/issues. Request you to have a look and fix those as well.

Regards,
Mohamed Oosman B S

**Comment by oosman-rak** [comment]
Hi @RobiNN1 @FrederickChan ,

Any updates on this issue?

Thanks,
Mohamed Oosman B S

**Comment by meangczac** [comment]
ok we'll look into this this weekend

**Comment by RobiNN1** [comment]
https://github.com/PHPFusion/PHPFusion/commit/4b336a5eef757a200a65a519d3d6f8a0558e858c
