### ISSUE TITLE
Live website is down + BUGS

### ISSUE THREAD

**Issue by kkMatt** [PHPFusion/PHPFusion#2348]
PHPFusion.com:
After I tried to write a post in forum now it is fully down:
"Website configurations do not exist, please check your config.php file or run install.php again."

This website (phpfusion.com) has a bug. When I edit a profile i see "1Website" (why 1?) , also if I enter https://webdnd.com it says "please enter an url". So it is a bug and does not allows to save profiles

**Comment by RobiNN1** [comment]
I know, MySQL server is probably down, but I can't do anything because I don't have access. All sites running on the server are down.

The main page will soon receive a big update, so hopefully everything will be fixed.
