### ISSUE TITLE
Directory listing

### ISSUE THREAD

**Issue by Girishtester** [PHPFusion/PHPFusion#2350]
Hi Team , 

Based on the error message we can say if that particular directory is present or not 

**Version**
PHP Fusion V 9 

**To Reproduce**
1. Access the URL https://v9.demos.php-fusion.co.uk/infusions/gallery/
2. Type any directory after /gallery/X/X ( Error is displayed )
3. Now access the directory which is present - https://v9.demos.php-fusion.co.uk/infusions/gallery/admin/
4. Observe that there is no error message
5. So its confirmed that the directory is present 

**Expected behavior**
Generic error message has be displayed even if the directory is present or not 

**Screenshots**
![image](https://user-images.githubusercontent.com/29278280/104207705-67c7cc80-5456-11eb-9c76-37924153cf59.png)

**Comment by RobiNN1** [comment]
if the page does not exist, server displays a 404 error, nothing unusual

**Comment by JoakimFalk** [comment]
Please run your tests on localhost.

**Comment by Girishtester** [comment]
Hi @RobiNN1 ,
There is two screen shots 
1. When accessed https://v9.demos.php-fusion.co.uk/infusions/gallery/admin/   Empty page is displayed 
2. When accessed https://v9.demos.php-fusion.co.uk/infusions/gallery/test/       Error message is displayed 
3. So as per the error message **admin page** is present and **test page** is not present 

Hi @JoakimFalk 
Further tests will be performed on local host , however I ensure that there is no automation involved in my testing activity !
