### ISSUE TITLE
File upload 

### ISSUE THREAD

**Issue by Girishtester** [PHPFusion/PHPFusion#2354]
**Malicious File upload **

Able to upload other extension file rather than image file

**Version**

PHPFusion version:

**To Reproduce**

1. Go to 'https://s2.demo.opensourcecms.com/phpfusion/administration/photoalbums.php?aid=fda6864b2f098674&status=su&rowstart=0'
2. Click on 'image upload icon '
3. upload pdf or any other extension file 
4. observe that any other file can be uploaded 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/29278280/107126851-513b5680-68d8-11eb-9445-41ba36bf0549.png)

**Additional context**

Usually if the image file need to uploaded , thn there has to be proper file upload check need to be done.

**Comment by RobiNN1** [comment]
This looks like unsupported v7. // Confirmed v7.02.07..
