### ISSUE TITLE
Panel not rendering PHPCode

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#2355]
If i create a new Panel and add my code

openside("Version Info");
echo "<center>";
echo "Hier läuft:<br /><strong>";
echo "PHPFusion ".$settings['version'];
echo "</strong><br /> mit <br /><strong>";
echo "PHP ".phpversion();
echo "</strong></center>";
closeside();

it does´t render it on Frontpage.
It shows the Code.

If i create a info_php_panel.php and insert the same text and use it, it works perfekt.

**Use PHPFusion 8.00.80**

**Screenshots**

![as_code](https://user-images.githubusercontent.com/164333/107145105-c8580580-693f-11eb-8138-88dd01421be2.png)
![as_panel](https://user-images.githubusercontent.com/164333/107145108-c8f09c00-693f-11eb-9ea1-bdbcb941fa44.png)

**Comment by RobiNN1** [comment]
In security settings you have to enable PHP execution.

I also don't recommend doing this .. It's such a bad idea to save PHP to a DB.

**Comment by JoakimFalk** [comment]
For Future Reference, Please use : https://www.php-fusion.co.uk/infusions/forum/index.php For support. This is Development.
