### ISSUE TITLE
Private message sent without the recipient

### ISSUE THREAD

**Issue by Girishtester** [PHPFusion/PHPFusion#2356]
**Describe the bug**

As we see in the screen shot we are able to send the message but the email id is not registered to any user

**Version**

PHPFusion version: 9

**To Reproduce**

1. Go to https://v9.demos.phpfusion.com/messages.php?msg_send=new
2. Click on new message
3. In the "recipient" enter any email id 
4. Observe that two message is displayed , *Wrong Member ID* * Message sent*

**Expected behavior**

Either of the message has to be displayed 

**Screenshots**

![image](https://user-images.githubusercontent.com/29278280/107614230-e8edcb80-6c6f-11eb-850f-d9cc003e1ca7.png)

**Comment by RobiNN1** [comment]
Of course, you got this warning because the Recipient is empty.
