### ISSUE TITLE
form select error

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2357]
Uncaught SyntaxError: Identifier 'init_value' has already been declared
if usefield This is a required field enabled and the shoutbox is installed
![capture_001_22022021_114404](https://user-images.githubusercontent.com/16163102/108697744-87e1b580-7503-11eb-830c-ae073656ba26.jpg)
if not installed shoutbox then good, or default value required field, then good..
php 7, 8 is also faulty

**Comment by RobiNN1** [comment]
I don't see any error. (I tried it it with multiple languages as well.)

Try it on clean installation or just clear cache. Maybe you have older files in cache. Also it's JS error. So which js file? You should know that we need all info.

**Comment by karrak1** [comment]
9.03.100
clean installation
the error shown in the user fields

**Comment by RobiNN1** [comment]
Open dev tools and copy error and file path
