### ISSUE TITLE
themes / theme / classes / templates / HomePage.php I recommend adding the number of article views here.

### ISSUE THREAD

**Issue by Kvido-source** [PHPFusion/PHPFusion#2359]
**Describe the bug**

**Version**

PHPFusion version:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Kvido-source** [comment]
link 47
//Kvido
 echo '<div class="small m-b-10 overflow-hide">'.$data['meta'].' Přečteno: '.$data['views'].'</div>'
//end

**Comment by RobiNN1** [comment]
https://github.com/PHPFusion/PHPFusion/blob/Andromeda/home.php#L39  `views`

**Comment by Kvido-source** [comment]
OK, thanks

**Comment by Kvido-source** [comment]
And also in downloads?

**Comment by RobiNN1** [comment]
https://github.com/PHPFusion/PHPFusion/blob/Andromeda/home.php#L128 `dl_count`

**Comment by Kvido-source** [comment]
dl.download_id as id, dl.download_title as title, dl.download_description_short as content, dl.download_count as dl_count,
Dowloads:
Added, but doesn't show impressions.

**Comment by Kvido-source** [comment]
`dl.download_id as id, dl.download_title as title, dl.download_description_short as content, dl.download_count as dl_count,`
Dowloads:
Added, but doesn't show impressions.

**Comment by Kvido-source** [comment]
//Kvido
```
echo '<div class="small m-b-10 overflow-hide">'.$data['meta'].' Přečteno: '.$data['views'].'</div>';
//end
```
This must be put in Magazine / classes / Templates / Home.php for the Magazine theme, otherwise it will not appear in news and Blog Read / View.
download.php in Templates for theme Magazine is not!
