### ISSUE TITLE
Gallery front-end titles trims a tad short of the box size.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#236]
Silly issue really, but it is true..

![short-trim](https://cloud.githubusercontent.com/assets/4210004/9698320/de30853a-53b0-11e5-82a0-4903f1f897c3.png)

**Comment by meangczac** [comment]
Ok, the lines in the git. Trim Text 18 chars. Some screen is wide, some screen is very small. People who have problem viewing indent and need 2 monitor to view it would find the text was just nice perhaps. 
Anyway, not a big issue. Done.
