### ISSUE TITLE
Correct sitelinks-list.php file name in the file content

### ISSUE THREAD

**Issue by alqutob** [PHPFusion/PHPFusion#2362]
administration/includes/sitelinks/sitelinks-list.php

The file name is not correct

Open administration/includes/sitelinks/sitelinks-list.php

+--------------------------------------------------------+
| Filename: sitelinks.php
| Author: Core Development Team (coredevs@phpfusion.com)
+--------------------------------------------------------+

Must be

+--------------------------------------------------------+
| Filename: sitelinks-list.php
| Author: Core Development Team (coredevs@phpfusion.com)
+--------------------------------------------------------+

**Comment by RobiNN1** [comment]
Nothing important.
