### ISSUE TITLE
User sees draft news and links, but the administrator does not see 

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2363]
User sees draft news and links, but the administrator does not see 
PHPFusion version9.10.00

![Безымянный-2](https://user-images.githubusercontent.com/16386011/116492188-762edc80-a8bd-11eb-92b4-f5a1e9673ba2.jpg)
![Безымянный-4](https://user-images.githubusercontent.com/16386011/116492206-7dee8100-a8bd-11eb-90e6-8537fcf5e1e4.jpg)

**Comment by RobiNN1** [comment]
I don't see any problem.

Download latest version and try again. Maybe reinstall it. 9.10 is DEV version, so anything can happen. Also, do not use it on live site.
