### ISSUE TITLE
When saving the page, a \ character is created 

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2364]
PHP version 7.1.33
OpenServer
PHPFusion version 9.10.00

If an image is added to the page, then a `\` is created in the code when saving.
`<img src=\"http://ovas0513a/images/phpfusion-icon.png\" alt=\"\" class=\"img-responsive\"/>`
![Безымянный-6](https://user-images.githubusercontent.com/16386011/118092607-22a8ac80-b3ee-11eb-8871-4ac2c8ae3b03.jpg)

**Comment by RobiNN1** [comment]
Which admin page?
