### ISSUE TITLE
Bug when displaying Email when it matches the login on the pages 

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2365]
PHP version 7.1.33
OpenServer
PHPFusion version 9.10.00

For example 
**User:**
 github
cocacola
testcom
**Email:**
test@git.hub
test@coca.cola
test@test.com

![Безымянный-2](https://user-images.githubusercontent.com/16386011/118365275-cb593680-b5bd-11eb-853e-ecade7f54372.jpg)

**Comment by RobiNN1** [comment]
Uhm... Who would create these accounts at all?
