### ISSUE TITLE
Error blog

### ISSUE THREAD

**Issue by vitext** [PHPFusion/PHPFusion#2366]
9.03.110
File: blog_submissions.php
Page: /infusions/blog/blog_admin.php?aid=9aff5f0e48798f27§ion=submissions&submit_id=9
Line: 132
Error message: unserialize(): Error at offset 6 of 1323 bytes.

Note: The error occurs when an Admin or registered member is logged on.
Thanks!

**Comment by RobiNN1** [comment]
https://www.php-fusion.co.uk/infusions/forum/viewthread.php?thread_id=40568&pid=210007#post_210007

Don't spam the same thing!

SK: 
Nespamuj všade to iste! My to vidíme, stačí raz...
