### ISSUE TITLE
Very small value for album title 

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2367]
Very small value for album title.
infusions/gallery/templates/gallery.tpl.php
`37. echo "<a class='display-block' title='".$locale['gallery_430']."' href='".$info['album_link']['link']."'>n<strong>".trim_text($info['album_link']['name'], 18)."</strong>n</a>n";`
18-The meaning is very small for the title of an album consisting of 3-4 words .
![Безымянный-3](https://user-images.githubusercontent.com/16386011/120932587-3fe44880-c718-11eb-9a23-d3b1997ddb50.jpg)

**Comment by RobiNN1** [comment]
It's just a design. You can fix this yourself in your theme.

I also plan to create a new gallery template.
