### ISSUE TITLE
Theme Material?

### ISSUE THREAD

**Issue by vitext** [PHPFusion/PHPFusion#2368]
Does the Material material still count?
Thank you

**Comment by vitext** [comment]
Greetings, thank you.

**Comment by vitext** [comment]
The Material has more components, it can't run ...?

**Comment by JoakimFalk** [comment]
Please use our forums for Themes / Addons on non devlopment version specific questions. Also before you post a question write it in your own language then translate in Google translate before publish so we can understand your issue better.

**Comment by vitext** [comment]
Yes. Thanks!

**Comment by vitext** [comment]
I suggest adding an appendix to the theme of Magazin a Material on the homepage under the title of the articles to display the number of read articles "Reads / Displayeds".

We will make the adjustment in the file:
/www/themes/Magazine/classes/Templates/Home.php:

`//echo '<div class="small m-b-10 overflow-hide">'.$data['meta'].'</div>';
                                //Kvido
                                    echo '<div class="small m-b-10 overflow-hide">'.$data['meta'].' Přečteno: '.$data['views'].'</div>';
                                    //end`

**Comment by RobiNN1** [comment]
**Use Forum for addons support.** This Github is only for development purposes.
