### ISSUE TITLE
Line break in Site description in Main Settings

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2369]
Line break in Site description in Main Settings `<br/>` in the database is displayed as `& lt; br / & gt; `And on the site it comes out as `Test2021 <br/> Test2022 <br/> Test2023 <br/>`
Should be:
Test2021
Test2022
Test2023 
![Безымянный-2](https://user-images.githubusercontent.com/16386011/122096309-3e113800-ce30-11eb-8948-958fae12a7f4.jpg)

**Comment by RobiNN1** [comment]
https://github.com/PHPFusion/PHPFusion/issues/2287#issuecomment-580358397

Page description is only for meta tags that cannot contain any html.
