### ISSUE TITLE
The show / hide password button is gone.

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2371]
Version: 9.10.00
OpenServer
PHP version 8.0.7
The show / hide password button is gone.
It disappeared everywhere during installation, when logging in, when changing the password. 
![Безымянный-2](https://user-images.githubusercontent.com/16386011/124147217-4e701680-dab0-11eb-979c-e15551c0dcf3.jpg)

**Comment by RobiNN1** [comment]
https://github.com/PHPFusion/PHPFusion/commit/861b800b45e1af93a63e6c378d3afb4e2ba5b750
