### ISSUE TITLE
Why such a mess with headings?

### ISSUE THREAD

**Issue by nullatonce** [PHPFusion/PHPFusion#2378]
As a blind person, using phpfusion the cms and the official website, throws me off.
Not only it's counter intuitive and confusing, but also not professional, also, i believe, it's a bad for seo.
Is it any reason for this?
From what i know convention is to use css to change font sizes. Thanks.

**Comment by RobiNN1** [comment]
The whole official site is bad and I can't fix this because I don't have access to it.

Only @FrederickChan  or @JoakimFalk  can fix it.

**Comment by nullatonce** [comment]
But it's in the CMS itself too.

**Comment by meangczac** [comment]
I'm sorry to hear that . May I know which part need change. if you would be patient enough to list them all here, I will be able to accommodate and fix all the listed by you.

**Comment by nullatonce** [comment]
Hi @FrederickChan  ,
The headings, especially on official page, is a subjective topic.
However here's a quick resource, that can be usefull https://www.w3.org/WAI/tutorials/page-structure/headings/
Probably, the important thing is to not skip levels, so that user know what to expect.

If I have to point something out, lets take for example:

"Find and download the best addons and themes" level2
"Latest Themes" level6
<Theme list> level 4
Expected behavior, in the  example above, would be to have level6 heading as level3.

And overall the whole front page is all over the place.
Here's a current sequance of headings in front page:
 h1->h2->h6->h4->h6->h4->h4->h6->h2->h4(multiple)->h2)
I'm not sure that i can point out everything, as mentioned before - it's subjective. Also I don't know the importance of blocks in relation to SEO.

The same patterns can be seen in the CMS itself. I had no time to look deeper into system, but, at least, it's the same in installation template.
 

OT:
While I'm here: Navigating forum threads would be more easier if it would be wrapped in headings :) :)

Thanks.

**Comment by meangczac** [comment]
Now I see the h tags is what you rely on. That is a lesson for all of us
today. I will make the headings a linear and try to avoid captioning using
h tags if not necessary from now on.

I will be amending and replace h tags whenever I come across them.

I am thankful for your notes on this. Apologies for causing such
inconvenience.
