### ISSUE TITLE
Locale bug

### ISSUE THREAD

**Issue by MathiasHun** [PHPFusion/PHPFusion#2385]
LOCALE.LOCALESET. "admin/settings.php
and the
LOCALE.LOCALESET."admin/infusions.php
I used it together and had a minor problem.

There are the same variables, so it gets confused.

Example: $locale['411']

local-bug.jpg
https://i.postimg.cc/s2VLgy5d/local-bug.jpg

local-bug-correct.jpg
https://i.postimg.cc/jjFBgmnp/local-bug-correct.jpg

**Comment by karrak1** [comment]
and even these 
db-backup.php, image_uploads.php, main.php, panels.php, serverinfo.php

**Comment by meangczac** [comment]
I'll start to look into them.
