### ISSUE TITLE
Password char

### ISSUE THREAD

**Issue by MathiasHun** [PHPFusion/PHPFusion#2388]
Password character verification is a bit incomplete or the password generator and password description contain more allowed characters.

`$locale['u147'] = "Password must be between 8 and 64 chars long.<br/>Allowed symbols are a-z, 0-9 and @!#$%&/()=-_?+*.,:;";`
There is `oO0:`

I understand the exclusion of similar characters, but then you have to take it out in the description too, because that's how it's misleading. e.g.: o, O, 0

function getNewPassword(... There is `:`

function passwordStrengthOpts(... There not is `:`

function passwordStrengthOpts(... There is `[]`

This can cause problems when typing or requesting a password.

**Comment by meangczac** [comment]
I don't quite get it. What must be removed and what must be added?
\

**Comment by MathiasHun** [comment]
e.g.

Missing here _colon_ **:**
```
function passwordStrengthOpts(...

	$pass_regex .= '(?=.*?[@!#$%&\[\]()=\-_\\\\\/?+*.,;^*])';
```


Here is it _colon_ **:**
```
function getNewPassword(...

	$chars = ["abcdefghijklmnpqrstuvwxyzABCDEFGHIJKLMNPQRSTUVWXYZ", "123456789", "@!#$%&/()=-_?+*.,:;"];
```
