### ISSUE TITLE
When clicking send private message to a user from a user profile 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#239]
The user ID is not pickedup and you go to messages front only.

**Comment by meangczac** [comment]
Oh. Link url error. K.

**Comment by JoakimFalk** [comment]
Could be that simple or a deeper issue in PM system, one thing at a time tho ;)

**Comment by meangczac** [comment]
Yes, done anyway, but I'm now handling error messages. I lodge another issue.
