### ISSUE TITLE
form_textarea went wrong

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2394]
`<b>aa</b>` saves like this instead `<b>>aa</b>>` saves like this instead

![capture_001_02082022_124718](https://user-images.githubusercontent.com/16163102/182357249-97e86613-cabb-4768-be17-bd42fc895304.jpg)

after saving

![capture_002_02082022_124741](https://user-images.githubusercontent.com/16163102/182357252-6ad46094-6425-41b1-9064-25083a6c23d6.jpg)

**Comment by karrak1** [comment]
the reason of the mistake..
Security fix Proposed fix for issues reported by @Positive Technologies

https://github.com/PHPFusion/PHPFusion/blob/fa5a5bd1ec6e35f528d0346f7d85b60256f23ded/includes/core_functions_include.php#L1144

**Comment by meangczac** [comment]
I'll look into this, on the weekend.
