### ISSUE TITLE
Login method setting makes no locale change for user info panel in the login box

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#240]
We should have it as a default display to toggle depending on this settting.
1, User name (Login ID)
2, Email (your email)
3, Both (Login ID or email)

**Comment by meangczac** [comment]
Nice catch! @rizado , can you fix this?

**Comment by meangczac** [comment]
I'll fix this now. Removing Rizado. It's his birthday today. Let him enjoy :+1:
