### ISSUE TITLE
Unable to Register to PHPFusion Forum

### ISSUE THREAD

**Issue by bronallo-bd** [PHPFusion/PHPFusion#2422]
**Describe the bug**
Any attempts to register on phpfusion.com are met with a stacktrace, regardless of browser.

**Version**
PHPFusion version: N/A

**To Reproduce**
1. Go to https://www.phpfusion.com/
2. Click on 'Sign Up'
3. Answer security question

`Fatal error: Uncaught Error: Call to undefined method PHPFusion\Users\ProfileForm::parseLabel() in /home/fusion/public_html/includes/classes/PHPFusion/Users/ProfileForm.php:459 Stack trace: #0 /home/fusion/public_html/includes/classes/PHPFusion/Users/ProfileForm.php(318): PHPFusion\Users\ProfileForm->renderTerms() #1 /home/fusion/public_html/includes/classes/PHPFusion/UserFields.php(151): PHPFusion\Users\ProfileForm->getInfo() #2 /home/fusion/public_html/register.php(108): PHPFusion\UserFields->displayProfileInput() #3 {main} thrown in /home/fusion/public_html/includes/classes/PHPFusion/Users/ProfileForm.php on line 459`

**Expected behavior**
User is able to register for PHPFusion forums

**Screenshots**
![image](https://github.com/PHPFusion/PHPFusion/assets/54151096/c0d5485c-48f5-45d5-a733-3b02fe260fc5)

**Additional context**
Attempting to register to follow up on a disclosed security issue.

**Comment by meangczac** [comment]
It's fixed.
