### ISSUE TITLE
email templates notice

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#243]
administration/email.php Undefined index: testmail Line: 68

**Comment by meangczac** [comment]
small issue. fixed

**Comment by JoakimFalk** [comment]
Hien need this reopened due to test button issues.

**Comment by meangczac** [comment]
Err.. just noticed I was referring to another issue #244  with the git.

**Comment by JoakimFalk** [comment]
Comment makes sense on Git tho, good work.

**Comment by meangczac** [comment]
Thanks. :+1:
