### ISSUE TITLE
email templates wrong language sent on test message

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#244]
I send test message for Posts, PM, Contact form and they arrive in Dannish while sent as Eng

**Comment by meangczac** [comment]
now thats multilang.

**Comment by meangczac** [comment]
In L76 of sendmail_include.php the sendmail_template() function receives $subject, $message as is.

In Email.php - the sendmail_template() function uses $locale['412'], $locale['413'] as the input. That locale, is the current Admin Locale. Your admin panel must be in Dannish when you tested.

**Comment by meangczac** [comment]
I've put a convertor in.
