### ISSUE TITLE
Notice for User fields - Module install Comment under -stats

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#245]
Driver/PDOMySQL.php
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-stat' at line 1
Line: 99

**Comment by JoakimFalk** [comment]
It seems to work tho

**Comment by meangczac** [comment]
@rimelek , another PDO or Server faulty?

**Comment by JoakimFalk** [comment]
Server seem ok, can just be some query issue as well

**Comment by meangczac** [comment]
http://stackoverflow.com/questions/4544051/sqlstate42000-syntax-error-or-access-violation-1064-you-have-an-error-in-you

**Comment by JoakimFalk** [comment]
so it could be no quote on reserved words, Maybe stats is the one.

**Comment by meangczac** [comment]
Ok, i'll check.
