### ISSUE TITLE
Sublinks does not get rendered in the top menu in any theme when only sub header option is enabled

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#251]
I added a sublink to a menu item but it is not seen any any of our current themes when enabled to only be listed in sub header once navigation panel and subheader is enabled the sublink is displayed

**Comment by meangczac** [comment]
Header menu is link position 2, query is 2 and above 2
Site navigation panel is link position 1, query is 1 or 3
Both is 3

Whats v7? Whats admin? Whats functions render sql ... 

I will check the keys accuracy later. I bet its wrong key or something. Now, lunch time first.
