### ISSUE TITLE
Weblinks not showed

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#252]
I have created a Kategorie for Weblinks.
Add a Weblink to this Kategorie.
But it is not show on Public Page.
Still sayd There is no Weblink.
Can anyone confirm it?

Greatz WuChEn

**Comment by JoakimFalk** [comment]
I just reinstalled the infusion and I can not reproduce your error. Please update your whole installation with latest Git and reinstall the Infusions you have installed, there have been some changes made to em.

**Comment by JoakimFalk** [comment]
So considering your other issue, I assume you adding Links in one Language and tried to view them in another?. If not I will re-open but closing this for now.

**Comment by Der-WU** [comment]
Sorry Domi-php. i must reopen this issue.
I Use latest git.
1. Frontpage says no kategorie defined.
2. I have created a kategorie on admin interface.
3. Frontpage showed the Kategorie with 0 Links.
4. When i klick on the Kategorie i got the frontpage with no content.
5. I Create a link on admin interface in this kategorie.
6. Frontpage showed the Kategorie with 1 Link
7. When i klick on the Kategorie i got in the Kategorie and the Message says "no links defined"

I think its a language problem, on kategorie i can set the language, on link not.

Greatz WuChEn

**Comment by JoakimFalk** [comment]
Yes, confirmed an issue now. I must have had an older working version installed.

Notices thrown , 

weblinks/weblinks.php Undefined index: links_per_page Line: 64
weblinks/weblinks.php Undefined index: links_per_page Line: 61
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2 Line: 106
weblinks/weblinks.php Undefined variable: rows Line: 64

**Comment by meangczac** [comment]
Please give it a test run again.

**Comment by JoakimFalk** [comment]
Yes works, good work!
