### ISSUE TITLE
Feature wish

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#253]
It´s not needed by me.
But if some People create a multible Language Page.
Contets created in english not showed in other languages!?
So every Content musst be created on every language!?
Is there a way an creation directly enter content for all languages?

Like Weblinke Name for English and German , Description for English and German?

Greatz WuChEn

**Comment by JoakimFalk** [comment]
If you want same content for any language you don´t need Multilingual support.
There are multiple ways to control that, Settings > Language Settings and turn of the instance for a specific module as for one example. ( The system is very flexible ).
This is not a Wishpage nor a support page please respect that and use our forums for such discussions.

**Comment by JoakimFalk** [comment]
You can read more about it here : https://www.php-fusion.co.uk/infusions/wiki/documentation.php?page=202
