### ISSUE TITLE
PM - Send to all in groups

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#254]
What happens if someone's inbox is full ? Kinda, unfair that someone did not get the message isn't it?
But should the message get thru to the rest of the people?

$locale['628'] = Unable to send the Private Message. The recipient's inbox is full.

**Comment by JoakimFalk** [comment]
Yes messages from Admin should override box limits.

**Comment by meangczac** [comment]
OK, and another current issue. When someone send mass message, how do we handle outbox? Currently the SQL table structure does not support "groups" , omit recording ok.

**Comment by meangczac** [comment]
Also please check this situation..

User 1 - Admin - PM settings = Notify via email when I recieve PM is checked.
User 2 - User - PM Settings = Notify via email when I receive PM is "UNCHECKED".

From what I read in the code now, when Admin Send PM to all, Sendmail is on Sender's settings atm. 
So if User 1 check his notify email , system sends everyone email. lol..

Is this true now? Regardless, I'll change the codes.

**Comment by meangczac** [comment]
PM codes are kind of messy atm. I'll restructure the code.

**Comment by JoakimFalk** [comment]
no,it should be so that sendmail should only send to the ones that have checked notify.

**Comment by meangczac** [comment]
yep. i think so too. I'll change the codes. Not many issues now, and I have 3 hour to spare. I can do it.

**Comment by JoakimFalk** [comment]
:)

**Comment by meangczac** [comment]
Aiyah...... 

```
    dbquery("UPDATE ".DB_MESSAGES_OPTIONS." SET
    pm_email_notify = '".(isnum($_POST['pm_email_notify']) ? $_POST['pm_email_notify'] : 0)."',
    pm_save_sent = '".(isnum($_POST['pm_save_sent']) ? $_POST['pm_save_sent'] : 0)."',
    pm_inbox = '".(isnum($_POST['pm_inbox']) ? $_POST['pm_inbox'] : 0)."',
    pm_sentbox = '".(isnum($_POST['pm_sentbox']) ? $_POST['pm_sentbox'] : 0)."',
    pm_savebox = '".(isnum($_POST['pm_savebox']) ? $_POST['pm_savebox'] : 0)."'
    WHERE user_id='0'");
```

I do $settings.
