### ISSUE TITLE
Rewriting Private Messages

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#255]
Kissing the code.

**Comment by meangczac** [comment]
System limitations.
- Typically, only Admin and SA have unlimited inbox limit..
- User always follow core defaults.
- When ADMIN or SA updates core defaults, there are no codes that updates everyone's SQL record. 50k records to loop is a pain. If my earlier code doesn't have this, I don't think v7 has it even, .. a constructor need to update immediately when the member arrive at message.php - (kickstarting updating)

**Comment by meangczac** [comment]
There is no bug whatsoever in the previous TPL design, but there is a serious task behind - upgrade where migrating data will be a pain coz it's about 3 level down in array management. I'm going to re-template. Please back up yesterday's git -- if you like the previous design. The next incoming git will change the whole new UI.

You will need - basedir/messages.php, templates/global/messages.php and it's css file.

**Comment by meangczac** [comment]
<strong>Issue A:</strong> A message_cat column is needed if we want to reference to the previous message on the reader's view rather than group by message_subject. It's faster and more efficient. 

<strong>Issue B:</strong> But, since there is an inbox limit, flawed the requirements altogether. 
That was what bugged the last PM model. I did not test with the ordinary member, but since I am coding in a SA environment. So my inbox is unlimited. However, as member, you need to keep the previous message to be able to attach the last message. It's wrong to find previous message sometimes, and sometimes not because you have deleted the message to free up inbox space. 

Roadmap 9.1: Quoted reply messages can be added, since message_message column is TEXT NOT NULL. And BBcode is supported in PM.

**Comment by meangczac** [comment]
Further optimisation : Actually, we do not need to keep DB_MESSAGE_OPTIONS - inbox, outbox, archive values, we just set as 0 so we can follow core system values.  If some members premium or some shit like that, they can increase the value to beyond 1. So if value is 0, no need to make any query.

And Mailbox settings is directly involving users, why not in $userdata? ... now, we're reading the inbox settings here and there site wide, PM, User info panel use these settings too, and if i add another footer bar to make a chat based on this, fetch data another time. How many time do we need to fetch this table if a solution is integrating PM ? >.>

**Comment by JoakimFalk** [comment]
Please note that if you have PDO enabled, you need to disable it before you can run the script.
open config.php and set pdo to 0, go back to messages and upgrade.
It has to do with this https://github.com/php-fusion/PHP-Fusion/issues/266
