### ISSUE TITLE
New profile cats navigation feels a tad confusing

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#259]
There are two new cats in there, noone are clickable.
![profilecats](https://cloud.githubusercontent.com/assets/4210004/9715646/a4f411f2-5562-11e5-9178-ba71a25cabeb.png)

**Comment by meangczac** [comment]
Can be done. Just dont show if its empty.

**Comment by JoakimFalk** [comment]
Noone of em are clickable even with content now

**Comment by JoakimFalk** [comment]
When I come to think about it I somehow remember tabs for profile cats before, it was changed?
Now we have Tabs in the Admin for the Profile cats for each new one.
