### ISSUE TITLE
Administration > Setttings > Language Settings, many locale changes have not been reflected here

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#260]
Even small changes gives me 3-4 pages with errors, please revise the locale changes and reflect them in this file.

**Comment by meangczac** [comment]
I'll do it. Lets do this in 2 step. I'll git in a fix, then I will need full error logs if any remaining.

**Comment by meangczac** [comment]
I can remove all my language and still work... then i cannot install back language.

System has tonnes to do still. I will need to redo.
