### ISSUE TITLE
Custom Panels are not rendering codes in preview

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#265]
![panel-preview-not-rendering-code](https://cloud.githubusercontent.com/assets/4210004/9730095/67df8442-5614-11e5-9457-1ffcc67982e1.jpg)

**Comment by meangczac** [comment]
Yes, no more eval() of codes. https://github.com/php-fusion/PHP-Fusion/issues/141
I strongly am against evaluating php codes in admin console via MYSQL. Preview is an ajax file. It won't support evaluation of php code, it's support is - text, html or bbcode. https://github.com/php-fusion/PHP-Fusion/blob/9.00/includes/dynamics/assets/preview/preview.ajax.php
