### ISSUE TITLE
Captcha on registration, all of em are non working

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#267]
No images are displayed, full rights on images folder.

PHPFusion/UserFields.php Undefined index: user_field Line: 418 5 seconds ago

**Comment by meangczac** [comment]
![captcha](https://cloud.githubusercontent.com/assets/4078041/9753635/386750a8-56f2-11e5-83c3-bccf3aeca635.gif)

Not sure working or not. But it displays. I'll try with beta server later.

**Comment by meangczac** [comment]
I tested the grecaptcha - its ok.

**Comment by JoakimFalk** [comment]
Not sure why, but it is still not showing on next on a default new setup.( not tested grecaptcha , just the standard ones )

**Comment by meangczac** [comment]
Secureimage - 

go to : http://localhost/PHP-Fusion/includes/captchas/securimage/securimage_show.php
- replace as your server config params. (i'm on localhost)

If it works, you get a image usually. But this one.. 

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php on line 99

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php:99) in /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php on line 300

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php:99) in /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php on line 301

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php:99) in /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php on line 302

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php:99) in /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php on line 303

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php:99) in /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php on line 304

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php:99) in /Applications/MAMP/htdocs/PHP-Fusion/includes/captchas/securimage/securimage.php on line 315

**Comment by meangczac** [comment]
I patched using our new maincore.php and it fixed everything. I could now register on my localhost using either secure image 1 or 2. I have also tested grecaptcha on localhost earlier and its working as intended.

**Comment by JoakimFalk** [comment]
Yes works.
