### ISSUE TITLE
One odd captcha option or ?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#268]
The option en, no idea what it is doing since the other captchas does not work , 
![en](https://cloud.githubusercontent.com/assets/4210004/9734308/36b8381e-5632-11e5-8e76-49782a92a687.jpg)

Enabled it currently displays nothing, 
![result](https://cloud.githubusercontent.com/assets/4210004/9734339/724f2bda-5632-11e5-820a-0062a4dcbeeb.jpg)

**Comment by meangczac** [comment]
![recaptcha](https://cloud.githubusercontent.com/assets/4078041/9753556/ee013c50-56f0-11e5-8c81-a9d77fb2e5f1.gif)

I have this, but i will fix the en one..  maybe some typo during dynamics select transition.

**Comment by JoakimFalk** [comment]
I synced and EN is still present on next.

**Comment by meangczac** [comment]
Please compare your FTP folder with this: https://github.com/php-fusion/PHP-Fusion/tree/9.00/includes/captchas

**Comment by rimelek** [comment]
So we need to remove "recaptcha" from includes/captchas and the problem is solved. 

There is an index "recaptcha" in locales/LANGUAGE/global.php. It was why "en" appeared in the list as the name of the old recaptcha.

**Comment by meangczac** [comment]
yes, its aggregating with makefilelist function
