### ISSUE TITLE
user field - Location

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#269]
Should we not have this one with our Geomap or what happened with that one?

**Comment by meangczac** [comment]
![user_location](https://cloud.githubusercontent.com/assets/4078041/9753456/a5b13898-56ef-11e5-85e7-6b1fc4cb3613.gif)

User Location(S)... lol

**Comment by meangczac** [comment]
Since v7 have addon based on these values, we're talking about 9 years span. Who knows what they did with user_location... to keep until 9.1 even if we want to deprecate the old one (all users running 7 would have used 9 by then) Thats a safer route for smoother transition.

**Comment by JoakimFalk** [comment]
I am sitting with highlights and figured where is that Geo thing we worked so much on LOL.
So it is the address field ,man the name really does not make up for what it is, Address and you imagine 2 lines. We can simply call it what we called it, Geo Field or something simple, just not address.

**Comment by JoakimFalk** [comment]
Ok done...
https://github.com/php-fusion/PHP-Fusion/commit/a2bd33ab80edd44d5cb1e2a175d4d5765c2de583
