### ISSUE TITLE
The user field option This is a required field   

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#278]
This field should leave some marker in the profile / register form in the shape of a red star when enabled.
Right now nothing indicated that it is a required field from option toggling the option.
Nor does it require the fields it is marked on manually to be completed.

**Comment by meangczac** [comment]
It's all User Fields.
$options = array(
);
RESETS the parameter callback from Admin as Admin include them as $options as well.

$options += array(
);

Adds in addition to missing pairs. Required is one of them.
