### ISSUE TITLE
Custom pages preview adds slashes to php quotes

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#280]
![cpslashes](https://cloud.githubusercontent.com/assets/4210004/9757102/b34c44b8-56de-11e5-8991-f8e05696d947.jpg)

**Comment by meangczac** [comment]
Yes, no PHP in PF9.

**Comment by JoakimFalk** [comment]
I know, no php execution, but the slashes should not be added when previewing.

**Comment by meangczac** [comment]
Ah okay. Wait. too many issues. I come back in a moment.

**Comment by meangczac** [comment]
Do you want to do a "allow php codes" in Admin security $settings? 

![code_execution_enabled](https://cloud.githubusercontent.com/assets/4078041/9760744/5d284b08-572a-11e5-804f-1ac2b457b27a.gif)

**Comment by JoakimFalk** [comment]
yeah it is a good solution
Can be off by default if it makes it safer.

**Comment by meangczac** [comment]
Ok then :+1:

**Comment by JoakimFalk** [comment]
In reality, if people can add code to CPes as many also do, they can still save and then execute.
We either never have data php based in panels nor CPs or we need to have it fully supported.

**Comment by meangczac** [comment]
In a way thats true. It doesn't matter what we do here, users are users really in the end. I might have been looking too much at users point of view. Well, it's up to them at the end. Tech developers are like weapon makers, whether they do good or bad with a product is at their will and intellect.
