### ISSUE TITLE
Available name check upon registration

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#292]
Would be a neat feature to have, anything current interface can easilly do?

**Comment by meangczac** [comment]
Roadmap 9.1 bro. 

I need a post script and the suggest script. Also, the user name reservation is also in this too. I also pushed down 9.1

What we do in 9.1 will be visible to the community once 9.0 is released. Also, PFDN have agenda still, and more developers are expected to join. I need some bullets like these to guide developers in good development procedures, documentation, and ethics too.
