### ISSUE TITLE
User Language

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#295]
```
for ($i = 0; $i < count($enabled_languages); $i++) { // <---- loop every single language.
                // user_language is only 1 selection - how come multiple?
                $result = dbquery("UPDATE ".DB_USERS." SET user_language = '".$settings['locale']."' WHERE user_language !='".$enabled_languages[$i]."'");
            }
```

err.. I thought just outright set user_language = "English" ?

user_language is "English.Polish.Malay" ? I thought it's like user_theme.

like this:

```
dbquery("UPDATE ".DB_USERS." SET user_language='".$inputData['localeset']."'");
```

As I understood so far.. when installed, SA gets "English" in default. Then, when lang select switching, it updates the user_language to "Malay". If user_lang has no value, it should use system locale. 

If so, we do not need to update unless user_language choice no longer exist.  

And as such this line is sufficient:

```
$enabled_languages = "English,Malay,Danish,Polish";

// Resets Russian.
dbquery("UPDATE ".DB_USERS." SET user_language='".$inputData['localeset']."' WHERE user_language NOT IN '".$enabled_languages."'");

```

**Comment by JoakimFalk** [comment]
I don´t know was a year ago that was done, and before someone broke it, it was just about flawless.
