### ISSUE TITLE
Error logs as requested by https://github.com/php-fusion/PHP-Fusion/commit/208e9db104f1ef6b0a4cddf1818309b0916ba4a7

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#297]
administration/settings_languages.php Undefined index: T203 Line: 207
administration/settings_languages.php Undefined index: T202 Line: 207
administration/settings_languages.php Undefined index: T201 Line: 207
administration/settings_languages.php Undefined index: 144 Line: 196
administration/settings_languages.php Undefined index: T101 Line: 206
administration/settings_languages.php Undefined index: T102 Line: 206
administration/settings_languages.php Undefined index: T103 Line: 206
administration/settings_languages.php Undefined index: 143 Line: 195
administration/settings_languages.php Undefined index: 142 Line: 194
administration/settings_languages.php Undefined index: 141 Line: 193
administration/settings_languages.php Undefined index: 140 Line: 192
administration/settings_languages.php Undefined index: 139 Line: 190
administration/settings_languages.php Undefined index: 135 Line: 189
administration/settings_languages.php Undefined index: 138 Line: 187
administration/settings_languages.php Undefined index: 137 Line: 184
administration/settings_languages.php Undefined index: 136 Line: 181
administration/settings_languages.php Undefined index: 134 Line: 178
administration/settings_languages.php Undefined index: 133 Line: 175
administration/settings_languages.php Undefined index: 132 Line: 172
administration/settings_languages.php Undefined index: 131 Line: 169
administration/settings_languages.php Undefined index: 130 Line: 167
administration/settings_languages.php Undefined index: 195 Line: 157
administration/settings_languages.php Undefined index: 194 Line: 156
administration/settings_languages.php Undefined index: 193 Line: 155
administration/settings_languages.php Undefined index: 192 Line: 154
administration/settings_languages.php Undefined index: 191 Line: 153
administration/settings_languages.php Undefined index: 189 Line: 152
administration/settings_languages.php Undefined index: 188 Line: 151
administration/settings_languages.php Undefined index: 187 Line: 150
administration/settings_languages.php Undefined index: 186 Line: 149
administration/settings_languages.php Undefined index: 185 Line: 148
administration/settings_languages.php Undefined index: 184 Line: 147
administration/settings_languages.php Undefined index: 183 Line: 146
administration/settings_languages.php Undefined index: 182 Line: 145
administration/settings_languages.php Undefined index: 180 Line: 143
administration/settings_languages.php Undefined index: 181 Line: 144
administration/settings_languages.php Undefined index: 195 Line: 133
administration/settings_languages.php Undefined index: 194 Line: 132
administration/settings_languages.php Undefined index: 193 Line: 131
administration/settings_languages.php Undefined index: 192 Line: 130
administration/settings_languages.php Undefined index: 190 Line: 128
administration/settings_languages.php Undefined index: 191 Line: 129
administration/settings_languages.php Undefined index: 189 Line: 127
administration/settings_languages.php Undefined index: 186 Line: 124
administration/settings_languages.php Undefined index: 187 Line: 125
administration/settings_languages.php Undefined index: 188 Line: 126
administration/settings_languages.php Undefined index: 184 Line: 122
administration/settings_languages.php Undefined index: 185 Line: 123
administration/settings_languages.php Undefined index: 183 Line: 121
administration/settings_languages.php Undefined index: 181 Line: 119
administration/settings_languages.php Undefined index: 182 Line: 120
administration/settings_languages.php Undefined index: 180 Line: 118
administration/settings_languages.php Undefined index: T301 Line: 208
administration/settings_languages.php Undefined index: T302 Line: 208
administration/settings_languages.php Undefined index: T303 Line: 208
administration/settings_languages.php Undefined index: 201 Line: 219
administration/settings_languages.php Undefined index: 203 Line: 221
administration/settings_languages.php Undefined index: 204 Line: 222
administration/settings_languages.php Undefined index: 205 Line: 223
administration/settings_languages.php Undefined index: 206 Line: 224
administration/settings_languages.php Undefined index: 207 Line: 225
administration/settings_languages.php Undefined index: 208 Line: 226

Some of the issues there are changed locales from setup, I dumped Eng and put it back and most site links broke. It was possible to switch between most languages left and right before. 
Core component locale were in setup.php locale, but if there is a more clever way to loop Infusions locale, by all means that would be ideal. The Infusions who use MLT function wil automatically have the MLT tables installed anyway.

![missing-core-locales](https://cloud.githubusercontent.com/assets/4210004/9813488/39ffc3d8-5886-11e5-8459-4fad6280812b.jpg)

**Comment by meangczac** [comment]
I'll tag this ready to close if nothing happens. 

Note to forum and gallery, if we're to delete the category, the child remains. Fundamentally, need to have article_language and article_cat_language to do a proper clean up (both child and parent relationship). The API doesn't know where to query if our infusion is a wildcard. For example, DB_ADDONDB.
