### ISSUE TITLE
On translation

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#298]
Hello there.
Sorry if this the wrong way to ask.
On my way to translate it in German i found a lot not used strings and not showed strings on page.
What should i´m do with them?
report? delte? ignore? translate too?

Greatz WuChEn

**Comment by Rizado** [comment]
Send me in PM please. I saw such lines too.

**Comment by Der-WU** [comment]
how can i send a pm on github? :D or you mean on php fusion website?

Greatz WuChEn

**Comment by Rizado** [comment]
Email.

**Comment by meangczac** [comment]
Dup, Extra, can be deleted naturally. By all means submit the push, and commit can trace back if accident happen.
