### ISSUE TITLE
Venus Admin Theme

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#299]
I have a large screen, and the wording in Venus Admin theme is too small. I'm going bigger fonts and make over with some additional stuff. 

Cookie slider is not a perfect solution. I'm going to rethink the concept. When Venus comes out a year ago, sidebar in admin is a "new" thing . Now when i check Envato.. every designer copies the same layout over and over it gets too boring. 

Give me some time to reboil Venus. I'll be keeping the blue shades.

**Comment by meangczac** [comment]
I remembered user dashboard in v8. let me get the script out and see if i can turn some parts into widget.

**Comment by JoakimFalk** [comment]
:) Id vote to keep Venus as is and make Venus X2 or something related as an optional theme ( or new primary )

**Comment by Rizado** [comment]
@Domi-php , you are right. Let save Venus and make other theme.

**Comment by JoakimFalk** [comment]
uhoh, did someone remove the option to switch Admin Theme in the admin?,  lol I can´t find it !

**Comment by meangczac** [comment]
http://localhost/PHP-Fusion/administration/settings_theme.php?aid=9ff53020f31be590

who did this page :dancer:

**Comment by JoakimFalk** [comment]
hehe oh yeah I did ! but it is gone from my install, trolls in that one now. Re-installing today.

**Comment by meangczac** [comment]
Ok, i've submitted latest additions and removal for all of Admin interface now. Closing.
