### ISSUE TITLE
Fresh install errors - Installer does not recognize languages

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#300]
Seems the installer does not know my languages.. this is from step 5 > step 6.
Selected languages during install , English, Malay, Russian
PDO selected from scratch.

Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include() [function.include]: Failed opening '../locale//setup.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include() [function.include]: Failed opening '../locale//setup.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include() [function.include]: Failed opening '../locale//setup.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include() [function.include]: Failed opening '../locale//setup.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include() [function.include]: Failed opening '../locale//setup.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include() [function.include]: Failed opening '../locale//setup.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include(../locale//setup.php) [function.include]: failed to open stream: No such file or directory in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90
Warning: include() [function.include]: Failed opening '../locale//setup.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/nextphpf/public_html/RC7/infusions/articles/infusion.php on line 90

**Comment by meangczac** [comment]
include(../locale/[MISSING-FOLDER]/setup.php) .. Ok, will check why.

Yes, sorry, found the bug. Will resolve in an hour.

**Comment by meangczac** [comment]
should resolve now. doesn't relate PDO. The line was old inclusion method. I changed.
