### ISSUE TITLE
Private message complete halt - default install new user default fields and first message to it.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#309]
As Administrator I can read with no errors.

Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct() [<a href='datetimezone.--construct'>datetimezone.--construct</a>]: Unknown or bad timezone ()' in /home/nextphpf/public_html/RC7/includes/core_functions_include.php:1132 Stack trace: #0 /home/nextphpf/public_html/RC7/includes/core_functions_include.php(1132): DateTimeZone->__construct('') #1 /home/nextphpf/public_html/RC7/themes/templates/global/messages.php(92): showdate('shortdate', '1442384991') #2 /home/nextphpf/public_html/RC7/themes/templates/global/messages.php(69): _inbox(Array) #3 /home/nextphpf/public_html/RC7/messages.php(46): display_inbox(Array) #4 {main} thrown in /home/nextphpf/public_html/RC7/includes/core_functions_include.php on line 1132

**Comment by meangczac** [comment]
#316 will fix this. (Edit: Rizado said, his proposed solution is buggy and not perfect. So, he dropped his proposal and I will fix this my way.) #316  will postpone until 9.1

**Comment by JoakimFalk** [comment]
This did the trick https://github.com/php-fusion/PHP-Fusion/commit/e1565081e7c80a45f41653953136d250585d7899 ( along with other halt issues )
