### ISSUE TITLE
Forum Upgrade

### ISSUE THREAD

**Issue by Dahlgren** [PHPFusion/PHPFusion#311]
The new forum infusion database structure seems to differ a lot from 7.02.07. The current upgrade process does not seem to handle the migration. Will this be done before the RC or the release?

**Comment by meangczac** [comment]
Good note. However, in general if anybody here is keen enough, you are <strong>always welcome</strong> to do a pull request <strong> to any issues</strong> reported.

But I personally will not touch forum at all before every single issues is solved. I need to focus on forum alone when I do it. I tend to forget things when I go back and forth.

**Comment by Dahlgren** [comment]
I'd be happy to provide a pull request with the updates required. I tried to fix it manually on an upgraded install a few weeks ago but I even had issues with getting the forum working on a clean install. Perhaps it works better now, I can give it a try again. Is there any documentation or anything how the new fields for the forum works?

It also seemed that previous parts such as news and forum are not automatically activated as infusions either but that's a separate issue I guess.

**Comment by hien-** [comment]
Well, they are all done in a model view basis. What core does now is to inject the installation parameters on infuse, and when you run the codes on the forum, it sends data to the relevant files in /templates/, in this case infusions/forum/templates/forum_main.php, forum_input.php and forum_thread.php

forum_main is ex forum.php and forum?viewforum={%d}
forum_thread.php is for ex viewthread.php?thread_id={%d}
and forum_input.php is where all the forms are.

**Comment by meangczac** [comment]
No worries there, I'll cover it very soon when I rewrite the whole codebase. I've been busy covering all issues lately and it seems I am succeeding in suppressing most of it.

**Comment by Dahlgren** [comment]
Are you sure all the new forum fields are being added when updating from 7.02.7?

**Comment by Dahlgren** [comment]
There's no migration for all columns on the forums, threads and posts tables from 7.02.7.

Compare
https://github.com/php-fusion/PHP-Fusion/blob/7.02.07/setup.php#L520
with
https://github.com/php-fusion/PHP-Fusion/blob/9.00/infusions/forum/infusion.php#L90

Migration occurs in https://github.com/php-fusion/PHP-Fusion/blob/9.00/administration/upgrade/upgrade-7.02-9.00.php#L176

Only table names are changed.

**Comment by meangczac** [comment]
Oh, DB_FORUMS. ok, i was checking on consistency, my bad.
