### ISSUE TITLE
missing breadcrumb on faqs

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#313]
the bradcrumb is missing on faq page

Greatz WuChEn

**Comment by JoakimFalk** [comment]
I can see them clearly, be more exact in the problem description, maybe you have a incomplete translation, idk what could cause your issue really.
They do look a tad differant from Some others, but still they are there.

![breadcs](https://cloud.githubusercontent.com/assets/4210004/9926046/1cb90e3e-5d12-11e5-9cb6-c04507b7cc45.png)
