### ISSUE TITLE
showdate() optimization - for discuss first

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#316]
We use showdate() function (or showsubdate() etc.) some times at most pages. As time argument this functions requires Unix timestamp. And we calculate timeshift with every call of showdate.
I propose next:
In /maincore.php before lines:
// User level, Admin Rights & User Group definitions
define("iGUEST", $userdata['user_level'] == 0 ? 1 : 0);
define("iMEMBER", $userdata['user_level'] <= -101 ? 1 : 0);
add these:
$curr_timezone = isset($userdata['user_timezone']) ? $userdata['user_timezone'] ? $settings['default_offset'];
date_timezone_set($curr_timezone);

After that we can change showdate() to:

function showdate($format, $val) {
    global $settings;
    if ($format == "shortdate" || $format == "longdate" || $format == "forumdate" || $format == "newsdate") {
        return strftime($settings[$format], $val);
    } else {
        return strftime($format, $val);
    }
}

And after that option $settings['server_offset'] will be not needed.
Now all time values in DB is saved in UTC - function time, which we use, works with UTC only. And we have less calculations.
Besides, this way has another positive side - any time will be displayed correctly at that moment. For example, my current timezone is Europe/Moscow. Now is 17.09.2015, 12:01:32. But if we subract 365*86400 (a year), showdate() show 17.09.2014, 13:01:32, because timezone was changed.

**Comment by hien-** [comment]
Do it.
