### ISSUE TITLE
Words for formatting to single and plural forms not working right?

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#319]
I have created comments and ratings on news, but single and plural not working on news!
I hope it´s a bug and not a locale problem. ;)
It always show single.

Greatz WUChEn

**Comment by Rizado** [comment]
Thanks, I see this.

**Comment by Rizado** [comment]
What locale you use?

**Comment by Der-WU** [comment]
own german. 
i will try IT on english in the evening.

**Comment by Rizado** [comment]
Please made pull request, I'll merge.
Can you explain me about single and plural forms in German? I'll create function for tis language.

**Comment by Der-WU** [comment]
i only had 50% rdy of german language. :D Sorry, i´m a trucker, not time every day. :D 
if language rdy and tested i start a pull request.
i will be make photos of the issue.

**Comment by Rizado** [comment]
No problem, some languages are translated partially too.

**Comment by Der-WU** [comment]
![news_psted](https://cloud.githubusercontent.com/assets/164333/10051344/55ebfc16-6221-11e5-905a-dff655739444.png)
![one_comment](https://cloud.githubusercontent.com/assets/164333/10051345/55f051bc-6221-11e5-9c4a-9176bab4923e.png)
![second_comment](https://cloud.githubusercontent.com/assets/164333/10051346/55f1b8f4-6221-11e5-94b5-d5fd1acd7c96.png)

On German it should be:

0 Kommentare | 1 Kommentar | 2 Kommentare | 3 Kommentare
0 Bewertungen | 1 Bewertung | 2 Bewertungen | 3 Bewertungen

$locale['fmt_comment'] = "Kommentar|Kommentare";
$locale['fmt_rating'] = "Bewertung|Bewertungen";

The problem its, it always show single.

The second Problem is, german is a hard language.
0 and all more then 1 need plural
only 1 need single.

I think that problem can´t get solved, but the first. ;)

Greatz WuChEn

**Comment by JoakimFalk** [comment]
Yes it is the same for Swedish, The code and locale need to differ from 0 and more as a minimum.
pretty much the same in English for example , 
0 Comments
1 comment 
2 comments

0 Votes
1 Vote
2 Votes

**Comment by Rizado** [comment]
OK, @Domi-php , I'll fix this.

**Comment by Der-WU** [comment]
![rating_2_comments](https://cloud.githubusercontent.com/assets/164333/10053896/b91affc8-622e-11e5-9731-534a4ceb2045.png)
![rating_3_comments](https://cloud.githubusercontent.com/assets/164333/10053897/b93fadaa-622e-11e5-82df-7c4b236e0943.png)

Tanks. and now i See on my Screenshots thats comments Are Used for Ratings.

See the pictures again. Theresa Are only one Rating and it shows 2. After the third comment its Show 3 Ratings too. 

i will installiert english Version in a subfolder too, to Check if it a core Problem or a laguage Problem. 

greatz wuchen

**Comment by meangczac** [comment]
Is this boiled down to $locale translations now? Is this issue fixed? Please respond and close as soon as it's done. I said before, I will not open up forum.php at all until all problem is fixed.

**Comment by Der-WU** [comment]
Issus still present. Tested latest git hub verison.

**Comment by JoakimFalk** [comment]
One of the issue is clearly a translation mixup issue, the other can be missing plural here and there but one of the places where it actually works in English is in News, so we can close this issue.
3.00 out of 1 rating should be out of 1 vote, to switch to 2 votes or out of 0 votes..
Idk, I tackle later if needed.
For now, with these screens, please see your translation files, case closed.

![0-comments](https://cloud.githubusercontent.com/assets/4210004/10098887/f8dd6db0-6384-11e5-9993-ad767531e497.png)
![1-vote](https://cloud.githubusercontent.com/assets/4210004/10098890/f8e06b78-6384-11e5-8efd-f3adeb8f5872.png)
![2-comments](https://cloud.githubusercontent.com/assets/4210004/10098889/f8e06b32-6384-11e5-860a-db5958757f7f.png)
