### ISSUE TITLE
Add Download

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#321]
Searching and uploading Download only allow image Files. No other.

**Comment by JoakimFalk** [comment]
Please be more specific, a screenshot helps. In most places allowed download types are definable.
Per default zip, rar, pdf etc are allowed in the download system. Also URL is possible.

**Comment by Der-WU** [comment]
Hey Domi. Here 2 Screenshots.Sry, i think it´s because my bad english.
rar are allowed, but if i try to upload it, it says only images allowed.
![download_invalid_type](https://cloud.githubusercontent.com/assets/164333/9979663/97c8cc28-5f78-11e5-8190-9c050cd19434.png)
![download_settings](https://cloud.githubusercontent.com/assets/164333/9979664/97cb8332-5f78-11e5-85d4-ee93fdcacfce.png)
