### ISSUE TITLE
Deleting a member will give you a whole range of issues depending on content

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#323]
Since all have gone modular we must check if the database exists before trying to sanitize it.
Also message options was moved ( not sure to what but it need to be changed here as well ).

**Comment by meangczac** [comment]
Regarding PM, Message options have 2 sets, one runs with $settings, and the other runs with DB_USERS.
- comments posted
- ratings posted
- forum posts posted
- news posted
- articles posted
- downloads posted
- photo posted
- message posted

So when deleting users, yes, all rows associated with that specific users must be removed altogether. We'll handle this after forum for a final check.
