### ISSUE TITLE
phpFusion 6 - Support and Download source

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#324]
Dear developers,

I am interested as a tester for phpFusion 6 and just trying to install an old version. But that does not work and I will fault is displayed. Are there any support for it and where you can download the very last version of PHP Fusion. 6

Looking forward, if you can help me. Thanks in advance.

**Comment by JoakimFalk** [comment]
Hi, 
We do not provide support here on Github, it is solely for Developing and issue reports.
The development of PHP-Fusion 6 and it´s support was closed many years ago.
You can find both Support and Downloads for the latest versions of PHP-Fusion here : https://www.php-fusion.co.uk
We are about to release the next generation of PHP-Fusion as well.
