### ISSUE TITLE
Undefined offset: 101 

### ISSUE THREAD

**Issue by Bloodmorphed** [PHPFusion/PHPFusion#327]
https://github.com/php-fusion/PHP-Fusion/blob/9.00/infusions/forum/classes/Functions.php#L172

Undefined offset: 101 

No clue what this means, but got it in my error log opening topics in the forums.

**Comment by meangczac** [comment]
Unaltered User Level in Forum Ranks, 101 is group_id 101 in V9. It's not MEMBER anymore. 
MEMBER is -101. The change here will fix it.

https://github.com/php-fusion/PHP-Fusion/blob/9.00/infusions/forum/infusion.php#L239-L247

**Comment by meangczac** [comment]
This will fix your error forum ranks. Paste into your system. Refresh a couple of times, like home.php or something. Let it run. No harm done.

```
// Fix your forum ranks to new user level. 
$fix_forum_rank_query = dbquery("SELECT * FROM ".DB_FORUM_RANKS);
if (dbrows($fix_forum_rank_query)>0) {
    while ($fix_data = dbarray($fix_forum_rank_query)) {
        $fix_data['rank_apply'] = "-".$fix_data['rank_apply']."";
        dbquery_insert(DB_FORUM_RANKS, $fix_data, "update", array("keep_session"=>true));
    }
}
```

or defuse and infuse back with the latest git.
