### ISSUE TITLE
Can´t change or manage themes after last update

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#330]
Can´t change or manage themes at all after last update

**Comment by JoakimFalk** [comment]
Bootstrap Theme is activated, shows Arise. Clicking on activate theme does nothing for any of the themes in the list.

![nogo](https://cloud.githubusercontent.com/assets/4210004/10100274/d45a8020-6390-11e5-8398-b3c68253bac4.png)

**Comment by meangczac** [comment]
Actually i just checked everything is fine. The system theme activation stores theme in $settings['theme']. Now, you can override the theme settings in your edit_profile.php, which was bootstrap. So when you login, you ought to see your preferred theme. But when you log out, the site follow $settings['theme'].

Now i have changed your admin account user theme to Default. It will follow system $settings['theme'].

**Comment by JoakimFalk** [comment]
oh, that´s right. One thing then. We need it to not work if the option to allow user theme is off.

**Comment by meangczac** [comment]
the $_GET only for iSUPERADMIN. For <strong>us</strong> specifically to switch theme without going thru and fro Admin Panel
