### ISSUE TITLE
Run-time notices after creating a poll

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#333]
Undefined offset: 2
Line: 74 File -- infusions/member_poll_panel/member_poll_panel.php
On Page -- /home.php 

Undefined offset: 2
Line: 75 File -- infusions/member_poll_panel/member_poll_panel.php
On Page -- /home.php

**Comment by meangczac** [comment]
From the way i read the codes, did you check what is the output on Line 47? Can you please do a print_p($poll_option); and see if you have a complete array cache.

**Comment by meangczac** [comment]
```
if (dbrows($result)) {
    $data = dbarray($result);
    $poll_title = $data['poll_title'];
    $poll_option = array();
    for ($i = 0; $i <= 9; $i++) {
        if ($data["poll_opt_".$i]) $poll_option[$i] = $data["poll_opt_".$i]; // <---- $poll_option at Line 74 will behave badly if this is bad.
    }
print_p($poll_option); // <--- add this line

```

tell me what you see.

**Comment by Der-WU** [comment]
mom i do this.

the problem comes only after editing the poll i figured out.
after saving the edit, the poll create an empty 3 option.
with this the error is coming.

Output of print_p

Array
(
    [0] => Gut
    [1] => Schlecht
    [3] => Schlecht
)

But there only 0 and 1 on poll.

**Comment by JoakimFalk** [comment]
Indeed odd, I just made one and placed a vote on it. No issues there.

**Comment by Der-WU** [comment]
hmmmm.
After some time the error is going away.

please create a Poll. vote for it on Frontpage. 
Theo edit the Poll without any changes and save it. then go back on Frontpage and open the Poll on poll Archive. 

tested with latest git Version on english and german. 

pdo is on. i will test it without pdo.

**Comment by Der-WU** [comment]
Error comes always if i select a poll on poll_archive too. 

Greatz WuChEn

**Comment by JoakimFalk** [comment]
This might solve it, I can not get the error with or without token, with or without PDO.
https://github.com/php-fusion/PHP-Fusion/commit/9a296c5aa0ff1801559d39fcc719f36491882f89

**Comment by Der-WU** [comment]
Okay. poll archive fixed. 
Only after editing the poll on admin, the error is given for a time.

Greatz WuChEn

**Comment by Der-WU** [comment]
Bug still exist.

The way:

create a poll 
save the poll
go on frontpage
go back to admin
edit poll
save poll without changes
see frontpage

error log on admin:

Undefined offset: 2
Line: 55 File -- infusions/member_poll_panel/member_poll_panel.php
On Page -- /home.php
generated by User-Level: -103 -- IP: 79.205.119.179
on October 23 2015 18:45:28

**Comment by hien-** [comment]
Cannot find issues as well.
