### ISSUE TITLE
Whole range of notices when trying to Infuse a V7 infusion ( fresh sync from today )

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#334]
administration/infusions.php Undefined index: position  Line: 166
administration/infusions.php Undefined index: page  Line: 150
administration/infusions.php Undefined index: icon  Line: 166
administration/infusions.php Undefined index: position Line: 164
administration/infusions.php Undefined index: icon  Line: 164
administration/infusions.php Undefined index: page  Line: 148

**Comment by meangczac** [comment]
Please test the infusing again.
