### ISSUE TITLE
Send PM Function changed?, Make it compatible with V7 or a full rollback.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#335]
As seen in the image, 4 PM was sent and registred with old V7 Standard, send PM function.
None is listed in the box.

![4](https://cloud.githubusercontent.com/assets/4210004/10121721/4d13203e-64fa-11e5-913e-6a00eb708315.png)

**Comment by meangczac** [comment]
Give me your send_pm code. I just checked:

send_pm(1,2,"Subject", "message", "y"); -- works ok.

Go to /includes/classes/PHPFusion/PrivateMessages.php
Line 177 - set $strict to TRUE. see what happens in case you wonder why pm was not sent.

Please double check the codes again, it's all v7 codes with additional $save_sent params added. 

v7
send_pm($to, $from, $subject, $message, $smileys = 'y');

v9
send_pm($to, $from, $subject, $message, $smileys = 'y', $to_group = FALSE, $save_sent = TRUE);

How can it not be V7 compatible? Just omit the last 2 parameter.
