### ISSUE TITLE
articel comments

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#356]
i would fix it, but i don´t understand how to use fmt_comment.

the line on articel template is: 

```
    $comment = "<a href='".INFUSIONS."articles/articles.php?article_id=".$info['article_id']."#comments'>".$info['article_comments']." comment</a>\n";
```

the comment is hardcoded.

**Comment by meangczac** [comment]
Use like this;  Replace hardcoded comment with

```
".format_word($info['article_comments'], $locale['fmt_comment'])." 
```

All language goes through it, and the rules are <strong>auto selected</strong> whether English, Russian or German.

**Comment by Der-WU** [comment]
Working nice, thanks.
