### ISSUE TITLE
some problems with blog infusion

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#358]
hi there.
i have found some problems with the blog infuison.
1. latest_blog_panel don´t check language
2. latest_blog_panel don´t check visibly for
3. Blog overview by author don´t check language on count 
4. blog overview don´t show blogs. tested with all funktions, like most comment, highest rating, kategorie ....( Don´t know it´s a webserver problem, please check it. )

Greatz WuChEn

**Comment by meangczac** [comment]
Hi, I do not understand where, there is no latest_blog_panel in my system. There is however a blog_archive_panel. Is this the one to look into?

I'll check the blog overview for you. Do you have any SQL error regarding these Blog overview crashing for you?

<strong>CHECKED: Blog overview is doing ok.</strong>

Waiting now.

**Comment by hien-** [comment]
CHECKED: Blog overview is doing ok.

**Comment by Der-WU** [comment]
All right.  I mein Blog_Archive_panel.
It's don't Check language and Show on every language all entries.  and it doesn't Check the visibly rights.  Always Show all the guest.

**Comment by JoakimFalk** [comment]
This should do it, https://github.com/php-fusion/PHP-Fusion/commit/15e7bc3694b8263de6644d2fe143e48051ae6196
