### ISSUE TITLE
DB Backups 

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#381]
When i have selected a file to import it creates:

unlink(../administration/db_backups/): Is a directory
Line: 128 File -- htdocs/administration/db_backup.php
On Page -- /administration/db_backup.php 

Undefined variable: files
Line: 128 File -- htdocs/administration/db_backup.php
On Page -- /administration/db_backup.php 

if i try to import a backup 

Fatal error: Call to undefined method PHPFusion\Database\Driver\PDOMySQL::prepare() in /var/www/web1/htdocs/administration/db_backup.php on line 152

Greatz WuChEn

**Comment by hien-** [comment]
i didn't code this area... my expression now is.. like this.
![lol-i-dunno](https://cloud.githubusercontent.com/assets/4078041/10365629/633f30b8-6df7-11e5-9044-707811805091.jpg)

**Comment by meangczac** [comment]
152 .. What is your current PHP version? 

(PHP 5 >= 5.1.0, PECL pdo >= 0.1.0)
PDO::prepare — Prepares a statement for execution and returns a statement object

**Comment by Der-WU** [comment]
Server software Linux zulu1398 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64
Webserver software  Apache
PHP version 5.4.45-0+deb7u1
PHP interface   cgi-fcgi

**Comment by Der-WU** [comment]
no more notice. but Import says now every time wrong File Format After importing the Backup.

**Comment by meangczac** [comment]
Will look into it.

**Comment by meangczac** [comment]
Another Pandora Box.

**Comment by meangczac** [comment]
I've completed the check. Everything works as intended. 
This git refers : https://github.com/php-fusion/PHP-Fusion/commit/d7b0638c93d9b545c87c419a2fc06c24cd8d6ffe
