### ISSUE TITLE
user field re-shuffled 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#387]
See the Options divider, Admin options should go below it, and it all should be all the way down below every field. ( last in profile ).

![user-field-reshuffled](https://cloud.githubusercontent.com/assets/4210004/10331960/d975e098-6cd9-11e5-84e9-d1aaa371af5d.jpg)

**Comment by meangczac** [comment]
So admin options not in header but in footer.

**Comment by meangczac** [comment]
Cut, paste, done.
