### ISSUE TITLE
post & thread count is repeated from first post thru all threads with same numbers

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#401]
3 Posts
2 Threads
Naturally, the numbers are differant in reality for these forums.

![post-count](https://cloud.githubusercontent.com/assets/4210004/10392295/14df6e76-6e86-11e5-9c31-a6c697f5e7aa.jpg)

**Comment by meangczac** [comment]
![screen shot 2015-10-10 at 4 43 11 pm](https://cloud.githubusercontent.com/assets/4078041/10410238/0b7043b8-6f6e-11e5-8356-0c457a1ea5fe.png)
![screen shot 2015-10-10 at 4 42 59 pm](https://cloud.githubusercontent.com/assets/4078041/10410239/0b9d7f18-6f6e-11e5-8850-383e977b5819.png)

You see it's not replicating on my side. Can you defuse and infuse again? I'm not sure what caused the forum updating wrongly.

The information 3 posts , 2 threads is from -- DB_FORUMS. (See the image of phpmyadmin)

![screen shot 2015-10-10 at 4 45 35 pm](https://cloud.githubusercontent.com/assets/4078041/10410251/684ba190-6f6e-11e5-90e0-f457a26d18c9.png)

**Comment by JoakimFalk** [comment]
Yep, can´t reproduce same problem on a fresh install !
