### ISSUE TITLE
Download submit

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#407]
Hello.

I have checked Download submit.
Every time i got the error, file is to big.
file size, 1,5 MB.
allowed on settings 5 MB

and another notice on submit is:

Fusion Dynamics invalid accepted extension format. Please use either | or ,

Greatz WuChEn

**Comment by Der-WU** [comment]
downloads/download_submit.php
Undefined index: target_file
Line: 62

includes/infusions_include.php
in_array() expects parameter 2 to be array, null given
Line: 175

**Comment by meangczac** [comment]
Hi, WuChen, what did you upload? Just curious. Because it's either a file or it's a zip, hence target file according to the v7 api return

```
// might be image, might be file
                if (!empty($upload['image_name'])) {
                    $criteriaArray['download_file'] = $upload['image_name'];
                } else {
                    $criteriaArray['download_file'] = $upload['target_file'];
                }
```

**Comment by meangczac** [comment]
I'll increment on this for now.

<blockquote>
includes/infusions_include.php
in_array() expects parameter 2 to be array, null given
Line: 175
</blockquote>

**Comment by Der-WU** [comment]
Tested with *.rar *.mp3 and *.jpg. 
Always Same. 
Test latest git in the evening.

Greatz wuchen

**Comment by meangczac** [comment]
Please elaborate further bro. I'm confused at this moment.

There are 2 fileinput - one for file, one for screenshot in Download Submit. I need you to describe step by step for me to visualize the problem here. 

What did you do, and what error came in. Don't test everything one go. I dont know where to debug. Do one fileinput at a time. If no error message, test the other file input.

Thanks.

**Comment by Der-WU** [comment]
Okay hien. 
Sorry, now i am at home. :)

i have try to submit a download.
Only entered download titel and download description.
then select an rar file.
NO Image selected for download!
and with latest git now it says:

There was an error while processing your request
Upload file too large. File must be less than 1.43MB.
Fusion Dynamics invalid accepted extension format. Please use either | or ,

Admin download settings are:
max file size 50 MB ( 47.68MB )
allowed files default by setup
picture requiered and full description deactivated!

error log on admin 

Undefined index: target_file
Line: 62 File -- infusions/downloads/download_submit.php
On Page -- /submit.php
generated by User-Level: -103 -- IP: 79.205._._ on October 23 2015 18:33:45

---

with an file smaler then 1.43 MB error is:

There was an error while processing your request
Upload file is not a valid file type. Image must be one of the following file types -
Fusion Dynamics invalid accepted extension format. Please use either | or ,

Greatz WuChEn

**Comment by meangczac** [comment]
I'll test the dynamics again.

**Comment by meangczac** [comment]
Please check after upgrade this still persist. We really cannot replicate this anywhere.

**Comment by JoakimFalk** [comment]
Download submit from the front-end causes this.
![submit](https://cloud.githubusercontent.com/assets/4210004/11027408/3e975c3c-86b5-11e5-8902-ce4b9269c6c8.jpg)

**Comment by Der-WU** [comment]
Now working.
But there is still an bug.
Download Settings are set to 50 MB for uploading Files.
Server Settings are 50 MB too.
But Download Submit Upload only accept files smaler then 1,43 MB.

Greatz WuChEn

**Comment by meangczac** [comment]
In ~Line 179 download_submit.php, after $file_options , add after:

```
print_p($file_options);
```

Save, upload, refresh

See what is your max_bytes. Please give me screenshot.

**Comment by Der-WU** [comment]
Array
(
    [class] => m-10 p-10
    [inline] => 1
    [required] => 1
    [upload_path] => infusions/downloads/submissions/
    [max_bytes] => 50000000
    [valid_ext] => .pdf,.gif,.jpg,.png,.zip,.rar,.tar,.bz2,.7z
    [error_text] => Download Datei wird benötigt
    [width] => 100%
    [thumbnail] => 
    [thumbnail2] => 
    [type] => object
    [preview_off] => 1
)

All right.
I selected an 10,5 MB File and klick on Submit, then the error says, file is to big, 

![download_upload](https://cloud.githubusercontent.com/assets/164333/11124258/64fbf098-8964-11e5-80f8-33f088b345a6.png)

**Comment by meangczac** [comment]
Ok, please check apache - http://www.cyberciti.biz/faq/linux-unix-apache-increase-php-upload-limit/

Please try with a smaller treshold - If you upload say 500kb file, and 1mb is the limit and still error, then thats our problem in defender core file.

**Comment by Der-WU** [comment]
PHP Settings checked.

post_max_size   50M
upload_max_filesize 50M
max_execution_time 300
memory_limit    128M

Error still exist.

Submit with Files smaler then 1,43 MB are working without problems.

**Comment by meangczac** [comment]
Ok, what are the pages that has this problem?

Last this was fixed in the submission of download. 

How about Download Admin Panel? Can you add the files in?

Issue reopened.

**Comment by JoakimFalk** [comment]
I will tinker with it.

**Comment by Der-WU** [comment]
I have checked Download creation on Download Admin too.
Same Error.
File bigger then 1,43 not accepted.

I got those errors on try on admin

admin/downloads.php
Undefined index: source_size
Line: 111

admin/downloads.php
Undefined index: image_name
Line: 109

and on download submit i got 

downloads/download_submit.php
Undefined index: target_file
Line: 62

Greatz WuChEn

**Comment by meangczac** [comment]
Wuchen, Online or localhost?

**Comment by Der-WU** [comment]
all tested online
