### ISSUE TITLE
Private messages not shown after upgrade

### ISSUE THREAD

**Issue by Dahlgren** [PHPFusion/PHPFusion#414]
Private messages are not shown after upgrading the database from 7.02.7. I'm guessing this is due to `message_user` being 0 for all rows in `messages` table and `user_inbox` being 0 for all rows in `users` table

**Comment by meangczac** [comment]
yeah the message user is the inbox owner.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/blob/7.03/messages.php#L163

Say message_to is recepient's id. I'll try to see what i can.
