### ISSUE TITLE
Forum Types after upgrade

### ISSUE THREAD

**Issue by Dahlgren** [PHPFusion/PHPFusion#415]
All forums are marked as category after upgrade from 7.02.7. This makes all threads unreadable until type has been changed. I think forums which have a parent in 7.02.7 should have the forum type instead of category so that threads work on update. Any thoughts?

**Comment by meangczac** [comment]
yes, can you reflect the change while i figure out the #414

**Comment by Dahlgren** [comment]
I can fix a PR later today

**Comment by meangczac** [comment]
ok
