### ISSUE TITLE
In language settings we need an mass updater for all Core Infusions

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#424]
We need a mass changer on Core Infusions / Components language tables need to be set to system default language when an optional Language is removed from the installed languages.
This is to avoid issues such as , 
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=36932&pid=196384#post_196379
and 
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=36933&pid=196382#post_196382

**Comment by meangczac** [comment]
Don't language settings work? $inf_mlt can drop and rebuild lang on the fly.

**Comment by JoakimFalk** [comment]
Yeah, my memory failed me on this part.

Please note: By removing a language you also remove all customized site links, categories and any other multilangual content for the specific language from the system.
