### ISSUE TITLE
Administrator is Unable to Change Password for Member

### ISSUE THREAD

**Issue by thepcn3rd** [PHPFusion/PHPFusion#430]
Maybe this is a feature and not a bug.  I noticed that, if an administrator was asked to update a password for a member, you type in the "Set New Password" and then confirm the password.  After you click the submission of the edit member it states that the profile was updated but the password was never changed.

The reason why I wonder if this is a feature and not a bug is the member should be directed or be going to the forgot password page to reset the password.  Just thought I would point this out and I understand if it is a feature and not a bug.

Thank you.

**Comment by meangczac** [comment]
Yes, ok. I'll check it.
