### ISSUE TITLE
User signature migration

### ISSUE THREAD

**Issue by Dahlgren** [PHPFusion/PHPFusion#431]
Migration of user signature fails when upgrading from 7.02.7. Old dababase type is TEXT which has no upper limit for number of characters where as new is VARCHAR with 255 letter limitation. Database will not allow this migration if any row has a column value for `user_sig` with more than 255 characters.

``` sql
ALTER TABLE fusion7_users CHANGE user_sig user_sig VARCHAR(255) NOT NULL DEFAULT '' 
```

Error while migrating:
`Data too long for column 'user_sig'`

7.02.7: https://github.com/php-fusion/PHP-Fusion/blob/7.02.07/setup.php#L981
9.0: https://github.com/php-fusion/PHP-Fusion/blob/9.00/install/includes/core_setup.php#L378
Migration: https://github.com/php-fusion/PHP-Fusion/blob/9.00/administration/upgrade/upgrade-7.02-9.00.php#L741

Column values for `user_sig` needs to be truncated to max number of characters before changing data type.

**Comment by meangczac** [comment]
The design in user signature does not bear much importance as much as compatibility. Lets follow the old one for BC reasons. I'll amend.
