### ISSUE TITLE
LOCALE NOTICES TO ALL - PLAIN TEXT ONLY (PLEASE READ)

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#435]
Problem arises where locale values contains any of the following:

<ul>
<li>$aidlink</li>
<li>$userdata</li>
<li>HTML tags such as text styling and anchor href or src link.</li>
</ul>

HTML tags in Locales will had been tested not to work on get_text() API. 

As a resolution, we need to remove this and use [AIDLINK], [USERDATA_ID] etc. Adjustments are necessary for the long term beneficial effect. Locales must purely be plain text only. We will not be able to decipher HTML text when going through any kinds of translation service.

Please report ANY locale key and filename where it contains any of these, pointing a link to the lines involved is much appreciated. 

The first round will be on English Locale, and after we're done, then to update the rest of the locale libraries. 

Thank you.

**Comment by meangczac** [comment]
K, Now everything should be in plain text, excepted for one global locale containing "Please wait while we transfer you..... ". Where is this used? I can't find it.

**Comment by JoakimFalk** [comment]
It used to be in setuser.php but it is not used since some versions ago.

**Comment by meangczac** [comment]
Ok, the final one is in then. Those who want to use it in their mods can just do a str_replace() as I've done.
