### ISSUE TITLE
LINK missing on sign in page

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#438]
![nolink](https://cloud.githubusercontent.com/assets/4210004/10935118/2eaa8f3a-82e4-11e5-81b8-44058b037155.jpg)

**Comment by ALTUN69** [comment]
LINK sayfasında işareti eksik # 438

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/b1db9f32743707fcd8fae8275ce1e327205ee168

Close
