### ISSUE TITLE
Notices after latest git, news & blog, permalinks enabled

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#444]
admin/news.php Undefined index: blog_0425a  Line: 237
admin/news.php Undefined index: blog_0426b  Line: 249
PHPFusion/PermalinksDisplay.php Undefined index: 0 Line: 530
RC7/login.php Undefined index: user_name  Line: 89
RC7/login.php Undefined index: user_pass  Line: 90

**Comment by meangczac** [comment]
PHPFusion/PermalinksDisplay.php Undefined index: 0 Line: 530
is -- $replace = str_replace($other_tags, $this->data_cache[$type][$match][$other_attr], $replace);

I have no idea what it is replacing.
