### ISSUE TITLE
When reading blog the theme header background poofs 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#449]
Since it stays in News, I take it as an misstake.

![untitled-9](https://cloud.githubusercontent.com/assets/4210004/11027586/1e6a6ac4-86b7-11e5-887c-c8c9f92fe866.jpg)

**Comment by meangczac** [comment]
http://next.php-fusion.co.uk/RC7/infusions/blog/blog.php?readmore=3

It's the SEO engine. Not blog or theme. Changing this issue to SEO.

**Comment by meangczac** [comment]
The background is served from css file it's hardcoded path. The adjustment needed is to use php style instead so it will recalculate what is the proper directory seperator to support SEO
