### ISSUE TITLE
Settings stopped work?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#452]
Admin Dashboard > Settings > Security Settings 

There was an error while processing your request
Database update error occurs: Settings were not Updated!

Settings successfully updated

^no update.

**Comment by JoakimFalk** [comment]
nm !
Connected to G captcha as it is default while not used..

**Comment by meangczac** [comment]
I also found that settings contains global locale files. I removed them this morning to respective infusions. So dejavu. I did this with the 8.

**Comment by JoakimFalk** [comment]
If it is not one thing, we can  be sure it is the other :)
