### ISSUE TITLE
Blog does not break with line break , all text is cluttered.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#456]
Saved as
![untitled-4](https://cloud.githubusercontent.com/assets/4210004/11116263/c7625778-8931-11e5-9ce0-c96a42a089e5.jpg)

Result
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11116264/c7641324-8931-11e5-8002-8dc9dfec91a8.jpg)

**Comment by JoakimFalk** [comment]
Does not work

**Comment by meangczac** [comment]
![is fixed for real](https://cloud.githubusercontent.com/assets/4078041/11160966/22672406-8aad-11e5-9a76-7999c671e17d.PNG)

**Comment by meangczac** [comment]
I don't think i need to do anything, it works fully on my system those line breaks.

Must have Automatic Line breaks checkbox checked. See SQL row to see if blog_breaks is Y

**Comment by JoakimFalk** [comment]
It was checked, in fact, I can not uncheck it ! but after toggling it, it started to work !

**Comment by meangczac** [comment]
Yes, there's its SQL oriented. I moved the function break calculation out in #462 fix as well. No worries.

I'm upgrading my OSX now to El Capitan. Gonna take a few hour off. Need the text-to-speech to assist me in locale translations before I can get translations in, together with the lang switch admin to work again.
