### ISSUE TITLE
Blog image thumbs to full size click stoped working

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#458]
This image thumb does not translate to full size when clicking. ( missing link )
![image-can-not-click](https://cloud.githubusercontent.com/assets/4210004/11142572/99f7cf6c-89ee-11e5-9fa0-67a02cdb87f3.jpg)

**Comment by meangczac** [comment]
thats no image thumb i think. in full blog view, it's full blog image. Because of the alignment to the left i think it cuts. Not sure, will check.

**Comment by JoakimFalk** [comment]
No. It used to be clickable, just as News images are for large size, since we can define the setting on size.

**Comment by hien-** [comment]
A question. What if someone doesn't want it?
