### ISSUE TITLE
blog settings for image is not existing

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#459]
In the settings it says Image link: News / Category
The code does not differ, it always link to the Blog item, I think this setting is abundant and can be removed for blog since we can have multiple cats here.

![blog-settings-error](https://cloud.githubusercontent.com/assets/4210004/11143126/1b686594-89f3-11e5-83b9-d092354427c5.jpg)

**Comment by meangczac** [comment]
Ah yes, can be removed.
