### ISSUE TITLE
Hardcoded info parts, what does it do?, remoable?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#460]
in blog/blog.php 

$user_contact = '';
            if (isset($item['user_skype']) && $item['user_skype']) {
                $user_contact .= "<strong>Skype:</strong> ".$item['user_skype'];
            }
            if (isset($item['user_aim']) && $item['user_aim']) {
                $user_contact .= "<strong>AIM:</strong> ".$item['user_aim'];
            }
            if (isset($item['user_yahoo']) && $item['user_yahoo']) {
                $user_contact .= "<strong>Yahoo:</strong> ".$item['user_yahoo']." , ";
            }
            if (isset($item['user_yahoo']) && $item['user_yahoo']) {
                $user_contact .= "<strong>YahooIM:</strong> ".$item['user_yahoo']." , ";
            }
            if (isset($item['user_yahoo']) && $item['user_yahoo']) {
                $user_contact .= "<strong>YahooIM:</strong> ".$item['user_yahoo']." , ";
            }
            if (isset($item['user_icq']) && $item['user_icq']) {
                $user_contact .= "<strong>ICQ:</strong> ".$item['user_icq'];
            }

**Comment by meangczac** [comment]
That is for User Fields to show how it can be integrated into Blog.

Your other issue has the screenshot of it. 

# About Admin

With all full information filled in user profile, it can show..

$locale['testimonial_rank'] = "I am the %s of this website";
$locale['testimonial_location'] = "and I currently live in %s";
$locale['testimonial_join'] = "I joined this website on %s";
$locale['testimonial_web'] = "I also run another website at %s";
$locale['testimonial_contact'] = "If you need to contact me, you can reach me at %s";
$locale['testimonial_email'] = "You can also reach me at my e-mail address at %s";

**Comment by JoakimFalk** [comment]
:+1:
