### ISSUE TITLE
center align of images is not working

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#462]
CSS does not seem to be loaded at all.

**Comment by meangczac** [comment]
i can do all.

![right](https://cloud.githubusercontent.com/assets/4078041/11160556/5514081c-8aa6-11e5-8561-0bf95e65e91e.PNG)

![left](https://cloud.githubusercontent.com/assets/4078041/11160557/55c601a2-8aa6-11e5-8595-58a94662f524.PNG)

![center](https://cloud.githubusercontent.com/assets/4078041/11160558/5768b914-8aa6-11e5-82a5-7677d7bbd516.PNG)

**Comment by meangczac** [comment]
Can it be your SEO

**Comment by JoakimFalk** [comment]
No SEO is not on, the images you display are two left aligned and one right aligned, where is the center aligned one? It does not work !
