### ISSUE TITLE
Alias 

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#481]
Fix alias to a working state

**Comment by meangczac** [comment]
I had alias working but it is very heavy when used dynamically.

```
fetch all 8 infusion drivers
while looping 8 infusions driver, load every rules
query db to fetch all alias from DB. (1 rule per query on each driver)
while looping x amount of forum alias, try preg_match each on buffered html (50 alias for forum name on db, preg_match 50 times)
if not found, go for next rule
if finish, go for next driver
```

8 x 1 x 50 = minimum 400 preg_match() run loop and parse - just for a forum name match.

This is not a good format. If I add those 60+ pattern on forum filter into alias, We'll do about 24,000 preg_match, single refresh -  just to drop a Forum ID.

Will check on further algorithm methods to get the ID outta our ways. For now, I am keeping this issue open.

**Comment by meangczac** [comment]
i'll close for now.

**Comment by JoakimFalk** [comment]
Ok. The most important part is the driver anyway :)
