### ISSUE TITLE
Adding members from Admin generate double mails and 1 is faulty

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#485]
As you can see SITENAME etc is not translated, but I also recived a secondary letter where it all is translated and correct.

![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11322716/38318a54-90f9-11e5-9a21-180f8a12aef4.jpg)

**Comment by meangczac** [comment]
This is where it should be if you add from Admin Panel. The codes look fine to me.

https://github.com/php-fusion/PHP-Fusion/blob/9.00/administration/members.php#L117-L122

$settings is declared in line 24 of the same file.

**Comment by JoakimFalk** [comment]
Idk why it is doing it, but there it is again two mails. One account created. One click, one faulty mail ( no translation ) one good mail. 

![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11424930/6781519e-9451-11e5-9228-72d5f92a28e5.jpg)

**Comment by meangczac** [comment]
Man.. things are really getting wierd. I cannot check bro, coz my machine doesn't run SMTP.

But I'll scan...  Please help as well to figure why.
