### ISSUE TITLE
SEO Engine Notices 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#491]
Rewrite/RewriteDriver.php Invalid argument supplied for foreach() Line: 445
Rewrite/RewriteDriver.php preg_match_all() [function.preg-match-all]: Delimiter must not be alphanumeric or backslash Line: 569
Rewrite/RewriteDriver.php array_combine() [function.array-combine]: Both parameters should have an equal number of elements Line: 443
Rewrite/RewriteDriver.php Invalid argument supplied for foreach()  Line: 740
Rewrite/RewriteDriver.php Undefined index: query Line: 473
Rewrite/RewriteDriver.php preg_match_all() [function.preg-match-all]: Delimiter must not be alphanumeric or backslash Line: 561
Rewrite/RewriteDriver.php array_combine() [function.array-combine]: Both parameters should have an equal number of elements Line: 738
Rewrite/RewriteDriver.php preg_match_all() [function.preg-match-all]: Delimiter must not be alphanumeric or backslash Line: 843

**Comment by meangczac** [comment]
I need the page and the driver to be able to debug this. If the regex fails, these notices are common.

Ok, I see some that will happen by default. I'll do supress statements
