### ISSUE TITLE
Notices in RewriteDriver, permalinks enabled

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#502]
This is on front with blog and news.
Rewrite/RewriteDriver.php array_combine() [function.array-combine]: Both parameters should have an equal number of elements Line: 736
Rewrite/RewriteDriver.php Invalid argument supplied for foreach() Line: 738

**Comment by meangczac** [comment]
This will only happen when wrong driver rules are used, now being supressed with $ so only 1 rule will pass at a time. If no rules passed, 404.
