### ISSUE TITLE
No modules installed, all rewrites enabled trying to logout render in notices and I am not logged out

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#504]
Rewrite/Router.php array_combine() [function.array-combine]: Both parameters should have an equal number of elements Line: 460
Rewrite/Router.php array_combine() [function.array-combine]: Both parameters should have an equal number of elements Line: 462
Rewrite/Router.php Invalid argument supplied for foreach() Line: 463
Rewrite/Router.php array_values() expects parameter 1 to be array, boolean given Line: 466
Rewrite/Router.php array_combine() expects parameter 1 to be array, null given Line: 467
Rewrite/RewriteDriver.php array_combine() [function.array-combine]: Both parameters should have an equal number of elements Line: 736
Rewrite/RewriteDriver.php Invalid argument supplied for foreach()  Line: 738

**Comment by meangczac** [comment]
Tried and cannot replicate. Can logout. If cannot logout, turn off SEO or install driver. 

Suppressing error notice.
