### ISSUE TITLE
Gallery renders the photo boxes a tad strange ( See gap )

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#507]
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11457755/561d6d9a-96b1-11e5-81fa-d82d1575bc1c.jpg)

**Comment by meangczac** [comment]
http://stackoverflow.com/questions/24590222/bootstrap-3-grid-with-different-height-in-each-item-is-it-solvable-using-only

All themes run different length of thumbnail per row. The default template issue it is.

```
$theme = fusion_get_settings("theme");
            switch ($theme) {
                case "Septenary":
                    $grid_offset = -10;
                    break;
                case "Bootstrap":
                    $grid_offset = 13;
                    break;
                case "debonair":
                    $grid_offset = 26;
                    break;
                default :
                    $grid_offset = 13;
            }
            foreach ($info['item'] as $data) {
```

As such, I won't cover. Taking out the long title name is the cleanest solution.
