### ISSUE TITLE
Custom page are dropping out when selecting a new language, even tho the page is enabled for the lang you select.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#509]
This is a tricky one. Before We only did a fallback when detecting & or ?. The individual page in it self would also at times do a fallback due to the multilingual check. But things have changed. We still need the custom pages to work pretty much as panels with no fallout just display or dont depending on enabled languages.

**Comment by meangczac** [comment]
Nothing wrong with non SEO. Adding SEO tag to check later. 

I am unable to get lang to translate. but it works with switch and doesn't drop out.
