### ISSUE TITLE
Articles,Blog,Downloads,FaQ,Gallery,News does not add a default title

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#516]
Web Links, Forum and Custom Pages ads the Title correctly upon entering it.

**Comment by meangczac** [comment]
I found Article not breaking lines, but I did not find Article not setting up title. 

Please confirm again. I will skip for now.

**Comment by JoakimFalk** [comment]
The report for all is on root level. infusions/articles/articles.php once you enter content it is there.
