### ISSUE TITLE
Admin > Settings > Theme Settings | No options can be toggled

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#519]
Enable Bootstrap Responsive Framework
Enable Entypo 
Enable Font-Awesome

**Comment by meangczac** [comment]
Add one more issue. Theme Settings page is missing in admin panel..

**Comment by JoakimFalk** [comment]
Actually, I think it poofs some times, But it is there for me. idk what removes it.. some glitch somewhere

**Comment by meangczac** [comment]
Man... defintiely poof in my PHPmyAdmin. But installer have it..

I'll manually add it

**Comment by JoakimFalk** [comment]
yeah, I know I reported once same thing, that it was missing.
You had it, I reinstalled. and yes there it was.
Now for my tests it have not poofed.

**Comment by meangczac** [comment]
Ok, done with it.
