### ISSUE TITLE
All tabs are broken in Administration

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#521]
includes/core_functions_include.php Use of undefined constant PHP_QUERY_RFC3986 - assumed 'PHP_QUERY_RFC3986'  Line: 492
includes/core_functions_include.php http_build_query() expects at most 3 parameters, 4 given  Line: 492
Rewrite/Permalinks.php preg_replace() [function.preg-replace]: Compilation failed: unmatched parentheses at offset 10378 Line: 75
Rewrite/Permalinks.php preg_replace() [function.preg-replace]: Compilation failed: unmatched parentheses at offset 10434 Line: 75

**Comment by meangczac** [comment]
it's fixed.
