### ISSUE TITLE
[SITENAME] not parsed on submit weblink

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#522]

**Comment by Der-WU** [comment]
[SITENAME] not parsed on Download submit too

**Comment by meangczac** [comment]
Well, thanks for pointing this out, maybe other locale have already used it, but English is not yet updated. I'll update that now.

**Comment by Der-WU** [comment]
Submit Weblink still show [SITENAME] :)
Download Submit done ^^
