### ISSUE TITLE
When enabling search permalink module the front display an empty white page

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#523]
As per above with a few notices thrown
Rewrite/Permalinks.php preg_replace() [function.preg-replace]: Compilation failed: range out of order in character class at offset 10564  Line: 75

**Comment by meangczac** [comment]
Compilation failed... whole fusion crashed. The \W is very dangerous material.. try restrict if possible. All trial and error. 

The driver is more stable than rules at this moment. Everytime I debug on rewrite engine, I find that incompatibilities almost caused by the rules or html.
