### ISSUE TITLE
Notices in site links when removing an item

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#529]
includes/theme_functions_include.php Undefined offset: 2 Line: 864
PHPFusion/SiteLinks.php Undefined index: 103 Line: 209

**Comment by meangczac** [comment]
No, this is something else. 103 is definitely a wrong offset. the correct offset is -103

I tried to add Super Admin item. It's -103 on link created. Something somewhere created that site links. Tested whole admin. Not Sitelinks.
