### ISSUE TITLE
Question: Can you already SEF URLs activate

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#539]
Hello Developers!

Some time ago you have begun to work on the SEO Engine for PF 9.0 and I wanted to know if you, the SEF URLs can now activate already ??

I would like to use it already, but if it is not finished yet, then accordingly not.

About feedback I'm happy. Thank you.

**Comment by JoakimFalk** [comment]
Hello, you should be able to use them now. Please keep to the forums for any general questions and not issues here !
