### ISSUE TITLE
verifying new account by email fails

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#543]
Parse error: syntax error, unexpected ':' in /home/nextphpf/public_html/RC7/register.php(40) : regexp code on line 1

Fatal error: preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Failed evaluating code: 's:'.strlen('user_id.':&quot;user_id&quot;;' in /home/nextphpf/public_html/RC7/register.php on line 40

**Comment by meangczac** [comment]
Another preg_replace need to be rewritten.
