### ISSUE TITLE
Member Polling

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#548]
When add poll option for 2 times consecutively, token error. This happens on all forms.

**Comment by meangczac** [comment]
Sigh. Intentionally left out this Infusion with just minor increments, but I can't fix without rewriting the whole application. 

I'll start now.

Update: Lucky, No need rewrite, program is ok. defender is causing probs.

**Comment by JoakimFalk** [comment]
There is something going on with token there for sure.
3 Options = no issues. 
4 Options = Token error but it still saves.
5 Options = Token error and no save.

See screen, 4 options saved even after error.
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11710935/391c0c5e-9f23-11e5-9477-0e6132e7db99.jpg)

**Comment by meangczac** [comment]
Fixed.

**Comment by hien-** [comment]
Member poll does not use $defender->safe() safety. It runs on normal dbquery(), thats why it still work.

**Comment by JoakimFalk** [comment]
Good work !
