### ISSUE TITLE
Administration of User Field Categories need some love to be clear

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#553]
Now when you add a tab it is pretty straight forward and works nice !
The problem comes when you want to install a module to your newly created tab.
You click on the tab you created and when you try to add a Module it is simply not possible.
You must first add another category like heading for the newly created tab before you can start populate it with content, this is quite confusing and I assume tons of people will not understand this double procedure when tinkering with it.

**Comment by meangczac** [comment]
Hmm. I tried but can do it. I remembered enabling it as well. 

Add 1 new root category - this create a new tab (page/section) - Name "Stats";
Add 1 more category - this is sub category of that page (container) - Name "User Statistics"
Add Module, select User Comments - add - select User Statistics - add

It's there. :+1:

**Comment by JoakimFalk** [comment]
Yes it is there, it is working. It is just hard to understand that you need to add two cats in order to add 1 or more items in a new tab section. 

It also switch back to tab one when working on 2 or 3 after saves etc... but it is polishing as I said it needs love.
