### ISSUE TITLE
Forum Infuse, the submenu for forum option are not displayed in subheader

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#556]
as per above, no errors. The option to display in both navigation and sub-header is ticked.

**Comment by meangczac** [comment]
I'm going to drop smart menus. Console.log shows that smartmenus has error, and the documentation , i cannot find why

**Comment by JoakimFalk** [comment]
Dropdown is still not happening, but it indicates that items are present.
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11739004/42e8317a-9fe8-11e5-8400-4e937812d295.jpg)

**Comment by JoakimFalk** [comment]
nm, CSS reload did the trick !
