### ISSUE TITLE
When selecting multiple languages in the custom pages the Add link to navigation menu does nothing

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#558]
No errors, it just does not create a link for any language.

![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11739058/bfa98f60-9fe8-11e5-964c-088e6e7273cb.jpg)

**Comment by meangczac** [comment]
Done this one. But I removed menu adjustments on edit custom page view.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/6ca67ef96ab04bcf643935c8b4bcd4dfd14338f4
