### ISSUE TITLE
accessing maintenance.php when logged in or when maintain mode is off should not be possible

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#565]
If people bookmark page or so and revisit it once it opens they will be stuck on this screen.

![untitled-7](https://cloud.githubusercontent.com/assets/4210004/11740856/950a1d76-9ff5-11e5-82fc-182aa87019cd.jpg)

**Comment by meangczac** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/11747023/fb03ce90-a05b-11e5-8ebb-ad12be24e0c2.PNG)

But mine is like this... ?

**Comment by JoakimFalk** [comment]
strange it never redirected me out of the site and sometimes I get loop. 
I guess does what I wanted, but crashes on SEO
if (!fusion_get_settings("maintenance")) {
    redirect("index.php");
}

**Comment by meangczac** [comment]
See my solution on header.php
