### ISSUE TITLE
Weblink it self does not work on next, when you click on a link, the page reloads.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#566]

**Comment by JoakimFalk** [comment]
not operational, the link is pasted upon current url.
Like : http://demos.php-fusion.co.uk/v7_Default/https://www.php-fusion.co.uk/downloads.php

**Comment by meangczac** [comment]
It certainly has something to do with A2's hosting routing condition, anyway, no matter how i tried to do the redirect, even hardcoded it, with: redirect(".../../../../../../../../../../".$location); it's still going back to /site-path/http://www.

I fixed anyway.
