### ISSUE TITLE
Site redirects badly when entering site thru a permalink with maintain mode on

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#567]
For example /articles/category/1/test-article-cat > articles/category/1/maintenance.php
then it naturally says error ;)

**Comment by meangczac** [comment]
#0 redirect(maintenance.php) called at [C:\MAMP\htdocs\php-fusion\themes\templates\header.php:26] #1 require_once(C:\MAMP\htdocs\php-fusion\themes\templates\header.php) called at [C:\MAMP\htdocs\php-fusion\home.php:21] 
#2 require_once(C:\MAMP\htdocs\php-fusion\home.php) called at [C:\MAMP\htdocs\php-fusion\index.php:45] 

#0 redirect(maintenance.php) called at [C:\MAMP\htdocs\php-fusion\themes\templates\header.php:26] #1 require_once(C:\MAMP\htdocs\php-fusion\themes\templates\header.php) called at [C:\MAMP\htdocs\php-fusion\home.php:21] 
#2 require_once(C:\MAMP\htdocs\php-fusion\home.php) called at [C:\MAMP\htdocs\php-fusion\index.php:45] redirected to maintenance.php

**Comment by meangczac** [comment]
I don't know how this works, but it just did -- what the heck.

**Comment by LipkeGu** [comment]
this doesnt work =(

We are using this Fix: https://github.com/TheWalkingRadio/PHP-Fusion/commit/60e21bd9645be024f1e82a75ec5b9ebae1ce7115

**Comment by meangczac** [comment]
Is the above fix working?
