### ISSUE TITLE
create new thread makes no differance on language specific forums

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#570]
Below is English forum listed on Dannish instance
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11744253/18656234-a00f-11e5-9fc2-9690ccb1449d.jpg)

**Comment by meangczac** [comment]
You mean Test Forum 1 is English but appear in Danish?  OK, i'll modify the forum selector.

`Start New Thread` is - Danish Locale or English..
