### ISSUE TITLE
Upgrade does not work with two tested methods. It need to work with at least one of the following

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#576]
1, Copy the upgrade script to the v7 administration folder and enter the admin, hit upgrade. Remove all files but config. Copy new 9 files, access site when done.
Since the upgrade script now have depencies from 9 you can´t do this as option 1.

2, Delete all files except config in old 7  and copy 9 over and run an upgrade from there.
Two is much more complicated , I vote to get 1 working.

I vote for getting rid of dependencies in upgrade.php and option 1 works. It is what people are used to when it comes to Fusion upgrades.

**Comment by meangczac** [comment]
I let you handle.

**Comment by JoakimFalk** [comment]
Amost done, will be one more day on it for sure, spent my weekend to fix this asap. 
It is quite tricky at parts, not to mention that it takes time, upgrade > test > reset - repeat.

**Comment by JoakimFalk** [comment]
After a week or so adjusting, testing and testing and adjusting and even more testing... repeat..
I am happy to say that the scripts work close to perfect now. User fields and Photogallery are two things that remains to decide on but overall, this ticket is solved.
