### ISSUE TITLE
Security > Allow PHP Execution stoped working for panels

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#581]
I noticed it when upgrading since I have this custom panel made for it.
Toggling the switch and it still does not translate echo and opentables
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11763538/77f5ed9e-a10f-11e5-883e-bca0b4c95604.jpg)

**Comment by Domi-php** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/17344daf052c3782e50d32b8d20da89e3562edd0
