### ISSUE TITLE
Photogallery structure for upgrade need an overhaul

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#585]
The gallery code still won´t work for a smooth upgrade.
This is because old structure assumed that all photos are in albums.
Any actual paths was not stored in the database.
With current mirgration tool we only moved content from images/photogallery to infusions/gallery/photos while the listing of albums remains the same.
People have their albums in album_x and so forth.

**Comment by meangczac** [comment]
Copy the photo into a new folder. Delete the old photo. No need to worry execution time. That's server side issue (them vs hosting company)

```

/** 
 * @param $album_id
 * PLEASE ADJUST THE PATH
 */

function move_photos($album_id) {
    $result = dbquery("SELECT * FROM ".DB_PHOTOS." WHERE album_id='".$album_id."'");
    if (dbrows($result)>0) {
        while ($photo_data = dbarray($result)) {

            // move photos from xxx to xxx please verify and change path
            $photo_from = "where/is/the/v7one/album_".$album_id."/".$photo_data['photo_filename'];
            $photo_t_from = "where/is/the/v7one/album_".$album_id."/".$photo_data['photo_thumb'];
            $photo_t2_from = "where/is/the/v7one/album_".$album_id."/".$photo_data['photo_thumb1'];

            $photo_to = IMAGES_G;
            $photo_t_to = IMAGES_G_T;
            $photo_t2_to = IMAGES_G;

            if (file_exists($photo_from)) {
                copy($photo_from, $photo_to);
                unlink($photo_from);
            }

            if (file_exists($photo_t_from)) {
                copy($photo_t_from, $photo_t_to);
                unlink($photo_t_from);
            }

            if (file_exists($photo_t2_from)) {
                copy($photo_t2_from, $photo_t2_to);
                unlink($photo_t_from);
            }

        }
    }
}
```

**Comment by JoakimFalk** [comment]
Thank you, that is great, will start testing on it.

**Comment by JoakimFalk** [comment]
I took another approach to it but kept your function base, just because it looks good ;)  
The procedure seems ok now, I am about to test it in sharp mode upgrade.
My approach : https://github.com/php-fusion/PHP-Fusion/commit/e6f0cba80d8482172e3cf4189826fcf37ebbdde9
