### ISSUE TITLE
User fields for an upgrade or not

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#586]
V7´s current structure plainly upgraded will put all "sections" as new main tabs with 0 content.
The old fields naturally don´t have languages or anything as that set so they simply poof in the interface while they are installed.
To push the old current user fields in to these new uf categories will require quite some scripting not to mention new injected place holders below the main cats for descriptions.

**Comment by meangczac** [comment]
I'm not sure if you're doing it directly in version 7 or 9, but anyway, this is how I would approach it, just for your reference ( complete user fields category upgrade ):

https://gist.github.com/hien-/01af639796e6bc6953b9

**Comment by JoakimFalk** [comment]
Thank you, I will tinker with it some.  Currenty I just drop em and inject new from installer default.

**Comment by JoakimFalk** [comment]
I am going nowhere with it, issue is the format on languages {Eng} and so forth. I am just not going to care about them fields for now.
