### ISSUE TITLE
Submenu site links first item is not clickable

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#591]
The forum droplist it works OK,  but the first item is not clickable ( it has an url and should be ) Naturally it can´t work like that now since a click is required to enable the drop list.
The same menu in the navigation panel however does work perfectly fine with hover functions and the first item is clickable. Currenty the top menu lacks a direct link to the forums index since the functions have changed with no alternative reference.

**Comment by meangczac** [comment]
Man. true......
