### ISSUE TITLE
locales

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#593]
There's no default locale for news and some other infusions and in the themes

**Comment by JoakimFalk** [comment]
It should be localized, News and some other Infusions still rely much on the Core locale as it was heavily integrated there. 
We will do a Locale cleanup for later versions.

**Comment by meangczac** [comment]
```
if (file_exists(INFUSIONS."blog/locale/".LOCALESET."blog.php")) {
    include INFUSIONS."blog/locale/".LOCALESET."blog.php";
} else {
    include INFUSIONS."blog/locale/English/blog.php";
}
```

Hi, why no? These were personally checked and standarized by Domi.

**Comment by Webmeteor** [comment]
I've renamed a locale Folder only in locales but not in the infusion it selfs. There comes an error file Not found. include(infusions/blog/locale/German/blog.php): failed to open stream: No such file or directory

**Comment by Domi-php** [comment]
Your folder structure is off. It does not look for the locale in locale/German/XX, it looks for locale in locale/German.php

**Comment by JoakimFalk** [comment]
I know that the function is rock solid, something else is going on there. 
It check for files, if the files is not there it should fallback to English , naturally if English and the Current non English locale is missing you will get an error.
