### ISSUE TITLE
Error in /home.php (Line: 294)

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#600]
Hi,
[/home.php](https://github.com/php-fusion/PHP-Fusion/blob/9.00/themes/debonair/theme.php#L294) will throw an error if debonair theme is selected.

``` PHP
if ($theme_settings['lbanner_col_4'] !=="") {
   include "include/".$theme_settings['lbanner_col_4'];
} 
```

**Error:**
include(): Failed opening 'include/' for inclusion (include_path='.:')

**Solution:**
Maybe (I'm not sure) use [empty()](http://www.php.net/empty) and [isset()](http://www.php.net/isset) or [file_exists()](http://www.php.net/file_exists). I'm not sure whether this is secure or not.

``` PHP
if (isset($theme_settings['lbanner_col_4']) && !empty($theme_settings['lbanner_col_4'])) {
   include "include/".$theme_settings['lbanner_col_4'];
} 
```

Best,
SuN

**Comment by JoakimFalk** [comment]
Thank you, 
Actually Debonair was not tested well on later months, I had no plan to include it but there it is :)
