### ISSUE TITLE
TinyMCE for Articles

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#601]
It does not seem to activate.

For security issues I don´t think we activate Tiny for submissions, but maybe it have changed?

By knap
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37060

**Comment by meangczac** [comment]
No, TinyMCE was not enabled in Submissions side. Since this issue is made, I'll increment on the patch now. It's pretty simple now with the latest api.
