### ISSUE TITLE
/search.php runs crazy with download infusion installed

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#604]
Hi,
I installed the official downloads infusion delivered within the install pakage. If I call /search.php I will get a lot of errors. Here are some of them:

Line 189: Undefined index: Downloads

``` PHP
echo form_select('chars', '', $_POST['sort'], array('options' => $sort_opts, 'disabled' => ($_GET['stype'] != "all" ? (in_array("chars", $form_elements[$_GET['stype']]['disabled']) ? "1" : "0") : "0"))); 
```

Line 180: in_array() expects parameter 2 to be array, null given

``` PHP
echo "<label><input type='radio' id='order2' name='order' value='1'".($_POST['order'] == 1 ? " checked='checked'" : "").($_GET['stype'] != "all"
    ? (in_array("order2", $form_elements[$_GET['stype']]['disabled']) ? " disabled='disabled'" : "") : "")." /> ".$locale['451']."</label><br
    /></td>\n";
```

**Comment by meangczac** [comment]
I tested the search without problem

**Comment by JoakimFalk** [comment]
More info is needed, I have tested without issues as well.
Please download latest Git and try again, also show what characters are used, might be related.
