### ISSUE TITLE
Have PDO selected default if detected and maybe have a link from a (?) to what it is

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#606]
Have PDO selected default if detected ( Me ) .
Have a link from a (?) to what it is // Richard

**Comment by meangczac** [comment]
Unless we invented PDO, then we have responsibility to explain. It's all over the net to search for answer. At most, have it described in online doc later.

If I add English locale in now, I need to get 27 other guys to translate in other lang. Can't get it done smoothly in a short RC phase out cycle patch.
