### ISSUE TITLE
Class Autoloader - Instability warning - How do we prevent it?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#613]
The breakdown is, we can´t accept something that important to not be 100% rock solid, it should never fail as it is a simple include in the base.
If it breaks on every 10th server it need to be fixed 
If it breaks on every 100th server it need to be fixed
If it breaks on every 1000th server it need to be fixed
My point, something that does an inclusion that the system are depending on should never be allowed to break.
If it can´t be fixed to never break, it need to be removed and replaced with manual includes to avoid the occasional headache for us and our users.

**Comment by meangczac** [comment]
I'm trying to fix, but to fix his server. Because that guy could not basically load ..

**DIR** (i.e C:/path/to/folder/htdocs/public_html/)  + "Autoloader.php ". Wrong virtual host apache settings is very imminent here. 

Autoloader is a PHP function, if it breaks, reinstall PHP is the only way.

**Comment by JoakimFalk** [comment]
Depending on amount of issues I can leave it be. But if it is a re-occuring issue we need to re-think it.

With that I mean, remove it as a whole and go with manual inclusion where it is needed, it is probably more optimized as well.
