### ISSUE TITLE
Newly registred users get invalid date ( 1970 )

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#620]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37096&pid=196957#post_196957

**Comment by meangczac** [comment]
Activation or no?

**Comment by meangczac** [comment]
Debug report:
Normal user registered, no problem.
Email activation registration - untested (Need Domi test on RC7)
Admin activation registration - untested
Admin add registration - no problem

**Comment by JoakimFalk** [comment]
Confirmed : Email Activated registration gives the issue "Date JoinedJanuary 01 1970 01:00:00"

**Comment by JoakimFalk** [comment]
"an activation email when registering does not save the user_joined, user_theme, user_timezone column (default value), the other option is saved."

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37097&pid=196961#post_196961
