### ISSUE TITLE
register.php need to be updated for PHP 5.5+

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#621]
register.php - preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead Line: 43

"What about the register.php and unserializeFix function? That one is not fixed even in Fusion 9 RC."

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=36803&pid=196970#post_196970

**Comment by meangczac** [comment]
I plan to wipe the code.
