### ISSUE TITLE
Lot´s of issues from html inspector ( this is news ) , some are wrong others might be right

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#622]
Is the HTML inspector not just more trouble than useful with such faulty reports as for the OG tags.

See discussion here : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37099&pid=196984#post_196984

<pre><code>
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​title" content=​"PHP-Fusion Powered Website">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​description" name=​"description" content>​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​url" content=​"http:​/​/​next.php-fusion.co.uk/​RC7/​">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​keywords" content>​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​image" content=​"images/​php-fusion-logo.png">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​title" content=​"Trying to see warnings">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​description" content=​"Trying to see warnings">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​site_name" content=​"PHP-Fusion Powered Website">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​type" content=​"article">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​url" content=​"http:​/​/​next.php-fusion.co.uk/​RC7/​infusions/​news.php?readmore=1">​
html-inspector.js:664 'property' is not a valid attribute of the <meta> element. <meta property=​"og:​image" content=​"http:​/​/​next.php-fusion.co.uk/​RC7/​infusions/​news/​images/​php-fusion_1.jpg">​
html-inspector.js:664 The <b> element cannot be a child of the <ul> element. <b>​2015​</b>​
html-inspector.js:664 The <br> element cannot be a child of the <ul> element. <br>​
html-inspector.js:664 The 'name' attribute is no longer valid on the <a> element and should not be used. <a id=​"edit_comment" name=​"edit_comment">​</a>​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​smiley.png" class=​"bbcode" onclick=​"return overlay(this, 'bbcode_smileys_list_comment_message', 'bottomleft')​;​" title=​"Smileys">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <div id=​"bbcode_smileys_list_comment_message" class=​"tbl1 bbcode-popup" style=​"display:​none;​border:​1px solid black;​position:​absolute;​overflow:​auto;​width:​400px;​height:​auto;​" onclick=​"overlayclose('bbcode_smileys_list_comment_message')​;​">​…​</div>​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​smile.gif" alt=​"Smile" onclick=​"insertText('comment_message', ':​)​', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​wink.gif" alt=​"Wink" onclick=​"insertText('comment_message', ';​)​', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​sad.gif" alt=​"Sad" onclick=​"insertText('comment_message', ':​(', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​frown.gif" alt=​"Frown" onclick=​"insertText('comment_message', ':​|', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​shock.gif" alt=​"Shock" onclick=​"insertText('comment_message', ':​o', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​pfft.gif" alt=​"Pfft" onclick=​"insertText('comment_message', ':​P', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​cool.gif" alt=​"Cool" onclick=​"insertText('comment_message', 'B)​', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​grin.gif" alt=​"Grin" onclick=​"insertText('comment_message', ':​D', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <img src=​"../​../​images/​smiley/​angry.gif" alt=​"Angry" onclick=​"insertText('comment_message', ':​@', 'inputform')​;​">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​b.png" class=​"bbcode" onclick=​"addText('comment_message','[b]​','[/​b]​','inputform')​;​return false;​" title=​"Displays selected text as bold">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​i.png" class=​"bbcode" onclick=​"addText('comment_message','[i]​','[/​i]​','inputform')​;​return false;​" title=​"Makes selected text italic">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​u.png" class=​"bbcode" onclick=​"addText('comment_message','[u]​','[/​u]​','inputform')​;​return false;​" title=​"Makes selected text underlined">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​url.png" class=​"bbcode" onclick=​"addText('comment_message','[url]​','[/​url]​','inputform')​;​return false;​" title=​"Makes a URL clickable">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​mail.png" class=​"bbcode" onclick=​"addText('comment_message','[mail]​','[/​mail]​','inputform')​;​return false;​" title=​"Makes email adress clickable">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​img.png" class=​"bbcode" onclick=​"addText('comment_message','[img]​','[/​img]​','inputform')​;​return false;​" title=​"Displays image from given URL address">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​center.png" class=​"bbcode" onclick=​"addText('comment_message','[center]​','[/​center]​','inputform')​;​return false;​" title=​"Aligns selected text to center">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​small.png" class=​"bbcode" onclick=​"addText('comment_message','[small]​','[/​small]​','inputform')​;​return false;​" title=​"Displays selected text as small">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​code.png" class=​"bbcode" onclick=​"addText('comment_message','[code]​','[/​code]​','inputform')​;​return false;​" title=​"Displays text as code">​
html-inspector.js:664 An 'onclick' attribute was found in the HTML. Use external scripts for event binding instead. <input type=​"image" src=​"../​../​includes/​bbcodes/​images/​quote.png" class=​"bbcode" onclick=​"addText('comment_message','[quote]​','[/​quote]​','inputform')​;​return false;​" title=​"Quoting selected text">​
html-inspector.js:664 The 'cols' attribute is required for <textarea> elements. <textarea name=​"comment_message" style=​"width:​ 100%;​ height:​ 80px;​ overflow:​ hidden;​ word-wrap:​ break-word;​ resize:​ horizontal;​" class=​"form-control p-15 m-0  animated-height no-shadow no-border textbox " placeholder id=​"comment_message">​</textarea>​
html-inspector.js:664 The 'rows' attribute is required for <textarea> elements. <textarea name=​"comment_message" style=​"width:​ 100%;​ height:​ 80px;​ overflow:​ hidden;​ word-wrap:​ break-word;​ resize:​ horizontal;​" class=​"form-control p-15 m-0  animated-height no-shadow no-border textbox " placeholder id=​"comment_message">​</textarea>​
html-inspector.js:664 The 'name' attribute is no longer valid on the <a> element and should not be used. <a id=​"comments" name=​"comments">​</a>​
html-inspector.js:664 <script> elements should appear right before the closing </body> tag for optimal performance. <script type=​"text/​javascript" src=​"../​../​includes/​jquery/​jquery.js">​</script>​
html-inspector.js:664 <script> elements should appear right before the closing </body> tag for optimal performance. <script type=​"text/​javascript" src=​"../​../​includes/​jscript.js">​</script>​
html-inspector.js:664 <script> elements should appear right before the closing </body> tag for optimal performance. <script type=​"text/​javascript" src=​"../​../​includes/​jquery/​jquery.cookie.js">​</script>​
html-inspector.js:664 <script> elements should appear right before the closing </body> tag for optimal performance. <script type=​"text/​javascript" src=​"../​../​includes/​jquery/​colorbox/​jquery.colorbox.js">​</script>​
</code></pre>

**Comment by meangczac** [comment]
Bring it up to this guy.. https://github.com/philipwalton/html-inspector

Dan put it there, I want to take it down long time ago against the basic errors like <img> must have alt tag, but <span> or <div> must have class error in the HTML inspector is totally bull..  

Still, I left it there due to appreciation of his good will of trying to allow assist. But nobody gets 0 error.

php-fusion.co.uk itself - 98 error found 
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.php-fusion.co.uk%2Fhome.php

facebook.com front page - 66 errors
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.facebook.com

wordpress.org - 72 errors
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwordpress.org%2Fplugins%2Fcontact-form-7%2F

Nobody claimed that any of our theme is 100% W3C valid, and thats why we never put this logo:
![valid-xhtml10](https://cloud.githubusercontent.com/assets/4078041/12017637/77cde86c-ad94-11e5-8339-3f1455bc4e69.png)

I close issue with these stat. And disable the html inspector. 

I don't want div/table issue all over, and col/rows deprecation arguments too. HTML subject is too wide.

For one, the console error is never empty. The reason is each major browser is trying to compete to its own (Safari/Chrome/Firefox) has their own standard and taste, and is still with development patching like madmen every week. I'm not going to jump in and say, hey i'm 100% chrome fit... because next week, they change again.
