### ISSUE TITLE
When Terms of Agreement is used in registration the field breaks right side panels

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#630]
Took me a while to find the issue, but I had broken panels there on a users site.

![untitled-2](https://cloud.githubusercontent.com/assets/4210004/12053035/3dfe1ea4-af15-11e5-9d42-68b0e6de422e.jpg)

**Comment by meangczac** [comment]
Ok, Debonair theme on a register page. On it.
