### ISSUE TITLE
Move posts fails

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#635]
Driver/PDOMySQL.php
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE forum_id = '3'' at line 1
Line: 106

**Comment by meangczac** [comment]
I cannot replicate.

**Comment by JoakimFalk** [comment]
Really wierd, just tested again. No issue but it was confirmed by my self at some point. We leave it closed for now then.
