### ISSUE TITLE
Wanabo's Forum Post Issues with MariaDB - Pending 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#636]
Maybe you can make something out of it, I tried @ next with latest git, I had no issues.
Source : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37119&pid=197072#post_197071

Setup :
Nginx-Apache 
MariaDB 
Php 5.6.8

**Comment by meangczac** [comment]
I think he upload wrong file wrong place? Not sure. But I can't get a single line of error my side, and those reported error lines... it's not in the files reported. So i'm puzzled now.

**Comment by JoakimFalk** [comment]
You have a PM with server data.

**Comment by Domi-php** [comment]
There they are @ next for the firsttime. Yet to be replicated back tho, Trying all kinds of variations.

templates/forum_main.php Undefined index: item Line: 199
templates/forum_main.php Undefined index: permissions Line: 269
templates/forum_main.php Undefined index: permissions Line: 270
templates/forum_main.php Undefined index: permissions Line: 271
templates/forum_main.php Undefined index: permissions Line: 272
templates/forum_main.php Undefined index: permissions Line: 273

**Comment by meangczac** [comment]
I've contacted Wanabo for him to contact me in Skype. Once he gets online, we'll solve this issue.
The whole problem is in MariaDB I think or it's gonna be SEO driver. Either way, I cannot replicate the whole issue in my system whether SEO on or off. 

Wanabo server running non compliant SQL - It can be adapted, but this repository technically speaking is not dependant on MariaDB. 

I'll support Wanabo on his server personally on unofficial capacity and even mod if needed. However, the codes that will change <b>might not</b> be reflected on this repository. 

MT can close this case anytime, or wait until Wanabo's server gets fixed.

**Comment by JoakimFalk** [comment]
Ok, anything related to this that would need to get updated as a result of your investigation will be done anyway, closing for now !
