### ISSUE TITLE
A few notices in forum triggered by guests

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#637]
templates/forum_main.php Undefined index: permissions Line: 272
templates/forum_main.php Undefined index: permissions Line: 273
templates/forum_main.php Undefined index: permissions Line: 271
templates/forum_main.php Undefined index: permissions Line: 270
templates/forum_main.php Undefined index: permissions Line: 269
templates/forum_main.php Undefined index: item Line: 199

**Comment by meangczac** [comment]
I don't know why it triggered. 

Viewthread, if !empty thread_data , then parse permission 

https://github.com/php-fusion/PHP-Fusion/blob/9.01/infusions/forum/classes/Viewthread.php#L64

Likewise, Viewforum, if !empty forum_data, then parse permission

Redirect not redirecting properly and then viewed template without any data would be possible causing this. Since we have many guest not redirecting issue. But them fixed already. 

Please see if you still have this error.

**Comment by JoakimFalk** [comment]
Closed the duplicate thread, had the errors in the log this morning again. No idea what triggers it still. 
Maybe we can add a tracker to the error log - $_SERVER['HTTP_REFERER'] ? that would help in many cases.

**Comment by meangczac** [comment]
I'll look into it. This does not happen on fresh installation

**Comment by JoakimFalk** [comment]
Yes it does, something triggers it on next,

**Comment by JoakimFalk** [comment]
Here it is, 

templates/forum_main.php /RC7//RC7/forum/2/0/type-all/sort-view/time-today/filters Undefined index: permissions Line: 272
templates/forum_main.php /RC7//RC7/forum/2/0/type-all/sort-view/time-today/filters Undefined index: permissions Line: 273
templates/forum_main.php /RC7//RC7/forum/2/0/type-all/sort-view/time-today/filters Undefined index: permissions Line: 274
templates/forum_main.php /RC7//RC7/forum/2/0/type-all/sort-view/time-today/filters Undefined index: permissions Line: 271
templates/forum_main.php /RC7//RC7/forum/2/0/type-all/sort-view/time-today/filters Undefined index: permissions Line: 270
templates/forum_main.php /RC7//RC7/forum/2/0/type-all/sort-view/time-today/filters Undefined index: item Line: 200

**Comment by meangczac** [comment]
Why your path is RC7//RC7 - is that correct?

**Comment by JoakimFalk** [comment]
No, it is the engine doing it for some reason.

**Comment by JoakimFalk** [comment]
Thats why I did this, https://github.com/php-fusion/PHP-Fusion/commit/46eaced957ed0aa23b6adce668a6d4f1ab5ec206
Only area I know is affected by it ..:/
