### ISSUE TITLE
Error Console redirects badly in a SEO Area (Forum tested)

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#638]
When you clear the log it adds sub dir twice with SEO on.
Like >  /RC7//RC7/forum/browse/2/0/Main-Forum

**Comment by meangczac** [comment]
Test and see if it works

**Comment by JoakimFalk** [comment]
Same problem.
It adds subdir twice , /RC7//RC7/forum/thread/view/10/My-mind-is-on-sub-forums

**Comment by JoakimFalk** [comment]
Fixed : https://github.com/php-fusion/PHP-Fusion/commit/7456eb46981fa6a350cdb4a7956351e421f2958e
