### ISSUE TITLE
When clicking track thread as guest in SEO mode you get a redirect loop

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#640]
/forum/thread/on/3/4/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/infusions/forum/index.php

**Comment by meangczac** [comment]
Yep, and Idk why redirecting to index.php results in infinity, I just make a quick  separate redirect now it works.

**Comment by JoakimFalk** [comment]
This one works now
