### ISSUE TITLE
Entering my threads, my posts,new posts  as Guest in SEO Mode causes a redirect back too server root (Forum Threads List)

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#641]
It is supose to stay @ rc7/ but goes way passed it.
The Tracked threads redirect properly in that group chain.

**Comment by meangczac** [comment]
It's ok for me now.

**Comment by JoakimFalk** [comment]
Does not take subdirs in to account, hitting domain root so on next it fails.
