### ISSUE TITLE
These notices come back @ next frequently, I simply have not found find what is triggering it yet

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#645]
templates/forum_main.php Line: 273
templates/forum_main.phpUndefined index: permissions Line: 272
templates/forum_main.php Undefined index: permissions Line: 271
templates/forum_main.php Undefined index: permissions Line: 270
templates/forum_main.php Undefined index: item Line: 199
templates/forum_main.php Undefined index: permissions Line: 269

**Comment by meangczac** [comment]
Tried to track it, but can't replicate.

**Comment by JoakimFalk** [comment]
Not me either, I had it reported already..:/

**Comment by meangczac** [comment]
Check on this now.

**Comment by meangczac** [comment]
Check completed.

SEO ON

Admin - View forum, post reply, used quick reply, new thread, use all filters on forum with threads, used all filters on forum with no threads. --- No error.

Guest - View forum, post reply, used quick reply, new thread, use all filters on forum with threads, used all filters on forum with no threads. --- No error.

Member - View forum, post reply, used quick reply, new thread, use all filters on forum with threads, used all filters on forum with no threads. --- No error.

SEO OFF. Repeat all steps above. --- No Error.
