### ISSUE TITLE
Something is off with custom user fields display

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#646]
The field is there in edit profile, I can enter values and they are saved.
![untitled-4](https://cloud.githubusercontent.com/assets/4210004/12074936/7cffaeb8-b16f-11e5-959b-fd35ca71b8b2.jpg)

However, here on the profile display the field poofed, it was visual before I enabled user web. 
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/12074935/7cfd21de-b16f-11e5-8a5b-c3b0e98f1dfc.jpg)

No notices at all are thrown

**Comment by meangczac** [comment]
I'll recheck codes. I'm sure it worked at one point.

**Comment by meangczac** [comment]
:musical_score:  Don't believe me just watch.. :musical_note:  Don't believe me just watch... :musical_note:  coz uptown funk gonna give it ya.. Don't believe me just watch... :+1:  Nailed woohoo.

**Comment by JoakimFalk** [comment]
Confirmed, works ! :)
