### ISSUE TITLE
user website in forum is broken without http

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#647]
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/12074965/7ad6b356-b170-11e5-88ce-b1a0af561e23.jpg)

Becomes 

![untitled-5](https://cloud.githubusercontent.com/assets/4210004/12074971/bfe57806-b170-11e5-8803-25f912cb65c2.jpg)

**Comment by JoakimFalk** [comment]
I added a check to http on or not, made no diff but solved the noindex option issue anyway https://github.com/php-fusion/PHP-Fusion/issues/648

**Comment by meangczac** [comment]
Ok, I tried to edit my profile - when i type in www.venue.nu, it saved as http://www.venue.nu. Defender is automating as intended.

Now, I'll check the user website with SEO on.

**Comment by meangczac** [comment]
Ok, yes, there is an error in string
