### ISSUE TITLE
Admin Activated Registration are not operational

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#658]
Members registering will be able to login before Admins had a chance to approve these.
Two things need to happend when this option is on.
1, The member will register as usual, once completed a notice saying that they need to wait for an admin to activate the account.
2. The Admin need to know that a user have registred and need to be activated.
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37166&pid=197205#post_197193

**Comment by meangczac** [comment]
On Registration with Admin approval settings on, user_status is 2. User unable to login at this point. 

Registration steps execution is correct.

**Comment by meangczac** [comment]
Then, Admin goes to Admin->Unactivated selector. User needs activation will be listed. Then Admin activate and user can login.

Affirmed. No issue.
