### ISSUE TITLE
Dropdowns (select2 plugin)

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#663]
Hi,

in general I like the idea of using the select2 plugin for drop down selections with that search bar but... in my opinion this is not necessary for a drop down with less then 10 options. Maybe that could be improved.

This plugin does that better I think: http://harvesthq.github.io/chosen/

Maybe the select2 plugin also provides an option when to show the search bar and when not.

Best,
SuN

**Comment by JoakimFalk** [comment]
Hi, Nice plugin there, but please use our Official forums for suggestions or support. 
https://www.php-fusion.co.uk/forum/index.php
