### ISSUE TITLE
[Question] Permalinks

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#664]
Hi,
can someone explain how permalink works?

Specially how links will be translated. If I create an infusion how can I integrate the permalink feature?

I know I have to write a FOOBAR_rewrite_include.php file and put it into includes/rewrites/ (what is not optimal if I develop a infusion) and then I have to activate the rules via admin interface (or insert some rows in database). Is that all to do?

Is there a regex that replaces all "path/file.php" links to "path/file" before the page will be send to the client?

Thanks for your help.

Best,
SuN

**Comment by JoakimFalk** [comment]
Hi, Nice plugin there, but please use our Official forums for suggestions or support. 
https://www.php-fusion.co.uk/forum/index.php

**Comment by meangczac** [comment]
Kinda of easy, see the driver includes/rewrites/ for the infusions. Copy and play around it :+1:
