### ISSUE TITLE
FUSION_SELF = home

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#665]
Hi,
the const FUSION_SELF is crazy if permalink is enabled.

**To reproduce:**
• Go to Admin Interface and enable permalink feature and activate all available permalinks.
• Open /themes/Septenary/theme.php and add

``` PHP
var_dump(FUSION_SELF);
```

after

``` PHP
    // Header - something fancy for login page.
    if (FUSION_SELF !== 'login.php') {
        require_once THEME."includes/content.php";
    }
```

• Go to /message => FUSION_SELF == "/home"
• Go to /edit-profile => FUSION_SELF == "/home"
• Go to /message/inbox => FUSION_SELF == "home"

Best,
SuN

**Comment by meangczac** [comment]
Check your .htaccess file basedir

```
    RewriteEngine On
    RewriteBase /php-fusion/
```

FUSION_SELF doesn't work when permalink because it's always index.php

due to this rule

```
RewriteRule ^(.*?)$ index.php [L]
```

Change code to 

```
if (FUSION_SELF !== "login.php" || PERMALINK_CURRENT_PATH == "login") {

}
```

**Comment by meangczac** [comment]
I found a problem in the permalink append path which only matches single quoted html anchor or source syntax. I included a double quote as well. See if it does any good.
