### ISSUE TITLE
form_text() => type number

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#667]
Hi,
I found that piece of code:

``` PHP
    // This should affect all number inputs by type, not by ID
    if ($options['type'] == 'number' && !defined('NUMBERS_ONLY_JS')) {
        define('NUMBERS_ONLY_JS', TRUE);
        add_to_jquery("$('input[data-type=number]').keypress(function(e) {
        var key_codes = [46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 0, 8];
        if (!($.inArray(e.which, key_codes) >= 0)) { e.preventDefault(); }
        });\n");
    }
```

That should be extended for Numpad numbers I think.

```
numpad 0    96
numpad 1    97
numpad 2    98
numpad 3    99
numpad 4    100
numpad 5    101
numpad 6    102
numpad 7    103 
```

And as mentioned here: http://api.jquery.com/attribute-equals-selector/

``` js
$('input[data-type=number]')
```

should be:

``` js
$('input[data-type="number"]')
```

I mean to remember it is a security risk but I'm not sure. Sorry :(

Best,
SuN

**Comment by meangczac** [comment]
Not relevant to security. It's an i/o only. Security is when issues are related to your database. while these are only related to functionality - accessibility, helpers, convenience, etc.

But yes, i'll increment as per your suggestion.
