### ISSUE TITLE
mod_rewrite with PHP 5.5.9 and FastCGI?

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#668]
Hi,

I'm running PHP 5.5.9 with FastCGI. If I want to enable the permalink feature I get a warning that my server does not support mod_rewrite. This is wrong... I found out that "apache_get_modules()" does not work with FastCGI.

https://discussion.dreamhost.com/thread-129205.html

Best,
SuN

**Comment by JoakimFalk** [comment]
Try this one, https://github.com/php-fusion/PHP-Fusion/commit/385e4d9094f1da7e2cfb5c5f8453b4937fa13d9b
in worse case you might need to add this to .htaccess, 
 SetEnv HTTP_MOD_REWRITE On
