### ISSUE TITLE
/home after disable permalink

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#671]
Hi,
I disabled the permalink feature and now all links to /home.php on my page are broken.

For example if I click the "Home" Button within the navigation I land at /home and see an error page saying: "This page was not found on this server!"

Best,
SuN

**Comment by meangczac** [comment]
Please logout and login again. The .htaccess cache are very sticky.

Tested: 
- Disabled/Uninstall Homepage Driver, 
- Logout admin -> Homepage 404. Logout. 
- Homepage OK, login Homepage OK @ index.php
