### ISSUE TITLE
Executeable JavaScript in Preview

### ISSUE THREAD

**Issue by iPaat** [PHPFusion/PHPFusion#677]
Hi,
found a way to execute own java script.

• Go to /messages.php?msg_send=new
• Enter the following text and click preview:

```
[code]<script>alert('Hi');</script>[/code]
```

It only works with [code]!

P.S.: This also works on https://www.php-fusion.co.uk/forum/post.php?action=newthread&forum_id=137

```
[code]<script>var foo = 12; alert(foo);</script>[/code]
```

Best,
SuN

**Comment by meangczac** [comment]
Thank you for such important notice. Now it's fixed.
