### ISSUE TITLE
Forum description is not rendering BBCodes

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#704]
![07f22a7ed1d3decda97b7322002352bb648](https://cloud.githubusercontent.com/assets/4210004/12417836/3ae1f524-beab-11e5-8d0c-d6d364b46c13.png)

**Comment by iPaat** [comment]
I'm on it.
It needs some time to fix that. Give me an hour.

**Comment by iPaat** [comment]
#705
