### ISSUE TITLE
The search does not seem to be working

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#726]
Hello Developers,

with me in the portal does the search(search.php) not. It can not be found, even though I already have content in the forum and the blog.

Can you also see it in well or not? I've now taken the last update from GitHib.

**Comment by iPaat** [comment]
Hi,
I can't understand what is the problem here. Can you explain again?
(Maybe in German language)

Best,
SuN

**Comment by ghost** [comment]
Also die Portal-Suche bei mir funktioniert nicht. Ich habe bereits Inhalte im Forum und dem Blog und wenn ich die komplette Webseite durchsuche und nach "blog" suche, gibt es keine Suchtreffer. Das sollte doch anders sein oder..

**Comment by iPaat** [comment]
He has content in his blog and his forum. If he searches the whole site for "blog" he gets no result.

---

The search only works for content and title. If any blog entry contains the word "blog" it should be found. Do you get any result if you don't search within the whole page but in blog?

**Comment by ghost** [comment]
Very strange. It does not work and I do not know why. That was noticed only today. The search for PHP Fusion is still under /search.php and so I have also entered under Sitelinks. The search will also be displayed, but it can not be found.

I stayed at the Forum 9.0 a CMS Forum, where I searched for "forum". Also found nothing. What can that be why it does not work?

![portal-search-not-worked](https://cloud.githubusercontent.com/assets/7885632/12513830/4539f734-c120-11e5-8ef1-78eb65427df5.jpg)

**Comment by iPaat** [comment]
![screen](https://cloud.githubusercontent.com/assets/943484/12514197/5fddb7ae-c122-11e5-86d3-da575668f63a.png)
In my forum I have an entry with title "My Test" and content "The Test...". Everything works as expected.

**Comment by ghost** [comment]
I found the mistake. If you have activated SEF URLs and from **/search.php** only **/search** is, the search does not work with me.

Now SEF have disabled in Search and lo, I can re-enter search terms, and I will search hits displayed.

Whether this is just me, I do not know. Perhaps it should still test the developers. Everything else seems to work.

Thank you for your time.

**Comment by Webmeteor** [comment]
Hast du denn auch auf "Suche starten" geklickt?
Hast du über Einträge mit dem Wort Blog? Obwohl dann sollte dort auch stehen keine Einträge gefunden.
Im Fehlerlog auch mal nach geschaut?

**Comment by ghost** [comment]
Die Suche funktioniert nun, aber nicht mit der SEF-URL /search. Wenn meine Portal-Suche unter /search.php zu erreichen ist, dann kann ich Inhalte finden und alles wird durchsucht. Warum das so ist, weiss ich nicht.

**Comment by ghost** [comment]
Hier habe ich in der Fehlerlog etwas gefunden:

PHPFusion/SiteLinks.php
/cms/phpfusion90/administration/site_links.php?aid=0a347fa6bc438587&section=nform&action=edit&link_id=3&link_cat=0
Undefined index: link_id
Zeile: 270
49 Minute(n) zuvor

Ob man damit etwas anfangen kann?!

**Comment by JoakimFalk** [comment]
I have also tested search with and without SEO enabled, I find no issues except that we don´t do module check. I will fix that. 
If you have another issue to report, please make a new reports if you have new issues. 
Keep to English here as well , we can´t help if we don´t understand.
