### ISSUE TITLE
Function time() in database querys

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#731]
This function makes problems in database querys with some hosting configurations.

The problem where in the registration (fixed by me) and now we have it in infusions/news/news.php
See thread http://phpfusion-deutschland.de/forum/viewthread.php?forum_id=17&thread_id=752&pid=4509#post_4501

Why we don't use the mysql function NOW()?
That makes no problems on all hosting configurations.

**Comment by meangczac** [comment]
Hi, Thanks for the feedback. 

My apology as I'm not familiar to `all hosting configurations` requirements and didn't know they do exist. 

I'll patch the news as requested. 

If there are further adjustment required, feel free to make a pull request to us here and it will be much convenient to you.

https://github.com/php-fusion/PHP-Fusion/commit/7db1db675fd703afa2d3f376004a4f34796bec40

**Comment by hien-** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/7db1db675fd703afa2d3f376004a4f34796bec40

**Comment by meangczac** [comment]
I've also pushed similar to Blog.

BUT in forum threads list panel. Please check.

```

if (!isset($lastvisited) || !isnum($lastvisited)) $lastvisited = time();

$result = dbquery("SELECT tp.post_id FROM ".DB_FORUM_POSTS." tp
    LEFT JOIN ".DB_FORUMS." tf ON tp.forum_id = tf.forum_id
    LEFT JOIN ".DB_FORUM_THREADS." tt ON tp.thread_id = tt.thread_id
    ".(multilang_table("FO") ? "WHERE tf.forum_language='".LANGUAGE."' AND" : "WHERE")."
    ".groupaccess('tf.forum_access')." AND tp.post_hidden='0' AND tt.thread_hidden='0'
    AND (tp.post_datestamp > ".$lastvisited." OR tp.post_edittime > ".$lastvisited.")");
```

How do you propose to solve it? If possible, I would require your assistance in making the pull request so all hosting configurations will work.

**Comment by Webmeteor** [comment]
Hi Hien,
it was a generally question. 
I had that issue only in the register. One Member on NSS Germany in the news.
MYSQL Version on both systems are 5.5.46
PHP Version 5.6.17

**Comment by meangczac** [comment]
Then it should be alright... since time() is a PHP microtime function, and I'm also using Mysql during development. First things first we'll just use the MYSQL NOW() since I've tested it and it works as well.

Now, what was the problem since you said News did not work. And Blog copies News as far as we know it. But I'm favoring Blog in development..  lol

Ok, what was your fix in the registration? Can you show where?

**Comment by Webmeteor** [comment]
In UserFieldsInput.php
`dbquery("INSERT INTO ".DB_NEW_USERS."
                    (user_code, user_name, user_email, user_datestamp, user_info)
                    VALUES
                    ('".$userCode."', '".$this->data['user_name']."', '".$this->data['user_email']."', NOW(), '".$userInfo."')
                    ");`

**Comment by Webmeteor** [comment]
@hien I update all files over weekend and set them to mysql function NOW()

**Comment by meangczac** [comment]
Yes, and you can definitely push your change here.

**Comment by Webmeteor** [comment]
Can closed
