### ISSUE TITLE
Forum Droplist in submenu under Gillette Theme is invisible

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#737]
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/12614464/765a0424-c500-11e5-87fd-aebea41eb5e2.png)

**Comment by meangczac** [comment]
I removed Gillette. It's just there to show that PF9 is cross-compatible with older themes that can go responsive. Community will develop new themes for 9 soon enough
