### ISSUE TITLE
This "fix" is not working, two times now, I just patch back to not break repo.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#738]
The error, Fatal error: Can't use function return value in write context in /includes/classes/PHPFusion/Authenticate.php on line 170

The applied fix, https://github.com/php-fusion/PHP-Fusion/commit/fc68746b0437d95405794ca63bfe7dcaaac98083

There was something wrong with revert, so manual patch once my sync is done.

**Comment by meangczac** [comment]
Oh, PHP-Version.  if (function()) only supported in later php version i think. I'll amend that part..

**Comment by meangczac** [comment]
Done. 

https://github.com/php-fusion/PHP-Fusion/commit/06801182ce0bfeeada283c0775daec3f88682245

**Comment by JoakimFalk** [comment]
:)
