### ISSUE TITLE
messages.php

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#747]
Line 552
`if ($defender::safe()) {`
that can't work, because objects in if statements are not allowed. Thats neither TRUE or FALSE thats an error like T_PAAMAYIM_NEKUDOTAYIM

**Comment by Webmeteor** [comment]
In atom.php line 372 crashes too in the same way
`if (!empty($this->less_var) && $defender::safe() && $this->Compiler) {`

**Comment by hien-** [comment]
man, a lot of codes used that... what php version may I ask?

**Comment by meangczac** [comment]
Try not make it not static 

```
 public static function safe() {
        if (!defined("FUSION_NULL")) {
            return TRUE;
        }
        return FALSE;
    }
```

This always returns FALSE. by default. Try change to :

```
global $defender;
if ($defender->safe()) {
```

See if it works? Make sure PHP version is 5.5

**Comment by meangczac** [comment]
I have run on my server so far its ok. So I'll be closing this.
