### ISSUE TITLE
userfield website

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#768]
you can input only www
no validation

**Comment by iPaat** [comment]
If you enter "www" a "http://" will be added automatically.
And http://www is for filter_var a valid URL.
http://www.hashbangcode.com/examples/filter_var_url_validate/
maybe we could implement:
https://github.com/symfony/Validator/blob/master/Constraints/UrlValidator.php

**Comment by Webmeteor** [comment]
It's too big. I've tested with curl. So we have then a real url that exits.

**Comment by iPaat** [comment]
The question is not what is big or small. The question is what is more compatible  and what is the "cheapest" solution.

My code posted below is from a common php framework called symphony. They could use curl as well but decided to implement a regex solution. I think we should take the same way since filter_var don't give us what we want.

**Comment by Webmeteor** [comment]
i've little bit googled. All regex solutions are either too hard or not hard enough.
Curl is implemented since PHP 4.x and I've tested it on a freehoster. I think it's of all hosting solutions compatible. So i think it's the best way to improve a url. And so the url definetely exits, and we can check German Umlaut Domains and other Multibyte Domains too. With symphony they fails.

**Comment by meangczac** [comment]
i like the real url validation a lot. It won't be expensive for the sake of url validation.

And dev always have a choice.

```
form_text("url_without_validation, "Enter URL", $url_callback_value, array("type"=>"text"));
form_text("url_with_actual_validation, "Enter URL", $url_callback_value, array("type"=>"url"));
```

Lets have it all.
