### ISSUE TITLE
Two new notices in blog 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#770]
blog/blog.php infusions/blog/blog.php Undefined variable: lowRes_image_path Line: 452
blog/blog.php infusions/blog/blog.php Undefined variable: hiRes_image_path Line: 451

No image attached, posted a comment.

**Comment by Webmeteor** [comment]
See pull request #774

**Comment by JoakimFalk** [comment]
Great , Thank you.
