### ISSUE TITLE
base table or view not found

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#776]
On each site I've this issue
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.com_news' doesn't exist

As I installed Fusion i have installed the news infusion. Then I have uninstalled the news.

I can't locate this issue. home.php, all panels and the debonair theme files i've checked.

**Comment by Webmeteor** [comment]
this would work for me.
includes/sqlhandler.inc.php

```
function db_exists($table, $updateCache = FALSE) {
    global $db_name;
    if(strpos($table,DB_PREFIX)===false) $table = DB_PREFIX.$table;
    $sql= "SHOW TABLES LIKE '%".$table."%'";
    $result = dbquery($sql);
    if(dbrows($result)) return TRUE;
    else return FALSE;
}
```

And the mysql version can be minor 5.0

**Comment by JoakimFalk** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/1966cb9dc95f3086e655e5fe9abe6d428639e8fd
