### ISSUE TITLE
Two new notices in Gallery

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#777]
admin/gallery_actions.php infusions/gallery/gallery_admin.php?aid=54bbc7a407404dce&section=actions&action=delete&photo_id=7
Undefined index: album_id Line: 159
admin/gallery_actions.php infusions/gallery/gallery_admin.php?aid=54bbc7a407404dce&section=actions&action=delete&photo_id=7
Undefined index: photo_order Line: 159

**Comment by keddyboys** [comment]
Line 153 from gallery/admin/gallery_actions.php looks like 
`$photo_data = dbarray(dbquery("select photo_id, photo_title, photo_filename, photo_thumb1, photo_thumb2 FROM ".DB_PHOTOS."
        where photo_id='".intval($_GET['photo_id'])."'
        "));`
and should look like 
`$photo_data = dbarray(dbquery("select photo_id, album_id, photo_title, photo_filename, photo_thumb1, photo_thumb2, photo_order FROM ".DB_PHOTOS."
        where photo_id='".intval($_GET['photo_id'])."'
        "));`
