### ISSUE TITLE
MySQL min Version is 5.0

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#778]
While we use information_schema.tables for function db_exists
In the description you says mysql min version 4.x

**Comment by Webmeteor** [comment]
See #776 so we can downgrade to mysql version 4.x

**Comment by JoakimFalk** [comment]
Done deal, Thank you 
https://github.com/php-fusion/PHP-Fusion/commit/1966cb9dc95f3086e655e5fe9abe6d428639e8fd
