### ISSUE TITLE
Photo sizes in list view is inconsistent

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#779]
![er-3](https://cloud.githubusercontent.com/assets/4210004/12865788/ba1b48f4-ccb6-11e5-9a5d-7452715f16c3.jpg)
ew
From : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37233&pid=197524#post_197524

**Comment by meangczac** [comment]
easy.. add the template css.

img { width: 100%; }
