### ISSUE TITLE
Problem with panel exclusions

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#780]
The latest version is still a problem with the display panel on the data pages.
The PA I select the option to display the panel only on home.php and it appears on each page.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37248&pid=197567#post_197567

**Comment by meangczac** [comment]
This is 2 part situation. SEO on and off. Algorithm is different on the checks.
SEO is on or not when tested?

**Comment by JoakimFalk** [comment]
The site seems to not have SEO Enabled.
http://www.pogoda-zachodniopomorskie.pl/

**Comment by meangczac** [comment]
I tested again. Nothing wrong with core codes and the admin. 

Tested with welcome message panel and on Septenary.

**Comment by JoakimFalk** [comment]
Closing the thread.
