### ISSUE TITLE
user_theme Notice is sometime thrown to superadmin on new installation

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#782]
Notice: Undefined index: user_theme in \includes\classes\PHPFusion\Authenticate.php on line 160

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37253&pid=197586#post_197586

**Comment by keddyboys** [comment]
Line 158 from includes/classes/PHPFusion/Authenticate.php i belive shouldn't look like this:
`private static function _setUserTheme(&$user) {`
and should be 
`private static function _setUserTheme($user) {`
