### ISSUE TITLE
notice in downloads admin

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#783]
infusions/downloads/admin/download_submissions.php Undefined index: 503 Line: 142

**Comment by Webmeteor** [comment]
is that from last repository? I mean before #788 .
In that line there are no variables

**Comment by JoakimFalk** [comment]
Yes , sorry the link was fubared.

**Comment by keddyboys** [comment]
Line 142 from download_submissions.php look like
`add_to_title($locale['global_200'].$locale['503'].$locale['global_201'].$callback_data['download_title']."?");` but $locale['503'] doesn't exist.
