### ISSUE TITLE
notice in custompage admin

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#785]
PHPFusion/CustomPage.php /administration/custom_pages.php?aid=b6b94e1ac8c8d266&section=cp2&action=edit&cpid=1 Undefined index: page_link_cat
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37258&pid=197593#post_197593

**Comment by meangczac** [comment]
Already patched when working with Main.
