### ISSUE TITLE
Hardcoded locale in permalink tabs

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#786]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37255&pid=197590#post_197590

**Comment by meangczac** [comment]
hmmm..

**Comment by JoakimFalk** [comment]
![untitled-6](https://cloud.githubusercontent.com/assets/4210004/13905272/a0bd368e-eebb-11e5-9deb-72eda5b2a302.png)
