### ISSUE TITLE
install/setup_includes.php

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#791]
With:

```
$htc .= "# Disable directory listing".PHP_EOL;
    $htc .= "Options -Indexes".PHP_EOL.PHP_EOL;
```

I have problems on some hosting like Hosteurope.

If I delete this lines the htaccess will work

Same in administration/ permalinks.php
and with
$htc .= "Options +SymLinksIfOwnerMatch".PHP_EOL;
for sef url the same problem.

**Comment by JoakimFalk** [comment]
We keep recomended and standard configuration. On most hosts it should work. A sticky was created for this issue long ago here : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=36357
