### ISSUE TITLE
mod_rewrite detection

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#792]
The mod_rewrite detection won't work on each host.

On most host it says theres mod_rewrite disabled, but mod_rewrite works.

**Comment by ghost** [comment]
Maybe you have to activate mod_rewrite by adding to .htaccess file:
`RewriteEngine On`

**Comment by meangczac** [comment]
Actually, if you confirm that your hosting works on mod rewrite, then disable the htaccess check manually here. We're developing on the rules by the book for everyone.
