### ISSUE TITLE
pagination is not happening in Articles

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#797]
The correct amount of articles set in settings are listed but the pagination bar never displays.

**Comment by keddyboys** [comment]
Line 199 from articles.php should look like 
`$info['page_nav'] = ($info['articles_max_rows'] > $article_settings['article_pagination']) ? makepagenav($_GET['rowstart'], $article_settings['article_pagination'], $info['articles_max_rows'], 3, FUSION_SELF."?cat_id=".$_GET['cat_id']."&amp;") : "";`

**Comment by JoakimFalk** [comment]
Got it, Ty
