### ISSUE TITLE
New locale has to be defined in includes/dynamics/includes/form_chain.php.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#800]
Line 182: 
Code Gist: Download source  
$html .= "<option value=''>No Option Available</option>";

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37278&pid=197677#post_197677

**Comment by meangczac** [comment]
form chain i think is not used and deprecated. was an experimental ui, but the plugin was not very well developed, so I never used it. We can delete this file.
