### ISSUE TITLE
New locale needs to be defined in includes/dynamics/includes/form_datepicker.php

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#801]
Line 136 :
Code Gist: Download source  
addNotice("warning", "Please ensure your date input value is formatted in date('Y-m-d', callback_data))");

line 138 :
Code Gist: Download source  
addNotice("warning", "Please ensure your date format has only year, month and day");

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37277&pid=197676#post_197676

**Comment by meangczac** [comment]
Forgot clean up earlier.
