### ISSUE TITLE
Amount of articles are restricted to only 1 in subcats

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#802]
Main Categorie is - Was würde aus?
Subs like that ------ Firma 0 - E
------ Firma F - K

and so on, but when i click one of the subs like Firma 0 - E, it only shows me one article, and not the 3 i postet in sub Firma 0 - E

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37282&pid=197684#post_197684

**Comment by meangczac** [comment]
I triple checked. No problem. The thread says bad url link breaks the html. That. I cannot control.
