### ISSUE TITLE
themes/templates/admin_header.php can not have NOW()

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#804]
$result = dbquery("UPDATE ".DB_USERS." SET user_lastvisit=NOW(), user_ip='".USER_IP."', user_ip_type='".USER_IP_TYPE."' WHERE user_id='".$userdata['user_id']."'");

user_lastvisit == int 10 (not date time format)

to this

$result = dbquery("UPDATE ".DB_USERS." SET user_lastvisit='".time()."', user_ip='".USER_IP."', user_ip_type='".USER_IP_TYPE."' WHERE user_id='".$userdata['user_id']."'");

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37285&pid=197696#post_197696

**Comment by iPaat** [comment]
We could use:

``` sql
SELECT UNIX_TIMESTAMP(NOW()) # (now() is optional)
```

[Link](http://www.epochconverter.com/programming/mysql-from-unixtime.php)

**Comment by meangczac** [comment]
This one fixed as recommended.
