### ISSUE TITLE
a silly rewrite driver

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#807]
There come links like this in error_log
/blogs/category/21/blogs/11/blogs/24/articles/2/blogs/17/blogs/11/blogs/10/articles/5/blogs/17/blogs/24/Krankenkassen-und-Fitnessba

**Comment by meangczac** [comment]
How did you get that?

**Comment by Webmeteor** [comment]
I've this in the Error-Log from Fusion Admin

**Comment by meangczac** [comment]
Does the page load properely on that blog page -

yoursite.com/blogs/17/blogs/24/Krankenkassen-und-Fitnessba 

?

**Comment by Webmeteor** [comment]
Yes it loads and display content, but another.

I think the urls will produce by google bot

**Comment by meangczac** [comment]
Ok, Try turn on normalize seo url. It's definitely stacking up and failing on regex /w preg match rules and failed to escape to include rowstart etc. I hope this works for you.

On most cases, I can test only on English titles and parameters.

Try to check the router file. It's reading and parsing wrong $_GET in this case.
