### ISSUE TITLE
Forum second site not shown

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#811]
The second site in forum isn't shown.

See http://community.webmeteor24.de/forum/thread/view/1/PHP-Fusion-V7-auf-PHP7?-row-20

**Comment by Webmeteor** [comment]
/forum/thread/view-24/1/PHP-Fusion-V7-auf-PHP7?#post_24
doesn't go to the post.

**Comment by meangczac** [comment]
Beyond me how it doesn't work in your server, but it does work in mine instead. Please give more input.
