### ISSUE TITLE
Nothing from the standard editor is inserted to the form.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#813]
Admin Dashboard > Content Admin > Web Link Categories
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/13198359/f0bb8242-d806-11e5-9e27-3c7f7adc25e3.png)

**Comment by meangczac** [comment]
What happen? I tested Edit. it's working

**Comment by JoakimFalk** [comment]
**editor**, Click buttons on the form editor ;)
