### ISSUE TITLE
home.php reports no content modules installed when we in fact have some

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#822]
It only account for News,Blog,Articles & Downloads.
Still, Forums, FaQ, Weblinks, Polls are also content modules. 
Forum will display a nice latest threads panel once enabled so the home can just be left blank.
Weblinks & Faq should be treated as the other (latest ) sections..
For now it is somewhat confusing for a new user anyway. 

Id actually like to re-make this home.php totally. Don´t like it at all. ideas?

**Comment by Webmeteor** [comment]
The home must flexibel by the way. Each website has other content. one has a photosite, another a magazin. There are a lot of internetradios and other communitys. For each is content of the home another module.

The most of version 7.02 sites have a extra startpage for showing the content that they like or has there themes.php so modded, that the theme.php only switches the content.

**Comment by Der-WU** [comment]
What about an Userloby like DZCP?
Is it hard to code?

![userloby](https://cloud.githubusercontent.com/assets/164333/13327600/edb23c84-dbea-11e5-8118-19bc18f11e93.png)

with check if modul installed or not and only installed modul are showed.

**Comment by JoakimFalk** [comment]
We sure need to figure something out. A user page is viable but it is only for users, the space is blank for visitors. We be getting some nice profile modules with feeds sooner or later, so it will self solve there.

The home issue is for visitors primarly. We might need an extra API for Infusions that scans the Infusions folder for content.
I will add it to Dev Plan 9.1 and we see what we figure out.

**Comment by JoakimFalk** [comment]
Ok I have this, 

```
home.php only account for News,Blog,Articles & Downloads while it excludes Forums, FaQ, Weblinks and Polls.
· Forum will display a nice latest threads panel once enabled so for that Module it is not needed. 
· Weblinks & FAQ should be treated as all the other sections.
· Create a Core API for Infusions that scans the installed Infusions folder for API content and populates a MVTed home.php with it.
· The MVTed home.php default box can be similar to News Boxes and have a nice top bar GFX for each section.
· The API controls number of items to list, char lenghts to use on an Infusion level while the Theme controls the layout via the MVT system.
```
