### ISSUE TITLE
namespace issue in Forum

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#823]
Fatal error: Class 'PHPFusion\Forums\defender' not found in /home/webpages/lima-city/all-in1/html/webmeteor_community/infusions/forum/classes/Viewthread.php on line 941

**Comment by meangczac** [comment]
Can you check whether \defender with a forward slash before it works?

**Comment by Webmeteor** [comment]
defender works, the forum answer wil be written in database. and then 
comes the issue.

Am 26.02.2016 um 00:21 schrieb Frederick MC Chan:

> Can you check whether \defender works?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/php-fusion/PHP-Fusion/issues/823#issuecomment-189032094.

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
