### ISSUE TITLE
entypo and font awesome

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#825]
why is the print Button sometimes with entypo and sometimes with font awesome?

That is for Theme designers not a good solution.

**Comment by JoakimFalk** [comment]
It is optional, we support both. But it would be good if we had one standard on Core items.

**Comment by Webmeteor** [comment]
i've disabled entypo and in forum the print button will not display

**Comment by meangczac** [comment]
We included 2 library, so these templates were coded in a mix to ensure both were compatible.

I strongly want the community to develop new templates. These options were for that purpose..
