### ISSUE TITLE
form_select array to string conversion

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#826]
includes/form_select.php
/administration/panels.php?aid=4a756eb481e04110
Array to string conversion
Zeile: 232

Overall where a select is.

**Comment by Der-WU** [comment]
It is cause you have a missing string in the global.php of your language. 
Check last change of global.php.

Greatz WuChEn

**Comment by Webmeteor** [comment]
You're right, it was the missing locale.

Can be closed
