### ISSUE TITLE
Weblinks are not working with SEO

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#827]
This is a re-occuring issue, not sure how many times it have been fixed and broke again, we need a solid solution to it now.
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37323&pid=197847#post_197847
Confirmed on Next by me with latest Git.

**Comment by meangczac** [comment]
Nothing on this issue. I dont know what caused it, but fresh install works fine. Reports need some more solid elements on it. 

Test this link: http://next.php-fusion.co.uk/beta/weblinks/1/1/Google
