### ISSUE TITLE
Notices generated when user submitting photos

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#832]
gallery/photo_submit.php, submit.php?stype=p Uninitialized string offset: 0 Line: 55
gallery/photo_submit.php, submit.php?stype=p Uninitialized string offset: 0 Line: 53
gallery/photo_submit.php, submit.php?stype=p Uninitialized string offset: 0 Line: 54

**Comment by meangczac** [comment]
fixed
