### ISSUE TITLE
Multiple Gallery Submissions is overriding each other

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#833]
My first submit failed by unknown reasons. ( See notices ) and no image was attached but the submissions was present for review.
I added another and noticed that the image for the other was present in both sumbissions while I in fact submitted two differant ones. 
I added a 3d and this image overrided the seconday as well for all 3 submissions.

**Comment by meangczac** [comment]
Done , was wrong sql query.
