### ISSUE TITLE
administration/members.php

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#838]
Line 394 must be:
`$message = str_replace("[USER_NAME]", $udata['user_name'],  $locale['email_activate_message']);`

But what we do with [PASSWORD] from the locale file?
We cant get it out of the database, it's unknown.

**Comment by meangczac** [comment]
The PASSWORD is only used in $locale['global_457']  which is used only in  userfieldsInput.php Line 623

Whereas -

$locale['email_activate_message'] = "Hello [USER_NAME],\nYour account at [SITENAME] has been activated.\n
You can now login using your chosen username and password.\n\nRegards,\n[SITEUSERNAME]";

There is no [PASSWORD]
