### ISSUE TITLE
Admin Menu

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#84]
Administration left menu are still not remembering position here and there.

**Comment by JoakimFalk** [comment]
You can simply infuse something and enter the section, like polls or a new infusion and the left menu will collapse when entering it for manageing content.

**Comment by meangczac** [comment]
Yes, it's buggy on Cookie, I don't think it's any vital here if the cookie gets deleted anyway.  Been spending hours to detect to no avail.
- Alternative solution will be overkill.
- Add extra SQL column in DB_USERS to have Venus_Toggle_status beside User_password, user_name ..
- Use PHP Cookie with hardlink refresh. If something is deleting cookie, end up with same.
- Totally remove the toggler.

And I'm not to spend anymore time on Venus as discussed on #299, so close case.
