### ISSUE TITLE
Panels that should be visual on HomePage are not visual with SEO on

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#840]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37341&pid=197910#post_197910

**Comment by Webmeteor** [comment]
It's a mistake with the links, if the link goes to index.php than in URL stays homepage. This wont work.
If its BASEDIR then the URL displays home, that works.

**Comment by meangczac** [comment]
Do you have a viable fix on this one? Please help contribute a commit.
