### ISSUE TITLE
News,Blog,Articles images lists from pulls content from images/ root and not from their own dirs

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#841]
Since our Images handler have specific targets of News, Blog, Article Images we should have it target these dirs to pull files from to insert.

![images_0](https://cloud.githubusercontent.com/assets/4210004/13564572/fd2783a0-e44a-11e5-8b05-7865a184455b.png)

**Comment by meangczac** [comment]
you mean the editor? lets push this back.

**Comment by JoakimFalk** [comment]
Yeah the image selector from the edior in each section. They all have their own directories with the image upload function.
