### ISSUE TITLE
Single Notice Error When Delete a Forum Post (Front End)

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#843]
Fatal error: Uncaught Error: Call to undefined function PHPFusion\Forums\mysql_affected_rows() in /customers/0/c/f/dosspiele.eu/httpd.www/infusions/forum/classes/Moderator.php:551 Stack trace: #0 /customers/0/c/f/dosspiele.eu/httpd.www/infusions/forum/classes/Moderator.php(128): PHPFusion\Forums\Moderator->mod_delete_posts() #1 /customers/0/c/f/dosspiele.eu/httpd.www/infusions/forum/classes/Viewthread.php(232): PHPFusion\Forums\Moderator->set_modActions() #2 /customers/0/c/f/dosspiele.eu/httpd.www/infusions/forum/viewthread.php(38): PHPFusion\Forums\Viewthread->__construct() #3 /customers/0/c/f/dosspiele.eu/httpd.www/index.php(48): require_once('/customers/0/c/...') #4 {main} thrown in /customers/0/c/f/dosspiele.eu/httpd.www/infusions/forum/classes/Moderator.php on line 551

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37360&pid=197976#post_197976

**Comment by meangczac** [comment]
/customers/0/c/f/dosspiele.eu/httpd.www/infusions/forum/classes/Moderator.php:551

Those are not from Admin. Those are front end deletion.

Then the whole thing was a stack trace based on 1 error found only. 

He delete the post... not deleting a forum. 

I was sent over to the moon and back.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/e79341bd611f706917e2e19bfa3cfff807d227ab
