### ISSUE TITLE
When trying to delete the first category in User Fields it crashes

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#844]

**Comment by meangczac** [comment]
Start debugging.. 

General: there are no conflict in the data. Only error pops up somewhere triggered by dbarray() which is non-fatal. Users can override this issue by turning off error reporting. I repeat, this is non-fatal error. It's only uncleaned codes inside quantum engine

Delete a new page with category in it and fields in that category, no error.
Results ..... new page deleted. category moved/fall back to the first page.

Moving a category into a new root category - failed.

**Comment by JoakimFalk** [comment]
Maybe a small check to not allow last cat to be removed would fix it, now it does become fatal in my tests with a full crash , 

> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2053 ' in /home/nextphpf/public_html/RC7/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php:163 Stack trace: #0 /home/nextphpf/public_html/RC7/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php(163): PDOStatement->fetch() #1 /home/nextphpf/public_html/RC7/includes/db_handlers/all_functions_include.php(156): PHPFusion\Database\Driver\PDOMySQL->fetchAssoc(Object(PDOStatement)) #2 /home/nextphpf/public_html/RC7/includes/classes/PHPFusion/QuantumFields.php(419): dbarray(Object(PDOStatement)) #3 /home/nextphpf/public_html/RC7/includes/classes/PHPFusion/QuantumFields.php(243): PHPFusion\QuantumFields->sql_delete_category() #4 /home/nextphpf/public_html/RC7/administration/user_fields.php(28): PHPFusion\QuantumFields->displayQuantumAdmin() #5 {main} thrown in /home/nextphpf/public_html/RC7/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php on line 163

**Comment by meangczac** [comment]
Well, i did say that it has nothing wrong to the Quantum engine. I checked user_fields and user_fields_cat on every step. They were consistent results.

What had happen is that when you delete things, and recall some of the codes inside the script execution based on a null result. Database Factory has clearly have a '@' sign to suppress these kinds of error, but it did not suppress. i don't know why.

$result = dbquery("bleh"); // PDO crash, SQL driver error. 

No big error anyways, flipping the deletion order before dropping column did the trick.
