### ISSUE TITLE
Question: PHP7 Support?

### ISSUE THREAD

**Issue by LaocheXe** [PHPFusion/PHPFusion#846]
Will this version support PHP 7? If you may know PHP 7 threw away the SQL functions that PHP 5 uses.

**Comment by meangczac** [comment]
Netrix (from PHP-Fusion USA) is reporting it is fully compatible with php 7. 

Just make sure your SQL is not MariaDB. We need another driver for DB Factory for that.

**Comment by LaocheXe** [comment]
You should add the PHP 7 Support on the info/readme on github, was looking
for the info there

**Comment by Domi-php** [comment]
Can´t add what we have yet verified, however MariaDB should work just fine according to other reports, so still away to go before we can set anything in stone.

**Comment by JoakimFalk** [comment]
Our PDO should be sufficent there. We have yet done so many various environmental tests, I do think MariaDB turned out to work well in most cases as well., Still lot´s of situational testing required.
