### ISSUE TITLE
Feature Request: 3rd Party Login

### ISSUE THREAD

**Issue by LaocheXe** [PHPFusion/PHPFusion#847]
I tried looking for any hybridauth info in the repo but nothing as of yet. Do you guys plain on adding hybridauth to PHP-Fusion 9 or do you prefer a developer create a infusion for this?

https://github.com/hybridauth/hybridauth

**Comment by JoakimFalk** [comment]
Hi, pease use the Github issues for issues and our site forums for questions.
In short, there are no plans to add anything until stable now.
