### ISSUE TITLE
form_textarea.php & defender.inc.php error

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#849]
admin/weblinks.php the url form_textarea.php not accept https: // link (http: // == yes)
Error Message https: // link : Please fill out this field
edit profile(Website) 
http://www.fusionjatek.hu == OK
https://www.fusionjatek.hu == NOT
error message: Please enter a valid URL

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37371&pid=198030#post_198030

**Comment by meangczac** [comment]
Yes, its not faulty. Click at https://www.fusionjatek.hu/ -- that https is invalid, therefore failed when cURL couldn't be validated. PHP-Fusion rejects them. That is correct.

You need a valid certificate to be https:// 

If you want to not check url, have the "type" set to "text"

![capture](https://cloud.githubusercontent.com/assets/4078041/13901815/3eb3de84-ee6b-11e5-89d4-092e6ff3a6ae.PNG)

Important to have it strict when private information is involved. No error in this case.
