### ISSUE TITLE
popup-previewing custom panel function have formatting issues

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#851]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37368&pid=198034#post_198022

**Comment by meangczac** [comment]
![dns](https://cloud.githubusercontent.com/assets/4078041/13903923/1c03574e-eec9-11e5-850a-01fdffbfcada.PNG)

**Comment by JoakimFalk** [comment]
Only from your part of the world ;)
Here is a screen of the reported flaw
![panel_flaw](https://cloud.githubusercontent.com/assets/4210004/13904437/03b663c0-eea1-11e5-98cd-b6c3b5c174ee.png)

**Comment by meangczac** [comment]
We have 2 preview. Fastest way would be to take out the entirely the preview button and use that comes with the tab.

**Comment by JoakimFalk** [comment]
yeah do it, one way is all we need.

**Comment by meangczac** [comment]
ok.

**Comment by meangczac** [comment]
Ok, when $settings['allow_php_exe'] is on, we need that preview button.

My test date as follow for the panel content when php execution is on:

Fix will be tested against this test data. Please copy the following into panel content when php allow execution is turned on.

```
Test data.. <strong><?php echo "Me"; ?></strong><br/>
<?php
echo "<img src='".IMAGES."article_slider.jpg' class='img-responsive'/>\n";
?>
<?php 
echo lorem_ipsum(3000); 
?>
```

When php execution is off, the preview button will not work and not render.
