### ISSUE TITLE
Double links & email templates are inserted during a re-install of the system

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#854]
This is strange, we had a report of it but I could not get the issue and the user did not answer following questions with multiple langs etc used.
But this time around, On a new install I have a double set of links in the menu and a double set of email templates automatically inserted.
Perhaps they are not dropped when selecting re-install option.

![untitled-7](https://cloud.githubusercontent.com/assets/4210004/13915830/4351e23c-ef57-11e5-9798-e79d1de4f664.png)
![untitled-9](https://cloud.githubusercontent.com/assets/4210004/13915829/4351b38e-ef57-11e5-82bd-bf1c6ee21eaf.png)

**Comment by meangczac** [comment]
Yes, not dropped maybe. So lets fix installer.
