### ISSUE TITLE
Alignment on icons vs text would look much better if text are middle to icon per default

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#856]
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/13979652/2a33fd56-f0da-11e5-8aad-efe00d66522a.png)

**Comment by meangczac** [comment]
you can do so by doing fa-fw class.

ie. "fa fa-search fa-fw"

**Comment by JoakimFalk** [comment]
oh. I need to make notes for readme !!
