### ISSUE TITLE
Message to verify email after registration does not get posted when new user register in SEO mode

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#860]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37393&pid=198123#post_198123

**Comment by meangczac** [comment]
I just registred with 4 different users trying 4 differant combos and all works on my test, tricky one.
I did notice 1 glitch. In SEO mode and email registration, you do not get notyfied that you must active your account. But the Mail is sent so the users should find it.

**Comment by Domi-php** [comment]
That´s my comments, read the full content of it ;)
The report says registration does not work. The error report is about missing message with SEO on.
Users don´t know they need to verify email.

**Comment by meangczac** [comment]
Please re-run test and see if this exist again after months. I'll keep the issue open

**Comment by JoakimFalk** [comment]
Issue is still there, the registration complete message never pops with SEO & Module for home enabled

**Comment by meangczac** [comment]
Yes, $_SESSION gets deleted before it can actually be read. Same case as defender earlier, i reshuffled some parts of the codes to footer.
