### ISSUE TITLE
time stamp need to change in viewthread.php

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#861]
Bad save date.
line: 223, 225, 229, 417, 420, 422, 426
thread_lastpost=now()
this 
thread_lastpost=UNIX_TIMESTAMP(NOW())

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37395&pid=198129#post_198129

**Comment by Kvido** [comment]
line 223, 225, 229, 417, 420, 422, 426
in
infussions / forum / classes / Viewthread.php
do not !!
They are on the line number:
511, 935
Here in DB_FORUM_THREADS I corrected:
thread_lastpost = now ()
this
thread_lastpost = UNIX_TIMESTAMP (NOW ())
As follows: 

```
// update current thread db query ("UPDATE" .DB_FORUM_THREADS. "SET thread_lastpost = UNIX_TIMESTAMP (NOW ()) thread_lastpostid = '". $ Post_data [' POST_ID '].' 'Thread_postcount thread_postcount = + 1, thread_lastuser = '". $ post_data [' post_author"]. '' WHERE thread_id = '". $ thread_data [' thread_id ']." "'); }
Is it right?

```

I adjusted Viewthread:
thread last post = UTC timestamps (NOW ());
It works the first row of the Forum.
