### ISSUE TITLE
Forum/index.php?section=participated

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#862]
"Not closed, disintegrates page."

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37400&pid=198147#post_198147

**Comment by meangczac** [comment]
I dont see how it breaks.....i checked and checked and even put many  `</div>` in the post content.

![how-break](https://cloud.githubusercontent.com/assets/4078041/14946691/49b05c30-1059-11e6-9964-569e24ab22de.JPG)

I fixed html on main forum containers template instead.
