### ISSUE TITLE
Guest comments in News,Blog SEO mode is not going thru

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#867]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37407

**Comment by meangczac** [comment]
This is working. I am not getting this bug with my current copy as well.

![capture](https://cloud.githubusercontent.com/assets/4078041/17075657/35b71782-50cd-11e6-81f2-666ff7d6e75b.JPG)
