### ISSUE TITLE
Bootstrap Theme breaks with 1 Infusion

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#871]
Hi,

Domi and I discussed this with RC1 of v9 in the forums (this is Routh from the forums).

I've just deployed RC3 and the result is the same. From a code perspective I'm at a loss to explain it, however the rendering of pages in the infusion fail with the following error:

```
PHP Fatal error:  Call to undefined function openside() in /var/www/html/infusions/quotes_panel/quotes_panel.php on line 18, referer: https://dev.amateurwriting.net/contact.php
```

This doesn't happen on any other pages. It seems that the theme functions are not accessible from the infusion. This is especially strange as the infusion renders without error in the Septinary theme or any other of the RC1 themes.

I'm fairly positive this is something that can be rectified with a code change in the infusion, however what that could be I'm at a loss, primarily because I cannot explain why only the bootstrap theme causes this.

**Comment by JoakimFalk** [comment]
Hi, 
Can you attach the Infusion here?, I will test if you can.

**Comment by Routhinator** [comment]
Let me review the infusions installer and I'll upload afterwards. The affected infusion is an internal one I've never released and the installer hasn't been used/tested in years.. last checked against PHP-Fusion 5 or 6 I believe.

**Comment by Routhinator** [comment]
Closing this for now as I won't be ready to release this for a bit. If no one else is reporting it, it must be something with the infusion.
