### ISSUE TITLE
Error in showing php-fusion banner

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#873]
When I select infusions to open the banner of the site disappears because it is being searched elsewhere. For example:
when I am on the home page the pathway of the banner is:images/php-fusion-logo.png
when I am in the blog the pathway becomes: infusions/blog/images/php-fusion-logo.png

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37423&pid=198247#post_198247

**Comment by meangczac** [comment]
ok add BASEDIR in front of that would solve the issue.

```
echo BASEDIR.fusion_get_settings("sitebanner");
```
- is the solution.

But i'm not sure where the code is. Theme?

**Comment by JoakimFalk** [comment]
Ive actually done the update at some point, not sure why I not closed it..:/
Just tested on Sept, Bootstrap and Debonair with no issues. Closing for now.
