### ISSUE TITLE
Make user field installation non-destructive during upgrading

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#874]
After upgrading, I cannot reinstall any of my user fields as their columns already exist in the user table. This means I would have to destroy the existing data to re-add the fields. Can you please adjust the user field uninstall/reinstall to have a non-destructive mode that leaves user data intact?

**Comment by meangczac** [comment]
Ah i see. OK, forget check users table.

**Comment by meangczac** [comment]
In v7, the UF is installed. 
This issue can be solved by making sure the UF data is same as the one required in v9. The pass of this test is done by installer. As long as data is congruent to the v9 one, issue self resolved. Just need test.
