### ISSUE TITLE
Forums Set to 'Public' viewing deny users from listing posts

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#876]
I have a lot of forums set to public viewing. If a user clicks a link from the 'Latest Forums' panel they can view the post, but if they try to go to the parent forum, they are denied the ability to list the posts.

Example:

You can view this post: [https://www.amateurwriting.net/infusions/forum/viewthread.php?thread_id=918&pid=3527#post_3527](https://www.amateurwriting.net/infusions/forum/viewthread.php?thread_id=918&pid=3527#post_3527)

But you cannot browse its parent, which is set to PUBLIC:

[https://www.amateurwriting.net/infusions/forum/index.php?viewforum&forum_id=35&parent_id=11](https://www.amateurwriting.net/infusions/forum/index.php?viewforum&forum_id=35&parent_id=11)

You can also see that this seems to be 'working as expected' as far as the forum permissions are concerned:

```
You cannot view all discussion threads in this forum.
```

I cannot find any permission in the permissions section that relates to this other than the forum viewing, which is set to public:

![screenshot from 2016-04-05 19-51-33](https://cloud.githubusercontent.com/assets/727535/14301717/1e09dbca-fb68-11e5-9be9-009e54cd44e2.png)

**Comment by Routhinator** [comment]
Additional information:

It appears this is only affecting subforums of categories. I managed to work around this by making all my forums parents and removing the categories they were in. My forums are an absolute mess now though with no structure. However people can at least post.

**Comment by Routhinator** [comment]
Oops. didn't mean to close that.

**Comment by meangczac** [comment]
Sorry about the upgrades issues. 

You can reinstate your forum structure by installing a copy of PF9 fresh and try it. Then check differences between the two and manually make changes to the correct config in phpmyadmin.

**Comment by meangczac** [comment]
infusions/forum/classes/Forum.php

Line 318 controls the listing of threads within a forum, and is possible the cultprit. The question is whether it's a design/concept error or a code bug.

We had run into similar problems here during early beta stages. About 3-4 issues by Daywalker. And I had solved it, then Tackacs solved it as well again. We had several runs on this, and unheard of this ever since. 

Now it's back.

I'm unsure now, I'll run several test further now. 

Do give a holler if you found the culprit. 

Thank you.

**Comment by meangczac** [comment]
The correct thing to do is

If you set a forum to super administrator

The Public should be able to View the forum, but unable to access just the threads within it. It's forum access. not forum visibility... there is something wrong with current design.

If we hide the visibility of parent to Super Administrator, there is no way to see the child which is set to public view.

Tell me if this is right or wrong.

Again, sorry and thank you for the patience. This is our _first hierarchy_ based design attempt in our software. :smile:

**Comment by Routhinator** [comment]
Hi @hien- I'm blocked from testing to see if this is resolved as I cannot create forums or forum categories due to issue #907 which is caused by the latest master in which you have your fix.

Will test once #907 is resolved.

**Comment by Routhinator** [comment]
Resolution confirmed. Thanks!
