### ISSUE TITLE
form_text and form_textarea.php can not be specified link

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#877]
"form_text and form_textarea.php can not be specified link
http:xxx.hu and www.xxx.hu and http://xxx.hu 
neither accept"

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37426&pid=198255#post_198255

**Comment by meangczac** [comment]
This issue is addressed on forum. I'm closing it.
