### ISSUE TITLE
need add translate $locale['UP'] = "Users Profile";into Russian locale

### ISSUE THREAD

**Issue by Logof** [PHPFusion/PHPFusion#878]
Russian/admin/main.php

$locale['UG'] = "Группы пользователей";
$locale['UP'] = "Профиль пользователя"; //need add
$locale['WC'] = "Категории ссылок";

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion-9-Locale/commit/2e8efcfaae87689ae8702c8d144307de066a2756
