### ISSUE TITLE
Maintenance mode are not in effect when enabled

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#879]
This must have come since last Git round , it sure worked before.

**Comment by LipkeGu** [comment]
can you live with that so far?

https://github.com/TheWalkingRadio/PHP-Fusion/commit/60e21bd9645be024f1e82a75ec5b9ebae1ce7115

**Comment by meangczac** [comment]
I'm going to change to the codes Karrak provided here: 
https://php-fusion.co.uk/forum/viewthread.php?thread_id=37607&pid=198818#post_198818
