### ISSUE TITLE
Default search SDK issues

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#881]
language problem if you translate the local->XXX-> search-> converter.php files then went to the wrong data (Hungarian side) but a file name does not exist

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37435

**Comment by meangczac** [comment]
Bro, this is like a 10 sentence summary to 1 single sentence.  What is local -> xxx -> search -> converter.php then wrong data on Hungarian side mean at all?

**Comment by JoakimFalk** [comment]
Alright, I agree LOL, I will bounce back to forum and request clarification.

**Comment by meangczac** [comment]
Got the meaning now :+1:

**Comment by meangczac** [comment]
Search options now done. 

Add your translations into the converter... for now. The better way is to delete the converter later if complain by a lot... i don't think that this file is any modular in a way as well. Nobody goes update converter.php for every infusion they install from which they download from everywhere that has a search api. 

Anyway, the reason I did not touch anything about it yet is that - There are no issues. 

I will remove the whole solution when I redo the 'Search API' in 9.02
