### ISSUE TITLE
weblink_cat_access is missing in infusion.php

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#882]
Errorlog Says
`Unknown column 'weblink_cat_access' in 'where clause' @ SELECT tw.*,twc.* FROM fusionH9E6x_weblinks tw INNER JOIN fusionH9E6x_weblink_cats twc ON tw.weblink_cat=twc.weblink_cat_id WHERE weblink_cat_access = 0 AND (weblink_name LIKE '%support%' || weblink_description LIKE '%support%' || weblink_url LIKE '%support%'Wink ORDER BY weblink_datestamp DESC LIMIT 0,10.`

**Comment by meangczac** [comment]
There is no weblink_cat_access column. Where this from?
