### ISSUE TITLE
Forum Threads listing oldest first

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#888]
Since upgrading, my forums are now listing all oldest posts first and there is no option to change this in the forum options. 

Listing posts in a forum oldest first makes little sense, as you want to see the newest posts, always.

**Comment by meangczac** [comment]
ok, i'll set the default listing of forum and threads latest on top.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/98b1a0a96c0bf722549d6484a54679f3b246be4f shall close this issue.
