### ISSUE TITLE
form_sanitizer doesn't work with defender form_text in theme/widgets.php

### ISSUE THREAD

**Issue by Webmeteor** [PHPFusion/PHPFusion#889]
This will not work

```
echo form_text("frog_subject_1", $locale['frog_007'], $data1['link_subject'], array("type"=>"text", "inline"=>true));

$subject1 = form_sanitizer($_POST['frog_subject_1'], '', 'frog_subject_1');
```

The options before in this form works fine, but the above code doesn't work.

The Error_log for this code is empty.

**Comment by meangczac** [comment]
I think this fails because session entry is only readable on next refresh. 

If you do this:

```
// Will not execute on first load
if (isset($_POST['something'])) {
     // When you post, it is the second load and session entry of frog_subject_1 will be available for perusal.
     $subject1 = form_sanitizer($_POST['frog_subject_1'], '', 'frog_subject_1');
}

// Loaded in first load.
echo openform("someForm", "post", FUSION_REQUEST);

/**
 when this first load, $_SESSION created. 
It won't be available on first load though. But when you post the button, 
browser reload for the second time, and session created can be used.
**/

echo form_text("frog_subject_1", $locale['frog_007'], $data1['link_subject'], array("type"=>"text", "inline"=>true));
echo form_button("something", $locale['post'], "1"));
echo closeform();
```

**Comment by Webmeteor** [comment]
Session is set by maincore.php

$_POST['frog_subject_1'] has the correct value but $subject1 is empty.

**Comment by meangczac** [comment]
Please read my comment.

**Comment by Webmeteor** [comment]
I read it and I,ve testet.

My complete Code
`<?php
/_-------------------------------------------------------+
| PHP-Fusion Content Management System
| Copyright (C) PHP-Fusion Inc
| https://www.php-fusion.co.uk/
+--------------------------------------------------------+
| Filename: frog/widget.php
| Author: Webmeteor24 Dennis Vorpahl
+--------------------------------------------------------+
| This program is released as free software under the
| Affero GPL license. You can redistribute it and/or
| modify it under the terms of this license which you
| can read by viewing the included agpl.txt or online
| at www.gnu.org/licenses/agpl.html. Removal of this
| copyright header is strictly prohibited without
| written permission from the original author(s).
+--------------------------------------------------------_/
if (!defined("IN_FUSION")) { die("Access Denied"); }

if(file_exists("locale/".LOCALESET."locale.php")){
    include "locale/".LOCALESET."locale.php";
}else{
    include "locale/German/locale.php";
}

opentable($locale['frog_002']);

$settings = get_theme_settings("Frog");

$settings = array(
        "frog_theme_col_1" => $settings['frog_theme_col_1'],
        "frog_theme_col_2" => $settings['frog_theme_col_2'],
        "frog_theme_col_3" => $settings['frog_theme_col_3'],
        "frog_theme_col_4" => $settings['frog_theme_col_4'],
);

if (isset($_POST['save_settings'])) {
    $inputArray = array(
            "frog_theme_col_1" => form_sanitizer($_POST['frog_theme_col_1'], "", "frog_theme_col_1"),
            "frog_theme_col_2" => form_sanitizer($_POST['frog_theme_col_2'], "", "frog_theme_col_2"),
            "frog_theme_col_3" => form_sanitizer($_POST['frog_theme_col_3'], "", "frog_theme_col_3"),
            "frog_theme_col_4" => form_sanitizer($_POST['frog_theme_col_4'], "", "frog_theme_col_4"),
    );
    foreach($inputArray as $settings_name => $settings_value) {
        $sqlArray = array(
                "settings_name" => $settings_name,
                "settings_value" => $settings_value,
                "settings_theme" => "Frog",
        );
        dbquery_insert(DB_SETTINGS_THEME, $sqlArray, "update", array("primary_key"=>"settings_name"));
    }

```
$subject1 = form_sanitizer($_POST['frog_subject_1'], '', 'frog_subject_1');
$link1 = form_sanitizer($_POST['frog_link_1'], '', 'frog_link_1');
$subject2 = form_sanitizer($_POST['frog_subject_2'], '', 'frog_subject_2');
$link2 = form_sanitizer($_POST['frog_link_2'], '', 'frog_link_2');
$subject3 = form_sanitizer($_POST['frog_subject_3'], '', 'frog_subject_3');
$link3 = form_sanitizer($_POST['frog_link_3'], '', 'frog_link_3');
$subject4 = form_sanitizer($_POST['frog_subject_4'], '', 'frog_subject_4');
$link4 = form_sanitizer($_POST['frog_link_4'], '', 'frog_link_4');
$subject5 = form_sanitizer($_POST['frog_subject_5'], '', 'frog_subject_5');
$link5 = form_sanitizer($_POST['frog_link_5'], '', 'frog_link_5');
$subject6 = form_sanitizer($_POST['frog_subject_6'], '', 'frog_subject_6');
$link6 = form_sanitizer($_POST['frog_link_6'], '', 'frog_link_6');

dbquery("UPDATE ".DB_FROG_THEME." SET link_subject=:subject, link_link=:link WHERE link_order=1", array(':subject'=>$subject1, ':link'=>$link1));
dbquery("UPDATE ".DB_FROG_THEME." SET link_subject=:subject, link_link=:link WHERE link_order=2", array(':subject'=>$subject2, ':link'=>$link2));
dbquery("UPDATE ".DB_FROG_THEME." SET link_subject=:subject, link_link=:link WHERE link_order=3", array(':subject'=>$subject3, ':link'=>$link3));
dbquery("UPDATE ".DB_FROG_THEME." SET link_subject=:subject, link_link=:link WHERE link_order=4", array(':subject'=>$subject4, ':link'=>$link4));
dbquery("UPDATE ".DB_FROG_THEME." SET link_subject=:subject, link_link=:link WHERE link_order=5", array(':subject'=>$subject5, ':link'=>$link5));
dbquery("UPDATE ".DB_FROG_THEME." SET link_subject=:subject, link_link=:link WHERE link_order=6", array(':subject'=>$subject6, ':link'=>$link6));
/*if (defender::safe()) {
    redirect(FUSION_REQUEST);
}*/
```

}

echo openform("frog_theme_settings", "post", FUSION_REQUEST);
$exclude_list = "index.php";
$include_list = array();
$file_list = makefilelist(THEMES."Frog/includes/", $exclude_list);
foreach ($file_list as $files) {
    $include_list[$files] = str_replace(".php", "", str_replace("_", " ", ucwords($files)));
}

echo form_select("frog_theme_col_1", $locale['frog_003'], $settings['frog_theme_col_1'], array("options"=>$include_list, "inline"=>true));
echo form_select("frog_theme_col_2", $locale['frog_004'], $settings['frog_theme_col_2'], array("options"=>$include_list, "inline"=>true));
echo form_select("frog_theme_col_3", $locale['frog_005'], $settings['frog_theme_col_3'], array("options"=>$include_list, "inline"=>true));
echo form_select("frog_theme_col_4", $locale['frog_006'], $settings['frog_theme_col_4'], array("options"=>$include_list, "inline"=>true));

$data1=dbarray(dbquery("SELECT link_subject, link_link FROM ".DB_FROG_THEME." WHERE link_order=1"));
echo form_text("frog_subject_1", $locale['frog_007'], $data1['link_subject'], array("type"=>"text", "inline"=>true));
echo form_text("frog_link_1", $locale['frog_008'], $data1['link_link'], array("type"=>"text", "inline"=>true));
$data2=dbarray(dbquery("SELECT link_subject, link_link FROM ".DB_FROG_THEME." WHERE link_order=2"));
echo form_text("frog_subject_2", $locale['frog_009'], $data2['link_subject'], array("type"=>"text", "inline"=>true));
echo form_text("frog_link_2", $locale['frog_010'], $data2['link_link'], array("type"=>"text", "inline"=>true));
$data3=dbarray(dbquery("SELECT link_subject, link_link FROM ".DB_FROG_THEME." WHERE link_order=3"));
echo form_text("frog_subject_3", $locale['frog_011'], $data3['link_subject'], array("type"=>"text", "inline"=>true));
echo form_text("frog_link_3", $locale['frog_012'], $data3['link_link'], array("type"=>"text", "inline"=>true));
$data4=dbarray(dbquery("SELECT link_subject, link_link FROM ".DB_FROG_THEME." WHERE link_order=4"));
echo form_text("frog_subject_4", $locale['frog_013'], $data4['link_subject'], array("type"=>"text", "inline"=>true));
echo form_text("frog_link_4", $locale['frog_014'], $data4['link_link'], array("type"=>"text", "inline"=>true));
$data5=dbarray(dbquery("SELECT link_subject, link_link FROM ".DB_FROG_THEME." WHERE link_order=5"));
echo form_text("frog_subject_5", $locale['frog_015'], $data5['link_subject'], array("type"=>"text", "inline"=>true));
echo form_text("frog_link_5", $locale['frog_016'], $data5['link_link'], array("type"=>"text", "inline"=>true));
$data6=dbarray(dbquery("SELECT link_subject, link_link FROM ".DB_FROG_THEME." WHERE link_order=6"));
echo form_text("frog_subject_6", $locale['frog_017'], $data6['link_subject'], array("type"=>"text", "inline"=>true));
echo form_text("frog_link_6", $locale['frog_018'], $data6['link_link'], array("type"=>"text", "inline"=>true));

//echo form_button("save_settings", $locale['save_changes'], "", array("class"=>"btn-success"));
echo form_button("save_settings", $locale['save_changes'], "1");
echo closeform();

closetable();`

The first part, the options array works fine, but the text fields won't work.

**Comment by Webmeteor** [comment]
$_SESSION['form_fields'] is not set.
I've this SESSIONS 
aid = 1.146..........
performance = Array
csrf_tokens = Array
notices = Array

**Comment by Webmeteor** [comment]
So now it works.
If we make a db insert with dbquery_insert() then the Session is unset. All Code for defender past dbquery_insert don't work then.

**Comment by meangczac** [comment]
It can work.

Just do like this:

```
dbquery_insert(YOUR_DB, $your_input_array, array("keep_session"=>true));
```

See dbquery_insert code docs in the file itself.

```
$options += array(
        'debug' => FALSE,
        'primary_key' => '',
        'no_unique' => FALSE,
        'keep_session' => FALSE
    );
```

It is 'presumed' that we should wipe the field $_SESSIONs past updating/insertion on SQL and generate new ones unless defender returns field config errors, such as blank field on required field.

The mooting was it should wipe the $_SESSIONs at a point, and determined that best to be after updating / insertion on SQL rows, perhaps for security.

However, if you are using multiple dbquery_insert() , you can remove the session on the last one. 

That is why if you still want to use form_sanitizer after dbquery_insert(), you can use the option `keep_session`
