### ISSUE TITLE
Paginator shows in Forum Thread List if thread has multiple pages

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#890]
If a forum thread has multiple pages of replies, the paginator is showing up under it's post date on the list of forum threads.

Example URL (Login required to see due to Issue #876): https://www.amateurwriting.net/infusions/forum/index.php?viewforum&forum_id=7&parent_id=6&order=descending 

Screenshot:

![paginator_bug](https://cloud.githubusercontent.com/assets/727535/14581619/3dcd29c6-03bf-11e6-8176-212b38c1965f.png)

**Comment by meangczac** [comment]
That was intended. So where is the bug?
