### ISSUE TITLE
Forum threads not in stated Order

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#891]
Here I have a screenshot of the forum after I have selected "Descending" order.

Note that neither the original post date or the most recent replies are actually in Descending order:

![paginator_bug](https://cloud.githubusercontent.com/assets/727535/14581630/9994694a-03bf-11e6-9911-867058f7f776.png)

**Comment by meangczac** [comment]
The sql was  set to sort on thread table datestamp which was not updated during reply. I fixed this along with the other issues.
