### ISSUE TITLE
defusing infusion in setup

### ISSUE THREAD

**Issue by MaWe4585** [PHPFusion/PHPFusion#893]
when i try defusing an infusion(i tried it with forum-infusion) in the setup in RC3 i get following messages:

Warning: opendir(../infusions/forum/images/thumbnail/,../infusions/forum/images/thumbnail/): Das System kann die angegebene Datei nicht finden. (code: 2) in C:\Apps\xampp\htdocs\soccerfusion\includes\core_functions_include.php on line 1148

Warning: opendir(../infusions/forum/images/thumbnail/): failed to open dir: No such file or directory in C:\Apps\xampp\htdocs\soccerfusion\includes\core_functions_include.php on line 1148

Warning: readdir() expects parameter 1 to be resource, boolean given in C:\Apps\xampp\htdocs\soccerfusion\includes\core_functions_include.php on line 1149

Warning: closedir() expects parameter 1 to be resource, boolean given in C:\Apps\xampp\htdocs\soccerfusion\includes\core_functions_include.php on line 1166

**Comment by meangczac** [comment]
It's non fatal here. What happen was that we tried to remove all files uploaded by users during defusing. If its empty, the error will show that we cannot delete anything.

Thanks. I will make a check.

**Comment by meangczac** [comment]
```
function makefilelist($folder, $filter, $sort = TRUE, $type = "files", $ext_filter = "") {
    $res = array();
    $filter = explode("|", $filter);
    if ($type == "files" && !empty($ext_filter)) {
        $ext_filter = explode("|", strtolower($ext_filter));
    }
    $temp = opendir($folder); // <---- this. the better fix is make sure you have that folder.
```
