### ISSUE TITLE
Forums are double html encoding characters in Forum titles

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#894]
The forums are double HTML encoding characters on input. The result is forums with HTML codes in the titles.

Example:

User Entry:

```
  Philosopher's Scrolls
```

Saved Forum title in database:

```
  Philosopher&amp;#039;s Scrolls
```

Output title

```
  Philosopher&#039;s Scrolls
```

**Comment by meangczac** [comment]
I have not gotten such issues, how did they get it? I use default editor

![capture](https://cloud.githubusercontent.com/assets/4078041/14946375/f6529c88-1053-11e6-9280-2017730d7f9f.GIF)

The SQL table yes, it's encoded as intended:

![capture2](https://cloud.githubusercontent.com/assets/4078041/14946412/5ebf2b2e-1054-11e6-936b-4f7e96783753.JPG)

Edit works fine, posted edited and encoding decoded works ok as well. 

Is it on your custom template? Output as $info['xxx'] , without any kinds of php function wrapper?

**Comment by JoakimFalk** [comment]
Another with same issue : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37484&pid=198450#post_198446

**Comment by meangczac** [comment]
Best bet is to update using the new scripts in forum infusions again. If still problem persist after upgrade, I need to inspect the site.

**Comment by Routhinator** [comment]
This is happening in the default admin theme. It's only affecting new or edited forms after update.

**Comment by Routhinator** [comment]
The v9 default. Not at the computer so can't look up the name.

Also based on your screenshot you are confusing forum titles with discussion thread titles. This issue affects forum titles.

**Comment by meangczac** [comment]
You should have pointed me to the forum administration in the first place.... takes me 3 minutes to fix, days to figure it out.
