### ISSUE TITLE
Forum thread start hickups

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#895]
When creating a forum as a category the start a thread button still exist when entering this new category.  When you click it, you get redirected back to forum index automatically,

**Comment by meangczac** [comment]
As a category will not have forum. It's just to be a container.

As such, it's not suppose to be able to contain any threads.

The redirect is right, but the template is wrong. Will remove from render.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/347734aea57efd8ec74f1687e7b412715122551d
