### ISSUE TITLE
global.php - $locale['UM061a'] = "Email"; is written in symbols but not in cyrillic.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#896]
See in profile.
![profilebg](https://cloud.githubusercontent.com/assets/4210004/14940398/82f3020e-0f73-11e6-8521-15985b58f811.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37102&pid=198430#post_198430

**Comment by meangczac** [comment]
err... not this repository since it is already moved. Go to https://github.com/php-fusion/PHP-Fusion-9-Locale and lodge issues there. Besides, i'm very sure it's a file not encoded UTF-8 problem.
