### ISSUE TITLE
user fields error when saving blank 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#898]
![userfields](https://cloud.githubusercontent.com/assets/4210004/14975949/6e87cdf0-1107-11e6-92db-31818e9b4121.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37486&pid=198452

**Comment by meangczac** [comment]
How can I replicate this issue? What is saving blank.

**Comment by RobiNN1** [comment]
![output_kjh4hd](https://cloud.githubusercontent.com/assets/11664877/15090973/c6e22ac4-1439-11e6-8e15-bf6679557e56.gif)

**Comment by meangczac** [comment]
Very elaborated. Could find and fix within seconds.

https://github.com/php-fusion/PHP-Fusion/commit/d043532760c6fa2355ca0a88f4face41519939be

Thanks.
