### ISSUE TITLE
Download Cats of dif.Languages are all shown regardless in DL frontpage

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#899]
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/14976101/fd352a10-1108-11e6-9c53-4b34217b4c94.jpg)

See DK Cat, Eng Cat, both created in respective lang but displayed under front regardless

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37483&pid=198445

**Comment by meangczac** [comment]
Should fix now.
