### ISSUE TITLE
valid email gets rejected during install

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#901]
Installation: email+site@gmail.com -> somename+phpfusion@gmail.com is a valid email adres but is rejected.
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37491&pid=198472

**Comment by meangczac** [comment]
- sign is not email. however, . dot is. Email sanitization rules is defined in defender. 

![not_valid](https://cloud.githubusercontent.com/assets/4078041/15595384/23658af4-23f1-11e6-8f93-c319d611a112.JPG)

**Comment by Wanabo** [comment]
gmail+admin@gmail.com is an alias for gmail@gmail.com. If you have a gmail account you could test it.
It comes in handy keeping track where your mail comes from.
Examples:
wanabo+amazon@gmail.com
wanabo+phpf@gmail.com
wanabo+somestore@gmail.com
All mail to these adresses will be delivered to wanabo@gmail.com (including the +part)

**Comment by meangczac** [comment]
ok, so email + is a valid one. Let us reopen this issue.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/8c7d4cf5929ffd5ba3a5fcb156caf0c0bed9e8fb

**Comment by Wanabo** [comment]
Great!

**Comment by meangczac** [comment]
Cheers. :+1:
