### ISSUE TITLE
Default search location in main settings includes not installed infusion

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#902]
Settings Main: Default search location: Blog -> wtf I didn't infused blog at installation -> check for installed infusions and present that list. (Default Forums has my blessing)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37491

**Comment by meangczac** [comment]
what is wtf mean? haha.. yes, there's some wtf still.. although a lot less now. lolol.

**Comment by JoakimFalk** [comment]
lol

**Comment by meangczac** [comment]
Just checked, default search is 'all' at setup
