### ISSUE TITLE
SubForums SEO is not working

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#904]
"Link to subforum does NOT work with permalinks."

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37491

**Comment by meangczac** [comment]
I checked is OK. Screenshot attached.

![forum_attach](https://cloud.githubusercontent.com/assets/4078041/17075652/c96f9900-50cc-11e6-9a71-7a31130a9b9f.JPG)
