### ISSUE TITLE
[Locale - German] Admin-panel: Undefined index: UP

### ISSUE THREAD

**Issue by LipkeGu** [PHPFusion/PHPFusion#906]
The error log is full with this error:

https://github.com/TheWalkingRadio/PHP-Fusion/blob/bleed/administration/index.php#L109

```
administration/index.php
/newsite/administration/index.php?aid=<stripped>&pagenum=0
Undefined index: UP
```

When using the German Locale

**Comment by meangczac** [comment]
Please ask the German NSS administrators to work on this, I'm unable to correctly fix German locales.
