### ISSUE TITLE
MySQL 5.7.x upgrade causes several tables to fail saving without error

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#907]
Ever since I pulled in the latest 9.01 commit, I am experiencing the following things:
- Cannot create new forums or forum categories in the admin panel
- Users get signup email but their data is not saved to the new_users table
- Users that were in the new_users table before the git pull cannot use their register links. Their accounts are never added to users, however their entry is removed from the new_users table. No message is given to the user and they just end up on the home page.
- Error 500 on forum index and forum category views.

None of the above activities generate any errors in the database logs or the php logs or the PHP-Fusion logs. 

I have tested creating data manually in the affected tables without any issues.

All other site functionality is unaffected, including replying to posts, creating new posts, updating user profiles, commenting etc.

Please advise.

**UPDATE:** 

Futher investigation leads me to believe that this is because I updated MySQL recently and PHP-Fusion is not 5.7.x ready

**Comment by Routhinator** [comment]
I managed to see some of what is happening by turning on the general logging in MYSQL. 

Here is the result when I add a new forum category:

```
2016-05-21T23:52:58.162731Z20928 Prepare    INSERT INTO `forums` SET `forum_id` = '0', `forum_name` = 'Test', `forum_description` = '', `forum_cat` = '0', `forum_type` = '2', `forum_language` = 'English', `forum_alias` = '', `forum_meta` = '', `forum_rules` = '', `forum_merge` = '0', `forum_allow_attach` = '0', `forum_quick_edit` = '1', `forum_allow_poll` = '0', `forum_poll` = '-101', `forum_users` = '0', `forum_lock` = '0', `forum_order` = '41', `forum_branch` = '77', `forum_image` = '', `forum_mods` = '', `forum_access` = '0', `forum_post` = '-101', `forum_reply` = '-101', `forum_post_ratings` = '-101', `forum_vote` = '-101'
2016-05-21T23:52:58.163165Z20928 Execute    INSERT INTO `forums` SET `forum_id` = '0', `forum_name` = 'Test', `forum_description` = '', `forum_cat` = '0', `forum_type` = '2', `forum_language` = 'English', `forum_alias` = '', `forum_meta` = '', `forum_rules` = '', `forum_merge` = '0', `forum_allow_attach` = '0', `forum_quick_edit` = '1', `forum_allow_poll` = '0', `forum_poll` = '-101', `forum_users` = '0', `forum_lock` = '0', `forum_order` = '41', `forum_branch` = '77', `forum_image` = '', `forum_mods` = '', `forum_access` = '0', `forum_post` = '-101', `forum_reply` = '-101', `forum_post_ratings` = '-101', `forum_vote` = '-101'
2016-05-21T23:52:58.164318Z20928 Prepare    SELECT error_id, error_status FROM errors
            WHERE error_message = ? AND error_file = ? AND error_line = ? AND error_status != '1' AND error_page = ?
            ORDER BY error_timestamp DESC LIMIT 1
2016-05-21T23:52:58.164974Z20928 Execute    SELECT error_id, error_status FROM errors
            WHERE error_message = 'SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column \'forum_post\' at row 1' AND error_file = '/var/www/html/theden-fusion/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php' AND error_line = 106 AND error_status != '1' AND error_page = '/infusions/forum/admin/forums.php?aid=dde3bb8457921036'
            ORDER BY error_timestamp DESC LIMIT 1
2016-05-21T23:52:58.180883Z20928 Close stmt 
2016-05-21T23:52:58.181026Z20928 Close stmt 
2016-05-21T23:52:58.181101Z20928 Close stmt 
2016-05-21T23:52:58.181731Z20928 Close stmt 
2016-05-21T23:52:58.181795Z20928 Close stmt 
2016-05-21T23:52:58.183605Z20928 Close stmt 
```

There's an error here.. but it never actually shows in the errors for PHP fusion

**Comment by meangczac** [comment]
column forum_post numeric value range -- what is the type in your side? Please change to INT 9999

**Comment by meangczac** [comment]
Your system is upgraded or new install?

**Comment by Routhinator** [comment]
@FrederickChan This is an upgrade install. 

forum.forum_post is currently a SMALLINT(3) UNSIGNED

It should be noted that this is on MySQL 5.7.8 which also has some breaking changes as of 5.7.6 - for example I was getting an error 500 on the forum index until i followed this issue and implemented the settings in the second response

http://craftcms.stackexchange.com/questions/12084/getting-this-sql-error-group-by-incompatible-with-sql-mode-only-full-group-by/12106 

I cannot follow your request. INT (9999) is an impossible setting. INT max width is 255:

```
8:16:36 AM use routh_fusion
8:16:36 AM ALTER TABLE routh_fusion.forums MODIFY forum_post INT(9999) UNSIGNED DEFAULT '101'
8:16:36 AM Display width out of range for column 'forum_post' (max = 255)
```

I have set it to INT(255) and I am testing now

**UPDATE:** This has failed to resolve the issue. I am trying to dig through the query log to see why.

Would be nice to figure why it's also failing to save Errors to PHP-Fusions error table so I can find the errors quickly rather than trying to dig through the query log.

**UPDATE2:**

Just realized this is because this is UNSIGNED and PHP-Fusion is trying to set a negative. This has been fixed by setting SMALLINT(3) 

Fixed on my site now.

**Comment by Routhinator** [comment]
@FrederickChan - Let's start with the Error table, do you see anything wrong here:

![screenshot from 2016-05-29 08-21-21](https://cloud.githubusercontent.com/assets/727535/15633281/75a52f6e-2576-11e6-88e2-c84fd8fd2e48.png)

**Comment by Routhinator** [comment]
I just did some tests. None of this is a problem in MariaDB. This seems to be an issue with MySQL only.

**Comment by Routhinator** [comment]
I have renamed this as I now suspect this is due to MySQl 5.7.x and not the latest commit.

There are many improvements in MySQL 5.7 such as read speed and a memcache API, however there are also data integrity improvements. Those improvements break certain incompatible SQL statements due to a change in MySQL's default behaviour.

See Digital Ocean's article for full details: 
https://www.digitalocean.com/community/tutorials/how-to-prepare-for-your-mysql-5-7-upgrade 

I managed to fix the 500 errors I was getting on the forum index and forum categories by adding the following calls to the my.cnf setup:

```
[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

I'm trying to find other settings I can change to workaround the other issues until PHP-Fusion's code is made compatible with a 5.7.x default install.

**Comment by Routhinator** [comment]
Found the error for users attempting to be created in the new_users table: 

```
SELECT error_id, error_status FROM errors
            WHERE error_message = 'SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column \'user_datestamp\' at row 1' AND error_file = '/var/www/html/theden-fusion/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php' AND error_line = 106 AND error_status != '1' AND error_page = '/register.php'
            ORDER BY error_timestamp DESC LIMIT 1
```

Looks like NOW() broke it:

```
                    (user_code, user_name, user_email, user_datestamp, user_info)
                    VALUES
                    ('c369d61ac49cba2c2bdd219373d4e494c576b9ca', 'Testing', 'user@example.com', NOW(), 'YTozMTp7czo3OiJ1c2VyX2lkIjtpOjA7czoxNToidXNlcl9oaWRlX2VtYWlsIjtpOjA7czoxMToidXNlcl9hdmF0YXIiO3M6MDoiIjtzOjEwOiJ1c2VyX3Bvc3RzIjtpOjA7czoxMjoidXNlcl90aHJlYWRzIjtpOjA7czoxMToidXNlcl9qb2luZWQiO2k6MTQ2NDU1MDI1ODtzOjE0OiJ1c2VyX2xhc3R2aXNpdCI7aTowO3M6NzoidXNlcl9pcCI7czoxMjoiMTAuMTMyLjYwLjQxIjtzOjEyOiJ1c2VyX2lwX3R5cGUiO2k6NDtzOjExOiJ1c2VyX3JpZ2h0cyI7czowOiIiO3M6MTE6InVzZXJfZ3JvdXBzIjtzOjA6IiI7czoxMDoidXNlcl9sZXZlbCI7aTotMTAxO3M6MTE6InVzZXJfc3RhdHVzIjtpOjA7czoxMDoidXNlcl90aGVtZSI7czo3OiJEZWZhdWx0IjtzOjEzOiJ1c2VyX2xhbmd1YWdlIjtzOjc6IkVuZ2xpc2giO3M6MTM6InVzZXJfdGltZXpvbmUiO3M6MTM6IkV1cm9wZS9Mb25kb24iO3M6OToidXNlcl9uYW1lIjtzOjc6IlRlc3RpbmciO3M6OToidXNlcl9hbGdvIjtzOjY6InNoYTI1NiI7czo5OiJ1c2VyX3NhbHQiO3M6NDA6IjZlMjM4NTRiZTUyNDU0ZDg4MWM5Njg4MTQxMzMzNmU3MzA0MzM3NzIiO3M6MTM6InVzZXJfcGFzc3dvcmQiO3M6NjQ6IjdmMGE5Zjc5MDMxNTdmYzc4N2YzZDYwYWVkZjU4ODYyMTlmNDFjYzYyMDdmZGQ2NTVlZTVmZWQ1NDJhYzU1MjkiO3M6MTA6InVzZXJfZW1haWwiO3M6MjM6ImNocmlzdG9waGVyQHJlZHN0YW1wLmNhIjtzOjE1OiJ1c2VyX25hbWVfZmlyc3QiO3M6MDoiIjtzOjE0OiJ1c2VyX2JpcnRoZGF0ZSI7czowOiIiO3M6MTM6InVzZXJfbG9jYXRpb24iO3M6MDoiIjtzOjg6InVzZXJfd2ViIjtzOjA6IiI7czo4OiJ1c2VyX2JpbyI7czowOiIiO3M6MTM6InVzZXJfd3JpdGluZ3MiO3M6MDoiIjtzOjg6InVzZXJfc2lnIjtzOjA6IiI7czoxNjoidXNlcl9zaG91dHMtc3RhdCI7czowOiIiO3M6MTg6InVzZXJfY29tbWVudHMtc3RhdCI7czowOiIiO3M6MTU6InVzZXJfZm9ydW0tc3RhdCI7czowOiIiO30=')
```

**UPDATE:**

OK this one fails because NOW() is now returning '0000-00-00 00:00:00' - This could be fixed by changing the column to VARCHAR.

**UPDATE2:**

Confirmed. I changed the datestamp to VARCHAR(20) and this was inserted:

`2016-05-29 16:06:28`

Either the use of NOW() needs to be deprecated or the column needs to be changed to VARCHAR

Oh, looks like you're planning to fix this by changing to UNIX(NOW) as per #905

**Comment by Routhinator** [comment]
As for the user failing to be inserted into the users table here is the error:

```
INSERT INTO `users` SET `user_id` = '0', `user_hide_email` = '0', `user_avatar` = '', `user_posts` = '0', `user_threads` = '0', `user_joined` = '1464552388', `user_lastvisit` = '0', `user_ip` = '10.132.60.41', `user_ip_type` = '4', `user_rights` = '', `user_groups` = '', `user_level` = '-101', `user_status` = '0', `user_theme` = 'Default', `user_language` = 'English', `user_name` = 'TESTING', `user_algo` = 'sha256', `user_salt` = '62741716e067ea9fed023d10a5ee8b2632fed177', `user_password` = '92bac37623af435f6852559afecd35342b467d31f62927a9a51cad2676cd7444', `user_email` = 'user@example.com', `user_name_first` = '', `user_birthdate` = '', `user_location` = '', `user_web` = '', `user_bio` = '', `user_sig` = ''

INSERT INTO `users` SET `user_id` = '0', `user_hide_email` = '0', `user_avatar` = '', `user_posts` = '0', `user_threads` = '0', `user_joined` = '1464552388', `user_lastvisit` = '0', `user_ip` = '10.132.60.41', `user_ip_type` = '4', `user_rights` = '', `user_groups` = '', `user_level` = '-101', `user_status` = '0', `user_theme` = 'Default', `user_language` = 'English', `user_name` = 'TESTING', `user_algo` = 'sha256', `user_salt` = '62741716e067ea9fed023d10a5ee8b2632fed177', `user_password` = '92bac37623af435f6852559afecd35342b467d31f62927a9a51cad2676cd7444', `user_email` = 'user@example.com', `user_name_first` = '', `user_birthdate` = '', `user_location` = '', `user_web` = '', `user_bio` = '', `user_sig` = ''

INSERT INTO errors (
                error_level, error_message, error_file, error_line, error_page,
                error_user_level, error_user_ip, error_user_ip_type, error_status, error_timestamp
            ) VALUES (
                ?, ?, ?, ?, ?,
                '0', '10.132.60.41', '4',
                '0', '1464552583'
            )

INSERT INTO errors (
                error_level, error_message, error_file, error_line, error_page,
                error_user_level, error_user_ip, error_user_ip_type, error_status, error_timestamp
            ) VALUES (
                256, 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: \'\' for column \'user_birthdate\' at row 1', '/var/www/html/theden-fusion/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php', 106, '/register.php?email=christopher@redstamp.ca&amp;code=7954ee9e588cc7a1dfa2e991809ec25cb288faa2',
                '0', '10.132.60.41', '4',
                '0', '1464552583'

```

Can't explain this one yet, seems dislike PHP-Fusion trying to set the value to '' - maybe in 5.7.x this is evaluating to NULL on a NOTNULL column?

**UPDATE:**

Found the answer to this one. This is a 5.7.x behaviour:
http://stackoverflow.com/questions/23581687/mysql-error-invalid-datetime-format-1292-incorrect-datetime-value-for-col 

Attempting to add ALLOW_INVALID_DATES

**UPDATE2:**

Nope. Nothing I pass to sql_mode seems to change this. Cannot pass a blank value to date in 5.7.x

**UPDATE3:**

Finally, starting MYSQL with sql_mode=ALLOW_INVALID_DATES and **no other options** fixes both users being created and the error 500 on forums. Thsi also fixes the PHP Error logging

The PHP-Fusion driver needs to be updated to set this in the session:

`SET SESSION sql_mode='ALLOW_INVALID_DATES'`

This is the proper way to fix this, and sql_mode should  not be set in my.cnf

**Comment by meangczac** [comment]
I don't know where this lead, but if you say so I'll add. I don't run MariaDB and the addition doesn't glitch the driver, so OK here goes.
