### ISSUE TITLE
Fatal error during installation PHP 7 MySQL 5.0.12

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#908]
Question in english:
When installing the php-fusion 9 RC3 to test, appeared the following error:
"Fatal error: SQLSTATE [42000]: Syntax error or access violation: 1067 Invalid default value for 'user_birthdate' in /usr/share/phpfusion9/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php on line 106"

I can not solve!!!
My S.O is ubuntu 16:04 TLS with apache2, php7 mysql5 and phpmyadmin
Apache / 2.4.18 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
PHP Version: 7.0.4-7ubuntu2
phpMyadmin: 4.5.4.1deb2ubuntu1
What to do?

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37567&pid=198661#post_198661

**Comment by InfoTON** [comment]
Because I was just copied my question (https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37567&pid=198661#post_198661) ?
There is no answer.

**Comment by JoakimFalk** [comment]
Issues are created because I have no instant answer for you. 
The problem need to be investigated and others have a chance to look at it.

**Comment by meangczac** [comment]
install/includes/core_setup.php

Line - 372 --- delete and remove

```
user_birthdate DATE NOT NULL DEFAULT '0000-00-00',
```

Please tell me result. If ok, I commit.

**Comment by InfoTON** [comment]
Falk
  The problem is in default fill the user_birthdate field.
Where is '000-00-00' must contain a valid date.
I do not rule out the line, just changed the line 372
(User_birthdate DATE NOT NULL DEFAULT '0000-00-00')
in the file
  (Install / includes / core_setup.php)
for
(User_birthdate DATE NOT NULL DEFAULT '1900-01-01')

Now generated the tables and the installation continued.
He returned to give error when filling the administrator user fields.
Error:
Fatal error: SQLSTATE [22007]: Invalid datetime format: 1292 Incorrect date value '0000-00-00' for column 'user_birthdate' at row 1 in / var / www / html / php-fusion / includes / classes / PHP-Fusion / Database / Driver / PDOMySQL.php on line 106
Link:
php-fusion / install / index.php? localeset = Inglês

I'll keep checking and you already return.

**Comment by InfoTON** [comment]
I could Falk,

With the command:
sudo grep -R 0000-00-00 (user) or
grep -R 0000-00-00 (root)

I located the files that have this format.
So I accessed each and changed to 1900-01-01.
And ready, I decided all the problems.

Follow the files to be changed:

/var/www/html/php-fusion/install/index.php: '', '-103', '0', 'Default', '', '1900-01-01', '', '', '', '', ''
/var/www/html/php-fusion/install/includes/core_setup.php: user_birthdate DATE NOT NULL DEFAULT '0000-00-00'
/var/www/html/php-fusion/install/includes/core_setup.php: "( 'user_birthdate' '". $ locale [' uf_birthdate ']. "', '3', 'file', '0' , '2', '0000-00-00', '', '', '') "
/var/www/html/php-fusion/upgrade 7:02:07 to 9.0/administration/upgrade/upgrade-7.02-9.00.php '. "" (' User_birthdate '' ". $ Locale [ 'uf_birthdate]', '3', 'file', '0', '2', '0000-00-00', '', '', '') "
/var/www/html/php-fusion/includes/user_fields/user_birthdate_include_var.php:$user_field_dbinfo = "DATE ​​NOT NULL DEFAULT '0000-00-00'";
/var/www/html/php-fusion/includes/user_fields/user_birthdate_include.php: if (isset ($ FIELD_VALUE) && $ FIELD_VALUE = "0000-00-00") {
/var/www/html/php-fusion/includes/user_fields/user_birthdate_include.php: if ($ FIELD_VALUE = "0000-00-00") {
/var/www/html/php-fusion/includes/dynamics/includes/form_document.php: if ($ input_value [4] = "0000-00-00") {
/var/www/html/php-fusion/includes/dynamics/includes/form_document.php: if ($ input_value [5] = "0000-00-00") {

I enjoyed browsing this challenge ...
Hugs and see you soon..

**Comment by meangczac** [comment]
I already committed your pull request. 

Thanks again, and I wish there was more people willing to participate.

**Comment by InfoTON** [comment]
The open-source world has this difficulty.
Everyone wants to use but do not want help.
What motivates us is the solution of the problem encountered.
Alone the strong prevails ...
Let the challenges. Count on me!!!

**Comment by meangczac** [comment]
Thank you very much.

Cost of development is always an issue. If no people help, progress is slow. That's the natural order how things are.
