### ISSUE TITLE
Download Submissions edit - by admin instead of by user when admin edits the submissions

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#909]
When a Member Uploads something, and i go in as a Admin and Change anyything and then save it, The Uploader is not the Uploader anymore its then the Admin. 

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37569&pid=198665#post_198665

**Comment by meangczac** [comment]
When member upload something in Download system, it goes to submissions. 

When the admin change "Anything" what?

The "uploader"  what? is not the "uploader" what? anymore "its then the Admin" what??

Please find out **what** .

**Comment by meangczac** [comment]
Ok, when a Member uploads something it works fine.

When i go in to admin site and change the upload made from a member, like add or change some of the text, picture. thenthe system changes the Member name to admin name.

See picture: 
All from admin changed uploads are then added to admin and not to the Member ho uploadet it
