### ISSUE TITLE
Download descriptions have multilingual issues - seems to clear previous lang set for each save

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#922]
"Hello, i have made som translations from German to English, and English to German.
When i save it in english, discription ok, german not there, when i save it in german discription ok , english not there. even if i made it in both languages. Made 2 screenshots english ok, German discription missing."

![german](https://cloud.githubusercontent.com/assets/4210004/15964434/d1acab2e-2f18-11e6-977b-2bf411772126.png)
![uk](https://cloud.githubusercontent.com/assets/4210004/15964435/d1c3d510-2f18-11e6-921f-010fcfe43aad.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37605

**Comment by meangczac** [comment]
Ok, I understand your concern. Language switching German to English when showing category still show the download. I explain your problems in point form:
1. Create Category - Save under German
2. Create download item under German category.
   3 Go to Site - Switch Language to German, Category Appears. Go to item. 

German Download item appear
German Description appear.

Now Switch Language to English immediately in this item. Still in the Download Item. However, all item information dissapeared and become blank. Item view still ON.  

This is wrong, should directly boot you out. I'll add to query. 

This is a very good find!
