### ISSUE TITLE
Articles user submission halts on all languages except site lang

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#923]
The setting allow submissions is on. When trying to submit on any other language than system default language the system says it is not allowed. 
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/15990494/0d833c68-3094-11e6-8563-2bb041db0b84.png)
Works fine on English.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37610

**Comment by meangczac** [comment]
There is a count for missing category in the particular language. Administration method refers.
Unlike news and blog, there are no "Uncategorized" in Article.  Will add locale to explain this.
