### ISSUE TITLE
forum templates Undefined index: item

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#924]
templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&sort=reply&type=poll
Undefined index: item
Line: 206

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&sort=reply&type=discussions
Undefined index: item
Line: 206

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&sort=reply&type=attachments
Undefined index: item
Line: 206

templates/forum_main.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&sort=reply&type=all
Undefined index: item
Line: 206

**Comment by meangczac** [comment]
Should be fixed this one.
