### ISSUE TITLE
forum Driver/PDOMySQL.php

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#925]
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=4&parent_id=3&sort=reply&time=today
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p2.post_datestamp' in 'group statement'
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=time&time=2week
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=time&time=2days
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106   

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=time&time=1year
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=time&time=1week
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=time&time=1month
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=subject&time=today
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p2.post_datestamp' in 'group statement'
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=subject&time=6month
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=subject&time=3month
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=subject&time=2week
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

Error generated by user using trigger_error() function  
Driver/PDOMySQL.php
/site/infusions/forum/index.php?viewforum&forum_id=3&parent_id=0&type=attachments&sort=subject&time=2month
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 17
Line: 106

**Comment by JoakimFalk** [comment]
https://github.com/php-fusion/PHP-Fusion/issues/928

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/15f3e5577fffd66f06509f380997cfe326bac5bc
