### ISSUE TITLE
PN messages: send_pm("1", "1", "Hi - Subject", "Your Message", "y", "false");

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#930]
dosent work

plz look here: [https://www.php-fusion.co.uk/forum/viewthread.php?forum_id=143&thread_id=37530&pid=198911#post_198911](url)

**Comment by JoakimFalk** [comment]
As stated in the thread, do not sent to your self.
if (isset($_GET['pm'])) {
require_once(INCLUDES."infusions_include.php");
send_pm("1", "2", "Hi - Subject", "Your Message", "y", "false");
echo "PM sent";
}
Confirmed working, 
![works](https://cloud.githubusercontent.com/assets/4210004/16304839/8720701a-3957-11e6-9153-2e5d26c20b72.png)
