### ISSUE TITLE
token/form_sanitizer problem / no multible DB entries (DB_SUBMISSION/Other Table)

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#931]
it is not possible to save two db entries (one in DB_SUBMISSIONS und one in a other Table) to the same time. 

Plz look here for more infomrmationen: 
[https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37640&pid=198946#post_198946](https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37640&pid=198946#post_198946)

**Comment by JoakimFalk** [comment]
From what I can see, it is handled on main forum closing for now.
