### ISSUE TITLE
Bootstrap/functions.php - Missing argument 1 for opentable() / openside

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#932]
Bootstrap/functions.php
Missing argument 1 for opentable(), called in /var/www/vhosts/.........test/infusions/figurelib/templates/template_render_figure_cats.php on line 45 and defined

using _opentable()_ or _openside()_ --> notices
using: _<aside> ... </aside>_ all ok

**Comment by JoakimFalk** [comment]
You need to put a title in them like opentable("Title);
