### ISSUE TITLE
Pagenav is missing in forum and count is off with subforums

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#933]
"
It's another counting issue in the code. In the forum classes Forum.php, (around line 468) the $count value (thread_max_rows) gives 1 as result (at least after a couple of tests). After doing a separate counting for quick fix, it seems to work fine."

"If the viewforum attribute is set, the information for the forums are incorrect.
For some reason, the threads have the same number as the replies, which in that case is incorrect.
"

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37652

**Comment by meangczac** [comment]
Problem is gone. Was typo mistake on the page nav.
