### ISSUE TITLE
Mysqli

### ISSUE THREAD

**Issue by t0msk** [PHPFusion/PHPFusion#934]
Please add support for mysqli with binds

**Comment by meangczac** [comment]
referenced;
http://code.tutsplus.com/tutorials/pdo-vs-mysqli-which-should-you-use--net-24059

**Comment by t0msk** [comment]
yes i know what is it, and i use mysqli in php fusion 7 but with no binds :(

**Comment by meangczac** [comment]
I was referencing so that I can work with on the Database Factory to add this part later. ^^
