### ISSUE TITLE
Notices in forum

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#937]
includes/components.php forum/includes/dynamics/assets/preview/preview.ajax.php Undefined index: UM101 Line: 195
includes/components.php forum/create-new-thread Undefined index: UM101 Line: 195
includes/components.php infusions/forum/index.php?viewforum&forum_id=1&parent_id=0 Undefined index: UM101 Line: 195

**Comment by meangczac** [comment]
Septenary.

**Comment by meangczac** [comment]
is fixed. no error on SEO mode.
