### ISSUE TITLE
Problem with multilingual content - default page language is always checked

### ISSUE THREAD

**Issue by tom-11880** [PHPFusion/PHPFusion#940]
I tried to set up the same cuatom page in English and German but found that the default language (in my case German) always stays checked.

![cp3](https://cloud.githubusercontent.com/assets/20478537/17085281/c83a88b6-51d4-11e6-9b39-f078bf5d84c5.png)

**Comment by meangczac** [comment]
It's fixed now. Thank you so much for making an image for this issue. It is clear and it makes my job very easy.

Please get the new file. 
https://github.com/php-fusion/PHP-Fusion/blob/9.01/administration/custom_pages.php

**Comment by tom-11880** [comment]
Frederick, you're a champion :-) 
But the last commit still seems to be from february... probably I have to wait a little bit?

**Comment by meangczac** [comment]
Hi thank you.

I've already committed when I posted the file. 
https://github.com/php-fusion/PHP-Fusion/commit/7fb61332c0306024f09b4176b8d98cbcab2a78db
After that I altered again for something which I missed out..
https://github.com/php-fusion/PHP-Fusion/commit/c347811215dd517c9e17e092d096791084abddc9

You can always pull into your fork if you are using git cmd.
