### ISSUE TITLE
Problems with "$locale" array (aka why globals are causing nothing but troubles)

### ISSUE THREAD

**Issue by tom-11880** [PHPFusion/PHPFusion#941]
When setting up my page, I came across a weird translation issue.

Under Language -> Language settings, there is the caption **Site locale** for the language dropdown:

![pf01](https://cloud.githubusercontent.com/assets/20478537/17109035/90a39132-5296-11e6-8431-5d56bbabec1a.png)

When I switched to german, this was translated to **IP-Adresse** (sorry no screenshot this time, can't reproduce it right now), which seemd a weird translation for "site locale".

So I started to find out where this might come from.

In /administration/settings_languages.php, around line 268, I found this code snippet:

`echo form_select('localeset', $locale['417'], fusion_get_settings("locale"), ....`

So apparently, _$locale['417']_ is where the translation comes from and I searched where this was defined.

And actually there are more than one location, but with different text / translations:

English:
\phpfusion\locale\English\messages.php -> $locale['417'] = "Show sender with Letters:";
\phpfusion\locale\English\admin\admin_reset.php -> $locale['417'] = "Reset time";
\phpfusion\locale\English\admin\settings.php -> $locale['417'] = "Site locale:";
\phpfusion\locale\English\admin\errors.php -> $locale['417'] = "IP:";

German:
\phpfusion\locale\German\admin\errors.php -> $locale['417'] = "IP-Adresse:"; **(this is where the wrong translation comes from)**
\phpfusion\locale\German\admin\settings.php -> $locale['417'] = "Seitensprache"; **(this is the correct translation)**

I'm quite sure that when this happened, there was an error message at the top of the page, so it looks to me as if the $locale array gets overwritten by /admin/errors.php in case of an error.

**Comment by meangczac** [comment]
Corrrect. That is why I devised the 

```
// Returns an array from the source file + global.php
$locale = fusion_get_locale('', $source_of_locale_file);
$locale += fusion_get_locale('', $source_of_second_file);
```

This is to progressively add array into $locale via manual control.

It was a global that caused the file go wrong. I have no opportunity to clean the system clean yet. But if you can provide a push to the repo for your findings, I will be very glad to merge it.

My plan is.. once we get all working, I will be able to lead on lots of cool features on this.
