### ISSUE TITLE
settings_main.php error

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#943]
Undefined index: savesettings
Sor: 47
Undefined index: exclude_blower
Undefined index: exclude_right
etc all wrong

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37736&pid=199305#post_199305

**Comment by meangczac** [comment]
Test https://github.com/php-fusion/PHP-Fusion/commit/e55769fdd006016bd0649ae08cbf0fd7a3014ecc
