### ISSUE TITLE
Forum BBCode Glitch on secondary posts

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#948]
![bbcxode-glitch](https://cloud.githubusercontent.com/assets/4210004/17474268/6578139c-5d55-11e6-80bf-46e343825c2a.png)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37762

**Comment by meangczac** [comment]
The quick reply reversed wrongly on post_smileys :dancer:
