### ISSUE TITLE
Submissions - Port links and theme paths to cover each infusion

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#95]
Port all submissions to Infusions.

to eliminate another bug:

Approving submissions renders the following error message : There was an error while processing your request

**Comment by meangczac** [comment]
Blog done, news done - removing labels.

**Comment by meangczac** [comment]
This one literally says port submissions away. It's done.

**Comment by JoakimFalk** [comment]
The link from Admin is left, it still points to submissions.php
![down-the-right](https://cloud.githubusercontent.com/assets/4210004/9548369/66f11a86-4da0-11e5-8576-74d1da37001a.png)

**Comment by JoakimFalk** [comment]
Basically we need some handler-API in admin to check Infusion and point to it directly to it for submisson approval and remove the admin/submissions.php

**Comment by meangczac** [comment]
Already done. Please check and close issue if ok.

**Comment by JoakimFalk** [comment]
Not from what I can see, the bottom right image, submissions in Venus , each link that popup there need to point to the infusions submissions tab

**Comment by meangczac** [comment]
See this... this is the Git referenced earlier.

It suppose to look like this:

![screen shot 2015-09-03 at 3 01 21 pm](https://cloud.githubusercontent.com/assets/4078041/9652332/db11ee58-524c-11e5-8696-a26e3aefaedb.png)

**Comment by JoakimFalk** [comment]
Was a local issue, wiped an re-installed Git dir and now I have the update !
