### ISSUE TITLE
Hardcoded locale in News administration

### ISSUE THREAD

**Issue by jantom** [PHPFusion/PHPFusion#959]
In RC4 I've found hardcoded locale in _/infusion/news/admin/news.php_, but it's possible, that in another files will be similar situation.

**Comment by meangczac** [comment]
If you have errors list of the undefined index, please help copy and paste the whole list into this issue.

**Comment by jantom** [comment]
/Infusions/news
- _/admin/news.php_  
  Line 58, 63, 66, 151, 195, 203, 205, 233-235, 242, 248, 256, 264, 274, 286, 302-311, 623
- _/admin/news_cat.php_  
  Line: 179, 181, 186, 198, 267, 270, 342, 344-348, 384, 394, 422-424, 437, 440, 475-482
- _/admin/news_submissions.php_  
  Line: 205
- _/news_admin.php_  
  Line: 67, 70, 72, 79, 82, 84

I think, that's all lines to check.

**Comment by meangczac** [comment]
Thanks Jan. I'll fix as soon possible.
