### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#96]
Installer, Move the add Infusions as the last step due to the Admin rights issues.

**Comment by rimelek** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/bc97ba2acbf70f4de7b54aec4b506b18c131c28e

I needed to make more changes and I have tested more times, but please, test it you too before you close it.

**Comment by meangczac** [comment]
I'm currently tied into Gallery. My schedules IRL is getting tighter by the day. I'm pushing a lot of stuff behind and make fusion priority.. so i'm putting all time to what i can do now. 

I will leave the testing to Domi. So let me tag him.

**Comment by meangczac** [comment]
Tested. Works nice.
