### ISSUE TITLE
forum user field adding not possible

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#960]
Driver/PDOMySQL.php
/test/administration/user_fields.php?aid=4xxxxxxxxxxxxxx
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-stat' at line 1
Line: 108

Module Fields Information
Version: 1.01.00
Field Table Column:
user_forum-stat
Field Table Column Info:
This is not a field
Field Description:
Displays number of forum posts.

**Comment by RobiNN1** [comment]
It is not a issue, on my site works well
