### ISSUE TITLE
can't import database

### ISSUE THREAD

**Issue by tabux** [PHPFusion/PHPFusion#961]
Fatal error: Call to undefined method PHPFusion\Database\Driver\PDOMySQL::prepare() in /home/someuser/public_html/administration/db_backup.php on line 152

**Comment by JoakimFalk** [comment]
Please update from latest Git, I belivie it have been fixed. ( https://github.com/php-fusion/PHP-Fusion/commit/dac8c2326b0bffc3e9b83d6fd79e4752131c5c88 )

**Comment by meangczac** [comment]
I think that one is export?

**Comment by JoakimFalk** [comment]
Yes !.
