### ISSUE TITLE
instalation failed php fusion 9

### ISSUE THREAD

**Issue by QuillLittlefeather** [PHPFusion/PHPFusion#964]
trying to install php fusion but get this error

Fatal error: Invalid default value for 'page_grid_order' @ CREATE TABLE fusion73QB7_custom_pages_grid ( page_id MEDIUMINT(8) NOT NULL DEFAULT '0', page_grid_id MEDIUMINT(9) NOT NULL AUTO_INCREMENT, page_grid_column_count TINYINT(1) NOT NULL DEFAULT '0', page_grid_html_id VARCHAR(50) NOT NULL DEFAULT '', page_grid_class VARCHAR(100) NOT NULL DEFAULT '', page_grid_order TINYINT(5) NOT NULL DEFAULT '', PRIMARY KEY (page_grid_id), KEY page_id (page_id) ) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci in C:\xampp3\htdocs\includes\classes\PHPFusion\Database\Driver\MySQL.php on line 176

**Comment by meangczac** [comment]
Is done.
