### ISSUE TITLE
Php code is not working in panel

### ISSUE THREAD

**Issue by QuillLittlefeather** [PHPFusion/PHPFusion#966]
in php fusion 7 i could add 

openside(\"Server #1\");$output = \"\";
$lgsl_zone_number = 1;
include INFUSIONS.\"lgsl/lgsl_files/lgsl_zone.php\";
echo $output;
unset($output);
closeside();

this nolonger works in 9.0.x
What has changed that makes this not work?

**Comment by meangczac** [comment]
Security Settings , turn it on.

![capture](https://cloud.githubusercontent.com/assets/4078041/17829567/67d312ec-66e5-11e6-9384-6d1f99b28961.JPG)

The convention now is to use a proper file inclusion and try not to use Eval. 

Make a panel.

I know the convenience, but I'm emphasizing the importance against malicious admin. If you know what i mean.
