### ISSUE TITLE
no emails by register and in infusions

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#967]
i have RC4 installed
i have register two times and get no email
in database in table "new_users" is see this 2 new users

in my figurelib infusion i have build in a notification too ... there is also no email notification. only private messages works

**Comment by meangczac** [comment]
Please tell me your parameters in settings, I just fixed this many times already  ---

![capture](https://cloud.githubusercontent.com/assets/4078041/17829100/b7804cca-66d5-11e6-8db1-2c720bcec5a9.JPG)

**Comment by meangczac** [comment]
Please get and replace 4 files and tell me the result: Latest

https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/classes/PHPFusion/QuantumFields.php
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/classes/PHPFusion/UserFields.php
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/classes/PHPFusion/UserFieldsInput.php
https://github.com/php-fusion/PHP-Fusion/blob/9.02/register.php

**Comment by Catzenjaeger** [comment]
ok i will tell the result. 

my settings are ok i think

![ashampoo_snap_2016 08 20_11h18m15s_023_](https://cloud.githubusercontent.com/assets/19621858/17830287/c8ec6a60-66c7-11e6-9734-2a57a053520e.jpg)

see also in our github project figurelib https://github.com/Catzenjaeger/FigureLib_3/issues/51

**Comment by JoakimFalk** [comment]
Works for me on latest Git here to 3d party mail ( gmail ) .
