### ISSUE TITLE
min/max/step eg doesnt work on forms correct

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#968]
I have a form with some restrictions but some dosent work

Guess it is a failure based in PHP-Fusion.

plz add the following options for "type='number'":
min
max
step

HTML Reference
http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_number_step

normally this is not possible (negative when set min = 0)
![ashampoo_snap_2016 08 20_19h01m15s_041_](https://cloud.githubusercontent.com/assets/19621858/17832660/8bcbb154-6708-11e6-9bec-d32eb6179e1b.jpg)

**Comment by meangczac** [comment]
I will increment on it.
