### ISSUE TITLE
Notice Undefined variable: internal_url / remote_url

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#975]
this notice comes in a form what uses formfields as link
i dont use this varibales in my files

check --> https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/admin.php

includes/defender.inc.php
/test/infusions/figurelib/admin.php?aid=8d4c55eb004cd355&section=figurelib_form&action=edit&figure_id=2
Undefined variable: internal_url
Line: 1027

Run-time notices  
includes/defender.inc.php
/test/infusions/figurelib/admin.php?aid=8d4c55eb004cd355&section=figurelib_form&action=edit&figure_id=2
Undefined variable: remote_url
Line: 1029

`Source code (Line: 1017 - 1037)
1017            if ($this->field_config['required'] && !$this->field_value) {
1018                self::setInputError($this->field_name);
1019            }
1020            if ($this->field_value) {
1021                $url_parts = parse_url($this->field_value);
1022                if (!isset($url_parts['scheme']) && isset($url_parts['path'])) {
1023                    $remote_url = 'http://'.$this->field_value;
1024                    $internal_url = fusion_get_settings('siteurl').$this->field_value;
1025                }
1026                // Check both remote and internal.
1027                if (self::validateURL($internal_url) !== FALSE) {`

**Comment by meangczac** [comment]
Already fix this.

**Comment by Catzenjaeger** [comment]
:+1:
