### ISSUE TITLE
Email Notification Levelmeter

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#977]
always blank 
i had 16 messages but on home.php i see always a empty levelmeter

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17961663/566ecd7c-6aad-11e6-9b10-f4d133adee06.JPG)

**Comment by meangczac** [comment]
The level meter is only for member, Super Admin is infinite. 

IF a max number is given, it's gonna be like 16/1000000000000000000000000000000000000000000000000000 width. That is why you will never see meter growing at all. For a progress bar to move, you need like 5/10 = 50% meter. With infinite, progress meter do not have Max.

**Comment by Catzenjaeger** [comment]
lol sorry i don't know that ... when its normally not bad when you this feature hide for admins .. when i never see a result = i don't need that :)

**Comment by meangczac** [comment]
Well, why not. OK.
