### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#988]
Recaptcha
pf9\includes\captchas\grecaptcha\recaptchalib.php
/pf9/contact.php
Methods with the same name as their class will not be constructors in a future version of PHP; ReCaptcha has a deprecated constructor
Line: 41

Secure Image
Code does not show
pf9\includes\captchas\securimage\securimage.php
/pf9/contact.php
Methods with the same name as their class will not be constructors in a future version of PHP; Securimage has a deprecated constructor
Line: 55

Secure Image v2
Code does not show
pf9\includes\captchas\securimage2\securimage.php
/pf9/contact.php
Methods with the same name as their class will not be constructors in a future version of PHP; Securimage has a deprecated constructor
Line: 91

pf9\includes\captchas\securimage2\securimage.php
/pf9/contact.php
Methods with the same name as their class will not be constructors in a future version of PHP; Securimage_Color has a deprecated constructor
Line: 1247

**Comment by meangczac** [comment]
This is the problem - http://stackoverflow.com/questions/36339774/php7-constructor-class-name

The code is provided by Google. What PHP Version are you using at the moment? I updated a crude fix, but I strongly suggest up the PHP Version on your end.

**Comment by RobiNN1** [comment]
I'm using php 7.0.7

**Comment by meangczac** [comment]
I'll follow up on your Secureimage v3
