### ISSUE TITLE
administration/site_links.php --> Undefined index: link_position_id

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#989]
administration/site_links.php
/test/administration/site_links.php?aid=a5f1e144909e9066&section=links&action=edit&link_id=91&link_cat=0
Undefined index: link_position_id
Line: 605

Run-time notices  
administration/site_links.php
/test/administration/site_links.php?aid=a5f1e144909e9066&section=links&ref=link_form&action=edit&link_id=91&link_cat=0
Undefined index: link_position_id
Line: 428

**Comment by meangczac** [comment]
This issue already fix.
