### ISSUE TITLE
panel_restriction

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#990]
$inf_insertdbrow[] = DB_PANELS." (
                        panel_name, 
                        panel_filename, 
                        panel_content, 
                        panel_side, 
                        panel_order, 
                        panel_type, 
                        panel_access, 
                        panel_display, 
                        panel_status, 
                        panel_url_list, 
                        panel_restriction
                        ) VALUES(
                        'FigureLib Admin Panel', 
                        'figurelib_admin_panel', 
                        '', 
                        '1', 
                        '1', 
                        'file', 
                        '3', 
                        '1', 
                        '1', 
                        '', 
                        '3'
                        )"; 

it doesnt work correct i guess. My home site is home.php and set in settings main but the panel would not show on this place - 3 = show in homepage

**Comment by meangczac** [comment]
Add the panel in administration. and see your DB_PANELS data in PHPMyAdmin. 
Copy back the same values ?

**Comment by Catzenjaeger** [comment]
i have do that :) but the function show on startpage dosent work .. i can show the panel on all sited but i have to add it manually.

**Comment by meangczac** [comment]
I'll try and get back to you later.

**Comment by meangczac** [comment]
panel_access is 3. There is no 3 in panel_access, only -103, -102, -101, and 0
