### ISSUE TITLE
Bootstrap Collapsible List Group not correct

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#992]
i use this code on my site but get a small error in view

code: 
`echo "<div class='panel-group'>
  <div class='panel panel-default'>
    <div class='panel-heading'>
      <h4 class='panel-title'>
        <a data-toggle='collapse' href='#collapse1'>Collapsible list group</a>
      </h4>
    </div>
    <div id='collapse1' class='panel-collapse collapse'>
      <ul class='list-group'>
        <li class='list-group-item'>One</li>
        <li class='list-group-item'>Two</li>
        <li class='list-group-item'>Three</li>
      </ul>
      <div class='panel-footer'>Footer</div>
    </div>
  </div>
</div>";`

it looks so and is not correct
![ashampoo_snap_2016 08 30_18h48m09s_003_](https://cloud.githubusercontent.com/assets/19621858/18098395/5864995c-6ee2-11e6-80e4-f7900b81ecb8.jpg)

http://www.w3schools.com/bootstrap/bootstrap_collapse.asp

**Comment by RobiNN1** [comment]
Add this code to your code
`add_to_head('<style type="text/css">.panel .list-group {margin-bottom: 0;}.panel .list-group .list-group-item:first-child {border-top-right-radius: 0px;border-top-left-radius: 0px;}.panel .list-group .list-group-item:last-child {border-bottom-right-radius: 0px;border-bottom-left-radius: 0px;}.panel .list-group .list-group-item {border-left: 0;border-right: 0;}</style>');`

**Comment by Catzenjaeger** [comment]
thanx but i guess it must be fix in core files and not manually

**Comment by RobiNN1** [comment]
Reupload pf9, this problem is fixed.

**Comment by Catzenjaeger** [comment]
cool thanx :+1:
