### ISSUE TITLE
fresh installed PHPF - missing some panels Bootstrap theme 

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#997]
look at this image - i installed it for 5 minutes with the newest files from here

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18128787/d2f930ce-6f87-11e6-8054-45131f636f3a.JPG)

**Comment by Catzenjaeger** [comment]
found the mistake .. fresh installed fusion start view a custom page as general page. normally we had home.php

**Comment by RobiNN1** [comment]
In Main Settings set site opening page to home.php

**Comment by Catzenjaeger** [comment]
yup i found itself but new php fusion members too?

**Comment by RobiNN1** [comment]
home.php will later be removed.

**Comment by FrederickChan** [comment]
Yes, home.php I want to get rid of when I'm complete with Fusion Theme.

**Comment by meangczac** [comment]
It's my goal, but it's not clear at this moment.

**Comment by meangczac** [comment]
But @Catzenjaeger is right here. I already put in back administration link.

**Comment by Catzenjaeger** [comment]
so i have install my system complette new (install time 14:50 German Time) 
this is my start screen: 

![ashampoo_snap_2016 09 03_14h53m41s_021_](https://cloud.githubusercontent.com/assets/19621858/18224916/386f199a-71e6-11e6-8754-83df548ba910.jpg)

**Comment by meangczac** [comment]
Bootstrap Theme, Septenary will delete by end of RC5 phase.

New installation starting page will be only coming from Nebula.
