### ISSUE TITLE
Glyphicons not visible

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#998]
with the last PHPF version all my glyphicons not visible

example: <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

show only placeholders on every sites

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18129098/6c9ef546-6f89-11e6-8ea1-c0eca0dd1a12.JPG)

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18129129/903abbca-6f89-11e6-8b86-fd78a6d4435f.JPG)

**Comment by RobiNN1** [comment]
In includes/bootstrap/bootstrap.css and bootstrap.min.css is wrong path to glyphicon

**Comment by meangczac** [comment]
I'll check bootstrap

**Comment by meangczac** [comment]
Please try again.. https://github.com/php-fusion/PHP-Fusion/commit/ac2965e0e77598dc17f5c8b0f8990c73bc1e9bd5

I didn't notice it earlier sorry, was busy with theming myself. I used the 'fa'. 

It has more icons to play with. The Font Awesome ones in Theme Settings (Turn on) then check the alias here: http://fontawesome.io/icons/

**Comment by Catzenjaeger** [comment]
its not the solution .. not shown :(

**Comment by RobiNN1** [comment]
Delete cache or use font awesome

**Comment by Catzenjaeger** [comment]
i guess i have to rebuilt all my panels but sorry its not the solution general .. it must be fixed sometime for all others.

**Comment by Catzenjaeger** [comment]
hmn i dont have this file in my folder only a bootstrap.min.js

 PHP-Fusion/includes/bootstrap/bootstrap.js

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18160861/9a631362-702f-11e6-8961-1f602541453e.JPG)

**Comment by RobiNN1** [comment]
Download latest PHP Fusion

**Comment by Catzenjaeger** [comment]
lol my php f is some hours old ... you make me crazy me lol

**Comment by RobiNN1** [comment]
In the lastest commit were moved icons to the fonts folder.

**Comment by meangczac** [comment]
Catzenjaeger you work offline or online? lol

**Comment by Catzenjaeger** [comment]
online on a extra testsite .. younknow my url :)

**Comment by Catzenjaeger** [comment]
i have download the newest version and reupload the complete bootstrap folder -- icon not shown :(

**Comment by Catzenjaeger** [comment]
i have add aw but the result is worst. i guess it works not with some bootstrap components. Here i pic for show what i mean. Guess i have to use glyhos

```
// show carousel)
echo "<div id='myCarousel' class='carousel slide' data-ride='carousel' style='height: 400px !important; overflow: hidden;'>\n";
                  echo "<ol class='carousel-indicators'>\n";
                    echo $indicators;
                  echo "</ol>\n";
                  echo "<div class='carousel-inner' role='listbox'>\n";
                    echo $images;
                  echo "</div>\n";
                  if ($image_count > 1) {
                      echo "<a class='left carousel-control' href='#myCarousel' role='button' data-slide='prev'>\n";
                          echo "<span class='glyphicon glyphicon-chevron-left' aria-hidden='true'></span>\n";
                          echo "<span class='fa fa-backward' aria-hidden='true'></span>";
                          echo "<span class='sr-only'>Previous</span>\n";
                      echo "</a>\n";
                      echo "<a class='right carousel-control' href='#myCarousel' role='button' data-slide='next'>\n";
                         echo "<span class='glyphicon glyphicon-chevron-right' aria-hidden='true'></span>\n";
                          echo "<span class='fa fa-forward' aria-hidden='true'></span>";
                         echo "<span class='sr-only'>Next</span>\n";
                      echo "</a>\n";
                  }
                echo "</div>\n";
```

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18165798/9adbfc4c-7047-11e6-80c7-bae546cd3227.JPG)

**Comment by Catzenjaeger** [comment]
so, i have download the brand new files and the problem is NOT solved. 
All my glyphos not shown. Most i have replace with aw but someone works not. My slideshow as example (see other post) . Anyone can watch on it please?

**Comment by RobiNN1** [comment]
Open incognito mode and try to see if there will go

**Comment by RobiNN1** [comment]
Fixed
https://github.com/php-fusion/PHP-Fusion/blob/9e690dcfe962fc5ac57c247a604aad2dcf0d0d99/includes/bootstrap/bootstrap.min.css

**Comment by Catzenjaeger** [comment]
thx soved :) :+1:
