### ISSUE TITLE
Error log link dosent work

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#999]
look image:

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18129658/f321a0bc-6f8b-11e6-9f3f-fa1129d986f7.JPG)

**Comment by RobiNN1** [comment]
In classes PHPFusion/Errors.php
Line 572 find: 
`$html .= str_replace(array("[ERROR_LOG_URL]"),
                                 array(ADMIN."errors.php".$aidlink),
                               $locale['err_101']);`

replace to 
`$html .= str_replace(array("[ERROR_LOG_URL]", "[/ERROR_LOG_URL]"),
                                 array(
                                    "<a id='footer_debug' href='".ADMIN."errors.php".$aidlink."'>",
                                    "</a>"
                               ), $locale['err_101']);` 

Pull request https://github.com/php-fusion/PHP-Fusion/pull/996/files

**Comment by Catzenjaeger** [comment]
works thanx

**Comment by meangczac** [comment]
Already fix

**Comment by Catzenjaeger** [comment]
yup works thanx
